import { Medication, Category } from '../../../types';
import { enhanceAntipsychoticList } from './enhanceAntipsychotic';

const fixed = (text: string) => (_w: number, _a: number) => text;

const BASE_ANTIPSYCHOTIC_WARNINGS = [
	'قد يسبب نعاس/دوخة؛ تجنب القيادة في البداية.',
	'قد يسبب هبوط ضغط عند الوقوف (قم ببطء).',
	'قد يزيد الوزن/السكر/الدهون خاصة بعض الأنواع (متابعة دورية).',
	'قد يسبب أعراض خارج هرمية (تيبس/رعشة) خصوصاً الجرعات العالية أو الأدوية التقليدية.',
	'لا يوقف فجأة دون خطة سحب تدريجي.',
];

const QUETIAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب نعاس واضح؛ يفضل مساءً.',
	'قد يسبب جفاف فم/إمساك.',
];

const RISPERIDONE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع هرمون البرولاكتين (اضطراب دورة/إفرازات/تضخم ثدي).',
	'راقب أعراض خارج هرمية خصوصاً مع الجرعات الأعلى.',
];

const OLANZAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد الوزن/الشهية بشكل ملحوظ عند بعض المرضى.',
	'راقب السكر والدهون بشكل دوري.',
];

const ARIPIPRAZOLE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب أرق/تململ (Akathisia) عند بعض المرضى.',
	'عادة تأثيره أقل على الوزن مقارنة ببعض الأنواع (ليس دائماً).',
];

const HALOPERIDOL_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد خطر QT واضطراب نظم القلب (خاصة بالحقن/الجرعات العالية).',
	'يزيد خطر أعراض خارج هرمية/تيبس بشكل أوضح.',
];

const OLANZAPINE_FLUOXETINE_WARNINGS = [
	...OLANZAPINE_WARNINGS,
	'قد يسبب غثيان/صداع/اضطراب جنسي (بسبب فلوكسيتين).',
	'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.',
	'قد يزيد القلق/الأرق في البداية ثم يتحسن.',
];

const CHLORPROMAZINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب جفاف فم/إمساك/احتباس بول (تأثير مضاد كولين).',
	'قد يسبب حساسية للضوء (تجنب الشمس المباشرة).',
	'قد يسبب هبوط ضغط أو دوخة واضحة خصوصاً بالبداية.',
	'قد يطيل QT ويزيد اضطراب النظم؛ يُحذر مع أدوية تطيل QT.',
];

const PIMOZIDE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد خطر QT واضطراب نظم القلب؛ يُفضّل تقييم ECG وعوامل الخطورة.',
	'تجنب أدوية/مضادات حيوية تطيل QT (مثل الماكرولايد) أو مثبطات CYP3A4 القوية.',
	'قد يسبب أعراض خارج هرمية.',
];

const SULPIRIDE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع البرولاكتين.',
	'قد يسبب أعراض خارج هرمية، خصوصاً بجرعات أعلى.',
	'قد يطيل QT؛ يُحذر مع أدوية تطيل QT.',
];

const LURASIDONE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب تململ/أكاثيزيا أو غثيان.',
	'يجب تناوله مع وجبة (≥ 350 سعر حراري) لتحسين الامتصاص.',
	'تجنب مثبطات/محفزات CYP3A4 القوية (وتجنب الجريب فروت).',
];

const CARIPRAZINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب تململ/أكاثيزيا أو أرق.',
	'له نصف عمر طويل؛ أي تعديل جرعة يحتاج وقت لظهور أثره.',
	'راقب الأعراض خارج الهرمية والوزن.',
];

const TRIFLUOPERAZINE_WARNINGS = [
	...HALOPERIDOL_WARNINGS,
	'يزيد خطر خلل الحركة المتأخر مع الاستخدام الطويل (خصوصاً كبار السن).',
];

const ANTIPSYCHOTIC_DRUGS_PART_3_RAW: Medication[] = [
	// 116) neurazine 100 mg 20 tabs
	{
		id: 'neurazine-100-20-tabs-psy',
		name: 'neurazine 100 mg 20 tabs',
		genericName: 'chlorpromazine hydrochloride',
		concentration: '100mg',
		price: 46,
		matchKeywords: ['neurazine 100', 'chlorpromazine 100', 'largactil', 'neurozine', 'نيورازين', 'كلوربرومازين', 'ذهان', 'هياج', '#anti-psychotic'],
		usage: 'كلوربرومازين (مضاد ذهان تقليدي) للذهان/الهياج حسب التشخيص بجرعة محددة مع متابعة.',
		timing: 'كل ٨ ساعات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — كل ٨ ساعات — بدون اعتبار للأكل — مزمن.'),
		warnings: CHLORPROMAZINE_WARNINGS,
	},

	// 117) olazine 10mg 7 scored f.c.tab.
	{
		id: 'olazine-10-7-scored-tabs-psy',
		name: 'olazine 10mg 7 scored f.c.tab.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 35,
		matchKeywords: ['olazine 10', 'olanzapine 10', 'olazine', 'أولازين', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين مضاد ذهان غير نمطي للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Scored Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 118) orap forte 4mg 20 tab.
	{
		id: 'orap-forte-4-20-tabs-psy',
		name: 'orap forte 4mg 20 tab.',
		genericName: 'pimozide',
		concentration: '4mg',
		price: 180,
		matchKeywords: ['orap forte 4', 'pimozide 4', 'orap', 'tics', 'tourette', 'أوراب', 'بيموزيد', 'تيكس', 'توريت', '#anti-psychotic'],
		usage: 'بيموزيد (مضاد ذهان تقليدي) يُستخدم غالباً لاضطراب العرات/توريت في حالات مختارة حسب التشخيص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٢ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: PIMOZIDE_WARNINGS,
	},

	// 119) prexal 5 mg 30 caplets
	{
		id: 'prexal-5-30-caplets-psy',
		name: 'prexal 5 mg 30 caplets',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 230,
		matchKeywords: ['prexal 5', 'olanzapine 5', 'prexal', 'بريكسال', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 120) psychodal 1mg 30 f.c. tab.
	{
		id: 'psychodal-1-30-fc-tabs-psy',
		name: 'psychodal 1mg 30 f.c. tab.',
		genericName: 'risperidone',
		concentration: '1mg',
		price: 108,
		matchKeywords: ['psychodal 1 30', 'risperidone 1', 'psychodal', 'سايكودال ١', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 121) psychodal 2 mg 10 oral dis.tab.
	{
		id: 'psychodal-2-10-odt-psy',
		name: 'psychodal 2 mg 10 oral dis.tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 57,
		matchKeywords: ['psychodal 2 odt', 'risperidone 2 orodispersible', 'oral disintegrating', 'سايكودال ٢ فموي متحلل', '#anti-psychotic'],
		usage: 'ريسبيريدون أقراص تذوب بالفم (ODT) لضبط الجرعة أو عند صعوبة بلع الأقراص.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 122) psychodal 2mg 30 f.c.tab.
	{
		id: 'psychodal-2-30-fc-tabs-psy',
		name: 'psychodal 2mg 30 f.c.tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 171,
		matchKeywords: ['psychodal 2 30', 'risperidone 2', 'سايكودال ٢ ٣٠', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 123) psychodal 3mg 30 f.c.tab.
	{
		id: 'psychodal-3-30-fc-tabs-psy',
		name: 'psychodal 3mg 30 f.c.tab.',
		genericName: 'risperidone',
		concentration: '3mg',
		price: 198,
		matchKeywords: ['psychodal 3 30', 'risperidone 3', 'سايكودال ٣', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 124) psychodal 4mg 30 f.c. tab.
	{
		id: 'psychodal-4-30-fc-tabs-psy',
		name: 'psychodal 4mg 30 f.c. tab.',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 231,
		matchKeywords: ['psychodal 4 30', 'risperidone 4', 'سايكودال ٤', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 125) quitcool xr 150mg 10 ext. rel. f.c. tabs.
	{
		id: 'quitcool-xr-150-10-fc-tabs-psy',
		name: 'quitcool xr 150mg 10 ext. rel. f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '150mg',
		price: 50,
		matchKeywords: ['quitcool xr 150 10', 'quetiapine xr 150', 'كويت كول ممتد ١٥٠ ١٠', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 126) quitiadel 200 mg 10 f.c. tab.
	{
		id: 'quitiadel-200-10-fc-tabs-psy',
		name: 'quitiadel 200 mg 10 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 80,
		matchKeywords: ['quitiadel 200 10', 'quetiapine 200', 'كيوتيادل ٢٠٠ ١٠', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 127) raibyax 12/25 mg 30 caps.
	{
		id: 'raibyax-12-25-30-caps-psy-2',
		name: 'raibyax 12/25 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '12/25mg',
		price: 249,
		matchKeywords: ['raibyax 12/25', 'olanzapine fluoxetine 12/25', 'symbyax', 'رايباياكس ١٢/٢٥', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) لحالات مختارة بجرعة محددة مع متابعة (طبيب نفسي؛ راقب المزاج والوزن).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('12/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 128) raibyax 6/50 mg 30 caps.
	{
		id: 'raibyax-6-50-30-caps-psy',
		name: 'raibyax 6/50 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '6/50mg',
		price: 216,
		matchKeywords: ['raibyax 6/50', 'olanzapine fluoxetine 6/50', 'رايباياكس ٦/٥٠', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('6/50mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 129) schizofy 30mg 10 f.c. tab.
	{
		id: 'schizofy-30-10-fc-tabs-psy',
		name: 'schizofy 30mg 10 f.c. tab.',
		genericName: 'aripiprazole',
		concentration: '30mg',
		price: 106,
		matchKeywords: ['schizofy 30', 'aripiprazole 30', 'شيزوفي ٣٠', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة ٣٠ مجم - حد أعلى شائع) للفصام/ثنائي القطب حسب التشخيص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٣٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 130) topmode forte 200mg 10 tab.
	{
		id: 'topmode-forte-200-10-tabs-psy',
		name: 'topmode forte 200mg 10 tab.',
		genericName: 'sulpiride',
		concentration: '200mg',
		price: 16,
		matchKeywords: ['topmode forte 200', 'sulpiride 200', 'dogmatil 200', 'توبمود فورت', 'سلبيريد', '#anti-psychotic'],
		usage: 'سلبيريد (مشتق بنزاميد) لحالات مختارة حسب التشخيص.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٤٠٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: SULPIRIDE_WARNINGS,
	},

	// 131) tudasidone 40 mg 20 f.c. tabs
	{
		id: 'tudasidone-40-20-fc-tabs-psy',
		name: 'tudasidone 40 mg 20 f.c. tabs',
		genericName: 'lurasidone',
		concentration: '40mg',
		price: 238,
		matchKeywords: ['tudasidone 40', 'lurasidone 40', 'latuda', 'توداسيدون', 'لوراسيدون', '#anti-psychotic'],
		usage: 'لوراسيدون مضاد ذهان غير نمطي للفصام/اكتئاب ثنائي القطب حسب التشخيص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 156,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٤٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: LURASIDONE_WARNINGS,
	},

	// 132) elbaluran 20 mg 30 f.c. tabs.
	{
		id: 'elbaluran-20-30-fc-tabs-psy',
		name: 'elbaluran 20 mg 30 f.c. tabs.',
		genericName: 'lurasidone hcl',
		concentration: '20mg',
		price: 165,
		matchKeywords: ['elbaluran 20', 'lurasidone 20', 'elbaluran', 'إلبالوران', 'لوراسيدون', '#anti-psychotic'],
		usage: 'لوراسيدون (HCl) مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 156,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٤٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: LURASIDONE_WARNINGS,
	},

	// 133) elbaluran 40 mg 30 f.c. tabs.
	{
		id: 'elbaluran-40-30-fc-tabs-psy',
		name: 'elbaluran 40 mg 30 f.c. tabs.',
		genericName: 'lurasidone hcl',
		concentration: '40mg',
		price: 267,
		matchKeywords: ['elbaluran 40', 'lurasidone 40', 'إلبالوران ٤٠', '#anti-psychotic'],
		usage: 'لوراسيدون (HCl) مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 156,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: LURASIDONE_WARNINGS,
	},

	// 134) psycholanz 12/50 mg 30 caps.
	{
		id: 'psycholanz-12-50-30-caps-psy',
		name: 'psycholanz 12/50 mg 30 caps.',
		genericName: 'fluoxetine & olanzapine',
		concentration: '12/50mg',
		price: 201,
		matchKeywords: ['psycholanz 12/50', 'fluoxetine olanzapine 12/50', 'olanzapine fluoxetine 12/50', 'سايكولانز ١٢/٥٠', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) لحالات مختارة بجرعة محددة مع متابعة (طبيب نفسي؛ راقب المزاج والوزن).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('12/50mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 135) olazorix 10 mg 30 f.c.tabs.
	{
		id: 'olazorix-10-30-fc-tabs-psy',
		name: 'olazorix 10 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 201,
		matchKeywords: ['olazorix 10', 'olanzapine 10', 'أولازوريكس ١٠', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 136) aripiprex 30mg 30 f.c.tab.
	{
		id: 'aripiprex-30-30-fc-tabs-psy',
		name: 'aripiprex 30mg 30 f.c.tab.',
		genericName: 'aripiprazole',
		concentration: '30mg',
		price: 318,
		matchKeywords: ['aripiprex 30 30', 'aripiprazole 30', 'أريبيبريكس ٣٠ ٣٠', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة ٣٠ مجم - حد أعلى شائع).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٣٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 137) aripiprex 1mg/ml oral sol. 100 ml
	{
		id: 'aripiprex-1mgml-100ml-solution-psy',
		name: 'aripiprex 1mg/ml oral sol. 100 ml',
		genericName: 'aripiprazole',
		concentration: '1mg/ml',
		price: 44,
		matchKeywords: ['aripiprex solution 1mg/ml', 'aripiprazole solution 100ml', 'أريبيبريكس محلول', '#anti-psychotic'],
		usage: 'أريبيبرازول محلول فموي لضبط الجرعة.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (جرعة) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 138) quetiasu 300mg 30 tabs
	{
		id: 'quetiasu-300-30-tabs-psy',
		name: 'quetiasu 300mg 30 tabs',
		genericName: 'quetiapine fumarate',
		concentration: '300mg',
		price: 304.5,
		matchKeywords: ['quetiasu 300', 'quetiapine fumarate 300', 'quetiapine 300', 'كويتياسو ٣٠٠', '#anti-psychotic'],
		usage: 'كويتيابين (فومارات) IR للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 139) olazorix 20 mg 21 f.c.tabs.
	{
		id: 'olazorix-20-21-fc-tabs-psy',
		name: 'olazorix 20 mg 21 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '20mg',
		price: 198,
		matchKeywords: ['olazorix 20 21', 'olanzapine 20', 'أولازوريكس ٢٠', '#anti-psychotic'],
		usage: 'أولانزابين (جرعة ٢٠ مجم - حد أقصى شائع).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 140) quetiasu 100mg 30 tabs
	{
		id: 'quetiasu-100-30-tabs-psy',
		name: 'quetiasu 100mg 30 tabs',
		genericName: 'quetiapine',
		concentration: '100mg',
		price: 166.5,
		matchKeywords: ['quetiasu 100', 'quetiapine 100', 'كويتياسو ١٠٠', '#anti-psychotic'],
		usage: 'كويتيابين IR للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 141) seroquel 25mg 10 tab
	{
		id: 'seroquel-25-10-tabs-psy',
		name: 'seroquel 25mg 10 tab',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 44.5,
		matchKeywords: ['seroquel 25 10', 'quetiapine 25', 'سيروكويل ٢٥ ١٠', '#anti-psychotic'],
		usage: 'كويتيابين (جرعة تدرج) للفصام/ثنائي القطب.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 142) stellasil 1mg 30 tab.
	{
		id: 'stellasil-1-30-tabs-psy',
		name: 'stellasil 1mg 30 tab.',
		genericName: 'trifluoperazine',
		concentration: '1mg',
		price: 27,
		matchKeywords: ['stellasil 1', 'trifluoperazine 1', 'stelazine', 'ستيللاسيل ١', '#anti-psychotic'],
		usage: 'تريفلو بيرازين (تقليدي) للذهان/القلق الشديد في حالات مختارة حسب التشخيص.',
		timing: 'كل ٨ ساعات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢ مجم (قرص) — كل ٨ ساعات — بدون اعتبار للأكل — مزمن.'),
		warnings: TRIFLUOPERAZINE_WARNINGS,
	},

	// 143) zyprexa velotab 10 mg 28 orodisperdible tabs.
	{
		id: 'zyprexa-velotab-10-28-odt-psy',
		name: 'zyprexa velotab 10 mg 28 orodisperdible tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 1001,
		matchKeywords: ['zyprexa velotab 10', 'olanzapine orodispersible 10', 'zyprexa', 'velotab', 'زيبريكسا فيلوتاب', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين أقراص تذوب بالفم (Velotab/ODT) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 144) dogmatil 50mg 30 caps.
	{
		id: 'dogmatil-50-30-caps-psy',
		name: 'dogmatil 50mg 30 caps.',
		genericName: 'sulpiride',
		concentration: '50mg',
		price: 63,
		matchKeywords: ['dogmatil 50', 'sulpiride 50', 'دوجماتيل ٥٠', 'سلبيريد', '#anti-psychotic'],
		usage: 'سلبيريد (مشتق بنزاميد) لحالات مختارة حسب التشخيص.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١٥٠ مجم (كبسولة) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: SULPIRIDE_WARNINGS,
	},

	// 145) halonace 5mg/ml i.m./i.v.amp.
	{
		id: 'halonace-5mgml-im-iv-amp-psy',
		name: 'halonace 5mg/ml i.m./i.v.amp.',
		genericName: 'haloperidol',
		concentration: '5mg/ml',
		price: 7,
		matchKeywords: ['halonace 5mg/ml', 'haloperidol 5mg/ml', 'iv', 'im', 'acute agitation', 'هالوناس حقن', 'هالوبيريدول حقن', '#anti-psychotic'],
		usage: 'هالوبيريدول حقن IM/IV للحالات الحادة داخل منشأة طبية.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (حقنة) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 146) haloprol 5mg/ml i.m. 3 amp.
	{
		id: 'haloprol-5mgml-im-3-amp-psy',
		name: 'haloprol 5mg/ml i.m. 3 amp.',
		genericName: 'haloperidol',
		concentration: '5mg/ml',
		price: 39,
		matchKeywords: ['haloprol 5mg/ml', 'haloperidol im', 'هالوبرول', 'هالوبيريدول', '#anti-psychotic'],
		usage: 'هالوبيريدول حقن عضل للحالات الحادة داخل منشأة طبية.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (حقنة) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 147) brexpiprazole clavita pharma 2 mg 30 f.c.tabs.
	{
		id: 'brexpiprazole-clavita-2-30-fc-tabs-psy',
		name: 'brexpiprazole clavita pharma 2 mg 30 f.c.tabs.',
		genericName: 'brexpiprazole',
		concentration: '2mg',
		price: 216,
		matchKeywords: ['brexpiprazole clavita 2', 'brexpiprazole 2', 'rexulti', 'بريكسبيبرازول ٢', 'كلافيتا', '#anti-psychotic'],
		usage: 'بريكسبيبرازول مضاد ذهان غير نمطي (للفصام وقد يستخدم كمساعد للاكتئاب حسب التشخيص).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: [
			...BASE_ANTIPSYCHOTIC_WARNINGS,
			'قد يسبب تململ/أكاثيزيا أو أرق.',
			'قد يزيد الوزن عند بعض المرضى؛ راقب الوزن والسكر والدهون.',
			'قد يزيد خطر أفكار انتحارية لدى صغار السن مع اضطراب الاكتئاب (في صغار السن).',
		],
	},

	// 148) quetiasu 25mg 30 tabs
	{
		id: 'quetiasu-25-30-tabs-psy',
		name: 'quetiasu 25mg 30 tabs',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 63,
		matchKeywords: ['quetiasu 25', 'quetiapine 25', 'كويتياسو ٢٥', '#anti-psychotic'],
		usage: 'كويتيابين IR جرعة صغيرة للتدرج.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 149) elbaluran 120 mg 30 f.c. tabs.
	{
		id: 'elbaluran-120-30-fc-tabs-psy',
		name: 'elbaluran 120 mg 30 f.c. tabs.',
		genericName: 'lurasidone hcl',
		concentration: '120mg',
		price: 580.5,
		matchKeywords: ['elbaluran 120', 'lurasidone 120', 'إلبالوران ١٢٠', '#anti-psychotic'],
		usage: 'لوراسيدون (HCl) جرعة ١٢٠ مجم ضمن الجرعات المتوسطة/العالية حسب التشخيص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 156,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: LURASIDONE_WARNINGS,
	},

	// 150) elbaluran 60 mg 30 f.c. tabs.
	{
		id: 'elbaluran-60-30-fc-tabs-psy',
		name: 'elbaluran 60 mg 30 f.c. tabs.',
		genericName: 'lurasidone hcl',
		concentration: '60mg',
		price: 354,
		matchKeywords: ['elbaluran 60', 'lurasidone 60', 'إلبالوران ٦٠', '#anti-psychotic'],
		usage: 'لوراسيدون (HCl) مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 156,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: LURASIDONE_WARNINGS,
	},

	// 151) elbaluran 80 mg 30 f.c. tabs.
	{
		id: 'elbaluran-80-30-fc-tabs-psy',
		name: 'elbaluran 80 mg 30 f.c. tabs.',
		genericName: 'lurasidone hcl',
		concentration: '80mg',
		price: 447,
		matchKeywords: ['elbaluran 80', 'lurasidone 80', 'إلبالوران ٨٠', '#anti-psychotic'],
		usage: 'لوراسيدون (HCl) مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 156,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: LURASIDONE_WARNINGS,
	},

	// 152) quebolm 25 mg 20 f.c. tabs.
	{
		id: 'quebolm-25-20-fc-tabs-psy',
		name: 'quebolm 25 mg 20 f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 58,
		matchKeywords: ['quebolm 25', 'quetiapine 25', 'كيبولم', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين IR جرعة صغيرة للتدرج.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 153) reagila 6 mg 28 caps.
	{
		id: 'reagila-6-28-caps-psy',
		name: 'reagila 6 mg 28 caps.',
		genericName: 'cariprazine',
		concentration: '6mg',
		price: 891,
		matchKeywords: ['reagila 6', 'cariprazine 6', 'vraylar', 'رياجيلا', 'كاربرازين', '#anti-psychotic'],
		usage: 'كاريبرازين مضاد ذهان غير نمطي للفصام/ثنائي القطب حسب التشخيص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٫٥ مجم (كبسولة) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: CARIPRAZINE_WARNINGS,
	},

	// 154) olazorix 5 mg 30 f.c.tabs.
	{
		id: 'olazorix-5-30-fc-tabs-psy',
		name: 'olazorix 5 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 123,
		matchKeywords: ['olazorix 5', 'olanzapine 5', 'أولازوريكس ٥', '#anti-psychotic'],
		usage: 'أولانزابين مضاد ذهان غير نمطي.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 155) olazorix 20 mg 7 f.c.tabs.
	{
		id: 'olazorix-20-7-fc-tabs-psy',
		name: 'olazorix 20 mg 7 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '20mg',
		price: 66,
		matchKeywords: ['olazorix 20 7', 'olanzapine 20', 'أولازوريكس ٢٠ ٧', '#anti-psychotic'],
		usage: 'أولانزابين (جرعة ٢٠ مجم - حد أقصى شائع) عبوة صغيرة.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},
];

export const ANTIPSYCHOTIC_DRUGS_PART_3: Medication[] = enhanceAntipsychoticList(ANTIPSYCHOTIC_DRUGS_PART_3_RAW);

