import { Medication, Category } from '../../../types';
import { enhanceAntipsychoticList } from './enhanceAntipsychotic';

const fixed = (text: string) => (_w: number, _a: number) => text;

const BASE_ANTIPSYCHOTIC_WARNINGS = [
	'قد يسبب نعاس/دوخة؛ تجنب القيادة في البداية.',
	'قد يسبب هبوط ضغط عند الوقوف (قم ببطء).',
	'قد يزيد الوزن/السكر/الدهون خاصة بعض الأنواع (متابعة دورية).',
	'قد يسبب أعراض خارج هرمية (تيبس/رعشة) خصوصاً الجرعات العالية أو الأدوية التقليدية.',
	'لا يوقف فجأة دون خطة سحب تدريجي.',
];

const QUETIAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب نعاس واضح؛ يفضل مساءً.',
	'قد يسبب جفاف فم/إمساك.',
];

const RISPERIDONE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع هرمون البرولاكتين (اضطراب دورة/إفرازات/تضخم ثدي).',
	'راقب أعراض خارج هرمية خصوصاً مع الجرعات الأعلى.',
];

const OLANZAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد الوزن/الشهية بشكل ملحوظ عند بعض المرضى.',
	'راقب السكر والدهون بشكل دوري.',
];

const ARIPIPRAZOLE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب أرق/تململ (Akathisia) عند بعض المرضى.',
	'عادة تأثيره أقل على الوزن مقارنة ببعض الأنواع (ليس دائماً).',
];

const HALOPERIDOL_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد خطر QT واضطراب نظم القلب (خاصة بالحقن/الجرعات العالية).',
	'يزيد خطر أعراض خارج هرمية/تيبس بشكل أوضح.',
];

const AMISULPRIDE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع البرولاكتين.',
	'قد يطيل QT؛ يُحذر مع أدوية تطيل QT.',
];

const OLANZAPINE_FLUOXETINE_WARNINGS = [
	...OLANZAPINE_WARNINGS,
	'قد يسبب غثيان/صداع/اضطراب جنسي (بسبب فلوكسيتين).',
	'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.',
	'قد يزيد القلق/الأرق في البداية ثم يتحسن.',
];

const BREXPIPRAZOLE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب تململ/أكاثيزيا أو أرق.',
	'قد يزيد الوزن عند بعض المرضى؛ راقب الوزن والسكر والدهون.',
	'قد يزيد خطر أفكار انتحارية لدى صغار السن مع اضطراب الاكتئاب (في صغار السن).',
];

const PALIPERIDONE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع البرولاكتين.',
	'قد يطيل QT؛ يُحذر مع أدوية تطيل QT.',
	'قد يسبب أعراض خارج هرمية عند بعض المرضى.',
];

const TRIFLUOPERAZINE_WARNINGS = [
	...HALOPERIDOL_WARNINGS,
	'يزيد خطر خلل الحركة المتأخر مع الاستخدام الطويل (خصوصاً كبار السن).',
];

const SULPIRIDE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع البرولاكتين.',
	'قد يسبب أعراض خارج هرمية، خصوصاً بجرعات أعلى.',
	'قد يطيل QT؛ يُحذر مع أدوية تطيل QT.',
];

const ANTIPSYCHOTIC_DRUGS_PART_2_RAW: Medication[] = [
	// 66) quitiadel 25 mg 30 f.c. tab.
	{
		id: 'quitiadel-25-30-fc-tabs-psy',
		name: 'quitiadel 25 mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 57,
		matchKeywords: ['quitiadel 25', 'quetiapine 25', 'quitiadel', 'كيوتيادل ٢٥', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للتدرج في بداية العلاج أو للوصول لجرعة علاجية أعلى حسب الحالة.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 67) riscure 2mg 30 f.c. tab.
	{
		id: 'riscure-2-30-fc-tabs-psy',
		name: 'riscure 2mg 30 f.c. tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 109.5,
		matchKeywords: ['riscure 2 30', 'risperidone 2', 'riscure', 'ريسكير ٢ ٣٠', 'ريسبيريدون', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي للفصام/الذهان وبعض الاضطرابات السلوكية حسب التشخيص.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 68) rispadex 3mg 30 f.c.tab
	{
		id: 'rispadex-3-30-fc-tabs-psy',
		name: 'rispadex 3mg 30 f.c.tab',
		genericName: 'risperidone',
		concentration: '3mg',
		price: 51,
		matchKeywords: ['rispadex 3', 'risperidone 3', 'rispadex', 'ريسباديكس ٣', 'ريسبيريدون', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 69) seroquel 200mg 10 tab
	{
		id: 'seroquel-200-10-tabs-psy',
		name: 'seroquel 200mg 10 tab',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 143,
		matchKeywords: ['seroquel 200 10', 'seroquel 200', 'quetiapine 200', 'سيروكويل ٢٠٠ ١٠', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (الاسم التجاري) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 70) spiraquet 100mg 20 f.c. tab.
	{
		id: 'spiraquet-100-20-fc-tabs-psy',
		name: 'spiraquet 100mg 20 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '100mg',
		price: 70,
		matchKeywords: ['spiraquet 100', 'quetiapine 100', 'سبيراكت', 'سبيراكويت', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 71) spiraquet 200 mg 20 f.c.tabs.
	{
		id: 'spiraquet-200-20-fc-tabs-psy',
		name: 'spiraquet 200 mg 20 f.c.tabs.',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 148,
		matchKeywords: ['spiraquet 200', 'quetiapine 200', 'سبيراكويت ٢٠٠', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 72) topmode 50mg 30 caps.
	{
		id: 'topmode-50-30-caps-psy',
		name: 'topmode 50mg 30 caps.',
		genericName: 'sulpiride',
		concentration: '50mg',
		price: 30,
		matchKeywords: ['topmode 50', 'sulpiride 50', 'dogmatil', 'توبمود', 'سلبيريد', '#anti-psychotic'],
		usage: 'سلبيريد (مشتق بنزاميد) قد يُستخدم لبعض الاضطرابات النفسية أو أعراض وظيفية حسب التشخيص.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١٥٠ مجم (كبسولة) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: SULPIRIDE_WARNINGS,
	},

	// 73) bioprex 2.5 mg 30 f.c.tabs.
	{
		id: 'bioprex-2-5-30-fc-tabs-psy',
		name: 'bioprex 2.5 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '2.5mg',
		price: 123,
		matchKeywords: ['bioprex 2.5', 'olanzapine 2.5', 'بيوبريكس ٢٫٥', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين مضاد ذهان غير نمطي (جرعة صغيرة للتدرج).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 74) bioprex 5 mg 30 f.c.tabs.
	{
		id: 'bioprex-5-30-fc-tabs-psy-2',
		name: 'bioprex 5 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 123,
		matchKeywords: ['bioprex 5', 'olanzapine 5', 'بيوبريكس ٥', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين مضاد ذهان غير نمطي.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 75) lanzapine 10mg 21 f.c. tab.
	{
		id: 'lanzapine-10-21-fc-tabs-psy',
		name: 'lanzapine 10mg 21 f.c. tab.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 210,
		matchKeywords: ['lanzapine 10 21', 'olanzapine 10', 'لانزابين ٢١', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 76) neopression 2mg 20 f.c.tabs.
	{
		id: 'neopression-2-20-fc-tabs-psy',
		name: 'neopression 2mg 20 f.c.tabs.',
		genericName: 'brexpiprazole',
		concentration: '2mg',
		price: 130,
		matchKeywords: ['neopression 2', 'brexpiprazole 2', 'rexulti', 'نيوبرشن', 'بريكسبيبرازول', '#anti-psychotic'],
		usage: 'بريكسبيبرازول مضاد ذهان غير نمطي (يستخدم للفصام وقد يستخدم كمُساعد للاكتئاب حسب التشخيص).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: BREXPIPRAZOLE_WARNINGS,
	},

	// 77) psycholanz 12/25 mg 30 caps.
	{
		id: 'psycholanz-12-25-30-caps-psy',
		name: 'psycholanz 12/25 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '12/25mg',
		price: 201,
		matchKeywords: ['psycholanz 12/25', 'olanzapine fluoxetine 12/25', 'symbyax', 'bipolar depression', 'سايكولانز ١٢/٢٥', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) لحالات مختارة (مثل اكتئاب ثنائي القطب) بجرعة محددة مع متابعة (طبيب نفسي؛ راقب المزاج والوزن).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('12/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 78) spiraquet 25 mg 20 f.c.tabs.
	{
		id: 'spiraquet-25-20-fc-tabs-psy',
		name: 'spiraquet 25 mg 20 f.c.tabs.',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 26.5,
		matchKeywords: ['spiraquet 25', 'quetiapine 25', 'سبيراكويت ٢٥', '#anti-psychotic'],
		usage: 'كويتيابين (IR) جرعة صغيرة للتدرج.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 79) psycholanz 3/25 mg 30 caps.
	{
		id: 'psycholanz-3-25-30-caps-psy',
		name: 'psycholanz 3/25 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '3/25mg',
		price: 117,
		matchKeywords: ['psycholanz 3/25', 'olanzapine fluoxetine 3/25', 'symbyax', 'سايكولانز ٣/٢٥', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) بجرعات معتمدة.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('3/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 80) neopression 1 mg 10 f.c.tabs.
	{
		id: 'neopression-1-10-fc-tabs-psy',
		name: 'neopression 1 mg 10 f.c.tabs.',
		genericName: 'brexpiprazole',
		concentration: '1mg',
		price: 65,
		matchKeywords: ['neopression 1', 'brexpiprazole 1', 'rexulti 1', 'نيوبرشن ١', '#anti-psychotic'],
		usage: 'بريكسبيبرازول مضاد ذهان غير نمطي (جرعة بدء شائعة).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: BREXPIPRAZOLE_WARNINGS,
	},

	// 81) quitcool xr 150mg 30 ext. rel. f.c. tabs.
	{
		id: 'quitcool-xr-150-30-fc-tabs-psy-2',
		name: 'quitcool xr 150mg 30 ext. rel. f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '150mg',
		price: 243,
		matchKeywords: ['quitcool xr 150', 'quetiapine xr 150', 'كويت كول ممتد ١٥٠', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 82) quitcool xr 400mg 30 ext. rel. f.c. tabs.
	{
		id: 'quitcool-xr-400-30-fc-tabs-psy-2',
		name: 'quitcool xr 400mg 30 ext. rel. f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '400mg',
		price: 387,
		matchKeywords: ['quitcool xr 400', 'quetiapine xr 400', 'كويت كول ممتد ٤٠٠', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 83) abilify 10 mg 10 discmelt orally dis.tabs.
	{
		id: 'abilify-10-10-discmelt-odt-psy',
		name: 'abilify 10 mg 10 discmelt orally dis.tabs.',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 190,
		matchKeywords: ['abilify 10 discmelt', 'aripiprazole 10 odt', 'orally disintegrating', 'ابيليفاي ديسكميلت', 'أريبيبرازول ١٠', '#anti-psychotic'],
		usage: 'أريبيبرازول أقراص تذوب بالفم (ODT) للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 84) abilify 10 mg 10 tabs.
	{
		id: 'abilify-10-10-tabs-psy',
		name: 'abilify 10 mg 10 tabs.',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 220.5,
		matchKeywords: ['abilify 10 10', 'aripiprazole 10', 'abilify', 'ابيليفاي ١٠', '#anti-psychotic'],
		usage: 'أريبيبرازول مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 85) abilify 15 mg 10 discmelt orally dis.tabs.
	{
		id: 'abilify-15-10-discmelt-odt-psy',
		name: 'abilify 15 mg 10 discmelt orally dis.tabs.',
		genericName: 'aripiprazole',
		concentration: '15mg',
		price: 330.5,
		matchKeywords: ['abilify 15 discmelt', 'aripiprazole 15 odt', 'orally disintegrating', 'ابيليفاي ١٥ ديسكميلت', '#anti-psychotic'],
		usage: 'أريبيبرازول ODT (جرعة ١٥ مجم شائعة).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٥ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 86) abilify 15 mg 10 tabs.
	{
		id: 'abilify-15-10-tabs-psy',
		name: 'abilify 15 mg 10 tabs.',
		genericName: 'aripiprazole',
		concentration: '15mg',
		price: 330.5,
		matchKeywords: ['abilify 15 10', 'aripiprazole 15', 'ابيليفاي ١٥', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة ١٥ مجم شائعة).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٥ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 87) abilify 5 mg 10 tabs.
	{
		id: 'abilify-5-10-tabs-psy',
		name: 'abilify 5 mg 10 tabs.',
		genericName: 'aripiprazole',
		concentration: '5mg',
		price: 134.5,
		matchKeywords: ['abilify 5 10', 'aripiprazole 5', 'ابيليفاي ٥', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة صغيرة للتدرج).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 88) apexidone 1mg/ml syrup 100 ml
	{
		id: 'apexidone-1mgml-100ml-syr-psy',
		name: 'apexidone 1mg/ml syrup 100 ml',
		genericName: 'risperidone',
		concentration: '1mg/ml',
		price: 60,
		matchKeywords: ['apexidone syrup', 'risperidone syrup 1mg/ml', 'أبيكسيدون شراب', 'ريسبيريدون شراب', '#anti-psychotic'],
		usage: 'ريسبيريدون شراب (مناسب لضبط الجرعة خصوصاً للأطفال).',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Syrup',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (شراب) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 89) aripiprazole 1mg/ml oral sol. 120 ml
	{
		id: 'aripiprazole-1mgml-120ml-solution-psy',
		name: 'aripiprazole 1mg/ml oral sol. 120 ml',
		genericName: 'aripiprazole',
		concentration: '1mg/ml',
		price: 46,
		matchKeywords: ['aripiprazole solution 1mg/ml', 'aripiprazole oral solution', 'abilify solution', 'أريبيبرازول محلول', '#anti-psychotic'],
		usage: 'أريبيبرازول محلول فموي لضبط الجرعة عند صعوبة بلع الأقراص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (جرعة) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 90) quitiadel 200 mg 30 f.c. tab.
	{
		id: 'quitiadel-200-30-fc-tabs-psy',
		name: 'quitiadel 200 mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 240,
		matchKeywords: ['quitiadel 200', 'quetiapine 200', 'كيوتيادل ٢٠٠', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 91) clozapine 25mg 30 tab.
	{
		id: 'clozapine-25-30-tabs-psy',
		name: 'clozapine 25mg 30 tab.',
		genericName: 'clozapine',
		concentration: '25mg',
		price: 36,
		matchKeywords: ['clozapine 25 30', 'clozaril', 'كلوزابين ٢٥', 'فصام مقاوم', '#anti-psychotic'],
		usage: 'كلوزابين للفصام المقاوم للعلاج (يلزم متابعة صورة دم منتظمة).',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: [
			...BASE_ANTIPSYCHOTIC_WARNINGS,
			'يلزم متابعة صورة دم (ANC/WBC) بانتظام بسبب خطر نقص العدلات.',
			'قد يسبب زيادة لعاب/إمساك شديد؛ عالج الإمساك مبكراً.',
			'يُحذر من التهاب عضلة القلب/خفقان/ألم صدر—اطلب تقييم عاجل.',
		],
	},

	// 92) haloperidol retard 100mg/ml i.m. amp.
	{
		id: 'haloperidol-retard-100mgml-im-amp-psy',
		name: 'haloperidol retard 100mg/ml i.m. amp.',
		genericName: 'haloperidol',
		concentration: '100mg/ml',
		price: 19.2,
		matchKeywords: ['haloperidol retard 100mg/ml', 'haldol decanoate 100', 'depot', 'long acting', 'هالوبيريدول ديبوت ١٠٠', '#anti-psychotic'],
		usage: 'هالوبيريدول ديبوت (طويل المفعول) للحقن العضلي العميق بجرعة محددة في العيادة/منشأة صحية مع متابعة (حقن عميق؛ متابعة QT).',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠٠ مجم (حقنة) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 93) invega 6mg 7 extended release tabs
	{
		id: 'invega-6-7-extended-release-tabs-psy',
		name: 'invega 6mg 7 extended release tabs',
		genericName: 'paliperidone',
		concentration: '6mg',
		price: 300,
		matchKeywords: ['invega 6 7', 'paliperidone 6', 'extended release', 'er', 'إنفيجا', 'باليبيريدون', '#anti-psychotic'],
		usage: 'باليبيريدون ممتد المفعول (ER) للفصام/الاضطراب الفصامي العاطفي حسب التشخيص.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: PALIPERIDONE_WARNINGS,
	},

	// 94) risdal 4mg 20 f.c. tab.
	{
		id: 'risdal-4-20-fc-tabs-psy',
		name: 'risdal 4mg 20 f.c. tab.',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 80,
		matchKeywords: ['risdal 4', 'risperidone 4', 'ريسدال', 'ريسبيريدون', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 95) risperdal 2mg 20 f.c. tab.
	{
		id: 'risperdal-2-20-fc-tabs-psy',
		name: 'risperdal 2mg 20 f.c. tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 190,
		matchKeywords: ['risperdal 2 20', 'risperidone 2', 'risperdal', 'ريسبردال ٢', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 96) risperdal 4mg 20 tabs.
	{
		id: 'risperdal-4-20-tabs-psy',
		name: 'risperdal 4mg 20 tabs.',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 374,
		matchKeywords: ['risperdal 4 20', 'risperidone 4', 'ريسبردال ٤', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 97) schizofy 10mg 20 scored f.c.tab.
	{
		id: 'schizofy-10-20-scored-fc-tabs-psy',
		name: 'schizofy 10mg 20 scored f.c.tab.',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 114,
		matchKeywords: ['schizofy 10', 'aripiprazole 10', 'schizofy', 'شيزوفي', 'أريبيبرازول', '#anti-psychotic'],
		usage: 'أريبيبرازول أقراص مقسمة/مخددة لتسهيل ضبط الجرعة.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Scored Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 98) seroquel 100mg 10 tab
	{
		id: 'seroquel-100-10-tabs-psy',
		name: 'seroquel 100mg 10 tab',
		genericName: 'quetiapine',
		concentration: '100mg',
		price: 116.5,
		matchKeywords: ['seroquel 100 10', 'quetiapine 100', 'سيروكويل ١٠٠ ١٠', '#anti-psychotic'],
		usage: 'كويتيابين (الاسم التجاري) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 99) seroquel 100mg 30 tab
	{
		id: 'seroquel-100-30-tabs-psy',
		name: 'seroquel 100mg 30 tab',
		genericName: 'quetiapine',
		concentration: '100mg',
		price: 349.5,
		matchKeywords: ['seroquel 100 30', 'quetiapine 100', 'سيروكويل ١٠٠ ٣٠', '#anti-psychotic'],
		usage: 'كويتيابين (الاسم التجاري) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 100) stellasil 5 mg 30 tab.
	{
		id: 'stellasil-5-30-tabs-psy',
		name: 'stellasil 5 mg 30 tab.',
		genericName: 'trifluoperazine',
		concentration: '5mg',
		price: 33,
		matchKeywords: ['stellasil 5', 'trifluoperazine 5', 'stelazine', 'ستيللاسيل', 'تريفلو بيرازين', 'ذهان', '#anti-psychotic'],
		usage: 'تريفلو بيرازين (مضاد ذهان تقليدي) للذهان/الهياج حسب التشخيص.',
		timing: 'كل ٨ ساعات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (قرص) — كل ٨ ساعات — بدون اعتبار للأكل — مزمن.'),
		warnings: TRIFLUOPERAZINE_WARNINGS,
	},

	// 101) raibyax 12/50 mg 30 caps.
	{
		id: 'raibyax-12-50-30-caps-psy',
		name: 'raibyax 12/50 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '12/50mg',
		price: 306,
		matchKeywords: ['raibyax 12/50', 'olanzapine fluoxetine 12/50', 'symbyax', 'رايباياكس', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) لحالات مختارة بجرعة محددة مع متابعة (طبيب نفسي؛ راقب المزاج والوزن).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('12/50mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 102) raibyax 6/25 mg 30 caps.
	{
		id: 'raibyax-6-25-30-caps-psy',
		name: 'raibyax 6/25 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '6/25mg',
		price: 174,
		matchKeywords: ['raibyax 6/25', 'olanzapine fluoxetine 6/25', 'رايباياكس ٦/٢٥', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('6/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 103) ranxapin 5mg 14 tabs
	{
		id: 'ranxapin-5-14-tabs-psy',
		name: 'ranxapin 5mg 14 tabs',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 77,
		matchKeywords: ['ranxapin 5 14', 'olanzapine 5', 'رانكسابين ٥', '#anti-psychotic'],
		usage: 'أولانزابين مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 104) amipride 200mg 30 tab
	{
		id: 'amipride-200-30-tabs-psy',
		name: 'amipride 200mg 30 tab',
		genericName: 'amisulpride',
		concentration: '200mg',
		price: 243,
		matchKeywords: ['amipride 200 30', 'amisulpride 200', 'أميبرايد ٢٠٠', '#anti-psychotic'],
		usage: 'أميسولبرايد مضاد ذهان للفصام.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: AMISULPRIDE_WARNINGS,
	},

	// 105) ranxapin 5mg 21 tabs
	{
		id: 'ranxapin-5-21-tabs-psy',
		name: 'ranxapin 5mg 21 tabs',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 115.5,
		matchKeywords: ['ranxapin 5 21', 'olanzapine 5', 'رانكسابين ٥ ٢١', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 106) apilipex 10 mg 30 f.c.tab.
	{
		id: 'apilipex-10-30-fc-tabs-psy',
		name: 'apilipex 10 mg 30 f.c.tab.',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 90,
		matchKeywords: ['apilipex 10', 'aripiprazole 10', 'أبيليبيكس', 'أريبيبرازول', '#anti-psychotic'],
		usage: 'أريبيبرازول مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 107) aripiprazole 5 mg 30 f.c. tablets
	{
		id: 'aripiprazole-5-30-fc-tabs-psy',
		name: 'aripiprazole 5 mg 30 f.c. tablets',
		genericName: 'aripiprazole',
		concentration: '5mg',
		price: 96,
		matchKeywords: ['aripiprazole 5 30', 'abilify 5', 'أريبيبرازول ٥ ٣٠', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة صغيرة للتدرج).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 108) aripiprex 30mg 20 f.c.tab.
	{
		id: 'aripiprex-30-20-fc-tabs-psy',
		name: 'aripiprex 30mg 20 f.c.tab.',
		genericName: 'aripiprazole',
		concentration: '30mg',
		price: 160,
		matchKeywords: ['aripiprex 30 20', 'aripiprazole 30', 'أريبيبريكس ٣٠', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة ٣٠ مجم - حد أعلى شائع).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٣٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 109) brexpiprazole clavita pharma 1 mg 30 f.c.tabs.
	{
		id: 'brexpiprazole-clavita-1-30-fc-tabs-psy',
		name: 'brexpiprazole clavita pharma 1 mg 30 f.c.tabs.',
		genericName: 'brexpiprazole',
		concentration: '1mg',
		price: 216,
		matchKeywords: ['brexpiprazole clavita 1', 'brexpiprazole 1', 'rexulti', 'بريكسبيبرازول', 'كلافيتا', '#anti-psychotic'],
		usage: 'بريكسبيبرازول مضاد ذهان غير نمطي (للفصام وقد يستخدم كمساعد للاكتئاب حسب التشخيص).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: BREXPIPRAZOLE_WARNINGS,
	},

	// 110) flunzapine 12/25 mg 20 caps.
	{
		id: 'flunzapine-12-25-20-caps-psy',
		name: 'flunzapine 12/25 mg 20 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '12/25mg',
		price: 174,
		matchKeywords: ['flunzapine 12/25', 'olanzapine fluoxetine 12/25', 'فلونزابين', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) بجرعات معتمدة.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('12/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 111) flunzapine 12/50 mg 20 capsules
	{
		id: 'flunzapine-12-50-20-caps-psy',
		name: 'flunzapine 12/50 mg 20 capsules',
		genericName: 'olanzapine & fluoxetine',
		concentration: '12/50mg',
		price: 200,
		matchKeywords: ['flunzapine 12/50', 'olanzapine fluoxetine 12/50', 'فلونزابين ١٢/٥٠', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) بجرعات معتمدة.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('12/50mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 112) flunzapine 6/25 mg 20 capsulses
	{
		id: 'flunzapine-6-25-20-caps-psy',
		name: 'flunzapine 6/25 mg 20 capsulses',
		genericName: 'olanzapine & fluoxetine',
		concentration: '6/25mg',
		price: 122,
		matchKeywords: ['flunzapine 6/25', 'olanzapine fluoxetine 6/25', 'فلونزابين ٦/٢٥', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('6/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 113) flunzapine 6/50 mg 20 caps.
	{
		id: 'flunzapine-6-50-20-caps-psy',
		name: 'flunzapine 6/50 mg 20 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '6/50mg',
		price: 144,
		matchKeywords: ['flunzapine 6/50', 'olanzapine fluoxetine 6/50', 'فلونزابين ٦/٥٠', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('6/50mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 114) bioprex 10 mg 30 f.c.tabs.
	{
		id: 'bioprex-10-30-fc-tabs-psy',
		name: 'bioprex 10 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 195,
		matchKeywords: ['bioprex 10', 'olanzapine 10', 'بيوبريكس ١٠', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 115) integrol 5 mg 30 f.c. tabs.
	{
		id: 'integrol-5-30-fc-tabs-psy',
		name: 'integrol 5 mg 30 f.c. tabs.',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 77.25,
		matchKeywords: ['integrol 5', 'olanzapine 5', 'انتجرول ٥', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},
];

export const ANTIPSYCHOTIC_DRUGS_PART_2: Medication[] = enhanceAntipsychoticList(ANTIPSYCHOTIC_DRUGS_PART_2_RAW);

