
import { Medication, Category } from '../../../types';
import { ANTIPSYCHOTIC_DRUGS_PART_2 } from './antipsychotic_2';
import { ANTIPSYCHOTIC_DRUGS_PART_3 } from './antipsychotic_3';
import { enhanceAntipsychoticList } from './enhanceAntipsychotic';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const fixed = (text: string) => (_w: number, _a: number) => text;


const BASE_ANTIPSYCHOTIC_WARNINGS = [
	'قد يسبب نعاس/دوخة؛ تجنب القيادة في البداية.',
	'قد يسبب هبوط ضغط عند الوقوف (قم ببطء).',
	'قد يزيد الوزن/السكر/الدهون خاصة بعض الأنواع (متابعة دورية).',
	'قد يسبب أعراض خارج هرمية (تيبس/رعشة) خصوصاً الجرعات العالية أو الأدوية التقليدية.',
	'لا يوقف فجأة دون خطة سحب تدريجي.',
];

const QUETIAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب نعاس واضح؛ يفضل مساءً.',
	'قد يسبب جفاف فم/إمساك.',
];

const RISPERIDONE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع هرمون البرولاكتين (اضطراب دورة/إفرازات/تضخم ثدي).',
	'راقب أعراض خارج هرمية خصوصاً مع الجرعات الأعلى.',
];

const OLANZAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد الوزن/الشهية بشكل ملحوظ عند بعض المرضى.',
	'راقب السكر والدهون بشكل دوري.',
];

const ARIPIPRAZOLE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يسبب أرق/تململ (Akathisia) عند بعض المرضى.',
	'عادة تأثيره أقل على الوزن مقارنة ببعض الأنواع (ليس دائماً).',
];

const CLOZAPINE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يلزم متابعة صورة دم (ANC/WBC) بانتظام بسبب خطر نقص العدلات.',
	'قد يسبب زيادة لعاب/إمساك شديد؛ عالج الإمساك مبكراً.',
	'يُحذر من التهاب عضلة القلب/خفقان/ألم صدر—اطلب تقييم عاجل.',
];

const HALOPERIDOL_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'يزيد خطر QT واضطراب نظم القلب (خاصة بالحقن/الجرعات العالية).',
	'يزيد خطر أعراض خارج هرمية/تيبس بشكل أوضح.',
];

const AMISULPRIDE_WARNINGS = [
	...BASE_ANTIPSYCHOTIC_WARNINGS,
	'قد يرفع البرولاكتين.',
	'قد يطيل QT؛ يُحذر مع أدوية تطيل QT.',
];

const OLANZAPINE_FLUOXETINE_WARNINGS = [
	...OLANZAPINE_WARNINGS,
	'قد يسبب غثيان/صداع/اضطراب جنسي (بسبب فلوكسيتين).',
	'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.',
	'قد يزيد القلق/الأرق في البداية ثم يتحسن.',
];

const ANTIPSYCHOTIC_DRUGS_PART_1_RAW: Medication[] = [
	// 1) quitapex 150mg 30 f.c. tab.
	{
		id: 'quitapex-150-30-fc-tabs-psy',
		name: 'quitapex 150mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '150mg',
		price: 201,
		matchKeywords: ['quitapex 150', 'quitapex', 'quetiapine 150', 'seroquel', 'schizophrenia', 'bipolar', 'mania', 'psychosis', 'كيوتابكس', 'كويتيابين', 'ذهان', 'فصام', 'ثنائي القطب', '#anti-psychotic'],
		usage: 'كويتيابين (مضاد ذهان غير نمطي) للفصام/الاضطراب ثنائي القطب حسب التشخيص.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 2) quitapex 50mg 30 f.c. tab.
	{
		id: 'quitapex-50-30-fc-tabs-psy',
		name: 'quitapex 50mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '50mg',
		price: 111,
		matchKeywords: ['quitapex 50', 'quetiapine 50', 'seroquel', 'sleep', 'anxiety', 'bipolar', 'كيوتابكس ٥٠', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين للفصام/ثنائي القطب؛ بجرعات صغيرة للأرق: أقل جرعة وأقصر مدة مع متابعة.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 3) quitapex 100mg 30 f.c. tab.
	{
		id: 'quitapex-100-30-fc-tabs-psy',
		name: 'quitapex 100mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '100mg',
		price: 186,
		matchKeywords: ['quitapex 100', 'quetiapine 100', 'seroquel', 'schizophrenia', 'bipolar', 'كيوتابكس ١٠٠', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 4) quitapex 200mg 30 f.c.tab.
	{
		id: 'quitapex-200-30-fc-tabs-psy',
		name: 'quitapex 200mg 30 f.c.tab.',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 261,
		matchKeywords: ['quitapex 200', 'quetiapine 200', 'seroquel', 'psychosis', 'mania', 'كيوتابكس ٢٠٠', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (IR) مضاد ذهان غير نمطي.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 5) quitapex 25mg 30 f.c.tab
	{
		id: 'quitapex-25-30-fc-tabs-psy',
		name: 'quitapex 25mg 30 f.c.tab',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 87,
		matchKeywords: ['quitapex 25', 'quetiapine 25', 'seroquel', 'sleep', 'كيوتابكس ٢٥', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (جرعة صغيرة) كبداية للتدرج أو لاستخدامات مختارة بجرعة محددة مع متابعة.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 6) zesperone 4mg 10 f.c. tab
	{
		id: 'zesperone-4-10-fc-tabs-psy',
		name: 'zesperone 4mg 10 f.c. tab',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 62,
		matchKeywords: ['zesperone 4', 'risperidone 4', 'risperdal', 'psychosis', 'schizophrenia', 'irritability', 'زيسبيرون', 'ريسبيريدون', 'ذهان', 'فصام', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي للفصام/الذهان وبعض الاضطرابات السلوكية حسب التشخيص.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 7) amipride 50mg 20 tab
	{
		id: 'amipride-50-20-tabs-psy',
		name: 'amipride 50mg 20 tab',
		genericName: 'amisulpride',
		concentration: '50mg',
		price: 74,
		matchKeywords: ['amipride 50 20', 'amisulpride 50', 'solian', 'schizophrenia', 'أميبرايد', 'أميسولبرايد', '#anti-psychotic'],
		usage: 'أميسولبرايد مضاد ذهان للفصام (جرعات منخفضة قد تفيد الأعراض السلبية عند بعض المرضى).',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٣٠٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: AMISULPRIDE_WARNINGS,
	},

	// 8) amipride 50mg 30 tab
	{
		id: 'amipride-50-30-tabs-psy',
		name: 'amipride 50mg 30 tab',
		genericName: 'amisulpride',
		concentration: '50mg',
		price: 111,
		matchKeywords: ['amipride 50 30', 'amisulpride 50', 'أميبرايد', 'أميسولبرايد', '#anti-psychotic'],
		usage: 'أميسولبرايد مضاد ذهان للفصام.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٣٠٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: AMISULPRIDE_WARNINGS,
	},

	// 9) clozapex 100mg 50 tab
	{
		id: 'clozapex-100-50-tabs-psy',
		name: 'clozapex 100mg 50 tab',
		genericName: 'clozapine',
		concentration: '100mg',
		price: 135,
		matchKeywords: ['clozapex 100 50', 'clozapine 100', 'treatment resistant schizophrenia', 'clozaril', 'كلوزابكس', 'كلوزابين', 'فصام مقاوم', '#anti-psychotic'],
		usage: 'كلوزابين للفصام المقاوم للعلاج (يحتاج متابعة صارمة للدم).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٢٫٥ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: CLOZAPINE_WARNINGS,
	},

	// 10) clozapex 25mg 50 tab
	{
		id: 'clozapex-25-50-tabs-psy',
		name: 'clozapex 25mg 50 tab',
		genericName: 'clozapine',
		concentration: '25mg',
		price: 50,
		matchKeywords: ['clozapex 25 50', 'clozapine 25', 'كلوزابكس ٢٥', 'كلوزابين', '#anti-psychotic'],
		usage: 'كلوزابين (للتدرج في البداية أو تقسيم الجرعات).',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: CLOZAPINE_WARNINGS,
	},

	// 11) haloperidol 5mg/ml i.m. 5 amps.
	{
		id: 'haloperidol-5mgml-im-5-amps-psy',
		name: 'haloperidol 5mg/ml i.m. 5 amps.',
		genericName: 'haloperidol',
		concentration: '5mg/ml',
		price: 65,
		matchKeywords: ['haloperidol 5mg/ml im', 'haldol', 'acute agitation', 'psychosis', 'هالوبيريدول حقن', 'هالدول', 'هياج', 'ذهان', '#anti-psychotic'],
		usage: 'هالوبيريدول حقن عضل للحالات الحادة (هياج/ذهان) داخل منشأة طبية.',
		timing: 'عند الحاجة – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (حقنة) — عند الحاجة — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 12) sulpepta 25 mg 30 tabs.
	{
		id: 'sulpepta-25-30-tabs-psy',
		name: 'sulpepta 25 mg 30 tabs.',
		genericName: 'levosulpiride',
		concentration: '25mg',
		price: 54,
		matchKeywords: ['sulpepta 25', 'levosulpiride 25', 'dyspepsia', 'functional dyspepsia', 'سولبيبتا', 'ليفوسلبرايد', 'عسر هضم', '#anti-psychotic'],
		usage: 'ليفوسلبرايد (مشتق بنزاميد) يُستخدم غالباً لأعراض الجهاز الهضمي؛ وقد يسبب أعراض عصبية/برولاكتين.',
		timing: 'كل ٨ ساعات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — كل ٨ ساعات — قبل الأكل — مزمن.'),
		warnings: ['قد يرفع البرولاكتين (اضطراب دورة/إفرازات).', 'قد يسبب أعراض خارج هرمية خصوصاً مع كبار السن.', 'يُحذر مع إطالة QT أو مرضى باركنسون.'],
	},

	// 13) olapex 5 mg 30 f.c.tabs.
	{
		id: 'olapex-5-30-fc-tabs-psy',
		name: 'olapex 5 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '5mg',
		price: 160,
		matchKeywords: ['olapex 5', 'olanzapine 5', 'zyprexa', 'psychosis', 'bipolar', 'mania', 'أولابكس', 'أولانزابين', 'ذهان', 'ثنائي القطب', '#anti-psychotic'],
		usage: 'أولانزابين مضاد ذهان غير نمطي للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 14) riscure 4mg 20 f.c. tablets
	{
		id: 'riscure-4-20-fc-tabs-psy',
		name: 'riscure 4mg 20 f.c. tablets',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 86,
		matchKeywords: ['riscure 4 20', 'risperidone 4', 'riscure', 'ريسكير', 'ريسبيريدون', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 15) riscure 4mg 30 f.c. tab.
	{
		id: 'riscure-4-30-fc-tabs-psy',
		name: 'riscure 4mg 30 f.c. tab.',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 129,
		matchKeywords: ['riscure 4 30', 'risperidone 4', 'ريسكير ٤', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 16) quetiapine 300mg 30 f.c. tabs.
	{
		id: 'quetiapine-300-30-fc-tabs-psy',
		name: 'quetiapine 300mg 30 f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '300mg',
		price: 336,
		matchKeywords: ['quetiapine 300', 'seroquel 300', 'schizophrenia', 'bipolar', 'كويتيابين ٣٠٠', 'سيروكويل', '#anti-psychotic'],
		usage: 'كويتيابين (IR) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 17) apexidone 2mg 20 f.c.tab.
	{
		id: 'apexidone-2-20-fc-tabs-psy',
		name: 'apexidone 2mg 20 f.c.tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 75,
		matchKeywords: ['apexidone 2 20', 'risperidone 2', 'apexidone', 'أبيكسيدون', 'ريسبيريدون', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان غير نمطي.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 18) halonace 1.5 mg 10 tab.
	{
		id: 'halonace-1-5-10-tabs-psy',
		name: 'halonace 1.5 mg 10 tab.',
		genericName: 'haloperidol',
		concentration: '1.5mg',
		price: 13,
		matchKeywords: ['halonace 1.5', 'haloperidol 1.5', 'haldol', 'psychosis', 'هالوناس', 'هالوبيريدول', '#anti-psychotic'],
		usage: 'هالوبيريدول (تقليدي) للذهان/الهياج حسب الحالة.',
		timing: 'كل ٨ ساعات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (قرص) — كل ٨ ساعات — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 19) olapex 10 mg 30 f.c.tabs.
	{
		id: 'olapex-10-30-fc-tabs-psy',
		name: 'olapex 10 mg 30 f.c.tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 234,
		matchKeywords: ['olapex 10', 'olanzapine 10', 'zyprexa', 'mania', 'psychosis', 'أولابكس ١٠', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 20) psycholanz 6/25 mg 30 capsules
	{
		id: 'psycholanz-6-25-30-caps-psy',
		name: 'psycholanz 6/25 mg 30 capsules',
		genericName: 'olanzapine & fluoxetine',
		concentration: '6/25mg',
		price: 174,
		matchKeywords: ['psycholanz 6/25', 'olanzapine fluoxetine', 'symbyax', 'bipolar depression', 'treatment resistant depression', 'سايكولانز', 'أولانزابين', 'فلوكسيتين', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) لاضطراب ثنائي القطب (الاكتئاب) أو حالات مختارة بجرعة محددة مع متابعة (طبيب نفسي؛ راقب المزاج والوزن).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('6/25mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 21) quetiapine 100mg 30 f.c. tab.
	{
		id: 'quetiapine-100-30-fc-tabs-psy-2',
		name: 'quetiapine 100mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '100mg',
		price: 222,
		matchKeywords: ['quetiapine 100 30', 'quetiapine 100', 'seroquel', 'كويتيابين ١٠٠', '#anti-psychotic'],
		usage: 'كويتيابين للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 22) quetiapine 200mg 30 f.c. tabs.
	{
		id: 'quetiapine-200-30-fc-tabs-psy-2',
		name: 'quetiapine 200mg 30 f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 291,
		matchKeywords: ['quetiapine 200 30', 'quetiapine 200', 'seroquel', 'كويتيابين ٢٠٠', '#anti-psychotic'],
		usage: 'كويتيابين للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 23) quetiapine 25mg 30 f.c. tab.
	{
		id: 'quetiapine-25-30-fc-tabs-psy',
		name: 'quetiapine 25mg 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '25mg',
		price: 87,
		matchKeywords: ['quetiapine 25 30', 'quetiapine 25', 'seroquel', 'كويتيابين ٢٥', '#anti-psychotic'],
		usage: 'كويتيابين (جرعة بدء) للتدرج.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 24) quetiazic xr 150 mg 30 tabs.
	{
		id: 'quetiazic-xr-150-30-tabs-psy',
		name: 'quetiazic xr 150 mg 30 tabs.',
		genericName: 'quetiapine',
		concentration: '150mg',
		price: 195,
		matchKeywords: ['quetiazic xr 150', 'quetiapine xr 150', 'xr', 'extended release', 'كويتيازك ممتد', 'كويتيابين ممتد', '#anti-psychotic'],
		usage: 'كويتيابين ممتد المفعول (XR) مرة يومياً للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 25) quetiazic xr 300mg 30 tablets
	{
		id: 'quetiazic-xr-300-30-tabs-psy',
		name: 'quetiazic xr 300mg 30 tablets',
		genericName: 'quetiapine',
		concentration: '300mg',
		price: 321,
		matchKeywords: ['quetiazic xr 300', 'quetiapine xr 300', 'كويتيازك ممتد ٣٠٠', '#anti-psychotic'],
		usage: 'كويتيابين XR للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 26) quetiazic xr 400mg 30 tablets
	{
		id: 'quetiazic-xr-400-30-tabs-psy',
		name: 'quetiazic xr 400mg 30 tablets',
		genericName: 'quetiapine',
		concentration: '400mg',
		price: 387,
		matchKeywords: ['quetiazic xr 400', 'quetiapine xr 400', 'كويتيازك ممتد ٤٠٠', '#anti-psychotic'],
		usage: 'كويتيابين XR للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 27) zesperone 2mg 10 f.c. tab.
	{
		id: 'zesperone-2-10-fc-tabs-psy',
		name: 'zesperone 2mg 10 f.c. tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 41.5,
		matchKeywords: ['zesperone 2', 'risperidone 2', 'زيسبيرون ٢', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 28) psycholanz 6/50 mg 30 caps.
	{
		id: 'psycholanz-6-50-30-caps-psy',
		name: 'psycholanz 6/50 mg 30 caps.',
		genericName: 'olanzapine & fluoxetine',
		concentration: '6/50mg',
		price: 100.5,
		matchKeywords: ['psycholanz 6/50', 'olanzapine fluoxetine 6/50', 'symbyax', 'سايكولانز ٦/٥٠', '#anti-psychotic', '#antidepressants'],
		usage: 'أولانزابين + فلوكسيتين (مزيج) لحالات مختارة بجرعات معتمدة.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('6/50mg (كبسولة) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_FLUOXETINE_WARNINGS,
	},

	// 29) ranxapin 10 mg 7 tabs.
	{
		id: 'ranxapin-10-7-tabs-psy',
		name: 'ranxapin 10 mg 7 tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 48.5,
		matchKeywords: ['ranxapin 10 7', 'olanzapine 10', 'رانكسابين', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب (عبوة صغيرة).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 30) apexidone 0.5mg 30 f.c.tab.
	{
		id: 'apexidone-0-5-30-fc-tabs-psy',
		name: 'apexidone 0.5mg 30 f.c.tab.',
		genericName: 'risperidone',
		concentration: '0.5mg',
		price: 49.5,
		matchKeywords: ['apexidone 0.5', 'risperidone 0.5', 'أبيكسيدون ٠٫٥', '#anti-psychotic'],
		usage: 'ريسبيريدون (جرعة صغيرة للتدرج/الأطفال حسب الحالة).',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٠٫٥ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 31) apexidone 1mg 20 f.c.tab.
	{
		id: 'apexidone-1-20-fc-tabs-psy',
		name: 'apexidone 1mg 20 f.c.tab.',
		genericName: 'risperidone',
		concentration: '1mg',
		price: 54,
		matchKeywords: ['apexidone 1 20', 'risperidone 1', 'أبيكسيدون ١', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 32) apexidone 3mg 30 f.c.tab.
	{
		id: 'apexidone-3-30-fc-tabs-psy',
		name: 'apexidone 3mg 30 f.c.tab.',
		genericName: 'risperidone',
		concentration: '3mg',
		price: 126,
		matchKeywords: ['apexidone 3 30', 'risperidone 3', 'أبيكسيدون ٣', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 33) apexidone 4mg 30 f.c.tab.
	{
		id: 'apexidone-4-30-fc-tabs-psy',
		name: 'apexidone 4mg 30 f.c.tab.',
		genericName: 'risperidone',
		concentration: '4mg',
		price: 126,
		matchKeywords: ['apexidone 4 30', 'risperidone 4', 'أبيكسيدون ٤', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 34) aripiprazole 15mg 20 f.c. tab.
	{
		id: 'aripiprazole-15-20-fc-tabs-psy',
		name: 'aripiprazole 15mg 20 f.c. tab.',
		genericName: 'aripiprazole',
		concentration: '15mg',
		price: 117,
		matchKeywords: ['aripiprazole 15', 'abilify', 'psychosis', 'bipolar', 'irritability', 'أريبيبرازول', 'ابيليفاي', '#anti-psychotic'],
		usage: 'أريبيبرازول مضاد ذهان غير نمطي للفصام/ثنائي القطب وبعض الاضطرابات السلوكية حسب التشخيص.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٥ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 35) aripiprazole 20 mg 20 f.c. tab.
	{
		id: 'aripiprazole-20-20-fc-tabs-psy',
		name: 'aripiprazole 20 mg 20 f.c. tab.',
		genericName: 'aripiprazole',
		concentration: '20mg',
		price: 106,
		matchKeywords: ['aripiprazole 20', 'abilify 20', 'أريبيبرازول ٢٠', '#anti-psychotic'],
		usage: 'أريبيبرازول مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٣٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 36) aripiprazole 30mg 20 f.c tab
	{
		id: 'aripiprazole-30-20-fc-tabs-psy',
		name: 'aripiprazole 30mg 20 f.c tab',
		genericName: 'aripiprazole',
		concentration: '30mg',
		price: 152,
		matchKeywords: ['aripiprazole 30', 'abilify 30', 'أريبيبرازول ٣٠', '#anti-psychotic'],
		usage: 'أريبيبرازول (جرعة ٣٠ مجم - الحد الأعلى الشائع).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٣٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 37) aripiprex 10mg 30 f.c.tab.
	{
		id: 'aripiprex-10-30-fc-tabs-psy',
		name: 'aripiprex 10mg 30 f.c.tab.',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 162,
		matchKeywords: ['aripiprex 10', 'aripiprazole 10', 'abilify 10', 'أريبيبريكس', 'أريبيبرازول ١٠', '#anti-psychotic'],
		usage: 'أريبيبرازول مضاد ذهان غير نمطي (جرعة بداية شائعة).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 38) clozapine 100mg 30 scored tab
	{
		id: 'clozapine-100-30-scored-tabs-psy',
		name: 'clozapine 100mg 30 scored tab',
		genericName: 'clozapine',
		concentration: '100mg',
		price: 93,
		matchKeywords: ['clozapine 100 30', 'scored', 'clozaril', 'كلوزابين ١٠٠', '#anti-psychotic'],
		usage: 'كلوزابين للفصام المقاوم للعلاج (يتطلب متابعة دم).',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Scored Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٥ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: CLOZAPINE_WARNINGS,
	},

	// 39) clozapine 100mg 20 scored tab
	{
		id: 'clozapine-100-20-scored-tabs-psy',
		name: 'clozapine 100mg 20 scored tab',
		genericName: 'clozapine',
		concentration: '100mg',
		price: 38,
		matchKeywords: ['clozapine 100 20', 'scored', 'كلوزابين', '#anti-psychotic'],
		usage: 'كلوزابين للفصام المقاوم للعلاج.',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Scored Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٤٥٠ مجم (قرص) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: CLOZAPINE_WARNINGS,
	},

	// 40) halonace 5 mg 10 tabs.
	{
		id: 'halonace-5-10-tabs-psy',
		name: 'halonace 5 mg 10 tabs.',
		genericName: 'haloperidol',
		concentration: '5mg',
		price: 17,
		matchKeywords: ['halonace 5', 'haloperidol 5', 'haldol 5', 'هالوناس ٥', 'هالوبيريدول', '#anti-psychotic'],
		usage: 'هالوبيريدول (تقليدي) للذهان/الهياج حسب الحالة.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 41) haloperidol retard 50mg/ml i.m.amp.
	{
		id: 'haloperidol-retard-50mgml-im-amp-psy',
		name: 'haloperidol retard 50mg/ml i.m.amp.',
		genericName: 'haloperidol',
		concentration: '50mg/ml',
		price: 28,
		matchKeywords: ['haloperidol retard 50mg/ml', 'haldol decanoate', 'depot', 'long acting', 'هالوبيريدول ديبوت', 'حقنة شهرية', '#anti-psychotic'],
		usage: 'هالوبيريدول ديبوت (طويل المفعول) للحقن العضلي العميق بجرعة محددة في العيادة/منشأة صحية مع متابعة (حقن عميق؛ متابعة QT).',
		timing: 'حسب التعليمات – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠٠ مجم (حقنة) — حسب التعليمات — بدون اعتبار للأكل — مزمن.'),
		warnings: HALOPERIDOL_WARNINGS,
	},

	// 42) lanzapine 10mg 7 f.c. tab.
	{
		id: 'lanzapine-10-7-fc-tabs-psy',
		name: 'lanzapine 10mg 7 f.c. tab.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 70,
		matchKeywords: ['lanzapine 10 7', 'olanzapine 10', 'لانزابين', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب (عبوة صغيرة).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 43) riscure 1mg 20 f.c. tab.
	{
		id: 'riscure-1-20-fc-tabs-psy',
		name: 'riscure 1mg 20 f.c. tab.',
		genericName: 'risperidone',
		concentration: '1mg',
		price: 37,
		matchKeywords: ['riscure 1 20', 'risperidone 1', 'ريسكير ١', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 44) riscure 2mg 20 f.c. tab.
	{
		id: 'riscure-2-20-fc-tabs-psy',
		name: 'riscure 2mg 20 f.c. tab.',
		genericName: 'risperidone',
		concentration: '2mg',
		price: 73,
		matchKeywords: ['riscure 2 20', 'risperidone 2', 'ريسكير ٢', '#anti-psychotic'],
		usage: 'ريسبيريدون مضاد ذهان.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('٦ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 45) rispadex 1mg/ml syrup 100ml
	{
		id: 'rispadex-1mgml-100ml-syr-psy',
		name: 'rispadex 1mg/ml syrup 100ml',
		genericName: 'risperidone',
		concentration: '1mg/ml',
		price: 33,
		matchKeywords: ['rispadex syrup', 'risperidone syrup 1mg/ml', 'adhd aggression', 'autism irritability', 'ريسباديكس', 'ريسبيريدون شراب', '#anti-psychotic'],
		usage: 'ريسبيريدون شراب (مفيد لجرعات الأطفال حسب الحالة).',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Syrup',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (شراب) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 46) risperdal 1mg/ml oral solution 30 ml
	{
		id: 'risperdal-1mgml-30ml-solution-psy',
		name: 'risperdal 1mg/ml oral solution 30 ml',
		genericName: 'risperidone',
		concentration: '1mg/ml',
		price: 137,
		matchKeywords: ['risperdal oral solution', 'risperidone solution 1mg/ml', 'risperdal', 'ريسبردال', 'ريسبيريدون محلول', '#anti-psychotic'],
		usage: 'ريسبيريدون محلول فموي (مناسب لضبط الجرعة).',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Solution',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (جرعة) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 47) seroquel 200mg 30 tab
	{
		id: 'seroquel-200-30-tabs-psy',
		name: 'seroquel 200mg 30 tab',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 429,
		matchKeywords: ['seroquel 200', 'quetiapine 200', 'سيروكويل ٢٠٠', 'كويتيابين', '#anti-psychotic'],
		usage: 'كويتيابين (الاسم التجاري) للفصام/ثنائي القطب.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 48) ranxapin 10 mg 10 tabs.
	{
		id: 'ranxapin-10-10-tabs-psy',
		name: 'ranxapin 10 mg 10 tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 48.5,
		matchKeywords: ['ranxapin 10 10', 'olanzapine 10', 'رانكسابين ١٠', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 49) amipride 100mg 30 tab
	{
		id: 'amipride-100-30-tabs-psy',
		name: 'amipride 100mg 30 tab',
		genericName: 'amisulpride',
		concentration: '100mg',
		price: 88.25,
		matchKeywords: ['amipride 100', 'amisulpride 100', 'أميبرايد ١٠٠', '#anti-psychotic'],
		usage: 'أميسولبرايد مضاد ذهان للفصام.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: AMISULPRIDE_WARNINGS,
	},

	// 50) amipride 200 mg 20 scored tab
	{
		id: 'amipride-200-20-scored-tabs-psy',
		name: 'amipride 200 mg 20 scored tab',
		genericName: 'amisulpride',
		concentration: '200mg',
		price: 111,
		matchKeywords: ['amipride 200', 'amisulpride 200', 'scored', 'أميبرايد ٢٠٠', '#anti-psychotic'],
		usage: 'أميسولبرايد مضاد ذهان للفصام.',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Scored Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: AMISULPRIDE_WARNINGS,
	},

	// 51) aripiprazole 10 mg 20 orally dis. tablets
	{
		id: 'aripiprazole-10-20-odt-psy',
		name: 'aripiprazole 10 mg 20 orally dis. tablets',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 89.75,
		matchKeywords: ['aripiprazole 10 odt', 'orally disintegrating', 'abilify', 'أريبيبرازول فوار بالفم', 'أقراص تذوب', '#anti-psychotic'],
		usage: 'أريبيبرازول أقراص تذوب بالفم (ODT) مضاد ذهان غير نمطي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 52) aripiprazole 10mg 20 f.c. tab.
	{
		id: 'aripiprazole-10-20-fc-tabs-psy',
		name: 'aripiprazole 10mg 20 f.c. tab.',
		genericName: 'aripiprazole',
		concentration: '10mg',
		price: 99,
		matchKeywords: ['aripiprazole 10', 'abilify 10', 'أريبيبرازول ١٠', '#anti-psychotic'],
		usage: 'أريبيبرازول مضاد ذهان غير نمطي (جرعة بداية شائعة).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 53) aripiprazole 30mg 20 orally dis.tablets
	{
		id: 'aripiprazole-30-20-odt-psy',
		name: 'aripiprazole 30mg 20 orally dis.tablets',
		genericName: 'aripiprazole',
		concentration: '30mg',
		price: 126,
		matchKeywords: ['aripiprazole 30 odt', 'orally disintegrating', 'abilify 30', 'أريبيبرازول ٣٠ أقراص تذوب', '#anti-psychotic'],
		usage: 'أريبيبرازول ODT (جرعة ٣٠ مجم - حد أعلى شائع).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('٣٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: ARIPIPRAZOLE_WARNINGS,
	},

	// 54) bioprex 7.5 mg 30 f.c. tabs.
	{
		id: 'bioprex-7-5-30-fc-tabs-psy',
		name: 'bioprex 7.5 mg 30 f.c. tabs.',
		genericName: 'olanzapine',
		concentration: '7.5mg',
		price: 153,
		matchKeywords: ['bioprex 7.5', 'olanzapine 7.5', 'بيوبريكس', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 55) ranxapin 10 mg 21 tabs.
	{
		id: 'ranxapin-10-21-tabs-psy',
		name: 'ranxapin 10 mg 21 tabs.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 145.5,
		matchKeywords: ['ranxapin 10 21', 'olanzapine 10', 'رانكسابين ٢١', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 56) integrol 10mg 30 f.c. tablets
	{
		id: 'integrol-10-30-fc-tabs-psy',
		name: 'integrol 10mg 30 f.c. tablets',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 117,
		matchKeywords: ['integrol 10', 'olanzapine 10', 'integrol', 'انتجرول', 'أولانزابين', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 57) lanzapine 10mg 14 f.c. tab.
	{
		id: 'lanzapine-10-14-fc-tabs-psy',
		name: 'lanzapine 10mg 14 f.c. tab.',
		genericName: 'olanzapine',
		concentration: '10mg',
		price: 90,
		matchKeywords: ['lanzapine 10 14', 'olanzapine 10', 'لانزابين ١٤', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب (عبوة ١٤ قرص).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 58) olanzapine-copad 7.5 mg 14 f.c. tab
	{
		id: 'olanzapine-copad-7-5-14-fc-tabs-psy',
		name: 'olanzapine-copad 7.5 mg 14 f.c. tab',
		genericName: 'olanzapine',
		concentration: '7.5mg',
		price: 98,
		matchKeywords: ['olanzapine-copad 7.5', 'olanzapine 7.5', 'copad', 'أولانزابين كوباد', '#anti-psychotic'],
		usage: 'أولانزابين للفصام/ثنائي القطب (جرعة ٧٫٥ مجم).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم (قرص) — مرة يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: OLANZAPINE_WARNINGS,
	},

	// 59) psychodal 1mg/ml syrup 30ml
	{
		id: 'psychodal-1mgml-30ml-syr-psy',
		name: 'psychodal 1mg/ml syrup 30ml',
		genericName: 'risperidone',
		concentration: '1mg/ml',
		price: 67,
		matchKeywords: ['psychodal syrup', 'risperidone 1mg/ml', 'سايكودال', 'ريسبيريدون شراب', '#anti-psychotic'],
		usage: 'ريسبيريدون شراب لضبط الجرعة (خصوصاً للأطفال).',
		timing: 'مرتين يومياً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Syrup',
		minAgeMonths: 60,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('١ مجم (شراب) — مرتين يومياً — بدون اعتبار للأكل — مزمن.'),
		warnings: RISPERIDONE_WARNINGS,
	},

	// 60) quetiazic xr 50 mg 30 tablets
	{
		id: 'quetiazic-xr-50-30-tabs-psy',
		name: 'quetiazic xr 50 mg 30 tablets',
		genericName: 'quetiapine',
		concentration: '50mg',
		price: 113.5,
		matchKeywords: ['quetiazic xr 50', 'quetiapine xr 50', 'كويتيازك ممتد ٥٠', '#anti-psychotic'],
		usage: 'كويتيابين ممتد المفعول (XR) للتدرج.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 61) quitapex 300mg xr 30 f.c. tab.
	{
		id: 'quitapex-xr-300-30-fc-tabs-psy',
		name: 'quitapex 300mg xr 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '300mg',
		price: 336,
		matchKeywords: ['quitapex xr 300', 'quetiapine xr 300', 'كيوتابكس ممتد ٣٠٠', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 62) quitapex 400mg xr 30 f.c. tab.
	{
		id: 'quitapex-xr-400-30-fc-tabs-psy',
		name: 'quitapex 400mg xr 30 f.c. tab.',
		genericName: 'quetiapine',
		concentration: '400mg',
		price: 387,
		matchKeywords: ['quitapex xr 400', 'quetiapine xr 400', 'كيوتابكس ممتد ٤٠٠', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 63) quitcool xr 200mg 30 ext. rel. f.c. tabs.
	{
		id: 'quitcool-xr-200-30-fc-tabs-psy',
		name: 'quitcool xr 200mg 30 ext. rel. f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '200mg',
		price: 264,
		matchKeywords: ['quitcool xr 200', 'quetiapine xr 200', 'quitcool', 'كويت كول ممتد', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 64) quitcool xr 300mg 30 ext. rel. f.c. tabs.
	{
		id: 'quitcool-xr-300-30-fc-tabs-psy',
		name: 'quitcool xr 300mg 30 ext. rel. f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '300mg',
		price: 336,
		matchKeywords: ['quitcool xr 300', 'quetiapine xr 300', 'كويت كول ممتد ٣٠٠', '#anti-psychotic'],
		usage: 'كويتيابين XR مرة يومياً.',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},

	// 65) quitcool xr 50mg 30 ext. rel. f.c. tabs.
	{
		id: 'quitcool-xr-50-30-fc-tabs-psy',
		name: 'quitcool xr 50mg 30 ext. rel. f.c. tabs.',
		genericName: 'quetiapine',
		concentration: '50mg',
		price: 135,
		matchKeywords: ['quitcool xr 50', 'quetiapine xr 50', 'كويت كول ممتد ٥٠', '#anti-psychotic'],
		usage: 'كويتيابين XR (جرعة تدرج).',
		timing: 'مرة ليلاً – مزمن',
		category: Category.ANTIPSYCHOTIC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('٨٠٠ مجم (قرص) — مرة ليلاً — بدون اعتبار للأكل — مزمن.'),
		warnings: QUETIAPINE_WARNINGS,
	},
];

export const ANTIPSYCHOTIC_DRUGS_PART_1: Medication[] = enhanceAntipsychoticList(ANTIPSYCHOTIC_DRUGS_PART_1_RAW);

export const ANTIPSYCHOTIC_DRUGS: Medication[] = [
	...ANTIPSYCHOTIC_DRUGS_PART_1,
	...ANTIPSYCHOTIC_DRUGS_PART_2,
	...ANTIPSYCHOTIC_DRUGS_PART_3,
];

