import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;
const clamp = (n: number, min: number, max: number) => Math.min(max, Math.max(min, n));

const COMMON_CEPHALOSPORIN_WARNINGS = [
	'حساسية: أوقف الدواء واطلب مساعدة إذا ظهر طفح شديد/تورم/ضيق نفس.',
	'تاريخ حساسية بنسلين: نسبة التفاعل المتبادل مع السيفالوسبورينات ≈١–٢٪؛ اسأل المريض وتجنّب عند حساسية شديدة سابقة (anaphylaxis).',
	'إسهال شديد/دموي أو ألم بطن مستمر: أوقف المضاد واشتبه بالتهاب قولون C. difficile؛ أجرِ فحص Toxin/زرع وعالج حسب التشخيص والتحاليل (مترونيدازول ٥٠٠ مجم × ٣ فموي أو فانكومايسين فموي في الحالات الشديدة).',
	'مرضى الكلى/كبار السن: قد تحتاج الجرعة لتعديل حسب وظائف الكلى.',
	'لا يفيد في نزلات البرد والإنفلونزا (عدوى فيروسية).',
];

const vialMg = (c: string) => (c === '2gm' || c === '2g' ? 2000 : c === '1gm' || c === '1g' ? 1000 : c === '500mg' ? 500 : 0);

const ceftriaxoneDose = (weightKg: number, ageMonths: number, concentration: string, route: 'IV' | 'IM'): string => {
	if (ageMonths < 1) return 'حديثي الولادة: جرعات خاصة—يلزم بروتوكول.';
	const v = vialMg(concentration);
	if (!v) return 'جرعة غير متاحة لهذا التركيز.';
	const isAdult = ageMonths >= 144 || weightKg >= 40;
	const mgPerMl = route === 'IV' ? 100 : 250;
	const dailyMin = isAdult ? 1000 : clamp(weightKg * 50, 0, 4000);
	const dailyMax = isAdult ? 2000 : clamp(weightKg * 100, 0, 4000);
	const mlMin = Math.round((dailyMin / mgPerMl) * 10) / 10;
	const mlMax = Math.round((dailyMax / mgPerMl) * 10) / 10;
	if (Math.abs(mlMin - mlMax) < 0.1) return `${toAr(mlMin)} مل مرة يومياً لمدة ٥–١٤ يوم`;
	return `${toAr(mlMin)}–${toAr(mlMax)} مل مرة يومياً لمدة ٥–١٤ يوم`;
};

const cefotaximeDose = (weightKg: number, ageMonths: number, concentration: string, route: 'IV' | 'IM'): string => {
	if (ageMonths < 1) return 'حديثي الولادة: جرعات خاصة—يلزم بروتوكول.';
	const v = vialMg(concentration);
	if (!v) return 'جرعة غير متاحة لهذا التركيز.';
	const isAdult = ageMonths >= 144 || weightKg >= 40;
	const mgPerMl = route === 'IV' ? 125 : 250;
	const doseMin = isAdult ? 1000 : clamp(weightKg * 50, 0, 2000);
	const doseMax = isAdult ? 1000 : clamp(weightKg * 75, 0, 2000);
	const mlMin = Math.round((doseMin / mgPerMl) * 10) / 10;
	const mlMax = Math.round((doseMax / mgPerMl) * 10) / 10;
	if (Math.abs(mlMin - mlMax) < 0.1) return `${toAr(mlMin)} مل كل ٨ ساعات لمدة ٧–١٤ يوم`;
	return `${toAr(mlMin)}–${toAr(mlMax)} مل كل ٨ ساعات لمدة ٧–١٤ يوم`;
};

const ceftazidimeDose = (weightKg: number, ageMonths: number, concentration: string, route: 'IV' | 'IM'): string => {
	if (ageMonths < 1) return 'حديثي الولادة: جرعات خاصة—يلزم بروتوكول.';
	const v = vialMg(concentration);
	if (!v) return 'جرعة غير متاحة لهذا التركيز.';
	const isAdult = ageMonths >= 144 || weightKg >= 40;
	const mgPerMl = route === 'IV' ? 100 : 250;
	const doseMin = isAdult ? 1000 : clamp(weightKg * 50, 0, 2000);
	const doseMax = isAdult ? 1000 : clamp(weightKg * 75, 0, 2000);
	const mlMin = Math.round((doseMin / mgPerMl) * 10) / 10;
	const mlMax = Math.round((doseMax / mgPerMl) * 10) / 10;
	if (Math.abs(mlMin - mlMax) < 0.1) return `${toAr(mlMin)} مل كل ٨ ساعات لمدة ٧–١٤ يوم`;
	return `${toAr(mlMin)}–${toAr(mlMax)} مل كل ٨ ساعات لمدة ٧–١٤ يوم`;
};

const ceftriaxone = (conc: string, route: 'IV' | 'IM') => (w: number, a: number) => ceftriaxoneDose(w, a, conc, route);
const cefotaxime = (conc: string, route: 'IV' | 'IM') => (w: number, a: number) => cefotaximeDose(w, a, conc, route);
const ceftazidime = (conc: string, route: 'IV' | 'IM') => (w: number, a: number) => ceftazidimeDose(w, a, conc, route);

const ceftriaxoneWarnings = [
	...COMMON_CEPHALOSPORIN_WARNINGS,
	'حديثي الولادة: يُتجنب عادةً (خطر زيادة الصفراء/ترسّبات) ويُمنع مع محاليل/أدوية تحتوي كالسيوم—يلزم بروتوكول متخصص.',
	'السيفترياكسون + كالسيوم: يُمنع مع محاليل تحتوي كالسيوم (مثل رينجر لاكتات) ولا يُخلط/لا يُعطى في نفس الخط (حسب بروتوكول المستشفى).',
	'تاريخ حساسية شديد لمضادات بيتالاكتام: يلزم تقييم طبي؛ قد يلزم اختبار حساسية (skin test) في بيئة مناسبة مع توفر أدوية الطوارئ.',
];

const cefiximePedsOnceDaily = (weightKg: number, ageMonths: number, concMgPerMl: number) => {
	// Pediatric: 8 mg/kg/day PO once daily (or 4 mg/kg q12h). Max 400 mg/day.
	if (ageMonths < 6) return 'أقل من ٦ أشهر: الجرعة والسلامة تحتاج تقييم طبي.';
	if (ageMonths >= 144 || weightKg >= 40) return '٤٠٠ مجم مرة يومياً بعد الأكل لمدة ٧–١٤ يوم';
	const dailyMg = clamp(weightKg * 8, 0, 400);
	const ml = dailyMg / concMgPerMl;
	return `${toAr(roundVol(ml))} مل مرة يومياً بعد الأكل لمدة ٧–١٤ يوم`;
};

const cefdinirPedsOnceDaily = (weightKg: number, ageMonths: number, concMgPerMl: number) => {
	// Pediatric: 14 mg/kg/day once daily (or 7 mg/kg q12h). Max 600 mg/day.
	if (ageMonths < 6) return 'أقل من ٦ أشهر: الجرعة والسلامة تحتاج تقييم طبي.';
	if (ageMonths >= 144 || weightKg >= 40) return '٦٠٠ مجم مرة يومياً بدون اعتبار للأكل لمدة ٥–١٠ أيام';
	const dailyMg = clamp(weightKg * 14, 0, 600);
	const ml = dailyMg / concMgPerMl;
	return `${toAr(roundVol(ml))} مل مرة يومياً بدون اعتبار للأكل لمدة ٥–١٠ أيام`;
};

export const THIRD_GEN_CEPHALOSPORINS: Medication[] = [
	// ==========================================
	// CEFTRIAXONE (Injectables)
	// ==========================================

	// 1) cefaxone 1 gm i.v. vial
	{
		id: 'cefaxone-1g-iv-vial',
		name: 'cefaxone 1 gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 69,
		matchKeywords: ['cefaxone 1g iv', 'cefaxone', 'سيفاكسون', 'ceftriaxone', 'سيفترياكسون', 'pneumonia', 'uti', 'typhoid', 'sepsis', 'التهاب رئوي', 'التهاب بول', 'تيفود', 'ميكروب دم', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون حقن وريد فقط لعلاج عدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 2) cefaxone 1 gm i.m. vial
	{
		id: 'cefaxone-1g-im-vial',
		name: 'cefaxone 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 69,
		matchKeywords: ['cefaxone 1g im', 'cefaxone im', 'سيفاكسون عضل', 'ceftriaxone', 'سيفترياكسون', 'im injection', 'حقن عضل', 'pneumonia', 'meningitis', 'uti', 'typhoid', 'sepsis', 'التهاب رئوي', 'سحايا', 'التهاب بول', 'تيفود', 'ميكروب دم', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون حقن عضل فقط لعلاج عدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 4) ceftriaxone-sandoz 1 gm i.v. vial
	{
		id: 'ceftriaxone-sandoz-1g-iv-vial',
		name: 'ceftriaxone-sandoz 1 gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 95,
		matchKeywords: ['ceftriaxone sandoz 1g iv', 'sandoz ceftriaxone', 'سيفترياكسون ساندوز', 'ceftriaxone', 'iv', 'حقن وريد', 'pneumonia', 'meningitis', 'uti', 'typhoid', 'sepsis', 'التهاب رئوي', 'سحايا', 'التهاب بول', 'تيفود', 'ميكروب دم', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Sandoz) حقن وريد فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 5) ceftriaxone-sandoz 1 gm i.m. vial
	{
		id: 'ceftriaxone-sandoz-1g-im-vial',
		name: 'ceftriaxone-sandoz 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 95,
		matchKeywords: ['ceftriaxone sandoz 1g im', 'sandoz ceftriaxone im', 'سيفترياكسون ساندوز عضل', 'ceftriaxone', 'im', 'حقن عضل', 'pneumonia', 'meningitis', 'uti', 'typhoid', 'sepsis', 'التهاب رئوي', 'سحايا', 'التهاب بول', 'تيفود', 'ميكروب دم', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Sandoz) حقن عضل فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 6) ceftriaxone-sandoz 500 mg i.v. vial
	{
		id: 'ceftriaxone-sandoz-500mg-iv-vial',
		name: 'ceftriaxone-sandoz 500 mg i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 42,
		matchKeywords: ['ceftriaxone sandoz 500 iv', 'ceftriaxone 500 iv', 'سيفترياكسون ٥٠٠ وريد', 'sandoz', 'ceftriaxone', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم حقن وريد فقط—يُستخدم حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 20) ceftriaxone-sandoz 500 mg i.m. vial
	{
		id: 'ceftriaxone-sandoz-500mg-im-vial',
		name: 'ceftriaxone-sandoz 500 mg i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 62,
		matchKeywords: ['ceftriaxone sandoz 500 im', 'ceftriaxone 500 im', 'سيفترياكسون ٥٠٠ عضل', 'sandoz', 'ceftriaxone', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم حقن عضل فقط—يُستخدم حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 13) ceftriaxone-sedico 1 gm i.v. vial
	{
		id: 'ceftriaxone-sedico-1g-iv-vial',
		name: 'ceftriaxone-sedico 1 gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 39,
		matchKeywords: ['ceftriaxone sedico 1g iv', 'sedico ceftriaxone', 'سيفترياكسون سيديكو', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Sedico) حقن وريد فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 14) ceftriaxone-sedico 1 gm i.m. vial
	{
		id: 'ceftriaxone-sedico-1g-im-vial',
		name: 'ceftriaxone-sedico 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['ceftriaxone sedico 1g im', 'sedico ceftriaxone im', 'سيفترياكسون سيديكو عضل', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Sedico) حقن عضل فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 17) xoraxon 1gm i.m. vial
	{
		id: 'xoraxon-1g-im-vial',
		name: 'xoraxon 1gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['xoraxon 1g im', 'xoraxon', 'زوراكسون', 'ceftriaxone', 'سيفترياكسون', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Xoraxon) حقن عضل فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 18) xoraxon 1gm i.v. vial
	{
		id: 'xoraxon-1g-iv-vial',
		name: 'xoraxon 1gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['xoraxon 1g iv', 'xoraxon', 'زوراكسون', 'ceftriaxone', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Xoraxon) حقن وريد فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 22) cefaxone 2gm i.v. vial
	{
		id: 'cefaxone-2g-iv-vial',
		name: 'cefaxone 2gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '2gm',
		price: 96,
		matchKeywords: ['cefaxone 2g iv', 'cefaxone 2gm', 'سيفاكسون ٢ جم', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٢ جم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: ceftriaxone('2gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 23) cefaxone 500mg i.m. vial
	{
		id: 'cefaxone-500mg-im-vial',
		name: 'cefaxone 500mg i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 49,
		matchKeywords: ['cefaxone 500 im', 'cefaxone 0.5g im', 'سيفاكسون ٥٠٠ عضل', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 34) cefaxone 500mg i.v. vial
	{
		id: 'cefaxone-500mg-iv-vial',
		name: 'cefaxone 500mg i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 25.25,
		matchKeywords: ['cefaxone 500 iv', 'cefaxone 0.5g iv', 'سيفاكسون ٥٠٠ وريد', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 28) epicephin 1 gm i.m. vial
	{
		id: 'epicephin-1g-im-vial',
		name: 'epicephin 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 60,
		matchKeywords: ['epicephin 1g im', 'epicephin', 'ايبوسيفين', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Epicephin) حقن عضل فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 37) epicephin 1gm i.v. vial
	{
		id: 'epicephin-1g-iv-vial',
		name: 'epicephin 1gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 60,
		matchKeywords: ['epicephin 1g iv', 'epicephin', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Epicephin) حقن وريد فقط لعدوى بكتيرية حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 38) epicephin 2gm i.v. vial
	{
		id: 'epicephin-2g-iv-vial',
		name: 'epicephin 2gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '2gm',
		price: 77,
		matchKeywords: ['epicephin 2g iv', 'epicephin 2gm', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٢ جم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: ceftriaxone('2gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 39) epicephin 500mg i.v. vial
	{
		id: 'epicephin-500mg-iv-vial',
		name: 'epicephin 500mg i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 47,
		matchKeywords: ['epicephin 500 iv', 'ceftriaxone 500 iv', 'epicephin', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 40) epicephin 500mg i.m. vial
	{
		id: 'epicephin-500mg-im-vial',
		name: 'epicephin 500mg i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 47,
		matchKeywords: ['epicephin 500 im', 'ceftriaxone 500 im', 'epicephin', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 32) kempoxone 1 gm i.m. vial
	{
		id: 'kempoxone-1g-im-vial',
		name: 'kempoxone 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['kempoxone 1g im', 'kempoxone', 'كيمبوكسون', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Kempoxone) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 33) oframax 1 gm i.v. vial
	{
		id: 'oframax-1g-iv-vial',
		name: 'oframax 1 gm i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 70,
		matchKeywords: ['oframax 1g iv', 'oframax', 'اوفراكس', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Oframax) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 45) oframax 1 gm i.m. vial
	{
		id: 'oframax-1g-im-vial',
		name: 'oframax 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 71,
		matchKeywords: ['oframax 1g im', 'oframax', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Oframax) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 46) rameceftrax 1 gm i.m. vial
	{
		id: 'rameceftrax-1g-im-vial',
		name: 'rameceftrax 1 gm i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['rameceftrax 1g im', 'rameceftrax', 'راميسيفتراكس', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Rameceftrax) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 47) rameceftrax 1 gm iv vial
	{
		id: 'rameceftrax-1g-iv-vial',
		name: 'rameceftrax 1 gm iv vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['rameceftrax 1g iv', 'rameceftrax', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Rameceftrax) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 48) rameceftrax 500 mg vial for i.m. inj.
	{
		id: 'rameceftrax-500mg-im-vial',
		name: 'rameceftrax 500 mg vial for i.m. inj.',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 46,
		matchKeywords: ['rameceftrax 500 im', 'ceftriaxone 500 im', 'rameceftrax', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 49) rameceftrax 500 mg vial for i.v. inj.
	{
		id: 'rameceftrax-500mg-iv-vial',
		name: 'rameceftrax 500 mg vial for i.v. inj.',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 46,
		matchKeywords: ['rameceftrax 500 iv', 'ceftriaxone 500 iv', 'rameceftrax', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 50) trixomash 1 gm vial for i.m. inj.
	{
		id: 'trixomash-1g-im-vial',
		name: 'trixomash 1 gm vial for i.m. inj.',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 48,
		matchKeywords: ['trixomash 1g im', 'trixomash', 'تريكسوماش', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Trixomash) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 51) trixomash 1 gm vial for i.v. inj.
	{
		id: 'trixomash-1g-iv-vial',
		name: 'trixomash 1 gm vial for i.v. inj.',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 48,
		matchKeywords: ['trixomash 1g iv', 'trixomash', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Trixomash) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 52) votriaxone 1 gm i.m vial
	{
		id: 'votriaxone-1g-im-vial',
		name: 'votriaxone 1 gm i.m vial',
		genericName: 'ceftriaxone',
		concentration: '1gm',
		price: 56,
		matchKeywords: ['votriaxone 1g im', 'votriaxone', 'فوترياكسون', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (Votriaxone) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('1gm', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 53) votriaxone 500 mg i.m vial
	{
		id: 'votriaxone-500mg-im-vial',
		name: 'votriaxone 500 mg i.m vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 46,
		matchKeywords: ['votriaxone 500 im', 'votriaxone', 'ceftriaxone 500 im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون ٥٠٠ مجم عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 54) ceftriaxone-eva 500 mg i.m. vial
	{
		id: 'ceftriaxone-eva-500mg-im-vial',
		name: 'ceftriaxone-eva 500 mg i.m. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 53,
		matchKeywords: ['ceftriaxone eva 500 im', 'eva ceftriaxone', 'سيفترياكسون ايفا', 'ceftriaxone', 'im', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (EVA) ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IM'),
		warnings: [...ceftriaxoneWarnings],
	},

	// 55) ceftriaxone-eva 500 mg i.v. vial
	{
		id: 'ceftriaxone-eva-500mg-iv-vial',
		name: 'ceftriaxone-eva 500 mg i.v. vial',
		genericName: 'ceftriaxone',
		concentration: '500mg',
		price: 53,
		matchKeywords: ['ceftriaxone eva 500 iv', 'eva ceftriaxone', 'ceftriaxone', 'iv', '#antibiotics', '#cephalosporin'],
		usage: 'سيفترياكسون (EVA) ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٢٤ ساعة – ٥–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: ceftriaxone('500mg', 'IV'),
		warnings: [...ceftriaxoneWarnings],
	},

	// ==========================================
	// CEFOTAXIME (Injectables)
	// ==========================================

	// 3) cefotax 1 gm i.v. vial
	{
		id: 'cefotax-1g - iv-vial',
		name: 'cefotax 1 gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 30,
		matchKeywords: ['cefotax 1g iv', 'cefotax iv', 'cefotax', 'سيفوتاكس', 'cefotaxime', 'سيفوتاكسيم', 'iv', 'حقن وريد', 'pneumonia', 'sepsis', 'التهاب رئوي', 'ميكروب دم', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم حقن وريد فقط لعدوى بكتيرية (التهاب رئوي، إنتان، بول، إلخ). الجرعة المعتادة: ١ جم كل ٨–١٢ ساعة؛ ٢ جم كل ٨ ساعات في العدوى الشديدة أو السحايا.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 3b) cefotax 1 gm i.m. vial
	{
		id: 'cefotax-1g-im-vial',
		name: 'cefotax 1 gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 30,
		matchKeywords: ['cefotax 1g im', 'cefotax im', 'cefotax', 'سيفوتاكس', 'cefotaxime', 'سيفوتاكسيم', 'im', 'حقن عضل', 'pneumonia', 'sepsis', 'التهاب رئوي', 'ميكروب دم', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم حقن عضل فقط لعدوى بكتيرية (التهاب رئوي، إنتان، بول، إلخ). الجرعة المعتادة: ١ جم كل ٨–١٢ ساعة؛ ٢ جم كل ٨ ساعات في العدوى الشديدة.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 9) rametax 1gm i.v. vial
	{
		id: 'rametax-1g-iv-vial',
		name: 'rametax 1gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 44,
		matchKeywords: ['rametax 1g iv', 'rametax iv', 'rametax', 'راميتاكس', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (Rametax) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 9b) rametax 1gm i.m. vial
	{
		id: 'rametax-1g-im-vial',
		name: 'rametax 1gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 44,
		matchKeywords: ['rametax 1g im', 'rametax im', 'rametax', 'راميتاكس', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (Rametax) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 10) rametax 500 mg i.v. vial
	{
		id: 'rametax-500mg-iv-vial',
		name: 'rametax 500 mg i.v. vial',
		genericName: 'cefotaxime',
		concentration: '500mg',
		price: 29,
		matchKeywords: ['rametax 500 iv', 'rametax iv', 'rametax 500', 'rametax', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('500mg', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 10b) rametax 500 mg i.m. vial
	{
		id: 'rametax-500mg-im-vial',
		name: 'rametax 500 mg i.m. vial',
		genericName: 'cefotaxime',
		concentration: '500mg',
		price: 29,
		matchKeywords: ['rametax 500 im', 'rametax im', 'rametax 500', 'rametax', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('500mg', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 11) cefotax (up pharma) 1 gm i.v. vial
	{
		id: 'cefotax-up-pharma-1g-iv-vial',
		name: 'cefotax (up pharma) 1 gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 48.5,
		matchKeywords: ['cefotax up pharma 1g iv', 'cefotax up iv', 'cefotax up pharma', 'cefotax up', 'up pharma', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (UP Pharma) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 11b) cefotax (up pharma) 1 gm i.m. vial
	{
		id: 'cefotax-up-pharma-1g-im-vial',
		name: 'cefotax (up pharma) 1 gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 48.5,
		matchKeywords: ['cefotax up pharma 1g im', 'cefotax up im', 'cefotax up pharma', 'cefotax up', 'up pharma', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (UP Pharma) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 12) cefotax 1gm i.v. vial - eipico
	{
		id: 'cefotax-eipico-1g-iv-vial',
		name: 'cefotax 1gm i.v. vial - eipico',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 43,
		matchKeywords: ['cefotax eipico 1g iv', 'eipico cefotax iv', 'cefotax eipico iv', 'سيفوتاكس ايبيكو وريد', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (EIPICO) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 12b) cefotax 1gm i.m. vial - eipico
	{
		id: 'cefotax-eipico-1g-im-vial',
		name: 'cefotax 1gm i.m. vial - eipico',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 43,
		matchKeywords: ['cefotax eipico 1g im', 'eipico cefotax im', 'cefotax eipico im', 'سيفوتاكس ايبيكو عضل', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (EIPICO) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 15) rametax 2gm i.v. vial
	{
		id: 'rametax-2g-iv-vial',
		name: 'rametax 2gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '2gm',
		price: 71,
		matchKeywords: ['rametax 2g iv', 'rametax iv', 'rametax 2g', 'rametax', 'cefotaxime 2g', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٢ جم حقن وريد فقط لعدوى شديدة (إنتان، سحايا، ذات رئة مستشفوية). الجرعة: ٢ جم كل ٨ ساعات؛ سحايا: حتى ٢ جم كل ٦ ساعات.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: cefotaxime('2gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 15b) rametax 2gm i.m. vial
	{
		id: 'rametax-2g-im-vial',
		name: 'rametax 2gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '2gm',
		price: 71,
		matchKeywords: ['rametax 2g im', 'rametax im', 'rametax 2g', 'rametax', 'cefotaxime 2g', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٢ جم حقن عضل فقط لعدوى شديدة. الجرعة: ٢ جم كل ٨ ساعات. يُفضّل الوريد في الإنتان والسحايا.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: cefotaxime('2gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 19) xorin 1 gm i.v. vial
	{
		id: 'xorin-1g-iv-vial',
		name: 'xorin 1 gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 48,
		matchKeywords: ['xorin 1g iv', 'xorin iv', 'xorin', 'زورين', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (Xorin) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 19b) xorin 1 gm i.m. vial
	{
		id: 'xorin-1g-im-vial',
		name: 'xorin 1 gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 48,
		matchKeywords: ['xorin 1g im', 'xorin im', 'xorin', 'زورين', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (Xorin) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 30) hebitaxime 500 mg i.v. vial
	{
		id: 'hebitaxime-500mg-iv-vial',
		name: 'hebitaxime 500 mg i.v. vial',
		genericName: 'cefotaxime',
		concentration: '500mg',
		price: 29,
		matchKeywords: ['hebitaxime 500 iv', 'hebitaxime iv', 'hebitaxime 500', 'hebitaxime', 'هيبيتكسيم', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('500mg', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 30b) hebitaxime 500 mg i.m. vial
	{
		id: 'hebitaxime-500mg-im-vial',
		name: 'hebitaxime 500 mg i.m. vial',
		genericName: 'cefotaxime',
		concentration: '500mg',
		price: 29,
		matchKeywords: ['hebitaxime 500 im', 'hebitaxime im', 'hebitaxime 500', 'hebitaxime', 'هيبيتكسيم', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('500mg', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 31) hebitaxime 1 gm i.v. vial
	{
		id: 'hebitaxime-1g-iv-vial',
		name: 'hebitaxime 1 gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 45,
		matchKeywords: ['hebitaxime 1g iv', 'hebitaxime iv', 'hebitaxime 1g', 'hebitaxime', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ١ جم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 31b) hebitaxime 1 gm i.m. vial
	{
		id: 'hebitaxime-1g-im-vial',
		name: 'hebitaxime 1 gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 45,
		matchKeywords: ['hebitaxime 1g im', 'hebitaxime im', 'hebitaxime 1g', 'hebitaxime', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ١ جم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 36) cefotax 500mg i.v. vial (eipico)
	{
		id: 'cefotax-eipico-500mg-iv-vial',
		name: 'cefotax 500mg i.v. vial (eipico)',
		genericName: 'cefotaxime',
		concentration: '500mg',
		price: 29,
		matchKeywords: ['cefotax 500 eipico iv', 'eipico cefotax 500 iv', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('500mg', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 36b) cefotax 500mg i.m. vial (eipico)
	{
		id: 'cefotax-eipico-500mg-im-vial',
		name: 'cefotax 500mg i.m. vial (eipico)',
		genericName: 'cefotaxime',
		concentration: '500mg',
		price: 29,
		matchKeywords: ['cefotax 500 eipico im', 'eipico cefotax 500 im', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('500mg', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 56) ceforan 1 gm i.v. vial
	{
		id: 'ceforan-1g-iv-vial',
		name: 'ceforan 1 gm i.v. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 41,
		matchKeywords: ['ceforan 1g iv', 'ceforan iv', 'ceforan', 'سيفوران', 'cefotaxime', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (Ceforan) حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
	// 56b) ceforan 1 gm i.m. vial
	{
		id: 'ceforan-1g-im-vial',
		name: 'ceforan 1 gm i.m. vial',
		genericName: 'cefotaxime',
		concentration: '1gm',
		price: 41,
		matchKeywords: ['ceforan 1g im', 'ceforan im', 'ceforan', 'سيفوران', 'cefotaxime', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفوتاكسيم (Ceforan) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: cefotaxime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// ==========================================
	// CEFTAZIDIME (Injectables)
	// ==========================================

	// 24) cefidime 1 gm i.v. vial
	{
		id: 'cefidime-1g-im-iv-vial',
		name: 'cefidime 1 gm i.v. vial',
		genericName: 'ceftazidime',
		concentration: '1gm',
		price: 53,
		matchKeywords: ['cefidime 1g iv', 'cefidime iv', 'cefidime 1g', 'cefidime', 'سيفيديم', 'ceftazidime', 'سيفتازيديم', 'iv', 'حقن وريد', 'pseudomonas', 'sudomonas', 'hospital infection', 'سودوموناس', 'عدوى مستشفيات', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم حقن وريد فقط (يغطي سودوموناس). الجرعة: ١–٢ جم كل ٨ ساعات؛ عدوى شديدة/محايدة المناعة: ٢ جم كل ٨ ساعات. المدة: ٧–١٠ أيام | صدر/مستشفيات: ١٠–١٤ يوم.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// cefidime 1 gm i.m. vial
	{
		id: 'cefidime-1g-im-vial',
		name: 'cefidime 1 gm i.m. vial',
		genericName: 'ceftazidime',
		concentration: '1gm',
		price: 53,
		matchKeywords: ['cefidime 1g im', 'cefidime im', 'cefidime 1g', 'cefidime', 'سيفيديم', 'ceftazidime', 'سيفتازيديم', 'im', 'حقن عضل', 'pseudomonas', 'sudomonas', 'hospital infection', 'سودوموناس', 'عدوى مستشفيات', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم حقن عضل فقط (يغطي سودوموناس). الجرعة: ١–٢ جم كل ٨ ساعات. المدة: ٧–١٠ أيام.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// 26) cefzim 1 gm i.v. vial
	{
		id: 'cefzim-1g-vial',
		name: 'cefzim 1 gm i.v. vial',
		genericName: 'ceftazidime',
		concentration: '1gm',
		price: 59,
		matchKeywords: ['cefzim 1g iv', 'cefzim iv', 'cefzim 1g', 'cefzim', 'سيفزيم', 'ceftazidime', 'iv', 'حقن وريد', 'pseudomonas', 'سودوموناس', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم (Cefzim) حقن وريد فقط (يغطي سودوموناس). الجرعة: ١–٢ جم كل ٨ ساعات. المدة: ٧–١٠ أيام.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// cefzim 1 gm i.m. vial
	{
		id: 'cefzim-1g-im-vial',
		name: 'cefzim 1 gm i.m. vial',
		genericName: 'ceftazidime',
		concentration: '1gm',
		price: 59,
		matchKeywords: ['cefzim 1g im', 'cefzim im', 'cefzim 1g', 'cefzim', 'سيفزيم', 'ceftazidime', 'im', 'حقن عضل', 'pseudomonas', 'سودوموناس', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم (Cefzim) حقن عضل فقط (يغطي سودوموناس). الجرعة: ١–٢ جم كل ٨ ساعات. المدة: ٧–١٠ أيام.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// 27) cefzim 500mg i.v. vial
	{
		id: 'cefzim-500mg-vial',
		name: 'cefzim 500mg i.v. vial',
		genericName: 'ceftazidime',
		concentration: '500mg',
		price: 37,
		matchKeywords: ['cefzim 500 iv', 'cefzim iv', 'cefzim 500', 'cefzim', 'ceftazidime 500', 'iv', 'حقن وريد', 'سيفزيم ٥٠٠', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('500mg', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// cefzim 500mg i.m. vial
	{
		id: 'cefzim-500mg-im-vial',
		name: 'cefzim 500mg i.m. vial',
		genericName: 'ceftazidime',
		concentration: '500mg',
		price: 37,
		matchKeywords: ['cefzim 500 im', 'cefzim im', 'cefzim 500', 'cefzim', 'ceftazidime 500', 'im', 'حقن عضل', 'سيفزيم ٥٠٠', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('500mg', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// 42) fortazedim 1 gm i.v. vial
	{
		id: 'fortazedim-1g-vial',
		name: 'fortazedim 1 gm i.v. vial',
		genericName: 'ceftazidime anhydrous',
		concentration: '1gm',
		price: 59,
		matchKeywords: ['fortazedim 1g iv', 'fortazedim iv', 'fortazedim 1g', 'fortazedim', 'فورتازيديم', 'ceftazidime', 'iv', 'حقن وريد', 'pseudomonas', 'سودوموناس', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم (Fortazedim) حقن وريد فقط (يغطي سودوموناس). الجرعة: ١–٢ جم كل ٨ ساعات. المدة: ٧–١٠ أيام.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// fortazedim 1 gm i.m. vial
	{
		id: 'fortazedim-1g-im-vial',
		name: 'fortazedim 1 gm i.m. vial',
		genericName: 'ceftazidime anhydrous',
		concentration: '1gm',
		price: 59,
		matchKeywords: ['fortazedim 1g im', 'fortazedim im', 'fortazedim 1g', 'fortazedim', 'فورتازيديم', 'ceftazidime', 'im', 'حقن عضل', 'pseudomonas', 'سودوموناس', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم (Fortazedim) حقن عضل فقط (يغطي سودوموناس). الجرعة: ١–٢ جم كل ٨ ساعات. المدة: ٧–١٠ أيام.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// 43) fortazedim 500 mg i.v. vial
	{
		id: 'fortazedim-500mg-vial',
		name: 'fortazedim 500 mg i.v. vial',
		genericName: 'ceftazidime anhydrous',
		concentration: '500mg',
		price: 34,
		matchKeywords: ['fortazedim 500 iv', 'fortazedim iv', 'fortazedim 500', 'fortazedim', 'ceftazidime 500', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('500mg', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// fortazedim 500 mg i.m. vial
	{
		id: 'fortazedim-500mg-im-vial',
		name: 'fortazedim 500 mg i.m. vial',
		genericName: 'ceftazidime anhydrous',
		concentration: '500mg',
		price: 34,
		matchKeywords: ['fortazedim 500 im', 'fortazedim im', 'fortazedim 500', 'fortazedim', 'ceftazidime 500', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'سيفتازيديم ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('500mg', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// 44) fortum 1 gm i.v. vial
	{
		id: 'fortum-1g-vial',
		name: 'fortum 1 gm i.v. vial',
		genericName: 'ceftazidime',
		concentration: '1gm',
		price: 106,
		matchKeywords: ['fortum 1g iv', 'fortum iv', 'fortum 1g', 'fortum', 'فورتُم', 'ceftazidime', 'iv', 'حقن وريد', 'pseudomonas', 'سودوموناس', '#antibiotics', '#cephalosporin'],
		usage: 'فورتُم (سيفتازيديم) حقن وريد فقط لعدوى شديدة/سودوموناس. الجرعة: ١–٢ جم كل ٨ ساعات؛ محايدو المناعة: ٢ جم كل ٨ ساعات. المدة: ٧–١٤ يوم حسب الموضع.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// fortum 1 gm i.m. vial
	{
		id: 'fortum-1g-im-vial',
		name: 'fortum 1 gm i.m. vial',
		genericName: 'ceftazidime',
		concentration: '1gm',
		price: 106,
		matchKeywords: ['fortum 1g im', 'fortum im', 'fortum 1g', 'fortum', 'فورتُم', 'ceftazidime', 'im', 'حقن عضل', 'pseudomonas', 'سودوموناس', '#antibiotics', '#cephalosporin'],
		usage: 'فورتُم (سيفتازيديم) حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('1gm', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// 57) fortum 500mg i.v. vial
	{
		id: 'fortum-500mg-vial',
		name: 'fortum 500mg i.v. vial',
		genericName: 'ceftazidime',
		concentration: '500mg',
		price: 66,
		matchKeywords: ['fortum 500 iv', 'fortum iv', 'fortum 500', 'fortum', 'ceftazidime 500', 'iv', 'حقن وريد', '#antibiotics', '#cephalosporin'],
		usage: 'فورتُم (سيفتازيديم) ٥٠٠ مجم حقن وريد فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('500mg', 'IV'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// fortum 500mg i.m. vial
	{
		id: 'fortum-500mg-im-vial',
		name: 'fortum 500mg i.m. vial',
		genericName: 'ceftazidime',
		concentration: '500mg',
		price: 66,
		matchKeywords: ['fortum 500 im', 'fortum im', 'fortum 500', 'fortum', 'ceftazidime 500', 'im', 'حقن عضل', '#antibiotics', '#cephalosporin'],
		usage: 'فورتُم (سيفتازيديم) ٥٠٠ مجم حقن عضل فقط حسب التشخيص.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: ceftazidime('500mg', 'IM'),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS, 'يغطي بكتيريا السودوموناس (Pseudomonas).'],
	},

	// ==========================================
	// CEFIXIME (Oral)
	// ==========================================

	// 7) suprax 100mg/5 ml susp. 60ml
	{
		id: 'suprax-100mg-5ml-susp-60ml',
		name: 'suprax 100mg/5 ml susp. 60ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 131,
		matchKeywords: ['suprax 100', 'suprax suspension', 'suprax', 'سوبراكس', 'cefixime', 'سيفيكسيم', 'uti', 'typhoid', 'otitis media', 'التهاب بول', 'تيفود', 'التهاب اذن', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم معلق للأطفال لالتهابات الأذن الوسطى/الحلق/المسالك البولية/تيفود.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		// 100mg/5ml = 20mg/ml
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 16) suprax 100mg/5 ml susp. 30ml
	{
		id: 'suprax-100mg-5ml-susp-30ml',
		name: 'suprax 100mg/5 ml susp. 30ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 95,
		matchKeywords: ['suprax 100 30ml', 'suprax 30ml', 'suprax', 'cefixime', 'سوبراكس ٣٠', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم معلق (حجم أصغر) للأطفال لالتهابات الأذن الوسطى/الحلق/المسالك البولية.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 25) cefixime 100mg/5ml susp. 60ml
	{
		id: 'cefixime-100mg-5ml-susp-60ml',
		name: 'cefixime 100mg/5ml susp. 60ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 63,
		matchKeywords: ['cefixime 100 susp 60', 'cefixime suspension', 'سيفيكسيم شراب', 'uti', 'typhoid', 'التهاب بول', 'تيفود', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم معلق للأطفال لالتهابات الأذن الوسطى/الحلق/المسالك البولية/تيفود.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 35) cefixime 100mg/5ml susp. 30 ml
	{
		id: 'cefixime-100mg-5ml-susp-30ml',
		name: 'cefixime 100mg/5ml susp. 30 ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 43,
		matchKeywords: ['cefixime 100 susp 30', 'cefixime 30ml', 'سيفيكسيم ٣٠', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم معلق (حجم أصغر) للأطفال لالتهابات الأذن الوسطى/الحلق/المسالك البولية.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 21) wideprex 100mg/5ml susp. 60ml
	{
		id: 'wideprex-100mg-5ml-susp-60ml',
		name: 'wideprex 100mg/5ml susp. 60ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 83,
		matchKeywords: ['wideprex 100', 'wideprex', 'وايدبريكس', 'cefixime', 'سيفيكسيم', 'uti', 'typhoid', 'التهاب بول', 'تيفود', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم معلق للأطفال (Wideprex) لالتهابات الأذن الوسطى/الحلق/المسالك البولية/تيفود.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 29) flavicef 100mg/5ml pd. for oral susp. 30ml
	{
		id: 'flavicef-100mg-5ml-powder-susp-30ml',
		name: 'flavicef 100mg/5ml pd. for oral susp. 30ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 43,
		matchKeywords: ['flavicef 100', 'flavicef 30', 'flavicef', 'فلاڤيسيف', 'cefixime', 'سيفيكسيم', 'powder for suspension', 'بودرة معلق', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم بودرة تُحضّر لمعلق (Flavicef) للأطفال لالتهابات الأذن الوسطى/الحلق/المسالك البولية.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Powder',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 41) flavicef 100mg/5ml pd. for oral susp. 60ml
	{
		id: 'flavicef-100mg-5ml-powder-susp-60ml',
		name: 'flavicef 100mg/5ml pd. for oral susp. 60ml',
		genericName: 'cefixime',
		concentration: '100mg/5ml',
		price: 83,
		matchKeywords: ['flavicef 100', 'flavicef 60', 'flavicef', 'cefixime', 'powder for suspension', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم بودرة تُحضّر لمعلق (حجم أكبر) لالتهابات الأذن الوسطى/الحلق/المسالك البولية.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Powder',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		calculationRule: (w, a) => cefiximePedsOnceDaily(w, a, 20),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// 8) suprax 400 mg 5 caps.
	{
		id: 'suprax-400mg-5-caps',
		name: 'suprax 400 mg 5 caps.',
		genericName: 'cefixime',
		concentration: '400mg',
		price: 159,
		matchKeywords: ['suprax 400 caps', 'suprax 400', 'suprax', 'سوبراكس ٤٠٠', 'cefixime 400', 'adult dose', 'uti', 'typhoid', 'التهاب بول', 'تيفود', '#antibiotics', '#cephalosporin'],
		usage: 'سيفيكسيم كبسولات للبالغين لالتهابات المسالك البولية/الأذن الوسطى/الحلق/تيفود.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => '٤٠٠ مجم (١ كبسولة) مرة يومياً بدون اعتبار للأكل لمدة ٧–١٤ يوم',
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},

	// ==========================================
	// CEFDINIR (Oral)
	// ==========================================

	// 58) maxdinir 125mg/5ml 60ml susp
	{
		id: 'maxdinir-125mg-5ml-susp-60ml',
		name: 'maxdinir 125mg/5ml 60ml susp',
		genericName: 'cefdinir',
		concentration: '125mg/5ml',
		price: 70,
		matchKeywords: ['maxdinir 125', 'maxdinir', 'ماكسدينير', 'cefdinir', 'سيفدينير', 'otitis media', 'sinusitis', 'tonsillitis', 'التهاب اذن', 'التهاب جيوب', 'التهاب لوز', '#antibiotics', '#cephalosporin'],
		usage: 'سيفدينير معلق للأطفال لالتهابات الأذن الوسطى/الجيوب/الحلق.',
		timing: 'مرة يومياً – ٥–١٠ أيام',
		category: Category.CEPHALOSPORINS_G3,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 40,
		// 125mg/5ml = 25mg/ml
		calculationRule: (w, a) => cefdinirPedsOnceDaily(w, a, 25),
		warnings: [...COMMON_CEPHALOSPORIN_WARNINGS],
	},
];
