import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const CONTRACEPTION_WARNINGS = [
  'لا يُستخدم أثناء الحمل أو عند الاشتباه في الحمل.',
  'يزيد التدخين (خصوصاً >35 سنة) من خطر الجلطات مع الحبوب المركبة.',
  'بعض الأدوية تقلل الفاعلية (محفزات إنزيمات الكبد مثل rifampicin وبعض أدوية الصرع).',
  'لا يحمي من الأمراض المنقولة جنسياً.',
];

const combined21 = fixed('١ قرص مرة يومياً في نفس الوقت – ٢١ يوم ثم ٧ أيام راحة');

const combined28 = fixed('١ قرص مرة يومياً في نفس الوقت – ٢٨ يوم بدون توقف حسب ترتيب الشريط');

const pop28 = fixed('١ قرص مرة يومياً في نفس الوقت – ٢٨ يوم بدون توقف');

const depoIM = fixed('حقنة ١٥٠ مجم عضل – كل ١٢ أسبوع (٣ أشهر)');

const monthlyIM = fixed('أمبول حقنة عضل – مرة كل ٤ أسابيع في نفس اليوم');

const emergencyLNG = fixed('٢ كبسولة فموياً جرعة واحدة بأسرع وقت خلال ٧٢ ساعة من العلاقة – أو كبسولة ثم أخرى بعد ١٢ ساعة');

const CONTRACEPTIVES_GROUP_RAW: Medication[] = [
  {
    id: 'contraception-1',
    name: 'yasmin 21 f.c.tabs.',
    genericName: 'ethinylestradiol + drospirenone',
    concentration: '0.03mg/3mg',
    price: 250,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['yasmin', 'ياسمين', 'drospirenone', 'ethinylestradiol'],
  },
  {
    id: 'contraception-2',
    name: 'yasmin 21 sugar c.tabs.',
    genericName: 'ethinylestradiol + drospirenone',
    concentration: '0.03mg/3mg',
    price: 290,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['yasmin', 'ياسمين'],
  },
  {
    id: 'contraception-3',
    name: 'yasmin plus 28 f.c.tabs.',
    genericName: 'ethinylestradiol + drospirenone',
    concentration: '0.03mg/3mg',
    price: 340,
    usage: 'حبوب منع حمل مركبة (28 قرص).',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['yasmin plus', 'ياسمين بلس'],
  },
  {
    id: 'contraception-4',
    name: 'yazz 28 f.c.tabs.',
    genericName: 'ethinylestradiol + drospirenone',
    concentration: '0.02mg/3mg',
    price: 340,
    usage: 'حبوب منع حمل مركبة (28 قرص).',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['yazz', 'ياز'],
  },
  {
    id: 'contraception-5',
    name: 'gynera 21 sugar c.tabs.',
    genericName: 'ethinylestradiol + gestodene',
    concentration: '0.03mg/0.075mg',
    price: 135,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['gynera', 'جينيرا', 'gestodene'],
  },
  {
    id: 'contraception-6',
    name: 'gynera plus 28 sugar c.tabs.',
    genericName: 'ethinylestradiol + gestodene',
    concentration: '0.03mg/0.075mg',
    price: 175,
    usage: 'حبوب منع حمل مركبة (28 قرص).',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['gynera plus', 'جينيرا بلس'],
  },
  {
    id: 'contraception-7',
    name: 'cycloproginova 21 s.c.tabs.',
    genericName: 'estradiol valerate + norgestrel',
    concentration: 'mixed tablets',
    price: 140,
    usage: 'تنظيم الدورة/علاج اضطرابات الدورة (يُستخدم حسب التشخيص والحالة وقد يعمل كمنظم هرموني).',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['cycloproginova', 'سيكلوبروجينوفا'],
  },
  {
    id: 'contraception-8',
    name: 'cycloproginova 42 s.c.tabs.',
    genericName: 'estradiol valerate + norgestrel',
    concentration: 'mixed tablets',
    price: 200,
    usage: 'تنظيم الدورة/علاج اضطرابات الدورة (حسب التشخيص والحالة).',
    timing: 'مرة يومياً – حسب الشريط',
    category: Category.CONTRACEPTION,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('١ قرص مرة يومياً في نفس الوقت حسب ترتيب الشريط – عبوة ممتدة حسب تعليمات العبوة'),
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['cycloproginova', '42'],
  },
  {
    id: 'contraception-9',
    name: 'microcept 21 f.c.tab.',
    genericName: 'ethinylestradiol + levonorgestrel',
    concentration: '0.03mg/0.15mg',
    price: 95,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['microcept', 'ميكروسيبت'],
  },
  {
    id: 'contraception-10',
    name: 'microcept plus 28 f.c.tab.',
    genericName: 'ethinylestradiol + levonorgestrel',
    concentration: '0.03mg/0.15mg',
    price: 125,
    usage: 'حبوب منع حمل مركبة (28 قرص).',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['microcept plus', 'ميكروسيبت بلس'],
  },
  {
    id: 'contraception-11',
    name: 'marvelon 21 tabs.',
    genericName: 'ethinylestradiol + desogestrel',
    concentration: '0.03mg/0.15mg',
    price: 160,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['marvelon', 'مارفيلون'],
  },
  {
    id: 'contraception-12',
    name: 'marvelon 21 f.c.tabs.',
    genericName: 'ethinylestradiol + desogestrel',
    concentration: '0.03mg/0.15mg',
    price: 160,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['marvelon', 'f.c'],
  },
  {
    id: 'contraception-13',
    name: 'regulon 21 tabs.',
    genericName: 'ethinylestradiol + desogestrel',
    concentration: '0.03mg/0.15mg',
    price: 105,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['regulon', 'ريجولون'],
  },
  {
    id: 'contraception-14',
    name: 'regulon 21 f.c.tabs.',
    genericName: 'ethinylestradiol + desogestrel',
    concentration: '0.03mg/0.15mg',
    price: 110,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['regulon', 'f.c'],
  },
  {
    id: 'contraception-15',
    name: 'regulon plus 28 f.c.tabs.',
    genericName: 'ethinylestradiol + desogestrel',
    concentration: '0.03mg/0.15mg',
    price: 140,
    usage: 'حبوب منع حمل مركبة (28 قرص).',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['regulon plus', 'ريجولون بلس'],
  },
  {
    id: 'contraception-16',
    name: 'novalona 21 f.c.tabs.',
    genericName: 'ethinylestradiol + desogestrel',
    concentration: '0.03mg/0.15mg',
    price: 110,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['novalona', 'نوفالونا'],
  },
  {
    id: 'contraception-17',
    name: 'jessie 28 tablets.',
    genericName: 'ethinylestradiol + drospirenone',
    concentration: '0.02mg/3mg',
    price: 250,
    usage: 'حبوب منع حمل مركبة (28 قرص).',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['jessie', 'جيسي'],
  },
  {
    id: 'contraception-18',
    name: 'clexane 21 s.c.tabs.',
    genericName: 'ethinylestradiol + levonorgestrel',
    concentration: '0.03mg/0.15mg',
    price: 90,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['clexane 21', 'كليكسان 21'],
  },
  {
    id: 'contraception-19',
    name: 'centuryon 21 tablets.',
    genericName: 'ethinylestradiol + levonorgestrel',
    concentration: '0.03mg/0.15mg',
    price: 55,
    usage: 'حبوب منع حمل مركبة.',
    timing: 'مرة يومياً – ٢١ يوم',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined21,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['centuryon', 'سنتوريون'],
  },
  {
    id: 'contraception-20',
    name: 'climodien 28 f.c.tabs.',
    genericName: 'estradiol valerate + dienogest',
    concentration: 'variable tablets',
    price: 260,
    usage: 'تنظيم/علاج أعراض هرمونية (حسب التشخيص والحالة) وقد يؤثر على الدورة.',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 720,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: CONTRACEPTION_WARNINGS,
    matchKeywords: ['climodien', 'كليمودين'],
  },
  {
    id: 'contraception-21',
    name: 'norigyncin 50/5mg i.m amp.',
    genericName: 'estradiol valerate + norethisterone enanthate',
    concentration: '50mg/5mg',
    price: 50,
    usage: 'مانع حمل حقن شهري (حسب التشخيص والحالة).',
    timing: 'حقنة – مرة كل ٤ أسابيع',
    category: Category.CONTRACEPTION,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: monthlyIM,
    warnings: [...CONTRACEPTION_WARNINGS, 'يُمنع في أمراض كبد شديدة أو تاريخ جلطات إلا بتقييم طبي.'],
    matchKeywords: ['norigyncin', 'نورجينسين', 'monthly injection'],
  },
  {
    id: 'contraception-22',
    name: 'contraplan ii 0.75 mg 4 caps.',
    genericName: 'levonorgestrel',
    concentration: '0.75mg',
    price: 55,
    usage: 'وسيلة طارئة لمنع الحمل بعد العلاقة.',
    timing: 'جرعة واحدة – خلال ٧٢ ساعة',
    category: Category.CONTRACEPTION,
    form: 'Capsules',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: emergencyLNG,
    warnings: ['لا يُستخدم كوسيلة منتظمة لمنع الحمل.', 'قد يسبب غثياناً أو دوخة أو اضطراباً بالدورة.'],
    matchKeywords: ['contraplan', 'كونترابلان', 'emergency', 'levonorgestrel'],
  },
  {
    id: 'contraception-23',
    name: 'oxyprogest 150mg/ml amp.',
    genericName: 'medroxyprogesterone acetate',
    concentration: '150mg/ml',
    price: 30,
    usage: 'حقنة منع حمل طويلة المفعول (ديبو) أو حسب التشخيص والحالة.',
    timing: 'حقنة – كل ١٢ أسبوع',
    category: Category.CONTRACEPTION,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: depoIM,
    warnings: ['قد يسبب اضطراباً بالدورة أو زيادة وزن.', 'لا يُستخدم أثناء الحمل.'],
    matchKeywords: ['oxyprogest', 'ديبو', 'medroxyprogesterone'],
  },
  {
    id: 'contraception-24',
    name: 'oxyprogest 150mg/ml vial',
    genericName: 'medroxyprogesterone acetate',
    concentration: '150mg/ml',
    price: 30,
    usage: 'حقنة منع حمل طويلة المفعول (ديبو) أو حسب التشخيص والحالة.',
    timing: 'حقنة – كل ١٢ أسبوع',
    category: Category.CONTRACEPTION,
    form: 'Vial',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: depoIM,
    warnings: ['قد يسبب اضطراباً بالدورة أو زيادة وزن.', 'لا يُستخدم أثناء الحمل.'],
    matchKeywords: ['oxyprogest', 'vial'],
  },
  {
    id: 'contraception-25',
    name: 'lactevenor 0.03mg 35 coated tabs.',
    genericName: 'levonorgestrel',
    concentration: '0.03mg',
    price: 30,
    usage: 'حبوب منع حمل أحادية الهرمون (للرضاعة/POP) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – بدون توقف',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: pop28,
    warnings: ['لا يحمي من الأمراض المنقولة جنسياً.', 'أعيدي التقييم في حالات النزيف غير المعتاد.'],
    matchKeywords: ['lactevenor', 'لاكتيفينور', 'levonorgestrel pop'],
  },
  {
    id: 'contraception-26',
    name: 'microlut 0.03mg 35 coated tabs.',
    genericName: 'levonorgestrel',
    concentration: '0.03mg',
    price: 78,
    usage: 'حبوب منع حمل أحادية الهرمون (POP) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – بدون توقف',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: pop28,
    warnings: ['لا يُستخدم أثناء الحمل.', 'أعيدي التقييم في أمراض الكبد الشديدة.'],
    matchKeywords: ['microlut', 'ميكرولوت'],
  },
  {
    id: 'contraception-27',
    name: 'cerazette 75mcg 28 tablets.',
    genericName: 'desogestrel',
    concentration: '75mcg',
    price: 185,
    usage: 'حبوب منع حمل أحادية الهرمون (POP).',
    timing: 'مرة يومياً – بدون توقف',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: pop28,
    warnings: ['لا يحمي من الأمراض المنقولة جنسياً.'],
    matchKeywords: ['cerazette', 'سيرازيت'],
  },
  {
    id: 'contraception-28',
    name: 'slynd 4mg 28 f.c.tabs.',
    genericName: 'drospirenone',
    concentration: '4mg',
    price: 490,
    usage: 'حبوب منع حمل أحادية الهرمون (POP) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 660,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: combined28,
    warnings: ['لا يُستخدم أثناء الحمل.', 'أعيدي التقييم في أمراض الكلى أو ارتفاع البوتاسيوم.'],
    matchKeywords: ['slynd', 'سليند', 'drospirenone 4mg'],
  },
  {
    id: 'contraception-29',
    name: 'visanne 2mg 28 tabs.',
    genericName: 'dienogest',
    concentration: '2mg',
    price: 515,
    usage: 'علاج الانتباذ البطاني الرحمي/آلامه (حسب التشخيص والحالة).',
    timing: 'مرة يومياً – بدون توقف',
    category: Category.CONTRACEPTION,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 720,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('١ قرص مرة يومياً في نفس الوقت – باستمرار بدون فاصل – حسب التشخيص والمدة المقررة'),
    warnings: ['لا يُستخدم أثناء الحمل.', 'ليس مخصصاً كوسيلة منع حمل وحيدة إلا بعد إعادة تقييم.'],
    matchKeywords: ['visanne', 'فيزان', 'dienogest'],
  },
  {
    id: 'contraception-30',
    name: 'betafem 2mg 28 f.c.tabs.',
    genericName: 'dienogest',
    concentration: '2mg',
    price: 340,
    usage: 'علاج الانتباذ البطاني الرحمي/اضطرابات الدورة (حسب التشخيص والحالة).',
    timing: 'مرة يومياً – بدون توقف',
    category: Category.CONTRACEPTION,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 720,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('١ قرص مرة يومياً في نفس الوقت – باستمرار بدون فاصل – حسب التشخيص والمدة المقررة'),
    warnings: ['لا يُستخدم أثناء الحمل.', 'قد يسبب نزيفاً غير منتظم أو صداعاً.'],
    matchKeywords: ['betafem', 'بيتا فيم', 'dienogest 2mg'],
  },
];

export const CONTRACEPTIVES_GROUP: Medication[] = enhanceGynMedicationList(CONTRACEPTIVES_GROUP_RAW);
