import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const PROGESTOGEN_WARNINGS = [
  'لاضطرابات الدورة/تثبيت الحمل/علاج هرموني؛ الجرعة والمدة حسب التشخيص والتحاليل.',
  'قد يسبب نعاس/دوخة (خصوصاً البروجستيرون الميكرونايزد)؛ يفضل أخذه ليلاً.',
  'نزيف شديد أو ألم شديد أو أعراض جلطة: أعيدي التقييم فوراً.',
];

const PROGESTERONE_PROGESTOGENS_GROUP_RAW: Medication[] = [
  {
    id: 'lentojeston-250mg-ml-im-amp',
    name: 'lentojeston 250mg/ml i.m. amp.',
    genericName: 'hydroxyprogesterone',
    concentration: '250mg/ml',
    price: 27,
    usage: 'بروجستوجين/هرمون (حقن) حسب التشخيص.',
    timing: 'حقنة في اليوم المحدد من الدورة',
    category: Category.PROGESTOGENS,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('أمبول ٢٥٠ مجم حقنة عضل في اليوم المحدد من الدورة – حسب التشخيص والتحاليل'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['lentojeston', 'لينتوجستون', 'hydroxyprogesterone'],
  },
  {
    id: 'duphaston-10mg-60-fc-tabs',
    name: 'duphaston 10 mg 60 f.c.tabs.',
    genericName: 'dydrogesterone',
    concentration: '10mg (60 f.c. tablets)',
    price: 386,
    usage: 'بروجستوجين لتنظيم الدورة/دعم الطور الأصفر حسب التشخيص والحالة.',
    timing: 'مرة إلى مرتين يومياً – في الأيام المحددة من الدورة',
    category: Category.PROGESTOGENS,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 720,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ١٠ مجم مرة إلى مرتين يومياً بعد الأكل – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['duphaston', 'دوفاستون', 'dydrogesterone'],
  },
  {
    id: 'progest-100mg-24-oral-vaginal-caps',
    name: 'progest 100mg 24 oral/ vaginal caps.',
    genericName: 'progesterone micronized',
    concentration: '100mg (24 capsules)',
    price: 110,
    usage: 'بروجستيرون ميكرونايزد (فموي/مهبلي) حسب التشخيص والحالة.',
    timing: 'ليلاً قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Capsules',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة ١٠٠ مجم مرة إلى مرتين يومياً فموياً أو مهبلياً ليلاً قبل النوم – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['progest 100', 'بروجست', 'progesterone micronized'],
  },
  {
    id: 'prontogest-100mg-2ml-10-im-amp',
    name: 'prontogest 100mg/2ml 10 im ampoule',
    genericName: 'progesterone',
    concentration: '100mg/2ml (10 ampoules)',
    price: 240,
    usage: 'بروجستيرون حقن عضل حسب التشخيص والحالة.',
    timing: 'حقنة يومياً أو يوماً بعد يوم',
    category: Category.PROGESTOGENS,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('أمبول ١٠٠ مجم حقنة عضل يومياً أو يوماً بعد يوم – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['prontogest 100', 'برونتوجست', 'progesterone injection'],
  },
  {
    id: 'progest-200mg-30-oral-vaginal-caps',
    name: 'progest 200mg 30 oral/ vaginal caps',
    genericName: 'progesterone micronized',
    concentration: '200mg (30 capsules)',
    price: 246,
    usage: 'بروجستيرون ميكرونايزد (فموي/مهبلي) حسب التشخيص والحالة.',
    timing: 'ليلاً قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Capsules',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة ٢٠٠ مجم مرة يومياً فموياً أو مهبلياً ليلاً قبل النوم – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['progest 200', 'progesterone 200'],
  },
  {
    id: 'prontogest-400mg-30-vaginal-pessaries',
    name: 'prontogest 400mg 30 vaginal pessaries',
    genericName: 'progesterone',
    concentration: '400mg (30 pessaries)',
    price: 372,
    usage: 'بروجستيرون مهبلي لتثبيت الحمل/دعم الطور الأصفر حسب التشخيص والحالة.',
    timing: 'ليلاً – قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Suppositories',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('لبوس ٤٠٠ مجم في المهبل ليلاً قبل النوم – مرة يومياً – حسب التشخيص والمدة المقررة'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['prontogest 400', 'pessaries', 'progesterone'],
  },
  {
    id: 'steronate-5mg-20-tab',
    name: 'steronate 5mg 20 tab',
    genericName: 'norethisterone',
    concentration: '5mg (20 tablets)',
    price: 56,
    usage: 'بروجستوجين لتنظيم/تأخير الدورة أو نزيف وظيفي حسب التشخيص والحالة.',
    timing: '٢–٣ مرات يومياً – في الأيام المحددة من الدورة',
    category: Category.PROGESTOGENS,
    form: 'Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 720,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ٥ مجم ٢–٣ مرات يومياً بعد الأكل – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['steronate', 'ستيرونات', 'norethisterone'],
  },
  {
    id: 'tonadogest-10mg-30-fc-tabs',
    name: 'tonadogest 10 mg 30 f.c. tabs.',
    genericName: 'dydrogesterone',
    concentration: '10mg (30 f.c. tablets)',
    price: 198,
    usage: 'بروجستوجين لتنظيم الدورة/دعم الطور الأصفر حسب التشخيص والحالة.',
    timing: 'مرة إلى مرتين يومياً – في الأيام المحددة من الدورة',
    category: Category.PROGESTOGENS,
    form: 'F.C. Tablets',
    minAgeMonths: 156,
    maxAgeMonths: 720,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ١٠ مجم مرة إلى مرتين يومياً بعد الأكل – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['tonadogest', 'تونادوجست', 'dydrogesterone'],
  },
  {
    id: 'lutofolone-2-amp',
    name: 'lutofolone 2 amp.',
    genericName: 'estradiol benzoate & progesterone',
    concentration: '2 ampoules',
    price: 40,
    usage: 'هرمونات نسائية (حقن) حسب التشخيص والحالة.',
    timing: 'حقنة في اليوم المحدد من الدورة',
    category: Category.FEMALE_HORMONES,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 168,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('أمبول حقنة عضل في اليوم المحدد من الدورة – حسب التشخيص والحالة'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['lutofolone', 'لوتوفولون', 'estradiol benzoate', 'progesterone'],
  },
  {
    id: 'prontogest-200mg-30-vaginal-or-rectal-pessaries',
    name: 'prontogest 200mg 30 vaginal or rectal pessaries',
    genericName: 'progesterone',
    concentration: '200mg (30 pessaries)',
    price: 192,
    usage: 'بروجستيرون (مهبلي/شرجي) حسب التشخيص والحالة.',
    timing: 'ليلاً – قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Suppositories',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('لبوس ٢٠٠ مجم في المهبل أو الشرج ليلاً قبل النوم – مرة إلى مرتين يومياً – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['prontogest 200', 'rectal', 'vaginal', 'progesterone'],
  },
  {
    id: 'hystrogest-200mg-30-soft-gelatin-caps',
    name: 'hystrogest 200mg 30 soft gelatin capsules',
    genericName: 'progesterone',
    concentration: '200mg (30 soft gelatin capsules)',
    price: 264,
    usage: 'بروجستيرون (غالباً فموي/مهبلي) حسب التشخيص والحالة.',
    timing: 'ليلاً قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة ٢٠٠ مجم مرة يومياً فموياً أو مهبلياً ليلاً قبل النوم – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['hystrogest', 'هيستروجست', 'progesterone 200'],
  },
  {
    id: 'cidolut-depot-250mg-1-amp',
    name: 'cidolut depot 250mg 1 amp.',
    genericName: 'hydroxyprogesterone caproate',
    concentration: '250mg (1 ampoule)',
    price: 35,
    usage: 'بروجستوجين طويل المفعول (حقن) حسب التشخيص والحالة.',
    timing: 'حقنة في اليوم المحدد من الدورة',
    category: Category.PROGESTOGENS,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('أمبول ٢٥٠ مجم حقنة عضل في اليوم المحدد من الدورة – حسب التشخيص والتحاليل'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['cidolut depot', 'سيدولوت ديبوت', 'hydroxyprogesterone caproate'],
  },
  {
    id: 'trisequens-novo-28-tab',
    name: 'trisequens ( novo ) 28 tab',
    genericName: 'estradiol & norethisterone',
    concentration: '28 tablets',
    price: 39,
    usage: 'علاج هرموني تعويضي (HRT) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – ٢٨ يوم',
    category: Category.FEMALE_HORMONES,
    form: 'Tablets',
    minAgeMonths: 480,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد مرة يومياً في نفس الوقت – ٢٨ يوم حسب ترتيب الشريط – بدون توقف'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['trisequens', 'ترايسيكوينس', 'estradiol', 'norethisterone'],
  },
  {
    id: 'utrocare-100mg-30-soft-gelatin-caps',
    name: 'utrocare 100mg 30 soft gelatin caps.',
    genericName: 'progesterone micronized',
    concentration: '100mg (30 soft gelatin capsules)',
    price: 126,
    usage: 'بروجستيرون ميكرونايزد حسب التشخيص والحالة.',
    timing: 'ليلاً قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة ١٠٠ مجم مرة إلى مرتين يومياً ليلاً قبل النوم – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['utrocare', 'يوتروكير', 'progesterone micronized 100'],
  },
  {
    id: 'cyclogest-400mg-15-rectal-or-vaginal-pessaries',
    name: 'cyclogest 400mg 15 rectal or vag. pessaries',
    genericName: 'progesterone',
    concentration: '400mg (15 pessaries)',
    price: 406,
    usage: 'بروجستيرون (مهبلي/شرجي) حسب التشخيص والحالة.',
    timing: 'ليلاً – قبل النوم',
    category: Category.PROGESTOGENS,
    form: 'Suppositories',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('لبوس ٤٠٠ مجم في المهبل أو الشرج ليلاً قبل النوم – مرة يومياً – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['cyclogest', 'سايكلوجيست', 'progesterone 400'],
  },
  {
    id: 'progesterone-ait-100mg-2ml-10-amp',
    name: 'progesterone-ait 100mg/ 2ml 10 amp.',
    genericName: 'progesterone micronized',
    concentration: '100mg/2ml (10 ampoules)',
    price: 160,
    usage: 'بروجستيرون حقن عضل حسب التشخيص والحالة.',
    timing: 'حقنة يومياً أو يوماً بعد يوم',
    category: Category.PROGESTOGENS,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 168,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('أمبول ١٠٠ مجم حقنة عضل يومياً أو يوماً بعد يوم – في الأيام المحددة من الدورة – حسب التشخيص'),
    warnings: PROGESTOGEN_WARNINGS,
    matchKeywords: ['progesterone-ait', 'ait', 'progesterone injection'],
  },
];

export const PROGESTERONE_PROGESTOGENS_GROUP: Medication[] = enhanceGynMedicationList(
  PROGESTERONE_PROGESTOGENS_GROUP_RAW
);
