import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const FERTILITY_WARNINGS = [
  'يُفضل المتابعة في عيادة نساء/عقم (سونار وتحاليل) لتحديد السبب والخطة.',
  'أدوية التنشيط والحقن تحتاج متابعة سونار وتحاليل.',
];

const FERTILITY_DRUGS_GROUP_RAW: Medication[] = [
  {
    id: 'letrozol-2.5mg-30-fc-tabs',
    name: 'letrozol 2.5 mg 30 f.c.tabs.',
    genericName: 'letrozole',
    concentration: '2.5mg (30 f.c. tablets)',
    price: 964,
    usage: 'مثبط أروماتاز (تنشيط تبويض) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – ٥ أيام من الدورة',
    category: Category.AROMATASE_INHIBITOR,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('قرص ٢.٥ مجم مرة يومياً فموياً – لمدة ٥ أيام (شائعاً من اليوم ٣–٧ أو ٥–٩ من الدورة) – حسب التشخيص'),
    warnings: [...FERTILITY_WARNINGS, 'لا يُستخدم أثناء الحمل أو عند الاشتباه في الحمل.'],
    matchKeywords: ['letrozol', 'ليتروزول', 'letrozole', 'ovulation induction'],
  },
  {
    id: 'tecnovula-50mg-20-tablets',
    name: 'tecnovula 50mg 20 tablets',
    genericName: 'clomiphene',
    concentration: '50mg (20 tablets)',
    price: 70,
    usage: 'منشط تبويض (Clomiphene) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – ٥ أيام من الدورة',
    category: Category.OVULATION_INDUCER,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('قرص ٥٠ مجم مرة يومياً فموياً – لمدة ٥ أيام من الدورة – حسب التشخيص'),
    warnings: [...FERTILITY_WARNINGS, 'قد يسبب تنشيط زائد/تكيسات/صداع أو اضطراب إبصار.'],
    matchKeywords: ['tecnovula', 'تكنوفولا', 'clomiphene', 'clomid'],
  },
  {
    id: 'menzoflic-fc-30-tabs',
    name: 'menzoflic f. c 30 tabs',
    genericName: 'l-arginine & l-carnitine & magnesium & vitamin c & iron',
    concentration: '30 f.c. tablets',
    price: 275,
    usage: 'مكمل لدعم الخصوبة حسب التشخيص والحالة.',
    timing: 'مرة يومياً – بعد الأكل',
    category: Category.INFERTILITY,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 900,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد مرة يومياً بعد الأكل – لمدة ٣ أشهر أو حسب التشخيص'),
    warnings: FERTILITY_WARNINGS,
    matchKeywords: ['menzoflic', 'مينزوفليك', 'fertility supplement'],
  },
  {
    id: 'kiromix-pro-10-sachets',
    name: 'kiromix pro 10 sachets',
    genericName: 'molybdenum & selenium & vitamin c & vitamin d (as listed on pack)',
    concentration: '10 sachets',
    price: 520,
    usage: 'مكمل لدعم الخصوبة/مضادات أكسدة حسب العبوة.',
    timing: 'مرة يومياً – بعد الأكل',
    category: Category.INFERTILITY,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 900,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يذاب في ماء أو عصير مرة يومياً بعد الأكل – لمدة ١٠ أيام أو حسب التشخيص'),
    warnings: FERTILITY_WARNINGS,
    matchKeywords: ['kiromix pro', 'كيروميكس', 'sachets'],
  },
  {
    id: 'carnivita-forte-30-fc-tab',
    name: 'carnivita forte 30 f.c. tab',
    genericName: 'l-carnitine l-tartarate & zinc',
    concentration: '30 f.c. tablets',
    price: 177,
    usage: 'مكمل (كارنيتين/زنك) لدعم الخصوبة/مضادات أكسدة.',
    timing: 'مرة يومياً – بعد الأكل',
    category: Category.INFERTILITY,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 900,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد مرة يومياً بعد الأكل – لمدة ٣ أشهر أو حسب التشخيص'),
    warnings: FERTILITY_WARNINGS,
    matchKeywords: ['carnivita forte', 'كارنيفينا', 'l-carnitine', 'zinc'],
  },
  {
    id: 'carnisight-30-capsule',
    name: 'carnisight 30 capsule',
    genericName: 'l-carnitine & l-arginine & co-enzyme q-10 & zinc & selenium',
    concentration: '30 capsules',
    price: 330,
    usage: 'مكمل لدعم خصوبة الرجال/مضادات أكسدة.',
    timing: 'مرة يومياً – بعد الأكل',
    category: Category.MALE_FERTILITY,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 900,
    minWeight: 50,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرة يومياً بعد الأكل – لمدة ٣ أشهر على الأقل'),
    warnings: FERTILITY_WARNINGS,
    matchKeywords: ['carnisight', 'كارنسايت', 'male fertility', 'coq10'],
  },
  {
    id: 'femapent-2.5mg-14-fc-tablets',
    name: 'femapent 2.5mg 14 f.c. tablets',
    genericName: 'letrozole',
    concentration: '2.5mg (14 f.c. tablets)',
    price: 228,
    usage: 'مثبط أروماتاز (تنشيط تبويض) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – ٥ أيام من الدورة',
    category: Category.AROMATASE_INHIBITOR,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('قرص ٢.٥ مجم مرة يومياً فموياً – لمدة ٥ أيام من الدورة – حسب التشخيص'),
    warnings: [...FERTILITY_WARNINGS, 'لا يُستخدم أثناء الحمل أو عند الاشتباه في الحمل.'],
    matchKeywords: ['femapent', 'فيمابنت', 'letrozole'],
  },
  {
    id: 'instolab-20-caps',
    name: 'instolab 20 caps.',
    genericName: 'myo-inositol & d-chiro inositol & methylfolate & chromium',
    concentration: '20 capsules',
    price: 200,
    usage: 'مكمل (إنوزيتول) لدعم التبويض/تكيس المبايض حسب التشخيص والحالة.',
    timing: 'مرة إلى مرتين يومياً – بعد الأكل',
    category: Category.INFERTILITY,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 900,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة إلى كبسولتين مرة إلى مرتين يومياً بعد الأكل – لمدة عدة أشهر حسب التشخيص'),
    warnings: FERTILITY_WARNINGS,
    matchKeywords: ['instolab', 'انستولاب', 'inositol', 'pcos'],
  },
];

export const FERTILITY_DRUGS_GROUP: Medication[] = enhanceGynMedicationList(FERTILITY_DRUGS_GROUP_RAW);
