import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const FSH_WARNINGS = [
  'يلزم متابعة سونار وتحاليل (E2، البروجستيرون) أثناء التحفيز لتعديل الجرعة وتجنب OHSS.',
  'قد يسبب فرط تنبيه المبيض (OHSS).',
  'يُحفظ في الثلاجة (٢–٨ م°).',
];

const FSH_GROUP_RAW: Medication[] = [
  {
    id: 'fostimon-150-iu-im-sc-vial',
    name: 'fostimon 150 i.u. i.m./s.c. vial',
    genericName: 'urofollitropin',
    concentration: '150 IU',
    price: 1128,
    usage: 'FSH (urofollitropin) لتنشيط التبويض. الجرعة ٧٥–٢٢٥ وحدة/يوم (أو أكثر) تُعدّل حسب الاستجابة والسونار.',
    timing: 'حقنة يومياً – حسب السونار',
    category: Category.INFERTILITY_FSH,
    form: 'Vial',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('٧٥–٢٢٥ وحدة دولية/يوم حقنة تحت الجلد أو عضل – تُعدّل حسب السونار – في الأيام المحددة من الدورة'),
    warnings: FSH_WARNINGS,
    matchKeywords: ['fostimon 150', 'فوستيمون', 'urofollitropin', 'fsh'],
  },
  {
    id: 'epigonal-75-iu-amp',
    name: 'epigonal 75 i.u. 1 amp.',
    genericName: 'follicle stimulating hormone (fsh) & lh',
    concentration: '75 IU',
    price: 286,
    usage: 'منشطات (FSH+LH) لتنشيط التبويض. الجرعة ٧٥–١٥٠ وحدة/يوم تُعدّل حسب السونار.',
    timing: 'حقنة يومياً – حسب السونار',
    category: Category.INFERTILITY,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('٧٥–١٥٠ وحدة/يوم حقنة عضل في اليوم المحدد من الدورة – حسب السونار'),
    warnings: FSH_WARNINGS,
    matchKeywords: ['epigonal', 'ايبيجونال', 'fsh', 'lh', 'infertility'],
  },
  {
    id: 'fostimon-75-iu-im-sc-vial',
    name: 'fostimon 75 i.u. i.m./s.c. vial',
    genericName: 'urofollitropin',
    concentration: '75 IU',
    price: 566,
    usage: 'FSH (urofollitropin) لتنشيط التبويض. الجرعة ٧٥–٢٢٥ وحدة/يوم (أو أكثر) تُعدّل حسب الاستجابة والسونار.',
    timing: 'حقنة يومياً – حسب السونار',
    category: Category.INFERTILITY_FSH,
    form: 'Vial',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('٧٥–٢٢٥ وحدة دولية/يوم حقنة تحت الجلد أو عضل – تُعدّل حسب السونار – في الأيام المحددة من الدورة'),
    warnings: FSH_WARNINGS,
    matchKeywords: ['fostimon 75', 'urofollitropin', 'fsh'],
  },
  {
    id: 'gonapure-150-iu-ml-im-sc-vial',
    name: 'gonapure 150 i.u./ml i.m./s.c. vial',
    genericName: 'follitropin alfa',
    concentration: '150 IU/ml',
    price: 572,
    usage: 'FSH (follitropin alfa) لتنشيط التبويض. الجرعة ٧٥–٢٢٥ وحدة/يوم تُعدّل حسب الاستجابة.',
    timing: 'حقنة يومياً – حسب السونار',
    category: Category.INFERTILITY_FSH,
    form: 'Vial',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('٧٥–٢٢٥ وحدة دولية/يوم حقنة تحت الجلد أو عضل – تُعدّل حسب السونار – في الأيام المحددة من الدورة'),
    warnings: FSH_WARNINGS,
    matchKeywords: ['gonapure 150', 'جونابيور', 'follitropin alfa', 'fsh'],
  },
  {
    id: 'gonal-f-900-iu-pen',
    name: 'gonal-f 900 i.u. pen',
    genericName: 'follitropin alfa',
    concentration: '900 IU (pen)',
    price: 8366,
    usage: 'قلم FSH لتنشيط التبويض. الجرعة ٧٥–٢٢٥ وحدة/يوم (تُضبط على القلم) حسب التشخيص والسونار.',
    timing: 'قلم يومياً – حسب السونار',
    category: Category.INFERTILITY_FSH,
    form: 'Pen',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('٧٥–٢٢٥ وحدة/يوم تُضبط على القلم – حقنة تحت الجلد يومياً في الأيام المحددة من الدورة – حسب السونار'),
    warnings: FSH_WARNINGS,
    matchKeywords: ['gonal-f 900', 'جونال اف', 'pen', 'follitropin alfa'],
  },
  {
    id: 'gonapure-75-iu-ml-im-sc-amp',
    name: 'gonapure 75 i.u./ml i.m./s.c. amp.',
    genericName: 'follitropin alfa',
    concentration: '75 IU/ml',
    price: 357,
    usage: 'FSH (follitropin alfa) لتنشيط التبويض. الجرعة ٧٥–٢٢٥ وحدة/يوم حسب الاستجابة.',
    timing: 'حقنة يومياً – حسب السونار',
    category: Category.INFERTILITY_FSH,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('٧٥–٢٢٥ وحدة دولية/يوم حقنة تحت الجلد أو عضل – تُعدّل حسب السونار – في الأيام المحددة من الدورة'),
    warnings: FSH_WARNINGS,
    matchKeywords: ['gonapure 75', 'follitropin alfa', 'fsh'],
  },
];

export const FSH_GROUP: Medication[] = enhanceGynMedicationList(FSH_GROUP_RAW);
