import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const LACTAGOGUE_WARNINGS = [
  'قد يسبب اضطراب معدة/غازات (خصوصاً الحلبة).',
  'الحذر في مرضى حساسية البقوليات أو الربو.',
  'في مرضى السكر: الحلبة قد تؤثر على سكر الدم.',
  'ألم شديد بالثدي أو حمى أو التهاب: أعيدي التقييم.',
];

const LACTAGOGUE_GROUP_RAW: Medication[] = [
  {
    id: 'lactagogue-1',
    name: 'herbana 20 caps',
    genericName: 'fenugreek & fennel & dill & caraway',
    concentration: '20 capsules',
    price: 60,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['herbana', 'هربانا', 'lactagogue', 'galactagogue', 'fenugreek', 'حلبة'],
  },
  {
    id: 'lactagogue-2',
    name: 'herbana 30 caps.',
    genericName: 'fenugreek & dill & fennel & caraway',
    concentration: '30 capsules',
    price: 120,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['herbana', 'هربانا', '30'],
  },
  {
    id: 'lactagogue-3',
    name: 'mami milk 20 caps.',
    genericName: 'fenugreek & anise & caraway & fennel',
    concentration: '20 capsules',
    price: 99,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['mami milk', 'مامي ميلك', 'anise', 'يانسون'],
  },
  {
    id: 'lactagogue-4',
    name: 'lactomax 20 caps',
    genericName: 'fenugreek & caraway oil & fennel oil',
    concentration: '20 capsules',
    price: 120,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['lactomax', 'لاكتوماكس', 'lactagauge', 'lactagogue'],
  },
  {
    id: 'lactagogue-5',
    name: 'lactomax 10 sachets',
    genericName: 'fenugreek & caraway oil & fennel oil',
    concentration: '10 sachets',
    price: 75,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يذاب في ماء أو عصير مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['lactomax sachets', 'لاكتوماكس اكياس'],
  },
  {
    id: 'lactagogue-6',
    name: 'moralin 10 sachets',
    genericName: 'fenugreek & fennel & chamomile & anise',
    concentration: '10 sachets',
    price: 97,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يذاب في ماء دافئ مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['moralin', 'مورالين', 'chamomile', 'بابونج'],
  },
  {
    id: 'lactagogue-7',
    name: 'herbolin 10 sachets',
    genericName: 'fenugreek seed extract & fennel seed extract & star anise seed extract',
    concentration: '10 sachets',
    price: 85,
    usage: 'مكمل عشبي للمساعدة في إدرار اللبن.',
    timing: 'مرتين يومياً – بعد الأكل',
    category: Category.LACTAGOGUE,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 720,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يذاب في ماء دافئ مرتين يومياً بعد الأكل – طوال فترة الرضاعة حسب الحاجة'),
    warnings: LACTAGOGUE_WARNINGS,
    matchKeywords: ['herbolin', 'هيربولين', 'star anise', 'يانسون نجمي'],
  },
];

export const LACTAGOGUE_GROUP: Medication[] = enhanceGynMedicationList(LACTAGOGUE_GROUP_RAW);
