import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const CABERGOLINE_WARNINGS = [
  'قد يسبب دوخة/هبوط ضغط خاصة عند الوقوف؛ يُفضل أخذه قبل النوم.',
  'قد يسبب غثيان—يفضل تناوله بعد الأكل.',
  'ممنوع/بحذر شديد في أمراض صمامات القلب أو تليفات رئوية؛ أعد التصوير عند الشك.',
  'الجرعة تُعدّل حسب تحليل البرولاكتين (عادة ٠.٢٥–١ مجم أسبوعياً مقسمة).',
];

const cabergolineStandard = fixed('نصف قرص ٠.٢٥ مجم فموياً بعد الأكل – مرتين أسبوعياً – تُعدّل حسب تحليل البرولاكتين (٠.٢٥–١ مجم أسبوعياً) – لمدة ٦ أشهر أو حسب التشخيص');

const PROLACTIN_INHIBITORS_GYN_GROUP_RAW: Medication[] = [
  {
    id: 'prolactin-inhibitor-1',
    name: 'dostinex 0.5 mg 2 tabs.',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 172,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['dostinex', 'دوستينيكس', 'cabergoline', 'dopamine agonist', 'prolactin inhibitor', 'هرمون الحليب'],
  },
  {
    id: 'prolactin-inhibitor-2',
    name: 'cabergamoun 0.5 mg 2 tabs.',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 78,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['cabergamoun', 'كابيرجامون', 'cabergoline'],
  },
  {
    id: 'prolactin-inhibitor-3',
    name: 'elonda 0.5mg 2 tab.',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 125,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['elonda', 'ايلوندا', 'cabergoline'],
  },
  {
    id: 'prolactin-inhibitor-4',
    name: 'hypolact 0.5 mg 2 tablets',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 103,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['hypolact', 'هايبو لاكت', 'cabergoline'],
  },
  {
    id: 'prolactin-inhibitor-5',
    name: 'jakaranda 0.5mg 4 tab',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 204,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['jakaranda', 'جاكاراندا', 'cabergoline'],
  },
  {
    id: 'prolactin-inhibitor-6',
    name: 'nostifix 0.5mg 2 tablets',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 68,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['nostifix', 'نوستيفكس', 'cabergoline'],
  },
  {
    id: 'prolactin-inhibitor-7',
    name: 'jakaranda 0.5mg 2 tab',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 102,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['jakaranda', 'جاكاراندا', '2 tab'],
  },
  {
    id: 'prolactin-inhibitor-8',
    name: 'golinosab 0.5 mg 4 tabs.',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 153,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['golinosab', 'جولينوساب', 'cabergoline'],
  },
  {
    id: 'prolactin-inhibitor-9',
    name: 'dostilact 0.5 mg 2 tabs.',
    genericName: 'cabergoline',
    concentration: '0.5mg',
    price: 105,
    usage: 'ناهض دوبامين/مثبط برولاكتين لعلاج ارتفاع هرمون الحليب.',
    timing: 'مرتين أسبوعياً – بعد الأكل',
    category: Category.PROLACTIN_INHIBITORS_GYN,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: cabergolineStandard,
    warnings: CABERGOLINE_WARNINGS,
    matchKeywords: ['dostilact', 'دوستيلاكت', 'cabergoline'],
  },
];

export const PROLACTIN_INHIBITORS_GYN_GROUP: Medication[] = enhanceGynMedicationList(PROLACTIN_INHIBITORS_GYN_GROUP_RAW);
