import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const TAMOXIFEN_WARNINGS = [
  'لعلاج/وقاية أورام الثدي (SERM)؛ الجرعة ١٠–٢٠ مجم يومياً حسب التشخيص والحالة.',
  'قد يزيد خطر الجلطات؛ أوقفيه وأعدي التقييم فوراً عند ألم/تورم بالساق أو ضيق نفس مفاجئ.',
  'قد يسبب هبات ساخنة/تغيرات بالمزاج/غثيان.',
  'يلزم متابعة دورية (تصوير/تحاليل) خصوصاً مع الاستخدام الطويل.',
];

const TAMOXIFEN_GROUP_RAW: Medication[] = [
  {
    id: 'tamoxifen-1',
    name: 'nolvadex 10mg 30 tab',
    genericName: 'tamoxifen',
    concentration: '10mg (30 tablets)',
    price: 160,
    usage: 'مضاد إستروجين (SERM) لعلاج/وقاية حسب التشخيص والحالة.',
    timing: 'مرة يومياً – في نفس الوقت',
    category: Category.ANTI_ESTROGEN,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ١٠ مجم أو ٢٠ مجم مرة يومياً فموياً في نفس الوقت – ١٠–٢٠ مجم/يوم – لمدة ٥ سنوات أو حسب التشخيص'),
    warnings: TAMOXIFEN_WARNINGS,
    matchKeywords: ['nolvadex', 'نولفاديكس', 'tamoxifen', 'anti-estrogen'],
  },
  {
    id: 'tamoxifen-2',
    name: 'tamoxifen 10mg 30 tablets',
    genericName: 'tamoxifen',
    concentration: '10mg (30 tablets)',
    price: 66,
    usage: 'مضاد إستروجين (SERM) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – في نفس الوقت',
    category: Category.ANTI_ESTROGEN,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ١٠ مجم أو ٢٠ مجم مرة يومياً فموياً في نفس الوقت – ١٠–٢٠ مجم/يوم – لمدة ٥ سنوات أو حسب التشخيص'),
    warnings: TAMOXIFEN_WARNINGS,
    matchKeywords: ['tamoxifen 10', 'تاموكسيفين 10'],
  },
  {
    id: 'tamoxifen-3',
    name: 'tamoxifen 20mg 20 tab.',
    genericName: 'tamoxifen',
    concentration: '20mg (20 tablets)',
    price: 68,
    usage: 'مضاد إستروجين (SERM) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – في نفس الوقت',
    category: Category.ANTI_ESTROGEN,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ٢٠ مجم مرة يومياً أو ١٠ مجم مرتين فموياً – ٢٠–٤٠ مجم/يوم – لمدة ٥ سنوات أو حسب التشخيص'),
    warnings: TAMOXIFEN_WARNINGS,
    matchKeywords: ['tamoxifen 20', 'تاموكسيفين 20'],
  },
  {
    id: 'tamoxifen-4',
    name: 'tamoxifen-acdima 10mg 30 tab',
    genericName: 'tamoxifen',
    concentration: '10mg (30 tablets)',
    price: 18.5,
    usage: 'مضاد إستروجين (SERM) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – في نفس الوقت',
    category: Category.ANTI_ESTROGEN,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ١٠ مجم أو ٢٠ مجم مرة يومياً فموياً في نفس الوقت – ١٠–٢٠ مجم/يوم – لمدة ٥ سنوات أو حسب التشخيص'),
    warnings: TAMOXIFEN_WARNINGS,
    matchKeywords: ['tamoxifen-acdima', 'اكديمة', 'tamoxifen'],
  },
  {
    id: 'tamoxifen-5',
    name: 'tamoxifen-ebewe 20mg 30 tab.',
    genericName: 'tamoxifen',
    concentration: '20mg (30 tablets)',
    price: 45.3,
    usage: 'مضاد إستروجين (SERM) حسب التشخيص والحالة.',
    timing: 'مرة يومياً – في نفس الوقت',
    category: Category.ANTI_ESTROGEN,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص ١٠ مجم أو ٢٠ مجم مرة يومياً فموياً في نفس الوقت – ١٠–٢٠ مجم/يوم – لمدة ٥ سنوات أو حسب التشخيص'),
    warnings: TAMOXIFEN_WARNINGS,
    matchKeywords: ['tamoxifen-ebewe', 'ايبيوي', 'tamoxifen'],
  },
];

export const TAMOXIFEN_GROUP: Medication[] = enhanceGynMedicationList(TAMOXIFEN_GROUP_RAW);
