import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const VAGINAL_ANTIFUNGAL_WARNINGS = [
  'أعراض مستمرة/متكررة أو ألم شديد/حمى: أعيدي التقييم.',
  'في الحمل: يُستخدم عند الضرورة فقط؛ كلوتريمازول/ميكونازول/نيستاتين موضعي غالباً آمن.',
  'تجنبي الدوش الداخلي أثناء العلاج.',
];

const VAGINAL_ANTIFUNGAL_GROUP_RAW: Medication[] = [
  {
    id: 'vaginal-antifungal-1',
    name: 'gynozol 400mg 3 vag. ovules',
    genericName: 'miconazole nitrate',
    concentration: '400mg (3 ovules)',
    price: 30,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynozol 400', 'جينوزول 400', 'miconazole'],
  },
  {
    id: 'vaginal-antifungal-2',
    name: 'gynoconazol 0.8% vaginal cream 30 gm',
    genericName: 'terconazole',
    concentration: '0.8% (30 gm)',
    price: 46,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynoconazol 0.8', 'جينوكنازول 0.8', 'terconazole'],
  },
  {
    id: 'vaginal-antifungal-3',
    name: 'gynoconazol 80mg 3 vag. supp',
    genericName: 'terconazole',
    concentration: '80mg (3 suppositories)',
    price: 53,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynoconazol 80', 'terconazole suppository'],
  },
  {
    id: 'vaginal-antifungal-4',
    name: 'gynoconazol 0.4% vag. cream 30 gm',
    genericName: 'terconazole',
    concentration: '0.4% (30 gm)',
    price: 36,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٧ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٧ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynoconazol 0.4', 'terconazole cream 0.4'],
  },
  {
    id: 'vaginal-antifungal-5',
    name: 'viatrazo 0.8% vaginal cream 30 gm',
    genericName: 'terconazole',
    concentration: '0.8% (30 gm)',
    price: 36,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['viatrazo 0.8', 'فياترازو', 'terconazole'],
  },
  {
    id: 'vaginal-antifungal-6',
    name: 'viatrazo 80 mg 3 vag. supp.',
    genericName: 'terconazole',
    concentration: '80mg (3 suppositories)',
    price: 53,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['viatrazo 80', 'terconazole'],
  },
  {
    id: 'vaginal-antifungal-7',
    name: 'gynozol 200mg 6 vag. ovules',
    genericName: 'miconazole',
    concentration: '200mg (6 ovules)',
    price: 32,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٦ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٦ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynozol 200', 'miconazole 200'],
  },
  {
    id: 'vaginal-antifungal-8',
    name: 'gynomonix 80 mg 3 vag. ovules',
    genericName: 'terconazole',
    concentration: '80mg (3 ovules)',
    price: 41,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynomonix 80', 'جينومونيكس', 'terconazole'],
  },
  {
    id: 'vaginal-antifungal-9',
    name: 'sedalostate 2% vaginal cream 5 gm',
    genericName: 'butoconazole',
    concentration: '2% (5 gm)',
    price: 23,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['sedalostate 5', 'سيدالوسيت', 'butoconazole'],
  },
  {
    id: 'vaginal-antifungal-10',
    name: 'sedalostate 2% vaginal cream 15 gm',
    genericName: 'butoconazole',
    concentration: '2% (15 gm)',
    price: 79,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['sedalostate 15', 'butoconazole'],
  },
  {
    id: 'vaginal-antifungal-11',
    name: 'monicure 400mg 3 vaginal supp',
    genericName: 'miconazole nitrate',
    concentration: '400mg (3 suppositories)',
    price: 24,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['monicure', 'مونيكيور', 'miconazole 400'],
  },
  {
    id: 'vaginal-antifungal-12',
    name: 'andocandoxin 600 mg 1 vaginal caps.',
    genericName: 'fenticonazole nitrate',
    concentration: '600mg (1 vaginal capsule)',
    price: 61,
    usage: 'علاج فطريات مهبلية (جرعة عالية).',
    timing: 'ليلاً – جرعة واحدة',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Capsule',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة في المهبل ليلاً قبل النوم – جرعة وحيدة'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['andocandoxin 600', 'اندو كاندوكسين', 'fenticonazole'],
  },
  {
    id: 'vaginal-antifungal-13',
    name: 'gynomonix 0.8% vag. cream 30 gm',
    genericName: 'terconazole',
    concentration: '0.8% (30 gm)',
    price: 50,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynomonix 0.8', 'جينومونيكس كريم', 'terconazole'],
  },
  {
    id: 'vaginal-antifungal-14',
    name: 'andocandoxin 200 mg 3 vaginal caps.',
    genericName: 'fenticonazole nitrate',
    concentration: '200mg (3 vaginal capsules)',
    price: 58,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Capsule',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['andocandoxin 200', 'fenticonazole 200'],
  },
  {
    id: 'vaginal-antifungal-15',
    name: 'gynomonix 0.4% vag. cream 30 gm',
    genericName: 'terconazole',
    concentration: '0.4% (30 gm)',
    price: 36,
    usage: 'علاج فطريات مهبلية.',
    timing: 'ليلاً – ٧ أيام',
    category: Category.VAGINAL_ANTIFUNGAL,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٧ أيام'),
    warnings: VAGINAL_ANTIFUNGAL_WARNINGS,
    matchKeywords: ['gynomonix 0.4', 'terconazole 0.4'],
  },
];

export const VAGINAL_ANTIFUNGAL_GROUP: Medication[] = enhanceGynMedicationList(VAGINAL_ANTIFUNGAL_GROUP_RAW);
