import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const VAGINAL_INFECTION_WARNINGS = [
  'لا يُستخدم بدون تشخيص واضح خصوصاً مع تكرار الأعراض.',
  'في الحمل: يُستخدم عند الضرورة فقط؛ كلوتريمازول/نيستاتين/ميكونازول موضعي غالباً آمن؛ تجنبي الميترونيدازول في الثلث الأول.',
  'ألم شديد/حمى/إفرازات كريهة/نزيف: أعيدي التقييم.',
];

const VAGINAL_INFECTIONS_GROUP_RAW: Medication[] = [
  {
    id: 'vaginal-infection-1',
    name: 'amrizole 500mg 5 vaginal supp.',
    genericName: 'metronidazole',
    concentration: '500mg (5 vaginal suppositories)',
    price: 10.5,
    usage: 'علاج التهاب مهبلي بكتيري/طفيلي (حسب التشخيص).',
    timing: 'ليلاً – ٥ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٥ أيام'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['amrizole', 'امريزول', 'metronidazole', 'vaginal'],
  },
  {
    id: 'vaginal-infection-2',
    name: 'gynozol 2% vaginal cream 40 gm',
    genericName: 'miconazole',
    concentration: '2% (40 gm)',
    price: 58,
    usage: 'علاج فطريات مهبلية/حكة (المدة ٣–٧ أيام حسب العبوة).',
    timing: 'ليلاً – ٣–٧ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣–٧ أيام حسب العبوة'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['gynozol 2%', 'جينوزول كريم', 'miconazole'],
  },
  {
    id: 'vaginal-infection-3',
    name: 'gynotrazonagen 600mg 3 vaginal ovules + applicator',
    genericName: 'isoconazole nitrate',
    concentration: '600mg (3 ovules)',
    price: 33,
    usage: 'علاج فطريات مهبلية (حسب العبوة/الطبيب).',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['gynotrazonagen', 'isoconazole', 'ovules'],
  },
  {
    id: 'vaginal-infection-4',
    name: 'candicure 1 - 600mg 3 vag. ovules',
    genericName: 'isoconazole nitrate',
    concentration: '600mg (3 ovules)',
    price: 50,
    usage: 'علاج فطريات مهبلية (حسب العبوة/الطبيب).',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['candicure', 'كانديكيور', 'isoconazole'],
  },
  {
    id: 'vaginal-infection-5',
    name: 'gyno-daktarin 2% vaginal cream 40 gm',
    genericName: 'miconazole',
    concentration: '2% (40 gm)',
    price: 59,
    usage: 'علاج فطريات مهبلية/حكة (حسب التشخيص أو العبوة).',
    timing: 'ليلاً – ٣–٧ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣–٧ أيام حسب العبوة'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['gyno-daktarin', 'داكتارين', 'miconazole'],
  },
  {
    id: 'vaginal-infection-6',
    name: 'vagizole 2% vaginal cream 15 gm + 3 applicators',
    genericName: 'butoconazole',
    concentration: '2% (15 gm)',
    price: 123,
    usage: 'علاج فطريات مهبلية (حسب العبوة/الطبيب).',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['vagizole', 'فاجيزول', 'butoconazole'],
  },
  {
    id: 'vaginal-infection-7',
    name: 'treatocandivag 2% vaginal cream 15 gm',
    genericName: 'butoconazole',
    concentration: '2% (15 gm)',
    price: 123,
    usage: 'علاج فطريات مهبلية (حسب العبوة/الطبيب).',
    timing: 'ليلاً – ٣ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Cream',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة كريم في المهبل ليلاً قبل النوم لمدة ٣ أيام'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['treatocandivag', 'butoconazole'],
  },
];

export const VAGINAL_INFECTIONS_GROUP: Medication[] = enhanceGynMedicationList(VAGINAL_INFECTIONS_GROUP_RAW);
