import type { Medication } from '../../types';
import { Category } from '../../types';
import { enhanceGynMedicationList } from './gynEnhancer';

const fixed = (text: string) => (_weight: number, _ageMonths: number) => text;

const VAGINAL_CARE_WARNINGS = [
  'للاستخدام الخارجي فقط ما لم يُحدد التشخيص خلاف ذلك.',
  'تجنب الاستخدام المفرط أو المتكرر للغسول الداخلي لأنه قد يسبب تهيّجاً ويخل بتوازن البكتيريا النافعة.',
  'أوقفي الاستخدام عند الحرقان الشديد/الحساسية.',
  'في الحمل أو تكرار الالتهابات: يُفضّل تقييم سبب الالتهاب واختيار المنتج المناسب.',
];

const VAGINAL_INFECTION_WARNINGS = [
  'لا يُستخدم بدون تشخيص واضح خصوصاً مع تكرار الأعراض.',
  'في الحمل: يُستخدم عند الضرورة فقط؛ اختر منتجاً له بيانات أمان (مثل كلوتريمازول موضعي) وتجنب الميترونيدازول في الثلث الأول إن أمكن.',
  'ألم شديد/حمى/إفرازات كريهة/نزيف: أعيدي التقييم.',
];

const washStandard = fixed('يُستخدم خارجياً كغسول مرتين أسبوعياً');

const VAGINAL_WASH_DOUCHE_CLEANSER_GROUP_RAW: Medication[] = [
  {
    id: 'vaginal-care-1',
    name: 'alka-misr alkaline wash powder 10 sachets',
    genericName: 'borax & sodium chloride anhydrous & sodium bicarbonate',
    concentration: '10 sachets',
    price: 28,
    usage: 'بودرة قلوية للغسول/العناية بالمنطقة (وقد تُستخدم أيضاً كغسول أنف حسب المنتج).',
    timing: 'مرتين أسبوعياً – عند الحاجة',
    category: Category.VAGINAL_CARE,
    form: 'Sachets',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كيس يذاب في ماء دافئ ويُستخدم خارجياً كغسول مرتين أسبوعياً'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['alka-misr', 'الكمصر', 'alkaline wash', 'borax', 'nasal wash', 'vaginal care'],
  },
  {
    id: 'vaginal-care-2',
    name: 'tantum rosa 0.5g powder for vaginal solution',
    genericName: 'benzydamine hydrochloride',
    concentration: '0.5g',
    price: 19,
    usage: 'مضاد التهاب موضعي لتخفيف الحكة/الالتهاب (حسب الاستعمال الموضح).',
    timing: 'مرة يومياً – ٣–٧ أيام',
    category: Category.VAGINAL_CARE,
    form: 'Powder',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كيس يذاب في ماء دافئ ويُستخدم كغسول خارجي مرة يومياً لمدة ٣–٧ أيام'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['tantum rosa', 'تانتم روزا', 'benzydamine'],
  },
  {
    id: 'vaginal-mixed-amrizole-n',
    name: 'amrizole-n 5 vaginal suppositories',
    genericName: 'metronidazole & nystatin',
    concentration: '5 vaginal suppositories',
    price: 30,
    usage: 'عدوى مهبلية مختلطة (بكتيري/فطري)؛ لبوس واحد ليلاً ٥ أيام (المدة حسب الاستجابة).',
    timing: 'ليلاً – ٥ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٥ أيام'),
    warnings: VAGINAL_INFECTION_WARNINGS,
    matchKeywords: ['amrizole-n', 'امريزول', 'metronidazole', 'nystatin'],
  },
  {
    id: 'vaginal-care-4',
    name: 'klenva vaginal douche 250 ml',
    genericName: 'alum & chamomile extract & thymol & menthol',
    concentration: '250 ml',
    price: 85,
    usage: 'غسول/دوش للعناية بالمنطقة وتقليل الروائح (حسب العبوة).',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['klenva', 'كلينفا', 'douche', 'wash'],
  },
  {
    id: 'vaginal-care-5',
    name: 'li.li vaginal wash 250 ml',
    genericName: 'chlorhexidine & cetrimide & triclosan & thyme & sage',
    concentration: '250 ml',
    price: 70,
    usage: 'غسول للعناية بالمنطقة (مطهر خفيف) حسب العبوة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['li.li', 'lili', 'chlorhexidine', 'triclosan'],
  },
  {
    id: 'vaginal-care-6',
    name: 'revarest plus vaginal douche 250 ml',
    genericName: 'rose water & glycerin & citric acid & menthol & tea tree oil',
    concentration: '250 ml',
    price: 85,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['revarest', 'ريفاريست', 'tea tree'],
  },
  {
    id: 'vaginal-care-7',
    name: 'alka-misr alkaline wash powder 12 sachets',
    genericName: 'borax & sodium chloride & sodium bicarbonate',
    concentration: '12 sachets',
    price: 40,
    usage: 'بودرة قلوية للغسول/العناية بالمنطقة.',
    timing: 'مرتين أسبوعياً – عند الحاجة',
    category: Category.VAGINAL_CARE,
    form: 'Sachets',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كيس يذاب في ماء دافئ ويُستخدم خارجياً كغسول مرتين أسبوعياً'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['alka-misr', '12 sachets'],
  },
  {
    id: 'vaginal-care-8',
    name: 'bidalkin vaginal douche powder 12 sachets',
    genericName: 'borax & sodium bicarbonate & potash alum',
    concentration: '12 sachets',
    price: 58,
    usage: 'بودرة للغسول/العناية بالمنطقة.',
    timing: 'مرتين أسبوعياً – عند الحاجة',
    category: Category.VAGINAL_CARE,
    form: 'Sachets',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كيس يذاب في ماء دافئ ويُستخدم خارجياً كغسول مرتين أسبوعياً'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['bidalkin', 'بيدالكين', 'borax'],
  },
  {
    id: 'vaginal-care-9',
    name: 'malva vaginal douche 120 ml',
    genericName: 'malva extract & tegobain & chlorhexidine gluconate',
    concentration: '120 ml',
    price: 59,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['malva', 'ملفا', 'chlorhexidine'],
  },
  {
    id: 'vaginal-care-10',
    name: 'vagyl powder 10 sachet',
    genericName: 'borax & sodium chloride anhydrous & sodium bicarbonate',
    concentration: '10 sachets',
    price: 35,
    usage: 'بودرة للغسول/العناية بالمنطقة.',
    timing: 'مرتين أسبوعياً – عند الحاجة',
    category: Category.VAGINAL_CARE,
    form: 'Sachets',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('كيس يذاب في ماء دافئ ويُستخدم خارجياً كغسول مرتين أسبوعياً'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['vagyl', 'فاجيل', 'borax'],
  },
  {
    id: 'vaginal-care-11',
    name: 'clinso vaginal douche 200 ml',
    genericName: 'triclosan & cetrimide & chamomile extract & thymol',
    concentration: '200 ml',
    price: 72,
    usage: 'غسول/دوش للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['clinso', 'كلينسو'],
  },
  {
    id: 'vaginal-care-12',
    name: 'dormant vaginal wash 120 ml',
    genericName: 'thymol & triclosan & menthol',
    concentration: '120 ml',
    price: 28,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['dormant', 'دورمانت', 'menthol'],
  },
  {
    id: 'vaginal-care-13',
    name: 'dormant vaginal wash 240 ml',
    genericName: 'thymol & triclosan & menthol',
    concentration: '240 ml',
    price: 55,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['dormant', '240 ml'],
  },
  {
    id: 'vaginal-care-14',
    name: 'flugenil 600 - 10 vaginal ovules',
    genericName: 'boric acid & tea tree oil & avena sativa (oat) extract',
    concentration: '10 ovules',
    price: 537,
    usage: 'مساعد على استعادة التوازن وتقليل التهيّج/الروائح (حسب العبوة).',
    timing: 'ليلاً – ١٠ أيام',
    category: Category.VAGINAL_CARE,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ١٠ أيام'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['flugenil 600', 'فلوجينيل', 'boric acid', 'tea tree'],
  },
  {
    id: 'vaginal-care-15',
    name: 'flugenil vaginal gel 5 applicators 30 ml',
    genericName: 'hyaluronic acid & soy extract & mallow extract',
    concentration: '30 ml (5 applicators)',
    price: 569,
    usage: 'جل مهبلي مرطب/ملطف (حسب العبوة).',
    timing: 'ليلاً – ٥ أيام',
    category: Category.VAGINAL_CARE,
    form: 'Gel',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('مُطبق واحد في المهبل ليلاً قبل النوم لمدة ٥ أيام'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['flugenil gel', 'فلوجينيل جل', 'hyaluronic'],
  },
  {
    id: 'vaginal-care-16',
    name: 'gold plus vaginal douche 250 ml',
    genericName: 'menthol & aloe vera & chamomile extract',
    concentration: '250 ml',
    price: 85,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['gold plus', 'جولد بلس'],
  },
  {
    id: 'vaginal-care-17',
    name: 'hyalsolo vaginal gel 30 gm',
    genericName: 'soyabean phospholipids & sodium hyaluronate',
    concentration: '30 gm',
    price: 895,
    usage: 'جل مرطب/ملطف للجفاف (حسب العبوة).',
    timing: 'ليلاً – ٧–١٤ يوم',
    category: Category.VAGINAL_CARE,
    form: 'Gel',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('جرعة جل في المهبل ليلاً قبل النوم لمدة ٧–١٤ يوم أو حسب الحاجة'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['hyalsolo', 'هيالسولو', 'hyaluronate'],
  },
  {
    id: 'vaginal-care-18',
    name: 'right vaginal douche 200ml',
    genericName: 'tea tree (melaleuca) & triclosan & cetrimide & camphor',
    concentration: '200 ml',
    price: 80,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['right douche', 'رايت', 'tea tree'],
  },
  {
    id: 'vaginal-care-19',
    name: 'rovan intimate feminine wash 250 ml',
    genericName: 'aloe barbadensis & tea tree oil & peppermint oil & cucumber extract',
    concentration: '250 ml',
    price: 65,
    usage: 'غسول نسائي للعناية اليومية.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['rovan', 'روفان', 'intimate wash'],
  },
  {
    id: 'vaginal-care-20',
    name: 'logus gyn 10 vaginal ovules',
    genericName: 'probiotic blend & lactic acid blend (as listed on pack)',
    concentration: '10 ovules',
    price: 395,
    usage: 'مساعد بروبيوتك/توازن مهبلي (حسب العبوة).',
    timing: 'ليلاً – ١٠ أيام',
    category: Category.VAGINAL_CARE,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ١٠ أيام'),
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['logus gyn', 'لوجس', 'probiotic', 'ovules'],
  },
  {
    id: 'vaginal-care-21',
    name: 'rovadene vaginal wash 200 ml',
    genericName: 'chlorhexidine & chamomile & panthenol',
    concentration: '200 ml',
    price: 75,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['rovadene', 'روفادين', 'panthenol'],
  },
  {
    id: 'vaginal-care-22',
    name: 'femi 9 intimate liquid cleanser 250 ml',
    genericName: 'l-arginine & chlorhexidine gluconate & vitamin e (as listed on pack)',
    concentration: '250 ml',
    price: 85,
    usage: 'غسول نسائي للعناية اليومية.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['femi 9', 'فيمي 9', 'chlorhexidine'],
  },
  {
    id: 'vaginal-infection-betadine-ovule',
    name: 'betadine 200mg 14 vaginal ovule',
    genericName: 'povidone iodine',
    concentration: '200mg (14 ovules)',
    price: 16.5,
    usage: 'مطهر مساعد لالتهابات مهبلية؛ لبوس واحد ليلاً ٧ أيام (المدة حسب الاستجابة).',
    timing: 'ليلاً – ٧ أيام',
    category: Category.VAGINAL_INFECTIONS,
    form: 'Suppositories',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('لبوس واحد في المهبل ليلاً قبل النوم لمدة ٧ أيام'),
    warnings: [...VAGINAL_INFECTION_WARNINGS, 'يُستخدم بحذر في اضطرابات الغدة الدرقية أو حساسية اليود.'],
    matchKeywords: ['betadine ovule', 'بيتادين لبوس', 'povidone iodine'],
  },
  {
    id: 'vaginal-care-24',
    name: 'tricogyn vaginal douche 200 ml',
    genericName: 'cetrimide & thyme extract & menthol & chamomile extract',
    concentration: '200 ml',
    price: 70,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['tricogyn', 'تريكوجين'],
  },
  {
    id: 'vaginal-care-25',
    name: 'vamix feminine wash 220 ml',
    genericName: 'thyme & menthol & chamomile & triclosan & ph adjuster',
    concentration: '220 ml',
    price: 95,
    usage: 'غسول نسائي للعناية اليومية.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['vamix', 'فاميكس'],
  },
  {
    id: 'vaginal-care-26',
    name: 'verdol feminine wash 250 ml',
    genericName: 'tea tree & borax',
    concentration: '250 ml',
    price: 75,
    usage: 'غسول نسائي للعناية اليومية.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['verdol', 'فيردول', 'tea tree'],
  },
  {
    id: 'vaginal-care-27',
    name: 'vimora vaginal douche 120ml',
    genericName: 'chamomile extract & thyme extract & aloe vera extract',
    concentration: '120 ml',
    price: 60,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['vimora', 'فيمورا', 'aloe vera'],
  },
  {
    id: 'vaginal-care-28',
    name: 'vimora vaginal gel cleanser 120 ml',
    genericName: 'hyaluronic acid & lactic acid & thyme & vitamin e & tea tree oil',
    concentration: '120 ml',
    price: 60,
    usage: 'جل غسول/مرطب للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Gel',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['vimora gel', 'فيمورا جل', 'hyaluronic', 'lactic acid'],
  },
  {
    id: 'vaginal-care-29',
    name: 'zeta rose vaginal douche 120 ml',
    genericName: 'chlorhexidine & thymol & tea tree oil & triclosan',
    concentration: '120 ml',
    price: 22,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['zeta rose', 'زيتا روز', 'chlorhexidine'],
  },
  {
    id: 'vaginal-care-30',
    name: 'intidare vaginal douche 240 ml',
    genericName: 'tea tree oil & glycerol & citric acid & cocamidopropyl betaine',
    concentration: '240 ml',
    price: 75,
    usage: 'غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Cleanser',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['intidare', 'انتي دير', 'cocamidopropyl betaine'],
  },
  {
    id: 'vaginal-care-31',
    name: 'mornin glow wash gel 200 gm',
    genericName: 'propolis extract & thyme extract & tea tree oil & chamomile extract',
    concentration: '200 gm',
    price: 49,
    usage: 'جل غسول للعناية بالمنطقة.',
    timing: 'مرتين أسبوعياً',
    category: Category.VAGINAL_CARE,
    form: 'Gel',
    minAgeMonths: 156,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: washStandard,
    warnings: VAGINAL_CARE_WARNINGS,
    matchKeywords: ['mornin glow', 'مورنين جلو', 'propolis', 'gel wash'],
  },
];

export const VAGINAL_WASH_DOUCHE_CLEANSER_GROUP: Medication[] = enhanceGynMedicationList(VAGINAL_WASH_DOUCHE_CLEANSER_GROUP_RAW);
