
import { Medication, Category } from '../../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const SSRI_SNRI_CORE = [
	'تحذير: أفكار انتحارية خصوصاً في بداية العلاج عند صغار السن (<٢٥ سنة)؛ راقب المزاج عن قرب.',
	'لا يوقف فجأة (أعراض انسحاب). يجب السحب التدريجي.',
	'ممنوع الجمع مع مثبطات MAO (خطر متلازمة السيروتونين المميتة).',
];
const SSRI_WARNINGS = [...SSRI_SNRI_CORE, 'قد يسبب غثيان/صداع في البداية.', 'قد يسبب ضعف/تأخر جنسي.'];
const SNRI_WARNINGS = [...SSRI_SNRI_CORE, 'قد يسبب غثيان/دوخة في البداية.', 'قد يرفع ضغط الدم/النبض (خاصة الجرعات الأعلى).'];
const TCA_WARNINGS = ['تحذير: أفكار انتحارية خصوصاً في بداية العلاج عند صغار السن (<٢٥ سنة).', 'لا يوقف فجأة.', 'خطر سمّية قلبية بجرعات زائدة؛ ممنوع الجمع مع MAOIs.', 'يسبب نعاس وجفاف فم/إمساك.', 'يزيد خطر اضطراب نظم/هبوط ضغط خصوصاً مع الجرعات العالية.'];

export const ANTIDEPRESSANTS_2: Medication[] = [
	// 71) supranil 25mg 20 caps.
	{
		id: 'supranil-25-20-caps-ad2',
		name: 'supranil 25mg 20 caps.',
		genericName: 'clomipramine',
		concentration: '25mg',
		price: 21,
		matchKeywords: [
			'supranil 25 20', 'supranil', 'clomipramine', 'anafranil',
			'ocd', 'obsessive compulsive', 'panic', 'depression',
			'سوبرانيل', 'كلوميبرامين', 'وسواس', 'هلع', 'اكتئاب',
			'#antidepressants', '#tca'
		],
		usage: 'كلوميبرامين (TCA) فعال خصوصاً في الوسواس القهري وبعض اضطرابات القلق.',
		timing: 'مساءً ثم تُقسم – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٥ مجم مساءً. يمكن زيادة ٢٥ مجم كل ٣–٧ أيام حسب التحمل. جرعة شائعة: ٧٥–١٥٠ مجم/يوم مقسمة. الحد الأقصى: ٢٥٠ مجم/يوم.'),
		warnings: [...TCA_WARNINGS, 'يُحذر مع الجلوكوما/احتباس البول.', 'قد يتداخل مع أدوية كثيرة (خاصة مثبطات/محفزات إنزيمات).'],
	},

	// 72) trittico 100mg 20 tab.
	{
		id: 'trittico-100-20-tabs-ad2',
		name: 'trittico 100mg 20 tab.',
		genericName: 'trazodone',
		concentration: '100mg',
		price: 60,
		matchKeywords: [
			'trittico 100 20', 'trazodone 100', 'trazodone',
			'depression', 'insomnia', 'sleep',
			'تريتيكو', 'ترازودون', 'اكتئاب', 'أرق',
			'#antidepressants'
		],
		usage: 'ترازودون للاكتئاب (ويساعد على النوم بجرعات صغيرة).',
		timing: 'مرة يومياً مساءً قبل النوم – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('للأرق: ٥٠–١٠٠ مجم قبل النوم. للاكتئاب: يبدأ ٥٠ مجم مرتين يومياً ثم الزيادة تدريجياً حتى ١٥٠–٣٠٠ مجم/يوم مقسمة. الحد الأقصى: ٤٠٠ مجم/يوم (للخارج) أو ٦٠٠ مجم/يوم (داخل المستشفى).'),
		warnings: ['قد يسبب نعاس شديد/دوخة.', 'قد يسبب هبوط ضغط عند الوقوف.', 'نادر: انتصاب مؤلم مطول (Priapism) يستدعي طوارئ.'],
	},

	// 73) trittico 50 mg 20 tabs.
	{
		id: 'trittico-50-20-tabs-ad2',
		name: 'trittico 50 mg 20 tabs.',
		genericName: 'trazodone',
		concentration: '50mg',
		price: 38,
		matchKeywords: ['trittico 50 20', 'trazodone 50', 'trazodone', 'insomnia', 'sleep', 'تريتيكو ٥٠', 'أرق', '#antidepressants'],
		usage: 'ترازودون يساعد على النوم بجرعات صغيرة، وتُستخدم جرعات أعلى عند علاج الاكتئاب.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('للأرق: قرص ٥٠ مجم قبل النوم (يمكن ١–٢ قرص). للاكتئاب: ٥٠ مجم مرتين يومياً ثم زيادة تدريجية. الحد الأقصى: ٤٠٠ مجم/يوم.'),
		warnings: ['قد يسبب نعاس/دوخة.', 'قد يسبب هبوط ضغط عند الوقوف.', 'نادر: Priapism.'],
	},

	// 74) adwitine 60 mg 30 caps.
	{
		id: 'adwitine-60-30-caps-ad2',
		name: 'adwitine 60 mg 30 caps.',
		genericName: 'duloxetine',
		concentration: '60mg',
		price: 300,
		matchKeywords: [
			'adwitine 60 30', 'duloxetine 60', 'duloxetine',
			'depression', 'anxiety', 'neuropathic pain', 'fibromyalgia',
			'ادويتين', 'دولوكسيتين', 'اكتئاب', 'قلق', 'ألم أعصاب', 'فيبروميالجيا',
			'#antidepressants', '#snri'
		],
		usage: 'دولوكسيتين (SNRI) للاكتئاب والقلق وآلام الأعصاب/الفيبروميالجيا.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Delayed-Release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٣٠ مجم يومياً لمدة أسبوع ثم ٦٠ مجم يومياً. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SNRI_WARNINGS, 'يُحذر في أمراض الكبد الشديدة/إدمان كحول.', 'قد يزيد التعرق أو جفاف الفم.'],
	},

	// 75) bedremine 100mg 30 exten. rel. tab.
	{
		id: 'bedremine-100-30-pr-tabs-ad2',
		name: 'bedremine 100mg 30 exten. rel. tab.',
		genericName: 'desvenlafaxine',
		concentration: '100mg',
		price: 198,
		matchKeywords: ['bedremine 100 30', 'desvenlafaxine 100', 'pristiq', 'snri', 'depression', 'بدريمين', 'ديسفينلافاكسين', 'اكتئاب', '#antidepressants', '#snri'],
		usage: 'ديسفينلافاكسين (SNRI) للاكتئاب (ممتد المفعول).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٥٠ مجم مرة يومياً. يمكن الزيادة إلى ١٠٠ مجم مرة يومياً حسب الاستجابة. لا تُكسر/تُسحق.'),
		warnings: [...SNRI_WARNINGS, 'قد يزيد الغثيان/الأرق.'],
	},

	// 76) brintellix 10 mg 14 f.c. tab.
	{
		id: 'brintellix-10-14-tabs-ad2',
		name: 'brintellix 10 mg 14 f.c. tab.',
		genericName: 'vortioxetine',
		concentration: '10mg',
		price: 364,
		matchKeywords: ['brintellix 10 14', 'vortioxetine 10', 'vortioxetine', 'depression', 'brintellix', 'برينتيلكس', 'فورتيوكسيتين', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب (قد يفيد التركيز/الوظائف المعرفية عند بعض المرضى).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٠ مجم مرة يومياً. يمكن خفضها إلى ٥ مجم عند عدم التحمل أو زيادتها إلى ٢٠ مجم/يوم. الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: ['قد يسبب غثيان (شائع).', 'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.', 'لا يوقف فجأة.'],
	},

	// 77) brintellix 20mg 14 f.c. tab.
	{
		id: 'brintellix-20-14-tabs-ad2',
		name: 'brintellix 20mg 14 f.c. tab.',
		genericName: 'vortioxetine',
		concentration: '20mg',
		price: 573,
		matchKeywords: ['brintellix 20 14', 'vortioxetine 20', 'brintellix', 'depression', 'برينتيلكس ٢٠', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب (جرعة ٢٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (٢٠ مجم) مرة يومياً. الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: ['قد يسبب غثيان.', 'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.'],
	},

	// 78) citalo 40mg 30 f.c.tab.
	{
		id: 'citalo-40-30-tabs-ad2',
		name: 'citalo 40mg 30 f.c.tab.',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 180,
		matchKeywords: ['citalo 40 30', 'citalopram 40', 'citalopram', 'depression', 'anxiety', 'panic', 'سيتالو', 'سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام (SSRI) للاكتئاب واضطرابات القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٠ مجم يومياً. يمكن الزيادة إلى ٤٠ مجم/يوم حسب الاستجابة. كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم بسبب خطر QT.'),
		warnings: [...SSRI_WARNINGS, 'قد يطيل QT خصوصاً مع الجرعات العالية أو أدوية أخرى.'],
	},

	// 79) cipramaline 10 mg 20 f.c. tabs.
	{
		id: 'cipramaline-10-20-tabs-ad2',
		name: 'cipramaline 10 mg 20 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 144,
		matchKeywords: ['cipramaline 10 20', 'escitalopram 10', 'cipralex', 'depression', 'anxiety', 'panic', 'سيبرامالين', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٥–١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_WARNINGS, 'قد يسبب قلق/أرق في الأسبوع الأول ثم يتحسن.'],
	},

	// 80) escitapram 20 mg 20 f.c.tabs.
	{
		id: 'escitapram-20-20-tabs-ad2',
		name: 'escitapram 20 mg 20 f.c.tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 116,
		matchKeywords: ['escitapram 20 20', 'escitalopram 20', 'cipralex', 'depression', 'anxiety', 'اسكيتابرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب واضطرابات القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم (الحد الأقصى).'),
		warnings: [...SSRI_WARNINGS],
	},

	// 81) excelsa 20mg 14 f.c.tab.
	{
		id: 'excelsa-20-14-tabs-ad2',
		name: 'excelsa 20mg 14 f.c.tab.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 114,
		matchKeywords: ['excelsa 20 14', 'escitalopram 20', 'excelsa', 'اكسيلسا', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم (الحد الأقصى).'),
		warnings: [...SSRI_WARNINGS],
	},

	// 82) excelsa 20mg 7 f.c.tab.
	{
		id: 'excelsa-20-7-tabs-ad2',
		name: 'excelsa 20mg 7 f.c.tab.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 57,
		matchKeywords: ['excelsa 20 7', 'escitalopram 20', 'اكسيلسا ٧', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 83) karbalta 60 mg 30 caps.
	{
		id: 'karbalta-60-30-caps-ad2',
		name: 'karbalta 60 mg 30 caps.',
		genericName: 'duloxetine hydrochloride',
		concentration: '60mg',
		price: 249,
		matchKeywords: ['karbalta 60 30', 'duloxetine 60', 'neuropathic pain', 'fibromyalgia', 'depression', 'كاربالتا', 'دولوكسيتين', 'ألم أعصاب', 'اكتئاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Delayed-Release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٦٠ مجم مرة يومياً. يمكن البدء بـ٣٠ مجم لمدة أسبوع ثم ٦٠ مجم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 84) lecital 40mg 30 f.c.tablets
	{
		id: 'lecital-40-30-tabs-ad2',
		name: 'lecital 40mg 30 f.c.tablets',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 255,
		matchKeywords: ['lecital 40 30', 'citalopram 40', 'lecital', 'ليستال', 'سيتالوبرام', 'depression', 'anxiety', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام (SSRI) للاكتئاب واضطرابات القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٠ مجم يومياً ثم الزيادة إلى ٤٠ مجم/يوم حسب الاستجابة. كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS, 'قد يطيل QT.'],
	},

	// 85) paroxedep cr 37.5 mg 10 enteric f.c.tabs.
	{
		id: 'paroxedep-cr-37-5-10-tabs-ad2',
		name: 'paroxedep cr 37.5 mg 10 enteric f.c.tabs.',
		genericName: 'paroxetine',
		concentration: '37.5mg',
		price: 39,
		matchKeywords: ['paroxedep cr 37.5 10', 'paroxetine cr 37.5', 'seroxat cr', 'panic', 'anxiety', 'depression', 'باروكسيديب', 'باروكستين', 'هلع', 'قلق', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد المفعول للاكتئاب واضطرابات القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: بداية شائعة ١٢٫٥–٢٥ مجم مرة يومياً ثم الزيادة تدريجياً. جرعة شائعة: ٢٥–٣٧٫٥ مجم/يوم. الحد الأقصى: ٦٢٫٥ مجم/يوم. لا يُكسر/يُسحق.'),
		warnings: [...SSRI_WARNINGS, 'قد يسبب أعراض انسحاب أوضح عند الإيقاف المفاجئ.'],
	},

	// 86) paroxetine cr 37.5 mg 30 f.c.tab
	{
		id: 'paroxetine-cr-37-5-30-tabs-ad2',
		name: 'paroxetine cr 37.5 mg 30 f.c.tab',
		genericName: 'paroxetine',
		concentration: '37.5mg',
		price: 132,
		matchKeywords: ['paroxetine cr 37.5 30', 'paroxetine controlled release', 'seroxat cr', 'panic', 'anxiety', 'depression', 'باروكستين ممتد', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد المفعول للاكتئاب والقلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: جرعة شائعة ٢٥–٣٧٫٥ مجم مرة يومياً. الحد الأقصى: ٦٢٫٥ مجم/يوم. لا يُكسر/يُسحق.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 87) prismaven 100 mg 30 ext. rel. tab.
	{
		id: 'prismaven-100-30-pr-tabs-ad2',
		name: 'prismaven 100 mg 30 ext. rel. tab.',
		genericName: 'desvenlafaxine',
		concentration: '100mg',
		price: 204,
		matchKeywords: ['prismaven 100 30', 'desvenlafaxine 100', 'pristiq', 'depression', 'بريزمـافين', 'ديسفينلافاكسين', '#antidepressants', '#snri'],
		usage: 'ديسفينلافاكسين ممتد المفعول للاكتئاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٥٠ مجم مرة يومياً. يمكن الزيادة إلى ١٠٠ مجم مرة يومياً حسب الاستجابة. لا يُكسر/يُسحق.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 88) prismaven 50mg 30 ext. rel. tab.
	{
		id: 'prismaven-50-30-pr-tabs-ad2',
		name: 'prismaven 50mg 30 ext. rel. tab.',
		genericName: 'desvenlafaxine',
		concentration: '50mg',
		price: 159,
		matchKeywords: ['prismaven 50 30', 'desvenlafaxine 50', 'pristiq 50', 'depression', 'بريزمـافين ٥٠', '#antidepressants', '#snri'],
		usage: 'ديسفينلافاكسين ممتد المفعول للاكتئاب (جرعة ٥٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (٥٠ مجم) مرة يومياً. لا يُكسر/يُسحق.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 89) seroxat 20mg 30 f.c.tab.
	{
		id: 'seroxat-20-30-tabs-ad2',
		name: 'seroxat 20mg 30 f.c.tab.',
		genericName: 'paroxetine',
		concentration: '20mg',
		price: 74.25,
		matchKeywords: ['seroxat 20 30', 'paroxetine 20', 'panic', 'ocd', 'anxiety', 'depression', 'سيروكسات', 'باروكستين', 'هلع', 'وسواس', 'قلق', '#antidepressants', '#ssri'],
		usage: 'باروكستين لعلاج الاكتئاب واضطرابات القلق/الهلع/الوسواس.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٠ مجم يومياً. يمكن الزيادة تدريجياً كل أسبوع حتى ٤٠–٥٠ مجم/يوم حسب التشخيص. الحد الأقصى: ٥٠ مجم/يوم (للأقراص العادية).'),
		warnings: [...SSRI_WARNINGS, 'قد يسبب أعراض انسحاب أوضح عند الإيقاف المفاجئ.'],
	},

	// 90) venllamash 75 mg 30 ext. rel. caps.
	{
		id: 'venllamash-75-30-mr-caps-ad2',
		name: 'venllamash 75 mg 30 ext. rel. caps.',
		genericName: 'venlafaxine',
		concentration: '75mg',
		price: 159,
		matchKeywords: ['venllamash 75 30', 'venlafaxine xr 75', 'snri', 'depression', 'anxiety', 'panic', 'فينلافاكسين ممتد', 'فينلاماش', '#antidepressants', '#snri'],
		usage: 'فينلافاكسين ممتد المفعول للاكتئاب واضطرابات القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Modified-release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('XR: بداية شائعة ٣٧٫٥–٧٥ مجم مرة يومياً ثم الزيادة تدريجياً. جرعة شائعة: ٧٥–٢٢٥ مجم/يوم. الحد الأقصى المعتاد: ٢٢٥ مجم/يوم.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 91) verdapiotal 10mg 30 f.c.tablets
	{
		id: 'verdapiotal-10-30-tabs-ad2',
		name: 'verdapiotal 10mg 30 f.c.tablets',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 139.5,
		matchKeywords: ['verdapiotal 10 30', 'escitalopram 10', 'depression', 'anxiety', 'verdapiotal', 'فيردابيوتال', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٥–١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 92) vilaphoria 20 mg 30 f.c.tabs.
	{
		id: 'vilaphoria-20-30-tabs-ad2',
		name: 'vilaphoria 20 mg 30 f.c.tabs.',
		genericName: 'vilazodone hydrochloride',
		concentration: '20mg',
		price: 294,
		matchKeywords: ['vilaphoria 20 30', 'vilazodone 20', 'viibryd', 'depression', 'vilazodone', 'فيلوفوريا', 'فيلازودون', 'اكتئاب', '#antidepressants'],
		usage: 'فيلازودون للاكتئاب (SSRI + partial agonist).',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('تدرج شائع: ١٠ مجم يومياً مع الطعام لمدة ٧ أيام، ثم ٢٠ مجم يومياً لمدة ٧ أيام، ثم ٤٠ مجم/يوم. (تركيز ٢٠ مجم: قرص يومياً بالمرحلة الثانية).'),
		warnings: ['قد يسبب إسهال/غثيان.', 'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.', 'لا يوقف فجأة.'],
	},

	// 93) vilaphoria 40 mg 30 f.c.tabs.
	{
		id: 'vilaphoria-40-30-tabs-ad2',
		name: 'vilaphoria 40 mg 30 f.c.tabs.',
		genericName: 'vilazodone hydrochloride',
		concentration: '40mg',
		price: 477,
		matchKeywords: ['vilaphoria 40 30', 'vilazodone 40', 'depression', 'فيلوفوريا ٤٠', 'اكتئاب', '#antidepressants'],
		usage: 'فيلازودون للاكتئاب (جرعة مداومة شائعة ٤٠ مجم).',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بعد التدرج: قرص واحد (٤٠ مجم) مرة يومياً مع الأكل.'),
		warnings: ['قد يسبب إسهال/غثيان.', 'احذر متلازمة السيروتونين.'],
	},

	// 94) effegad 75 mg 14 e.r. caps.
	{
		id: 'effegad-75-14-er-caps-ad2',
		name: 'effegad 75 mg 14 e.r. caps.',
		genericName: 'venlafaxine',
		concentration: '75mg',
		price: 76,
		matchKeywords: ['effegad 75 14', 'venlafaxine xr 75', 'snri', 'depression', 'anxiety', 'ايفيجاد', 'فينلافاكسين ممتد', '#antidepressants', '#snri'],
		usage: 'فينلافاكسين ممتد المفعول للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Modified-release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('XR: ٧٥ مجم مرة يومياً (بداية شائعة) ثم الزيادة تدريجياً حتى ٢٢٥ مجم/يوم حسب الاستجابة.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 95) mirpresion 30 mg 30 tabs
	{
		id: 'mirpresion-30-30-tabs-ad2',
		name: 'mirpresion 30 mg 30 tabs',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 151.5,
		matchKeywords: ['mirpresion 30 30', 'mirtazapine 30', 'remeron', 'insomnia', 'appetite', 'ميربريشن', 'ميرتازابين', 'أرق', 'فاتح شهية', '#antidepressants'],
		usage: 'ميرتازابين للاكتئاب المصحوب بأرق/فقدان شهية.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Scored Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٥ مجم قبل النوم ثم ٣٠ مجم بعد ١–٢ أسبوع. نطاق الجرعة: ١٥–٤٥ مجم/يوم.'),
		warnings: ['قد يسبب نعاس وزيادة وزن.', 'قد يسبب زيادة الشهية.', 'نادر: نقص كريات بيضاء—أوقف وأعد التقييم عند التهاب حلق/سخونية غير مفسرة.'],
	},

	// 96) supranil 25 mg 30 caps.
	{
		id: 'supranil-25-30-caps-ad2',
		name: 'supranil 25 mg 30 caps.',
		genericName: 'clomipramine',
		concentration: '25mg',
		price: 66,
		matchKeywords: ['supranil 25 30', 'clomipramine', 'ocd', 'وسواس', 'سوبرانيل', '#antidepressants', '#tca'],
		usage: 'كلوميبرامين (TCA) للوسواس القهري/الاكتئاب حسب الحالة.',
		timing: 'مساءً ثم تُقسم – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('بداية ٢٥ مجم مساءً ثم زيادة تدريجية. جرعة شائعة ٧٥–١٥٠ مجم/يوم. الحد الأقصى ٢٥٠ مجم/يوم.'),
		warnings: [...TCA_WARNINGS],
	},

	// 97) vortoxicalm 15 mg 20 f.c.tabs.
	{
		id: 'vortoxicalm-15-20-tabs-ad2',
		name: 'vortoxicalm 15 mg 20 f.c.tabs.',
		genericName: 'vortioxetine',
		concentration: '15mg',
		price: 452,
		matchKeywords: ['vortoxicalm 15 20', 'vortioxetine 15', 'depression', 'فورتوكسيكالم ١٥', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب (جرعة ١٥ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ١٠ مجم يومياً، ويمكن تعديلها إلى ٥–٢٠ مجم/يوم. تركيز ١٥ مجم: قرص واحد يومياً كجرعة وسطية.'),
		warnings: ['قد يسبب غثيان.', 'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.'],
	},

	// 98) cipramax 40mg 10 f.c. tab.
	{
		id: 'cipramax-40-10-tabs-ad2',
		name: 'cipramax 40mg 10 f.c. tab.',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 50,
		matchKeywords: ['cipramax 40 10', 'citalopram 40', 'cipramax', 'سيبراماكس', 'سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام للاكتئاب والقلق (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٢٠–٤٠ مجم/يوم. كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS, 'قد يطيل QT.'],
	},

	// 99) cipramax 40mg 30 f.c. tab.
	{
		id: 'cipramax-40-30-tabs-ad2',
		name: 'cipramax 40mg 30 f.c. tab.',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 210,
		matchKeywords: ['cipramax 40 30', 'citalopram 40', 'سيبراماكس ٤٠', 'سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية ٢٠ مجم/يوم ثم الزيادة إلى ٤٠ مجم/يوم حسب الاستجابة. كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS, 'قد يطيل QT.'],
	},

	// 100) moodamash 20 mg 14 f.c. tabs.
	{
		id: 'moodamash-20-14-tabs-ad2',
		name: 'moodamash 20 mg 14 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 80,
		matchKeywords: ['moodamash 20 14', 'escitalopram 20', 'مـوداماش', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 101) moodamash 10 mg 14 f.c. tabs.
	{
		id: 'moodamash-10-14-tabs-ad2',
		name: 'moodamash 10 mg 14 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 63,
		matchKeywords: ['moodamash 10 14', 'escitalopram 10', 'موداماش ١٠', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق (جرعة بدء شائعة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (١٠ مجم) مرة يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم حسب الحاجة.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 102) depratiox 10 mg 20 f.c. tabs.
	{
		id: 'depratiox-10-20-tabs-ad2',
		name: 'depratiox 10 mg 20 f.c. tabs.',
		genericName: 'vortioxetine',
		concentration: '10mg',
		price: 206,
		matchKeywords: ['depratiox 10 20', 'vortioxetine 10', 'depratiox', 'ديبراتيوكس', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٠ مجم مرة يومياً. يمكن تعديلها إلى ٥–٢٠ مجم/يوم حسب الاستجابة.'),
		warnings: ['قد يسبب غثيان.', 'احذر متلازمة السيروتونين عند الجمع مع أدوية سيروتونين.'],
	},

	// 103) depratiox 20 mg 20 f.c. tabs.
	{
		id: 'depratiox-20-20-tabs-ad2',
		name: 'depratiox 20 mg 20 f.c. tabs.',
		genericName: 'vortioxetine',
		concentration: '20mg',
		price: 396,
		matchKeywords: ['depratiox 20 20', 'vortioxetine 20', 'ديبراتيوكس ٢٠', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب (جرعة ٢٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (٢٠ مجم) مرة يومياً. الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: ['قد يسبب غثيان.', 'احذر متلازمة السيروتونين.'],
	},

	// 104) seroxat cr 12.5mg 30 f.c. tab
	{
		id: 'seroxat-cr-12-5-30-tabs-ad2',
		name: 'seroxat cr 12.5mg 30 f.c. tab',
		genericName: 'paroxetine',
		concentration: '12.5mg',
		price: 242,
		matchKeywords: ['seroxat cr 12.5 30', 'paroxetine cr 12.5', 'panic', 'anxiety', 'depression', 'سيروكسات ممتد ١٢٫٥', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد المفعول (جرعة بدء شائعة) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: قرص ١٢٫٥ مجم مرة يومياً كبداية، ثم الزيادة إلى ٢٥–٣٧٫٥ مجم/يوم حسب الاستجابة. الحد الأقصى: ٦٢٫٥ مجم/يوم. لا يُكسر/يُسحق.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 105) vixadep 150mg 60 s.r. tablets
	{
		id: 'vixadep-150-60-sr-tabs-ad2',
		name: 'vixadep 150mg 60 s.r. tablets',
		genericName: 'bupropion hydrochloride',
		concentration: '150mg',
		price: 221,
		matchKeywords: ['vixadep 150 60', 'bupropion 150', 'wellbutrin', 'smoking cessation', 'depression', 'فيكساديب', 'بوبروبيون', 'اقلاع التدخين', 'اكتئاب', '#antidepressants'],
		usage: 'بوبروبيون (منشط) للاكتئاب والمساعدة في الإقلاع عن التدخين.',
		timing: 'مرة يومياً ثم مرتين تدريجياً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Sustained-release Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: fixed('SR: يبدأ ١٥٠ مجم صباحاً لمدة ٣ أيام، ثم ١٥٠ مجم كل ١٢ ساعة. الحد الأقصى: ٤٠٠ مجم/يوم (SR). لا يُكسر/يُسحق.'),
		warnings: ['قد يسبب أرق/عصبية.', 'يزيد خطر التشنجات مع الجرعات العالية أو اضطرابات الأكل.', 'يُحذر مع ارتفاع ضغط غير منضبط.'],
	},

	// 106) ramdeep 40mg 10 f.c. tab.
	{
		id: 'ramdeep-40-10-tabs-ad2',
		name: 'ramdeep 40mg 10 f.c. tab.',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 43,
		matchKeywords: ['ramdeep 40 10', 'citalopram 40', 'ramdeep', 'رامديب', 'سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام للاكتئاب/القلق (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٢٠–٤٠ مجم/يوم. كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS, 'قد يطيل QT.'],
	},

	// 107) rapizapine 30 mg 10 tab.
	{
		id: 'rapizapine-30-10-tabs-ad2',
		name: 'rapizapine 30 mg 10 tab.',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 29.4,
		matchKeywords: ['rapizapine 30 10', 'mirtazapine 30', 'insomnia', 'appetite', 'رابيزابين', 'ميرتازابين', 'أرق', 'فاتح شهية', '#antidepressants'],
		usage: 'ميرتازابين للاكتئاب المصحوب بأرق/فقدان شهية (عبوة صغيرة).',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('نطاق الجرعة: ١٥–٤٥ مجم/يوم. جرعة شائعة: ٣٠ مجم قبل النوم.'),
		warnings: ['قد يسبب نعاس وزيادة وزن.'],
	},

	// 108) agovald 25mg 21 f.c. tabs
	{
		id: 'agovald-25-21-tabs-ad2',
		name: 'agovald 25mg 21 f.c. tabs',
		genericName: 'agomelatine',
		concentration: '25mg',
		price: 111,
		matchKeywords: ['agovald 25 21', 'agomelatine', 'valdoxan', 'sleep', 'depression', 'اجوفالد', 'اجوميلاتين', 'اكتئاب', 'نوم', '#antidepressants'],
		usage: 'أجوميلاتين للاكتئاب (يحسن النوم وتنظيم الساعة البيولوجية عند بعض المرضى).',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٢٥ مجم قبل النوم. يمكن الزيادة إلى ٥٠ مجم بعد ٢ أسبوع إذا لم يتحسن. الحد الأقصى: ٥٠ مجم/يوم.'),
		warnings: ['خطر ارتفاع إنزيمات كبد/التهاب كبد (يلزم متابعة).', 'ممنوع في مرضى الكبد.', 'قد يسبب دوخة/نعاس.'],
	},

	// 109) bedremine 50 mg 30 ext. rel.tabs.
	{
		id: 'bedremine-50-30-pr-tabs-ad2',
		name: 'bedremine 50 mg 30 ext. rel.tabs.',
		genericName: 'desvenlafaxine',
		concentration: '50mg',
		price: 153,
		matchKeywords: ['bedremine 50 30', 'desvenlafaxine 50', 'pristiq 50', 'depression', 'بدريمين ٥٠', '#antidepressants', '#snri'],
		usage: 'ديسفينلافاكسين ممتد المفعول للاكتئاب (جرعة ٥٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (٥٠ مجم) مرة يومياً. لا يُكسر/يُسحق.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 110) cymbalta 30 mg 28 caps.
	{
		id: 'cymbalta-30-28-caps-ad2',
		name: 'cymbalta 30 mg 28 caps.',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 399,
		matchKeywords: ['cymbalta 30 28', 'duloxetine 30', 'fibromyalgia', 'neuropathic pain', 'سيمبالتا', 'دولوكسيتين', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (الأصلي) للاكتئاب والقلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Delayed-Release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٣٠ مجم يومياً لمدة أسبوع ثم ٦٠ مجم يومياً. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 111) effegad 150 mg 28 e.r.cap
	{
		id: 'effegad-150-28-er-caps-ad2',
		name: 'effegad 150 mg 28 e.r.cap',
		genericName: 'venlafaxine',
		concentration: '150mg',
		price: 256,
		matchKeywords: ['effegad 150 28', 'venlafaxine xr 150', 'snri', 'depression', 'anxiety', 'ايفيجاد ١٥٠', '#antidepressants', '#snri'],
		usage: 'فينلافاكسين ممتد المفعول للاكتئاب والقلق (جرعة ١٥٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Modified-release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('XR: كبسولة ١٥٠ مجم مرة يومياً. جرعة شائعة: ٧٥–٢٢٥ مجم/يوم. الحد الأقصى المعتاد: ٢٢٥ مجم/يوم.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 112) excelsa 10mg 14 f.c.tab.
	{
		id: 'excelsa-10-14-tabs-ad2',
		name: 'excelsa 10mg 14 f.c.tab.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 66,
		matchKeywords: ['excelsa 10 14', 'escitalopram 10', 'اكسيلسا ١٠', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق (جرعة بدء شائعة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (١٠ مجم) مرة يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 113) excelsa 10mg 7 f.c.tab
	{
		id: 'excelsa-10-7-tabs-ad2',
		name: 'excelsa 10mg 7 f.c.tab',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 33,
		matchKeywords: ['excelsa 10 7', 'escitalopram 10', 'اكسيلسا ٧', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (١٠ مجم) مرة يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 114) futapramin 10 mg 30 f.c. tabs
	{
		id: 'futapramin-10-30-tabs-ad2',
		name: 'futapramin 10 mg 30 f.c. tabs',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 78,
		matchKeywords: ['futapramin 10 30', 'escitalopram 10', 'فوتابرامين', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (١٠ مجم) مرة يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 115) futapramin 20mg 30 f.c. tabs.
	{
		id: 'futapramin-20-30-tabs-ad2',
		name: 'futapramin 20mg 30 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 114,
		matchKeywords: ['futapramin 20 30', 'escitalopram 20', 'فوتابرامين ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق (جرعة ٢٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (٢٠ مجم) مرة يومياً (الحد الأقصى المعتاد).'),
		warnings: [...SSRI_WARNINGS],
	},

	// 116) mirtofutal 30mg 20 f.c. tabs
	{
		id: 'mirtofutal-30-20-tabs-ad2',
		name: 'mirtofutal 30mg 20 f.c. tabs',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 89,
		matchKeywords: ['mirtofutal 30 20', 'mirtazapine 30', 'insomnia', 'appetite', 'ميرتوفوتال', 'ميرتازابين', 'أرق', '#antidepressants'],
		usage: 'ميرتازابين للاكتئاب المصحوب بأرق/فقدان شهية.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('نطاق الجرعة: ١٥–٤٥ مجم/يوم. جرعة شائعة: ٣٠ مجم قبل النوم.'),
		warnings: ['قد يسبب نعاس وزيادة وزن.'],
	},

	// 117) nervalta 60 mg 10 del. rel. caps.
	{
		id: 'nervalta-60-10-dr-caps-ad2',
		name: 'nervalta 60 mg 10 del. rel. caps.',
		genericName: 'duloxetine',
		concentration: '60mg',
		price: 102,
		matchKeywords: ['nervalta 60 10', 'duloxetine 60', 'neuropathic pain', 'نيرفالتا', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب وآلام الأعصاب (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Delayed-Release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة ٣٠ مجم/يوم ثم ٦٠ مجم/يوم. جرعة ٦٠ مجم: كبسولة مرة يومياً.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 118) paroxetine cr 25mg 30 f.c. tablets
	{
		id: 'paroxetine-cr-25-30-tabs-ad2',
		name: 'paroxetine cr 25mg 30 f.c. tablets',
		genericName: 'paroxetine',
		concentration: '25mg',
		price: 105,
		matchKeywords: ['paroxetine cr 25 30', 'paroxetine controlled release', 'seroxat cr 25', 'panic', 'anxiety', 'paroxetine', 'باروكستين ممتد ٢٥', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد المفعول للاكتئاب واضطرابات القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: قرص ٢٥ مجم مرة يومياً. يمكن الزيادة تدريجياً حتى ٣٧٫٥–٦٢٫٥ مجم/يوم حسب الاستجابة. لا يُكسر/يُسحق.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 119) philozac 10mg 10 caps.
	{
		id: 'philozac-10-10-caps-ad2',
		name: 'philozac 10mg 10 caps.',
		genericName: 'fluoxetine',
		concentration: '10mg',
		price: 9,
		matchKeywords: ['philozac 10 10', 'fluoxetine 10', 'prozac', 'depression', 'ocd', 'bulimia', 'فيلوزاك', 'فلوكسيتين', '#antidepressants', '#ssri'],
		usage: 'فلوكسيتين للاكتئاب/الوسواس/النهام العصبي حسب الحالة.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 96,
		maxAgeMonths: 1200,
		minWeight: 25,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٠–٢٠ مجم صباحاً. يمكن الزيادة تدريجياً حتى ٤٠–٦٠ مجم/يوم حسب الحالة.'),
		warnings: [...SSRI_WARNINGS, 'له نصف عمر طويل؛ التحسن/الآثار قد تتأخر.'],
	},

	// 120) pristiq 50mg 30 ext. rel. tab
	{
		id: 'pristiq-50-30-pr-tabs-ad2',
		name: 'pristiq 50mg 30 ext. rel. tab',
		genericName: 'desvenlafaxine',
		concentration: '50mg',
		price: 231.5,
		matchKeywords: ['pristiq 50 30', 'desvenlafaxine 50', 'pristiq', 'depression', 'بريستيك', '#antidepressants', '#snri'],
		usage: 'ديسفينلافاكسين ممتد المفعول للاكتئاب (الدواء الأصلي).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٥٠ مجم مرة يومياً. لا يُكسر/يُسحق.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 121) psychopram 20 mg 20 f.c. tabs.
	{
		id: 'psychopram-20-20-tabs-ad2',
		name: 'psychopram 20 mg 20 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 140,
		matchKeywords: ['psychopram 20 20', 'escitalopram 20', 'psychopram', 'سايكوبرام', 'اسيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ١٠ مجم يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 122) vilazover 40 mg 30 tabs
	{
		id: 'vilazover-40-30-tabs-ad2',
		name: 'vilazover 40 mg 30 tabs',
		genericName: 'vilazodone hydrochloride',
		concentration: '40mg',
		price: 337.5,
		matchKeywords: ['vilazover 40 30', 'vilazodone 40', 'depression', 'فيلازوفر', 'فيلازودون', 'اكتئاب', '#antidepressants'],
		usage: 'فيلازودون للاكتئاب (جرعة مداومة ٤٠ مجم).',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بعد التدرج: ٤٠ مجم مرة يومياً مع الطعام.'),
		warnings: ['قد يسبب إسهال/غثيان.', 'احذر متلازمة السيروتونين.'],
	},

	// 123) zapimert 30mg 30 f.c. tabs.
	{
		id: 'zapimert-30-30-tabs-ad2',
		name: 'zapimert 30mg 30 f.c. tabs.',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 165,
		matchKeywords: ['zapimert 30 30', 'mirtazapine 30', 'zapimert', 'زابيمرت', 'اكتئاب', 'أرق', 'فاتح شهية', '#antidepressants'],
		usage: 'ميرتازابين للاكتئاب المصحوب بأرق/فقدان شهية.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('نطاق الجرعة: ١٥–٤٥ مجم/يوم. جرعة شائعة: ٣٠ مجم قبل النوم.'),
		warnings: ['قد يسبب نعاس وزيادة وزن.'],
	},

	// 124) lustral 50 mg 10 f.c.tabs.
	{
		id: 'lustral-50-10-tabs-ad2',
		name: 'lustral 50 mg 10 f.c.tabs.',
		genericName: 'sertraline',
		concentration: '50mg',
		price: 50.5,
		matchKeywords: ['lustral 50 10', 'sertraline 50', 'depression', 'anxiety', 'ocd', 'panic', 'لسترال', 'سيرترالين', 'اكتئاب', 'قلق', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'سيرترالين للاكتئاب واضطرابات القلق/الوسواس.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٥–٥٠ مجم يومياً. يمكن الزيادة تدريجياً حتى ٢٠٠ مجم/يوم حسب التشخيص.'),
		warnings: [...SSRI_WARNINGS],
	},

	// 125) wadiloxtin 30 mg 28 del. rel. caps.
	{
		id: 'wadiloxtin-30-28-dr-caps-ad2',
		name: 'wadiloxtin 30 mg 28 del. rel. caps.',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 204,
		matchKeywords: ['wadiloxtin 30 28', 'duloxetine 30', 'neuropathic pain', 'واديلوكسـتين', 'دولوكسيتين', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين للاكتئاب والقلق وآلام الأعصاب (جرعة بدء شائعة ٣٠ مجم).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Delayed-Release Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٣٠ مجم مرة يومياً لمدة أسبوع ثم ٦٠ مجم/يوم حسب الاستجابة. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SNRI_WARNINGS],
	},

	// 126) cipramax 40mg 20 f.c. tabs.
	{
		id: 'cipramax-40-20-tabs-ad2',
		name: 'cipramax 40mg 20 f.c. tabs.',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 100,
		matchKeywords: ['cipramax 40 20', 'citalopram 40', 'cipramax', 'سيبراماكس ٢٠', 'سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام للاكتئاب والقلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٢٠–٤٠ مجم/يوم. كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_WARNINGS, 'قد يطيل QT.'],
	},
];

