
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const fixed = (text: string) => (_w: number, _a: number) => text;

const SSRI_SNRI_CORE_WARNINGS = [
	'تحذير: أفكار انتحارية خصوصاً في بداية العلاج عند صغار السن (<٢٥ سنة)؛ راقب المزاج عن قرب.',
	'لا يوقف فجأة (أعراض انسحاب). يجب السحب التدريجي.',
	'ممنوع الجمع مع مثبطات MAO (خطر متلازمة السيروتونين المميتة).',
];

const TCA_CORE_WARNINGS = [
	'تحذير: أفكار انتحارية خصوصاً في بداية العلاج عند صغار السن (<٢٥ سنة).',
	'لا يوقف فجأة.',
	'خطر سمّية قلبية بجرعات زائدة؛ ممنوع الجمع مع MAOIs.',
];

const citalopramSolutionRule = (concentration: string) => {
	// citalo 2mg/ml: common adult dosing 10–40 mg/day
	return (_w: number, _a: number) => {
		const normalized = concentration.toLowerCase().replace(/\s/g, '');
		const match = normalized.match(/(\d+(?:\.\d+)?)mg\/(\d+(?:\.\d+)?)ml/);
		const mgPerMl = match ? Number(match[1]) / Number(match[2]) : null;
		const vol10 = mgPerMl ? 10 / mgPerMl : null;
		const vol20 = mgPerMl ? 20 / mgPerMl : null;
		return (
			'بداية شائعة: ١٠ مجم يومياً ثم ٢٠ مجم يومياً بعد أسبوع حسب التحمل. ' +
			'الحد الأقصى: ٤٠ مجم/يوم (كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم بسبب QT). ' +
			(vol10 !== null && vol20 !== null
				? `يعادل تقريباً ${toAr(vol10.toFixed(0))} مل لجرعة ١٠ مجم و${toAr(vol20.toFixed(0))} مل لجرعة ٢٠ مجم.`
				: '')
		);
	};
};

export const ANTIDEPRESSANTS_1: Medication[] = [
	// 1) estikan 20mg 14 f.c.tab.
	{
		id: 'estikan-20-14-tabs-ad1',
		name: 'estikan 20mg 14 f.c.tab.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 106,
		matchKeywords: [
			'estikan', 'estikan 20', 'escitalopram', 'es citalopram', 'cipralex',
			'depression', 'anxiety', 'panic', 'gad', 'social anxiety',
			'اكتئاب', 'قلق', 'هلع', 'نوبات هلع', 'رهاب اجتماعي', 'استيكان',
			'#antidepressants', '#ssri'
		],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب واضطرابات القلق/الهلع.',
		timing: 'مرة يومياً مع/بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص ١٠ مجم مرة يومياً بدون اعتبار للأكل بداية، يمكن الزيادة إلى ٢٠ مجم/يوم بعد ١–٢ أسبوع (حد أقصى ٢٠ مجم/يوم) – علاج مزمن لعدة أشهر.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع في البداية.', 'قد يسبب اضطراب جنسي.'],
	},

	// 2) tryptizol 25 mg 30 tabs.
	{
		id: 'tryptizol-25-30-tabs-ad1',
		name: 'tryptizol 25 mg 30 tabs.',
		genericName: 'amitriptyline',
		concentration: '25mg',
		price: 33,
		matchKeywords: [
			'tryptizol', 'tryptizol 25', 'amitriptyline', 'tca',
			'neuropathic pain', 'migraine prophylaxis', 'insomnia', 'depression',
			'تريبتيزول', 'أميتريبتيلين', 'ألم أعصاب', 'صداع نصفي', 'أرق', 'اكتئاب',
			'#antidepressants', '#tricyclic'
		],
		usage: 'أميتريبتيلين (TCA) للاكتئاب وآلام الأعصاب/الأرق (جرعات منخفضة للألم/الأرق وأعلى للاكتئاب).',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('للألم العصبي/الأرق: يبدأ ١٠–٢٥ مجم قبل النوم ثم زيادة تدريجية حتى ٥٠–٧٥ مجم/يوم. للاكتئاب: ٢٥ مجم ٢–٣ مرات يومياً أو ٥٠–١٠٠ مجم ليلاً ثم التدرج. الحد الأقصى (كبار): ١٥٠ مجم/يوم.'),
		warnings: [...TCA_CORE_WARNINGS, 'جفاف فم/إمساك/زغللة.', 'يُحذر في الجلوكوما واحتباس البول واضطرابات نظم القلب.'],
	},

	// 3) cymbatex 20 mg 30 caps.
	{
		id: 'cymbatex-20-30-caps-ad1',
		name: 'cymbatex 20 mg 30 caps.',
		genericName: 'duloxetine',
		concentration: '20mg',
		price: 174,
		matchKeywords: [
			'cymbatex', 'cymbatex 20', 'duloxetine', 'cymbalta', 'snri',
			'depression', 'anxiety', 'diabetic neuropathy', 'fibromyalgia', 'chronic pain',
			'سيمباتكس', 'دولوكسيتين', 'اكتئاب', 'قلق', 'ألم أعصاب', 'اعتلال أعصاب سكري', 'فيبروميالجيا',
			'#antidepressants', '#snri'
		],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب والآلام المزمنة.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٣٠ مجم يومياً ثم ٦٠ مجم/يوم. مع تركيز ٢٠ مجم: يمكن بدء ٢٠ مجم يومياً في الحساسية للآثار الجانبية ثم الزيادة. الجرعة الشائعة: ٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/جفاف فم.', 'قد يرفع ضغط الدم قليلاً.', 'يُحذر في أمراض الكبد الشديدة.'],
	},

	// 4) cymbatex 30 mg 30 caps.
	{
		id: 'cymbatex-30-30-caps-ad1',
		name: 'cymbatex 30 mg 30 caps.',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 228,
		matchKeywords: ['cymbatex 30', 'duloxetine 30', 'snri', 'سيمباتكس ٣٠', 'دولوكسيتين', 'اكتئاب', 'قلق', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٣٠ مجم يومياً لمدة أسبوع ثم ٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/أرق.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 5) cymbatex 60 mg 30 cap
	{
		id: 'cymbatex-60-30-caps-ad1',
		name: 'cymbatex 60 mg 30 cap',
		genericName: 'duloxetine',
		concentration: '60mg',
		price: 295.5,
		matchKeywords: ['cymbatex 60', 'duloxetine 60', 'snri', 'سيمباتكس ٦٠', 'اكتئاب', 'قلق', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('الجرعة الشائعة: ٦٠ مجم مرة يومياً. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/جفاف فم.', 'يُحذر في أمراض الكبد.'],
	},

	// 6) efexor xr 75mg 14 caps
	{
		id: 'efexor-xr-75-14-caps-ad1',
		name: 'efexor xr 75mg 14 caps',
		genericName: 'venlafaxine',
		concentration: '75mg',
		price: 158,
		matchKeywords: ['efexor xr 75', 'venlafaxine xr 75', 'snri', 'extended release', 'ايفيكسور', 'فينلافاكسين', 'اكتئاب', 'قلق', '#antidepressants', '#snri'],
		usage: 'فينلافاكسين ممتد المفعول (SNRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'S.R. Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('XR: بداية شائعة ٣٧٫٥–٧٥ مجم مرة يومياً. يمكن الزيادة كل ١–٢ أسبوع حتى ١٥٠–٢٢٥ مجم/يوم. الحد الأقصى الشائع: ٢٢٥ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يرفع ضغط الدم (خصوصاً جرعات عالية).', 'قد يسبب غثيان/أرق.'],
	},

	// 7) efexor xr 150mg 14 caps.
	{
		id: 'efexor-xr-150-14-caps-ad1',
		name: 'efexor xr 150mg 14 caps.',
		genericName: 'venlafaxine',
		concentration: '150mg',
		price: 230,
		matchKeywords: ['efexor xr 150', 'venlafaxine xr 150', 'snri', 'ايفيكسور ١٥٠', 'فينلافاكسين', 'اكتئاب', 'قلق', '#antidepressants', '#snri'],
		usage: 'فينلافاكسين ممتد المفعول (SNRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'S.R. Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('XR: جرعة شائعة ١٥٠ مجم مرة يومياً. يمكن الزيادة حتى ٢٢٥ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يرفع ضغط الدم.', 'قد يسبب أرق/غثيان.'],
	},

	// 8) faverin 100mg 30 f.c. scored tab
	{
		id: 'faverin-100-30-tabs-ad1',
		name: 'faverin 100mg 30 f.c. scored tab',
		genericName: 'fluvoxamine maleate',
		concentration: '100mg',
		price: 261,
		matchKeywords: ['faverin 100', 'fluvoxamine', 'ssri', 'ocd', 'وسواس', 'فافرن', 'فلوفوكسامين', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'فلوفوكسامين (SSRI) خصوصاً للوسواس القهري والاكتئاب.',
		timing: 'مساءً أو مقسمة – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٥٠ مجم مساءً ثم زيادة ٥٠ مجم كل أسبوع. جرعة شائعة: ١٠٠–٢٠٠ مجم/يوم. الحد الأقصى: ٣٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'تداخلات دوائية كثيرة (مثبط CYP1A2/CYP2C19).', 'قد يسبب غثيان/نعاس.'],
	},

	// 9) lustral 50 mg 20 f.c.tabs.
	{
		id: 'lustral-50-20-tabs-ad1',
		name: 'lustral 50 mg 20 f.c.tabs.',
		genericName: 'sertraline',
		concentration: '50mg',
		price: 136,
		matchKeywords: ['lustral 50 20', 'sertraline 50', 'zoloft', 'ssri', 'depression', 'anxiety', 'ocd', 'ptsd', 'لسترال', 'سيرترالين', 'اكتئاب', 'قلق', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق/الوسواس واضطرابات أخرى.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٥–٥٠ مجم يومياً. يمكن زيادة ٢٥–٥٠ مجم كل أسبوع حتى ٢٠٠ مجم/يوم. الحد الأقصى: ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة/إسهال.', 'قد يسبب اضطراب جنسي.'],
	},

	// 10) mirtimash 30 mg 30 scored f.c. tabs.
	{
		id: 'mirtimash-30-30-tabs-ad1',
		name: 'mirtimash 30 mg 30 scored f.c. tabs.',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 177,
		matchKeywords: ['mirtimash 30', 'mirtazapine 30', 'remeron', 'sleep', 'insomnia', 'depression', 'ميرتيمش', 'ميرتازابين', 'اكتئاب', 'أرق', '#antidepressants'],
		usage: 'ميرتازابين للاكتئاب خصوصاً مع الأرق/نقص الشهية.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٥ مجم قبل النوم. يمكن الزيادة إلى ٣٠ مجم ثم ٤٥ مجم حسب الاستجابة. الحد الأقصى: ٤٥ مجم/يوم.'),
		warnings: ['قد يسبب نعاس/زيادة وزن.', 'قد يرفع الدهون بالدم.', 'نادر: نقص كريات بيضاء (اذهب للطبيب عند حرارة/التهاب حلق).'],
	},

	// 11) moodapex 50mg 30 f.c.tab.
	{
		id: 'moodapex-50-30-tabs-ad1',
		name: 'moodapex 50mg 30 f.c.tab.',
		genericName: 'sertraline',
		concentration: '50mg',
		price: 111,
		matchKeywords: ['moodapex 50 30', 'sertraline 50', 'ssri', 'اكتئاب', 'قلق', 'moodapex', 'مودابكس', 'سيرترالين', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق/الوسواس.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٥٠ مجم يومياً (أو ٢٥ مجم لمدة أسبوع ثم ٥٠). يمكن الزيادة حتى ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة.', 'قد يسبب اضطراب جنسي.'],
	},

	// 12) tryptizol 10mg 100 tab
	{
		id: 'tryptizol-10-100-tabs-ad1',
		name: 'tryptizol 10mg 100 tab',
		genericName: 'amitriptyline',
		concentration: '10mg',
		price: 30,
		matchKeywords: ['tryptizol 10 100', 'amitriptyline 10', 'sleep', 'neuropathic pain', 'migraine', 'تريبتيزول ١٠٠', 'ألم أعصاب', 'أرق', '#antidepressants', '#tricyclic'],
		usage: 'أميتريبتيلين بجرعات صغيرة للألم العصبي/الأرق/الصداع النصفي.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يبدأ ١٠ مجم قبل النوم، ويمكن الزيادة كل أسبوع حتى ٢٥–٥٠ مجم قبل النوم حسب الاستجابة.'),
		warnings: [...TCA_CORE_WARNINGS, 'جفاف فم/إمساك/زغللة.', 'يُحذر في الجلوكوما واحتباس البول واضطرابات نظم القلب.'],
	},

	// 13) anafranil 25mg 30 tab.
	{
		id: 'anafranil-25-30-tabs-ad1',
		name: 'anafranil 25mg 30 tab.',
		genericName: 'clomipramine',
		concentration: '25mg',
		price: 66,
		matchKeywords: ['anafranil 25', 'clomipramine', 'tca', 'ocd', 'وسواس', 'انفرانيل', 'كلوميبرامين', 'اكتئاب', '#antidepressants', '#tricyclic'],
		usage: 'كلوميبرامين (TCA) خصوصاً للوسواس القهري والاكتئاب.',
		timing: 'مساءً ثم تُقسم – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٥ مجم مساءً ثم زيادة تدريجية. جرعة شائعة للوسواس: ١٠٠–١٥٠ مجم/يوم مقسمة. الحد الأقصى: ٢٥٠ مجم/يوم.'),
		warnings: [...TCA_CORE_WARNINGS, 'جفاف فم/إمساك/نعاس.', 'قد يطيل QT/يسبب اضطراب نظم؛ يُحذر مع أمراض القلب.', 'قد يقلل عتبة التشنج.'],
	},

	// 14) anafronil sr 75mg 20 f.c.tab.
	{
		id: 'anafronil-sr-75-20-tabs-ad1',
		name: 'anafrronil sr 75mg 20 f.c.tab.'.replace('anafrronil', 'anafronil'),
		genericName: 'clomipramine',
		concentration: '75mg',
		price: 106,
		matchKeywords: ['anafronil sr 75', 'clomipramine sr', 'ocd', 'وسواس', 'انفرانيل ممتد', '#antidepressants', '#tricyclic'],
		usage: 'كلوميبرامين ممتد المفعول للوسواس القهري/الاكتئاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('SR: يبدأ عادةً ٧٥ مجم مرة يومياً ويمكن الزيادة تدريجياً حتى ١٥٠ مجم/يوم أو أكثر حسب الاستجابة. الحد الأقصى: ٢٥٠ مجم/يوم.'),
		warnings: [...TCA_CORE_WARNINGS, 'جفاف فم/إمساك/نعاس.', 'يُحذر مع أمراض القلب واضطراب نظم.', 'قد يقلل عتبة التشنج.'],
	},

	// 15) estikana 10mg 28 f.c.tab.
	{
		id: 'estikana-10-28-tabs-ad1',
		name: 'estikana 10mg 28 f.c.tab.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 132,
		matchKeywords: ['estikana 10 28', 'escitalopram 10', 'cipralex', 'ssri', 'استيكانا', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة بدء شائعة: ١٠ مجم مرة يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم. الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 16) estikana 10 mg 14 f.c. tab
	{
		id: 'estikana-10-14-tabs-ad1',
		name: 'estikana 10 mg 14 f.c. tab',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 48,
		matchKeywords: ['estikana 10 14', 'escitalopram 10', 'ssri', 'استيكانا ١٤', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 17) wellinta 150 mg 30s.r.f.c.tabs.
	{
		id: 'wellinta-150-30-sr-tabs-ad1',
		name: 'wellinta 150 mg 30s.r.f.c.tabs.',
		genericName: 'bupropion hydrochloride',
		concentration: '150mg',
		price: 291,
		matchKeywords: ['wellinta 150', 'bupropion', 'wellbutrin', 'smoking cessation', 'depression', 'ويلينتا', 'بوبروبيون', 'اقلاع عن التدخين', 'اكتئاب', '#antidepressants'],
		usage: 'بوبروبيون (منشط نسبيًا) للاكتئاب والمساعدة في الإقلاع عن التدخين.',
		timing: 'صباحاً ثم مرتين يومياً تدريجياً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Sustained-release Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: fixed('SR: يبدأ ١٥٠ مجم صباحاً لمدة ٣ أيام، ثم ١٥٠ مجم مرتين يومياً (فاصل ≥٨ ساعات). الحد الأقصى: ٣٠٠ مجم/يوم (SR).'),
		warnings: ['ممنوع في الصرع أو اضطرابات الأكل (يقلل عتبة التشنج).', 'قد يسبب أرق/عصبية.', 'تداخلات دوائية (مثبط CYP2D6).'],
	},

	// 18) esctikana 10 mg 28 f.c.tabs.
	{
		id: 'esctikana-10-28-tabs-ad1',
		name: 'esctikana 10 mg 28 f.c.tabs.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 132,
		matchKeywords: ['esctikana 10 28', 'escitalopram', 'ssri', 'اسكتكانا', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم. الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 19) tryptizol 10 mg 20 tabs.
	{
		id: 'tryptizol-10-20-tabs-ad1',
		name: 'tryptizol 10 mg 20 tabs.',
		genericName: 'amitriptyline',
		concentration: '10mg',
		price: 10,
		matchKeywords: ['tryptizol 10 20', 'amitriptyline 10', 'sleep', 'pain', 'تريبتيزول ٢٠', 'ألم أعصاب', 'أرق', '#antidepressants', '#tricyclic'],
		usage: 'أميتريبتيلين بجرعات صغيرة للألم العصبي/الأرق.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يبدأ ١٠ مجم قبل النوم، ويمكن الزيادة تدريجياً حتى ٢٥–٥٠ مجم قبل النوم.'),
		warnings: [...TCA_CORE_WARNINGS, 'جفاف فم/إمساك/زغللة.', 'يُحذر في الجلوكوما واحتباس البول وأمراض القلب.'],
	},

	// 20) esctikana 10 mg 14 f.c.tabs.
	{
		id: 'esctikana-10-14-tabs-ad1',
		name: 'esctikana 10 mg 14 f.c.tabs.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 17,
		matchKeywords: ['esctikana 10 14', 'escitalopram 10', 'ssri', 'اسكتكانا ١٤', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 21) paroxedep cr 37.5 mg 30 f.c.tabs.
	{
		id: 'paroxedep-cr-37-5-30-tabs-ad1',
		name: 'paroxedep cr 37.5 mg 30 f.c.tabs.',
		genericName: 'paroxetine',
		concentration: '37.5mg',
		price: 117,
		matchKeywords: ['paroxedep cr 37.5', 'paroxetine cr 37.5', 'ssri', 'controlled release', 'panic', 'anxiety', 'depression', 'باروكسيديب', 'باروكسيتين', 'قلق', 'هلع', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد المفعول (SSRI) للاكتئاب واضطرابات القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: بداية شائعة ١٢٫٥–٢٥ مجم مرة يومياً. يمكن الزيادة تدريجياً كل أسبوع. جرعة شائعة: ٢٥–٣٧٫٥ مجم/يوم. الحد الأقصى: ٦٢٫٥ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب نعاس/زيادة وزن.', 'أعراض انسحاب قوية إذا توقف فجأة.', 'يُحذر في الحمل (خصوصاً الثلث الأول).'],
	},

	// 22) vortoxicalm 10 mg 20 f.c.tabs.
	{
		id: 'vortoxicalm-10-20-tabs-ad1',
		name: 'vortoxicalm 10 mg 20 f.c.tabs.',
		genericName: 'vortioxetine',
		concentration: '10mg',
		price: 340,
		matchKeywords: ['vortoxicalm 10', 'vortioxetine 10', 'brintellix', 'depression', 'فوكسيتين', 'فورتيوكسيتين', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب (قد يساعد على التركيز/المعرفية عند بعض المرضى).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٠ مجم مرة يومياً. يمكن الزيادة إلى ٢٠ مجم/يوم. يمكن تقليلها إلى ٥ مجم عند عدم التحمل.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان في البداية.'],
	},

	// 23) vortoxicalm 20 mg 20 f.c.tabs.
	{
		id: 'vortoxicalm-20-20-tabs-ad1',
		name: 'vortoxicalm 20 mg 20 f.c.tabs.',
		genericName: 'vortioxetine',
		concentration: '20mg',
		price: 534,
		matchKeywords: ['vortoxicalm 20', 'vortioxetine 20', 'depression', 'فورتيوكسيتين ٢٠', 'اكتئاب', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٢٠ مجم مرة يومياً (بعد بدء ١٠ مجم).'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.'],
	},

	// 24) joviapram 10 mg 30 f.c. tabs.
	{
		id: 'joviapram-10-30-tabs-ad1',
		name: 'joviapram 10 mg 30 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 115.5,
		matchKeywords: ['joviapram 10 30', 'escitalopram 10', 'ssri', 'جوفيابرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 25) ciprapro 10mg 20 f.c. tab.
	{
		id: 'ciprapro-10-20-tabs-ad1',
		name: 'ciprapro 10mg 20 f.c. tab.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 158,
		matchKeywords: ['ciprapro 10 20', 'escitalopram 10', 'cipralex', 'ssri', 'سيبرابرو', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 26) ciprapro 10mg 30 f.c. tab
	{
		id: 'ciprapro-10-30-tabs-ad1',
		name: 'ciprapro 10mg 30 f.c. tab',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 237,
		matchKeywords: ['ciprapro 10 30', 'escitalopram 10', 'ssri', 'سيبرابرو ٣٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 27) duloxifutal 30 mg 30 caps.
	{
		id: 'duloxifutal-30-30-caps-ad1',
		name: 'duloxifutal 30 mg 30 caps.',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 303,
		matchKeywords: ['duloxifutal 30', 'duloxetine 30', 'snri', 'دولوكسيفيوتال', 'ألم أعصاب', 'اكتئاب', 'قلق', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٣٠ مجم يومياً لمدة أسبوع ثم ٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/جفاف فم.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 28) depram 40mg 20 f.c. tab
	{
		id: 'depram-40-20-tabs-ad1',
		name: 'depram 40mg 20 f.c. tab',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 140,
		matchKeywords: ['depram 40 20', 'citalopram 40', 'celexa', 'ssri', 'ديبرام', 'سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام (SSRI) للاكتئاب واضطرابات القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٠ مجم مرة يومياً. يمكن الزيادة إلى ٤٠ مجم/يوم بعد أسبوعين. الحد الأقصى: ٤٠ مجم/يوم (كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم بسبب QT).'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يطيل QT خصوصاً بجرعات عالية.', 'قد يسبب غثيان/صداع.'],
	},

	// 29) faverin 50mg 60 f.c. scored tab
	{
		id: 'faverin-50-60-tabs-ad1',
		name: 'faverin 50mg 60 f.c. scored tab',
		genericName: 'fluvoxamine',
		concentration: '50mg',
		price: 262,
		matchKeywords: ['faverin 50 60', 'fluvoxamine 50', 'ocd', 'ssri', 'فافرن ٥٠', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'فلوفوكسامين (SSRI) للوسواس القهري والاكتئاب.',
		timing: 'مساءً أو مقسمة – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٥٠ مجم مساءً ثم زيادة تدريجية. جرعة شائعة: ١٠٠–٢٠٠ مجم/يوم. الحد الأقصى: ٣٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'تداخلات دوائية كثيرة (مثبط CYP1A2/CYP2C19).', 'قد يسبب غثيان/نعاس.'],
	},

	// 30) remeron 30mg 10 tab.
	{
		id: 'remeron-30-10-tabs-ad1',
		name: 'remeron 30mg 10 tab.',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 135,
		matchKeywords: ['remeron 30 10', 'mirtazapine 30', 'sleep', 'appetite', 'remeron', 'ريمرون', 'ميرتازابين', 'اكتئاب', 'أرق', '#antidepressants'],
		usage: 'ميرتازابين للاكتئاب خصوصاً مع الأرق/نقص الشهية.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٥ مجم قبل النوم ثم زيادة إلى ٣٠–٤٥ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب نعاس/زيادة وزن.', 'نادر: نقص كريات بيضاء (اذهب للطبيب عند حرارة/التهاب حلق).'],
	},

	// 31) adwitine 30 mg 30 caps.
	{
		id: 'adwitine-30-30-caps-ad1',
		name: 'adwitine 30 mg 30 caps.',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 243,
		matchKeywords: ['adwitine 30', 'duloxetine 30', 'snri', 'ادويتين', 'اكتئاب', 'قلق', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية ٣٠ مجم يومياً ثم ٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 32) averomilan 50 mg 30 f.c. tabs.
	{
		id: 'averomilan-50-30-tabs-ad1',
		name: 'averomilan 50 mg 30 f.c. tabs.',
		genericName: 'milnacipran hydrochloride',
		concentration: '50mg',
		price: 106.5,
		matchKeywords: ['averomilan 50', 'milnacipran', 'snri', 'fibromyalgia', 'أفيروميلان', 'ميلناسـيبران', 'فيبروميالجيا', 'اكتئاب', '#antidepressants', '#snri'],
		usage: 'ميلناسـيبران (SNRI) يُستخدم للاكتئاب أو آلام مزمنة/فيبروميالجيا حسب التشخيص والحالة.',
		timing: 'كل ١٢ ساعة بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٥ مجم مرتين يومياً ثم ٥٠ مجم مرتين يومياً. الحد الأقصى المعتاد: ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/خفقان.', 'قد يرفع ضغط الدم.'],
	},

	// 33) cipralex 10mg 28 f.c. tab
	{
		id: 'cipralex-10-28-tabs-ad1',
		name: 'cipralex 10mg 28 f.c. tab',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 392,
		matchKeywords: ['cipralex 10 28', 'escitalopram', 'cipralex', 'ssri', 'سيبرالكس', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (الدواء الأصلي) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 34) duloxeprin 30mg 28 capsules
	{
		id: 'duloxeprin-30-28-caps-ad1',
		name: 'duloxeprin 30mg 28 capsules',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 180,
		matchKeywords: ['duloxeprin 30 28', 'duloxetine 30', 'snri', 'دولوكسبرين', 'اكتئاب', 'قلق', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية ٣٠ مجم يومياً ثم ٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 35) duloxeprin 60mg 28 capsules
	{
		id: 'duloxeprin-60-28-caps-ad1',
		name: 'duloxeprin 60mg 28 capsules',
		genericName: 'duloxetine',
		concentration: '60mg',
		price: 214,
		matchKeywords: ['duloxeprin 60 28', 'duloxetine 60', 'snri', 'دولوكسبرين ٦٠', 'اكتئاب', 'قلق', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('الجرعة الشائعة: ٦٠ مجم مرة يومياً. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 36) serpass 100mg 30 f.c. tab.
	{
		id: 'serpass-100-30-tabs-ad1',
		name: 'serpass 100mg 30 f.c. tab.',
		genericName: 'sertraline',
		concentration: '100mg',
		price: 177,
		matchKeywords: ['serpass 100 30', 'sertraline 100', 'ssri', 'سيرباس', 'سيرترالين', 'اكتئاب', 'قلق', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق/الوسواس.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٥٠–١٠٠ مجم يومياً. يمكن الزيادة حتى ٢٠٠ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة.', 'قد يسبب اضطراب جنسي.'],
	},

	// 37) hermpro 10mg 20 f.c. tab.
	{
		id: 'hermpro-10-20-tabs-ad1',
		name: 'hermpro 10mg 20 f.c. tab.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 122,
		matchKeywords: ['hermpro 10 20', 'escitalopram 10', 'ssri', 'هيرمبرو', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 38) hermpro 20mg 20 f.c. tab.
	{
		id: 'hermpro-20-20-tabs-ad1',
		name: 'hermpro 20mg 20 f.c. tab.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 103,
		matchKeywords: ['hermpro 20 20', 'escitalopram 20', 'ssri', 'هيرمبرو ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً (عادةً بعد بدء ١٠ مجم). الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 39) karbalta 30 mg 28 caps.
	{
		id: 'karbalta-30-28-caps-ad1',
		name: 'karbalta 30 mg 28 caps.',
		genericName: 'duloxetine',
		concentration: '30mg',
		price: 212,
		matchKeywords: ['karbalta 30 28', 'duloxetine 30', 'cymbalta', 'snri', 'كاربالتا', 'اكتئاب', 'قلق', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/القلق وآلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية ٣٠ مجم يومياً ثم ٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 40) paroxedep cr 12.5 mg 10 f.c. tab
	{
		id: 'paroxedep-cr-12-5-10-tabs-ad1',
		name: 'paroxedep cr 12.5 mg 10 f.c. tab',
		genericName: 'paroxetine',
		concentration: '12.5mg',
		price: 27,
		matchKeywords: ['paroxedep cr 12.5 10', 'paroxetine cr 12.5', 'ssri', 'باروكسيديب ١٢٫٥', 'قلق', 'اكتئاب', 'هلع', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد (CR) للاكتئاب/القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: بداية شائعة ١٢٫٥ مجم مرة يومياً. يمكن الزيادة تدريجياً كل أسبوع.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'أعراض انسحاب قوية إذا توقف فجأة.', 'قد يسبب نعاس/زيادة وزن.', 'يُحذر في الحمل (خصوصاً الثلث الأول).'],
	},

	// 41) paroxedep cr 25 mg 10 f.c. tab
	{
		id: 'paroxedep-cr-25-10-tabs-ad1',
		name: 'paroxedep cr 25 mg 10 f.c. tab',
		genericName: 'paroxetine',
		concentration: '25mg',
		price: 33,
		matchKeywords: ['paroxedep cr 25 10', 'paroxetine cr 25', 'ssri', 'باروكسيديب ٢٥', 'قلق', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد (CR) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: جرعة شائعة ٢٥ مجم مرة يومياً. يمكن الزيادة تدريجياً حسب الاستجابة.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'أعراض انسحاب قوية إذا توقف فجأة.', 'قد يسبب نعاس/زيادة وزن.', 'يُحذر في الحمل (خصوصاً الثلث الأول).'],
	},

	// 42) paroxetine cr 12.5mg 30 f.c. tab
	{
		id: 'paroxetine-cr-12-5-30-tabs-ad1',
		name: 'paroxetine cr 12.5mg 30 f.c. tab',
		genericName: 'paroxetine',
		concentration: '12.5mg',
		price: 99,
		matchKeywords: ['paroxetine cr 12.5 30', 'paroxetine controlled release', 'ssri', 'قلق', 'هلع', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد (CR) للاكتئاب/القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: بداية شائعة ١٢٫٥ مجم مرة يومياً. يمكن الزيادة تدريجياً.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'أعراض انسحاب قوية إذا توقف فجأة.', 'قد يسبب نعاس/زيادة وزن.', 'يُحذر في الحمل (خصوصاً الثلث الأول).'],
	},

	// 43) philozac 20mg 10 caps.
	{
		id: 'philozac-20-10-caps-ad1',
		name: 'philozac 20mg 10 caps.',
		genericName: 'fluoxetine',
		concentration: '20mg',
		price: 11,
		matchKeywords: ['philozac 20 10', 'fluoxetine 20', 'prozac', 'ssri', 'depression', 'bulimia', 'ocd', 'فيلوزاك', 'فلوكسيتين', 'اكتئاب', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'فلوكسيتين (SSRI) للاكتئاب/الوسواس واضطرابات أخرى.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٠ مجم صباحاً. يمكن الزيادة بعد ٢–٤ أسابيع حتى ٤٠–٦٠ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب أرق/غثيان.', 'نصف عمر طويل؛ تداخلات دوائية كثيرة (مثبط CYP2D6).'],
	},

	// 44) philozac 20mg 30 caps.
	{
		id: 'philozac-20-30-caps-ad1',
		name: 'philozac 20mg 30 caps.',
		genericName: 'fluoxetine',
		concentration: '20mg',
		price: 57,
		matchKeywords: ['philozac 20 30', 'fluoxetine 20', 'ssri', 'فيلوزاك ٣٠', 'اكتئاب', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'فلوكسيتين (SSRI) للاكتئاب/الوسواس.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم صباحاً كبداية شائعة. يمكن الزيادة تدريجياً حتى ٤٠–٦٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب أرق/غثيان.', 'نصف عمر طويل؛ تداخلات دوائية كثيرة (مثبط CYP2D6).'],
	},

	// 45) psychopram 10 mg 30 f.c. tabs.
	{
		id: 'psychopram-10-30-tabs-ad1',
		name: 'psychopram 10 mg 30 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 138,
		matchKeywords: ['psychopram 10 30', 'escitalopram 10', 'ssri', 'سايكوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 46) remeron soltab 30mg orodisp.tabs.
	{
		id: 'remeron-soltab-30-odt-ad1',
		name: 'remeron soltab 30mg orodisp.tabs.',
		genericName: 'mirtazapine',
		concentration: '30mg',
		price: 40,
		matchKeywords: ['remeron soltab 30', 'mirtazapine odt', 'orodispersible', 'sleep', 'remeron', 'ريمرون سولتاب', 'قرص يذوب', 'اكتئاب', 'أرق', '#antidepressants'],
		usage: 'ميرتازابين قرص متحلل بالفم للاكتئاب خصوصاً مع الأرق.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Orodispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ١٥ مجم قبل النوم ثم زيادة إلى ٣٠–٤٥ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب نعاس/زيادة وزن.', 'نادر: نقص كريات بيضاء (اذهب للطبيب عند حرارة/التهاب حلق).'],
	},

	// 47) serlift 100mg 10 f.c. tab.
	{
		id: 'serlift-100-10-tabs-ad1',
		name: 'serlift 100mg 10 f.c. tab.',
		genericName: 'sertraline',
		concentration: '100mg',
		price: 74,
		matchKeywords: ['serlift 100 10', 'sertraline 100', 'ssri', 'سيرلفت', 'اكتئاب', 'قلق', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق/الوسواس.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة شائعة: ٥٠–١٠٠ مجم يومياً. يمكن الزيادة حتى ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة.', 'قد يسبب اضطراب جنسي.'],
	},

	// 48) serpass 100mg 20 f.c. tab.
	{
		id: 'serpass-100-20-tabs-ad1',
		name: 'serpass 100mg 20 f.c. tab.',
		genericName: 'sertraline',
		concentration: '100mg',
		price: 135,
		matchKeywords: ['serpass 100 20', 'sertraline', 'ssri', 'سيرباس ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥٠–١٠٠ مجم يومياً. الحد الأقصى: ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة.', 'قد يسبب اضطراب جنسي.'],
	},

	// 49) serpass 50mg 30 f.c.tab.
	{
		id: 'serpass-50-30-tabs-ad1',
		name: 'serpass 50mg 30 f.c.tab.',
		genericName: 'sertraline',
		concentration: '50mg',
		price: 102,
		matchKeywords: ['serpass 50 30', 'sertraline 50', 'ssri', 'سيرباس ٥٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٥٠ مجم يومياً (أو ٢٥ مجم أسبوع ثم ٥٠). الحد الأقصى: ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة.', 'قد يسبب اضطراب جنسي.'],
	},

	// 50) elarpic 20 mg 20 f.c.tabs.
	{
		id: 'elarpic-20-20-tabs-ad1',
		name: 'elarpic 20 mg 20 f.c.tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 118,
		matchKeywords: ['elarpic 20 20', 'escitalopram 20', 'ssri', 'ايلاربيك', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً (بعد بدء ١٠ مجم). الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 51) duloxeprin 20 mg 28 caps.
	{
		id: 'duloxeprin-20-28-caps-ad1',
		name: 'duloxeprin 20 mg 28 caps.',
		genericName: 'duloxetine',
		concentration: '20mg',
		price: 148,
		matchKeywords: ['duloxeprin 20 28', 'duloxetine 20', 'snri', 'دولوكسبرين ٢٠', 'اكتئاب', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/آلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يمكن بدء ٢٠ مجم يومياً في الحساسية للآثار الجانبية ثم الزيادة إلى ٣٠–٦٠ مجم/يوم. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 52) depram 40mg 10 f.c. tab. (n/a)
	{
		id: 'depram-40-10-tabs-na-ad1',
		name: 'depram 40mg 10 f.c. tab. (n/a)',
		genericName: 'citalopram',
		concentration: '40mg',
		price: 40,
		matchKeywords: ['depram 40 10', 'citalopram 40', 'ديبرام ١٠', 'سيتالوبرام', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام (SSRI) للاكتئاب/القلق (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('عادةً ٢٠ مجم يومياً ثم ٤٠ مجم/يوم حسب الاستجابة. الحد الأقصى: ٤٠ مجم/يوم (كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم).'),
		warnings: ['قد يطيل QT خصوصاً بجرعات عالية.'],
	},

	// 53) paroxedep cr 12.5 mg 30 f.c.tabs.
	{
		id: 'paroxedep-cr-12-5-30-tabs-ad1',
		name: 'paroxedep cr 12.5 mg 30 f.c.tabs.',
		genericName: 'paroxetine',
		concentration: '12.5mg',
		price: 81,
		matchKeywords: ['paroxedep cr 12.5 30', 'paroxetine cr', 'ssri', 'باروكسيديب ٣٠', 'قلق', 'اكتئاب', 'هلع', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد (CR) للاكتئاب/القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: بداية ١٢٫٥ مجم مرة يومياً. يمكن الزيادة تدريجياً كل أسبوع.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'أعراض انسحاب قوية إذا توقف فجأة.', 'قد يسبب نعاس/زيادة وزن.', 'يُحذر في الحمل (خصوصاً الثلث الأول).'],
	},

	// 54) paroxedep cr 25 mg 30 f.c.tab
	{
		id: 'paroxedep-cr-25-30-tabs-ad1',
		name: 'paroxedep cr 25 mg 30 f.c.tab',
		genericName: 'paroxetine',
		concentration: '25mg',
		price: 99,
		matchKeywords: ['paroxedep cr 25 30', 'paroxetine cr 25', 'ssri', 'باروكسيديب ٢٥ ٣٠', 'قلق', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد (CR) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: جرعة شائعة ٢٥ مجم مرة يومياً. يمكن الزيادة تدريجياً حتى ٣٧٫٥–٥٠ مجم/يوم حسب الاستجابة.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'أعراض انسحاب قوية إذا توقف فجأة.', 'قد يسبب نعاس/زيادة وزن.', 'يُحذر في الحمل (خصوصاً الثلث الأول).'],
	},

	// 55) vortoxicalm 5 mg 20 f.c.tabs.
	{
		id: 'vortoxicalm-5-20-tabs-ad1',
		name: 'vortoxicalm 5 mg 20 f.c.tabs.',
		genericName: 'vortioxetine',
		concentration: '5mg',
		price: 151,
		matchKeywords: ['vortoxicalm 5', 'vortioxetine 5', 'depression', 'فورتيوكسيتين ٥', '#antidepressants'],
		usage: 'فورتيوكسيتين للاكتئاب (جرعة منخفضة عند عدم التحمل).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم مرة يومياً (جرعة بداية/عند عدم التحمل). يمكن الزيادة إلى ١٠ ثم ٢٠ مجم/يوم.'),
		warnings: ['قد يسبب غثيان.', 'تحذير متلازمة السيروتونين مع أدوية سيروتونين أخرى.'],
	},

	// 56) joviapram 20 mg 30 f.c. tabs.
	{
		id: 'joviapram-20-30-tabs-ad1',
		name: 'joviapram 20 mg 30 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 201,
		matchKeywords: ['joviapram 20 30', 'escitalopram 20', 'ssri', 'جوفيابرام ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً (بعد بدء ١٠ مجم). الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 57) citalo 2mg/ml oral solution 120 ml
	{
		id: 'citalo-2mg-ml-solution-120ml-ad1',
		name: 'citalo 2mg/ml oral solution 120 ml',
		genericName: 'citalopram',
		concentration: '2mg/ml',
		price: 38,
		matchKeywords: ['citalo solution', 'citalo 2mg/ml', 'citalopram drops', 'citalopram solution', 'سيتالو', 'محلول سيتالوبرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام محلول فموي للاكتئاب/القلق (مناسب لمن لديهم صعوبة بلع).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Solution',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: citalopramSolutionRule('2mg/ml'),
		warnings: ['قد يطيل QT خصوصاً بجرعات عالية.', 'تحذير أفكار انتحارية في بداية العلاج.'],
	},

	// 58) citalo 20mg 14 f.c.tab.
	{
		id: 'citalo-20-14-tabs-ad1',
		name: 'citalo 20mg 14 f.c.tab.',
		genericName: 'citalopram',
		concentration: '20mg',
		price: 81,
		matchKeywords: ['citalo 20 14', 'citalopram 20', 'ssri', 'سيتالو ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٤٠ مجم/يوم. الحد الأقصى: ٤٠ مجم/يوم (كبار السن/مشاكل كبد: حد أقصى ٢٠ مجم/يوم).'),
		warnings: ['قد يطيل QT خصوصاً بجرعات عالية.'],
	},

	// 59) citapronex 10mg 14 f.c. tab.
	{
		id: 'citapronex-10-14-tabs-ad1',
		name: 'citapronex 10mg 14 f.c. tab.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 70,
		matchKeywords: ['citapronex 10 14', 'escitalopram 10', 'ssri', 'سيتابرونكس', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 60) citapronex 20mg 14 f.c. tabs.
	{
		id: 'citapronex-20-14-tabs-ad1',
		name: 'citapronex 20mg 14 f.c. tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 106,
		matchKeywords: ['citapronex 20 14', 'escitalopram 20', 'ssri', 'سيتابرونكس ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً (بعد بدء ١٠ مجم). الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 61) citapronex 5mg 14 f.c. tab
	{
		id: 'citapronex-5-14-tabs-ad1',
		name: 'citapronex 5mg 14 f.c. tab',
		genericName: 'escitalopram',
		concentration: '5mg',
		price: 62,
		matchKeywords: ['citapronex 5 14', 'escitalopram 5', 'ssri', 'جرعة صغيرة', 'سيتابرونكس ٥', 'قلق', 'اكتئاب', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام جرعة منخفضة لبدء العلاج أو كبار السن.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥ مجم مرة يومياً كبداية عند الحساسية للآثار الجانبية، ثم ١٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 62) depram 20mg 20 f.c. tab
	{
		id: 'depram-20-20-tabs-ad1',
		name: 'depram 20mg 20 f.c. tab',
		genericName: 'citalopram',
		concentration: '20mg',
		price: 104,
		matchKeywords: ['depram 20 20', 'citalopram 20', 'ssri', 'ديبرام ٢٠', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'سيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً كبداية. يمكن الزيادة إلى ٤٠ مجم/يوم. الحد الأقصى: ٤٠ مجم/يوم (كبار السن: ٢٠ مجم/يوم).'),
		warnings: ['قد يطيل QT خصوصاً بجرعات عالية.'],
	},

	// 63) effegad 75 mg 30 e.r. caps.
	{
		id: 'effegad-75-30-er-caps-ad1',
		name: 'effegad 75 mg 30 e.r. caps.',
		genericName: 'venlafaxine',
		concentration: '75mg',
		price: 90,
		matchKeywords: ['effegad 75 30', 'venlafaxine er', 'venlafaxine xr', 'snri', 'ايفيجاد', 'فينلافاكسين', 'اكتئاب', 'قلق', '#antidepressants', '#snri'],
		usage: 'فينلافاكسين ممتد المفعول (SNRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'S.R. Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('XR/ER: بداية ٣٧٫٥–٧٥ مجم مرة يومياً، وزيادة تدريجية حتى ١٥٠–٢٢٥ مجم/يوم. الحد الأقصى الشائع: ٢٢٥ مجم/يوم.'),
		warnings: ['قد يرفع ضغط الدم.', 'أعراض انسحاب إذا توقف فجأة.'],
	},

	// 64) duloxifutal 60 mg 30 caps.
	{
		id: 'duloxifutal-60-30-caps-ad1',
		name: 'duloxifutal 60 mg 30 caps.',
		genericName: 'duloxetine',
		concentration: '60mg',
		price: 387,
		matchKeywords: ['duloxifutal 60', 'duloxetine 60', 'snri', 'دولوكسيفيوتال ٦٠', 'اكتئاب', 'ألم أعصاب', '#antidepressants', '#snri'],
		usage: 'دولوكسيتين (SNRI) للاكتئاب/آلام الأعصاب.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('الجرعة الشائعة: ٦٠ مجم مرة يومياً. الحد الأقصى: ١٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان.', 'قد يرفع ضغط الدم قليلاً.'],
	},

	// 65) escitapram 20 mg 10 f.c.tabs.
	{
		id: 'escitapram-20-10-tabs-ad1',
		name: 'escitapram 20 mg 10 f.c.tabs.',
		genericName: 'escitalopram',
		concentration: '20mg',
		price: 48,
		matchKeywords: ['escitapram 20 10', 'escitalopram 20', 'ssri', 'اسيتابرام', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق (عبوة صغيرة).',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٢٠ مجم مرة يومياً (بعد بدء ١٠ مجم). الحد الأقصى: ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 66) imipramine 25mg 50 tab.
	{
		id: 'imipramine-25-50-tabs-ad1',
		name: 'imipramine 25mg 50 tab.',
		genericName: 'imipramine',
		concentration: '25mg',
		price: 52.5,
		matchKeywords: ['imipramine 25 50', 'tofranil', 'tca', 'depression', 'enuresis', 'bedwetting', 'امبرامين', 'إيميبرامين', 'اكتئاب', 'تبول لا إرادي', '#antidepressants', '#tricyclic antidepressant'],
		usage: 'إيميبرامين (TCA) للاكتئاب، ويُستخدم أيضاً للتبول الليلي عند الأطفال (بروتوكولات خاصة).',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 216
				? 'للتبول الليلي (٦–١٢ سنة): ٢٥ مجم قبل النوم. (>١٢ سنة): ٥٠ مجم قبل النوم. لا تتجاوز ٧٥ مجم/يوم للأطفال.'
				: 'للاكتئاب: يبدأ ٢٥ مجم مساءً ثم زيادة تدريجية. جرعة شائعة ٧٥–١٥٠ مجم/يوم. الحد الأقصى: ٢٠٠ مجم/يوم.' ,
		warnings: ['يُحذر مع أمراض القلب واضطراب نظم.', 'خطر سمّية بجرعات زائدة.', 'جفاف فم/إمساك/زغللة.'],
	},

	// 67) inspago 25 mg 14 f.c.tabs
	{
		id: 'inspago-25-14-tabs-ad1',
		name: 'inspago 25 mg 14 f.c.tabs',
		genericName: 'agomelatine',
		concentration: '25mg',
		price: 74,
		matchKeywords: ['inspago 25 14', 'agomelatine', 'valdoxan', 'depression', 'sleep', 'انسـباجو', 'اجوميلاتين', 'اكتئاب', 'نوم', '#antidepressants'],
		usage: 'أجوميلاتين للاكتئاب (قد يساعد على تنظيم النوم).',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد (٢٥ مجم) قبل النوم. يمكن زيادة إلى ٥٠ مجم/يوم بعد أسبوعين إذا لم تتحسن الأعراض.'),
		warnings: ['ممنوع في أمراض كبد نشطة/إنزيمات مرتفعة.', 'قد يسبب دوخة/غثيان.', 'تداخلات دوائية مع مثبطات CYP1A2.'],
	},

	// 68) nodep 10mg 30 f.c. tab.
	{
		id: 'nodep-10-30-tabs-ad1',
		name: 'nodep 10mg 30 f.c. tab.',
		genericName: 'escitalopram',
		concentration: '10mg',
		price: 75,
		matchKeywords: ['nodep 10 30', 'escitalopram 10', 'ssri', 'نوديب', 'اكتئاب', 'قلق', '#antidepressants', '#ssri'],
		usage: 'إسيتالوبرام (SSRI) للاكتئاب/القلق.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Film-coated Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١٠ مجم مرة يومياً كبداية شائعة. يمكن الزيادة إلى ٢٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب غثيان/صداع.', 'قد يسبب اضطراب جنسي.'],
	},

	// 69) seroxat cr 25mg 30 f.c. tab
	{
		id: 'seroxat-cr-25-30-tabs-ad1',
		name: 'seroxat cr 25mg 30 f.c. tab',
		genericName: 'paroxetine',
		concentration: '25mg',
		price: 321,
		matchKeywords: ['seroxat cr 25 30', 'seroxat', 'paroxetine cr', 'ssri', 'panic', 'anxiety', 'depression', 'سيروكسات', 'باروكستين', 'قلق', 'هلع', '#antidepressants', '#ssri'],
		usage: 'باروكستين ممتد المفعول (الدواء الأصلي) للاكتئاب/القلق/الهلع.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('CR: بداية شائعة ١٢٫٥–٢٥ مجم مرة يومياً. يمكن الزيادة تدريجياً كل أسبوع. الحد الأقصى: ٦٢٫٥ مجم/يوم.'),
		warnings: ['أعراض انسحاب قوية إذا توقف فجأة.', 'قد يسبب نعاس/زيادة وزن.', 'يُحذر في الحمل.'],
	},

	// 70) seserine 50mg 30 tab.
	{
		id: 'seserine-50-30-tabs-ad1',
		name: 'seserine 50mg 30 tab.',
		genericName: 'sertraline',
		concentration: '50mg',
		price: 75,
		matchKeywords: ['seserine 50 30', 'sertraline 50', 'ssri', 'سيسيرين', 'سيرترالين', 'اكتئاب', 'قلق', 'وسواس', '#antidepressants', '#ssri'],
		usage: 'سيرترالين (SSRI) للاكتئاب/القلق/الوسواس.',
		timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
		category: Category.ANTIDEPRESSANTS,
		form: 'Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('بداية شائعة: ٢٥–٥٠ مجم يومياً. يمكن الزيادة أسبوعياً حتى ٢٠٠ مجم/يوم.'),
		warnings: [...SSRI_SNRI_CORE_WARNINGS, 'قد يسبب اضطراب معدة.', 'قد يسبب اضطراب جنسي.'],
	},
];

