import { Medication, Category } from '../../../types';

const TAGS = {
  healing: ['healing', '#healing', 'التئام', 'التئام الجروح', 'wound', 'wound care', 'جرح', 'حروق', 'burns', 'ندبات', 'scar'],
  topicalHealing: ['topical healing', '#topical healing', 'topical', 'موضعي'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
};

export const HEELING_MEDS: Medication[] = [
  // 1
  {
    id: 'markzone-cream-15',
    name: 'markzone cream 15 gm',
    genericName: 'Silicone & Onion extract & Panthenol',
    concentration: '15 gm',
    price: 52,
    matchKeywords: ['markzone', 'مارك زون', ...TAGS.healing],
    usage: 'كريم لعلاج آثار الجروح/الندبات (دعم التئام).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 2
  {
    id: 'diaper-rash-cream-adults-50',
    name: 'diaper rash cream (adults) 50 gm',
    genericName: 'Zinc oxide & Lanolin & Glycine soja oil',
    concentration: '50 gm',
    price: 50,
    matchKeywords: ['diaper rash adults', 'zinc oxide', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'كريم واقٍ/مساعد على التئام التسلخات (للبالغين).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 3
  {
    id: 'bravamax-cream-20',
    name: 'bravamax cream 20 gm',
    genericName: 'Bees wax & Aloe vera ext. & Beta sitosterol & Chlorhexidine & Hyaluronic acid',
    concentration: '20 gm',
    price: 60,
    matchKeywords: ['bravamax', 'برافاماكس', 'hyaluronic', ...TAGS.healing],
    usage: 'كريم مساعد لالتئام الجروح السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 4
  {
    id: 'mederma-advanced-scar-gel-20',
    name: 'mederma advanced scar gel 20 gm',
    genericName: 'Allium cepa & Panthenol',
    concentration: '20 gm',
    price: 575,
    matchKeywords: ['mederma', 'scar gel', 'ندبات', ...TAGS.healing],
    usage: 'جل لعلاج آثار الندبات.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 5
  {
    id: 'eurofresh-spray-50',
    name: 'eurofresh spray 50 ml',
    genericName: 'Oxygen & Eucalyptus oil & Tea tree oil',
    concentration: '50 ml',
    price: 55,
    matchKeywords: ['eurofresh', 'يورو فريش', 'oxygen', ...TAGS.healing],
    usage: 'سبراي موضعي للمساعدة في تنظيف/العناية بالجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 6
  {
    id: 'keravita-gel-30',
    name: 'keravita gel 30 gm',
    genericName: 'Silicone & Onion extract & Panthenol',
    concentration: '30 gm',
    price: 155,
    matchKeywords: ['keravita', 'كيرافيتا', ...TAGS.healing],
    usage: 'جل للندبات ودعم التحسن التجميلي.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 7
  {
    id: 'tegaderm-film-10x12',
    name: 'tegaderm film 10*12',
    genericName: 'Transparent film dressing',
    concentration: '10×12 cm',
    price: 40,
    matchKeywords: ['tegaderm film', 'ضمادة شفافة', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'ضمادة فيلم شفافة لحماية الجروح السطحية.',
    timing: 'تُغير حسب الحاجة.',
    category: Category.FIRST_AID,
    form: 'Film',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'تثبت على جلد نظيف وجاف وتُغير حسب الحاجة.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 8
  {
    id: 'tegaderm-transparent-film-6x7',
    name: 'tegaderm transparent film 6*7',
    genericName: 'Transparent film dressing',
    concentration: '6×7 cm',
    price: 18,
    matchKeywords: ['tegaderm 6x7', 'tegaderm transparent', ...TAGS.healing],
    usage: 'ضمادة فيلم شفافة.',
    timing: 'تُغير حسب الحاجة.',
    category: Category.FIRST_AID,
    form: 'Film',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'تثبت على جلد نظيف وجاف.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 9
  {
    id: 'tegaderm-transparent-film-10x25',
    name: 'tegaderm transparent film 10*25',
    genericName: 'Transparent film dressing',
    concentration: '10×25 cm',
    price: 40,
    matchKeywords: ['tegaderm 10x25', 'film', ...TAGS.healing],
    usage: 'ضمادة فيلم شفافة.',
    timing: 'تُغير حسب الحاجة.',
    category: Category.FIRST_AID,
    form: 'Film',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'تثبت على جلد نظيف وجاف.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 10
  {
    id: 'cuticare-cream-15',
    name: 'cuticare cream 15 gm',
    genericName: 'Bees wax & Aloe vera ext. & Beta sitosterol & Chlorhexidine & Hyaluronic acid',
    concentration: '15 gm',
    price: 48,
    matchKeywords: ['cuticare', 'كوتيكير', ...TAGS.healing],
    usage: 'كريم مساعد لالتئام الجروح السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 11
  {
    id: 'eurofresh-spray-75',
    name: 'eurofresh spray 75 ml',
    genericName: 'Oxygen & Eucalyptus oil & Tea tree oil',
    concentration: '75 ml',
    price: 60,
    matchKeywords: ['eurofresh 75', ...TAGS.healing],
    usage: 'سبراي موضعي للعناية بالجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 12
  {
    id: 'tegaderm-film-6x7',
    name: 'tegaderm film 6*7',
    genericName: 'Transparent film dressing',
    concentration: '6×7 cm',
    price: 18,
    matchKeywords: ['tegaderm film 6*7', ...TAGS.healing],
    usage: 'ضمادة فيلم شفافة.',
    timing: 'تُغير حسب الحاجة.',
    category: Category.FIRST_AID,
    form: 'Film',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'تثبت على جلد نظيف وجاف.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 13
  {
    id: 'chitosan-plus-spray-120',
    name: 'chitosan plus spray 120 ml',
    genericName: 'Chitosan & Aloe vera',
    concentration: '120 ml',
    price: 85,
    matchKeywords: ['chitosan plus', 'كيتوسان بلس', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'سبراي مساعد على التئام الجروح السطحية.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يرش مرة–مرتين يومياً على المنطقة.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 14
  {
    id: 'tegaderm-film-10x25-dup',
    name: 'tegaderm film 10*25',
    genericName: 'Transparent film dressing',
    concentration: '10×25 cm',
    price: 40,
    matchKeywords: ['tegaderm film 10*25', ...TAGS.healing],
    usage: 'ضمادة فيلم شفافة.',
    timing: 'تُغير حسب الحاجة.',
    category: Category.FIRST_AID,
    form: 'Film',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'تثبت على جلد نظيف وجاف.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 15
  {
    id: 'fresh-wound-spray',
    name: 'fresh wound spray',
    genericName: 'oxygen & zinc & cucumber extract & green tea extract',
    concentration: 'Spray',
    price: 52,
    matchKeywords: ['fresh wound', 'جرح', 'oxygen', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'سبراي للعناية بالجروح السطحية.',
    timing: 'حسب الحاجة 1-2 مرة يومياً.',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يرش على المنطقة حسب الحاجة.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 16
  {
    id: 'chitosan-plus-spray-50',
    name: 'chitosan plus spray 50ml',
    genericName: 'Chitosan & Aloe vera',
    concentration: '50 ml',
    price: 65,
    matchKeywords: ['chitosan plus 50', ...TAGS.healing],
    usage: 'سبراي مساعد على التئام الجروح السطحية.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يرش مرة–مرتين يومياً.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 17
  {
    id: 'bepanthen-plus-cream-30',
    name: 'bepanthen plus cream 30 gm',
    genericName: 'Dexpanthenol & Chlorhexidine',
    concentration: '30 gm',
    price: 60,
    matchKeywords: ['bepanthen plus 30', 'بيبانثين بلس', ...TAGS.healing],
    usage: 'كريم مطهر/مساعد على التئام الجروح السطحية.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 18
  {
    id: 'bepanthen-plus-cream-100',
    name: 'bepanthen plus cream 100 gm',
    genericName: 'Dexpanthenol & Chlorhexidine',
    concentration: '100 gm',
    price: 175,
    matchKeywords: ['bepanthen plus 100', ...TAGS.healing],
    usage: 'كريم مطهر/مساعد على التئام الجروح السطحية.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 19
  {
    id: 'contractubex-gel-20',
    name: 'contractubex gel 20 gm',
    genericName: 'Heparin & Allantoin & Onion extract',
    concentration: '20 gm',
    price: 150,
    matchKeywords: ['contractubex 20', 'كونتراكتيوبكس', ...TAGS.healing],
    usage: 'جل للندبات وتحسين المظهر.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 20
  {
    id: 'maalu-cream-120',
    name: 'maalu cream 120 gm',
    genericName: 'Collegen peptide & Hyaluronic acid & Aloe vera ext. & Lanolin',
    concentration: '120 gm',
    price: 130,
    matchKeywords: ['maalu', 'مالو', 'hyaluronic', ...TAGS.healing],
    usage: 'كريم مرطب ومساعد على تجدد الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 21
  {
    id: 'bepanthen-ointment-30',
    name: 'bepanthen ointment 30 gm',
    genericName: 'Dexpanthenol',
    concentration: '30 gm',
    price: 50,
    matchKeywords: ['bepanthen ointment 30', 'بيبانثين مرهم', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'مرهم مساعد على التئام الجلد وتهدئته.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Ointment',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 22
  {
    id: 'bepanthen-ointment-100',
    name: 'bepanthen ointment 100 gm',
    genericName: 'Dexpanthenol',
    concentration: '100 gm',
    price: 120,
    matchKeywords: ['bepanthen ointment 100', ...TAGS.healing],
    usage: 'مرهم مساعد على التئام الجلد وتهدئته.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Ointment',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 23
  {
    id: 'contractubex-gel-50',
    name: 'contractubex gel 50 gm',
    genericName: 'Heparin & Allantoin & Onion extract',
    concentration: '50 gm',
    price: 250,
    matchKeywords: ['contractubex 50', ...TAGS.healing],
    usage: 'جل للندبات وتحسين المظهر.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 24
  {
    id: 'levoragel-spray-75',
    name: 'levoragel spray 75 ml',
    genericName: 'Beta glucan & Aloe vera',
    concentration: '75 ml',
    price: 75,
    matchKeywords: ['levoragel spray', 'ليفوراجيل', ...TAGS.healing],
    usage: 'سبراي مساعد لتهدئة الجلد ودعم الالتئام.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 25
  {
    id: 'd-panthenol-ointment-30',
    name: 'd-panthenol ointment 30 gm',
    genericName: 'Dexpanthenol',
    concentration: '30 gm',
    price: 25,
    matchKeywords: ['d-panthenol ointment 30', 'دي-بانثينول مرهم', ...TAGS.healing],
    usage: 'مرهم مساعد على التئام الجلد وتهدئته.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Ointment',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 26
  {
    id: 'silverex-cream-40',
    name: 'silverex cream 40 gm',
    genericName: 'Silver sulfadiazine',
    concentration: '40 gm',
    price: 35,
    matchKeywords: ['silverex', 'سيلفركس', 'silver sulfadiazine', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'كريم للحروق والجروح السطحية (مضاد ميكروبي).',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 27
  {
    id: 'flamazine-cream-50',
    name: 'flamazine cream 50 gm',
    genericName: 'Silver sulfadiazine',
    concentration: '50 gm',
    price: 70,
    matchKeywords: ['flamazine', 'فلامازين', ...TAGS.healing],
    usage: 'كريم للحروق والجروح السطحية (مضاد ميكروبي).',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 28
  {
    id: 'chitosan-plus-gel-50',
    name: 'chitosan plus gel 50 gm',
    genericName: 'Chitosan & Aloe vera',
    concentration: '50 gm',
    price: 70,
    matchKeywords: ['chitosan plus gel', 'كيتوسان جل', ...TAGS.healing],
    usage: 'جل مساعد على التئام الجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 29
  {
    id: 'fucidin-cream-15',
    name: 'fucidin cream 15 gm',
    genericName: 'Fusidic acid',
    concentration: '15 gm',
    price: 45,
    matchKeywords: ['fucidin', 'فيوسيدين', 'fusidic', ...TAGS.healing],
    usage: 'مضاد حيوي موضعي لعدوى الجلد السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 30
  {
    id: 'fucidin-cream-30',
    name: 'fucidin cream 30 gm',
    genericName: 'Fusidic acid',
    concentration: '30 gm',
    price: 62,
    matchKeywords: ['fucidin 30', ...TAGS.healing],
    usage: 'مضاد حيوي موضعي لعدوى الجلد السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 31
  {
    id: 'fucidin-ointment-15',
    name: 'fucidin ointment 15 gm',
    genericName: 'Fusidic acid',
    concentration: '15 gm',
    price: 47,
    matchKeywords: ['fucidin ointment 15', 'فيوسيدين مرهم', ...TAGS.healing],
    usage: 'مضاد حيوي موضعي لعدوى الجلد السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Ointment',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 32
  {
    id: 'fucidin-ointment-30',
    name: 'fucidin ointment 30 gm',
    genericName: 'Fusidic acid',
    concentration: '30 gm',
    price: 64,
    matchKeywords: ['fucidin ointment 30', ...TAGS.healing],
    usage: 'مضاد حيوي موضعي لعدوى الجلد السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Ointment',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 33
  {
    id: 'mupirocin-ointment-15',
    name: 'mupirocin ointment 15gm',
    genericName: 'Mupirocin',
    concentration: '15 gm',
    price: 22,
    matchKeywords: ['mupirocin', 'موبيروسين', ...TAGS.healing],
    usage: 'مضاد حيوي موضعي لعدوى الجلد السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Ointment',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 34
  {
    id: 'lacteol-forte-gel-30',
    name: 'lacteol forte gel 30gm',
    genericName: 'Hyaluronic acid & Centella asiatica & Aloe vera ext & Copper sulfate & Zinc sulfate',
    concentration: '30 gm',
    price: 70,
    matchKeywords: ['lacteol forte', 'لاكتول فورت', 'centella', ...TAGS.healing],
    usage: 'جل مساعد لتهدئة الجلد ودعم الالتئام.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 35
  {
    id: 'mupirocin-cream-15',
    name: 'mupirocin cream 15gm',
    genericName: 'Mupirocin',
    concentration: '15 gm',
    price: 23,
    matchKeywords: ['mupirocin cream', ...TAGS.healing],
    usage: 'مضاد حيوي موضعي لعدوى الجلد السطحية.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 36
  {
    id: 'bepanthen-plus-spray-100',
    name: 'bepanthen plus spray 100ml',
    genericName: 'Dexpanthenol & Chlorhexidine',
    concentration: '100 ml',
    price: 142,
    matchKeywords: ['bepanthen plus spray', 'بيبانثين بلس سبراي', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'سبراي مطهر/مساعد على التئام الجروح السطحية.',
    timing: '١–٢ مرة يومياً',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 37
  {
    id: 'fucicort-cream-15',
    name: 'fucicort cream 15gm',
    genericName: 'Fusidic acid & Betamethasone',
    concentration: '15 gm',
    price: 50,
    matchKeywords: ['fucicort', 'فيوسيكورت', ...TAGS.healing],
    usage: 'مضاد حيوي + كورتيزون موضعي (التهاب مع عدوى).',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 38
  {
    id: 'mupirocin-plus-cream-15',
    name: 'mupirocin plus cream 15 gm',
    genericName: 'Mupirocin & Betamethasone',
    concentration: '15 gm',
    price: 18,
    matchKeywords: ['mupirocin plus', ...TAGS.healing],
    usage: 'مضاد حيوي + كورتيزون موضعي (التهاب مع عدوى).',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 39
  {
    id: 'piomegal-scar-cream-30',
    name: 'piomegal scar cream 30 gm',
    genericName: 'Silicone',
    concentration: '30 gm',
    price: 225,
    matchKeywords: ['piomegal', 'بيوميجال', 'scar', ...TAGS.healing],
    usage: 'كريم سيليكون للندبات.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 40
  {
    id: 'eurofresh-spray-150',
    name: 'eurofresh spray 150ml',
    genericName: 'Oxygen & Eucalyptus oil & Tea tree oil',
    concentration: '150 ml',
    price: 95,
    matchKeywords: ['eurofresh 150', ...TAGS.healing],
    usage: 'سبراي موضعي للعناية بالجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 41
  {
    id: 'chitosan-plus-cream-30',
    name: 'chitosan plus cream 30gm',
    genericName: 'Chitosan & Aloe vera',
    concentration: '30 gm',
    price: 60,
    matchKeywords: ['chitosan plus cream', ...TAGS.healing],
    usage: 'كريم مساعد على التئام الجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.FIRST_AID,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 42
  {
    id: 'elastic-gel-collagen-30',
    name: 'elastic gel collagen 30 gm',
    genericName: 'Marine collagen & Hyaluronic acid & Aloevera',
    concentration: '30 gm',
    price: 65,
    matchKeywords: ['elastic gel collagen', 'collagen', 'hyaluronic', ...TAGS.healing],
    usage: 'جل مرطب ومساعد على تجدد الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 43
  {
    id: 'manzanilla-cream-50',
    name: 'manzanilla cream 50 gm',
    genericName: 'Chamomile extract & Propolis & Vitamin E',
    concentration: '50 gm',
    price: 37,
    matchKeywords: ['manzanilla', 'مانزانيلا', 'chamomile', ...TAGS.healing],
    usage: 'كريم مهدئ ومساعد على ترميم الجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 44
  {
    id: 'folicap-cream-50',
    name: 'folicap cream 50 gm',
    genericName: 'Panthenol & Shea butter & Avocado oil',
    concentration: '50 gm',
    price: 45,
    matchKeywords: ['folicap cream', 'فوليكاب', 'panthenol', ...TAGS.healing],
    usage: 'كريم مرطب ومساعد لترميم الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 45
  {
    id: 'wound-care-spray',
    name: 'wound care spray',
    genericName: 'Oxygen & Echinacea & Tea tree oil & Hyaluronic acid',
    concentration: 'Spray',
    price: 48,
    matchKeywords: ['wound care spray', 'ووند كير', 'echinacea', ...TAGS.healing, ...TAGS.topicalHealing],
    usage: 'سبراي للعناية بالجروح السطحية ودعم الالتئام.',
    timing: 'حسب الحاجة 1-2 مرة يومياً.',
    category: Category.FIRST_AID,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يرش حسب الحاجة.',
    warnings: ['للاستخدام الخارجي فقط.']
  }
];

