import { Medication, Category } from '../../../types';

const TAGS = {
  moisturizer: ['moisturizer', '#moisturizer', 'moisturising', 'moisturizing', 'ترطيب', 'مرطب', 'emollient', 'ملطف', 'جفاف', 'dry skin', 'جلد جاف', 'بشرة جافة'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
  soothing: ['soothing topical', '#soothing topical', 'مهدئ', 'تهدئة'],
  healing: ['healing', '#healing', 'التئام', 'ترميم'],
  cleaning: ['cleaning', '#cleaning', 'تنظيف'],
  emollient: ['emollient', '#emollient', 'مطري'],
};

export const MOISTURIZING_2_MEDS: Medication[] = [
  // 62
  {
    id: 'macsen-cream-75',
    name: 'macsen cream 75 gm',
    genericName: 'Paraffin oil & Dimethicone & Panthenol & Sesame oil & Beeswax',
    concentration: '75 gm',
    price: 110,
    matchKeywords: ['macsen', 'ماكسين', 'paraffin', 'dimethicone', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وحماية للجلد الجاف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 63
  {
    id: 'novex-carbamide-cream-30',
    name: 'novex carbamide cream 30 gm',
    genericName: 'Carbamide',
    concentration: '30 gm',
    price: 35,
    matchKeywords: ['novex carbamide', 'نوڤكس كارباميد', 'carbamide', 'urea', ...TAGS.moisturizer],
    usage: 'كريم كارباميد للترطيب وعلاج الجفاف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 64
  {
    id: 'orient-n-nipple-balm-cream-50',
    name: 'orient-n nipple balm cream 50 ml',
    genericName:
      'Tocopherol & Panthenol & Beeswax & Almond oil & Paraffin oil & Vaseline & Olive oil',
    concentration: '50 ml',
    price: 70,
    matchKeywords: ['orient-n', 'اورينت', 'nipple balm', 'panthenol', ...TAGS.moisturizer],
    usage: 'بلسم/كريم لترطيب وحماية الجلد (خاصة الحلمة/الجلد الجاف).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 65
  {
    id: 'primo-plus-topical-lotion-120',
    name: 'primo plus topical lotion 120 ml',
    genericName:
      'Dimethicone & Zinc oxide & Aluminum ammonium sulfate & Camphor & Menthol & Thyme extract & Glycerin',
    concentration: '120 ml',
    price: 70,
    matchKeywords: ['primo plus', 'بريمو بلس', 'menthol', 'camphor', ...TAGS.moisturizer],
    usage: 'لوشن موضعي ملطف/مرطب للجسم.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 66
  {
    id: 'qv-cream-250',
    name: 'qv cream 250 gm',
    genericName: 'Aqua & Paraffinum liquidum & Glycerin & Petrolatum & Cetearyl alcohol',
    concentration: '250 gm',
    price: 421,
    matchKeywords: ['qv 250', 'كيو ڤي', 'petrolatum', ...TAGS.moisturizer],
    usage: 'كريم ترطيب كثيف ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 67
  {
    id: 'rostevo-deep-moisture-shea-cream-50',
    name: 'rostevo deep moisture shea 50 gm cream',
    genericName: 'Shea butter',
    concentration: '50 gm',
    price: 110,
    matchKeywords: ['rostevo', 'روستيفو', 'shea', 'شيا', ...TAGS.moisturizer],
    usage: 'كريم شيا مرطب ومطري.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 68
  {
    id: 'sfira-moisturizing-cream-60',
    name: 'sfira moisturizing cream 60 gm',
    genericName:
      'Aloe vera & Jojoba oil & Panthenol & Shea butter & Olive oil & Collagen & Glycerin & Caffeine & Vitamin C & Vitamin B5 & Vitamin E',
    concentration: '60 gm',
    price: 69,
    matchKeywords: ['sfira', 'سفيرة', 'caffeine', 'jojoba', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتغذية للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 69
  {
    id: 'sonakto-cream-50',
    name: 'sonakto cream 50 gm',
    genericName: 'Chamomile extract & Panthenol & Soya protein & Olive oil & Vitamin E',
    concentration: '50 gm',
    price: 88.5,
    matchKeywords: ['sonakto', 'سوناكتو', 'chamomile', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 70
  {
    id: 'hyalkonex-serum',
    name: 'hyalkonex serum',
    genericName:
      'Hyaluronic acid & Hydrolyzed collagen & Kojic acid & Vitamin C & Retinol & Elastin & Rumex extract & Mulberry root extract & Melaslow complex',
    concentration: 'Serum',
    price: 220,
    matchKeywords: ['hyalkonex', 'هيالكونكس', 'hyaluronic', 'retinol', ...TAGS.moisturizer],
    usage: 'سيروم عناية وترطيب (قد يحتوي ريتينول).',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Solution',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['قد يسبب تهيجاً.', 'تجنب أثناء الحمل.']
  },
  // 71
  {
    id: 'infinity-soothing-moisturizing-cream-120',
    name: 'infinity soothing & moisturizing cream 120 ml',
    genericName:
      'Shea butter & Onion extract & Aloe vera ext. & Dow corning & Oatmeal & Honey & Pro vitamin B5 & Coconut oil & Chamomile extract & Wheat germ oil & Green tea extract',
    concentration: '120 ml',
    price: 150,
    matchKeywords: ['infinity', 'انفينتي', 'soothing', 'oatmeal', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب وتهدئة للجسم.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 72
  {
    id: 'infinity-soothing-moisturizing-gel-120',
    name: 'infinity soothing & moisturizing gel 120 ml',
    genericName:
      'Hydrogenated castor oil & Honey & Panthenol & Chamomile ext & Green tea ext & Aloe vera ext & Calendula ext',
    concentration: '120 ml',
    price: 165,
    matchKeywords: ['infinity gel', 'انفينتي جل', 'panthenol', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'جل ترطيب وتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 73
  {
    id: 'melanocool-cream-40',
    name: 'melanocool cream 40 gm',
    genericName: 'Olive oil & Coconut oil & Almond oil & Vitamin E & Aloe vera extract & Urea & Honey',
    concentration: '40 gm',
    price: 51,
    matchKeywords: ['melanocool', 'ميلانوكول', 'urea', 'honey', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب وتغذية.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 74
  {
    id: 'spectra-panthenol-extra-cream-30',
    name: 'spectra panthenol extra cream 30 gm',
    genericName: 'Panthenol & Urea & Shea butter',
    concentration: '30 gm',
    price: 35,
    matchKeywords: ['spectra panthenol', 'سبكترا بانثينول', 'urea', 'shea', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب مكثف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 75
  {
    id: 'vitabalm-skin-moisturiser',
    name: 'vitabalm skin moisturiser',
    genericName:
      'Ceramide & Ferulic acid & Vitamin A & Vitamin E & Vitamin C & Paraffin & Zinc oxide & Glycerin & Almond oil & Cod liver oil & Aloe vera extract & Honey',
    concentration: 'Moisturiser',
    price: 178,
    matchKeywords: ['vitabalm', 'فيتابالم', 'ceramide', 'ferulic', ...TAGS.moisturizer],
    usage: 'مرطب للبشرة ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 76
  {
    id: 'macro-panthenol-5-lotion-100',
    name: 'macro panthenol 5% lotion 100 ml',
    genericName: 'Panthenol & Glycerin & Paraffin oil',
    concentration: '5% (100 ml)',
    price: 90,
    matchKeywords: ['macro panthenol 5%', 'ماكرو بانثينول', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'لوشن بانثينول للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 77
  {
    id: 'hyalokonex-skin-serum-40',
    name: 'hyalokonex skin serum 40 ml',
    genericName:
      'Hyaluronic acid & Hydrolyzed collagen & Kojic acid & Vitamin C & Retinol & Elastin & Rumex extract & Mulberry root extract & Melaslow complex',
    concentration: '40 ml',
    price: 380,
    matchKeywords: ['hyalokonex 40', 'هيالكونكس 40', 'hyaluronic', 'retinol', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'سيروم عناية وترطيب (قد يحتوي ريتينول).',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Solution',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['قد يسبب تهيجاً.', 'تجنب أثناء الحمل.']
  },
  // 78
  {
    id: 'acro-cream-75',
    name: 'acro cream 75 gm',
    genericName: 'Vitamin A & Vitamin E',
    concentration: '75 gm',
    price: 75,
    matchKeywords: ['acro', 'اكرو', 'vitamin a', 'vitamin e', ...TAGS.moisturizer],
    usage: 'كريم ترطيب/عناية بفيتامينات.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 79
  {
    id: 'sinzahoc-nasal-spray-70',
    name: 'sinzahoc 70 ml nasal spray soothing & moisturising',
    genericName: 'Sea water & Hyaluronic acid & Eucalyptus & Panthenol',
    concentration: '70 ml',
    price: 95,
    matchKeywords: ['sinzahoc 70', 'سينزا هوك 70', 'nasal spray', ...TAGS.moisturizer, ...TAGS.soothing],
    usage: 'بخاخ أنفي لترطيب وتهدئة الأنف.',
    timing: '١–٢ مرة يومياً',
    category: Category.NASAL_CARE,
    form: 'Nasal Spray',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['إذا استمرت الأعراض أعد التقييم.']
  },
  // 80
  {
    id: 'force-carbamide-cream-30',
    name: 'force carbamide 30 gm cream',
    genericName: 'Carbamide',
    concentration: '30 gm',
    price: 54,
    matchKeywords: ['force carbamide', 'فورس كارباميد', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم كارباميد للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 81
  {
    id: 'uremel-cream-100',
    name: 'uremel 100ml cream',
    genericName: 'Urea',
    concentration: '100 ml',
    price: 240,
    matchKeywords: ['uremel', 'يوريميل', 'urea', ...TAGS.moisturizer],
    usage: 'كريم يوريا للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 82
  {
    id: 'helo-cream-50',
    name: 'helo cream 50 gm',
    genericName: 'Bee propolis & Olive oil & Chamomile extract & Honey',
    concentration: '50 gm',
    price: 63,
    matchKeywords: ['helo', 'هيلو', 'propolis', 'honey', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتغذية.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 83
  {
    id: 'well-femme-nipple-care-cream-50',
    name: 'well femme nipple care cream 50 gm',
    genericName: 'Allantoin & Tea tree oil & Aloe vera extract & Menthol & Chamomile flower extract',
    concentration: '50 gm',
    price: 120,
    matchKeywords: ['well femme', 'ويل فيم', 'nipple care', ...TAGS.moisturizer],
    usage: 'كريم عناية وترطيب للجلد (خاصة الحلمة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 84
  {
    id: 'purelan-cream-60',
    name: 'purelan cream 60 gm',
    genericName: 'Lanolin & Wheat germ oil & Panthenol & Allantoin & Vitamin C & Vitamin E',
    concentration: '60 gm',
    price: 55,
    matchKeywords: ['purelan 60', 'بوريلان 60', 'lanolin', ...TAGS.moisturizer],
    usage: 'كريم لانولين لترطيب وحماية الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 85
  {
    id: 'melanthenol-lotion-250',
    name: 'melanthenol 250ml lotion',
    genericName: 'D-panthenol & Glycerin & Sweet almond oil & Vitamin E',
    concentration: '250 ml',
    price: 235,
    matchKeywords: ['melanthenol lotion', 'ميلانثينول لوشن', ...TAGS.moisturizer],
    usage: 'لوشن مرطب للجسم.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 86
  {
    id: 'sate-cream-50',
    name: 'sate cream 50 gm',
    genericName:
      'Bee propolis & Salicylic acid & Casein & Vitamin E & Vitamin A & Calendula & Panthenol & Tea tree oil & Chamomile & Aloe vera',
    concentration: '50 gm',
    price: 70,
    matchKeywords: ['sate', 'ساتي', 'salicylic acid', 'tea tree', ...TAGS.moisturizer],
    usage: 'كريم ترطيب/عناية (قد يحتوي ساليسيليك).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 87
  {
    id: 'revano-soft-cream-50',
    name: 'revano soft 50 gm cream',
    genericName: 'Panthenol & Sun flower oil & Aloe vera extract & Avocado oil & Shea butter',
    concentration: '50 gm',
    price: 55,
    matchKeywords: ['revano', 'ريفانو', ...TAGS.moisturizer, ...TAGS.emollient],
    usage: 'كريم مرطب ومطري.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 88
  {
    id: 'flexiseo-skin-cream',
    name: 'flexiseo skin cream',
    genericName: 'Collagen & Shea butter & Vitamin A & Vitamin E',
    concentration: 'Cream',
    price: 45,
    matchKeywords: ['flexiseo', 'فليكسي سيو', 'collagen', 'shea', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وعناية.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 89
  {
    id: 'bellyroc-cream-50',
    name: 'bellyroc cream 50 gm',
    genericName:
      'Zinc oxide & Chamomile extract & Olive oil & Panthenol & Jojoba oil & Aloe vera & Wheat germ oil & Avocado',
    concentration: '50 gm',
    price: 49,
    matchKeywords: ['bellyroc', 'بيليروك', 'zinc oxide', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 90
  {
    id: 'nilpig-cream-60',
    name: 'nilpig cream 60 gm',
    genericName:
      'Pro-vitamin B5 & Olive oil & Cyclopentasiloxane & Allantoin & L-carnitine & Glycerin & Wheat germ oil & Collagen & Zinc oxide & Vitamin E',
    concentration: '60 gm',
    price: 65,
    matchKeywords: ['nilpig', 'نيلبيج', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وعناية.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 91
  {
    id: 'nobur-cream-50',
    name: 'nobur cream 50 gm',
    genericName:
      'Chlorhexidine & Myrrh & Yarrow extract & Centella asiatica & Hypericum perforatum extract & Plantain extract',
    concentration: '50 gm',
    price: 90,
    matchKeywords: ['nobur', 'نوبور', 'centella', 'chlorhexidine', ...TAGS.moisturizer],
    usage: 'كريم عناية وترطيب (قد يحتوي مطهر خفيف).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 92
  {
    id: 'panthozin-cream-30',
    name: 'panthozin cream 30 gm',
    genericName:
      'Panthenol & Olive oil & Wheat germ oil & Seasame oil & Chamomile extract & Zinc oxide & Glycerin & Cetrimide & Dimethicone',
    concentration: '30 gm',
    price: 55,
    matchKeywords: ['panthozin 30', 'بانثوزين 30', 'zinc oxide', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وحماية (حاجز).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 93
  {
    id: 'panthozin-topical-lotion-60',
    name: 'panthozin topical loton 60 ml',
    genericName:
      'Panthenol & Olive oil & Wheat germ oil & Seasame oil & Chamomile extract & Zinc oxide & Glycerin & Cetrimide & Dimethicone',
    concentration: '60 ml',
    price: 75,
    matchKeywords: ['panthozin lotion', 'بانثوزين لوشن', ...TAGS.moisturizer],
    usage: 'لوشن ترطيب وحماية.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 94
  {
    id: 'purelan-cream-30',
    name: 'purelan cream 30 gm',
    genericName: 'Lanolin & Wheat germ oil & Panthenol & Allantoin & Vitamin C & Vitamin E',
    concentration: '30 gm',
    price: 35,
    matchKeywords: ['purelan 30', 'بوريلان 30', 'lanolin', ...TAGS.moisturizer],
    usage: 'كريم لانولين للترطيب (عبوة صغيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 95
  {
    id: 'regetal-cream-20',
    name: 'regetal cream 20 gm',
    genericName:
      'Panthenol & Aloe vera & Calendula oil & Propolis & Lavender oil & Vitamin E & Vitamin A',
    concentration: '20 gm',
    price: 48,
    matchKeywords: ['regetal 20', 'ريجيتال 20', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وترميم.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 96
  {
    id: 'seta-cream-50',
    name: 'seta cream 50 gm',
    genericName: 'Urea & Lactic acid & Salicylic acid & Sorbitol',
    concentration: '50 gm',
    price: 24.75,
    matchKeywords: ['seta', 'سيتا', 'urea', 'lactic acid', 'salicylic acid', ...TAGS.moisturizer],
    usage: 'كريم للجفاف/الخشونة (يوريا + أحماض).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 97
  {
    id: 'rota-carbamide-cream-30',
    name: 'rota carbamide cream 30 gm',
    genericName: 'Carbamide',
    concentration: '30 gm',
    price: 35,
    matchKeywords: ['rota carbamide', 'روتا كارباميد', ...TAGS.moisturizer],
    usage: 'كريم كارباميد للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 98
  {
    id: 'regetal-cream-30',
    name: 'regetal cream 30 gm',
    genericName:
      'Panthenol & Aloe vera & Calendula oil & Propolis & Lavender oil & Vitamin E & Vitamin A',
    concentration: '30 gm',
    price: 120,
    matchKeywords: ['regetal 30', 'ريجيتال 30', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب وترميم (عبوة أكبر).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 99
  {
    id: 'nanobee-nasal-spray-30',
    name: 'nanobee 30 ml spray',
    genericName: 'Sea water & Hyaluronic acid & Dexpanthenol & Menthol & Eucalyptus oil',
    concentration: '30 ml',
    price: 85,
    matchKeywords: ['nanobee', 'نانوبي', 'nasal spray', 'sea water', ...TAGS.moisturizer, ...TAGS.cleaning],
    usage: 'بخاخ/محلول أنفي للترطيب والتنظيف.',
    timing: '١–٢ مرة يومياً',
    category: Category.NASAL_CARE,
    form: 'Nasal Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['إذا سبب تهيجاً أوقفه وأعد التقييم.']
  }
];

