import { Medication, Category } from '../../../types';

const TAGS = {
  moisturizer: ['moisturizer', '#moisturizer', 'moisturising', 'moisturizing', 'ترطيب', 'مرطب', 'emollient', 'ملطف', 'جفاف', 'dry skin', 'جلد جاف', 'بشرة جافة'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
  soothing: ['soothing topical', '#soothing topical', 'مهدئ', 'تهدئة'],
  healing: ['healing', '#healing', 'التئام', 'ترميم'],
};

export const MOISTURIZING_MEDS: Medication[] = [
  // 1
  {
    id: 'hepta-panthenol-beta-cream-50',
    name: 'hepta panthenol beta cream 50 gm',
    genericName: 'Panthenol & Tocopheryl acetate',
    concentration: '50 gm',
    price: 140,
    matchKeywords: ['hepta', 'هيبتا', 'panthenol', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم بانثينول لترطيب وتهدئة الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 2
  {
    id: 'hepta-panthenol-max-cream-50',
    name: 'hepta panthenol max cream 50 gm',
    genericName: 'Panthenol & Hyaluronic acid & Ceramides & Hydrolyzed collagen & Biotin & Oat extract & Vitamins C & Vitamins E',
    concentration: '50 gm',
    price: 99,
    matchKeywords: ['hepta max', 'هيبتا ماكس', 'ceramides', 'hyaluronic', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب مكثف ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 3
  {
    id: 'zinc-olive-baby-cream-75',
    name: 'zinc olive baby cream 75 gm',
    genericName: 'Zinc oxide',
    concentration: '75 gm',
    price: 80,
    matchKeywords: ['zinc olive', 'زينك اوليف', 'baby', 'zinc oxide', ...TAGS.moisturizer],
    usage: 'كريم حماية وترطيب (خاصة لمنطقة الحفاض).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 60,
    minWeight: 3,
    maxWeight: 25,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 4
  {
    id: 'panthenol-2-cream-20',
    name: 'panthenol 2% topical cream 20 gm',
    genericName: 'D-panthenol',
    concentration: '2% (20 gm)',
    price: 38,
    matchKeywords: ['panthenol 2%', 'بانثينول 2', ...TAGS.moisturizer],
    usage: 'كريم بانثينول لترطيب وتهدئة الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 5
  {
    id: 'hepta-panthenol-cream-50',
    name: 'hepta panthenol cream 50 gm',
    genericName: 'Panthenol & Tocopheryl acetate',
    concentration: '50 gm',
    price: 69,
    matchKeywords: ['hepta panthenol', 'هيبتا بانثينول', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم بانثينول لترطيب وتهدئة الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 6
  {
    id: 'hepta-panthenol-rich-body-lotion-100',
    name: 'hepta panthenol rich body lotion 100 ml',
    genericName: 'Panthenol',
    concentration: '100 ml',
    price: 130,
    matchKeywords: ['hepta rich', 'هيبتا ريتش', 'body lotion', 'panthenol', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'لوشن مرطب للجسم.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 7
  {
    id: 'hipanthen-plus-cream-30',
    name: 'hipanthen plus cream 30 gm',
    genericName: 'Panthenol & Zinc oxide & Glycerin & Cetyl alcohol & Natural oils',
    concentration: '30 gm',
    price: 35,
    matchKeywords: ['hipanthen plus 30', 'هيبانثين بلس 30', 'zinc oxide', ...TAGS.moisturizer],
    usage: 'كريم مرطب/حاجز للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 8
  {
    id: 'hipanthen-plus-cream-60',
    name: 'hipanthen plus cream 60 gm',
    genericName: 'Panthenol & Zinc oxide & Glycerin & Cetyl alcohol & Natural oils',
    concentration: '60 gm',
    price: 60,
    matchKeywords: ['hipanthen plus 60', 'هيبانثين بلس 60', 'zinc oxide', ...TAGS.moisturizer],
    usage: 'كريم مرطب/حاجز للجلد (عبوة أكبر).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 9
  {
    id: 'panthenol-cream-20',
    name: 'panthenol cream 20 gm',
    genericName: 'D-panthenol',
    concentration: '20 gm',
    price: 5.25,
    matchKeywords: ['panthenol cream 20', 'بانثينول كريم 20', 'd-panthenol', ...TAGS.moisturizer],
    usage: 'كريم بانثينول للترطيب والتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 10
  {
    id: 'beegu-nose-soothing-moisturizing-spray',
    name: 'beegu nose brand soothing & moisturizing spray',
    genericName: 'Sea water & Eucalyptus & Glycerin & Hyaluronic acid',
    concentration: 'Nasal spray',
    price: 95,
    matchKeywords: ['beegu', 'بيجو', 'nose spray', 'sea water', 'hyaluronic', ...TAGS.moisturizer, ...TAGS.soothing],
    usage: 'بخاخ أنفي لترطيب وتهدئة الأنف.',
    timing: '١–٢ مرة يومياً',
    category: Category.NASAL_CARE,
    form: 'Nasal Spray',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['إذا استمر الاحتقان/النزيف: أعد التقييم.']
  },
  // 11
  {
    id: 'urecare-10-cream-30',
    name: 'urecare 10% cream 30 gm',
    genericName: 'Urea',
    concentration: '10% (30 gm)',
    price: 23,
    matchKeywords: ['urecare', 'يوركير', 'urea 10', ...TAGS.moisturizer],
    usage: 'كريم يوريا للترطيب (للجفاف/التشققات البسيطة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['قد يسبب لسعاً على الجلد المتشقق.']
  },
  // 12
  {
    id: 'raku-ten-emollient-cream-50',
    name: 'raku-ten emollient cream 50 gm',
    genericName: 'Honey & Zinc oxide & Chamomile & Cyclopentasiloxane & Aloe vera & Propolis & Shea butter',
    concentration: '50 gm',
    price: 85,
    matchKeywords: ['raku-ten', 'راكو-تن', 'emollient', ...TAGS.moisturizer],
    usage: 'كريم مطري/مرطب للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 13
  {
    id: 'hepta-carbamide-cream-50',
    name: 'hepta carbamide cream 50 gm',
    genericName: 'Carbamide',
    concentration: '50 gm',
    price: 69.5,
    matchKeywords: ['hepta carbamide', 'هيبتا كارباميد', 'carbamide', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم كارباميد للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 14
  {
    id: 'carbamide-memphis-10-cream-30',
    name: 'carbamide-memphis 10% cream 30 gm',
    genericName: 'Carbamide',
    concentration: '10% (30 gm)',
    price: 40,
    matchKeywords: ['carbamide-memphis', 'كارباميد ممفيس', 'carbamide 10', ...TAGS.moisturizer],
    usage: 'كريم كارباميد 10% للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 15
  {
    id: 'gelinose-delicate-moisturizing-gel-20',
    name: 'gelinose delicate moisturizing gel 20gm',
    genericName: 'Propylene glycol & Aloe vera & Sodium chloride & Carbomer & Sodium hydroxide & Panthenol & Methyl paraben',
    concentration: '20 gm',
    price: 50,
    matchKeywords: ['gelinose', 'جيلينوز', 'aloe vera', 'panthenol', ...TAGS.moisturizer],
    usage: 'جل ترطيب وتهدئة للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 16
  {
    id: 'jbc-cream-50',
    name: 'j.b.c cream 50 gm',
    genericName: 'Jojoba oil & Panthenol & Aloe vera & Glycerin & Propolis',
    concentration: '50 gm',
    price: 100,
    matchKeywords: ['j.b.c', 'jbc', 'جي بي سي', 'jojoba', ...TAGS.moisturizer],
    usage: 'كريم مرطب ومطري.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 17
  {
    id: 'panthenol-2-cream-50',
    name: 'panthenol 2% topical cream 50 gm',
    genericName: 'Dexpanthenol',
    concentration: '2% (50 gm)',
    price: 80,
    matchKeywords: ['panthenol 2% 50', 'dexpanthenol', ...TAGS.moisturizer],
    usage: 'كريم بانثينول 2% للترطيب والتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 18
  {
    id: 'panthenol-panax-cream-20',
    name: 'panthenol panax cream 20 gm',
    genericName: 'D-panthenol',
    concentration: '20 gm',
    price: 29,
    matchKeywords: ['panax 20', 'بانكس 20', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم بانثينول للترطيب والتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 19
  {
    id: 'revi-2-cream-50',
    name: 'revi 2 cream 50 gm',
    genericName: 'Panthenol & Dimethicone & Chamomile extract & Glycerin & Vitamin A & Vitamin E & Olive oil & Almond oil',
    concentration: '50 gm',
    price: 75,
    matchKeywords: ['revi 2', 'ريفي 2', 'dimethicone', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وحماية (حاجز) للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 20
  {
    id: 'richi-panthenol-cream-20',
    name: 'richi panthenol cream 20gm',
    genericName: 'Dexpanthenol & Vitamin C & Nicotinamide & Liquorice extract',
    concentration: '20 gm',
    price: 25,
    matchKeywords: ['richi 20', 'ريشي 20', 'niacinamide', 'vitamin c', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب/عناية للبشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 21
  {
    id: 'richi-panthenol-cream-50',
    name: 'richi panthenol cream 50gm',
    genericName: 'Dexpanthenol & Vitamin C & Nicotinamide & Liquorice extract',
    concentration: '50 gm',
    price: 49.5,
    matchKeywords: ['richi 50', 'ريشي 50', 'niacinamide', 'vitamin c', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب/عناية للبشرة (عبوة أكبر).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 22
  {
    id: 'hipanthen-plus-topical-lotion-120',
    name: 'hipanthen plus topical lotion 120ml',
    genericName: 'Dimethicone & Casein protein & Panthenol & Whey protein & Glycerin & Zinc oxide & Chamomile & Olive oil & Almond oil & Vitamin E & Allantoin',
    concentration: '120 ml',
    price: 55,
    matchKeywords: ['hipanthen lotion', 'هيبانثين لوشن', 'dimethicone', ...TAGS.moisturizer],
    usage: 'لوشن مرطب وحاجز للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 23
  {
    id: 'panthenol-novex-plus-cream-30',
    name: 'panthenol novex plus cream 30 gm',
    genericName: 'Panthenol & Chlorhexidine',
    concentration: '30 gm',
    price: 40,
    matchKeywords: ['novex plus', 'نوڤكس بلس', 'chlorhexidine', ...TAGS.moisturizer],
    usage: 'كريم بانثينول مع مطهر خفيف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 24
  {
    id: 'melanthenol-ss-cream-30',
    name: 'melanthenol ss 30gm cream',
    genericName: 'D-panthenol & Glycerin & Vitamin E & Allantoin',
    concentration: '30 gm',
    price: 75,
    matchKeywords: ['melanthenol ss', 'ميلانثينول اس اس', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتهدئة للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 25
  {
    id: 'zincofact-cream-50',
    name: 'zincofact cream 50 gm',
    genericName: 'Calendula oil & Chamomile oil & Honey & Chlorhexidine & Triclosan & Zinc oxide',
    concentration: '50 gm',
    price: 75,
    matchKeywords: ['zincofact', 'زينكوفاكت', 'zinc oxide', ...TAGS.moisturizer],
    usage: 'كريم حماية وترطيب مع مطهرات خفيفة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 26
  {
    id: 'andoderma-extra-emollient-gel-50',
    name: 'andoderma extra emollient gel 50 ml',
    genericName: 'Isopropyl myristate & Liquid paraffin & Glycerol & Carbomer & Cetomacrogol & Triethanolamine & Phenoxyethanol',
    concentration: '50 ml',
    price: 110,
    matchKeywords: ['andoderma', 'اندوديرما', 'emollient', ...TAGS.moisturizer],
    usage: 'جل مطري/مرطب للجفاف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 27
  {
    id: 'elay-spray-70',
    name: 'elay 70ml spray',
    genericName: 'Sea water & Panthenol & Hyaluronic',
    concentration: '70 ml',
    price: 80,
    matchKeywords: ['elay', 'ايلاي', 'panthenol', 'hyaluronic', ...TAGS.moisturizer],
    usage: 'سبراي ترطيب/تهدئة للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Spray',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 28
  {
    id: 'emo-soft-cream-15',
    name: 'emo soft cream 15 gm',
    genericName: 'Zinc oxide & Capric triglyceride & Hexyl laurate & Panthenol & Glycerol & Bisabolol',
    concentration: '15 gm',
    price: 40,
    matchKeywords: ['emo soft 15', 'ايمو سوفت 15', ...TAGS.moisturizer],
    usage: 'كريم مرطب وملطف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 29
  {
    id: 'foot-smart-cream-60',
    name: 'foot smart cream 60 gm',
    genericName: 'Lactic acid & Urea & Almond oil & Glycerin',
    concentration: '60 gm',
    price: 65,
    matchKeywords: ['foot smart', 'فوت سمارت', 'urea', 'lactic acid', ...TAGS.moisturizer],
    usage: 'كريم للقدمين للجفاف/التشققات.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['قد يسبب تهيجاً على الجلد المتشقق.']
  },
  // 30
  {
    id: 'hiderm-cream-50',
    name: 'hiderm cream 50 gm',
    genericName: 'Glycerin & Zinc oxide & Olive oil & Menthol & Titanium dioxide & Lanolin',
    concentration: '50 gm',
    price: 55,
    matchKeywords: ['hiderm cream', 'هايديرم كريم', 'lanolin', ...TAGS.moisturizer],
    usage: 'كريم مرطب/ملطف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 31
  {
    id: 'hiderm-topical-lotion-100',
    name: 'hiderm topical lotion 100ml',
    genericName: 'Glycerin & Zinc oxide & Olive oil & Menthol & Titanium dioxide & Lanolin',
    concentration: '100 ml',
    price: 55,
    matchKeywords: ['hiderm lotion', 'هايديرم لوشن', 'lanolin', ...TAGS.moisturizer],
    usage: 'لوشن مرطب/ملطف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 32
  {
    id: 'macro-panthenol-cream-50',
    name: 'macro panthenol cream 50 gm',
    genericName: 'Panthenol & Glycerin & Paraffin oil',
    concentration: '50 gm',
    price: 60,
    matchKeywords: ['macro panthenol', 'ماكرو بانثينول', 'paraffin', ...TAGS.moisturizer],
    usage: 'كريم بانثينول مرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 33
  {
    id: 'mondo-cream-50',
    name: 'mondo cream 50 gm',
    genericName: 'Panthenol & Chamomile oil & Borax & Methyl ethylene glycol',
    concentration: '50 gm',
    price: 75,
    matchKeywords: ['mondo', 'موندو', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم مرطب وملطف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 34
  {
    id: 'np-plus-cream-50',
    name: 'n.p plus cream 50 gm',
    genericName: 'Panthenol & Whey casein & Honey & Glycerin & Olive oil & Lanolin',
    concentration: '50 gm',
    price: 60,
    matchKeywords: ['n.p plus', 'ان بي بلس', 'lanolin', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتغذية للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 35
  {
    id: 'panthenol-panax-cream-50',
    name: 'panthenol panax cream 50 gm',
    genericName: 'Panthenol',
    concentration: '50 gm',
    price: 50,
    matchKeywords: ['panax 50', 'بانكس 50', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم بانثينول للترطيب والتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 36
  {
    id: 'qv-cream-100',
    name: 'qv cream 100 gm',
    genericName: 'Aqua & Paraffinum liquidum & Glycerin & Petrolatum & Cetearyl alcohol',
    concentration: '100 gm',
    price: 224,
    matchKeywords: ['qv 100', 'كيو ڤي', ...TAGS.moisturizer],
    usage: 'كريم ترطيب كثيف ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 37
  {
    id: 'qv-cream-50',
    name: 'qv cream 50 gm',
    genericName: 'Aqua & Paraffinum liquidum & Glycerin & Petrolatum & Cetearyl alcohol',
    concentration: '50 gm',
    price: 123,
    matchKeywords: ['qv 50', 'كيو ڤي 50', ...TAGS.moisturizer],
    usage: 'كريم ترطيب كثيف (عبوة أصغر).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 38
  {
    id: 'shoma-cream-60',
    name: 'shoma cream 60 gm',
    genericName: 'Glycerin & Paraffin oil & Salicylic acid & Lactic acid & Panthenol',
    concentration: '60 gm',
    price: 130,
    matchKeywords: ['shoma', 'شوما', 'salicylic', 'lactic', ...TAGS.moisturizer],
    usage: 'كريم للجفاف/الخشونة (قد يحتوي أحماض).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['قد يسبب تهيجاً/جفافاً.']
  },
  // 39
  {
    id: 'well-derm-cream-50',
    name: 'well derm cream 50 gm',
    genericName: 'Zinc oxide & Vitamin A & Olive oil & Panthenol',
    concentration: '50 gm',
    price: 65,
    matchKeywords: ['well derm', 'ويل ديرم', 'panthenol', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 40
  {
    id: 'aleavia-ear-drops-20',
    name: 'aleavia ear drops 20 ml',
    genericName: 'Olive oil & Almond oil & Paraffin & Tea tree & Garlic & Coconut',
    concentration: '20 ml',
    price: 50,
    matchKeywords: ['aleavia', 'اليڤيا', 'ear drops', ...TAGS.moisturizer],
    usage: 'قطرات أذن ملطفة/مطرية حسب الاستخدام.',
    timing: 'حسب الحاجة.',
    category: Category.EAR_CARE,
    form: 'Drops',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُستخدم حسب تعليمات المنتج/الطبيب.',
    warnings: ['ألم شديد/إفرازات: أعد التقييم (استبعاد التهاب أذن وسطى/انثقاب).']
  },
  // 41
  {
    id: 'jbc-cream-100',
    name: 'j.b.c cream 100 gm',
    genericName: 'Jojoba oil & Panthenol & Aloe vera & Glycerin & Propolis',
    concentration: '100 gm',
    price: 100,
    matchKeywords: ['j.b.c 100', 'jbc 100', 'جي بي سي 100', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم مرطب (عبوة كبيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 42
  {
    id: 'melanthenol-cream-40',
    name: 'melanthenol cream 40 gm',
    genericName: 'D-panthenol & Ceramide & Almond oil & Vitamin E',
    concentration: '40 gm',
    price: 60,
    matchKeywords: ['melanthenol', 'ميلانثينول', 'ceramide', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 43
  {
    id: 'nody-nasal-spray-30',
    name: 'nody nasal spray 30 ml',
    genericName: 'Panthenol & Hyaluronic acid & Vitamin A & Vitamin E & Biotin',
    concentration: '30 ml',
    price: 110,
    matchKeywords: ['nody', 'نودي', 'nasal spray', 'hyaluronic', 'panthenol', ...TAGS.moisturizer],
    usage: 'بخاخ أنفي لترطيب الأنف.',
    timing: '١–٢ مرة يومياً',
    category: Category.NASAL_CARE,
    form: 'Nasal Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['إذا استمرت الأعراض: أعد التقييم.']
  },
  // 44
  {
    id: 'panthenol-novex-cream-30',
    name: 'panthenol novex cream 30 gm',
    genericName: 'Panthenol',
    concentration: '30 gm',
    price: 33,
    matchKeywords: ['panthenol novex 30', 'نوڤكس بانثينول 30', ...TAGS.moisturizer],
    usage: 'كريم بانثينول مرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 45
  {
    id: 'panthenol-novex-cream-50',
    name: 'panthenol novex cream 50 gm',
    genericName: 'Panthenol',
    concentration: '50 gm',
    price: 35,
    matchKeywords: ['panthenol novex 50', 'نوڤكس بانثينول 50', ...TAGS.moisturizer],
    usage: 'كريم بانثينول مرطب (عبوة أكبر).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 46
  {
    id: 'melanthenol-gel-40',
    name: 'melanthenol gel 40 gm',
    genericName: 'D-panthenol & Ceramide & Almond oil & Vitamin E',
    concentration: '40 gm',
    price: 60,
    matchKeywords: ['melanthenol gel', 'ميلانثينول جل', 'ceramide', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'جل ترطيب وتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 47
  {
    id: 'ivywonder-moisturizing-cream-50',
    name: 'ivywonder moisturizing cream 50gm',
    genericName: 'Ceramide & Panthenol & Shea butter & Glycerin',
    concentration: '50 gm',
    price: 110,
    matchKeywords: ['ivywonder', 'آيفي وندر', 'ceramide', 'shea butter', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'كريم ترطيب ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 48
  {
    id: 'mamy-care-cream-30',
    name: 'mamy care cream 30 gm',
    genericName: 'Panthenol & Allantoin & Bisabolol & Dimethicone & Glycerin',
    concentration: '30 gm',
    price: 17,
    matchKeywords: ['mamy care 30', 'مامي كير 30', ...TAGS.moisturizer],
    usage: 'كريم ترطيب وتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 49
  {
    id: 'sinzahoc-nasal-spray-30',
    name: 'sinzahoc 30 ml nasal spray soothing & moisturising',
    genericName: 'Sea water & Hyaluronic acid & Eucalyptus & Panthenol',
    concentration: '30 ml',
    price: 75,
    matchKeywords: ['sinzahoc 30', 'سينزا هوك 30', 'nasal spray', ...TAGS.moisturizer, ...TAGS.soothing],
    usage: 'بخاخ أنفي لترطيب وتهدئة الأنف.',
    timing: '١–٢ مرة يومياً',
    category: Category.NASAL_CARE,
    form: 'Nasal Spray',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['إذا استمرت الأعراض: أعد التقييم.']
  },
  // 50
  {
    id: 'emo-soft-cream-30',
    name: 'emo soft cream 30 gm',
    genericName: 'Zinc oxide & Capric triglyceride & Hexyl laurate & Panthenol & Glycerol & Bisabolol',
    concentration: '30 gm',
    price: 60,
    matchKeywords: ['emo soft 30', 'ايمو سوفت 30', ...TAGS.moisturizer],
    usage: 'كريم مرطب وملطف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 51
  {
    id: 'mamy-care-cream-50',
    name: 'mamy care cream 50 gm',
    genericName: 'Panthenol & Allantoin & Bisabolol & Dimethicone & Glycerin',
    concentration: '50 gm',
    price: 90,
    matchKeywords: ['mamy care 50', 'مامي كير 50', ...TAGS.moisturizer],
    usage: 'كريم مرطب وملطف (عبوة أكبر).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 52
  {
    id: 'panthenol-5-gel-20',
    name: 'panthenol 5% topical gel 20 gm',
    genericName: 'D-panthenol',
    concentration: '5% (20 gm)',
    price: 30,
    matchKeywords: ['panthenol 5%', 'بانثينول 5', ...TAGS.moisturizer],
    usage: 'جل بانثينول للترطيب والتهدئة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 53
  {
    id: 'didder-cream-75',
    name: 'didder 75 gm cream',
    genericName: 'Honey & Propolis & Royal jelly & Beaswax & Glycerol & Vitamin E',
    concentration: '75 gm',
    price: 120,
    matchKeywords: ['didder', 'ديدر', ...TAGS.moisturizer, ...TAGS.healing],
    usage: 'كريم ترطيب/ترميم للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 54
  {
    id: 'hydrensa-moisturizing-cream-200',
    name: 'hydrensa moisturizing cream 200 ml',
    genericName: 'Ceramides & Hyaluronic acid & Niacinamide & Shea butter & Vitamin E',
    concentration: '200 ml',
    price: 195,
    matchKeywords: ['hydrensa', 'هايدرينسا', 'niacinamide', 'ceramides', ...TAGS.moisturizer],
    usage: 'كريم ترطيب مكثف ودعم حاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 55
  {
    id: 'bb-skin-emollient-cream-120',
    name: 'b & b skin emollient cream 120 gm',
    genericName: 'Avocado oil & Propolis & Aloe vera extract & Calendula extract',
    concentration: '120 gm',
    price: 159,
    matchKeywords: ['b & b', 'b&b', 'avocado', 'aloe vera', ...TAGS.moisturizer],
    usage: 'كريم مطري ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 56
  {
    id: 'demark-face-cream-30',
    name: 'demark face cream 30 gm',
    genericName: 'Collagen & Royal jelly & Silicon oil & Emu oil & Vitamins A & Vitamin E',
    concentration: '30 gm',
    price: 160,
    matchKeywords: ['demark', 'ديمارك', 'face', ...TAGS.moisturizer],
    usage: 'كريم ترطيب للوجه.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 57
  {
    id: 'like-moisturizing-cream-50',
    name: 'like 50 gm moisturizing cream',
    genericName: 'Panthenol & Alovera extract & Cucumber extract & Petrolatum',
    concentration: '50 gm',
    price: 75,
    matchKeywords: ['like moisturizing', 'لايك', 'aloe vera', 'petrolatum', ...TAGS.moisturizer],
    usage: 'كريم ترطيب للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 58
  {
    id: 'genica-moist-cream-100',
    name: 'genica moist cream 100 gm',
    genericName: 'Shea butter & Aloe vera & Glycerin & Olive oil & Cocoa butter & Panthenol',
    concentration: '100 gm',
    price: 145,
    matchKeywords: ['genica', 'جينيكا', 'shea butter', 'cocoa butter', ...TAGS.moisturizer],
    usage: 'كريم ترطيب مكثف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 59
  {
    id: 'hepta-carbamide-10-body-lotion-120',
    name: 'hepta carbamide 10% body lotion 120 ml',
    genericName: 'Carbamide',
    concentration: '10% (120 ml)',
    price: 165,
    matchKeywords: ['hepta carbamide 10% lotion', 'هيبتا كارباميد لوشن', ...TAGS.moisturizer, ...TAGS.skinCare],
    usage: 'لوشن كارباميد 10% لترطيب الجسم.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 60
  {
    id: 'infinity-moisturizing-cream-120',
    name: 'infinity moisturizing cream 120 ml',
    genericName: 'Patch2o & Scab extr. & Macadamia oil & Allantoin & Caviar ext. & Niacinamide',
    concentration: '120 ml',
    price: 170,
    matchKeywords: ['infinity moisturizing', 'انفينتي مرطب', 'niacinamide', ...TAGS.moisturizer],
    usage: 'كريم ترطيب/عناية للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 61
  {
    id: 'macro-carbamide-10-cream-50',
    name: 'macro carbamide 10% cream 50 gm',
    genericName: 'Carbamide',
    concentration: '10% (50 gm)',
    price: 65,
    matchKeywords: ['macro carbamide 10%', 'ماكرو كارباميد', ...TAGS.moisturizer],
    usage: 'كريم كارباميد 10% للترطيب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  }
];

