import { Medication, Category } from '../../../types';

const TAGS = {
  soap: ['soap', '#soap', 'صابونة', 'غسول', 'منظف', 'cleanser', 'bar soap'],
  acne: ['acne', 'acne prone', 'حب الشباب', 'حب شباب', 'بشرة دهنية', 'oily skin'],
  whitening: ['whitening', 'تفتيح', 'تفتيح البشرة', 'brightening'],
  baby: ['baby', 'أطفال'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
};

export const SOAPS_MEDS: Medication[] = [
  // 1
  {
    id: 'synobar-soap-100',
    name: 'synobar soap 100 gm',
    genericName: 'Tea tree oil & Irgasan & Lavendula oily extract & Wheat germ oil & Salicylic acid',
    concentration: '100 gm',
    price: 60,
    matchKeywords: ['synobar', 'سينوبار', 'tea tree', 'irgasan', 'salicylic', ...TAGS.soap, ...TAGS.acne],
    usage: 'صابونة/منظف للبشرة المعرضة للحبوب والدهون.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 2
  {
    id: 'harvy-soap-80',
    name: 'harvy soap 80 gm',
    genericName: 'Kojic acid & Licuorice extract & Vitamin C & Glycolic acid & Zinc oxide',
    concentration: '80 gm',
    price: 55,
    matchKeywords: ['harvy', 'هارفي', 'kojic', 'glycolic', 'vitamin c', ...TAGS.soap, ...TAGS.whitening],
    usage: 'صابونة تفتيح/تنظيف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 3
  {
    id: 'starville-soap-acne-100',
    name: 'starville soap for acne prone skin 100 gm',
    genericName: 'Sulphur & Zinc oxide & Tea tree oil & Vitamin C & Salicylic acid & Aloe vera & Licorice',
    concentration: '100 gm',
    price: 50,
    matchKeywords: ['starville acne soap', 'ستارفيل', 'sulphur', 'salicylic', ...TAGS.soap, ...TAGS.acne],
    usage: 'صابونة للبشرة المعرضة لحب الشباب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 4
  {
    id: 'starville-whitening-soap-100',
    name: 'starville whitening soap 100 gm',
    genericName: 'Collagen & Vitamin E & Kojic acid & Arbutin & Papaya & Olive oil',
    concentration: '100 gm',
    price: 50,
    matchKeywords: ['starville whitening', 'arbutin', 'papaya', 'kojic', ...TAGS.soap, ...TAGS.whitening],
    usage: 'صابونة تفتيح/تنظيف.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 5
  {
    id: 'ventamor-soap-60',
    name: 'ventamor soap 60 gm',
    genericName: 'Licuorice extract & Vitamin C & Salicylic acid & Glutathione & Sulfur & Aloe vera',
    concentration: '60 gm',
    price: 80,
    matchKeywords: ['ventamor', 'فينتامور', 'glutathione', 'sulfur', 'salicylic', ...TAGS.soap, ...TAGS.whitening],
    usage: 'صابونة تنظيف/تفتيح.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 6
  {
    id: 'fitt-bar-soap-100',
    name: 'fitt-bar soap 100 gm',
    genericName:
      'Calendula extract & Liquorice extract & Tea tree oil & Emu oil & Aloe vera & Onion extract & Panthenol & Vitamin E',
    concentration: '100 gm',
    price: 60,
    matchKeywords: ['fitt-bar', 'فيت بار', 'emu oil', 'panthenol', ...TAGS.soap],
    usage: 'صابونة/منظف للعناية بالبشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 7
  {
    id: 'fungicare-soap-80',
    name: 'fungicare soap 80 gm',
    genericName: 'Resorcinol & Salicylic acid & Benzoic acid & Cetrimide',
    concentration: '80 gm',
    price: 50,
    matchKeywords: ['fungicare', 'فانجيكير', 'resorcinol', 'benzoic', 'salicylic', ...TAGS.soap],
    usage: 'صابونة/منظف قد يساعد في العناية بالجلد المعرض للفطريات/الرائحة.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 8
  {
    id: 'hiderm-transparent-soap-75',
    name: 'hiderm transparent soap 75 gm',
    genericName: 'Panthenol & Chamomile & Olive oil & Vitamin E & Glycerin & Cetrimide',
    concentration: '75 gm',
    price: 50,
    matchKeywords: ['hiderm', 'هايدرم', 'panthenol', 'chamomile', ...TAGS.soap, ...TAGS.skinCare],
    usage: 'صابونة لطيفة/منظف للعناية بالبشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 9
  {
    id: 'kapritage-soap-100',
    name: 'kapritage soap 100 gm',
    genericName: 'Sulfokonzentrol',
    concentration: '100 gm',
    price: 55,
    matchKeywords: ['kapritage', 'كابريتاج', 'sulfokonzentrol', ...TAGS.soap],
    usage: 'صابونة/منظف.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 10
  {
    id: 'liquovit-soap-100',
    name: 'liquovit soap 100 gm',
    genericName: 'Chamomile & Liquorice & Salicylic acid & Aloe vera & Lanolin & Vitamin C',
    concentration: '100 gm',
    price: 100,
    matchKeywords: ['liquovit', 'ليكوفِت', 'lanolin', 'salicylic', ...TAGS.soap],
    usage: 'صابونة/منظف للعناية بالبشرة.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 11
  {
    id: 'natry-soap-100',
    name: 'natry soap 100 gm',
    genericName: 'Native hydrated aluminium silicate & Irgazan & Thyme oil & Glycerin & Salicylic acid & Zinc oxide',
    concentration: '100 gm',
    price: 60,
    matchKeywords: ['natry', 'ناتري', 'irgasan', 'thyme', 'salicylic', ...TAGS.soap],
    usage: 'صابونة/منظف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 12
  {
    id: 'sensoderm-baby-soap-80',
    name: 'sensoderm baby soap 80 gm',
    genericName: 'Zinc oxide & Titanium dioxide & Glycerin & Olive oil & Chamomile',
    concentration: '80 gm',
    price: 50,
    matchKeywords: ['sensoderm baby soap', 'سينسوديرم صابونة اطفال', 'chamomile', 'olive oil', ...TAGS.soap, ...TAGS.baby],
    usage: 'صابونة/منظف لطيف للأطفال.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 0,
    maxAgeMonths: 60,
    minWeight: 3,
    maxWeight: 25,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 13
  {
    id: 'sensoderm-moisturizing-soap-80',
    name: 'sensoderm moisturizing soap 80 gm',
    genericName: 'Zinc oxide & Glycerin & Betaine & Paraffin oil & Titanium dioxide',
    concentration: '80 gm',
    price: 50,
    matchKeywords: ['sensoderm moisturizing soap', 'سينسوديرم صابونة مرطبة', 'paraffin', 'betaine', ...TAGS.soap],
    usage: 'صابونة/منظف مرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 14
  {
    id: 'sensoderm-soap-80',
    name: 'sensoderm soap 80 gm',
    genericName: 'Triclosan & Boric acid & Zinc oxide & Glycerin & Betaine & Panthenol',
    concentration: '80 gm',
    price: 50,
    matchKeywords: ['sensoderm soap', 'سينسوديرم صابونة', 'triclosan', 'boric', 'panthenol', ...TAGS.soap],
    usage: 'صابونة/منظف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 15
  {
    id: 'top-zad-soap-80',
    name: 'top zad soap 80 gm',
    genericName: 'Boric acid & Zinc oxide & Olive oil',
    concentration: '80 gm',
    price: 55,
    matchKeywords: ['top zad', 'توب زاد', 'boric', 'zinc oxide', ...TAGS.soap],
    usage: 'صابونة/منظف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 16
  {
    id: 'advance-soap-100',
    name: 'advance soap 100 gm',
    genericName: 'Sulphur & Salicylic acid & Lemon oil & Citric acid & Boric acid & Tea tree oil',
    concentration: '100 gm',
    price: 57,
    matchKeywords: ['advance soap', 'ادفانس صابونة', 'sulphur', 'salicylic', 'tea tree', ...TAGS.soap, ...TAGS.acne],
    usage: 'صابونة للبشرة الدهنية/المعرضة للحبوب.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 17
  {
    id: 'no-acne-soap-100',
    name: 'no acne soap 100 gm',
    genericName: 'Resorcinol & Zinc oxide & Allantoin',
    concentration: '100 gm',
    price: 55,
    matchKeywords: ['no acne', 'نو اكني', 'resorcinol', 'allantoin', ...TAGS.soap, ...TAGS.acne],
    usage: 'صابونة للبشرة المعرضة للحبوب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 18
  {
    id: 'r-m-soap-80',
    name: 'r.m. soap 80 gm',
    genericName: 'Irgasan & Citric acid & Salicylic acid',
    concentration: '80 gm',
    price: 55,
    matchKeywords: ['r.m.', 'rm soap', 'irgasan', 'salicylic', ...TAGS.soap],
    usage: 'صابونة/منظف.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 120,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 19
  {
    id: 'sensoderm-t-s-soap-75',
    name: 'sensoderm t.s soap 75 gm',
    genericName: 'Panthenol & Chamomile & Olive oil & Castor oil & Glycerin & Vitamin E',
    concentration: '75 gm',
    price: 64,
    matchKeywords: ['sensoderm t.s', 'sensoderm ts', 'castor oil', 'panthenol', ...TAGS.soap],
    usage: 'صابونة/منظف لطيف.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 20
  {
    id: 'vatex-soap-80',
    name: 'vatex soap 80 gm',
    genericName: 'Liquorice extract & Titanium dioxide & Kojic acid & Vitamin C & Glycerin & Sodium hydroxide',
    concentration: '80 gm',
    price: 45,
    matchKeywords: ['vatex', 'ڤاتكس', 'kojic', 'titanium dioxide', 'vitamin c', ...TAGS.soap, ...TAGS.whitening],
    usage: 'صابونة تفتيح/تنظيف.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  }
];

