import { Medication, Category } from '../../../types';

const TAGS = {
  soothing: ['soothing topical', '#soothing topical', 'soothing', 'مهدئ', 'تهدئة', 'calamine', 'zinc oxide', 'تهيج', 'irritation', 'حكة', 'itching', 'تسلخات', 'حساسية جلد'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
  antiAllergic: ['anti-allergic', '#anti-allergic', 'anti allergic', 'مضاد حساسية'],
  diaper: ['diaper area', '#diaper area', 'diaper', 'حفاض', 'تسلخات'],
  emollient: ['emollient', '#emollient', 'مطري'],
};

export const SOOTHING_MEDS: Medication[] = [
  // 1
  {
    id: 'zincoderm-topical-lotion-120',
    name: 'zincoderm topical lotion 120ml',
    genericName: 'Zinc oxide & Thyme extract & Chamomile extract & Glycerin',
    concentration: '120 ml',
    price: 65,
    matchKeywords: ['zincoderm', 'زينكوديرم', ...TAGS.soothing],
    usage: 'لوشن مهدئ وواقٍ للجلد (خصوصاً التسلخات والتهيج البسيط).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 2
  {
    id: 'sensoderm-cream-50',
    name: 'sensoderm cream 50 gm',
    genericName: 'Panthenol & Liquorice & Vitamin E & Urea & Bees wax & Calendula',
    concentration: '50 gm',
    price: 65,
    matchKeywords: ['sensoderm', 'سينسوديرم', 'panthenol', ...TAGS.soothing],
    usage: 'كريم مهدئ ومرطب للبشرة المتهيجة.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 3
  {
    id: 'zincoderm-topical-cream-50',
    name: 'zincoderm topical cream 50 gm',
    genericName: 'Zinc oxide & Thyme extract & Chamomile extract & Glycerin',
    concentration: '50 gm',
    price: 70,
    matchKeywords: ['zincoderm', 'زينكوديرم', 'cream', ...TAGS.soothing],
    usage: 'كريم مهدئ وواقٍ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 4
  {
    id: 'bringo-topical-lotion-120',
    name: 'bringo topical lotion 120ml',
    genericName: 'Zinc oxide & Thyme extract & Chamomile extract & Menthol',
    concentration: '120 ml',
    price: 70,
    matchKeywords: ['bringo', 'برينجو', 'menthol', ...TAGS.soothing],
    usage: 'لوشن مهدئ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 5
  {
    id: 'calamyl-lotion-100',
    name: 'calamyl lotion 100 ml',
    genericName: 'Calamine & Glycerin & Camphor',
    concentration: '100 ml',
    price: 49,
    matchKeywords: ['calamyl', 'كالاميل', 'calamine', 'camphor', ...TAGS.soothing, ...TAGS.antiAllergic],
    usage: 'لوشن كالامين مهدئ للحكة والتهيج.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 6
  {
    id: 'clawash-lotion-120',
    name: 'clawash lotion 120 ml',
    genericName: 'Chamomile & Glycerin & Menthol & Titanium dioxide & Vitamin E & Zinc oxide',
    concentration: '120 ml',
    price: 38,
    matchKeywords: ['clawash', 'كلاواش', 'menthol', ...TAGS.soothing],
    usage: 'لوشن مهدئ وملطف للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 7
  {
    id: 'sensoderm-topical-lotion-120',
    name: 'sensoderm topical lotion 120 ml',
    genericName: 'Zinc oxide & Grape seed extract & Triclosan & Camphor & Glycerin',
    concentration: '120 ml',
    price: 60,
    matchKeywords: ['sensoderm lotion', 'سينسوديرم لوشن', 'grape seed', ...TAGS.soothing],
    usage: 'لوشن مهدئ وواقٍ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 8
  {
    id: 'helozin-topical-lotion-120',
    name: 'helozin topical lotion 120 ml',
    genericName: 'Zinc oxide & Glycerin & Panthenol & Vitamin E & Menthol',
    concentration: '120 ml',
    price: 60,
    matchKeywords: ['helozin', 'هيلوزين', 'panthenol', ...TAGS.soothing],
    usage: 'لوشن مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 9
  {
    id: 'care-by-care-cream-100',
    name: 'care by care cream 100 gm',
    genericName: 'Zinc oxide & Lanolin & Olive oil & Vaseline & Triclosan & Bees wax',
    concentration: '100 gm',
    price: 90,
    matchKeywords: ['care by care', 'كير باي كير', 'lanolin', ...TAGS.soothing],
    usage: 'كريم واقٍ ومهدئ للجلد (تسلخات/تهيج).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 10
  {
    id: 'care-by-care-plus-cream-100',
    name: 'care by care plus cream 100 gm',
    genericName: 'Olive oil & Paraffin oil & Babong & Tea tree oil & Tretinoin & Thyme',
    concentration: '100 gm',
    price: 130,
    matchKeywords: ['care by care plus', 'تريتينوين', 'tretinoin', ...TAGS.soothing],
    usage: 'كريم مهدئ/عناية للجلد.',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['قد يسبب تهيجاً.', 'غير مناسب أثناء الحمل.']
  },
  // 11
  {
    id: 'epiderm-soothing-cream-50',
    name: 'epiderm soothing cream 50 gm',
    genericName: 'Panthenol & Olive oil & Chamomile & Zinc oxide & Petrolatum',
    concentration: '50 gm',
    price: 70,
    matchKeywords: ['epiderm', 'ايبيديرم', 'panthenol', ...TAGS.soothing],
    usage: 'كريم مهدئ ومرطب للبشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 12
  {
    id: 'shaan-soothing-gel-120',
    name: 'shaan soothing gel 120 gm',
    genericName: 'Panthenol & Carbomer & Triethanolamine & Aloe vera & Chamomile & Hydrogenated castor oil',
    concentration: '120 gm',
    price: 170,
    matchKeywords: ['shaan', 'شعان', 'aloe vera', 'panthenol', ...TAGS.soothing],
    usage: 'جل مهدئ ومرطب للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 13
  {
    id: 'sudocrem-cream-125',
    name: 'sudocrem cream 125 gm',
    genericName: 'Zinc oxide & Benzyl alcohol & Benzyl benzoate & Benzyl cinnamate',
    concentration: '125 gm',
    price: 195,
    matchKeywords: ['sudocrem 125', 'سودوكريم', ...TAGS.soothing],
    usage: 'كريم واقٍ ومهدئ (تسلخات/تهيج).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 14
  {
    id: 'vano-cream-50',
    name: 'vano cream 50gm',
    genericName: 'Panthenol & Dimethicone & Chamomile oil & Zinc sulfate & Cocoa butter & Tea tree oil',
    concentration: '50 gm',
    price: 75,
    matchKeywords: ['vano', 'فانو', 'dimethicone', ...TAGS.soothing],
    usage: 'كريم مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 15
  {
    id: 'shaan-soothing-gel-200',
    name: 'shaan soothing gel 200 gm',
    genericName: 'Panthenol & Carbomer & Triethanolamine & Aloe vera & Chamomile & Hydrogenated castor oil',
    concentration: '200 gm',
    price: 220,
    matchKeywords: ['shaan 200', 'شعان 200', ...TAGS.soothing, ...TAGS.skinCare],
    usage: 'جل مهدئ ومرطب للجلد (عبوة كبيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 16
  {
    id: 'istikrema-cream-30',
    name: 'istikrema 30gm cream',
    genericName: 'Beta sitosterol & Chlorhexidine & Hyaluronic acid & Aloe vera ext',
    concentration: '30 gm',
    price: 85,
    matchKeywords: ['istikrema', 'استيكريما', 'hyaluronic', ...TAGS.soothing],
    usage: 'كريم مهدئ ومساعد لالتئام الجلد الخفيف.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 17
  {
    id: 'care-by-care-baby-soap-100',
    name: 'care by care baby soap 100 gm',
    genericName: 'Zinc oxide & Lanolin & Olive oil & Vaseline & Triclosan & Bees wax',
    concentration: '100 gm',
    price: 60,
    matchKeywords: ['care by care soap', 'baby soap', 'صابونة', ...TAGS.soothing],
    usage: 'منظف/صابونة لطيفة للبشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 0,
    maxAgeMonths: 60,
    minWeight: 3,
    maxWeight: 25,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 18
  {
    id: 'derma-soft-cream-60',
    name: 'derma soft cream 60 ml',
    genericName: 'Allantoin extract & Panthenol & Vitamin E',
    concentration: '60 ml',
    price: 55,
    matchKeywords: ['derma soft', 'ديرما سوفت', 'allantoin', 'panthenol', ...TAGS.soothing, ...TAGS.skinCare],
    usage: 'كريم مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 19
  {
    id: 'pan-d-topical-lotion-120',
    name: 'pan-d topical lotion 120ml',
    genericName: 'Zinc oxide & Camphor & Menthol & Glycerol',
    concentration: '120 ml',
    price: 60,
    matchKeywords: ['pan-d', 'بان-دي', 'camphor', 'menthol', ...TAGS.soothing],
    usage: 'لوشن مهدئ للحكة والتهيج.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 20
  {
    id: 'three-zed-topical-lotion-120',
    name: 'three zed topical lotion 120ml',
    genericName: 'Zinc oxide & Menthol extract & Glycerin & C.M.C',
    concentration: '120 ml',
    price: 55,
    matchKeywords: ['three zed', '3 zed', 'ثري زيد', ...TAGS.soothing],
    usage: 'لوشن مهدئ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 21
  {
    id: 'zinc-olive-baby-lotion-60',
    name: 'zinc olive baby lotion 60 ml',
    genericName: 'Olive oil & Zinc oxide',
    concentration: '60 ml',
    price: 48,
    matchKeywords: ['zinc olive baby lotion', 'زينك اوليف لوشن', ...TAGS.soothing],
    usage: 'لوشن مهدئ وواقٍ للجلد (للأطفال).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 0,
    maxAgeMonths: 60,
    minWeight: 3,
    maxWeight: 25,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 22
  {
    id: 'calamine-lotion-120-novex',
    name: 'calamine lotion 120 ml novex',
    genericName: 'Calamine & Zinc oxide',
    concentration: '120 ml',
    price: 38,
    matchKeywords: ['novex calamine 120', 'نوڤكس كالامين', 'calamine', ...TAGS.soothing],
    usage: 'لوشن كالامين مهدئ للحكة والتهيج.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 23
  {
    id: 'calm-skin-cream-40',
    name: 'calm skin cream 40 gm',
    genericName: 'Chamomile & Zinc oxide & Dimethicone',
    concentration: '40 gm',
    price: 65,
    matchKeywords: ['calm skin 40', 'كالم سكين', ...TAGS.soothing],
    usage: 'كريم مهدئ وواقٍ.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 24
  {
    id: 'like-soothing-cream-50',
    name: 'like 50 gm soothing cream',
    genericName: 'Zinc oxide & Bees wax & Lanolin & Olive oil & Dimethicone & Vitamin E',
    concentration: '50 gm',
    price: 55,
    matchKeywords: ['like soothing', 'لايك مهدئ', ...TAGS.soothing, ...TAGS.diaper],
    usage: 'كريم مهدئ وواقٍ (مناسب لمنطقة الحفاض).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 25
  {
    id: 'bluekanza-spray-75',
    name: 'bluekanza 75 ml spray',
    genericName: 'Isotonic solution & Chammoile & Hyaluronic acid',
    concentration: '75 ml',
    price: 105,
    matchKeywords: ['bluekanza', 'بلوكنزا', 'isotonic', 'hyaluronic', ...TAGS.soothing],
    usage: 'سبراي مهدئ ومرطب للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Spray',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 26
  {
    id: 'sudocrem-cream-60',
    name: 'sudocrem cream 60 gm',
    genericName: 'Zinc oxide & Benzyl alcohol & Benzyl benzoate & Benzyl cinnamate',
    concentration: '60 gm',
    price: 120,
    matchKeywords: ['sudocrem 60', 'سودوكريم 60', ...TAGS.soothing],
    usage: 'كريم واقٍ ومهدئ (تسلخات/تهيج).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 27
  {
    id: 'kadyderm-cream-60',
    name: 'kadyderm 60 gm',
    genericName: 'Panthenol & Olive oil & Cyclopentasiloxane & Vitamin E',
    concentration: '60 gm',
    price: 75,
    matchKeywords: ['kadyderm', 'كاديديرم', 'panthenol', ...TAGS.soothing],
    usage: 'كريم مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 28
  {
    id: 'shaan-soothing-gel-60',
    name: 'shaan soothing gel 60 gm',
    genericName: 'Panthenol & Carbomer & Triethanolamine & Aloe vera & Chamomile & Hydrogenated castor oil',
    concentration: '60 gm',
    price: 100,
    matchKeywords: ['shaan 60', 'شعان 60', ...TAGS.soothing, ...TAGS.skinCare],
    usage: 'جل مهدئ ومرطب (عبوة صغيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 29
  {
    id: 'zinc-olive-lotion-spf50plus-100',
    name: 'zinc olive lotion 50+ spf 100 ml',
    genericName: 'Olive oil & Zinc oxide',
    concentration: '100 ml',
    price: 48,
    matchKeywords: ['zinc olive spf', 'spf 50+', 'sunblock', ...TAGS.soothing],
    usage: 'لوشن واقٍ وملطف (قد يستخدم كحاجز/واقي).',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 30
  {
    id: 'derma-soft-plus-cream-60',
    name: 'derma soft plus cream 60 gm',
    genericName: 'Collagen & Wheatgerm oil & Vitamin E & Aloe vera & Allantoin',
    concentration: '60 gm',
    price: 118,
    matchKeywords: ['derma soft plus 60', 'ديرما سوفت بلس', 'allantoin', ...TAGS.soothing, ...TAGS.skinCare],
    usage: 'كريم مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 31
  {
    id: 'uni-moist-cream-100',
    name: 'uni-moist cream 100 gm',
    genericName: 'Collegen & D panthenol & Avocado ext. & Candulla ext.',
    concentration: '100 gm',
    price: 129,
    matchKeywords: ['uni-moist', 'يوني موست', 'panthenol', ...TAGS.soothing],
    usage: 'كريم مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 32
  {
    id: 'roniderm-topical-lotion-120',
    name: 'roniderm topical lotion 120ml',
    genericName: 'Zinc oxide & Menthol extract & Glycerin & Olive oil & Chamomile',
    concentration: '120 ml',
    price: 49,
    matchKeywords: ['roniderm', 'رونيديرم', 'menthol', ...TAGS.soothing],
    usage: 'لوشن مهدئ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 33
  {
    id: 'herorash-cream-60',
    name: 'herorash cream 60 gm',
    genericName: 'Benzyl alcohol & Benzyl benzoate & Anhydrous wool fat',
    concentration: '60 gm',
    price: 70,
    matchKeywords: ['herorash', 'هيروراش', 'wool fat', 'lanolin', ...TAGS.soothing],
    usage: 'كريم مهدئ وواقٍ للجلد.',
    timing: 'مرتين يومياً – ٢–٤ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 34
  {
    id: 'calm-skin-cream-20',
    name: 'calm skin cream 20 gm',
    genericName: 'Chamomile & Dimethicone & Zinc oxide',
    concentration: '20 gm',
    price: 22.5,
    matchKeywords: ['calm skin 20', 'كالم سكين 20', ...TAGS.soothing],
    usage: 'كريم مهدئ وواقٍ (عبوة صغيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 35
  {
    id: 'derma-soft-plus-cream-100',
    name: 'derma soft plus cream 100 gm',
    genericName: 'Collagen & Wheatgerm oil & Vitamin E & Aloe vera & Allantoin',
    concentration: '100 gm',
    price: 180,
    matchKeywords: ['derma soft plus 100', 'ديرما سوفت بلس 100', ...TAGS.soothing],
    usage: 'كريم مهدئ ومرطب (عبوة كبيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 36
  {
    id: 'double-care-skin-gel-50',
    name: 'double care skin gel 50 gm',
    genericName: 'Tea tree oil & Aloe vera gel & Rose hip oil & Panthenol & Grape seed',
    concentration: '50 gm',
    price: 70,
    matchKeywords: ['double care', 'دابل كير', 'tea tree', 'aloe vera', ...TAGS.soothing],
    usage: 'جل مهدئ ومرطب.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 37
  {
    id: 'max-pro-topical-lotion-120',
    name: 'max-pro topical lotion 120 ml',
    genericName: 'Zinc oxide & Chamomile extract & Menthol crystals & Glycerin',
    concentration: '120 ml',
    price: 54,
    matchKeywords: ['max-pro', 'ماكس برو', 'menthol', ...TAGS.soothing],
    usage: 'لوشن مهدئ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 38
  {
    id: 'oz-topical-cream-100',
    name: 'o.z topical cream 100 gm',
    genericName: 'Zinc oxide & Olive oil & Liquid paraffin & Butylated hydroxy toluene',
    concentration: '100 gm',
    price: 80,
    matchKeywords: ['o.z', 'oz topical', 'liquid paraffin', ...TAGS.soothing],
    usage: 'كريم واقٍ ومهدئ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 39
  {
    id: 'novex-calamine-lotion-100',
    name: 'novex calamine lotion 100 ml',
    genericName: 'Calamine & Glycerin & Camphor',
    concentration: '100 ml',
    price: 49,
    matchKeywords: ['novex calamine 100', 'نوڤكس كالامين 100', 'calamine', ...TAGS.soothing, ...TAGS.skinCare],
    usage: 'لوشن كالامين مهدئ للحكة والتهيج.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 40
  {
    id: 'calamine-go-lotion',
    name: 'calamine go lotion',
    genericName: 'Calamine & Zinc oxide & Glycerol',
    concentration: 'Lotion',
    price: 29,
    matchKeywords: ['calamine go', 'كالامين جو', 'calamine', ...TAGS.soothing],
    usage: 'لوشن مهدئ للحكة والتهيج.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Lotion',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 41
  {
    id: 'emo-bro-gel-50',
    name: 'emo-bro gel 50 gm',
    genericName: 'Zinc oxide & Panthenol & Omega 3-6 & Dimethicone & Ceramide',
    concentration: '50 gm',
    price: 60,
    matchKeywords: ['emo-bro', 'ايمو برو', 'ceramide', ...TAGS.soothing, ...TAGS.skinCare],
    usage: 'جل مهدئ ومرطب وداعم لحاجز الجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 42
  {
    id: 'healovita-cream-30',
    name: 'healovita cream 30 gm',
    genericName: 'Hyaluronic acid & Collagen marine & Ceramide 3 & Shea butter',
    concentration: '30 gm',
    price: 88,
    matchKeywords: ['healovita', 'هيالوفيتا', 'hyaluronic', 'ceramide', ...TAGS.soothing, ...TAGS.emollient],
    usage: 'كريم مهدئ ومرطب (مطري).',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 43
  {
    id: 'diapella-soothing-cream-100',
    name: 'diapella soothing cream 100ml',
    genericName: 'Zincoxide & Panthenol & Cod liver oil & Centella asiatica & Honey',
    concentration: '100 ml',
    price: 85,
    matchKeywords: ['diapella', 'ديابيلا', 'centella', 'honey', ...TAGS.soothing],
    usage: 'كريم/مستحضر مهدئ للجلد.',
    timing: '١–٢ مرة يومياً',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 250,
    calculationRule: (_w, _a) => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  }
];

