import { Medication, Category } from '../../../types';

const TAGS = {
  sunblock: ['sunblock', '#sunblock', 'sunscreen', '#sunscreen', 'spf', 'واقي شمس', 'واقي', 'حماية من الشمس', 'sun protection', 'حروق شمس', 'sunburn'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
  tinted: ['tinted', 'ملون'],
  oilFree: ['oil free', 'oily skin', 'dry touch', 'oil-free'],
};

export const SUN_BLOCK_MEDS: Medication[] = [
  // 1
  {
    id: 'bobai-sunscreen-extra-lightening-gel-spf50-50',
    name: 'bobai sunscreen extra lightening gel spf 50 - 50 gm',
    genericName: 'Sun protection formula',
    concentration: '50 gm',
    price: 325,
    matchKeywords: ['bobai', 'بوباي', 'spf 50', 'gel', ...TAGS.sunblock],
    usage: 'واقي شمس جل للاستخدام اليومي.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 2
  {
    id: 'bobai-sun-block-cream-spf80-50',
    name: 'bobai sun block cream spf 80 - 50 gm',
    genericName: 'Sun protection formula',
    concentration: '50 gm',
    price: 195,
    matchKeywords: ['bobai', 'spf 80', 'cream', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 3
  {
    id: 'bobai-sunscreen-tinted-cream-spf80-60',
    name: 'bobai sunscreen tinted cream spf 80 - 60 gm',
    genericName: 'Sun protection formula',
    concentration: '60 gm',
    price: 225,
    matchKeywords: ['bobai', 'spf 80', 'tinted', ...TAGS.sunblock, ...TAGS.tinted],
    usage: 'واقي شمس كريم ملون.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 4
  {
    id: 'bobai-sun-block-tinted-cream-spf80-75',
    name: 'bobai sun block tinted cream spf 80 - 75 gm',
    genericName: 'Sun protection formula',
    concentration: '75 gm',
    price: 100,
    matchKeywords: ['bobai', 'spf 80', 'tinted', '75', ...TAGS.sunblock, ...TAGS.tinted],
    usage: 'واقي شمس كريم ملون.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 5
  {
    id: 'bobai-sunscreen-hydro-gel-spf50-60',
    name: 'bobai sun screen hydro gel spf 50 - 60 ml',
    genericName: 'Sun protection formula',
    concentration: '60 ml',
    price: 275,
    matchKeywords: ['bobai', 'hydro gel', 'spf 50', ...TAGS.sunblock],
    usage: 'واقي شمس جل/هيدرو جل.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 6
  {
    id: 'geneca-ray-sunscreen-spf50plus-cream-100',
    name: 'geneca ray sun screen spf 50+ cream 100 gm',
    genericName: 'Sun protection formula',
    concentration: '100 gm',
    price: 145,
    matchKeywords: ['geneca', 'ray', 'spf 50+', 'cream', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 7
  {
    id: 'geneca-ray-sunscreen-spf50plus-cream-50',
    name: 'geneca ray sun screen spf 50+ cream 50 gm',
    genericName: 'Sun protection formula',
    concentration: '50 gm',
    price: 90,
    matchKeywords: ['geneca', 'ray', 'spf 50+', 'cream 50', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 8
  {
    id: 'geneca-ray-sunscreen-spf50plus-lotion-100',
    name: 'geneca ray sun screen spf 50+ lotion 100 ml',
    genericName: 'Sun protection formula',
    concentration: '100 ml',
    price: 145,
    matchKeywords: ['geneca', 'ray', 'spf 50+', 'lotion 100', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 9
  {
    id: 'geneca-ray-sunscreen-spf50plus-lotion-200',
    name: 'geneca ray sun screen spf 50+ lotion 200 ml',
    genericName: 'Sun protection formula',
    concentration: '200 ml',
    price: 220,
    matchKeywords: ['geneca', 'ray', 'spf 50+', 'lotion 200', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 10
  {
    id: 'genica-ray-sunscreen-spf50plus-cream-100',
    name: 'genica ray sun screen spf 50+ cream 100 gm',
    genericName: 'Sun protection formula',
    concentration: '100 gm',
    price: 165,
    matchKeywords: ['genica', 'ray', 'spf 50+', 'cream 100', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 11
  {
    id: 'genica-ray-sunscreen-spf50plus-cream-50',
    name: 'genica ray sun screen spf 50+ cream 50 gm',
    genericName: 'Sun protection formula',
    concentration: '50 gm',
    price: 145,
    matchKeywords: ['genica', 'ray', 'spf 50+', 'cream 50', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 12
  {
    id: 'genica-ray-sunscreen-spf50plus-lotion-100',
    name: 'genica ray sun screen spf 50+ lotion 100 ml',
    genericName: 'Sun protection formula',
    concentration: '100 ml',
    price: 198,
    matchKeywords: ['genica', 'ray', 'spf 50+', 'lotion 100', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 13
  {
    id: 'genica-ray-sunscreen-spf50plus-lotion-200',
    name: 'genica ray sun screen spf 50+ lotion 200 ml',
    genericName: 'Sun protection formula',
    concentration: '200 ml',
    price: 250,
    matchKeywords: ['genica', 'ray', 'spf 50+', 'lotion 200', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 14
  {
    id: 'mash-sun-block-45-spf-lotion-125',
    name: 'mash sun block 45 spf lotion 125 ml',
    genericName: 'Sun protection formula',
    concentration: '125 ml',
    price: 200,
    matchKeywords: ['mash', 'spf 45', 'lotion 125', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 15
  {
    id: 'mash-sun-block-45-spf-lotion-60',
    name: 'mash sun block 45 spf lotion 60ml',
    genericName: 'Sun protection formula',
    concentration: '60 ml',
    price: 150,
    matchKeywords: ['mash', 'spf 45', 'lotion 60', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 16
  {
    id: 'mash-sun-block-95-spf-lotion-60',
    name: 'mash sun block 95 spf lotion 60ml',
    genericName: 'Sun protection formula',
    concentration: '60 ml',
    price: 160,
    matchKeywords: ['mash', 'spf 95', 'lotion 60', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 17
  {
    id: 'u-v-block-sunscreen-cream-75',
    name: 'u.v block sun screen cream 75 gm',
    genericName: 'Benzophenone-3 & Octyl methoxycinnamate & Octyl salicylate & Titanium dioxide',
    concentration: '75 gm',
    price: 225,
    matchKeywords: ['u.v block', 'uv block', 'benzophenone', 'titanium dioxide', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 18
  {
    id: 'uvascreen-sun-block-lotion-spf50plus-60',
    name: 'uvascreen sun block lotion 50+ spf 60 gm',
    genericName: 'Sun protection formula',
    concentration: '60 gm',
    price: 250,
    matchKeywords: ['uvascreen', 'uva screen', 'spf 50+', 'lotion', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 19
  {
    id: 'uvepro-spf50plus-dry-touch-oil-free-cream-50',
    name: 'uvepro spf50+ dry touch oil free cream 50 ml',
    genericName: 'Sun protection formula',
    concentration: '50 ml',
    price: 313,
    matchKeywords: ['uvepro', 'spf 50+', 'dry touch', 'oil free', ...TAGS.sunblock, ...TAGS.oilFree],
    usage: 'واقي شمس كريم (Dry touch) للبشرة الدهنية.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 20
  {
    id: 'bobai-sunscreen-cream-spf80-50',
    name: 'bobai sunscreen cream spf 80 - 50 gm',
    genericName: 'Sun protection formula',
    concentration: '50 gm',
    price: 225,
    matchKeywords: ['bobai', 'sunscreen cream', 'spf 80', ...TAGS.sunblock],
    usage: 'واقي شمس كريم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 21
  {
    id: 'bobai-sunscreen-hydrocare-tinted-gel-spf50-50',
    name: 'bobai sunscreen hydrocare tinted gel spf 50 - 50 gm',
    genericName: 'Sun protection formula',
    concentration: '50 gm',
    price: 295,
    matchKeywords: ['bobai', 'hydrocare', 'tinted gel', 'spf 50', ...TAGS.sunblock, ...TAGS.tinted],
    usage: 'واقي شمس جل ملون.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 22
  {
    id: 'rostevo-sunscreen-lotion-spf50plus',
    name: 'rostevo sunscreen lotion spf 50+',
    genericName: 'Avobenzone & Homosalate & Octisalate & Octocrylene & Oxybenzone',
    concentration: 'Lotion',
    price: 160,
    matchKeywords: ['rostevo', 'روستيفو', 'avobenzone', 'octocrylene', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 23
  {
    id: 'uvepro-spf50plus-milk-200',
    name: 'uvepro spf50+ milk 200 ml',
    genericName: 'Sun protection formula',
    concentration: '200 ml',
    price: 424,
    matchKeywords: ['uvepro', 'milk', 'spf 50+', ...TAGS.sunblock],
    usage: 'واقي شمس (Milk) للجسم.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 24
  {
    id: 'vacation-niacinamide-10-serum-30',
    name: 'vacation niacinamide 10% face serum 30 ml',
    genericName: 'Niacinamide & Collagen',
    concentration: '30 ml',
    price: 475,
    matchKeywords: ['vacation', 'niacinamide 10', 'serum', 'collagen', ...TAGS.sunblock, ...TAGS.skinCare],
    usage: 'سيروم عناية بالبشرة (حسب وصف المنتج).',
    timing: 'مرة يومياً أو حسب الحاجة.',
    category: Category.SKIN_CARE,
    form: 'Solution',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'توضع قطرات قليلة على البشرة حسب تعليمات المنتج.',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 25
  {
    id: 'beesline-whitening-sunfilter-spf50-60',
    name: 'beesline whitening sunfilter spf 50 - 60 ml',
    genericName: 'Sweet almond oil & Vegetable glycerin & Titanium dioxide & Beeswax & Sesame oil',
    concentration: '60 ml',
    price: 375,
    matchKeywords: ['beesline', 'بيزلين', 'sunfilter', 'spf 50', 'titanium dioxide', ...TAGS.sunblock],
    usage: 'واقي شمس/سن فلتر مع مكونات مرطبة.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 26
  {
    id: 'mash-sun-block-95-spf-lotion-125',
    name: 'mash sun block 95 spf lotion 125ml',
    genericName: 'Sun protection formula',
    concentration: '125 ml',
    price: 250,
    matchKeywords: ['mash', 'spf 95', 'lotion 125', ...TAGS.sunblock],
    usage: 'واقي شمس لوشن.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 27
  {
    id: 'uveblock-spf50plus-fluid-light-tinted-40',
    name: 'uveblock spf 50+ fluid light tinted 40ml',
    genericName: 'Sun protection formula',
    concentration: '40 ml',
    price: 299,
    matchKeywords: ['uveblock', 'uve block', 'fluid', 'tinted', 'spf 50+', ...TAGS.sunblock, ...TAGS.tinted],
    usage: 'واقي شمس فلود/لوسيون خفيف ملون.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  // 28
  {
    id: 'uvepro-spf50plus-light-texture-cream-50',
    name: 'uvepro spf50+ light texture cream 50 ml',
    genericName: 'Sun protection formula',
    concentration: '50 ml',
    price: 313,
    matchKeywords: ['uvepro', 'light texture', 'spf 50+', ...TAGS.sunblock],
    usage: 'واقي شمس كريم بقوام خفيف.',
    timing: 'قبل الخروج ويُكرر كل ٢ ساعة',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'قبل الخروج بـ١٥ دقيقة ويُكرر كل ٢ ساعة عند التعرض للشمس',
    warnings: ['للاستخدام الخارجي فقط.']
  }
];

