import { Medication, Category } from '../../../types';

const TAGS = {
  whitening: ['whitening', '#whitening', 'تفتيح', 'تفتيح البشرة', 'depigmenting', 'melasma', 'كلف', 'تصبغات', 'بقع', 'dark spots', 'بقع داكنة', 'hyperpigmentation', 'فرط تصبغ', 'توحيد لون'],
  topical: ['topical', '#topical', 'موضعي'],
  skinCare: ['skin care', '#skin care', 'عناية بالبشرة'],
};

export const WHITENING_MEDS: Medication[] = [
  {
    id: 'meloquin-4-cream-20',
    name: 'meloquin 4% cream 20 gm',
    genericName: 'Hydroquinone',
    concentration: '4%',
    price: 60,
    matchKeywords: ['meloquin', 'ميلوكوين', 'hydroquinone', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/تصبغات (هيدروكينون) يُستخدم على البقع الداكنة فقط حسب التشخيص والمنطقة.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['الحمل: ممنوع استخدامه أثناء الحمل.', 'غير مناسب للأطفال.', 'قد يسبب تهيجاً/جفافاً.', 'لا يُستخدم أكثر من 3–4 أشهر متصلة (خطر تصبغ دائم/ochronosis).', 'أوقفه عند تهيج شديد وأعد التقييم.']
  },
  {
    id: 'melanofree-cream-30',
    name: 'melanofree cream 30 gm',
    genericName: 'Fluocinolone acetonide micronized & Hydroquinone & Tretinoin',
    concentration: '30 gm',
    price: 74,
    matchKeywords: ['melanofree', 'ميلانوفري', 'fluocinolone', 'hydroquinone', 'tretinoin', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم مركب للتصبغات/الكلف يُستخدم على البقع حسب التشخيص والمنطقة.',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['الحمل: ممنوع تماماً (يحتوي تريتينوين—فئة X—خطر تشوهات جنينية).', 'يحتوي هيدروكينون: لا يُستخدم أكثر من 3–4 أشهر متصلة.', 'قد يسبب تهيجاً/تقشر. حساسية ضوئية—استخدم واقي شمس يومياً.']
  },
  {
    id: 'starville-whitening-antiperspirant-rollon-60',
    name: 'starville whitening antiprespirant roll-on 60 ml',
    genericName: 'Glabridin & Kojic acid & Vitamin C & Vitamin E',
    concentration: '60 ml',
    price: 140,
    matchKeywords: ['starville', 'ستارفيل', 'roll-on', 'underarm', 'kojic', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'مضاد تعرق مع مكونات تفتيح للإبط حسب الاستخدام.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.', 'أوقفه عند تهيج شديد.']
  },
  {
    id: 'starville-whitening-night-care-gel-60',
    name: 'starville whitening night care gel 60 gm',
    genericName: 'Glabridin & Kojic acid & Vitamin C & Vitamin E',
    concentration: '60 gm',
    price: 110,
    matchKeywords: ['starville', 'ستارفيل', 'night care', 'kojic', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'جل تفتيح ليلي حسب الاستخدام.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Gel',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً للبشرة الحساسة.']
  },
  {
    id: 'derma-white-cream-30',
    name: 'derma white cream 30 gm',
    genericName: 'Ceteareth-23 & Fatty acids & Licorice & Allantoin & Glycerin',
    concentration: '30 gm',
    price: 90,
    matchKeywords: ['derma white', 'dermawhite', 'licorice', 'العرقسوس', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/ترطيب للمساعدة في توحيد لون البشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'harvy-cream-60',
    name: 'harvy cream 60 gm',
    genericName: 'Kojic acid & Licuorice extract & Royal jelly & Vitamin C & Glycolic acid',
    concentration: '60 gm',
    price: 125,
    matchKeywords: ['harvy', 'هارفي', 'kojic', 'glycolic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح يحتوي على كوجيك/جلايكوليك للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً/تقشر.', 'تجنب حول العينين.']
  },
  {
    id: 'gotal-whitening-lotion-75',
    name: 'gotal whitening lotion 75 ml',
    genericName: 'Kojic acid & Glycerin & Licorice extract & Royal jelly & Vitamin C',
    concentration: '75 ml',
    price: 125,
    matchKeywords: ['gotal', 'جوتال', 'lotion', 'kojic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'لوشن تفتيح/ترطيب للمساعدة في توحيد لون البشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'hiderm-whitening-cream-50',
    name: 'hiderm whitening cream 50 gm',
    genericName: 'Kojic acid & Mulberry & Avobenzone & Vitamin C & Licorice',
    concentration: '50 gm',
    price: 125,
    matchKeywords: ['hiderm', 'هايديرم', 'mulberry', 'avobenzone', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح مع مكونات واقية للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'infinity-whitening-cream-60',
    name: 'infinity whitening cream 60 gm',
    genericName: 'Whitening formula',
    concentration: '60 gm',
    price: 160,
    matchKeywords: ['infinity', 'انفينتي', 'whitening', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'jictyl-cream-50',
    name: 'jictyl cream 50 gm',
    genericName: 'Kojic acid & Licorice extract & Vitamin C',
    concentration: '50 gm',
    price: 139,
    matchKeywords: ['jictyl', 'جيكتيل', 'kojic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً للبشرة الحساسة.']
  },
  {
    id: 'liquovit-cream-50',
    name: 'liquovit cream 50 gm',
    genericName: 'Liquorice extract & Parsley extract & Panthenol & Chamomile',
    concentration: '50 gm',
    price: 180,
    matchKeywords: ['liquovit', 'ليكوفِت', 'panthenol', 'parsley', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/تهدئة للمساعدة في توحيد اللون.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'moon-light-cream-30',
    name: 'moon light cream 30 gm',
    genericName: 'Licuorice extract & Bearberry extract & Parsely extract',
    concentration: '30 gm',
    price: 70,
    matchKeywords: ['moon light', 'moonlight', 'bearberry', 'licorice', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات الخفيفة.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'moon-light-cream-50',
    name: 'moon light cream 50 gm',
    genericName: 'Licuorice extract & Bearberry extract & Parsely extract',
    concentration: '50 gm',
    price: 80,
    matchKeywords: ['moon light 50', 'moonlight 50', 'bearberry', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح (عبوة أكبر) للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'trimelasma-cream-30',
    name: 'trimelasma top. cream 30 gm',
    genericName: 'Fluocinolone & Hydroquinone & Tretinoin',
    concentration: '30 gm',
    price: 59,
    matchKeywords: ['trimelasma', 'تريميلازما', 'fluocinolone', 'hydroquinone', 'tretinoin', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم مركب للتصبغات/الكلف يُستخدم على البقع حسب التشخيص والمنطقة.',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['غير مناسب أثناء الحمل.', 'قد يسبب تهيجاً/تقشر.']
  },
  {
    id: 'ultra-fair-cream-50',
    name: 'ultra fair cream 50 gm',
    genericName: 'Liquorice extract & Panthenol & Vitamin C & Vitamin E & Bearberry',
    concentration: '50 gm',
    price: 55,
    matchKeywords: ['ultra fair', 'التر فير', 'bearberry', 'panthenol', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/ترطيب للمساعدة في توحيد لون البشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'v-walla-cream-50',
    name: 'v walla cream 50 gm',
    genericName: 'Titanium dioxide & Liquorice & Lactic acid & Paraffin oil & Vitamin C',
    concentration: '50 gm',
    price: 129,
    matchKeywords: ['v walla', 'vwalla', 'titanium dioxide', 'lactic acid', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح مع مكونات واقية/مرطبة للمساعدة في توحيد اللون.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['قد يسبب تهيجاً للبشرة الحساسة.']
  },
  {
    id: 'ventamor-cream-60',
    name: 'ventamor cream 60 gm',
    genericName: 'Kojic acid & Licuorice extract & Royal jelly & Vitamin C & Glycolic acid',
    concentration: '60 gm',
    price: 175,
    matchKeywords: ['ventamor', 'فنتامور', 'kojic', 'glycolic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً/تقشر.']
  },
  {
    id: 'white-touch-cream-60',
    name: 'white touch cream 60 ml',
    genericName: 'Vitamin C & Vitamin E & Titanium dioxide & Licuorice & Stearic acid',
    concentration: '60 ml',
    price: 40,
    matchKeywords: ['white touch', 'وايت تاتش', 'vitamin c', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/حماية للمساعدة في توحيد لون البشرة.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'daky-sensitive-whitening-cream-50',
    name: 'daky sensitive whitening cream 50 gm',
    genericName: 'Licorice & Stearic acid & Vitamin C & Kojic acid & Marine collagen',
    concentration: '50 gm',
    price: 250,
    matchKeywords: ['daky', 'داكي', 'sensitive', 'kojic', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح للبشرة الحساسة للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً للبشرة الحساسة.']
  },
  {
    id: 'harvy-lotion-spray-120',
    name: 'harvy lotion spray 120 ml',
    genericName: 'Kojic acid & Licuorice extract & Vitamin C & Glycolic acid & Tea tree oil',
    concentration: '120 ml',
    price: 175,
    matchKeywords: ['harvy spray', 'هارفي سبراي', 'tea tree', 'kojic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'سبراي/لوشن تفتيح للجسم للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Spray',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً بسبب الأحماض.']
  },
  {
    id: 'lucocid-r-3-ointment-30',
    name: 'lucocid-r 3% oint. 30 gm',
    genericName: 'Retinoic acid & Hydroquinone',
    concentration: '3%',
    price: 31,
    matchKeywords: ['lucocid-r', 'لوكو سيد', 'retinoic', 'hydroquinone', ...TAGS.whitening, ...TAGS.topical],
    usage: 'مرهم للتصبغات يحتوي ريتينويد + هيدروكينون يُستخدم على البقع حسب التشخيص والمنطقة.',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.DERMA_CARE,
    form: 'Ointment',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['غير مناسب أثناء الحمل.', 'قد يسبب تهيجاً شديداً للبشرة الحساسة.']
  },
  {
    id: 'lunner-cream-50',
    name: 'lunner cream 50 gm',
    genericName: 'Glycerin & Titanium dioxide & Licorice extract',
    concentration: '50 gm',
    price: 90,
    matchKeywords: ['lunner', 'لونر', 'titanium dioxide', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/حماية للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'greenix-spotless-cream',
    name: 'greenix spotless cream',
    genericName: 'Panthenol',
    concentration: 'Cream',
    price: 50,
    matchKeywords: ['greenix', 'جرينكس', 'spotless', 'panthenol', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم موضعي للمساعدة في آثار البقع/تهدئة البشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'daky-night-whitening-cream-50',
    name: 'daky night whitening cream 50 gm',
    genericName: 'Kojic acid & Licorice & Honey & Vitamins C & Vitamins A & Vitamin E',
    concentration: '50 gm',
    price: 275,
    matchKeywords: ['daky night', 'داكي نايت', 'kojic', 'night', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح ليلي للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً.']
  },
  {
    id: 'elega-skin-lotion-120',
    name: 'elega skin lotion 120 ml',
    genericName: 'Kojic acid & Licorice & Mulberry & Titanium dioxide & Zinc oxide',
    concentration: '120 ml',
    price: 195,
    matchKeywords: ['elega', 'اليجا', 'mulberry', 'zinc oxide', ...TAGS.whitening, ...TAGS.topical],
    usage: 'لوشن تفتيح/حماية للمساعدة في توحيد اللون.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'keepaco-whitening-cream-60',
    name: 'keepaco whitening cream 60 gm',
    genericName: 'Kojic acid & Glycolic acid & Vitamin C & Vitamin E & Calendula',
    concentration: '60 gm',
    price: 120,
    matchKeywords: ['keepaco', 'كيباكو', 'kojic', 'glycolic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً.']
  },
  {
    id: 'romix-cream-60',
    name: 'romix cream 60 gm',
    genericName: 'Amino acids & Soya protein & Lecithin & Retinol & Tocopherol',
    concentration: '60 gm',
    price: 185,
    matchKeywords: ['romix', 'روميكس', 'retinol', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/عناية للمساعدة في توحيد اللون وتحسين مظهر البشرة.',
    timing: 'ليلاً – ٤–٦ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'نقطة على الحبوب ليلاً لمدة ٤–٦ أسابيع',
    warnings: ['قد يسبب تهيجاً/جفافاً.']
  },
  {
    id: 'sens-light-soap-100',
    name: 'sens light soap 100 gm',
    genericName: 'Salicylic acid & Liquorice ext. & Vitamin C & Vitamin E',
    concentration: '100 gm',
    price: 55,
    matchKeywords: ['sens light', 'سنس لايت', 'soap', 'salicylic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'صابونة/غسول للمساعدة في تنظيف البشرة وتوحيد اللون.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['قد يسبب جفافاً للبشرة الحساسة.']
  },
  {
    id: 'white-sat-cream-50',
    name: 'white sat cream 50 gm',
    genericName: 'Liquorice & Benzophenone 3 & Aloe vera & Germben & Chamomile',
    concentration: '50 gm',
    price: 39.95,
    matchKeywords: ['white sat', 'وايت سات', 'benzophenone', 'aloe vera', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/حماية خفيفة للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'white-shadow-cream-25',
    name: 'white shadow cream 25 gm',
    genericName: 'Melfade & Natural thymic peptides & Glycosomes & Copper',
    concentration: '25 gm',
    price: 50,
    matchKeywords: ['white shadow 25', 'وايت شادو 25', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/تصبغات للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'melanofree-soap-100',
    name: 'melanofree soap 100 gm',
    genericName: 'Aloe vera & Shea butter & Kojic acid & Mulberry extract & Vitamin C',
    concentration: '100 gm',
    price: 70,
    matchKeywords: ['melanofree soap', 'ميلانوفري صابون', 'kojic', 'mulberry', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'صابونة/غسول تفتيح للمساعدة في توحيد لون البشرة.',
    timing: 'مرة–مرتين يومياً',
    category: Category.SKIN_CARE,
    form: 'Cleanser',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['قد يسبب جفافاً للبشرة الحساسة.']
  },
  {
    id: 'moonshine-whitening-lotion-drops-30',
    name: 'moonshine whitening lotion drops 30 ml',
    genericName: 'Collagen & Vitamin C',
    concentration: '30 ml',
    price: 179,
    matchKeywords: ['moonshine', 'مون شاين', 'drops', 'collagen', ...TAGS.whitening, ...TAGS.topical],
    usage: 'قطرات/سيروم تفتيح للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Solution',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'gleam-mix-whitening-cream-50',
    name: 'gleam mix whitening cream 50 gm',
    genericName: 'Kojic acid & Titanium dioxide & Alpha arbutin',
    concentration: '50 gm',
    price: 150,
    matchKeywords: ['gleam mix', 'جليم ميكس', 'alpha arbutin', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح (ألفا أربوتين/كوجيك) للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً.']
  },
  {
    id: 'oria-whitening-cream-50',
    name: 'oria whitening cream 50 gm',
    genericName: 'Kojic acid & Licorice extract & Vitamin C & Glycolic acid & Vitamin B5',
    concentration: '50 gm',
    price: 240,
    matchKeywords: ['oria', 'اوريا', 'glycolic', 'vitamin b5', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً/تقشر.']
  },
  {
    id: 'rostevo-whitening-cream-50',
    name: 'rostevo whitening cream 50 gm',
    genericName: 'Licorice extract & Kojic acid & Zinc oxide & Titanium dioxide',
    concentration: '50 gm',
    price: 125,
    matchKeywords: ['rostevo', 'روستيفو', 'zinc oxide', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/حماية للمساعدة في توحيد اللون.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'vacation-whitening-cream-60',
    name: 'vacation whitening cream 60ml',
    genericName: 'Natriance brightener & Alpha-arbutin & Kojic acid',
    concentration: '60 ml',
    price: 175,
    matchKeywords: ['vacation', 'فكيشن', 'alpha arbutin', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً.']
  },
  {
    id: 'tyromax-cream-50',
    name: 'tyromax cream 50 gm',
    genericName: 'Tyrosine & Vitamin A & Vitamin E & Panthenol & Trithanolamine',
    concentration: '50 gm',
    price: 178,
    matchKeywords: ['tyromax', 'تيرومكس', 'tyrosine', 'panthenol', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم عناية/تفتيح للمساعدة في توحيد لون البشرة.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'melanofree-lotion-200',
    name: 'melanofree lotion 200 ml',
    genericName: 'Alpha arbutin & Collagen & Hyaluronic acid',
    concentration: '200 ml',
    price: 185,
    matchKeywords: ['melanofree lotion', 'ميلانوفري لوشن', 'alpha arbutin', 'hyaluronic', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'لوشن تفتيح/ترطيب للجسم للمساعدة في توحيد اللون.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Lotion',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'on-target-cream-50',
    name: 'on target cream 50 gm',
    genericName: 'Glycolic acid & Alpha-arbutin & Kojic acid & Licorice extract',
    concentration: '50 gm',
    price: 120,
    matchKeywords: ['on target', 'اون تارجت', 'glycolic', 'alpha arbutin', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح يحتوي على أحماض/أربوتين للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً/تقشر.']
  },
  {
    id: 'orgalight-cream-50',
    name: 'orgalight cream 50gm',
    genericName: 'Whitening formula',
    concentration: '50 gm',
    price: 60,
    matchKeywords: ['orgalight', 'اورجالايت', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'proyan-cream-50',
    name: 'proyan 50 gm cream',
    genericName: 'Skin care cream',
    concentration: '50 gm',
    price: 120,
    matchKeywords: ['proyan', 'برويان', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم عناية/تفتيح للمساعدة في توحيد لون البشرة.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'sector-whitening-cream-50',
    name: 'sector whitening cream 50 gm',
    genericName: 'Kojic acid & Glycolic acid & Licorice & Vitamin C & Vitamin E',
    concentration: '50 gm',
    price: 155,
    matchKeywords: ['sector', 'سيكتور', 'kojic', 'glycolic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً/تقشر.']
  },
  {
    id: 'sens-light-whitening-cream-60',
    name: 'sens light whitening cream 60 gm',
    genericName: 'Bearberry ext & Liquorice ext & Vitamin C & Vitamin E',
    concentration: '60 gm',
    price: 140,
    matchKeywords: ['sens light cream', 'سنس لايت كريم', 'bearberry', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'ultra-fair-cream-15',
    name: 'ultra fair cream 15 gm',
    genericName: 'Liquorice extract & Panthenol & Vitamin C & Vitamin E & Bearberry',
    concentration: '15 gm',
    price: 25,
    matchKeywords: ['ultra fair 15', 'التر فير 15', 'bearberry', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح (عبوة صغيرة).',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'white-shadow-cream-40',
    name: 'white shadow cream 40 gm',
    genericName: 'Octyl dodecanol & Titanium dioxide & Vitamin E & Kojic acid',
    concentration: '40 gm',
    price: 75,
    matchKeywords: ['white shadow 40', 'وايت شادو 40', 'kojic', ...TAGS.whitening, ...TAGS.topical],
    usage: 'كريم تفتيح/حماية للمساعدة في توحيد اللون.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'drakon-lifting-whitening-cream-50',
    name: 'drakon lifting whitening cream 50 gm',
    genericName: 'Liquorice & Arbutin & Kojic acid & Vitamin C & Caffeine & Hyaluronic acid',
    concentration: '50 gm',
    price: 185,
    matchKeywords: ['drakon lifting', 'دراكون ليفتينج', 'arbutin', 'caffeine', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح/شد للمساعدة في توحيد اللون وتحسين المظهر.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً للبشرة الحساسة.']
  },
  {
    id: 'drakon-senso-whitening-cream-50',
    name: 'drakon senso whitening cream 50 gm',
    genericName: 'Liquorice & Arbutin & Kojic acid & Vitamin C & Melon extract',
    concentration: '50 gm',
    price: 220,
    matchKeywords: ['drakon senso', 'دراكون سينسو', 'melon extract', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح للبشرة الحساسة للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً.']
  },
  {
    id: 'drakon-underarm-whitening-cream-50',
    name: 'drakon under-arm whitening cream 50 gm',
    genericName: 'Liquorice & Arbutin & Kojic acid & Vitamin C & Melon extract',
    concentration: '50 gm',
    price: 180,
    matchKeywords: ['drakon underarm', 'دراكون اندرام', 'under-arm', 'arbutin', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح للإبط للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'excellent-white-cream-80',
    name: 'excellent white cream 80 gm',
    genericName: 'Kojic acid & Licorice extract & Vitamin C & Collagen marine',
    concentration: '80 gm',
    price: 100,
    matchKeywords: ['excellent white', 'اكسيلنت وايت', 'kojic', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً.']
  },
  {
    id: 'kojicnal-whitening-cream-50',
    name: 'kojicnal whitening cream 50 gm',
    genericName: 'Panthenol & Kojic acid & Wheat germ oil & Chamomile & Liquorice',
    concentration: '50 gm',
    price: 100,
    matchKeywords: ['kojicnal', 'كوجيك نال', 'wheat germ', 'panthenol', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'كريم تفتيح/تهدئة للمساعدة في التصبغات.',
    timing: '١–٢ مرة يومياً',
    category: Category.SKIN_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: () => 'يُوضع على البشرة ١–٢ مرة يومياً',
    warnings: ['للاستخدام الخارجي فقط.']
  },
  {
    id: 'moon-shine-drops-lotion-30',
    name: 'moon shine drops lotion 30ml',
    genericName: 'Collagen & Vitamin C & Lactic acid & Glycolic acid & Kojic acid',
    concentration: '30 ml',
    price: 179,
    matchKeywords: ['moon shine', 'مون شاين', 'drops', 'glycolic', 'kojic', ...TAGS.whitening, ...TAGS.topical, ...TAGS.skinCare],
    usage: 'قطرات/سيروم تفتيح يحتوي على أحماض للمساعدة في التصبغات.',
    timing: 'مرة ليلاً – ٤–٨ أسابيع',
    category: Category.SKIN_CARE,
    form: 'Solution',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'طبقة رقيقة على المنطقة المصابة ٢ مرات يومياً لمدة ٢–٤ أسابيع',
    warnings: ['قد يسبب تهيجاً/لسعاً.']
  }
];

