
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;

const tag = (...tags: string[]) => tags;

const commonParacetamolWarnings = [
	'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
	'مرضى الكبد/الكحول: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
	'يفضل بعد الأكل لتقليل تهيج المعدة.',
	'لا تجمع أكثر من NSAID في نفس الوقت.',
	'يُتجنب مع قرحة/نزيف معدي أو فشل كلوي شديد، وأواخر الحمل.',
];

export const ANALGESICS_3: Medication[] = [
	// 94
	{
		id: 'declophen-diclofenac-sodium-100mg-supp-5-a3',
		name: 'declophen 100mg 5 supp',
		genericName: 'diclofenac sodium',
		concentration: '100mg',
		price: 21,
		matchKeywords: ['declophen 100 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٠٠ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى لبوستين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 95
	{
		id: 'diclac-diclofenac-sodium-75mg-id-prolonged-tabs-20-a3',
		name: 'diclac 75 id 20 prolonged tabs.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 90,
		matchKeywords: ['diclac 75 id 20', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 96
	{
		id: 'diclac-diclofenac-sodium-75mg-3ml-amps-5-a3',
		name: 'diclac 75 mg/3ml 5 amps.',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 55,
		matchKeywords: ['diclac amp 5', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (حقن).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 97
	{
		id: 'divido-diclofenac-sodium-75mg-dual-release-caps-30-a3',
		name: 'divido 75mg 30 dual release caps.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 141,
		matchKeywords: ['divido 75', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (تحرر مزدوج/معدل).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Modified-release Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى كبسولة/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 98
	{
		id: 'dolphin-diclofenac-sodium-25mg-supp-10-a3',
		name: 'dolphin 25 mg 10 supp.',
		genericName: 'diclofenac sodium',
		concentration: '25 mg',
		price: 38,
		matchKeywords: ['dolphin 25 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 180,
		minWeight: 15,
		maxWeight: 60,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٢٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 99
	{
		id: 'dolphin-k-diclofenac-potassium-75mg-supp-5-a3',
		name: 'dolphin k 75mg 5 supp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg',
		price: 21,
		matchKeywords: ['dolphin k 75 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٧٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 100
	{
		id: 'dolphin-k-diclofenac-potassium-75mg-sr-caps-20-a3',
		name: 'dolphin k 75mg s.r. 20 caps.',
		genericName: 'diclofenac potassium',
		concentration: '75mg',
		price: 64,
		matchKeywords: ['dolphin k 75 sr', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (ممتد المفعول).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'S.R. Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى كبسولة/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 101
	{
		id: 'ezacard-aspirin-100mg-ec-tabs-30-a3',
		name: 'ezacard 100 mg 30 e.c. tabs.',
		genericName: 'acetylsalicylic acid',
		concentration: '100 mg',
		price: 51,
		matchKeywords: ['ezacard 100', ...tag('#nsaid', '#salicylate')],
		usage: 'أسبرين منخفض الجرعة (غالباً للوقاية القلبية/مضاد صفائح).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'E.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٠٠ مجم) مرة يومياً.',
		warnings: ['يزيد خطر النزيف/قرحة المعدة.'],
	},

	// 102
	{
		id: 'feldene-piroxicam-20mg-ml-im-amp-3-a3',
		name: 'feldene 20mg/ml i.m. 3 amp.',
		genericName: 'piroxicam',
		concentration: '20mg/ml',
		price: 45,
		matchKeywords: ['feldene amp', ...tag('#nsaid', '#oxicam')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد بالعضل مرة يومياً ولمدة قصيرة (حد أقصى أمبول/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 103
	{
		id: 'flector-diclofenac-epolamine-50mg-caps-30-a3',
		name: 'flector 50mg 30 caps',
		genericName: 'diclofenac epolamine',
		concentration: '50mg',
		price: 87,
		matchKeywords: ['flector 50 caps', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (ديكلوفيناك).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٥٠ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى كبسولتين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 104
	{
		id: 'flector-diclofenac-epolamine-diclofenac-sodium-50mg-granules-sachets-9-a3',
		name: 'flector 50mg 9 granules in sachets',
		genericName: 'diclofenac epolamine & diclofenac sodium',
		concentration: '50mg',
		price: 22,
		matchKeywords: ['flector sachets', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (أكياس).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كيس واحد (٥٠ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى كيسين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 105
	{
		id: 'flotac-diclofenac-sodium-75mg-caps-20-a3',
		name: 'flotac 75mg 20 caps.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 90,
		matchKeywords: ['flotac 75', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (ديكلوفيناك).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى كبسولة/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 106
	{
		id: 'flurest-n-tabs-20-a3',
		name: 'flurest n 20 tabs',
		genericName: 'paracetamol & phenylephrine hydrochloride & chlorpheniramine maleate',
		concentration: 'Tablets',
		price: 32,
		matchKeywords: ['flurest n', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان (خافض حرارة + مزيل احتقان + مضاد حساسية).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144 ? 'لا يستخدم للأطفال أقل من ١٢ سنة.' : '١ قرص كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة). تجنب الجرعات المسائية لو سبب أرق.',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 107
	{
		id: 'panadol-acute-head-cold-fc-tabs-20-a3',
		name: 'panadol acute head cold 20 f.c.tabs.',
		genericName: 'paracetamol & brompheniramine maleate & pseudoephedrine',
		concentration: 'F.C. Tablets',
		price: 62,
		matchKeywords: ['panadol acute head cold', ...tag('#common cold')],
		usage: 'أعراض نزلات البرد/الاحتقان.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يفضل استخدامه للأطفال أقل من ١٢ سنة.'
				: '١–٢ قرص كل ٤–٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة). لا تستخدمه أكثر من ٣ أيام للحرارة أو ٥ أيام للألم دون إعادة تقييم.',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 108
	{
		id: 'xyrkux-etoricoxib-120mg-tabs-7-a3',
		name: 'xyrkux 120 mg 7 tabs',
		genericName: 'etoricoxib',
		concentration: '120 mg',
		price: 88,
		matchKeywords: ['xyrkux 120', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٢٠ مجم) مرة يومياً بعد الأكل ولمدة قصيرة (حد أقصى قرص واحد/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 109
	{
		id: 'rumaximap-etoricoxib-90mg-fc-tabs-30-a3',
		name: 'rumaximap 90mg 30 f.c. tab',
		genericName: 'etoricoxib',
		concentration: '90mg',
		price: 156,
		matchKeywords: ['rumaximap 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 110
	{
		id: 'lornoxicam-8mg-2ml-vial-im-iv-a3',
		name: 'lornoxicam 8mg/2ml vial for i.m./i.v. inj.',
		genericName: 'lornoxicam',
		concentration: '8mg/2ml',
		price: 32,
		matchKeywords: ['lornoxicam vial', ...tag('#nsaid', '#oxicam')],
		usage: 'حقنة مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) =>
			'فيال واحد (٨ مجم) بالعضل أو بالوريد. يمكن تكراره مرة واحدة بعد ١٢ ساعة عند الحاجة (حد أقصى ١٦ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 111
	{
		id: 'lornoxicam-8mg-fc-tabs-20-a3',
		name: 'lornoxicam 8mg 20 f.c.tab',
		genericName: 'lornoxicam',
		concentration: '8mg',
		price: 72,
		matchKeywords: ['lornoxicam 8', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٨ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى قرصين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 112
	{
		id: 'mobitil-meloxicam-15mg-tabs-10-a3',
		name: 'mobitil 15mg 10 tab.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 36,
		matchKeywords: ['mobitil 15 tab', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 113
	{
		id: 'mobitil-meloxicam-15mg-supp-6-a3',
		name: 'mobitil 15mg 6 supp.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 26,
		matchKeywords: ['mobitil supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٥ مجم) مرة يومياً بعد الأكل/قبل النوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 114
	{
		id: 'novalgin-oblong-metamizole-500mg-fc-tab-10-a3',
		name: 'novalgin oblong 500mg 10 f.c. tab.',
		genericName: 'metamizole sodium',
		concentration: '500mg',
		price: 20,
		matchKeywords: ['novalgin oblong', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة (ميتاميزول).',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [
			'قد يسبب حساسية نادرة وشديدة: توقف فوراً عند طفح/تورم/ضيق تنفس.',
			'إذا استمرت الحمى/الألم أكثر من ٣ أيام أو تكررت الأعراض، أعد التقييم.',
		],
	},

	// 115
	{
		id: 'olfen-diclofenac-sodium-100mg-sr-depocaps-10-a3',
		name: 'olfen 100mg s.r. 10 depocaps.',
		genericName: 'diclofenac sodium',
		concentration: '100mg',
		price: 36,
		matchKeywords: ['olfen 100 sr', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'S.R. Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (١٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 116
	{
		id: 'panadol-joint-paracetamol-er-tabs-18-a3',
		name: 'panadol joint 18 er tabs.',
		genericName: 'paracetamol',
		concentration: 'ER Tablets',
		price: 28.88,
		matchKeywords: ['panadol joint 18', ...tag('#antipyretics')],
		usage: 'باراسيتامول ممتد المفعول لتسكين الآلام.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) =>
			'قرص واحد كل ٨ ساعات عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة). لا تجمعه مع أي منتج باراسيتامول آخر.',
		warnings: [...commonParacetamolWarnings],
	},

	// 117
	{
		id: 'averocoxib-etoricoxib-90mg-fc-tabs-20-a3',
		name: 'averocoxib 90 mg 20 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 228,
		matchKeywords: ['averocoxib 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 118
	{
		id: 'spasmopyralgin-m-camylofin-analgin-tabs-10-a3',
		name: 'spasmopyralgin-m 10 tabs.',
		genericName: 'camylofin & analgin',
		concentration: 'Tablets',
		price: 21,
		matchKeywords: ['spasmopyralgin', ...tag('#antispasmodics')],
		usage: 'مضاد تقلصات + مسكن (مغص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANTISPASMODIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد حتى ٣ مرات يومياً بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/اليوم).',
		warnings: ['الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.'],
	},

	// 119
	{
		id: 'trimed-flu-loratadine-paracetamol-pseudoephedrine-fc-tabs-20-a3',
		name: 'trimed flu 20 f.c. tabs.',
		genericName: 'loratadine & paracetamol & pseudoephedrine',
		concentration: 'F.C. Tablets',
		price: 58,
		matchKeywords: ['trimed flu', ...tag('#common cold')],
		usage: 'أعراض البرد/الجيوب (مضاد حساسية + باراسيتامول + مزيل احتقان).',
		timing: 'كل ١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144 ? 'لا يستخدم للأطفال أقل من ١٢ سنة.' : 'قرص واحد مرتين يومياً (كل ١٢ ساعة) بحد أقصى قرصين في اليوم.',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 120
	{
		id: 'xyrkux-etoricoxib-90mg-tabs-30-a3',
		name: 'xyrkux 90 mg 30 tabs',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 297,
		matchKeywords: ['xyrkux 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 121
	{
		id: 'zacaglone-diclofenac-sodium-75mg-3ml-amp-3-im-a3',
		name: 'zacaglone 75mg/3ml 3 amp. for i.m. injection',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 45,
		matchKeywords: ['zacaglone amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 122
	{
		id: 'anselacox-etoricoxib-60mg-fc-tabs-30-a3',
		name: 'anselacox 60mg 30 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '60mg',
		price: 222,
		matchKeywords: ['anselacox 60', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 123
	{
		id: 'anselacox-etoricoxib-90mg-fc-tabs-30-a3',
		name: 'anselacox 90mg 30 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '90mg',
		price: 315,
		matchKeywords: ['anselacox 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 124
	{
		id: 'adwiflam-diclofenac-potassium-75mg-supp-5-a3',
		name: 'adwiflam 75mg 5 supp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg',
		price: 20,
		matchKeywords: ['adwiflam supp 75', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٧٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 125
	{
		id: 'rumaximap-etoricoxib-60mg-fc-tabs-30-a3',
		name: 'rumaximap 60mg 30 f.c. tab',
		genericName: 'etoricoxib',
		concentration: '60mg',
		price: 147,
		matchKeywords: ['rumaximap 60', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 126
	{
		id: 'anti-cox-ii-meloxicam-15mg-tabs-20-a3',
		name: 'anti-cox ii 15mg 20 tab',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 36,
		matchKeywords: ['anti-cox ii 15 tab', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 127
	{
		id: 'arcoxia-etoricoxib-90mg-fc-tabs-14-a3',
		name: 'arcoxia 90 mg 14 f.c. tabs',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 239,
		matchKeywords: ['arcoxia 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2 (أركوكسيا).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 128
	{
		id: 'aspricarlo-aspirin-81mg-chewable-tabs-30-a3',
		name: 'aspricarlo 81mg 30 chewable tabs.',
		genericName: 'acetylsalicylic acid',
		concentration: '81mg',
		price: 45,
		matchKeywords: ['aspricarlo 81', ...tag('#nsaid', '#salicylate')],
		usage: 'أسبرين منخفض الجرعة (غالباً للوقاية القلبية/مضاد صفائح).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٨١ مجم) مرة يومياً.',
		warnings: ['يزيد خطر النزيف/قرحة المعدة.'],
	},

	// 129
	{
		id: 'cetal-paracetamol-microfined-250mg-5ml-susp-60ml-a3',
		name: 'cetal 250mg/5ml 60ml susp',
		genericName: 'paracetamol microfined',
		concentration: '250mg/5ml',
		price: 31,
		matchKeywords: ['cetal susp', ...tag('#antipyretics')],
		usage: 'خافض حرارة ومسكن للأطفال.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Suspension',
		minAgeMonths: 2,
		maxAgeMonths: 144,
		minWeight: 4,
		maxWeight: 45,
		calculationRule: (weight: number, _a: number) => {
			const ml = roundVol((weight * 15) / 50);
			return `${toAr(ml)} مل كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
		},
		warnings: [...commonParacetamolWarnings],
	},

	// 130
	{
		id: 'cold-free-tabs-20-a3',
		name: 'cold free 20 tab.',
		genericName: 'chlorpheniramine & paracetamol & pseudoephedrine',
		concentration: 'Tablets',
		price: 50,
		matchKeywords: ['cold free', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يفضل استخدامه للأطفال أقل من ١٢ سنة.'
				: 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة). لا تجمعه مع أي دواء برد/مسكن آخر يحتوي على باراسيتامول.',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 131
	{
		id: 'coldatrexy-fc-tabs-30-a3',
		name: 'coldatrexy 30 f.c. tabs.',
		genericName: 'paracetamol & chlorpheniramine maleate & pseudoephedrine',
		concentration: 'F.C. Tablets',
		price: 63,
		matchKeywords: ['coldatrexy', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يفضل استخدامه للأطفال أقل من ١٢ سنة.'
				: 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 132
	{
		id: 'diclac-diclofenac-sodium-75mg-3ml-amps-6-a3',
		name: 'diclac 75 mg/3ml 6 amps.',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 66,
		matchKeywords: ['diclac amp 6', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 133
	{
		id: 'diclac-diclofenac-sodium-75mg-id-prolonged-tabs-30-a3',
		name: 'diclac 75 id 30 prolonged tabs.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 135,
		matchKeywords: ['diclac 75 id 30', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 134
	{
		id: 'dolphin-diclofenac-sodium-12-5mg-supp-10-a3',
		name: 'dolphin 12.5mg 10 supp',
		genericName: 'diclofenac sodium',
		concentration: '12.5mg',
		price: 36,
		matchKeywords: ['dolphin 12.5 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك للأطفال (مسكن/مضاد التهاب).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 120,
		minWeight: 10,
		maxWeight: 30,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٢.٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 135
	{
		id: 'dolphin-k-diclofenac-potassium-25mg-fc-tab-20-a3',
		name: 'dolphin k 25mg 20 f.c. tab',
		genericName: 'diclofenac potassium',
		concentration: '25mg',
		price: 34,
		matchKeywords: ['dolphin k 25', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'F.C. Tablets',
		minAgeMonths: 120,
		maxAgeMonths: 1200,
		minWeight: 25,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٥ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 136
	{
		id: 'dolphin-k-diclofenac-potassium-75mg-3ml-im-amp-3-a3',
		name: 'dolphin k 75mg/3ml i.m. 3 amp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg/3ml',
		price: 24,
		matchKeywords: ['dolphin k amp 3', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 137
	{
		id: 'dolphin-k-diclofenac-potassium-75mg-3ml-im-amp-6-a3',
		name: 'dolphin k 75mg/3ml i.m. 6 amp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg/3ml',
		price: 48,
		matchKeywords: ['dolphin k amp 6', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 138
	{
		id: 'gc-mol-guaifenesin-paracetamol-vitc-eff-sachets-6-a3',
		name: 'g.c. mol 6 eff. sachet',
		genericName: 'paracetamol + guaifenesin + phenylephrine HCl',
		concentration: '325mg + 100mg + 5mg',
		price: 25,
		matchKeywords: ['g.c. mol', ...tag('#common cold')],
		usage: 'فوار لأعراض البرد/الإنفلونزا مع احتقان الأنف وتسهيل طرد البلغم.',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) => {
			if (ageMonths < 144) return 'لا يفضل استخدامه للأطفال أقل من ١٢ سنة.';
			return 'كيس واحد كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أكياس/٢٤ ساعة).';
		},
		warnings: [
			...commonParacetamolWarnings,
			'تداخلات: ممنوع مع مثبطات MAO خلال ١٤ يوم. الحذر مع أدوية القلب/الضغط (مزيل الاحتقان).',
		],
	},

	// 139
	{
		id: 'ketoprek-ketoprofen-1mg-ml-syrup-125ml-a3',
		name: 'ketoprek 1mg/ml syrup 125 ml',
		genericName: 'ketoprofen',
		concentration: '1mg/ml',
		price: 27,
		matchKeywords: ['ketoprek syrup', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID) للأطفال.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Syrup',
		minAgeMonths: 24,
		maxAgeMonths: 180,
		minWeight: 10,
		maxWeight: 60,
		calculationRule: (weight: number, _a: number) => {
			const doseMl = Math.min(roundVol(weight * 0.5), 10);
			const dailyMaxMl = Math.min(roundVol(weight * 1.5), 30);
			return `${toAr(doseMl)} مل كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ${toAr(dailyMaxMl)} مل/٢٤ ساعة).`;
		},
		warnings: [...commonNsaidWarnings],
	},

	// 140
	{
		id: 'ketoprek-ketoprofen-75mg-caps-20-a3',
		name: 'ketoprek 75 mg 20 caps.',
		genericName: 'ketoprofen',
		concentration: '75 mg',
		price: 36,
		matchKeywords: ['ketoprek 75', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٧٥ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى كبسولتين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 141
	{
		id: 'mobitil-meloxicam-15mg-1-5ml-amp-3-a3',
		name: 'mobitil 15mg/1.5ml 3 amp.',
		genericName: 'meloxicam',
		concentration: '15mg/1.5ml',
		price: 39,
		matchKeywords: ['mobitil amp', ...tag('#nsaid', '#oxicam')],
		usage: 'ميلوكسيكام حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (١٥ مجم) مرة يومياً. لا تتجاوز أمبول/اليوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 142
	{
		id: 'novalgin-metamizole-500mg-tabs-100-a3',
		name: 'novalgin 500mg 100 tab.',
		genericName: 'metamizole sodium',
		concentration: '500mg',
		price: 31.5,
		matchKeywords: ['novalgin 100', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة (ميتاميزول).',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [
			'قد يسبب حساسية نادرة وشديدة: توقف فوراً عند طفح/تورم/ضيق تنفس.',
			'إذا استمرت الحمى/الألم أكثر من ٣ أيام أو تكررت الأعراض، أعد التقييم.',
		],
	},

	// 144
	{
		id: 'olfen-diclofenac-potassium-sodium-75mg-da-depocaps-10-a3',
		name: 'olfen 75mg d.a. 10 depocaps.',
		genericName: 'diclofenac potassium & diclofenac sodium',
		concentration: '75mg',
		price: 21,
		matchKeywords: ['olfen 75 da', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (ديكلوفيناك).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'S.R. Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى كبسولة/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 145
	{
		id: 'panadol-joint-paracetamol-er-tabs-24-a3',
		name: 'panadol joint 24 er tabs.',
		genericName: 'paracetamol',
		concentration: 'ER Tablets',
		price: 67,
		matchKeywords: ['panadol joint 24', ...tag('#antipyretics')],
		usage: 'باراسيتامول ممتد المفعول لتسكين الآلام.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) =>
			'قرص واحد كل ٨ ساعات عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة). لا تجمعه مع أي منتج باراسيتامول آخر.',
		warnings: [...commonParacetamolWarnings],
	},

	// 146
	{
		id: 'panadol-sinus-relief-pe-paracetamol-phenylephrine-tabs-24-a3',
		name: 'panadol sinus relief pe 24 tablets',
		genericName: 'paracetamol & phenylephrine hydrochloride',
		concentration: 'Tablets',
		price: 39,
		matchKeywords: ['panadol sinus relief', ...tag('#common cold')],
		usage: 'أعراض الجيوب/الاحتقان مع ألم/حرارة.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يفضل استخدامه للأطفال أقل من ١٢ سنة.'
				: '١–٢ قرص كل ٤–٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'فينيل إفرين قد يرفع الضغط/يزيد خفقان.'],
	},

	// 147
	{
		id: 'power-cold-flu-tabs-20-a3',
		name: 'power cold & flu 20 tab.',
		genericName: 'caffeine anhydrous & chlorpheniramine maleate & pseudoephedrine',
		concentration: 'Tablets',
		price: 42,
		matchKeywords: ['power cold & flu', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يستخدم للأطفال أقل من ١٢ سنة.'
				: 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٦ أقراص/٢٤ ساعة). تجنب جرعات المساء لو سبب أرق.',
		warnings: ['مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 148
	{
		id: 'recoxibright-etoricoxib-120mg-fc-tabs-7-a3',
		name: 'recoxibright 120 mg 7 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '120 mg',
		price: 88,
		matchKeywords: ['recoxibright 120', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 بجرعة أعلى (عادةً لفترة قصيرة).',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٢٠ مجم) مرة يومياً بعد الأكل ولمدة قصيرة (حد أقصى قرص واحد/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 149
	{
		id: 'recoxibright-etoricoxib-30mg-fc-tabs-30-a3',
		name: 'recoxibright 30 mg 30 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '30 mg',
		price: 97.5,
		matchKeywords: ['recoxibright 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٣٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 150
	{
		id: 'recoxibright-etoricoxib-90mg-fc-tabs-30-a3',
		name: 'recoxibright 90 mg 30 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 297,
		matchKeywords: ['recoxibright 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 151
	{
		id: 'rhinocalm-syrup-120ml-a3',
		name: 'rhinocalm syrup 120ml',
		genericName: 'chlorpheniramine maleate & pseudoephedrine hydrochloride',
		concentration: '120ml',
		price: 40,
		matchKeywords: ['rhinocalm syrup', ...tag('#common cold')],
		usage: 'مضاد حساسية + مزيل احتقان لأعراض الرشح/الاحتقان.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Syrup',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) => {
			if (ageMonths < 144) return 'لا يفضل استخدامه أقل من ١٢ سنة.';
			if (ageMonths <= 144) return '٥ مل كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
			return '١٠ مل كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
		},
		warnings: ['مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 152
	{
		id: 'rhinomol-s-syrup-120ml-a3',
		name: 'rhinomol-s syrup 120ml',
		genericName: 'chlorpheniramine maleate & paracetamol & pseudoephedrine',
		concentration: '120ml',
		price: 40,
		matchKeywords: ['rhinomol-s syrup', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان (خافض حرارة + مضاد حساسية + مزيل احتقان).',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Syrup',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) => {
			if (ageMonths < 72) return 'لا يستخدم للأطفال أقل من ٦ سنوات.';
			if (ageMonths < 144) return '٥ مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
			return '١٠ مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
		},
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 153
	{
		id: 'rotapyretic-paracetamol-1g-100ml-iv-infusion-vial-a3',
		name: 'rotapyretic 1 gm/100ml vial for i.v. inf.',
		genericName: 'paracetamol',
		concentration: '1 gm/100ml',
		price: 67,
		matchKeywords: ['rotapyretic 1g', ...tag('#antipyretics')],
		usage: 'باراسيتامول وريدي؛ للإعطاء بالمستشفى/العيادة بجرعة محددة.',
		timing: 'حقن – حسب بروتوكول المستشفى',
		category: Category.PARACETAMOL,
		form: 'I.V. Infusion Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'حسب بروتوكول المستشفى.',
		warnings: [...commonParacetamolWarnings],
	},

	// 154
	{
		id: 'rotapyretic-paracetamol-500mg-50ml-iv-infusion-vial-a3',
		name: 'rotapyretic 500mg/50ml vial for i.v. inf.',
		genericName: 'paracetamol',
		concentration: '500mg/50ml',
		price: 13.5,
		matchKeywords: ['rotapyretic 500', ...tag('#antipyretics')],
		usage: 'باراسيتامول وريدي؛ للإعطاء بالمستشفى/العيادة بجرعة محددة.',
		timing: 'حقن – حسب بروتوكول المستشفى',
		category: Category.PARACETAMOL,
		form: 'I.V. Infusion Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'حسب بروتوكول المستشفى.',
		warnings: [...commonParacetamolWarnings],
	},

	// 155
	{
		id: 'winzoxib-etoricoxib-60mg-fc-tabs-20-a3',
		name: 'winzoxib 60 mg 20 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 126,
		matchKeywords: ['winzoxib 60', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 156
	{
		id: 'oplex-n-plus-supp-10-a3',
		name: 'oplex-n plus 10 supp.',
		genericName: 'guaifenesin & oxomemazine & paracetamol & sodium benzoate',
		concentration: 'Suppositories',
		price: 32,
		matchKeywords: ['oplex-n plus', ...tag('#anti cough', '#antitussive', '#expectorant')],
		usage: 'لبوس للكحة (مهدئ كحة + طارد بلغم) مع باراسيتامول.',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.COUGH,
		form: 'Suppositories',
		minAgeMonths: 24,
		maxAgeMonths: 144,
		minWeight: 10,
		maxWeight: 45,
		calculationRule: (_w: number, _a: number) => 'لبوسة شرجية كل ١٢ ساعة عند اللزوم (حد أقصى ٢/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'قد يسبب نعاس/تهدئة بسبب أوكسوميمزين.'],
	},
];

