
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;

const tag = (...tags: string[]) => tags;

const commonParacetamolWarnings = [
	'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
	'مرضى الكبد/الكحول: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
	'يفضل بعد الأكل لتقليل تهيج المعدة.',
	'لا تجمع أكثر من NSAID في نفس الوقت.',
	'يُتجنب مع قرحة/نزيف معدي أو فشل كلوي شديد، وأواخر الحمل.',
];

export const ANALGESICS_4: Medication[] = [
	// 157
	{
		id: 'adwiflam-diclofenac-potassium-50mg-er-caps-30-a4',
		name: 'adwiflam 50mg e.r. 30 caps.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 29.25,
		matchKeywords: ['adwiflam 50 er 30', ...tag('#nsaid', '#acetic acid derivatives', '#antipyretics')],
		usage: 'مسكن ومضاد التهاب (NSAID) ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sustained-release Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٥٠ مجم) مرة يومياً بعد الأكل. الحد الأقصى: ٢ كبسولة/٢٤ ساعة عند الضرورة؛ حد أقصى ٢/٢٤ ساعة ولمدة قصيرة.',
		warnings: [...commonNsaidWarnings],
	},

	// 158
	{
		id: 'adwiflam-diclofenac-potassium-50mg-sachets-10-a4',
		name: 'adwiflam 50 mg 10 sachets',
		genericName: 'diclofenac potassium',
		concentration: '50 mg',
		price: 50,
		matchKeywords: ['adwiflam 50 sachets', ...tag('#nsaid', '#acetic acid derivatives', '#antipyretics', '#analgesics')],
		usage: 'مسكن ومضاد التهاب (NSAID) أكياس.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كيس واحد (٥٠ مجم) يُذاب في نصف كوب ماء ويُشرب مرة يومياً بعد الأكل. الحد الأقصى: ٢ كيس/٢٤ ساعة عند الضرورة؛ حد أقصى ٢/٢٤ ساعة ولمدة قصيرة.',
		warnings: [...commonNsaidWarnings],
	},

	// 159
	{
		id: 'cataflam-diclofenac-potassium-25mg-sugar-coated-tabs-20-a4',
		name: 'cataflam 25 mg 20 sugar c.tabs',
		genericName: 'diclofenac potassium',
		concentration: '25 mg',
		price: 34,
		matchKeywords: ['cataflam 25', ...tag('#analgesics', '#antipyretics', '#anti-inflammatory', '#nsaid')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sugar Coated Tablets',
		minAgeMonths: 120,
		maxAgeMonths: 1200,
		minWeight: 25,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٥ مجم) كل ٨ ساعات بعد الأكل عند اللزوم. الحد الأقصى: ٣ أقراص/٢٤ ساعة.',
		warnings: [...commonNsaidWarnings],
	},

	// 160
	{
		id: 'cetafen-plus-caffeine-paracetamol-ibuprofen-tabs-30-a4',
		name: 'cetafen plus 30 tab.',
		genericName: 'caffeine & paracetamol & ibuprofen',
		concentration: 'Tablets',
		price: 81,
		matchKeywords: ['cetafen plus 30', ...tag('#analgesics')],
		usage: 'مسكن مركب (باراسيتامول + إيبوبروفين + كافيين).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات عند اللزوم بعد الأكل. الحد الأقصى: ٣ أقراص/٢٤ ساعة.',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 161
	{
		id: 'coli-urinal-hexamine-khellin-piperazine-eff-gr-60gm-a4',
		name: 'coli-urinal eff. gr. 60 gm',
		genericName: 'hexamine & khellin & piperazine',
		concentration: '60 gm',
		price: 40,
		matchKeywords: ['coli-urinal', ...tag('#urinary', '#analgesics', '#antiseptics')],
		usage: 'فوار مطهر للمسالك البولية ومضاد للتقلصات (برطمان).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.URINARY_CARE,
		form: 'Granules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'تُذاب ملعقة كبيرة في نصف كوب ماء وتُشرب ٣ مرات يومياً.',
		warnings: ['ممنوع مع مركبات السلفا.', 'في قصور الكلى: عدّل الجرعة أو اختر بديلاً.'],
	},

	// 162
	{
		id: 'ost-map-acemetacin-60mg-caps-20-a4',
		name: 'ost-map 60mg 20 caps.',
		genericName: 'acemetacin',
		concentration: '60mg',
		price: 54,
		matchKeywords: ['ost-map 60', ...tag('#nsaid', '#analgesics')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٦٠ مجم) مرة إلى مرتين يومياً بعد الأكل. الحد الأقصى: ٣ كبسولات/٢٤ ساعة.',
		warnings: [...commonNsaidWarnings],
	},

	// 163
	{
		id: 'paracetamol-cid-paracetamol-500mg-tabs-20-a4',
		name: 'paracetamol-cid 500mg 20 tab',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 38,
		matchKeywords: ['paracetamol-cid 500', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 6,
		maxWeight: 250,
		calculationRule: (weight: number, _a: number) =>
			weight < 40
				? 'نصف قرص إلى قرص كل ٤–٦ ساعات عند اللزوم.'
				: 'قرص إلى قرصين كل ٤–٦ ساعات عند اللزوم.',
		warnings: [...commonParacetamolWarnings],
	},

	// 164
	{
		id: 'voltaren-diclofenac-sodium-50mg-tabs-20-a4',
		name: 'voltaren 50mg 20 tab.',
		genericName: 'diclofenac sodium',
		concentration: '50mg',
		price: 68,
		matchKeywords: ['voltaren 50 20', ...tag('#nsaid', '#acetic acid derivatives', '#analgesics', '#antipyretics')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 165
	{
		id: 'voltaren-diclofenac-sodium-100mg-supp-10-a4',
		name: 'voltaren 100mg 10 supp.',
		genericName: 'diclofenac sodium',
		concentration: '100mg',
		price: 54,
		matchKeywords: ['voltaren 100 supp', ...tag('#nsaid', '#acetic acid derivatives', '#analgesics', '#antipyretics')],
		usage: 'لبوس مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً مساءً (تحاميل) – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٠٠ مجم) مساءً بعد التبرز إن أمكن (حد أقصى لبوسة واحدة/٢٤ ساعة؛ لا تكرر أكثر).',
		warnings: [...commonNsaidWarnings],
	},

	// 166
	{
		id: 'pronto-plus-caffeine-paracetamol-tabs-20-a4',
		name: 'pronto plus 20 tab.',
		genericName: 'caffeine & paracetamol',
		concentration: 'Tablets',
		price: 40,
		matchKeywords: ['pronto plus 20', ...tag('#analgesics', '#antipyretics')],
		usage: 'مسكن وخافض حرارة (باراسيتامول + كافيين).',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 167
	{
		id: 'adwiflam-diclofenac-potassium-50mg-er-caps-20-a4',
		name: 'adwiflam 50mg e.r. 20 caps.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 42,
		matchKeywords: ['adwiflam 50 er 20', ...tag('#nsaid', '#acetic acid derivatives', '#antipyretics', '#analgesics')],
		usage: 'مسكن ومضاد التهاب (NSAID) ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sustained-release Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٥٠ مجم) مرة يومياً بعد الأكل. الحد الأقصى: ٢ كبسولة/٢٤ ساعة عند الضرورة؛ حد أقصى ٢/٢٤ ساعة ولمدة قصيرة.',
		warnings: [...commonNsaidWarnings],
	},

	// 168
	{
		id: 'adol-extra-caffeine-paracetamol-caplet-24-a4',
		name: 'adol extra 24 caplets.',
		genericName: 'caffeine & paracetamol',
		concentration: 'Caplets',
		price: 52,
		matchKeywords: ['adol extra 24', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة (باراسيتامول + كافيين).',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Caplet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 169
	{
		id: 'lidocaine-hydrochloride-10mg-ml-2ml-amp-a4',
		name: 'lidocaine hydrochloride 10mg/ml amp. 2 ml',
		genericName: 'lidocaine hydrochloride',
		concentration: '10mg/ml (2 ml)',
		price: 2,
		matchKeywords: ['lidocaine 10mg/ml 2ml', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي للحقن في العيادة/المستشفى بجرعة محددة.',
		timing: 'حقن – حسب الإجراء الطبي',
		category: Category.TOPICAL_CARE,
		form: 'Ampoules',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (w: number, _a: number) =>
			`يُعطى بواسطة مختص فقط. أمبول ٢ مل = ٢٠ مجم. الحد الأقصى المعتاد (بدون أدرينالين): ${toAr(Math.round(w * 4.5))} مجم تقريباً (${toAr(4.5)} مجم/كجم). استخدم أقل جرعة فعّالة.`,
		warnings: ['قد يسبب حساسية/هبوط ضغط أو اضطراب ضربات: يلزم الإعطاء في منشأة صحية.'],
	},

	// 171
	{
		id: 'lidocaine-hydrochloride-10mg-ml-5ml-amp-a4',
		name: 'lidocaine hydrochloride 10mg/ml amp. 5 ml',
		genericName: 'lidocaine hydrochloride',
		concentration: '10mg/ml (5 ml)',
		price: 4,
		matchKeywords: ['lidocaine 10mg/ml 5ml', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي للحقن في العيادة/المستشفى بجرعة محددة.',
		timing: 'حقن – حسب الإجراء الطبي',
		category: Category.TOPICAL_CARE,
		form: 'Ampoules',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (w: number, _a: number) =>
			`يُعطى بواسطة مختص فقط. أمبول ٥ مل = ٥٠ مجم. الحد الأقصى المعتاد (بدون أدرينالين): ${toAr(Math.round(w * 4.5))} مجم تقريباً (${toAr(4.5)} مجم/كجم). استخدم أقل جرعة فعّالة.`,
		warnings: ['قد يسبب حساسية/هبوط ضغط أو اضطراب ضربات: يلزم الإعطاء في منشأة صحية.'],
	},

	// 172
	{
		id: 'lidocaine-hydrochloride-2-epinephrine-0-01mg-amp-a4',
		name: 'lidocaine hydrochloride 2% & epinephrine 0.01 mg amp',
		genericName: 'lidocaine hydrochloride & epinephrine',
		concentration: '2% & 0.01 mg',
		price: 43.5,
		matchKeywords: ['lidocaine epinephrine amp', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي مع أدرينالين (إجراءات طبية/أسنان) في منشأة صحية.',
		timing: 'حقن – حسب الإجراء الطبي',
		category: Category.TOPICAL_CARE,
		form: 'Ampoules',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (w: number, _a: number) =>
			`يُعطى بواسطة مختص فقط. الحد الأقصى المعتاد (مع أدرينالين): ${toAr(Math.round(w * 7))} مجم تقريباً (${toAr(7)} مجم/كجم). استخدم أقل جرعة فعّالة.`,
		warnings: ['قد يرفع الضغط/يزيد خفقان بسبب الأدرينالين.'],
	},

	// 173
	{
		id: 'paramol-paracetamol-500mg-tabs-20-a4',
		name: 'paramol 500mg 20 tab.',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 38,
		matchKeywords: ['paramol 500', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 6,
		maxWeight: 250,
		calculationRule: (weight: number, _a: number) =>
			weight < 40 ? 'نصف قرص إلى قرص كل ٤–٦ ساعات عند اللزوم.' : 'قرص إلى قرصين كل ٤–٦ ساعات عند اللزوم.',
		warnings: [...commonParacetamolWarnings],
	},

	// 174
	{
		id: 'polyfresh-extra-eye-drops-30x0-4-sdu-a4',
		name: 'polyfresh extra eye drops 30 x 0.4 ml sdu',
		genericName: 'sodium hyaluronate & glycerin & sodium carboxymethylcellulose',
		concentration: '30 x 0.4 ml sdu',
		price: 185,
		matchKeywords: ['polyfresh extra', ...tag('#analgesics', '#anti-inflammatory', '#eye surge')],
		usage: 'قطرة مرطبة للعين (وحدات أحادية الجرعة).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => '1–2 نقطة عند اللزوم.',
		warnings: ['أوقف وأعد التقييم إذا حدث تهيج شديد أو ألم مستمر.'],
	},

	// 175
	{
		id: 'renal-s-hexamine-khellin-sachets-12-a4',
		name: 'renal-s 12 sachet',
		genericName: 'hexamine & khellin',
		concentration: '12 sachet',
		price: 21,
		matchKeywords: ['renal-s 12', ...tag('#urinary', '#analgesics', '#antiseptics')],
		usage: 'مطهر للمسالك البولية ومذيب للأملاح (فوار/أكياس).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.URINARY_CARE,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كيس واحد على نصف كوب ماء ٣ مرات يومياً.',
		warnings: ['يجب شرب كميات كبيرة من الماء.', 'في قصور الكلى: عدّل الجرعة أو اختر بديلاً.'],
	},

	// 176
	{
		id: 'stopadol-paracetamol-500mg-tabs-20-a4',
		name: 'stopadol 500mg 20 tabs.',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 38,
		matchKeywords: ['stopadol 500', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 6,
		maxWeight: 250,
		calculationRule: (weight: number, _a: number) =>
			weight < 40
				? 'نصف قرص إلى قرص كل ٤–٦ ساعات عند اللزوم.'
				: 'قرص إلى قرصين كل ٤–٦ ساعات عند اللزوم.',
		warnings: [...commonParacetamolWarnings],
	},

	// 177
	{
		id: 'stopadol-extra-caffeine-paracetamol-tabs-20-a4',
		name: 'stopadol extra 20 tab.',
		genericName: 'caffeine & paracetamol',
		concentration: 'Tablets',
		price: 38,
		matchKeywords: ['stopadol extra 20', ...tag('#analgesics')],
		usage: 'مسكن مركب (باراسيتامول + كافيين).',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 178
	{
		id: 'renal-s-n-hexamine-khellin-sachets-12-a4',
		name: 'renal s-n 12 sachet',
		genericName: 'hexamine & khellin',
		concentration: '12 sachet',
		price: 30,
		matchKeywords: ['renal s-n 12', ...tag('#urinary', '#analgesics', '#antiseptics')],
		usage: 'فوار/أكياس للمسالك البولية ومطهر بولي.',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.URINARY_CARE,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كيس واحد يُذاب في نصف كوب ماء ٢–٣ مرات يومياً.',
		warnings: ['في قصور الكلى: عدّل الجرعة أو اختر بديلاً.'],
	},

	// 179
	{
		id: 'stopadol-paracetamol-650mg-ext-rel-tabs-30-a4',
		name: 'stopadol 650 mg 30 ext. rel. tabs.',
		genericName: 'paracetamol',
		concentration: '650 mg',
		price: 75,
		matchKeywords: ['stopadol 650 ext rel', ...tag('#analgesics')],
		usage: 'باراسيتامول ممتد المفعول لتسكين الألم.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات عند اللزوم. يمكن تناول قرصين للألم الشديد. الحد الأقصى: ٦ أقراص/٢٤ ساعة.',
		warnings: [...commonParacetamolWarnings],
	},

	// 180
	{
		id: 'one-two-three-syrup-120ml-a4',
		name: '1 2 3 (one two three) syrup 120 ml',
		genericName: 'pseudoephedrine & paracetamol & chlorpheniramine maleate',
		concentration: '120 ml',
		price: 32,
		matchKeywords: ['1 2 3 syrup', ...tag('#common cold')],
		usage: 'شراب لأعراض البرد/الاحتقان (مزيل احتقان + باراسيتامول + مضاد حساسية).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Syrup',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 72
				? 'غير مناسب للأطفال أقل من ٦ سنوات.'
				: ageMonths < 144
					? '٥ مل كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).'
					: 'للبالغين: ١٠ مل كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 181
	{
		id: 'diclopro-diclofenac-sodium-150mg-id-tabs-20-a4',
		name: 'diclopro 150 mg id 20 tabs.',
		genericName: 'diclofenac sodium',
		concentration: '150 mg',
		price: 106,
		matchKeywords: ['diclopro 150 id', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٥٠ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 182
	{
		id: 'awadist-plus-paracetamol-diphenhydramine-fc-tabs-20-a4',
		name: 'awadist plus 20 f.c. tabs.',
		genericName: 'paracetamol & diphenhydramine hydrochloride',
		concentration: 'F.C. Tablets',
		price: 56,
		matchKeywords: ['awadist plus', ...tag('#common cold')],
		usage: 'أعراض البرد/الحساسية (قد يسبب نعاس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 183
	{
		id: 'anoxicam-tenoxicam-20mg-supp-10-a4',
		name: 'anoxicam 20mg 10 supp.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 34,
		matchKeywords: ['anoxicam 20 supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً مساءً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٢٠ مجم) مرة يومياً (حد أقصى لبوسة/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 184
	{
		id: 'antiflam-diclofenac-potassium-50mg-tabs-20-a4',
		name: 'antiflam 50mg 20 tab.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 44,
		matchKeywords: ['antiflam 50', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 185
	{
		id: 'antiflu-caps-20-a4',
		name: 'antiflu 20 cap',
		genericName: 'caffeine & chlorpheniramine & ibuprofen & phenylpropanolamine',
		concentration: 'Capsules',
		price: 38,
		matchKeywords: ['antiflu cap', ...tag('#common cold')],
		usage: 'كبسولات للبرد/الاحتقان (قد تسبب نعاس).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ كبسولات/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 186
	{
		id: 'anuva-diclofenac-sodium-50mg-dispersible-tabs-10-a4',
		name: 'anuva 50mg 10 dispersible tab.',
		genericName: 'diclofenac sodium',
		concentration: '50mg',
		price: 27,
		matchKeywords: ['anuva 50 dispersible', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID) أقراص تذوب/تتشتت.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 187
	{
		id: 'articavol-diclofenac-sodium-75mg-3ml-amps-3-a4',
		name: 'articavol 75mg/3ml 3 amp.',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 33,
		matchKeywords: ['articavol amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (حقن) يُعطى بواسطة مختص فقط.',
		timing: 'جرعة مفردة، تكرر بعد ١٢ ساعة عند الحاجة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم/٣ مل) عضل عميق. يمكن تكراره بعد ١٢ ساعة عند اللزوم. الحد الأقصى: ٢ أمبول/٢٤ ساعة (١٥٠ مجم).',
		warnings: [...commonNsaidWarnings],
	},

	// 188
	{
		id: 'awadist-paracetamol-1000mg-fc-tabs-20-a4',
		name: 'awadist 1000 mg 20 f.c. tabs.',
		genericName: 'paracetamol',
		concentration: '1000 mg',
		price: 60,
		matchKeywords: ['awadist 1000', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٠٠٠ مجم) كل ٨ ساعات عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 189
	{
		id: 'cetal-cold-flu-paracetamol-pseudoephedrine-caplets-20-a4',
		name: 'cetal cold & flu 20 caplets',
		genericName: 'paracetamol & pseudoephedrine hydrochloride',
		concentration: 'Caplets',
		price: 36,
		matchKeywords: ['cetal cold & flu', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان (باراسيتامول + مزيل احتقان).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Caplet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 190
	{
		id: 'cevamol-eff-granules-12-sachets-a4',
		name: 'cevamol eff granules 12 sachets',
		genericName: 'paracetamol & ascorbic acid (vitamin c)',
		concentration: '12 sachets',
		price: 27,
		matchKeywords: ['cevamol eff', ...tag('#common cold')],
		usage: 'فوار/أكياس لأعراض البرد مع باراسيتامول + فيتامين C.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كيس واحد يُذاب في نصف كوب ماء كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أكياس/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 191
	{
		id: 'cold-control-diphenhydramine-paracetamol-fc-tab-20-a4',
		name: 'cold control 20 f.c.tab',
		genericName: 'diphenhydramine hydrochloride & paracetamol',
		concentration: 'F.C. Tablets',
		price: 32,
		matchKeywords: ['cold control', ...tag('#common cold')],
		usage: 'أعراض البرد (قد يسبب نعاس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 192
	{
		id: 'dexketo-care-dexketoprofen-25mg-fc-tabs-30-a4',
		name: 'dexketo care 25 mg 30 f.c.tab.',
		genericName: 'dexketoprofen',
		concentration: '25 mg',
		price: 75,
		matchKeywords: ['dexketo care 25', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٥ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة = ٧٥ مجم).',
		warnings: [...commonNsaidWarnings],
	},

	// 193
	{
		id: 'dispercam-piroxicam-20mg-ml-amps-6-a4',
		name: 'dispercam 20 mg/ml 6 amp.',
		genericName: 'piroxicam',
		concentration: '20 mg/ml',
		price: 48,
		matchKeywords: ['dispercam amp', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (حقن) يُعطى بواسطة مختص فقط.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٢٠ مجم) عضل مرة يومياً لمدة قصيرة (١–٢ يوم) ثم التحويل لأقراص عند الإمكان. الحد الأقصى: ٢٠ مجم/٢٤ ساعة.',
		warnings: [...commonNsaidWarnings],
	},

	// 194
	{
		id: 'dolo-d-oral-susp-115ml-a4',
		name: 'dolo-d oral susp. 115 ml',
		genericName: 'pseudoephedrine hydrochloride & ibuprofen & chlorpheniramine',
		concentration: '115 ml',
		price: 37,
		matchKeywords: ['dolo-d susp', ...tag('#common cold')],
		usage: 'شراب لأعراض البرد/الاحتقان (يحتوي NSAID).',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Oral Suspension',
		minAgeMonths: 72,
		maxAgeMonths: 180,
		minWeight: 20,
		maxWeight: 60,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 72
				? 'غير مناسب للأطفال أقل من ٦ سنوات.'
				: '٥ مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 195
	{
		id: 'epicotil-tenoxicam-20mg-fc-tabs-10-a4',
		name: 'epicotil 20mg 10 f.c.tab.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 43,
		matchKeywords: ['epicotil 20', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٠ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 196
	{
		id: 'ezamol-c-paracetamol-phenylephrine-caffeine-terpin-tabs-20-a4',
		name: 'ezamol-c 20 tab.',
		genericName: 'paracetamol & phenylephrine hydrochloride & caffeine & terpin hydrate',
		concentration: 'Tablets',
		price: 24,
		matchKeywords: ['ezamol-c', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'فينيل إفرين قد يرفع الضغط/يزيد خفقان.'],
	},

	// 197
	{
		id: 'feldene-piroxicam-20mg-ml-im-amp-6-a4',
		name: 'feldene 20mg/ml i.m. 6 amp.',
		genericName: 'piroxicam',
		concentration: '20mg/ml',
		price: 90,
		matchKeywords: ['feldene amp 6', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (حقن) يُعطى بواسطة مختص فقط.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٢٠ مجم) عضل مرة يومياً لمدة قصيرة (١–٢ يوم) ثم التحويل لأقراص عند الإمكان. الحد الأقصى: ٢٠ مجم/٢٤ ساعة.',
		warnings: [...commonNsaidWarnings],
	},

	// 198
	{
		id: 'feldene-piroxicam-20mg-disp-tabs-10-a4',
		name: 'feldene 20mg 10 disp. tab',
		genericName: 'piroxicam',
		concentration: '20mg',
		price: 42.5,
		matchKeywords: ['feldene 20 disp', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٠ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 199
	{
		id: 'flamifast-diclofenac-potassium-50mg-odt-tabs-30-a4',
		name: 'flamifast 50mg 30 orally disintegrating tabs.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 52.5,
		matchKeywords: ['flamifast 50 odt', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID) أقراص تذوب بالفم.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Orodispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 200
	{
		id: 'ketofan-ketoprofen-25mg-tabs-30-a4',
		name: 'ketofan 25mg 30 tab',
		genericName: 'ketoprofen',
		concentration: '25mg',
		price: 33,
		matchKeywords: ['ketofan 25', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٥ مجم) ٢–٣ مرات يومياً بعد الأكل (حد أقصى ٣ أقراص/اليوم).',
		warnings: [...commonNsaidWarnings],
	},
];

