
import { Medication, Category } from '../../../types';


const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;
const roundSmallVol = (vol: number): number => Math.round(vol * 10) / 10;
const tag = (...tags: string[]) => tags;

const commonParacetamolWarnings = [
	'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
	'مرضى الكبد/الكحول: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
	'يفضل بعد الأكل لتقليل تهيج المعدة.',
	'لا تجمع أكثر من NSAID في نفس الوقت.',
	'يُتجنب مع قرحة/نزيف معدي أو فشل كلوي شديد، وأواخر الحمل.',
];

const lidocaineMaxDoseText = (weight: number, mgPerMl: number, withEpinephrine: boolean) => {
	const maxMg = withEpinephrine ? Math.min(weight * 7, 500) : Math.min(weight * 4.5, 300);
	const maxMl = roundSmallVol(maxMg / mgPerMl);
	return `الحد الأقصى الإجمالي = ${toAr(Math.round(maxMg))} مجم ≈ ${toAr(maxMl)} مل (لا يتكرر إلا بتوجيه مختص).`;
};

export const ANALGESICS_6: Medication[] = [
	// 267
	{
		id: 'etoricox-hexal-etoricoxib-90mg-fc-tabs-10-a6',
		name: 'etoricox-hexal 90 mg 10 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 102,
		matchKeywords: ['etoricox-hexal 90 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 268
	{
		id: 'futacoxib-etoricoxib-60mg-fc-tabs-30-a6',
		name: 'futacoxib 60 mg 30 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 231,
		matchKeywords: ['futacoxib 60 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 269
	{
		id: 'futacoxib-etoricoxib-90mg-fc-tabs-30-a6',
		name: 'futacoxib 90 mg 30 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 297,
		matchKeywords: ['futacoxib 90 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 270
	{
		id: 'etoricox-hexal-etoricoxib-90mg-fc-tabs-30-a6',
		name: 'etoricox-hexal 90 mg 30 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 306,
		matchKeywords: ['etoricox-hexal 90 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 271
	{
		id: 'baby-relief-diclofenac-sodium-12-5mg-supp-10-a6',
		name: 'baby relief 12.5 mg 10 supp.',
		genericName: 'diclofenac sodium',
		concentration: '12.5 mg',
		price: 36,
		matchKeywords: ['baby relief 12.5 10 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك للأطفال (مسكن/مضاد التهاب).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 84,
		minWeight: 7,
		maxWeight: 15,
		calculationRule: () => 'لبوسة واحدة (١٢.٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 272
	{
		id: 'baby-relief-diclofenac-sodium-25mg-supp-10-a6',
		name: 'baby relief 25 mg 10 supp.',
		genericName: 'diclofenac sodium',
		concentration: '25 mg',
		price: 38,
		matchKeywords: ['baby relief 25 10 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك للأطفال (مسكن/مضاد التهاب).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 144,
		minWeight: 15,
		maxWeight: 30,
		calculationRule: () => 'لبوسة واحدة (٢٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 273
	{
		id: 'medexaflam-meloxicam-15mg-tabs-30-a6',
		name: 'medexaflam 15mg 30 tabs.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 36,
		matchKeywords: ['medexaflam 15 30', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 274
	{
		id: 'stopadol-cold-flu-20-caps-a6',
		name: 'stopadol cold & flu 20 caps.',
		genericName: 'paracetamol & guaifenesin & phenylephrine hydrochloride',
		concentration: 'Capsules',
		price: 50,
		matchKeywords: ['stopadol cold flu 20', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان مع مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144 ? 'لا يُستخدم أقل من ١٢ سنة.' : 'كبسولة واحدة كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ كبسولات/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان؛ يُتجنب مع ضغط غير منضبط.'],
	},

	// 275
	{
		id: 'centravita-palmi-caps-20-a6',
		name: 'centravita palmi 20 caps',
		genericName: 'palmitoylethanolamide & bromelain & boswellia dry extract',
		concentration: 'Capsules',
		price: 160,
		matchKeywords: ['centravita palmi 20', ...tag('#analgesics')],
		usage: 'دعم لتقليل الالتهاب/الألم المزمن وآلام الأعصاب/المفاصل (مكمل).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة مرة إلى مرتين يومياً بعد الأكل.',
		warnings: ['الحمل/الرضاعة: يُفضل الاستشارة.', 'مميعات الدم: الحذر (بروميلين).'],
	},

	// 277
	{
		id: 'cetafen-200-500-tabs-30-a6',
		name: 'cetafen 200/500mg 30 tabs.',
		genericName: 'ibuprofen & paracetamol',
		concentration: '200/500mg',
		price: 69,
		matchKeywords: ['cetafen 200 500 30', ...tag('#nsaid', '#analgesics')],
		usage: 'مسكن مزدوج (باراسيتامول + إيبوبروفين).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد كل ٨ ساعات بعد الأكل (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 278
	{
		id: 'cetafen-dispersible-30-a6',
		name: 'cetafen 30 dispersible tab.',
		genericName: 'ibuprofen & paracetamol',
		concentration: 'Dispersible Tablets',
		price: 45,
		matchKeywords: ['cetafen dispersible 30', ...tag('#analgesics')],
		usage: 'مسكن مزدوج (باراسيتامول + إيبوبروفين) أقراص تذوب/تتشتت.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد كل ٨ ساعات بعد الأكل (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 279
	{
		id: 'cetal-extra-caffeine-paracetamol-20-tabs-a6',
		name: 'cetal extra 20 tabs.',
		genericName: 'caffeine & paracetamol',
		concentration: 'Tablets',
		price: 44,
		matchKeywords: ['cetal extra 20', ...tag('#analgesics', '#antipyretics')],
		usage: 'مسكن للصداع وآلام بسيطة (باراسيتامول + كافيين).',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'قد يسبب أرق/خفقان بسبب الكافيين.'],
	},

	// 280
	{
		id: 'ketolac-ketorolac-tromethamine-30mg-2ml-amp-5-a6',
		name: 'ketolac 30mg/2ml 5 amp. for i.m./i.v. inf.',
		genericName: 'ketorolac tromethamine',
		concentration: '30mg/2ml',
		price: 60,
		matchKeywords: ['ketolac 30 amp', ...tag('#nsaid', '#acetic acid derivatives', '#analgesics', '#antipyretics')],
		usage: 'حقن مسكنة قوية للألم الحاد قصير المدى.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 192,
		maxAgeMonths: 780,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'أمبول (٣٠ مجم) كل ٦–٨ ساعات عند اللزوم. الحد الأقصى: ٤ أمبول/٢٤ ساعة ولمدة لا تزيد عن ٥ أيام.',
		warnings: [...commonNsaidWarnings, 'ممنوع في الفشل الكلوي أو النزيف/القرحة.'],
	},

	// 281
	{
		id: 'lidocaine-hcl-20mg-ml-vial-50ml-a6',
		name: 'lidocaine hcl 20mg/ml vial im iv sc 50 ml',
		genericName: 'lidocaine hydrochloride',
		concentration: '20mg/ml',
		price: 11.25,
		matchKeywords: ['lidocaine 20mg/ml vial 50', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي/إقليمي (يُستخدم بواسطة مختص).',
		timing: 'حقن – جرعة واحدة حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (w: number) => lidocaineMaxDoseText(w, 20, false),
		warnings: ['جرعات زائدة قد تسبب تشنجات/اضطراب نظم. راقب العلامات الحيوية.', 'لا يُستخدم دون تدريب مناسب.'],
	},

	// 282
	{
		id: 'lidocaine-hcl-2percent-vial-50ml-a6',
		name: 'lidocaine hcl 2% vial 50 ml',
		genericName: 'lignocaine hydrochloride',
		concentration: '2% (20mg/ml)',
		price: 23,
		matchKeywords: ['lidocaine 2% vial 50', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي/إقليمي (يُستخدم بواسطة مختص).',
		timing: 'حقن – جرعة واحدة حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (w: number) => lidocaineMaxDoseText(w, 20, false),
		warnings: ['جرعات زائدة قد تسبب تشنجات/اضطراب نظم.'],
	},

	// 283
	{
		id: 'lidocaine-hcl-pharmacell-2percent-vial-50ml-a6',
		name: 'lidocaine hcl pharmacell 2% vial im iv sc 50 ml',
		genericName: 'lidocaine hydrochloride',
		concentration: '2% (20mg/ml)',
		price: 14,
		matchKeywords: ['lidocaine pharmacell 2% vial 50', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي/إقليمي (يُستخدم بواسطة مختص).',
		timing: 'حقن – جرعة واحدة حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (w: number) => lidocaineMaxDoseText(w, 20, false),
		warnings: ['جرعات زائدة قد تسبب أعراض عامة خطيرة.'],
	},

	// 284
	{
		id: 'solpadeine-soluble-tabs-24-a6',
		name: 'solpadeine soluble 24 tab',
		genericName: 'paracetamol & codeine & caffeine',
		concentration: 'Effervescent Tablets',
		price: 200,
		matchKeywords: ['solpadeine soluble 24', ...tag('#analgesics')],
		usage: 'مسكن للآلام المتوسطة (يحتوي على كودايين) + باراسيتامول.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Effervescent Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص إلى قرصين كل ٤–٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'يحتوي على كودايين: قد يسبب نعاساً/اعتماداً. يُمنع أقل من ١٢ سنة والرضاعة.'],
	},

	// 287
	{
		id: 'voltaren-diclofenac-sodium-25mg-enteric-tabs-30-a6',
		name: 'voltaren 25mg 30 enteric coated tab.',
		genericName: 'diclofenac sodium',
		concentration: '25mg',
		price: 13.56,
		matchKeywords: ['voltaren 25 enteric 30', ...tag('#nsaid', '#acetic acid derivatives', '#analgesics', '#antipyretics')],
		usage: 'مسكن ومضاد التهاب (Diclofenac).',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.DICLOFENAC,
		form: 'Enteric Coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٢٥ مجم) ٢–٣ مرات يومياً بعد الأكل (حد أقصى ٦ أقراص/٢٤ ساعة = ١٥٠ مجم).',
		warnings: [...commonNsaidWarnings],
	},

	// 288
	{
		id: 'voltaren-diclofenac-sodium-25mg-supp-5-a6',
		name: 'voltaren 25mg 5 supp.',
		genericName: 'diclofenac sodium',
		concentration: '25mg',
		price: 15,
		matchKeywords: ['voltaren 25 supp 5', ...tag('#nsaid', '#acetic acid derivatives', '#analgesics', '#antipyretics')],
		usage: 'لبوس ديكلوفيناك مسكن ومضاد التهاب.',
		timing: 'كل ٨–١٢ ساعة عند الألم – ٣–٧ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: () => 'لبوسة واحدة (٢٥ مجم) ٢–٣ مرات يومياً عند اللزوم (حد أقصى ٦ لبوس/٢٤ ساعة = ١٥٠ مجم).',
		warnings: [...commonNsaidWarnings],
	},

	// 289
	{
		id: 'cetafen-tabs-30-a6',
		name: 'cetafen 30 tabs.',
		genericName: 'ibuprofen & paracetamol',
		concentration: 'Tablets',
		price: 42,
		matchKeywords: ['cetafen 30 tabs', ...tag('#nsaid', '#analgesics')],
		usage: 'مسكن مزدوج (باراسيتامول + إيبوبروفين).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد كل ٨ ساعات بعد الأكل (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 293
	{
		id: 'deep-freeze-cold-spray-150ml-a6',
		name: 'deep freeze pain relief cold spray 150 ml',
		genericName: 'n-pentane & iso-butane & propane & n-butane',
		concentration: '150 ml',
		price: 449,
		matchKeywords: ['deep freeze cold spray 150', ...tag('#analgesics')],
		usage: 'سبراي تبريد لآلام العضلات/الإصابات البسيطة.',
		timing: 'كل ٦–٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: () => 'يرش من مسافة مناسبة لمدة ٢–٣ ثوانٍ على المنطقة المصابة حتى ٣–٤ مرات يومياً.',
		warnings: ['قابل للاشتعال وقد يسبب تهيجاً/حروق برد إذا أُفرط.'],
	},

	// 294
	{
		id: 'himax-topical-spray-100-a6',
		name: 'himax topical spray 100 ml',
		genericName: 'menthol & eucalyptus & camphor & methyl salicylate',
		concentration: '100 ml',
		price: 130,
		matchKeywords: ['himax spray 100', ...tag('#analgesics')],
		usage: 'سبراي مسكن موضعي لآلام العضلات البسيطة.',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: () => 'يرش على المنطقة مع تدليك خفيف ٢–٣ مرات يومياً.',
		warnings: ['يحتوي ساليسيلات: الحذر مع حساسية الأسبرين.'],
	},

	// 297
	{
		id: 'lidocaine-2percent-10-amp-a6',
		name: 'lidocaine 2% 10 amp',
		genericName: 'lidocaine hydrochloride',
		concentration: '2% (20mg/ml)',
		price: 90,
		matchKeywords: ['lidocaine 2% 10 amp', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي/إقليمي (أمبولات) — يستخدم بواسطة مختص.',
		timing: 'حقن – جرعة واحدة حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (w: number) => lidocaineMaxDoseText(w, 20, false),
		warnings: ['جرعات زائدة قد تسبب تشنجات/اضطراب نظم.'],
	},

	// 298
	{
		id: 'lidocaine-hcl-pharmacell-2percent-vial-20ml-a6',
		name: 'lidocaine hcl pharmacell 2% vial im iv sc 20 ml',
		genericName: 'lidocaine hydrochloride',
		concentration: '2% (20mg/ml)',
		price: 9.75,
		matchKeywords: ['lidocaine pharmacell 2% vial 20', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي/إقليمي (يُستخدم بواسطة مختص).',
		timing: 'حقن – جرعة واحدة حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (w: number) => lidocaineMaxDoseText(w, 20, false),
		warnings: ['جرعات زائدة قد تسبب أعراض عامة خطيرة.'],
	},

	// 300
	{
		id: 'lidocaine-1percent-epinephrine-amp-a6',
		name: 'lidocaine hydrochloride 1% & epinephrine 0.01 mg amp',
		genericName: 'lidocaine hydrochloride & epinephrine',
		concentration: '1% (10mg/ml) + epinephrine',
		price: 43.5,
		matchKeywords: ['lidocaine 1% epinephrine amp', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي مع أدرينالين (يطيل المفعول/يقلل النزف) — يستخدم بواسطة مختص.',
		timing: 'حقن – جرعة واحدة حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (w: number) => lidocaineMaxDoseText(w, 10, true),
		warnings: ['قد يسبب خفقان/قلق بسبب الأدرينالين. تجنب في اضطراب نظم/فرط حساسية للأدرينالين.'],
	},

	// 301
	{
		id: 'restage-spray-120-a6',
		name: 'restage spray 120 ml',
		genericName: 'menthol crystal & clove oil & peppermint oil & camphor oil',
		concentration: '120 ml',
		price: 210,
		matchKeywords: ['restage spray 120', ...tag('#analgesics', '#anti-inflammatory')],
		usage: 'سبراي مساج/تبريد لتخفيف آلام العضلات البسيطة.',
		timing: 'مرة–٣ مرات يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: () => 'يرش على المنطقة ثم يُدلك بلطف ١–٣ مرات يومياً.',
		warnings: ['قد يسبب تهيجاً/حساسية.'],
	},

	// 303
	{
		id: 'stopadol-night-20-fc-tabs-a6',
		name: 'stopadol night 20 f.c.tabs.',
		genericName: 'diphenhydramine & paracetamol',
		concentration: 'F.C. Tablets',
		price: 52,
		matchKeywords: ['stopadol night 20', ...tag('#analgesics')],
		usage: 'مسكن ليلي مع مضاد حساسية مُسبب للنعاس (يساعد على النوم).',
		timing: 'مرة يومياً قبل النوم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد قبل النوم (حد أقصى ٢ قرص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'ممنوع مع الكحول/المهدئات. يُتجنب في جلوكوما/تضخم بروستاتا.'],
	},

	// 307
	{
		id: 'one-two-three-20-fc-tabs-a6',
		name: '1 2 3 (one two three) 20 f.c.tabs.',
		genericName: 'pseudoephedrine & paracetamol & chlorpheniramine maleate',
		concentration: 'F.C. Tablets',
		price: 40,
		matchKeywords: ['1 2 3 tabs 20', ...tag('#common cold')],
		usage: 'لتخفيف أعراض البرد/الإنفلونزا (ألم/حرارة + رشح/عطس + احتقان).',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144 ? 'لا يُستخدم أقل من ١٢ سنة.' : 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 308
	{
		id: 'adwiflam-diclofenac-potassium-12-5mg-supp-5-a6',
		name: 'adwiflam 12.5mg infants 5 supp.',
		genericName: 'diclofenac potassium',
		concentration: '12.5mg',
		price: 7.5,
		matchKeywords: ['adwiflam 12.5 infants supp', ...tag('#nsaid', '#acetic acid derivatives', '#antipyretics')],
		usage: 'لبوس ديكلوفيناك للأطفال (مسكن/خافض حرارة).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 36,
		minWeight: 6,
		maxWeight: 12,
		calculationRule: () => 'لبوسة واحدة (١٢.٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 309
	{
		id: 'alexoprine-aspirin-75mg-chew-100-a6',
		name: 'alexoprine 75mg 100 chew. tab.',
		genericName: 'acetylsalicylic acid',
		concentration: '75mg',
		price: 140,
		matchKeywords: ['alexoprine 75 chew 100', ...tag('#nsaid')],
		usage: 'أسبرين جرعة منخفضة (غالباً للوقاية القلبية/مضاد صفائح).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٧٥ مجم) مرة يومياً بعد الأكل.',
		warnings: ['يزيد خطر النزيف. يُتجنب مع قرحة/نزيف معدي.', 'لا يُجمع مع مميعات الدم إلا حسب التشخيص.'],
	},

	// 310
	{
		id: 'diclopro-k-diclofenac-potassium-50mg-sachets-10-a6',
		name: 'diclopro k 50 mg 10 sachet',
		genericName: 'diclofenac potassium',
		concentration: '50 mg',
		price: 50,
		matchKeywords: ['diclopro k 50 sachet', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'ديكلوفيناك سريع (أكياس) مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كيس واحد (٥٠ مجم) مرتين يومياً بعد الأكل (حد أقصى ٣ أكياس/٢٤ ساعة = ١٥٠ مجم).',
		warnings: [...commonNsaidWarnings],
	},

	// 311
	{
		id: 'anti-cox-ii-meloxicam-7-5mg-caps-20-a6',
		name: 'anti-cox ii 7.5mg 20 caps',
		genericName: 'meloxicam',
		concentration: '7.5mg',
		price: 56,
		matchKeywords: ['anti-cox ii 7.5 20', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam) بجرعة منخفضة.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (٧.٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 312
	{
		id: 'celebrex-celecoxib-100mg-caps-10-a6',
		name: 'celebrex 100mg 10 caps',
		genericName: 'celecoxib',
		concentration: '100mg',
		price: 92,
		matchKeywords: ['celebrex 100 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 (Celecoxib).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (١٠٠ مجم) مرة إلى مرتين يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 313
	{
		id: 'comtrex-acute-head-cold-20-fc-tabs-a6',
		name: 'comtrex acute head cold 20 f.c.tab.',
		genericName: 'paracetamol & brompheniramine maleate & pseudoephedrine',
		concentration: 'F.C. Tablets',
		price: 62,
		matchKeywords: ['comtrex acute head cold 20', ...tag('#common cold')],
		usage: 'أعراض البرد/الاحتقان مع صداع.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144 ? 'لا يُستخدم أقل من ١٢ سنة.' : 'قرص واحد كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 314
	{
		id: 'coughsed-paracetamol-children-12-supp-a6',
		name: 'coughsed paracetamol children 12 supp',
		genericName: 'gelsemium extract & grindelia extract & niaouli essence & paracetamol',
		concentration: 'Suppositories',
		price: 58,
		matchKeywords: ['coughsed children 12 supp', ...tag('#anti-tussive', '#antipyretics')],
		usage: 'لبوس للكحة مع خافض حرارة للأطفال.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Suppositories',
		minAgeMonths: 12,
		maxAgeMonths: 84,
		minWeight: 8,
		maxWeight: 25,
		calculationRule: () => 'لبوسة واحدة كل ٨ ساعات عند اللزوم (حد أقصى ٣ لبوس/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 315
	{
		id: 'diclasium-diclofenac-potassium-50mg-fc-tabs-30-a6',
		name: 'diclasium 50mg 30 f.c. tabs.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 54,
		matchKeywords: ['diclasium 50 30', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٥٠ مجم) مرتين يومياً بعد الأكل (حد أقصى ٣ أقراص/اليوم = ١٥٠ مجم).',
		warnings: [...commonNsaidWarnings],
	},
];

