
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);

const roundVol = (vol: number): number => Math.round(vol * 2) / 2;

const ibuprofen100mg5mlDoseText = (weight: number) => {
	// 10 مجم/كجم لكل جرعة. التركيز 100 مجم/5 مل = 20 مجم/مل
	const ml = roundVol(weight / 2);
	return `${toAr(ml)} مل لكل جرعة كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
};

const commonParacetamolWarnings = [
	'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
	'مرضى الكبد/الكحول: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
	'يفضل بعد الأكل لتقليل تهيج المعدة.',
	'لا تجمع أكثر من NSAID في نفس الوقت.',
	'يُتجنب مع قرحة/نزيف معدي أو فشل كلوي شديد، وأواخر الحمل.',
];

const tag = (...tags: string[]) => tags;

export const ANALGESICS_2: Medication[] = [

	// 50
	{
		id: 'abimol-paracetamol-500mg-tabs-20-a2',
		name: 'abimol 500 mg 20 tab.',
		genericName: 'paracetamol',
		concentration: '500 mg',
		price: 24,
		matchKeywords: ['abimol', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٥٠٠ مجم) كل ٤–٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 51
	{
		id: 'abimol-extra-caffeine-paracetamol-tabs-20-a2',
		name: 'abimol extra 20 tab.',
		genericName: 'caffeine & paracetamol',
		concentration: 'Tablets',
		price: 28,
		matchKeywords: ['abimol extra', ...tag('#analgesics', '#antipyretics', '#headache')],
		usage: 'مسكن للصداع والآلام (يحتوي كافيين).',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, 'يحتوي على كافيين: قد يسبب أرق أو خفقان.'],
	},

	// 52
	{
		id: 'abimol-paracetamol-300mg-rectal-supp-5-a2',
		name: 'abimol 300mg 5 rectal supp.',
		genericName: 'paracetamol',
		concentration: '300mg',
		price: 15,
		matchKeywords: ['abimol supp', ...tag('#antipyretics', '#analgesics')],
		usage: 'لبوس مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Suppositories',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 10,
		maxWeight: 45,
		calculationRule: (_weight: number, _ageMonths: number) => 'لبوسة واحدة كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ لبوسات/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 53
	{
		id: 'adol-paracetamol-500mg-caplets-24-a2',
		name: 'adol 500mg 24 caplets',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 32,
		matchKeywords: ['adol 500', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Caplet',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٥٠٠ مجم) كل ٤–٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 54
	{
		id: 'adwiflam-diclofenac-potassium-75mg-3ml-amp-6-a2',
		name: 'adwiflam 75mg/3ml 6 amp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg/3ml',
		price: 72,
		matchKeywords: ['adwiflam amp', ...tag('#nsaid', '#acetic acid derivatives', '#antipyretics')],
		usage: 'مسكن ومضاد التهاب (حقن ديكلوفيناك).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 55
	{
		id: 'bi-profenid-ketoprofen-150mg-scored-tabs-20-a2',
		name: 'bi-profenid 150mg 20 scored tabs.',
		genericName: 'ketoprofen',
		concentration: '150mg',
		price: 54,
		matchKeywords: ['bi-profenid 150', ...tag('#nsaid', '#propionic acid derivatives', '#analgesics', '#anti-inflammatory')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Scored Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٥٠ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 57
	{
		id: 'brufen-ibuprofen-100mg-5ml-syrup-150ml-a2',
		name: 'brufen 100mg/5ml syrup 150ml',
		genericName: 'ibuprofen',
		concentration: '100mg/5ml',
		price: 44,
		matchKeywords: ['brufen syrup', ...tag('#nsaid', '#propionic acid derivatives', '#analgesics', '#anti-inflammatory')],
		usage: 'خافض حرارة ومسكن للأطفال (إيبوبروفين).',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 45,
		calculationRule: (weight: number, _ageMonths: number) => ibuprofen100mg5mlDoseText(weight),
		warnings: [...commonNsaidWarnings],
	},

	// 58
	{
		id: 'cataflam-diclofenac-potassium-75mg-3ml-amp-6-a2',
		name: 'cataflam 75mg/3ml 6 amp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg/3ml',
		price: 120,
		matchKeywords: ['cataflam amp', ...tag('#analgesics', '#antipyretics', '#anti-inflammatory', '#nsaid')],
		usage: 'مسكن ومضاد التهاب (حقن).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 59
	{
		id: 'lubrivisc-sodium-hyaluronate-0-1-eye-drops-10ml-a2',
		name: 'lubrivisc 0.1% eye drops 10 ml',
		genericName: 'sodium hyaluronate',
		concentration: '0.1%',
		price: 32,
		matchKeywords: ['lubrivisc', ...tag('#analgesics', '#anti-inflammatory', '#eye surge')],
		usage: 'قطرة مرطبة للعين (دموع صناعية) للجفاف والتهيج.',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'نقطة أو نقطتين بكل عين عند اللزوم.',
		warnings: ['أزل العدسات اللاصقة قبل الاستخدام إن لزم.'],
	},

	// 61
	{
		id: 'proximol-proximadiol-0-4mg-sugar-coated-tabs-40-a2',
		name: 'proximol 0.4mg 40 sugar c.tabs.',
		genericName: 'proximadiol',
		concentration: '0.4mg',
		price: 34,
		matchKeywords: ['proximol', ...tag('#urinary', '#analgesics', '#antiseptics')],
		usage: 'مساعد لطرد حصوات الحالب وتطهير المسالك البولية.',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.URINARY_CARE,
		form: 'Sugar Coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد ٣ مرات يومياً بعد الأكل مع شرب ماء وفير.',
		warnings: ['الحمل/الرضاعة أو قصور الكلى: استخدم بأقل جرعة ولأقصر مدة؛ عدّل أو اختر بديلاً.'],
	},

	// 62
	{
		id: 'doliprane-paracetamol-1g-tabs-20-a2',
		name: 'doliprane 1 gm 20 tabs.',
		genericName: 'paracetamol',
		concentration: '1 gm',
		price: 60,
		matchKeywords: ['doliprane 1 gm 20', ...tag('#analgesics', '#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١ جم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 64
	{
		id: 'uricol-hexamine-khellin-piperazine-eff-6-sachets-a2',
		name: 'uricol 6 eff. gr. in sachets',
		genericName: 'hexamine & khellin & piperazine',
		concentration: 'Sachets',
		price: 21,
		matchKeywords: ['uricol', ...tag('#urinary', '#analgesics', '#antiseptics')],
		usage: 'مطهر للمسالك البولية ومضاد للتقلصات (فوار).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.URINARY_CARE,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'كيس واحد ٣ مرات يومياً. يُذاب في نصف كوب ماء ويُشرب بعد الأكل.',
		warnings: ['يحتوي على هيكسامين (يتحول لفورمالدهيد في البول المطهر).', 'ممنوع لمرضى الفشل الكلوي.'],
	},

	// 66
	{
		id: 'voltaren-sr-diclofenac-sodium-100mg-fc-tab-20-a2',
		name: 'voltaren sr 100mg 20 f.c.tab.',
		genericName: 'diclofenac sodium',
		concentration: '100mg',
		price: 132,
		matchKeywords: ['voltaren sr 100', ...tag('#nsaid', '#acetic acid derivatives', '#analgesics', '#antipyretic')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 67
	{
		id: 'paramol-paracetamol-1000mg-tabs-20-a2',
		name: 'paramol 1000 mg 20 tabs.',
		genericName: 'paracetamol',
		concentration: '1000 mg',
		price: 52,
		matchKeywords: ['paramol 1000', ...tag('#analgesics', '#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١ جم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 68
	{
		id: 'brufen-ibuprofen-600mg-eff-sachets-10-a2',
		name: 'brufen 600mg 10 eff. gr. in sachets',
		genericName: 'ibuprofen',
		concentration: '600mg',
		price: 60,
		matchKeywords: ['brufen 600 eff', ...tag('#nsaid', '#propionic acid derivatives', '#analgesics', '#anti-inflammatory')],
		usage: 'مسكن ومضاد التهاب (فوار).',
		timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'كيس واحد بعد الأكل كل ٨–١٢ ساعة عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 69
	{
		id: 'brufen-ibuprofen-200mg-tabs-30-a2',
		name: 'brufen 200mg 30 tab',
		genericName: 'ibuprofen',
		concentration: '200mg',
		price: 48,
		matchKeywords: ['brufen 200', ...tag('#nsaid', '#propionic acid derivatives', '#analgesics', '#anti-inflammatory')],
		usage: 'مسكن وخافض حرارة ومضاد التهاب.',
		timing: 'بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص 200mg بعد الأكل عند اللزوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 71
	{
		id: 'cataflam-diclofenac-potassium-75mg-supp-5-a2',
		name: 'cataflam 75mg 5 supp.',
		genericName: 'diclofenac potassium',
		concentration: '75mg',
		price: 13.25,
		matchKeywords: ['cataflam supp 75', ...tag('#analgesics', '#antipyretics', '#anti-inflammatory', '#nsaid')],
		usage: 'لبوس مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'لبوسة واحدة (٧٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوسة/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 72
	{
		id: 'cetal-paracetamol-500mg-tabs-20-a2',
		name: 'cetal 500mg 20 tab',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 24,
		matchKeywords: ['cetal 500', ...tag('#antipyretics', '#analgesics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص عند اللزوم.',
		warnings: [...commonParacetamolWarnings],
	},

	// 73
	{
		id: 'panadol-migraine-30-tabs-a2',
		name: 'panadol migraine 30 tabs',
		genericName: 'caffeine & acetaminophen & aspirin',
		concentration: 'Tablets',
		price: 51,
		matchKeywords: ['panadol migraine', ...tag('#analgesics')],
		usage: 'مسكن مخصص للصداع النصفي/الصداع.',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) =>
			'قرص إلى قرصين عند بداية الألم، ويمكن تكراره كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: ['يحتوي أسبرين: يزيد خطر النزيف وقرحة المعدة.'],
	},

	// 76
	{
		id: 'polyfresh-sodium-hyaluronate-0-2-eye-drops-sdu-20x0-4-a2',
		name: 'polyfresh 0.2% eye drops 20*0.4 ml sdu',
		genericName: 'sodium hyaluronate',
		concentration: '0.2%',
		price: 50,
		matchKeywords: ['polyfresh sdu 20', ...tag('#analgesics', '#anti-inflammatory', '#eye surge')],
		usage: 'قطرة مرطبة للعين (وحدات أحادية الجرعة).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'نقطة أو نقطتين بكل عين عند اللزوم.',
		warnings: ['لا تلمس طرف العبوة للعين.'],
	},

	// 77
	{
		id: 'polyfresh-sodium-hyaluronate-0-2-eye-drops-sdu-30x0-4-a2',
		name: 'polyfresh 0.2% eye drops 30*0.4 ml sdu',
		genericName: 'sodium hyaluronate',
		concentration: '0.2%',
		price: 95,
		matchKeywords: ['polyfresh sdu 30', ...tag('#analgesics', '#anti-inflammatory', '#eye surge')],
		usage: 'قطرة مرطبة للعين (وحدات أحادية الجرعة).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'نقطة أو نقطتين بكل عين عند اللزوم.',
		warnings: ['لا تلمس طرف العبوة للعين.'],
	},

	// 78
	{
		id: 'polyfresh-sodium-hyaluronate-0-2-eye-drops-10ml-a2',
		name: 'polyfresh 0.2% eye drops 10 ml',
		genericName: 'sodium hyaluronate',
		concentration: '0.2%',
		price: 63,
		matchKeywords: ['polyfresh 10ml', ...tag('#analgesics', '#anti-inflammatory', '#eye surge')],
		usage: 'قطرة مرطبة للعين (دموع صناعية).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'نقطة أو نقطتين بكل عين عند اللزوم.',
		warnings: ['أزل العدسات قبل الاستخدام إن لزم.'],
	},

	// 79
	{
		id: 'adolor-ketorolac-tromethamine-30mg-amp-3-a2',
		name: 'adolor 30 mg 3 amps.',
		genericName: 'ketorolac tromethamine',
		concentration: '30 mg',
		price: 36,
		matchKeywords: ['adolor', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة قوية للألم الحاد قصير المدى.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) =>
			'أمبول (٣٠ مجم) كل ٦–٨ ساعات عند اللزوم. الحد الأقصى: ٤ أمبول/٢٤ ساعة ولمدة لا تزيد عن ٥ أيام.',
		warnings: [...commonNsaidWarnings, 'ممنوع في الفشل الكلوي أو النزيف/القرحة.', 'يستخدم لفترة قصيرة فقط.'],
	},

	// 80
	{
		id: 'aggrex-acetylsalicylic-acid-75mg-tabs-60-a2',
		name: 'aggrex 75mg 60 tabs.',
		genericName: 'acetylsalicylic acid',
		concentration: '75mg',
		price: 33,
		matchKeywords: ['aggrex 75', ...tag('#nsaid', '#salicylate', '#aspirin', '#blood thinner')],
		usage: 'أسبرين منخفض الجرعة (مضاد صفائح).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٧٥ مجم) مرة يومياً.',
		warnings: ['يزيد خطر النزيف مع مميعات الدم؛ راجع التفاعلات وعدّل الجرعة.'],
	},

	// 81
	{
		id: 'amigraine-adco-ergotamine-caffeine-analgin-tabs-30-a2',
		name: 'amigraine adco 30 tablets',
		genericName: 'ergotamine tartarate & caffeine & analgin',
		concentration: 'Tablets',
		price: 93,
		matchKeywords: ['amigraine', ...tag('#anti-migraine')],
		usage: 'لعلاج نوبات الصداع النصفي.',
		timing: 'عند بداية النوبة – جرعة مفردة',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) =>
			'قرص واحد عند بداية النوبة، ويمكن تكراره بعد ٣٠–٦٠ دقيقة إذا لزم. الحد الأقصى: ٣ أقراص/٢٤ ساعة و٦ أقراص/أسبوع.',
		warnings: ['ممنوع في الحمل أو مرضى القلب/الضغط غير المنضبط؛ إن لزم فبأقل جرعة ولمدة قصيرة.'],
	},

	// 82
	{
		id: 'anti-cox-ii-meloxicam-15mg-tabs-30-a2',
		name: 'anti-cox ii 15mg 30 tab.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 111,
		matchKeywords: ['anti-cox ii 15 tab', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (NSAID - Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 83
	{
		id: 'anti-cox-ii-meloxicam-15mg-3ml-amp-6-a2',
		name: 'anti-cox ii 15mg/3ml 6 amp',
		genericName: 'meloxicam',
		concentration: '15mg/3ml',
		price: 78,
		matchKeywords: ['anti-cox ii amp', ...tag('#nsaid', '#oxicam')],
		usage: 'ميلوكسيكام حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'أمبول واحد (١٥ مجم) مرة يومياً. لا تتجاوز أمبول/اليوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 84
	{
		id: 'anti-cox-ii-meloxicam-15mg-supp-10-a2',
		name: 'anti-cox ii 15mg 10 supp',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 25.5,
		matchKeywords: ['anti-cox ii supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'لبوسة واحدة (١٥ مجم) مرة يومياً بعد الأكل/قبل النوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 85
	{
		id: 'arthrofast-diclofenac-sodium-150mg-mr-tabs-14-a2',
		name: 'arthrofast 150 mg 14 m.r. tablets',
		genericName: 'diclofenac sodium',
		concentration: '150 mg',
		price: 120,
		matchKeywords: ['arthrofast 150', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٥٠ مجم) مرة يومياً بعد الأكل (يُبلع كاملاً).',
		warnings: [...commonNsaidWarnings],
	},

	// 86
	{
		id: 'arythrex-celecoxib-200mg-caps-20-a2',
		name: 'arythrex 200mg 20 cap',
		genericName: 'celecoxib',
		concentration: '200mg',
		price: 94,
		matchKeywords: ['arythrex 200', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: ['قد يزيد خطر الجلطات عند بعض المرضى: الحذر لمرضى القلب/الضغط.', ...commonNsaidWarnings],
	},

	// 87
	{
		id: 'aspocid-acetylsalicylic-acid-75mg-tabs-20-a2',
		name: 'aspocid 75mg 20 tab.',
		genericName: 'acetylsalicylic acid',
		concentration: '75mg',
		price: 22,
		matchKeywords: ['aspocid 75', ...tag('#nsaid', '#salicylate')],
		usage: 'أسبرين منخفض الجرعة.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٧٥ مجم) مرة يومياً.',
		warnings: ['يزيد خطر النزيف.'],
	},

	// 88
	{
		id: 'bi-ketogesic-ketoprofen-150mg-tabs-30-a2',
		name: 'bi-ketogesic 150 mg 30 tab.',
		genericName: 'ketoprofen',
		concentration: '150 mg',
		price: 81,
		matchKeywords: ['bi-ketogesic 150', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٥٠ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 89
	{
		id: 'catafast-diclofenac-potassium-50mg-sachets-9-a2',
		name: 'catafast 50 mg 9 sachet',
		genericName: 'diclofenac potassium',
		concentration: '50 mg',
		price: 72,
		matchKeywords: ['catafast 50', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (فوار/أكياس).',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_weight: number, _ageMonths: number) => 'كيس واحد (٥٠ مجم) كل ٨–١٢ ساعة بعد الأكل عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 90
	{
		id: 'cetal-paracetamol-120mg-infantile-supp-5-a2',
		name: 'cetal 120 mg 5 infantile supp',
		genericName: 'paracetamol',
		concentration: '120 mg',
		price: 13,
		matchKeywords: ['cetal 120 supp', ...tag('#antipyretics')],
		usage: 'لبوس خافض حرارة للأطفال.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Suppositories',
		minAgeMonths: 3,
		maxAgeMonths: 36,
		minWeight: 5,
		maxWeight: 15,
		calculationRule: (weight: number, _ageMonths: number) =>
			weight < 8
				? 'نصف لبوسة (٦٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).'
				: 'لبوسة واحدة (١٢٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 91
	{
		id: 'cetal-paracetamol-microfined-100mg-ml-oral-drops-15ml-a2',
		name: 'cetal 100mg/ml oral drops 15 ml',
		genericName: 'paracetamol microfined',
		concentration: '100mg/ml',
		price: 23,
		matchKeywords: ['cetal drops', ...tag('#antipyretics')],
		usage: 'نقط فموية خافض حرارة للرضع.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 24,
		minWeight: 2,
		maxWeight: 12,
		calculationRule: (weight: number, _ageMonths: number) => `${toAr(Math.max(0.5, Math.round((weight * 0.15) * 2) / 2))} مل تقريباً`,
		warnings: [...commonParacetamolWarnings],
	},

	// 92
	{
		id: 'congestal-paracetamol-chlorpheniramine-pseudoephedrine-syrup-120ml-a2',
		name: 'congestal syrup 120 ml',
		genericName: 'paracetamol & chlorpheniramine maleate & pseudoephedrine',
		concentration: '120 ml',
		price: 44,
		matchKeywords: ['congestal syrup', ...tag('#common cold')],
		usage: 'أعراض البرد والرشح (خافض حرارة + مضاد حساسية + مزيل احتقان).',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Syrup',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: (_weight: number, ageMonths: number) => {
			if (ageMonths < 72) {
				return 'لا يستخدم للأطفال أقل من ٦ سنوات.';
			}
			if (ageMonths < 144) {
				return '٥ مل كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
			}
			return '١٠ مل كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
		},
		warnings: ['مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.', ...commonParacetamolWarnings],
	},

	// 93
	{
		id: 'congestal-chlorpheniramine-paracetamol-pseudoephedrine-tabs-20-a2',
		name: 'congestal 20 tabs',
		genericName: 'chlorpheniramine & paracetamol & pseudoephedrine',
		concentration: '20 tabs',
		price: 50,
		matchKeywords: ['congestal tabs', ...tag('#common cold')],
		usage: 'أعراض البرد والرشح (أقراص).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_weight: number, ageMonths: number) => {
			if (ageMonths < 144) {
				return 'لا يفضل استخدامه للأطفال أقل من ١٢ سنة؛ استخدم الشراب المخصص للأطفال';
			}
			return 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة). لا تستخدمه أكثر من ٣ أيام للحرارة أو ٥ أيام للألم.';
		},
		warnings: ['مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.', ...commonParacetamolWarnings],
	},
];

