
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;
const roundSmallVol = (vol: number): number => Math.round(vol * 10) / 10;
const tag = (...tags: string[]) => tags;

const commonParacetamolWarnings = [
	'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
	'مرضى الكبد أو من يتناولون كحول بكثرة: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
	'يفضل بعد الأكل لتقليل تهيج المعدة.',
	'لا تجمع أكثر من مسكن من مضادات الالتهاب غير الستيرويدية في نفس الوقت.',
	'يُتجنب مع قرحة أو نزيف بالمعدة، فشل كلوي شديد، وأواخر الحمل.',
];

const commonDecongestantWarnings = [
	'مزيلات الاحتقان قد تسبب أرق أو خفقان أو ترفع الضغط؛ تُستخدم بحذر لمرضى الضغط والقلب.',
	'يُمنع مع أدوية مثبطات إنزيم أحادي الأمين خلال ١٤ يوم.',
];

const lidocaineMaxDoseText = (weight: number, mgPerMl: number, withEpinephrine: boolean) => {
	const maxMg = withEpinephrine ? Math.min(weight * 7, 500) : Math.min(weight * 4.5, 300);
	const maxMl = roundSmallVol(maxMg / mgPerMl);
	return `الحد الأقصى الإجمالي = ${toAr(Math.round(maxMg))} مجم ≈ ${toAr(maxMl)} مل (لا يتكرر إلا بتوجيه مختص).`;
};

const ibuprofen100mg5mlDoseText = (weight: number) => {
	// 10 مجم/كجم لكل جرعة. التركيز 100 مجم/5 مل = 20 مجم/مل
	const ml = roundVol(weight / 2);
	return `${toAr(ml)} مل لكل جرعة كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
};

const paracetamol120mg5mlDoseText = (weight: number) => {
	// 15 مجم/كجم لكل جرعة. التركيز 120 مجم/5 مل = 24 مجم/مل
	const ml = roundVol((weight * 15) / 24);
	return `${toAr(ml)} مل لكل جرعة كل ٦ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
};

const paracetamolIv1000mg100mlDoseText = (weight: number, ageMonths: number) => {
	// ١٠ مجم/مل. الأطفال: ١٥ مجم/كجم = ١.٥ مل/كجم. البالغون (≥ ٥٠ كجم): ١٠٠ مل.
	if (ageMonths >= 144 && weight >= 50) {
		return '١٠٠ مل (١ جم) بالتسريب الوريدي كل ٦ ساعات عند اللزوم (حد أقصى ٤ مرات/٢٤ ساعة).';
	}
	const ml = roundVol(weight * 1.5);
	return `${toAr(ml)} مل (تقريباً) بالتسريب الوريدي كل ٦ ساعات عند اللزوم (حد أقصى ٤ مرات/٢٤ ساعة).`;
};

export const ANALGESICS_7: Medication[] = [
	// 316
	{
		id: 'diclosp-sr-diclofenac-sodium-75mg-30-fc-tabs-a7',
		name: 'diclosp s.r. 75mg 30 f.c. tabs.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 108,
		matchKeywords: ['diclosp sr 75 30', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sustained-release Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى ٢ قرص/٢٤ ساعة عند الضرورة ولمدة قصيرة).',
		warnings: [...commonNsaidWarnings],
	},

	// 317
	{
		id: 'epicotil-tenoxicam-20mg-adult-supp-5-a7',
		name: 'epicotil 20mg 5 adult supp',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 17.5,
		matchKeywords: ['epicotil 20 supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'لبوسة واحدة (٢٠ مجم) مرة يومياً بعد الأكل أو قبل النوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 318
	{
		id: 'epifenac-diclofenac-sodium-50mg-ec-tabs-20-a7',
		name: 'epifenac 50 mg 20 e.c. tabs.',
		genericName: 'diclofenac sodium',
		concentration: '50mg',
		price: 30,
		matchKeywords: ['epifenac 50 ec 20', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'E.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٥٠ مجم) كل ٨–١٢ ساعة بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 319
	{
		id: 'epifenac-diclofenac-sodium-75mg-3ml-amp-3-a7',
		name: 'epifenac 75 mg/3ml 3 i.m./i.v. amp.',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 36,
		matchKeywords: ['epifenac 75 3ml amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'أمبول واحد (٧٥ مجم) بالعضل أو بالوريد البطيء مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 320
	{
		id: 'eurocox-celecoxib-200mg-10-tab-a7',
		name: 'eurocox 200mg 10 tab.',
		genericName: 'celecoxib',
		concentration: '200mg',
		price: 67,
		matchKeywords: ['eurocox 200 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 321
	{
		id: 'salitroxib-etoricoxib-90mg-20-fc-tabs-a7',
		name: 'salitroxib 90 mg 20 f.c. tabs',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 140,
		matchKeywords: ['salitroxib 90 20', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 322
	{
		id: 'flamotal-ibuprofen-400mg-30-fc-tabs-a7',
		name: 'flamotal 400 mg 30 f.c.tabs.',
		genericName: 'ibuprofen',
		concentration: '400mg',
		price: 46.5,
		matchKeywords: ['flamotal 400 30', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٤٠٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 323
	{
		id: 'flamotal-ibuprofen-600mg-20-fc-tabs-a7',
		name: 'flamotal 600 mg 20 f.c.tabs.',
		genericName: 'ibuprofen',
		concentration: '600mg',
		price: 56,
		matchKeywords: ['flamotal 600 20', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (تركيز عالٍ).',
		timing: 'كل ١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٦٠٠ مجم) كل ١٢ ساعة بعد الأكل عند اللزوم (حد أقصى قرصين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 324
	{
		id: 'flamotal-ibuprofen-800mg-10-tabs-a7',
		name: 'flamotal 800 mg 10 tabs.',
		genericName: 'ibuprofen',
		concentration: '800mg',
		price: 35,
		matchKeywords: ['flamotal 800 10', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (تركيز عالٍ).',
		timing: 'كل ١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٨٠٠ مجم) كل ١٢ ساعة بعد الأكل عند اللزوم (حد أقصى قرصين/٢٤ ساعة) ولمدة قصيرة عند الحاجة.',
		warnings: [...commonNsaidWarnings],
	},

	// 325
	{
		id: 'flash-act-diclofenac-potassium-50mg-9-sachets-a7',
		name: 'flash act 50mg 9 sachets',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 30,
		matchKeywords: ['flash act 50 sachet', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب سريع المفعول (أكياس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كيس واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 326
	{
		id: 'geskaprofen-dexketoprofen-25mg-20-fc-tabs-a7',
		name: 'geskaprofen 25mg 20 f.c. tabs.',
		genericName: 'dexketoprofen',
		concentration: '25mg',
		price: 52,
		matchKeywords: ['geskaprofen 25 20', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن سريع للألم ومضاد التهاب.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٢٥ مجم) كل ٨ ساعات عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 327
	{
		id: 'cetal-paracetamol-1000mg-15-tabs-a7',
		name: 'cetal 1000mg 15 tabs',
		genericName: 'paracetamol',
		concentration: '1000mg',
		price: 42,
		matchKeywords: ['cetal 1000 15', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة (تركيز عالٍ).',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١ جم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 328
	{
		id: 'inflacam-piroxicam-20mg-dispersible-tab-10-a7',
		name: 'inflacam 20 mg 10 dispersible tab.',
		genericName: 'piroxicam',
		concentration: '20mg',
		price: 18,
		matchKeywords: ['inflacam 20 dispersible', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٢٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 329
	{
		id: 'ketofan-ketoprofen-100mg-2ml-im-amps-3-a7',
		name: 'ketofan 100mg/2ml i.m. 3 amp',
		genericName: 'ketoprofen',
		concentration: '100mg/2ml',
		price: 10.5,
		matchKeywords: ['ketofan 100 2ml amp', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'أمبول واحد (١٠٠ مجم) بالعضل عند اللزوم ويمكن تكراره بعد ١٢ ساعة (حد أقصى ٢ أمبول/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings, 'لا تُستخدم الحقن لفترة طويلة.'],
	},

	// 330
	{
		id: 'ketofan-ketoprofen-200mg-sr-cap-14-a7',
		name: 'ketofan 200mg sr 14 cap',
		genericName: 'ketoprofen',
		concentration: '200mg',
		price: 36,
		matchKeywords: ['ketofan 200 sr', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Sustained-release Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 331
	{
		id: 'ketolgin-ketoprofen-50mg-30-film-coated-tab-a7',
		name: 'ketolgin 50mg 30 film coated tab',
		genericName: 'ketoprofen',
		concentration: '50mg',
		price: 36,
		matchKeywords: ['ketolgin 50 30', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Film-coated Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 332
	{
		id: 'ketolgin-sr-ketoprofen-200mg-10-caps-a7',
		name: 'ketolgin sr 200mg 10 caps.',
		genericName: 'ketoprofen',
		concentration: '200mg',
		price: 26,
		matchKeywords: ['ketolgin sr 200', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Sustained-release Capsule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 333
	{
		id: 'melocam-meloxicam-15mg-30-tab-a7',
		name: 'melocam 15mg 30 tab.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 54,
		matchKeywords: ['melocam 15 30', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل (ولا تتجاوز ١٥ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 334
	{
		id: 'melocam-meloxicam-15mg-supp-5-a7',
		name: 'melocam 15mg 5 supp.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 8.5,
		matchKeywords: ['melocam 15 supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'لبوسة واحدة (١٥ مجم) مرة يومياً (ولا تتجاوز ١٥ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 335
	{
		id: 'melocam-meloxicam-7-5mg-20-tab-a7',
		name: 'melocam 7.5mg 20 tab.',
		genericName: 'meloxicam',
		concentration: '7.5mg',
		price: 17,
		matchKeywords: ['melocam 7.5 20', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٧.٥ مجم) مرة يومياً بعد الأكل ويمكن زيادته إلى قرصين كحد أقصى (١٥ مجم/٢٤ ساعة) حسب التشخيص.',
		warnings: [...commonNsaidWarnings],
	},

	// 336 (معرّف موجود مسبقاً لتفادي التكرار)
	{
		id: 'awadist-day-20-tabs',
		name: 'awadist cold & flu day 20 f.c. tabs.',
		genericName: 'paracetamol & pseudoephedrine & triprolidine',
		concentration: 'أقراص مغلفة',
		price: 38,
		matchKeywords: ['awadist day 20', ...tag('#common cold')],
		usage: 'لتخفيف أعراض البرد نهاراً: ألم وحرارة مع احتقان الأنف.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w, ageMonths) =>
			ageMonths < 144 ? 'لا يستخدم للأطفال أقل من ١٢ سنة.' : 'قرص واحد كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [
			...commonParacetamolWarnings,
			...commonDecongestantWarnings,
			'قد يسبب نعاساً لدى بعض الأشخاص؛ تجنب القيادة إذا حدث نعاس.',
			'يُستخدم بحذر في تضخم البروستاتا أو احتباس البول أو جلوكوما ضيقة الزاوية.',
		],
	},

	// 337
	{
		id: 'olfen-diclofenac-sodium-75mg-2ml-amp-6-a7',
		name: 'olfen 75mg/2ml 6 amp',
		genericName: 'diclofenac sodium',
		concentration: '75mg/2ml',
		price: 66,
		matchKeywords: ['olfen 75 2ml amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'أمبول واحد (٧٥ مجم) بالعضل مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 338
	{
		id: 'paramol-paracetamol-120mg-5ml-syrup-125ml-a7',
		name: 'paramol 120mg/5ml syrup 125 ml',
		genericName: 'paracetamol',
		concentration: '120mg/5ml',
		price: 36,
		matchKeywords: ['paramol 120 syrup 125', ...tag('#antipyretics')],
		usage: 'خافض حرارة ومسكن للأطفال.',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Syrup',
		minAgeMonths: 3,
		maxAgeMonths: 144,
		minWeight: 4,
		maxWeight: 45,
		calculationRule: (weight, _ageMonths) => paracetamol120mg5mlDoseText(weight),
		warnings: [...commonParacetamolWarnings, 'أعد التقييم إذا استمرت الحرارة أكثر من ٣ أيام.'],
	},

	// 339
	{
		id: 'soral-tenoxicam-20mg-20-caps-a7',
		name: 'soral 20 mg 20 caps.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 86,
		matchKeywords: ['soral 20 20', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (٢٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 340
	{
		id: 'asprotect-salicylic-acid-acetate-100mg-30-ec-tabs-a7',
		name: 'asprotect 100 mg 30 e.c.tabs.',
		genericName: 'salicylic acid acetate',
		concentration: '100mg',
		price: 54,
		matchKeywords: ['asprotect 100 30', ...tag('#nsaid', '#salicylate')],
		usage: 'جرعة منخفضة كمضاد للتجلط (٧٥–١٥٠ مجم/يوم حسب التشخيص والحالة).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'E.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٠٠ مجم) مرة يومياً بعد الأكل أو حسب التشخيص والحالة.',
		warnings: [
			'قد يزيد خطر النزيف: أعد التقييم عند كدمات شديدة أو نزيف غير معتاد.',
			'يُتجنب مع قرحة أو نزيف بالمعدة.',
			'لا يستخدم للأطفال أو المراهقين مع عدوى فيروسية إلا حسب التشخيص والسن.',
		],
	},

	// 341
	{
		id: 'atcocoxib-etoricoxib-60mg-30-tabs-a7',
		name: 'atcocoxib 60 mg 30 tabs.',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 160.5,
		matchKeywords: ['atcocoxib 60 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 342
	{
		id: 'aceliofinaz-aceclofenac-100mg-20-fc-tab-a7',
		name: 'aceliofinaz 100 mg 20 f.c. tab.',
		genericName: 'aceclofenac',
		concentration: '100 mg',
		price: 56,
		matchKeywords: ['aceliofinaz 100 20', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٠٠ مجم) مرتين يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 343
	{
		id: 'actifast-diclofenac-potassium-50mg-30-fc-tab-a7',
		name: 'actifast 50mg 30 f.c.tab.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 39,
		matchKeywords: ['actifast 50 tab 30', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب سريع المفعول.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 344
	{
		id: 'recoxitro-etoricoxib-60mg-30-fc-tabs-a7',
		name: 'recoxitro 60 mg 30 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 147,
		matchKeywords: ['recoxitro 60 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 345 (معرّف موجود مسبقاً لتفادي التكرار)
	{
		id: 'diclonatrium-sr-diclofenac-sodium-75mg-20-fc-tabs-a7',
		name: 'diclonatrium sr 75mg 20 f.c. tabs.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 58,
		matchKeywords: ['diclonatrium sr 75 20', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sustained-release Film-coated Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٧٥ مجم) مرة يومياً بعد الأكل (حد أقصى ٢ قرص/٢٤ ساعة عند الضرورة ولمدة قصيرة).',
		warnings: [...commonNsaidWarnings],
	},

	// 347
	{
		id: 'diclotazen-diclofenac-potassium-50mg-10-sachets-a7',
		name: 'diclotazen 50 mg 10 sachets',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 25,
		matchKeywords: ['diclotazen 50 sachet 10', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب سريع المفعول (أكياس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كيس واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 348
	{
		id: 'diclotazen-diclofenac-potassium-50mg-100-sachets-a7',
		name: 'diclotazen 50 mg 100 sachets',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 180,
		matchKeywords: ['diclotazen 50 sachet 100', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب سريع المفعول (أكياس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كيس واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 349 (معرّف موجود مسبقاً لتفادي التكرار)
	{
		id: 'dolo-d-plus-suspension',
		name: 'dolo-d plus oral susp. 115 ml',
		genericName: 'pseudoephedrine hydrochloride & ibuprofen & chlorpheniramine',
		concentration: '100mg + 15mg / 5ml',
		price: 41,
		matchKeywords: ['dolo-d plus 115', ...tag('#common cold')],
		usage: 'خافض حرارة ومسكن ومزيل احتقان، وقد يسبب نعاساً.',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Suspension',
		minAgeMonths: 72,
		maxAgeMonths: 144,
		minWeight: 20,
		maxWeight: 50,
		calculationRule: (_w, ageMonths) =>
			ageMonths < 72
				? 'لا يُنصح به للأطفال أقل من ٦ سنوات.'
				: '٥ مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).',
		warnings: [
			...commonNsaidWarnings,
			...commonDecongestantWarnings,
			'يسبب نعاساً؛ تجنب الأنشطة التي تحتاج تركيزاً.',
			'يُتجنب في الربو الحساس للمسكنات أو أمراض الكلى الشديدة.',
			'لا تجمعه مع أدوية برد أخرى أو مضادات حساسية أخرى دون إعادة تقييم.',
		],
	},

	// 350
	{
		id: 'dolphin-diclofenac-sodium-75mg-3ml-im-amp-3-a7',
		name: 'dolphin 75mg/3ml i.m 3 ampoule',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 30,
		matchKeywords: ['dolphin 75 3ml amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'أمبول واحد (٧٥ مجم) بالعضل مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
		warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
	},

	// 351
	{
		id: 'inestafenac-diclofenac-potassium-50mg-10-sachet-a7',
		name: 'inestafenac 50 mg 10 sachet',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 50,
		matchKeywords: ['inestafenac 50 sachet 10', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (أكياس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كيس واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 352
	{
		id: 'inflacam-piroxicam-10mg-dispersible-tab-20-a7',
		name: 'inflacam 10 mg 20 dispersible tab',
		genericName: 'piroxicam',
		concentration: '10mg',
		price: 20,
		matchKeywords: ['inflacam 10 dispersible 20', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٠ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى ٢٠ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 353
	{
		id: 'juspoled-ibuprofen-100mg-5ml-susp-120ml-a7',
		name: 'juspoled 100mg/5ml susp. 120 ml',
		genericName: 'ibuprofen',
		concentration: '100mg/5ml',
		price: 16.5,
		matchKeywords: ['juspoled 100 susp 120', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'خافض حرارة ومسكن للأطفال.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 45,
		calculationRule: (weight, _ageMonths) => ibuprofen100mg5mlDoseText(weight),
		warnings: [...commonNsaidWarnings, 'أعد التقييم إذا استمرت الحرارة أكثر من ٣ أيام.'],
	},

	// 354
	{
		id: 'lornox-lornoxicam-8mg-30-fc-tabs-a7',
		name: 'lornox 8 mg 30 f.c. tabs.',
		genericName: 'lornoxicam',
		concentration: '8 mg',
		price: 66,
		matchKeywords: ['lornox 8 30', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٨ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى قرصين/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 355
	{
		id: 'mafo-ibuprofen-400mg-30-fc-tablets-a7',
		name: 'mafo 400 mg 30 f.c.tablets',
		genericName: 'ibuprofen',
		concentration: '400mg',
		price: 42,
		matchKeywords: ['mafo 400 30', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٤٠٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 356
	{
		id: 'medalgesic-paracetamol-1g-iv-inf-100ml-a7',
		name: 'medalgesic 1 gm vial i.v. inf. 100 ml',
		genericName: 'paracetamol',
		concentration: '1g/100ml',
		price: 60,
		matchKeywords: ['medalgesic 1g 100ml', ...tag('#antipyretics')],
		usage: 'خافض حرارة ومسكن بالتسريب الوريدي (يُعطى بواسطة مختص).',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'I.V. Infusion Vial',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 250,
		calculationRule: (weight, ageMonths) => paracetamolIv1000mg100mlDoseText(weight, ageMonths),
		warnings: [...commonParacetamolWarnings, 'مرضى الكبد: استخدم بأقل جرعة ولأقصر مدة.'],
	},

	// 357
	{
		id: 'melocam-meloxicam-15mg-2ml-amp-3-a7',
		name: 'melocam 15mg/2ml 3 amp.',
		genericName: 'meloxicam',
		concentration: '15mg/2ml',
		price: 15,
		matchKeywords: ['melocam 15 amp', ...tag('#nsaid', '#oxicam')],
		usage: 'حقن مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'أمبول واحد (١٥ مجم) بالعضل مرة يومياً ولمدة قصيرة فقط (ولا تتجاوز ١٥ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 358
	{
		id: 'mobic-meloxicam-15mg-30-tab-a7',
		name: 'mobic 15 mg 30 tab.',
		genericName: 'meloxicam',
		concentration: '15 mg',
		price: 142,
		matchKeywords: ['mobic 15 30', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل (ولا تتجاوز ١٥ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 359
	{
		id: 'mobitil-meloxicam-7-5mg-10-tab-a7',
		name: 'mobitil 7.5mg 10 tab.',
		genericName: 'meloxicam',
		concentration: '7.5mg',
		price: 24,
		matchKeywords: ['mobitil 7.5 10', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٧.٥ مجم) مرة يومياً بعد الأكل ويمكن زيادته إلى قرصين كحد أقصى (١٥ مجم/٢٤ ساعة) حسب التشخيص.',
		warnings: [...commonNsaidWarnings],
	},

	// 360
	{
		id: 'roqarik-etoricoxib-90mg-20-tabs-a7',
		name: 'roqarik 90 mg 20 tabs',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 159,
		matchKeywords: ['roqarik 90 20', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 361
	{
		id: 'oblong-pharmalgin-metamizole-sodium-500mg-10-tab-a7',
		name: 'oblong pharmalgin 500mg 10 tab.',
		genericName: 'metamizole sodium',
		concentration: '500mg',
		price: 20,
		matchKeywords: ['pharmalgin oblong 500 10', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٥٠٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [
			'قد يسبب حساسية شديدة ونادرة: أوقفه فوراً واطلب رعاية عاجلة عند طفح أو تورم أو صعوبة تنفس.',
			'أعد التقييم عند التهاب حلق شديد أو حرارة مستمرة أو تقرحات بالفم.',
			'يُستخدم بحذر في أمراض الكبد أو الكلى.',
		],
	},

	// 362 (معرّف موجود مسبقاً لتفادي التكرار)
	{
		id: 'panadol-night-20-tabs',
		name: 'panadol night 20 f.c. tabs',
		genericName: 'paracetamol & diphenhydramine',
		concentration: '500mg + 25mg',
		price: 48,
		matchKeywords: ['panadol night 20', ...tag('#common cold', '#analgesics')],
		usage: 'مسكن للألم مع دواء يساعد على النوم عندما يمنع الألم النوم.',
		timing: 'مرة يومياً قبل النوم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w, ageMonths) =>
			ageMonths < 144 ? 'لا يستخدم للأطفال أقل من ١٢ سنة.' : 'قرصان معاً قبل النوم بنحو ٢٠ دقيقة (حد أقصى قرصان/٢٤ ساعة من هذا المستحضر).',
		warnings: [
			...commonParacetamolWarnings,
			'يسبب نعاساً شديداً: يمنع القيادة أو تشغيل آلات بعد تناوله.',
			'تجنب تناوله مع المهدئات أو الكحول.',
			'يُستخدم بحذر لكبار السن أو من لديهم تضخم بروستاتا أو جلوكوما ضيقة الزاوية.',
		],
	},

	// 363
	{
		id: 'paracetamol-adco-paracetamol-500mg-20-tab-a7',
		name: 'paracetamol-adco 500 mg 20 tab.',
		genericName: 'paracetamol',
		concentration: '500 mg',
		price: 24,
		matchKeywords: ['paracetamol-adco 500 20', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w, ageMonths) =>
			ageMonths < 144
				? 'يفضل للأطفال استخدام الشراب حسب الوزن.'
				: 'قرص إلى قرصين (٥٠٠–١٠٠٠ مجم) كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 364
	{
		id: 'ponstan-forte-mefenamic-acid-500mg-20-fc-tabs-a7',
		name: 'ponstan forte 500mg 20 f.c. tabs.',
		genericName: 'mefenamic acid',
		concentration: '500mg',
		price: 14,
		matchKeywords: ['ponstan forte 500 20', ...tag('#nsaid', '#fenamates')],
		usage: 'مسكن ومضاد التهاب (مفيد لآلام الدورة والآلام الحادة).',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٥٠٠ مجم) ٢–٣ مرات يومياً بعد الأكل (حد أقصى ٣ أقراص/٢٤ ساعة) ولمدة قصيرة.',
		warnings: [...commonNsaidWarnings, 'قد يسبب إسهال أو مغص عند بعض الأشخاص.'],
	},

	// 365
	{
		id: 'powcold-ibuprofen-pseudoephedrine-susp-100ml-a7',
		name: 'powcold suspension 100 ml',
		genericName: 'ibuprofen & pseudoephedrine hydrochloride',
		concentration: 'تركيبة برد',
		price: 21,
		matchKeywords: ['powcold susp 100', ...tag('#common cold')],
		usage: 'خافض حرارة ومسكن ومزيل احتقان للأطفال الأكبر سناً.',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Suspension',
		minAgeMonths: 72,
		maxAgeMonths: 144,
		minWeight: 20,
		maxWeight: 50,
		calculationRule: (_w, ageMonths) =>
			ageMonths < 72
				? 'لا يُنصح به للأطفال أقل من ٦ سنوات.'
				: '٥ مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).',
		warnings: [
			...commonNsaidWarnings,
			...commonDecongestantWarnings,
			'يُتجنب في الربو الحساس للمسكنات أو أمراض الكلى الشديدة.',
		],
	},

	// 366
	{
		id: 'rheumamax-celecoxib-100mg-10-caps-a7',
		name: 'rheumamax 100mg 10 caps.',
		genericName: 'celecoxib',
		concentration: '100mg',
		price: 19.2,
		matchKeywords: ['rheumamax 100 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (١٠٠ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى ٢٠٠ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 367 (معرّف موجود مسبقاً لتفادي التكرار)
	{
		id: 'rhinocalm-20-tabs',
		name: 'rhinocalm 20 tabs.',
		genericName: 'chlorpheniramine & paracetamol & pseudoephedrine',
		concentration: '500mg + 30mg + 2mg',
		price: 56,
		matchKeywords: ['rhinocalm 20', ...tag('#common cold')],
		usage: 'لعلاج أعراض البرد: ألم وحرارة مع رشح واحتقان.',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w, ageMonths) =>
			ageMonths < 144 ? 'لا يُفضل استخدامه أقل من ١٢ سنة.' : 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [
			...commonParacetamolWarnings,
			...commonDecongestantWarnings,
			'يسبب نعاساً: تجنب القيادة أو العمل على آلات.',
			'يُستخدم بحذر في تضخم البروستاتا أو احتباس البول أو جلوكوما ضيقة الزاوية.',
		],
	},

	// 368
	{
		id: 'soral-tenoxicam-20mg-30-caps-a7',
		name: 'soral 20 mg 30 caps.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 129,
		matchKeywords: ['soral 20 30', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (٢٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 369
	{
		id: 'temporal-paracetamol-micronized-1000mg-20-tabs-a7',
		name: 'temporal 1000 mg 20 tabs.',
		genericName: 'paracetamol micronized',
		concentration: '1000 mg',
		price: 40,
		matchKeywords: ['temporal 1000 20', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة (تركيز عالٍ).',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١ جم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 370
	{
		id: 'rheumamax-celecoxib-200mg-10-caps-a7',
		name: 'rheumamax 200mg 10 caps.',
		genericName: 'celecoxib',
		concentration: '200mg',
		price: 36,
		matchKeywords: ['rheumamax 200 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 371
	{
		id: 'xefo-lornoxicam-8mg-vial-im-iv-a7',
		name: 'xefo 8mg vial for i.m./i.v. inj.',
		genericName: 'lornoxicam',
		concentration: '8mg',
		price: 18.5,
		matchKeywords: ['xefo 8 vial', ...tag('#nsaid', '#oxicam')],
		usage: 'حقنة مسكنة ومضادة للالتهاب (تُعطى بواسطة مختص).',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'فيال واحد (٨ مجم) بالعضل أو بالوريد حسب تقدير الطبيب (حد أقصى ١٦ مجم/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 372
	{
		id: 'anselacox-etoricoxib-120mg-10-fc-tabs-a7',
		name: 'anselacox 120 mg 10 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '120 mg',
		price: 120,
		matchKeywords: ['anselacox 120 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي (جرعة عالية للألم الحاد لفترة قصيرة).',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (١٢٠ مجم) مرة يومياً بعد الأكل لمدة قصيرة فقط.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 373
	{
		id: 'coxritor-etoricoxib-60mg-30-fc-tabs-a7',
		name: 'coxritor 60 mg 30 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 282,
		matchKeywords: ['coxritor 60 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 374
	{
		id: 'actifast-diclofenac-potassium-50mg-30-sachets-a7',
		name: 'actifast 50 mg 30 sachets',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 105,
		matchKeywords: ['actifast 50 sachet 30', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب سريع المفعول (أكياس).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: () => 'كيس واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 375
	{
		id: 'realcoxstar-etoricoxib-90mg-20-fc-tabs-a7',
		name: 'realcoxstar 90 mg 20 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 133,
		matchKeywords: ['realcoxstar 90 20', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن ومضاد التهاب انتقائي.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: () => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط وخطر الجلطات عند بعض المرضى.'],
	},

	// 376 (معرّف موجود مسبقاً لتفادي التكرار)
	{
		id: 'debocaine-lidocaine-hcl-2-vial-50ml-a7',
		name: 'debocaine hcl 2% (50ml) vial',
		genericName: 'lidocaine hydrochloride',
		concentration: '2% (20mg/ml)',
		price: 33,
		matchKeywords: ['debocaine 2 vial 50', ...tag('#analgesics', '#topical anaesthetic')],
		usage: 'مخدر موضعي للحقن الموضعي (يُستخدم بواسطة مختص).',
		timing: 'حقن – حسب الإجراء',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: (weight, _ageMonths) => lidocaineMaxDoseText(weight, 20, false),
		warnings: [
			'الجرعة الزائدة قد تسبب دوخة شديدة أو تشنجات أو اضطراب ضربات القلب.',
			'يُتجنب في الحساسية تجاه مخدرات موضعية مشابهة.',
			'لا يُحقن داخل وعاء دموي بالخطأ؛ يلزم شفط قبل الحقن بواسطة المختص.',
		],
	},
];

