
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;
const roundSmallVol = (vol: number): number => Math.round(vol * 10) / 10;

const tag = (...tags: string[]) => tags;

const commonParacetamolWarnings = [
	'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
	'مرضى الكبد/الكحول: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
	'يفضل بعد الأكل لتقليل تهيج المعدة.',
	'لا تجمع أكثر من NSAID في نفس الوقت.',
	'يُتجنب مع قرحة/نزيف معدي أو فشل كلوي شديد، وأواخر الحمل.',
];

const ibuprofen100mg5mlDose = (weight: number) => {
	// 10 mg/kg per dose. Concentration 100mg/5ml => 20 mg/ml => ml = mg/20 = weight/2
	const ml = roundVol(weight / 2);
	return `${toAr(ml)} مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
};

const paracetamol250mg5mlDose = (weight: number) => {
	// 15 mg/kg per dose. Concentration 250mg/5ml => 50 mg/ml => ml = (weight*15)/50
	const ml = roundVol((weight * 15) / 50);
	return `${toAr(ml)} مل كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
};

const paracetamol100mgmlDropsDose = (weight: number) => {
	// 15 mg/kg. Concentration 100 mg/ml => ml = 0.15 ml/kg
	const ml = roundSmallVol(weight * 0.15);
	const minDrops = Math.round(weight * 2);
	const maxDrops = Math.round(weight * 3);
	return `${toAr(ml)} مل تقريباً (${toAr(minDrops)}–${toAr(maxDrops)} نقط) كل ٦ ساعات عند اللزوم.`;
};

export const ANALGESICS_5: Medication[] = [
	// 201
	{
		id: 'ketorolin-30-amp',
		name: 'ketorolin 30mg/2ml 5 amp.',
		genericName: 'ketorolac',
		concentration: '30mg/2ml',
		price: 50,
		matchKeywords: ['ketorolin 30 amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'حقن مسكنة قوية (NSAID) للألم الحاد قصير المدى.',
		timing: 'كل ٦–٨ ساعات عند الألم – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 192,
		maxAgeMonths: 780,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول (٣٠ مجم) كل ٦–٨ ساعات عند اللزوم. الحد الأقصى: ٤ أمبول/٢٤ ساعة ولمدة لا تزيد عن ٥ أيام.',
		warnings: [...commonNsaidWarnings, 'ممنوع في الفشل الكلوي أو النزيف/القرحة.'],
	},

	// 202
	{
		id: 'anselacox-etoricoxib-30mg-fc-tabs-10-a5',
		name: 'anselacox 30mg 10 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '30mg',
		price: 39,
		matchKeywords: ['anselacox 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 حسب الحاجة.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٣٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 203
	{
		id: 'recoxitro-etoricoxib-90mg-fc-tabs-30-a5',
		name: 'recoxitro 90 mg 30 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 156,
		matchKeywords: ['recoxitro 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 لآلام/التهاب المفاصل.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'ممنوع لمرضى القلب/الذبحة غير المستقرة.'],
	},

	// 204
	{
		id: 'xyrkux-etoricoxib-60mg-tabs-20-a5',
		name: 'xyrkux 60 mg 20 tabs',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 188,
		matchKeywords: ['xyrkux 60', ...tag('#nsaid')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 205
	{
		id: 'medexaflam-meloxicam-15mg-supp-12-a5',
		name: 'medexaflam 15mg 12 supp.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 52,
		matchKeywords: ['medexaflam supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٥ مجم) مرة يومياً بعد الأكل/قبل النوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 206
	{
		id: 'medexaflam-meloxicam-15mg-tabs-20-a5',
		name: 'medexaflam 15mg 20 tabs.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 36,
		matchKeywords: ['medexaflam 15 tabs', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 207
	{
		id: 'megafen-ibuprofen-paracetamol-tabs-30-a5',
		name: 'megafen 30 tab',
		genericName: 'ibuprofen & paracetamol',
		concentration: 'Tablets',
		price: 60,
		matchKeywords: ['megafen 30', ...tag('#nsaid')],
		usage: 'مسكن مركب (NSAID + باراسيتامول).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 208
	{
		id: 'megafen-n-ibuprofen-100mg-5ml-susp-120ml-a5',
		name: 'megafen-n 100mg/5ml susp. 120 ml',
		genericName: 'ibuprofen',
		concentration: '100mg/5ml',
		price: 35,
		matchKeywords: ['megafen-n susp', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن وخافض حرارة للأطفال.',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 180,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: (w: number, _a: number) => ibuprofen100mg5mlDose(w),
		warnings: [...commonNsaidWarnings],
	},

	// 209
	{
		id: 'meloxicam-15mg-2ml-amps-3-a5',
		name: 'meloxicam 15mg/2ml 3 amp.',
		genericName: 'meloxicam',
		concentration: '15mg/2ml',
		price: 39,
		matchKeywords: ['meloxicam amp', ...tag('#nsaid', '#oxicam')],
		usage: 'ميلوكسيكام حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (١٥ مجم) مرة يومياً. لا تتجاوز أمبول/اليوم.',
		warnings: [...commonNsaidWarnings],
	},

	// 210
	{
		id: 'meloxicam-15mg-supp-5-a5',
		name: 'meloxicam 15mg 5 supp.',
		genericName: 'meloxicam',
		concentration: '15mg',
		price: 8.5,
		matchKeywords: ['meloxicam supp 15', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس ميلوكسيكام مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٥ مجم) مرة يومياً.',
		warnings: [...commonNsaidWarnings],
	},

	// 211
	{
		id: 'moxen-meloxicam-15mg-tabs-20-a5',
		name: 'moxen 15 mg 20 tabs',
		genericName: 'meloxicam',
		concentration: '15 mg',
		price: 46,
		matchKeywords: ['moxen 15', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٥ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 212
	{
		id: 'no-migrain-ergotamine-paracetamol-domperidone-30-fc-tab-a5',
		name: 'no-migrain 30 f.c. tab',
		genericName: 'ergotamine tartarate & paracetamol & domperidone',
		concentration: 'F.C. Tablets',
		price: 93,
		matchKeywords: ['no-migrain 30', ...tag('#anti-migraine')],
		usage: 'لعلاج نوبات الصداع النصفي.',
		timing: 'عند بداية النوبة – جرعة مفردة',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد عند بداية النوبة، ويمكن تكراره بعد ٣٠–٦٠ دقيقة إذا لزم. الحد الأقصى: ٣ أقراص/٢٤ ساعة و٦ أقراص/أسبوع.',
		warnings: [...commonParacetamolWarnings, 'ممنوع في الحمل وأمراض القلب/الضغط غير المنضبط.'],
	},

	// 213
	{
		id: 'no-migrain-ergotamine-paracetamol-domperidone-20-fc-tab-a5',
		name: 'no-migrain 20 f.c. tab. (n/a)',
		genericName: 'ergotamine tartarate & paracetamol & domperidone',
		concentration: 'F.C. Tablets',
		price: 42,
		matchKeywords: ['no-migrain 20', ...tag('#anti-migraine')],
		usage: 'لعلاج نوبات الصداع النصفي.',
		timing: 'عند بداية النوبة – جرعة مفردة',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد عند بداية النوبة، ويمكن تكراره بعد ٣٠–٦٠ دقيقة إذا لزم. الحد الأقصى: ٣ أقراص/٢٤ ساعة و٦ أقراص/أسبوع.',
		warnings: [...commonParacetamolWarnings, 'ممنوع في الحمل وأمراض القلب/الضغط غير المنضبط.'],
	},

	// 214
	{
		id: 'novalgin-metamizole-500mg-ml-amps-3-im-iv-a5',
		name: 'novalgin 500mg/ml 3 amp. for i.m./i.v. inj.',
		genericName: 'metamizole sodium',
		concentration: '500mg/ml',
		price: 33,
		matchKeywords: ['novalgin amp', ...tag('#antipyretics')],
		usage: 'مسكن/خافض حرارة (Metamizole) — يُعطى بالحقن.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Ampoules',
		minAgeMonths: 3,
		maxAgeMonths: 1200,
		minWeight: 4,
		maxWeight: 250,
		calculationRule: (w: number, a: number) => {
			const doseMg = Math.round(w * 10);
			const ml = roundSmallVol(doseMg / 500);
			if (a < 36) {
				return `${toAr(ml)} مل (${toAr(doseMg)} مجم) كل ٨ ساعات عند اللزوم (يعطى بواسطة مختص فقط).`;
			}
			return `${toAr(ml)} مل (${toAr(doseMg)} مجم) كل ٦–٨ ساعات عند اللزوم (يعطى بواسطة مختص فقط).`;
		},
		warnings: ['قد يسبب حساسية شديدة أو هبوط ضغط. نادراً: نقص عدلات (Agranulocytosis). اطلب رعاية عاجلة عند طفح/ضيق نفس/حمى غير مفسرة.'],
	},

	// 215
	{
		id: 'pain-reliefer-diclofenac-vitamins-b-caps-30-a5',
		name: 'pain reliefer 30 caps.',
		genericName: 'diclofenac sodium & vitamin b1 & vitamin b6 & vitamin b12',
		concentration: 'Capsules',
		price: 72,
		matchKeywords: ['pain reliefer', ...tag('#nsaid', '#vitamin b')],
		usage: 'مسكن ومضاد التهاب مع فيتامينات ب لدعم الأعصاب.',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Capsules',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة مرتين يومياً بعد الأكل (حد أقصى ٣ كبسولات/اليوم).',
		warnings: [...commonNsaidWarnings],
	},

	// 216
	{
		id: 'paragesic-paracetamol-500mg-rectal-supp-5-a5',
		name: 'paragesic 500 mg 5 rectal supp.',
		genericName: 'paracetamol',
		concentration: '500 mg',
		price: 26,
		matchKeywords: ['paragesic 500 supp', ...tag('#antipyretics')],
		usage: 'لبوس باراسيتامول خافض حرارة/مسكن.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Suppositories',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 25,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٥٠٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ لبوسات/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 217
	{
		id: 'parofen-30-tabs',
		name: 'parofen 30 oblong tab.',
		genericName: 'ibuprofen & paracetamol',
		concentration: 'Tablets',
		price: 69,
		matchKeywords: ['parofen 30', ...tag('#nsaid')],
		usage: 'مسكن مزدوج (باراسيتامول + إيبوبروفين).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 218
	{
		id: 'pentaflu-syrup-100ml-a5',
		name: 'pentaflu syrup 100 ml',
		genericName: 'dextromethorphan hydrobromide & paracetamol',
		concentration: '100 ml',
		price: 34,
		matchKeywords: ['pentaflu syrup', ...tag('#common cold')],
		usage: 'شراب للكحة/أعراض البرد (مهدئ كحة + باراسيتامول).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Syrup',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) => (ageMonths < 144 ? '٥ مل كل ٨ ساعات (حد أقصى ٤ جرعات/٢٤ ساعة).' : '١٠ مل كل ٨ ساعات (حد أقصى ٤ جرعات/٢٤ ساعة).'),
		warnings: [...commonParacetamolWarnings, 'تأكد من تركيز العبوة (قد يختلف بين الشركات).'],
	},

	// 219
	{
		id: 'soral-tenoxicam-20mg-supp-5-a5',
		name: 'soral 20mg 5 supp.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 30,
		matchKeywords: ['soral 20 supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٢٠ مجم) مرة يومياً.',
		warnings: [...commonNsaidWarnings],
	},

	// 220
	{
		id: 'soral-tenoxicam-20mg-vial-3-im-iv-a5',
		name: 'soral 20mg 3 vial i.m./i.v.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 38,
		matchKeywords: ['soral vial', ...tag('#nsaid', '#oxicam')],
		usage: 'تينوكسيكام حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'فيال واحد (٢٠ مجم) مرة يومياً (IM/IV) بواسطة مختص.',
		warnings: [...commonNsaidWarnings],
	},

	// 221
	{
		id: 'temporal-paracetamol-250mg-5ml-susp-60ml-a5',
		name: 'temporal 250mg/5ml susp. 60 ml',
		genericName: 'paracetamol',
		concentration: '250mg/5ml',
		price: 20,
		matchKeywords: ['temporal susp', ...tag('#antipyretics')],
		usage: 'خافض حرارة ومسكن للأطفال.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Suspension',
		minAgeMonths: 2,
		maxAgeMonths: 144,
		minWeight: 4,
		maxWeight: 45,
		calculationRule: (w: number, _a: number) => paracetamol250mg5mlDose(w),
		warnings: [...commonParacetamolWarnings],
	},

	// 222
	{
		id: 'unicetamol-drops',
		name: 'unicetamol 100mg/ml oral drops 15 ml',
		genericName: 'paracetamol',
		concentration: '100mg/ml',
		price: 23,
		matchKeywords: ['unicetamol drops', ...tag('#antipyretics')],
		usage: 'نقط باراسيتامول للرضع.',
		timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 36,
		minWeight: 2,
		maxWeight: 15,
		calculationRule: (w: number, _a: number) => paracetamol100mgmlDropsDose(w),
		warnings: [...commonParacetamolWarnings],
	},

	// 223
	{
		id: 'coxritor-etoricoxib-90mg-fc-tabs-30-a5',
		name: 'coxritor 90 mg 30 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 297,
		matchKeywords: ['coxritor 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 224
	{
		id: 'rumaximap-etoricoxib-120mg-fc-tab-10-a5',
		name: 'rumaximap 120mg 10 f.c. tab',
		genericName: 'etoricoxib',
		concentration: '120mg',
		price: 65.75,
		matchKeywords: ['rumaximap 120 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 بجرعة أعلى (عادة لفترة قصيرة).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٢٠ مجم) مرة يومياً لمدة قصيرة فقط.',
		warnings: [...commonNsaidWarnings, 'قد يزيد الضغط/خطر الجلطات عند بعض المرضى.'],
	},

	// 225
	{
		id: 'anoxicam-tenoxicam-20mg-tabs-20-a5',
		name: 'anoxicam 20mg 20 tab.',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 39,
		matchKeywords: ['anoxicam 20 tab', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 226
	{
		id: 'arcoxia-etoricoxib-60mg-fc-tabs-14-a5',
		name: 'arcoxia 60 mg 14 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '60 mg',
		price: 224,
		matchKeywords: ['arcoxia 60 14', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 (أركوكسيا).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 227
	{
		id: 'arthineur-diclofenac-vitb-caps-10-a5',
		name: 'arthineur 10 caps.',
		genericName: 'diclofenac sodium & vitamin b1 (thiamine) & pyridoxine hydroc',
		concentration: 'Capsules',
		price: 23,
		matchKeywords: ['arthineur', ...tag('#nsaid', '#vitamin b')],
		usage: 'مسكن ومضاد التهاب مع فيتامينات ب.',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Capsules',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة مرتين يومياً بعد الأكل (حد أقصى ٣ كبسولات/اليوم).',
		warnings: [...commonNsaidWarnings],
	},

	// 228
	{
		id: 'baby-relief-diclofenac-sodium-12-5mg-supp-5-a5',
		name: 'baby relief 12.5mg 5 supp.',
		genericName: 'diclofenac sodium',
		concentration: '12.5mg',
		price: 12,
		matchKeywords: ['baby relief 12.5 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك للأطفال (مسكن/مضاد التهاب).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 84,
		minWeight: 7,
		maxWeight: 15,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٢.٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 229
	{
		id: 'baby-relief-diclofenac-sodium-25mg-supp-5-a5',
		name: 'baby relief 25mg 5 supp.',
		genericName: 'diclofenac sodium',
		concentration: '25mg',
		price: 9,
		matchKeywords: ['baby relief 25 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك للأطفال (مسكن/مضاد التهاب).',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 72,
		maxAgeMonths: 144,
		minWeight: 15,
		maxWeight: 30,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٢٥ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 230
	{
		id: 'bristaflam-aceclofenac-100mg-fc-tabs-20-a5',
		name: 'bristaflam 100 mg 20 f.c.tabs.',
		genericName: 'aceclofenac',
		concentration: '100 mg',
		price: 102,
		matchKeywords: ['bristaflam 100', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (Aceclofenac).',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٠٠ مجم) مرتين يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 231
	{
		id: 'brufen-flu-ibuprofen-pseudoephedrine-susp-60ml-a5',
		name: 'brufen flu 60ml susp',
		genericName: 'ibuprofen & pseudoephedrine hydrochloride',
		concentration: '60ml',
		price: 9,
		matchKeywords: ['brufen flu susp', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'شراب للبرد/الاحتقان (يحتوي على NSAID + مزيل احتقان).',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Suspension',
		minAgeMonths: 72,
		maxAgeMonths: 144,
		minWeight: 20,
		maxWeight: 50,
		calculationRule: (_w: number, ageMonths: number) => {
			if (ageMonths < 72) return 'لا يُنصح به أقل من ٦ سنوات.';
			if (ageMonths < 144) return '٥ مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).';
			return 'للبالغين: يُفضل الأقراص. إذا استُخدم: ١٠ مل كل ٦–٨ ساعات (حد أقصى ٤ جرعات/٢٤ ساعة).';
		},
		warnings: [...commonNsaidWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 232
	{
		id: 'buscopan-compositum-20-sugar-coated-tabs-a5',
		name: 'buscopan compositum 20 sugar c. tab.',
		genericName: 'hyoscine-n-butylbromide & analgin',
		concentration: 'Sugar Coated Tablets',
		price: 20,
		matchKeywords: ['buscopan compositum', ...tag('#nsaid', '#antispasmodics')],
		usage: 'مسكن + مضاد تقلصات للمغص الشديد قصير المدى.',
		timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.ANTISPASMODIC,
		form: 'Sugar Coated Tablets',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) => (ageMonths >= 180 ? 'قرص واحد كل ٨–١٢ ساعة عند اللزوم بعد الأكل (حد أقصى ٨ أقراص/اليوم).' : 'غير موصى به عادةً أقل من ١٥ سنة بهذا المستحضر.'),
		warnings: ['قد يسبب نعاس/دوخة. اطلب رعاية عاجلة عند طفح شديد/ضيق تنفس/إغماء.'],
	},

	// 233
	{
		id: 'celeborg-celecoxib-200mg-caps-10-a5',
		name: 'celeborg 200mg 10 caps.',
		genericName: 'celecoxib',
		concentration: '200mg',
		price: 49.5,
		matchKeywords: ['celeborg 200 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 (Celecoxib).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 234
	{
		id: 'celebrex-celecoxib-200mg-caps-10-a5',
		name: 'celebrex 200mg 10 caps.',
		genericName: 'celecoxib',
		concentration: '200mg',
		price: 132,
		matchKeywords: ['celebrex 200 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 (Celebrex).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 235
	{
		id: 'celebrex-celecoxib-200mg-caps-15-a5',
		name: 'celebrex 200mg 15 caps.',
		genericName: 'celecoxib',
		concentration: '200mg',
		price: 198,
		matchKeywords: ['celebrex 200 15', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 (Celebrex).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 236
	{
		id: 'cevamol-paracetamol-vitc-eff-tab-12-a5',
		name: 'cevamol 12 eff. tab.',
		genericName: 'paracetamol microfined & ascorbic acid (vitamin c)',
		concentration: 'Effervescent Tablets',
		price: 59,
		matchKeywords: ['cevamol 12 eff', ...tag('#common cold')],
		usage: 'فوار باراسيتامول + فيتامين C لأعراض البرد/الحرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Effervescent Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يفضل استخدامه أقل من ١٢ سنة بسبب تركيز الباراسيتامول العالي.'
				: 'قرص فوار واحد في نصف كوب ماء كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 237
	{
		id: 'dispercam-piroxicam-10mg-dispersible-tab-20-a5',
		name: 'dispercam 10mg 20 dispersible tab.',
		genericName: 'piroxicam',
		concentration: '10mg',
		price: 22,
		matchKeywords: ['dispercam 10 dispersible', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٠ مجم) مرة إلى مرتين يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 238
	{
		id: 'dispercam-piroxicam-20mg-dispersible-tab-10-a5',
		name: 'dispercam 20mg 10 dispersible tab.',
		genericName: 'piroxicam',
		concentration: '20mg',
		price: 18,
		matchKeywords: ['dispercam 20 dispersible', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 239
	{
		id: 'dolphin-diclofenac-sodium-50mg-supp-10-a5',
		name: 'dolphin 50mg 10 supp',
		genericName: 'diclofenac sodium',
		concentration: '50mg',
		price: 48,
		matchKeywords: ['dolphin 50 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 120,
		maxAgeMonths: 1200,
		minWeight: 25,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٥٠ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 240
	{
		id: 'dolphin-k-diclofenac-potassium-50mg-fc-tab-20-a5',
		name: 'dolphin k 50mg 20 f.c. tab.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 42,
		matchKeywords: ['dolphin k 50', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠ مجم) مرتين يومياً بعد الأكل (حد أقصى ٣ أقراص/اليوم).',
		warnings: [...commonNsaidWarnings],
	},

	// 241
	{
		id: 'epicotil-tenoxicam-20mg-vial-3-im-iv-a5',
		name: 'epicotil 20mg i.m./i.v. 3 vial',
		genericName: 'tenoxicam',
		concentration: '20mg',
		price: 48,
		matchKeywords: ['epicotil vial 3', ...tag('#nsaid', '#oxicam')],
		usage: 'تينوكسيكام حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.ANALGESICS,
		form: 'Vial',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'فيال واحد (٢٠ مجم) مرة يومياً (IM/IV) بواسطة مختص.',
		warnings: [...commonNsaidWarnings],
	},

	// 242
	{
		id: 'epifenac-diclofenac-sodium-100mg-rectal-supp-5-a5',
		name: 'epifenac 100mg 5 rectal supp.',
		genericName: 'diclofenac sodium',
		concentration: '100mg',
		price: 21,
		matchKeywords: ['epifenac 100 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (١٠٠ مجم) مرة يومياً (حد أقصى لبوسة/اليوم).',
		warnings: [...commonNsaidWarnings],
	},

	// 243
	{
		id: 'epifenac-diclofenac-sodium-100mg-sr-caps-10-a5',
		name: 'epifenac 100mg s.r. 10 caps.',
		genericName: 'diclofenac sodium',
		concentration: '100mg',
		price: 33,
		matchKeywords: ['epifenac 100 sr', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'ديكلوفيناك ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'S.R. Capsule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (١٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 244
	{
		id: 'epifenac-diclofenac-sodium-50mg-supp-5-a5',
		name: 'epifenac 50 mg 5 supp.',
		genericName: 'diclofenac sodium',
		concentration: '50 mg',
		price: 8.75,
		matchKeywords: ['epifenac 50 supp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'لبوس ديكلوفيناك مسكن ومضاد التهاب.',
		timing: 'كل ١٢ ساعة عند الألم – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'Suppositories',
		minAgeMonths: 120,
		maxAgeMonths: 1200,
		minWeight: 25,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٥٠ مجم) كل ١٢ ساعة عند اللزوم (حد أقصى ٢ لبوس/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings],
	},

	// 245
	{
		id: 'coxorizet-etoricoxib-90mg-tabs-30-a5',
		name: 'coxorizet 90 mg 30 tabs',
		genericName: 'etoricoxib',
		concentration: '90 mg',
		price: 249,
		matchKeywords: ['coxorizet 90', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 246
	{
		id: 'feldene-piroxicam-10mg-caps-20-a5',
		name: 'feldene 10mg 20 caps',
		genericName: 'piroxicam',
		concentration: '10mg',
		price: 26.25,
		matchKeywords: ['feldene 10 caps', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (١٠ مجم) مرة إلى مرتين يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 247
	{
		id: 'feldene-piroxicam-10mg-dispersible-tab-20-a5',
		name: 'feldene 10mg 20 dispersible .tab',
		genericName: 'piroxicam',
		concentration: '10mg',
		price: 29,
		matchKeywords: ['feldene 10 dispersible', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam) أقراص تذوب/تتشتت.',
		timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Oral Dispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٠ مجم) مرة إلى مرتين يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 248
	{
		id: 'feldene-piroxicam-20mg-caps-10-a5',
		name: 'feldene 20mg 10 caps.',
		genericName: 'piroxicam',
		concentration: '20mg',
		price: 41.5,
		matchKeywords: ['feldene 20 caps', ...tag('#nsaid', '#oxicam')],
		usage: 'مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٢٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 249
	{
		id: 'feldene-piroxicam-20mg-supp-5-a5',
		name: 'feldene 20mg 5 supp.',
		genericName: 'piroxicam',
		concentration: '20mg',
		price: 23.5,
		matchKeywords: ['feldene 20 supp', ...tag('#nsaid', '#oxicam')],
		usage: 'لبوس مسكن ومضاد التهاب (Oxicam).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Suppositories',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'لبوسة واحدة (٢٠ مجم) مرة يومياً.',
		warnings: [...commonNsaidWarnings],
	},

	// 250
	{
		id: 'ketofan-ketoprofen-100mg-sr-caps-30-a5',
		name: 'ketofan 100mg sr 30 caps.',
		genericName: 'ketoprofen',
		concentration: '100mg',
		price: 66,
		matchKeywords: ['ketofan 100 sr', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'كيتوبروفين ممتد المفعول.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'S.R. Capsule',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (١٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 251
	{
		id: 'ketofan-ketoprofen-25mg-tabs-20-a5',
		name: 'ketofan 25 mg 20 tabs.',
		genericName: 'ketoprofen',
		concentration: '25 mg',
		price: 7.5,
		matchKeywords: ['ketofan 25 20', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن ومضاد التهاب (NSAID).',
		timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 180,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٢٥ مجم) ٢–٣ مرات يومياً بعد الأكل (حد أقصى ٣ أقراص/اليوم).',
		warnings: [...commonNsaidWarnings],
	},

	// 252
	{
		id: 'mafo-ibuprofen-100mg-5ml-syrup-100ml-a5',
		name: 'mafo 100mg/5ml syrup 100 ml',
		genericName: 'ibuprofen',
		concentration: '100mg/5ml',
		price: 25,
		matchKeywords: ['mafo syrup', ...tag('#nsaid', '#propionic acid derivatives')],
		usage: 'مسكن وخافض حرارة للأطفال.',
		timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
		category: Category.IBUPROFEN,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 180,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: (w: number, _a: number) => ibuprofen100mg5mlDose(w),
		warnings: [...commonNsaidWarnings],
	},

	// 253
	{
		id: 'megafen-ibuprofen-paracetamol-tabs-20-a5',
		name: 'megafen 20 tab',
		genericName: 'ibuprofen & paracetamol',
		concentration: 'Tablets',
		price: 18,
		matchKeywords: ['megafen 20', ...tag('#nsaid')],
		usage: 'مسكن مركب (NSAID + باراسيتامول).',
		timing: 'كل ٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings, ...commonNsaidWarnings],
	},

	// 254
	{
		id: 'paracetamol-500mg-tabs-20-bp80-pharco-a5',
		name: 'paracetamol 500mg 20 tab. b.p.80 pharco (n/a)',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 1.5,
		matchKeywords: ['paracetamol bp80 pharco 500', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 255
	{
		id: 'paracetamol-mup-500mg-tabs-20-a5',
		name: 'paracetamol-mup 500mg b.p. 20 tab.',
		genericName: 'paracetamol',
		concentration: '500mg',
		price: 13,
		matchKeywords: ['paracetamol-mup 500', ...tag('#antipyretics')],
		usage: 'مسكن وخافض حرارة.',
		timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
		category: Category.PARACETAMOL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠٠ مجم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
		warnings: [...commonParacetamolWarnings],
	},

	// 256
	{
		id: 'pentacold-syrup-120ml-a5',
		name: 'pentacold syrup 120 ml',
		genericName: 'chlorpheniramine maleate & dextromethorphan hydrobromide',
		concentration: '120 ml',
		price: 32,
		matchKeywords: ['pentacold syrup', ...tag('#common cold')],
		usage: 'شراب للكحة/أعراض البرد (قد يسبب نعاس).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Syrup',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 20,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) => (ageMonths < 144 ? '٥ مل كل ٨ ساعات (حد أقصى ٤ جرعات/٢٤ ساعة).' : '١٠ مل كل ٨ ساعات (حد أقصى ٤ جرعات/٢٤ ساعة).'),
		warnings: ['تأكد من تركيز العبوة (قد يختلف بين الشركات).', 'قد يسبب نعاساً؛ تجنب المهدئات/الكحول.'],
	},

	// 257
	{
		id: 'pharofen-diclofenac-sodium-75mg-4-amp-a5',
		name: 'pharofen 75mg 4 amp.',
		genericName: 'diclofenac sodium',
		concentration: '75mg',
		price: 44,
		matchKeywords: ['pharofen 75 amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'ديكلوفيناك حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) مرة يومياً. في الحالات الشديدة يمكن أمبولان/اليوم كحد أقصى.',
		warnings: [...commonNsaidWarnings],
	},

	// 258
	{
		id: 'rapidus-diclofenac-potassium-50mg-fc-tabs-20-a5',
		name: 'rapidus 50mg 20 f.c. tabs.',
		genericName: 'diclofenac potassium',
		concentration: '50mg',
		price: 29.1,
		matchKeywords: ['rapidus 50', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'مسكن سريع ومضاد التهاب (NSAID).',
		timing: 'كل ١٢ ساعة بعد الأكل – ٣–٥ أيام',
		category: Category.DICLOFENAC,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٥٠ مجم) مرتين يومياً بعد الأكل (حد أقصى ٣ أقراص/اليوم = ١٥٠ مجم).',
		warnings: [...commonNsaidWarnings],
	},

	// 259
	{
		id: 'recoxibright-etoricoxib-60mg-fc-tabs-20-a5',
		name: 'recoxibright 60mg 20 f.c. tabs.',
		genericName: 'etoricoxib',
		concentration: '60mg',
		price: 188,
		matchKeywords: ['recoxibright 60 20', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٦٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 260
	{
		id: 'rheumarene-diclofenac-sodium-75mg-3ml-amps-3-a5',
		name: 'rheumarene 75mg/3ml 3 amp. i.m',
		genericName: 'diclofenac sodium',
		concentration: '75mg/3ml',
		price: 27,
		matchKeywords: ['rheumarene amp', ...tag('#nsaid', '#acetic acid derivatives')],
		usage: 'ديكلوفيناك حقن مسكن ومضاد التهاب.',
		timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
		category: Category.DICLOFENAC,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'أمبول واحد (٧٥ مجم) مرة يومياً (IM).',
		warnings: [...commonNsaidWarnings],
	},

	// 261
	{
		id: 'sinlerg-tabs-20-a5',
		name: 'sinlerg 20 tabs.',
		genericName: 'chlorpheniramine & ibuprofen & pseudoephedrine',
		concentration: 'Tablets',
		price: 56,
		matchKeywords: ['sinlerg 20', ...tag('#common cold')],
		usage: 'أعراض البرد/الجيوب (NSAID + مزيل احتقان + مضاد حساسية).',
		timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
		category: Category.COLD_FLU,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: (_w: number, ageMonths: number) =>
			ageMonths < 144
				? 'لا يُنصح به أقل من ١٢ سنة.'
				: 'قرص واحد كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
		warnings: [...commonNsaidWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان.'],
	},

	// 262
	{
		id: 'spasmopyralgin-m-25x10-tabs-a5',
		name: 'spasmopyralgin-m 25*10 tablets',
		genericName: 'camylofin & analgin',
		concentration: 'Tablets',
		price: 525,
		matchKeywords: ['spasmopyralgin-m 25x10', ...tag('#antispasmodics')],
		usage: 'مضاد تقلصات + مسكن للمغص.',
		timing: 'عند الألم – لفترة قصيرة',
		category: Category.ANTISPASMODIC,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد حتى ٣ مرات يومياً بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/اليوم).',
		warnings: ['الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.'],
	},

	// 263
	{
		id: 'arcoxia-etoricoxib-120mg-fc-tabs-7-a5',
		name: 'arcoxia 120 mg 7 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '120 mg',
		price: 137,
		matchKeywords: ['arcoxia 120 7', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 بجرعة أعلى (عادة لفترة قصيرة).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (١٢٠ مجم) مرة يومياً لمدة قصيرة فقط.',
		warnings: [...commonNsaidWarnings],
	},

	// 264
	{
		id: 'celeborg-celecoxib-200mg-caps-20-a5',
		name: 'celeborg 200 mg 20 caps.',
		genericName: 'celecoxib',
		concentration: '200 mg',
		price: 99,
		matchKeywords: ['celeborg 200 20', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2 (Celecoxib).',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'كبسولة واحدة (٢٠٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 265
	{
		id: 'etoricox-hexal-etoricoxib-30mg-fc-tabs-10-a5',
		name: 'etoricox-hexal 30 mg 10 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '30 mg',
		price: 32.5,
		matchKeywords: ['etoricox-hexal 30 10', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٣٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},

	// 266
	{
		id: 'etoricox-hexal-etoricoxib-30mg-fc-tabs-30-a5',
		name: 'etoricox-hexal 30 mg 30 f.c.tabs.',
		genericName: 'etoricoxib',
		concentration: '30 mg',
		price: 97.5,
		matchKeywords: ['etoricox-hexal 30 30', ...tag('#nsaid', '#cox-2 inhibitors')],
		usage: 'مسكن COX-2.',
		timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
		category: Category.ANALGESICS,
		form: 'F.C. Tablets',
		minAgeMonths: 192,
		maxAgeMonths: 1200,
		minWeight: 50,
		maxWeight: 250,
		calculationRule: (_w: number, _a: number) => 'قرص واحد (٣٠ مجم) مرة يومياً بعد الأكل.',
		warnings: [...commonNsaidWarnings],
	},
];

