
import { Medication, Category } from '../../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;

const TAGS = {
  analgesics: ['analgesics', '#analgesics', 'analgesic', '#analgesic', 'مسكن', 'ألم'],
  antipyretics: ['antipyretics', '#antipyretics', 'fever', 'حمى', 'سخونية'],
  nsaid: ['nsaid', '#nsaid', 'NSAID', 'مضاد التهاب غير ستيرويدي'],
  antiInflammatory: ['anti-inflammatory', '#anti-inflammatory', 'anti inflammatory', 'مضاد التهاب'],
  muscleRelaxants: ['muscle relaxants', '#muscle relaxants', 'مرخي عضلات', 'باسط عضلات'],
  urinary: ['urinary', '#urinary', 'urinary care', 'مسالك بولية', 'مغص كلوي'],
  antiseptics: ['antiseptics', '#antiseptics', 'مطهر'],
  antiGout: ['anti-gout', '#anti-gout', 'gout', 'نقرس', 'حمض اليوريك'],
  mouth: ['mouth wash', '#mouth', 'mouthwash', 'غرغرة', 'التهاب الحلق'],
  antibacterial: ['anti-bacterial', '#anti-bacterial', 'antibacterial', 'مضاد بكتيري'],
  antispasmodics: ['antispasmodics', '#antispasmodics', 'colic', 'مغص', 'تقلصات'],
  commonCold: ['common cold', '#common cold', 'cold', 'flu', 'برد', 'نزلة برد'],
  cox2: ['cox-2 inhibitors', '#cox-2 inhibitors', 'COX-2'],
  oxicam: ['oxicam', '#oxicam'],
  propionicAcid: ['propionic acid derivatives', '#propionic acid derivatives', 'propionic acid'],
  aceticAcid: ['acetic acid derivatives', '#acetic acid derivatives', 'acetic acid'],
  salicylate: ['salicylate', '#salicylate', 'salicylates'],
  cns: ['cns', '#cns', 'central nervous system', 'جهاز عصبي'],
};

const commonParacetamolWarnings = [
  'لا تجمع أكثر من منتج يحتوي على باراسيتامول.',
  'مرضى الكبد/الكحول: استخدم أقل جرعة ولأقصر مدة؛ تجنب الكحول.',
];

const commonNsaidWarnings = [
  'يفضل بعد الأكل لتقليل تهيج المعدة.',
  'لا تجمع أكثر من NSAID في نفس الوقت.',
  'يُتجنب مع قرحة/نزيف معدي أو فشل كلوي شديد، وأواخر الحمل.',
];

export const ANALGESICS_1: Medication[] = [
  // 1) doliprane 1 gm 15 tabs.
  {
    id: 'doliprane-paracetamol-1g-tabs-15',
    name: 'doliprane 1 gm 15 tabs.',
    genericName: 'paracetamol',
    concentration: '1 gm',
    price: 48,
    matchKeywords: ['doliprane', 'دوليبران', ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن وخافض حرارة.',
    timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
    category: Category.PARACETAMOL,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١ جم) كل ٦–٨ ساعات عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
    warnings: [...commonParacetamolWarnings],
  },

  // 2) brufen 400mg 30 tab
  {
    id: 'brufen-ibuprofen-400mg-tabs-30',
    name: 'brufen 400mg 30 tab',
    genericName: 'ibuprofen',
    concentration: '400mg',
    price: 78,
    matchKeywords: ['brufen 400', 'بروفين 400', ...TAGS.nsaid, ...TAGS.propionicAcid, ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن وخافض حرارة ومضاد التهاب.',
    timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.IBUPROFEN,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٤٠٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 3) brufen 600mg 20 eff. gr. in sachets
  {
    id: 'brufen-ibuprofen-600mg-eff-gr-sachets-20',
    name: 'brufen 600mg 20 eff. gr. in sachets',
    genericName: 'ibuprofen',
    concentration: '600mg',
    price: 120,
    matchKeywords: ['brufen 600 sachets', 'بروفين 600 فوار', ...TAGS.nsaid, ...TAGS.propionicAcid, ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن وخافض حرارة ومضاد التهاب (فوار).',
    timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.IBUPROFEN,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كيس واحد بعد الأكل كل ٨–١٢ ساعة عند اللزوم (حد أقصى ٣ أكياس/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 4) cataflam 50 mg 20 sugar c.tabs
  {
    id: 'cataflam-diclofenac-potassium-50mg-sugar-coated-tabs-20',
    name: 'cataflam 50 mg 20 sugar c.tabs',
    genericName: 'diclofenac potassium',
    concentration: '50 mg',
    price: 86,
    matchKeywords: ['cataflam', 'كتافلام', ...TAGS.analgesics, ...TAGS.antipyretics, ...TAGS.antiInflammatory, ...TAGS.nsaid],
    usage: 'مسكن ومضاد التهاب.',
    timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.DICLOFENAC,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 5) declophen 75mg/3ml 6 ampoules
  {
    id: 'declophen-diclofenac-sodium-75mg-3ml-ampoules-6',
    name: 'declophen 75mg/3ml 6 ampoules',
    genericName: 'diclofenac sodium',
    concentration: '75mg/3ml',
    price: 39.5,
    matchKeywords: ['declophen 6 amp', 'ديكلوفين 6 امبول', ...TAGS.analgesics, ...TAGS.nsaid, ...TAGS.antiInflammatory, ...TAGS.antipyretics],
    usage: 'مسكن قوي للآلام الحادة (حقن ديكلوفيناك).',
    timing: 'عند الألم – لفترة قصيرة',
    category: Category.DICLOFENAC,
    form: 'Ampoules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'أمبول واحد (٧٥ مجم) بالعضل مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
    warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
  },

  // 6) declophen 75mg/3ml 3 ampoules
  {
    id: 'declophen-diclofenac-sodium-75mg-3ml-ampoules-3',
    name: 'declophen 75mg/3ml 3 ampoules',
    genericName: 'diclofenac sodium',
    concentration: '75mg/3ml',
    price: 36,
    matchKeywords: ['declophen 3 amp', 'ديكلوفين 3 امبول', ...TAGS.analgesics, ...TAGS.nsaid, ...TAGS.antiInflammatory, ...TAGS.antipyretics],
    usage: 'مسكن قوي للآلام الحادة (حقن ديكلوفيناك).',
    timing: 'عند الألم – لفترة قصيرة',
    category: Category.DICLOFENAC,
    form: 'Ampoules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'أمبول واحد (٧٥ مجم) بالعضل مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
    warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
  },

  // 7) dimra 20 f.c.tab.
  {
    id: 'dimra-diclofenac-potassium-methocarbamol-fc-tabs-20',
    name: 'dimra 20 f.c.tab.',
    genericName: 'diclofenac potassium & methocarbamol',
    concentration: 'F.C. Tablets',
    price: 70,
    matchKeywords: ['dimra', 'ديمرا', ...TAGS.analgesics, ...TAGS.muscleRelaxants],
    usage: 'مسكن ومضاد التهاب + باسط للعضلات لآلام الشد العضلي.',
    timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٧ أيام',
    category: Category.MUSCLE_RELAXANTS,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد بعد الأكل ٢–٣ مرات يومياً (لا تجمعه مع NSAIDs أخرى).',
    warnings: [...commonNsaidWarnings, 'قد يسبب نعاس/دوخة بسبب باسط العضلات.'],
  },

  // 8) indomethacin 100 mg 10 supp. b.p.2014
  {
    id: 'indomethacin-100mg-supp-10-bp2014',
    name: 'indomethacin 100 mg 10 supp. b.p.2014',
    genericName: 'indomethacin',
    concentration: '100 mg',
    price: 38,
    matchKeywords: ['indomethacin 100', 'اندوميثاسين', ...TAGS.analgesics, ...TAGS.nsaid, ...TAGS.aceticAcid, 'antirheumatic', '#antirheumatic', 'روماتيزم'],
    usage: 'مسكن ومضاد التهاب (NSAID) – لبوس.',
    timing: 'مرة يومياً مساءً بعد الأكل/قبل النوم – ٣–٥ أيام',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Suppositories',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'لبوسة واحدة (١٠٠ مجم) مساءً بعد الأكل/قبل النوم. لا تتجاوز لبوسة–لبوستين يومياً.',
    warnings: [...commonNsaidWarnings, 'يُمنع في أواخر الحمل.'],
  },

  // 9) ketolac 10mg 20 tab
  {
    id: 'ketolac-ketorolac-10mg-tabs-20',
    name: 'ketolac 10mg 20 tab',
    genericName: 'ketorolac',
    concentration: '10mg',
    price: 38,
    matchKeywords: ['ketolac', 'كيتولاك', 'ketorolac', ...TAGS.nsaid, ...TAGS.aceticAcid, ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن قوي قصير المدى (NSAID) لآلام حادة (لفترة قصيرة).',
    timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – لفترة قصيرة',
    category: Category.ANALGESICS,
    form: 'Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'قرص واحد (١٠ مجم) كل ٦–٨ ساعات بعد الأكل عند اللزوم. الحد الأقصى: ٤ أقراص/٢٤ ساعة ولمدة لا تزيد عن ٥ أيام.',
    warnings: [...commonNsaidWarnings, 'ممنوع في الفشل الكلوي أو النزيف/القرحة.', 'خطر أعلى للنزيف/قرحة المعدة: التزم بالمدة القصيرة الموصوفة.'],
  },

  // 10) mark fast 30 capsules
  {
    id: 'mark-fast-chlorzoxazone-ibuprofen-caps-30',
    name: 'mark fast 30 capsules',
    genericName: 'chlorzoxazone & ibuprofen',
    concentration: 'Capsules',
    price: 54,
    matchKeywords: ['mark fast', 'مارك فاست', 'chlorzoxazone', 'ibuprofen', ...TAGS.analgesics, ...TAGS.muscleRelaxants],
    usage: 'مسكن + باسط للعضلات لآلام الشد العضلي.',
    timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٧ أيام',
    category: Category.MUSCLE_RELAXANTS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كبسولة بعد الأكل ٢–٣ مرات يومياً (لا تجمعه مع NSAIDs أخرى).',
    warnings: [...commonNsaidWarnings, 'قد يسبب نعاس/دوخة بسبب باسط العضلات.'],
  },

  // 11) panadol advance 500 mg 24 f.c.tabs.
  {
    id: 'panadol-advance-paracetamol-500mg-fc-tabs-24',
    name: 'panadol advance 500 mg 24 f.c.tabs.',
    genericName: 'paracetamol',
    concentration: '500 mg',
    price: 46,
    matchKeywords: ['panadol advance 24', 'بانادول ادفانس', ...TAGS.antipyretics, ...TAGS.analgesics],
    usage: 'مسكن وخافض حرارة.',
    timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
    category: Category.PARACETAMOL,
    form: 'F.C. Tablets',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: (weight: number, _ageMonths: number) => (weight < 40 ? 'نصف قرص إلى قرص' : 'قرص إلى قرصين'),
    warnings: [...commonParacetamolWarnings],
  },

  // 12) panadol extra 48 f.c. tabs.
  {
    id: 'panadol-extra-paracetamol-caffeine-fc-tabs-48',
    name: 'panadol extra 48 f.c. tabs.',
    genericName: 'paracetamol & caffeine',
    concentration: 'F.C. Tablets',
    price: 108,
    matchKeywords: ['panadol extra 48', 'بانادول اكسترا 48', ...TAGS.analgesics],
    usage: 'مسكن للصداع والآلام (يحتوي كافيين).',
    timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
    category: Category.PARACETAMOL,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
    warnings: [...commonParacetamolWarnings, 'يحتوي على كافيين: قد يسبب أرق/خفقان.'],
  },

  // 13) rowatinex 45 capsules
  {
    id: 'rowatinex-anethol-borneol-camphene-cineole-athaverine-fenchone-caps-45',
    name: 'rowatinex 45 capsules',
    genericName: 'anethol & borneol & camphene & cineole & athaverine & fenchone',
    concentration: 'Capsules',
    price: 93,
    matchKeywords: ['rowatinex', 'رواتينكس', ...TAGS.urinary, ...TAGS.analgesics, ...TAGS.antiseptics],
    usage: 'مساعد لحصوات الكلى/الرمل والمغص الكلوي والتهابات المسالك البولية.',
    timing: 'كل ٨ ساعات قبل الأكل بنصف ساعة – ٣–٥ أيام',
    category: Category.URINARY_CARE,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كبسولة أو كبسولتين ٣ مرات يومياً قبل الأكل بنصف ساعة مع شرب ماء كثير.',
    warnings: ['الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.', 'أوقف وأعد التقييم عند مغص كلوي شديد جداً أو انحباس البول.'],
  },

  // 14) tantum verde 0.15% mouth wash 125 ml
  {
    id: 'tantum-verde-benzydamine-hcl-0-15-mouthwash-125ml',
    name: 'tantum verde 0.15% mouth wash 125 ml',
    genericName: 'benzydamine hydrochloride',
    concentration: '0.15%',
    price: 31,
    matchKeywords: ['tantum verde', 'تانتم فيردي', 'benzydamine', ...TAGS.analgesics, ...TAGS.antibacterial, ...TAGS.mouth],
    usage: 'غسول/غرغرة لتخفيف ألم والتهاب الفم/الحلق.',
    timing: 'كل ٢–٣ ساعات عند الألم – بحد أقصى ٦ مرات يومياً',
    category: Category.MOUTH_THROAT,
    form: 'Mouthwash',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      '١٥ مل (ملعقة كبيرة) غرغرة/مضمضة لمدة ٣٠ ثانية ثم تُبصق، وتكرر كل ٢–٣ ساعات عند اللزوم (حد أقصى ٦ مرات/اليوم).',
    warnings: ['إذا حدث حساسية/تورم أو صعوبة تنفس أوقفه وأعد التقييم.'],
  },

  // 15) urinex 24 caps
  {
    id: 'urinex-alpha-pinene-borneol-fenchone-anethol-cineol-camphene-caps-24',
    name: 'urinex 24 caps',
    genericName: 'alpha pinene & borneol & fenchone & anethol & cineol & camphene',
    concentration: 'Capsules',
    price: 44,
    matchKeywords: ['urinex', 'يورينكس', ...TAGS.urinary, ...TAGS.analgesics, ...TAGS.antiseptics],
    usage: 'مساعد لأعراض المسالك/الأملاح.',
    timing: 'كل ٨ ساعات قبل الأكل – ٣–٥ أيام',
    category: Category.URINARY_CARE,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كبسولة واحدة ٣ مرات يومياً قبل الأكل.',
    warnings: ['الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.'],
  },

  // 16) brufen 600mg 30 tab
  {
    id: 'brufen-ibuprofen-600mg-tabs-30',
    name: 'brufen 600mg 30 tab',
    genericName: 'ibuprofen',
    concentration: '600mg',
    price: 99,
    matchKeywords: ['brufen 600', 'بروفين 600', ...TAGS.nsaid, ...TAGS.propionicAcid, ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن ومضاد التهاب (NSAID).',
    timing: 'كل ٨–١٢ ساعة بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.IBUPROFEN,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٦٠٠ مجم) كل ٨–١٢ ساعة بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 17) methoquick 50/500 mg 30 tabs.
  {
    id: 'methoquick-diclofenac-potassium-methocarbamol-50-500-tabs-30',
    name: 'methoquick 50/500 mg 30 tabs.',
    genericName: 'diclofenac potassium & methocarbamol',
    concentration: '50/500 mg',
    price: 99,
    matchKeywords: ['methoquick', 'ميثوكويك', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxants],
    usage: 'مسكن ومضاد التهاب + باسط عضلات.',
    timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
    category: Category.MUSCLE_RELAXANTS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد بعد الأكل ٢–٣ مرات يومياً (حسب شدة الألم).',
    warnings: [...commonNsaidWarnings, 'قد يسبب نعاس/دوخة.'],
  },

  // 18) panadol advance 500 mg 48 tablets
  {
    id: 'panadol-advance-paracetamol-500mg-tabs-48',
    name: 'panadol advance 500 mg 48 tablets',
    genericName: 'paracetamol',
    concentration: '500 mg',
    price: 92,
    matchKeywords: ['panadol advance 48', 'بانادول ادفانس 48', ...TAGS.antipyretics, ...TAGS.analgesics],
    usage: 'مسكن وخافض حرارة.',
    timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
    category: Category.PARACETAMOL,
    form: 'Tablets',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: (weight: number, _ageMonths: number) => (weight < 40 ? 'نصف قرص إلى قرص' : 'قرص إلى قرصين'),
    warnings: [...commonParacetamolWarnings],
  },

  // 19) panadol extra 24 f.c. tab
  {
    id: 'panadol-extra-paracetamol-caffeine-fc-tabs-24',
    name: 'panadol extra 24 f.c. tab',
    genericName: 'paracetamol & caffeine',
    concentration: 'F.C. Tablets',
    price: 58,
    matchKeywords: ['panadol extra 24', 'بانادول اكسترا 24', ...TAGS.analgesics],
    usage: 'مسكن للصداع والآلام (يحتوي كافيين).',
    timing: 'كل ٦ ساعات عند الألم – ٣–٥ أيام',
    category: Category.PARACETAMOL,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص إلى قرصين كل ٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة).',
    warnings: [...commonParacetamolWarnings, 'يحتوي على كافيين: قد يسبب أرق/خفقان.'],
  },

  // 20) rheumatizen topical cream 30 gm
  {
    id: 'urivin-n-piperazine-citrate-colchicine-khellin-eff-sachets-10',
    name: 'urivin n 10 eff. sachets',
    genericName: 'piperazine citrate & colchicine & khellin',
    concentration: 'Sachets',
    price: 31,
    matchKeywords: ['urivin n', 'يوريڤين ان', ...TAGS.urinary, ...TAGS.analgesics, ...TAGS.antiseptics],
    usage: 'فوار مساعد لأعراض المسالك/الأملاح.',
    timing: 'كل ٨ ساعات بعد الأكل – ٣–٥ أيام',
    category: Category.URINARY_CARE,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كيس واحد ٣ مرات يومياً. يُذاب في نصف كوب ماء ويُشرب قبل الأكل.',
    warnings: ['لا تجمعه مع أدوية أخرى تحتوي على كولشيسين.', 'ممنوع للحوامل.'],
  },

  // 23) urosolvine eff. gran. 12 sachets
  {
    id: 'urosolvine-eff-granules-12-sachets',
    name: 'urosolvine eff. gran. 12 sachets',
    genericName: 'colchicine & piperazine citrate & atropine sulphate',
    concentration: 'Sachets',
    price: 34,
    matchKeywords: ['urosolvine', 'يوروسولفين', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'فوار مساعد في حالات النقرس/الأملاح.',
    timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
    category: Category.ANTI_GOUT,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كيس ٢–٣ مرات يومياً.',
    warnings: ['تحذير: يحتوي أتروبين—يُتجنب في الجلوكوما/احتباس البول.'],
  },

  // 24) voltaren 75mg/3ml 3 amp.
  {
    id: 'voltaren-75-3-amp',
    name: 'voltaren 75mg/3ml 3 amp.',
    genericName: 'diclofenac sodium',
    concentration: '75mg/3ml',
    price: 51,
    matchKeywords: ['voltaren 3 amp', 'فولتارين 3 امبول', ...TAGS.nsaid, ...TAGS.aceticAcid, ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن قوي للآلام الحادة (حقن ديكلوفيناك).',
    timing: 'عند الألم – لفترة قصيرة',
    category: Category.DICLOFENAC,
    form: 'Ampoules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'أمبول واحد (٧٥ مجم) بالعضل مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
    warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
  },

  // 25) voltaren 75mg/3ml 6 amp.
  {
    id: 'voltaren-75-6-amp',
    name: 'voltaren 75mg/3ml 6 amp.',
    genericName: 'diclofenac sodium',
    concentration: '75mg/3ml',
    price: 102,
    matchKeywords: ['voltaren 6 amp', 'فولتارين 6 امبول', ...TAGS.nsaid, ...TAGS.aceticAcid, ...TAGS.analgesics, ...TAGS.antipyretics],
    usage: 'مسكن قوي للآلام الحادة (حقن ديكلوفيناك) – عبوة 6 أمبول.',
    timing: 'عند الألم – لفترة قصيرة',
    category: Category.DICLOFENAC,
    form: 'Ampoules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'أمبول واحد (٧٥ مجم) بالعضل مرة يومياً (حد أقصى ٢ أمبول/٢٤ ساعة ولمدة قصيرة فقط).',
    warnings: [...commonNsaidWarnings, 'لا تستخدم الحقن لأكثر من يومين دون إعادة تقييم.'],
  },

  // 26) uraid-n eff. granul. 12 sachets
  {
    id: 'uraid-n-eff-granules-12-sachets',
    name: 'uraid-n eff. granul. 12 sachets',
    genericName: 'piperazine citrate & colchicine',
    concentration: 'Sachets',
    price: 38,
    matchKeywords: ['uraid-n', 'uraid n', 'يورايد ان', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'فوار مساعد للنقرس/الأملاح.',
    timing: 'كل ٨–١٢ ساعة بعد الأكل – ٣–٧ أيام',
    category: Category.ANTI_GOUT,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كيس ٢–٣ مرات يومياً.',
    warnings: ['لا تجمع كولشيسين من مصدر آخر.'],
  },

  // 27) aspirin protect 100mg 30 gastro-resistant tab
  {
    id: 'aspirin-protect-acetylsalicylic-acid-100mg-gastro-resistant-tabs-30',
    name: 'aspirin protect 100mg 30 gastro-resistant tab',
    genericName: 'acetylsalicylic acid',
    concentration: '100mg',
    price: 78,
    matchKeywords: ['aspirin protect', 'اسبرين بروتكت', ...TAGS.nsaid, ...TAGS.salicylate],
    usage: 'أسبرين بجرعة منخفضة (غالباً للوقاية القلبية).',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Gastro-resistant Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٠٠ مجم) مرة يومياً.',
    warnings: ['يزيد خطر النزيف مع مميعات الدم؛ راجع التفاعلات وعدّل أو اختر بديلاً.'],
  },

  // 28) aspcid paediatric 75mg 30 chewable tab.
  {
    id: 'aspcid-paediatric-acetylsalicylic-acid-75mg-chewable-tabs-30',
    name: 'aspcid paediatric 75mg 30 chewable tab.',
    genericName: 'acetylsalicylic acid',
    concentration: '75mg',
    price: 35,
    matchKeywords: ['aspcid paediatric', 'اسبسيد اطفال', ...TAGS.nsaid, ...TAGS.salicylate],
    usage: 'أسبرين منخفض الجرعة (مضاد تجمع صفائح).',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٧٥ مجم) مرة يومياً.',
    warnings: ['تحذير: لا يُعطى للأطفال/المراهقين مع عدوى فيروسية (خطر متلازمة راي).', 'يزيد خطر النزيف.'],
  },

  // 29) bi-alcofan 150 mg 30 tabs.
  {
    id: 'bi-alcofan-ketoprofen-150mg-tabs-30',
    name: 'bi-alcofan 150 mg 30 tabs.',
    genericName: 'ketoprofen',
    concentration: '150 mg',
    price: 81,
    matchKeywords: ['bi-alcofan', 'بي الكوفان', 'ketoprofen', ...TAGS.nsaid, ...TAGS.propionicAcid],
    usage: 'مسكن ومضاد التهاب (NSAID).',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٥٠ مجم) مرة يومياً بعد الأكل (حد أقصى قرص/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 30) contafever n 200mg/5ml susp. 120ml
  {
    id: 'contafever-n-ibuprofen-200mg-5ml-susp-120ml',
    name: 'contafever n 200mg/5ml susp. 120ml',
    genericName: 'ibuprofen',
    concentration: '200mg/5ml',
    price: 33,
    matchKeywords: ['contafever', 'كونتافيفر', ...TAGS.nsaid, ...TAGS.propionicAcid],
    usage: 'خافض حرارة ومسكن للأطفال (إيبوبروفين).',
    timing: 'كل ٦–٨ ساعات عند الألم – ٣–٥ أيام',
    category: Category.IBUPROFEN,
    form: 'Suspension',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 7,
    maxWeight: 45,
    calculationRule: (weight: number, _ageMonths: number) => {
      // Dose: 10 mg/kg/dose. Conc: 200mg/5ml = 40 mg/ml.
      const ml = roundVol(weight / 4);
      return `${toAr(ml)} مل كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ جرعات/٢٤ ساعة).`;
    },
    warnings: [...commonNsaidWarnings, 'لا يُستخدم للأطفال أقل من 6 شهور إلا حسب التشخيص.'],
  },

  // 31) diclac 150 id 20 prolonged r tabs
  {
    id: 'diclac-diclofenac-sodium-150mg-prolonged-release-tabs-20',
    name: 'diclac 150 id 20 prolonged r tabs',
    genericName: 'diclofenac sodium',
    concentration: '150mg',
    price: 132,
    matchKeywords: ['diclac 150', 'ديكلاك 150', ...TAGS.nsaid, ...TAGS.aceticAcid],
    usage: 'مسكن ومضاد التهاب ممتد المفعول (NSAID).',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.DICLOFENAC,
    form: 'Prolonged Release Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد يومياً بعد الأكل (يُبلع كاملاً).',
    warnings: [...commonNsaidWarnings],
  },

  // 32) ezacard 75 mg 30 e.c. tabs.
  {
    id: 'ezacard-acetylsalicylic-acid-75mg-ec-tabs-30',
    name: 'ezacard 75 mg 30 e.c. tabs.',
    genericName: 'acetylsalicylic acid',
    concentration: '75mg',
    price: 51,
    matchKeywords: ['ezacard', 'ايزاكارد', ...TAGS.nsaid, ...TAGS.salicylate],
    usage: 'أسبرين منخفض الجرعة (غالباً للوقاية القلبية).',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'E.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٧٥ مجم) مرة يومياً.',
    warnings: ['يزيد خطر النزيف.'],
  },

  // 33) injectmol 1 gm/100ml vial for i.v. inf.
  {
    id: 'injectmol-paracetamol-1g-100ml-iv-infusion-vial',
    name: 'injectmol 1 gm/100ml vial for i.v. inf.',
    genericName: 'paracetamol',
    concentration: '1 gm/100ml',
    price: 67,
    matchKeywords: ['injectmol 1g', 'انجيكتمول', ...TAGS.antipyretics],
    usage: 'باراسيتامول وريدي لتسكين الألم/خفض الحرارة؛ للإعطاء بالمستشفى/العيادة بجرعة محددة.',
    timing: 'حقن – حسب بروتوكول المستشفى',
    category: Category.PARACETAMOL,
    form: 'I.V. Infusion Vial',
    minAgeMonths: 1,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (weight: number, _ageMonths: number) => (weight < 50 ? `${toAr(Math.round(weight * 1.5))} مل وريد` : 'زجاجة كاملة (100 مل) وريد'),
    warnings: ['يُحسب بالوزن للأطفال لتجنب السمية الكبدية.', ...commonParacetamolWarnings],
  },

  // 34) ketofan 50mg 20 caps
  {
    id: 'ketofan-ketoprofen-50mg-caps-20',
    name: 'ketofan 50mg 20 caps',
    genericName: 'ketoprofen',
    concentration: '50mg',
    price: 30,
    matchKeywords: ['ketofan', 'كيتوفان', 'ketoprofen', ...TAGS.nsaid, ...TAGS.propionicAcid],
    usage: 'مسكن ومضاد التهاب (NSAID).',
    timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كبسولة واحدة (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ كبسولات/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 35) oflam 50mg 20 quicketab.
  {
    id: 'oflam-diclofenac-potassium-50mg-quicketab-tabs-20',
    name: 'oflam 50mg 20 quicketab.',
    genericName: 'diclofenac potassium',
    concentration: '50mg',
    price: 48,
    matchKeywords: ['oflam 50', 'اوفلام', ...TAGS.nsaid, ...TAGS.aceticAcid],
    usage: 'مسكن ومضاد التهاب سريع المفعول.',
    timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.DICLOFENAC,
    form: 'Tablets',
    minAgeMonths: 168,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 36) powercaps 20 caps.
  {
    id: 'powercaps-ibuprofen-pseudoephedrine-caps-20',
    name: 'powercaps 20 caps.',
    genericName: 'ibuprofen & pseudoephedrine',
    concentration: 'Capsules',
    price: 40,
    matchKeywords: ['powercaps', 'باوركابس', ...TAGS.commonCold],
    usage: 'أعراض البرد/الجيوب (مسكن + مزيل احتقان).',
    timing: 'كل ٦–٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.COMMON_COLD,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'كبسولة واحدة كل ٦–٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ كبسولات/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings, 'مزيل الاحتقان قد يرفع الضغط/يزيد خفقان: الحذر لمرضى القلب/الضغط.'],
  },

  // 37) rivo 320mg 20*10 tabs
  {
    id: 'rivo-acetylsalicylic-acid-320mg-tabs-200',
    name: 'rivo 320mg 20*10 tabs',
    genericName: 'acetylsalicylic acid',
    concentration: '320mg',
    price: 141,
    matchKeywords: ['rivo 320', 'ريفو 320', ...TAGS.analgesics],
    usage: 'أسبرين بجرعة أعلى (مسكن/مضاد التهاب).',
    timing: 'كل ٦ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٣٢٠ مجم) كل ٦ ساعات بعد الأكل عند اللزوم (حد أقصى ٤ أقراص/٢٤ ساعة).',
    warnings: ['يزيد خطر النزيف/قرحة المعدة.'],
  },

  // 38) spasmofen 3 amp. for i.m. inj.
  {
    id: 'spasmofen-hyoscine-ketoprofen-ampoules-3',
    name: 'spasmofen 3 amp. for i.m. inj.',
    genericName: 'hyoscine & ketoprofen',
    concentration: 'Ampoules',
    price: 54,
    matchKeywords: ['spasmofen', 'سبازموفين', ...TAGS.antispasmodics],
    usage: 'مضاد تقلصات + مسكن (حقن).',
    timing: 'جرعة مفردة عند الألم',
    category: Category.ANTISPASMODIC,
    form: 'Ampoules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'أمبول واحد بالعضل عند اللزوم. يمكن تكراره بعد ٨–١٢ ساعة عند الحاجة (حد أقصى ٢ أمبول/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings, 'هييوسين قد يسبب جفاف فم/زغللة: الحذر مع الجلوكوما/احتباس البول.'],
  },

  // 39) vastaflam 50mg 20 sugar coated tab.
  {
    id: 'vastaflam-diclofenac-potassium-50mg-sugar-coated-tabs-20',
    name: 'vastaflam 50mg 20 sugar coated tab.',
    genericName: 'diclofenac potassium',
    concentration: '50mg',
    price: 36,
    matchKeywords: ['vastaflam', 'فاستافلام', ...TAGS.nsaid, ...TAGS.aceticAcid],
    usage: 'مسكن ومضاد التهاب (NSAID).',
    timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.DICLOFENAC,
    form: 'Sugar Coated Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ أقراص/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 40) winzoxib 90mg 20 tab
  {
    id: 'winzoxib-etoricoxib-90mg-tabs-20',
    name: 'winzoxib 90mg 20 tab',
    genericName: 'etoricoxib',
    concentration: '90mg',
    price: 136,
    matchKeywords: ['winzoxib 90', 'وينزوكسِب 90', 'etoricoxib', ...TAGS.nsaid, ...TAGS.cox2],
    usage: 'مسكن ومضاد التهاب انتقائي COX-2.',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٩٠ مجم) مرة يومياً بعد الأكل.',
    warnings: [...commonNsaidWarnings, 'ممنوع لمرضى القلب/الذبحة غير المستقرة.'],
  },

  // 41) jusprin 81mg 60 enteric coated tab
  {
    id: 'jusprin-acetylsalicylic-acid-81mg-enteric-coated-tabs-60',
    name: 'jusprin 81mg 60 enteric coated tab',
    genericName: 'acetylsalicylic acid',
    concentration: '81mg',
    price: 81,
    matchKeywords: ['jusprin 81', 'جوسبرين 81', ...TAGS.nsaid, ...TAGS.salicylate],
    usage: 'أسبرين منخفض الجرعة (غالباً للوقاية القلبية).',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Enteric Coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٨١ مجم) مرة يومياً.',
    warnings: ['يزيد خطر النزيف.'],
  },

  // 42) winzoxib 120 mg 7 f.c.tabs.
  {
    id: 'winzoxib-etoricoxib-120mg-fc-tabs-7',
    name: 'winzoxib 120 mg 7 f.c.tabs.',
    genericName: 'etoricoxib',
    concentration: '120mg',
    price: 57,
    matchKeywords: ['winzoxib 120', 'etoricoxib 120', ...TAGS.nsaid, ...TAGS.cox2],
    usage: 'مسكن COX-2 بجرعة أعلى (عادةً لفترات قصيرة).',
    timing: 'مرة يومياً بعد الأكل – لفترة قصيرة',
    category: Category.ANALGESICS,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (١٢٠ مجم) مرة يومياً بعد الأكل ولمدة قصيرة (حد أقصى قرص واحد/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 43) aspcid 75mg 30 tab.
  {
    id: 'aspcid-acetylsalicylic-acid-75mg-tabs-30',
    name: 'aspcid 75mg 30 tab.',
    genericName: 'acetylsalicylic acid',
    concentration: '75mg',
    price: 33,
    matchKeywords: ['aspcid 75', 'اسبسيد 75', ...TAGS.nsaid, ...TAGS.salicylate],
    usage: 'أسبرين منخفض الجرعة.',
    timing: 'مرة يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٧٥ مجم) مرة يومياً.',
    warnings: ['يزيد خطر النزيف.'],
  },

  // 44) injectmol 500mg/50ml vial for i.v. inf.
  {
    id: 'injectmol-paracetamol-500mg-50ml-iv-infusion-vial',
    name: 'injectmol 500mg/50ml vial for i.v. inf.',
    genericName: 'paracetamol',
    concentration: '500mg/50ml',
    price: 46,
    matchKeywords: ['injectmol 500', 'انجيكتمول 500', ...TAGS.antipyretics],
    usage: 'باراسيتامول وريدي لتسكين الألم/خفض الحرارة؛ للإعطاء بالمستشفى/العيادة بجرعة محددة.',
    timing: 'حقن – حسب بروتوكول المستشفى',
    category: Category.PARACETAMOL,
    form: 'I.V. Infusion Vial',
    minAgeMonths: 1,
    maxAgeMonths: 1200,
    minWeight: 3,
    maxWeight: 250,
    calculationRule: (weight: number, _ageMonths: number) => (weight < 50 ? `${toAr(Math.round(weight * 1.5))} مل وريد` : 'زجاجة كاملة (50 مل) وريد'),
    warnings: [...commonParacetamolWarnings],
  },

  // 45) ketofan 50mg 30 caps.
  {
    id: 'ketofan-ketoprofen-50mg-caps-30',
    name: 'ketofan 50mg 30 caps.',
    genericName: 'ketoprofen',
    concentration: '50mg',
    price: 45,
    matchKeywords: ['ketofan 30', 'كيتوفان 30', 'ketoprofen', ...TAGS.nsaid, ...TAGS.propionicAcid],
    usage: 'مسكن ومضاد التهاب (NSAID).',
    timing: 'كل ٨ ساعات بعد الأكل عند الألم – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'كبسولة واحدة (٥٠ مجم) كل ٨ ساعات بعد الأكل عند اللزوم (حد أقصى ٣ كبسولات/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 46) panadol cold & flu day 24 f.c. tabs
  {
    id: 'panadol-cold-flu-day-paracetamol-caffeine-phenylephrine-fc-tabs-24',
    name: 'panadol cold & flu day 24 f.c. tabs',
    genericName: 'paracetamol & caffeine & phenylephrine hydrochloride',
    concentration: 'F.C. Tablets',
    price: 76,
    matchKeywords: ['panadol cold', 'بانادول كولد اند فلو', ...TAGS.commonCold],
    usage: 'لتخفيف أعراض نزلات البرد/الإنفلونزا نهاراً (ألم/صداع + حرارة) مع احتقان الأنف.',
    timing: 'كل ٤–٦ ساعات عند الألم – ٣–٥ أيام',
    category: Category.COMMON_COLD,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      '١–٢ قرص كل ٤–٦ ساعات عند اللزوم (حد أقصى ٨ أقراص/٢٤ ساعة). لا تستخدمه أكثر من ٣ أيام للحرارة أو ٥ أيام للألم.',
    warnings: [...commonParacetamolWarnings, 'فينيل إفرين قد يرفع الضغط: الحذر لمرضى الضغط/القلب.'],
  },

  // 47) rheuxicam 8mg 20 f.c.tab.
  {
    id: 'rheuxicam-lornoxicam-8mg-fc-tabs-20',
    name: 'rheuxicam 8mg 20 f.c.tab.',
    genericName: 'lornoxicam',
    concentration: '8mg',
    price: 72,
    matchKeywords: ['rheuxicam', 'ريوكسيكام', 'lornoxicam', ...TAGS.nsaid, ...TAGS.oxicam],
    usage: 'مسكن ومضاد التهاب (Oxicam NSAID).',
    timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٨ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى قرصين/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 48) rheuxicam 8mg pd for i.m. / i.v. inj. vial
  {
    id: 'rheuxicam-lornoxicam-8mg-powder-vial-im-iv',
    name: 'rheuxicam 8mg pd for i.m. / i.v. inj. vial',
    genericName: 'lornoxicam',
    concentration: '8mg',
    price: 26,
    matchKeywords: ['rheuxicam vial', 'lornoxicam vial', ...TAGS.nsaid, ...TAGS.oxicam],
    usage: 'لورنيوكسيكام حقن لتسكين الألم؛ للإعطاء بالمستشفى/العيادة بجرعة محددة.',
    timing: 'جرعة مفردة عند الألم',
    category: Category.ANALGESICS,
    form: 'Vial',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) =>
      'فيال واحد (٨ مجم) بالعضل أو بالوريد. يمكن تكراره مرة واحدة بعد ١٢ ساعة عند الحاجة (حد أقصى ١٦ مجم/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },

  // 49) xefo rapid 8 mg 20 f.c.tabs.
  {
    id: 'xefo-rapid-lornoxicam-8mg-fc-tabs-20',
    name: 'xefo rapid 8 mg 20 f.c.tabs.',
    genericName: 'lornoxicam',
    concentration: '8 mg',
    price: 89,
    matchKeywords: ['xefo rapid', 'زيفو رابيد', 'lornoxicam', ...TAGS.nsaid, ...TAGS.oxicam],
    usage: 'مسكن ومضاد التهاب (Oxicam NSAID).',
    timing: 'مرة–مرتين يومياً بعد الأكل – ٣–٥ أيام',
    category: Category.ANALGESICS,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: (_weight: number, _ageMonths: number) => 'قرص واحد (٨ مجم) مرة إلى مرتين يومياً بعد الأكل (حد أقصى قرصين/٢٤ ساعة).',
    warnings: [...commonNsaidWarnings],
  },
];

