import { Medication, Category } from '../../types';

const fixed = (t: string) => () => t;

const COMMON_EYE_LUBRICANT_WARNINGS = [
	'لا تلمس طرف القطارة/العبوة للعين أو الرموش لتجنب تلوث المستحضر.',
	'العدسات اللاصقة: تُزال قبل الاستخدام وتُعاد بعد ١٥ دقيقة (ويُفضل تجنبها مع جفاف شديد أو تهيج).',
	'إذا وُجد ألم شديد/رهاب ضوء/ضعف نظر أو إفرازات صديدية: يلزم تقييم عيون.',
];

const SDU_WARNINGS = [
	...COMMON_EYE_LUBRICANT_WARNINGS,
	'وحدات أحادية الجرعة: تُستخدم مرة واحدة ثم تُرمى، ولا تُحفظ للاستخدام لاحقاً.',
];

export const EYE_LUBRICANTS_GROUP: Medication[] = [
	// 1) cornetears 1000iu/g aqueous eye gel 10 gm
	{
		id: 'cornetears-vitamin-a-palmitate-1000iu-g-eye-gel-10g',
		name: 'cornetears 1000iu/g aqueous eye gel 10 gm',
		genericName: 'vitamin a palmitate',
		concentration: '1000 IU/g (10 gm)',
		price: 41,
		matchKeywords: ['cornetears', 'cornetears gel', 'vitamin a palmitate', 'عين', 'جل عين', 'جفاف العين', 'كورنيتيرز', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'جل مرطب للعين (فيتامين A) لتقليل جفاف/حرقان العين وتحسين ترطيب سطح القرنية.',
		timing: '٢–٣ مرات يومياً، وآخر جرعة قبل النوم.',
		category: Category.OPHTHALMIC,
		form: 'Gel',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('شريط جل صغير (حوالي ٠.٥–١ سم) داخل الجفن السفلي ٢–٣ مرات يومياً، وآخر جرعة قبل النوم.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS, 'قد يسبب زغللة مؤقتة: تجنب القيادة حتى تزول.'],
	},

	// 2) hyacarenol eye drops 10 ml
	{
		id: 'hyacarenol-dexpanthenol-sodium-hyaluronate-eye-drops-10ml',
		name: 'hyacarenol eye drops 10 ml',
		genericName: 'dexpanthenol & sodium hyaluronate',
		concentration: '10 ml',
		price: 56,
		matchKeywords: ['hyacarenol', 'hyaluronate', 'dexpanthenol', 'eye drops', 'هايـاكارينول', 'جفاف العين', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (هيالورونات + ديكسبانثينول) لترطيب العين وتقليل الحرقان/التهيج مع الجفاف.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً (صباح/عصر/مساء).'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 3) systane hydration eye drops 10 ml
	{
		id: 'systane-hydration-eye-drops-10ml',
		name: 'systane hydration eye drops 10 ml',
		genericName: 'sodium hyaluronate & polyethylene glycol 400 & propylene glycol',
		concentration: '10 ml',
		price: 390,
		matchKeywords: ['systane hydration', 'systane', 'hyaluronate', 'peg 400', 'propylene glycol', 'سيستان هايدريشن', 'dry eye', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية لترطيب العين وتقليل أعراض جفاف العين.',
		timing: 'نقطة إلى نقطتين في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة إلى نقطتين في كل عين ٤ مرات يومياً (كل ٦ ساعات).'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 4) tears guard 0.3% eye drops 15 ml
	{
		id: 'tears-guard-hypromellose-0-3-eye-drops-15ml',
		name: 'tears guard 0.3% eye drops 15 ml',
		genericName: 'hydroxypropyl methylcellulose (hypromellose)',
		concentration: '0.3% (15 ml)',
		price: 39,
		matchKeywords: ['tears guard 0.3', 'tears guard', 'hypromellose', 'hpmc', 'تيرز جارد', 'دموع صناعية', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية (هيبروميلوز) لترطيب العين وتقليل الإحساس بالرمل/الحرقان.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 5) lacritears eye drops 15 ml
	{
		id: 'lacritears-carmellose-sodium-eye-drops-15ml',
		name: 'lacritears eye drops 15 ml',
		genericName: 'carboxymethylcellulose sodium (carmellose)',
		concentration: '15 ml',
		price: 49,
		matchKeywords: ['lacritears', 'carmellose', 'carboxymethylcellulose', 'لاكريتيرز', 'جفاف العين', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (كاربوكسيميثيل سليلوز) لجفاف العين وتهيجها.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 6) systane original eye drops 10 ml
	{
		id: 'systane-original-eye-drops-10ml',
		name: 'systane original eye drops 10 ml',
		genericName: 'polyethylene glycol 400 & propylene glycol',
		concentration: '10 ml',
		price: 300,
		matchKeywords: ['systane original', 'systane', 'peg 400', 'propylene glycol', 'سيستان اوريجينال', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية لترطيب العين وتقليل أعراض الجفاف.',
		timing: 'نقطة إلى نقطتين في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة إلى نقطتين في كل عين ٤ مرات يومياً (كل ٦ ساعات).'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 7) systane eye gel drops 10 ml
	{
		id: 'systane-eye-gel-drops-10ml',
		name: 'systane eye gel drops 10 ml',
		genericName: 'polyethylene glycol 400 & propylene glycol',
		concentration: '10 ml (gel drops)',
		price: 360,
		matchKeywords: ['systane gel drops', 'systane gel', 'peg 400', 'propylene glycol', 'سيستان جل', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة جل مرطبة (أكثر لزوجة) لتقليل الجفاف الشديد خصوصاً قبل النوم.',
		timing: 'نقطة في كل عين مساءً، ويمكن تكرارها صباحاً وعصراً عند الحاجة.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مساءً، ويمكن إضافة جرعة صباحاً وعصراً عند الحاجة.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS, 'قد يسبب زغللة مؤقتة بعد الجرعة.'],
	},

	// 8) systane ultra eye drops 10 ml
	{
		id: 'systane-ultra-eye-drops-10ml',
		name: 'systane ultra eye drops 10 ml',
		genericName: 'polyethylene glycol 400 & propylene glycol',
		concentration: '10 ml',
		price: 360,
		matchKeywords: ['systane ultra', 'systane', 'peg 400', 'propylene glycol', 'سيستان الترا', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية لترطيب العين وتقليل التهيج مع الجفاف.',
		timing: 'نقطة إلى نقطتين في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة إلى نقطتين في كل عين ٤ مرات يومياً (كل ٦ ساعات).'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 9) tears guard 0.3% eye drops 20 * 0.4ml sdu
	{
		id: 'tears-guard-hypromellose-0-3-eye-drops-sdu-20x0-4',
		name: 'tears guard 0.3% eye drops 20 * 0.4ml sdu',
		genericName: 'hydroxypropyl methylcellulose (hypromellose)',
		concentration: '0.3% (20 × 0.4ml SDU)',
		price: 30,
		matchKeywords: ['tears guard sdu', 'tears guard 0.3 sdu', 'hypromellose', 'تيرز جارد وحدات', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (وحدات أحادية الجرعة) مناسبة لمن يفضلون بدون حفظ متكرر.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 10) twit-tear eye drops 10 ml
	{
		id: 'twit-tear-eye-drops-10ml',
		name: 'twit-tear eye drops 10 ml',
		genericName: 'sodium hyaluronate & hypromellose',
		concentration: '10 ml',
		price: 300,
		matchKeywords: ['twit-tear', 'twit tear', 'hyaluronate', 'hypromellose', 'تويت تير', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (هيالورونات + هيبروميلوز) لزيادة الترطيب وتقليل الإحساس بالجفاف.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 11) twit-tear xp eye drops 10 ml
	{
		id: 'twit-tear-xp-eye-drops-10ml',
		name: 'twit-tear xp eye drops 10 ml',
		genericName: 'sodium hyaluronate',
		concentration: '10 ml',
		price: 340,
		matchKeywords: ['twit-tear xp', 'twit tear xp', 'hyaluronate', 'تويت تير اكس بي', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (هيالورونات) لتقليل جفاف العين والحرقان.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 12) optiguard 3mg/ml eye dps. 15 ml
	{
		id: 'optiguard-hypromellose-3mg-ml-eye-drops-15ml',
		name: 'optiguard 3mg/ml eye dps. 15 ml',
		genericName: 'hydroxypropyl methylcellulose (hypromellose)',
		concentration: '3mg/ml (15 ml)',
		price: 28,
		matchKeywords: ['optiguard', 'hypromellose', '3mg/ml', 'اوبتيجارد', 'دموع صناعية', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية (هيبروميلوز) لترطيب العين وتقليل التهيج الناتج عن الجفاف.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 13) orchatears plus 50mg/ml eye drops 15 ml
	{
		id: 'orchatears-plus-polyvidone-50mg-ml-eye-drops-15ml',
		name: 'orchatears plus 50mg/ml eye drops 15 ml',
		genericName: 'polyvidone (povidone)',
		concentration: '50mg/ml (15 ml)',
		price: 8.5,
		matchKeywords: ['orchatears plus', 'orchatears', 'povidone', 'polyvidone', 'اوركاتيرز', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (بوفيدون) لتقليل الجفاف والتهيج.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 14) systane eye drops 30 x 0.7 ml sdu (n/a)
	{
		id: 'systane-eye-drops-sdu-30x0-7',
		name: 'systane eye drops 30 x 0.7 ml sdu (n/a)',
		genericName: 'polyethylene glycol 400 & propylene glycol',
		concentration: '30 × 0.7 ml SDU',
		price: 56.5,
		matchKeywords: ['systane sdu', 'systane 30', 'peg 400', 'propylene glycol', 'سيستان وحدات', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'دموع صناعية (وحدات أحادية الجرعة).',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 15) pharmatears 0.5% eye drops 15 ml
	{
		id: 'pharmatears-carmellose-sodium-0-5-eye-drops-15ml',
		name: 'pharmatears 0.5% eye drops 15 ml',
		genericName: 'carboxymethylcellulose sodium (carmellose)',
		concentration: '0.5% (15 ml)',
		price: 58,
		matchKeywords: ['pharmatears', 'carmellose', 'carboxymethylcellulose', 'فارماتيرز', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة للعين (كاربوكسيميثيل سليلوز) لتهدئة الجفاف والتهيج.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 16) privacond eye drops 15 ml
	{
		id: 'privacond-tetrahydrozoline-pva-povidone-eye-drops-15ml',
		name: 'privacond eye drops 15 ml',
		genericName: 'tetrahydrozoline hydrochloride & polyvinyl alcohol & povidone',
		concentration: '15 ml',
		price: 42,
		matchKeywords: ['privacond', 'tetrahydrozoline', 'polyvinyl alcohol', 'povidone', 'احمرار العين', 'بريفاكوند', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة عين مرطبة مع مزيل احتقان (تتراهيدروزولين) لتقليل احمرار العين مع الجفاف/التهيج البسيط.',
		timing: 'نقطة واحدة في كل عين ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام متتالية.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [
			...COMMON_EYE_LUBRICANT_WARNINGS,
			'يحتوي على مزيل احتقان: قد يسبب ارتداد الاحمرار مع الإفراط في الاستخدام.',
			'يُتجنب مع جلوكوما ضيقة الزاوية أو ارتفاع شديد بالضغط إلا بإرشاد طبي.',
		],
	},

	// 17) refresh liquigel 1% eye drops 15 ml
	{
		id: 'refresh-liquigel-carmellose-sodium-1pct-eye-drops-15ml',
		name: 'refresh liquigel 1% eye drops 15 ml',
		genericName: 'sodium carboxymethylcellulose (carmellose)',
		concentration: '1% (15 ml)',
		price: 39.5,
		matchKeywords: ['refresh liquigel', 'refresh', 'carmellose', 'carboxymethylcellulose', 'ريفريش ليكويجل', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة جل/لزوجة أعلى (كارميلوز) مناسبة للجفاف المتوسط إلى الشديد.',
		timing: 'نقطة واحدة في كل عين ٣ مرات يومياً، وآخر جرعة قبل النوم.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً، وآخر جرعة قبل النوم.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS, 'قد يسبب زغللة مؤقتة بعد الجرعة.'],
	},

	// 18) systane hydration eye drops 30 x 0.7 ml sdu
	{
		id: 'systane-hydration-eye-drops-sdu-30x0-7',
		name: 'systane hydration eye drops 30 x 0.7 ml sdu',
		genericName: 'sodium hyaluronate & polyethylene glycol 400 & propylene glycol',
		concentration: '30 × 0.7 ml SDU',
		price: 580,
		matchKeywords: ['systane hydration sdu', 'systane hydration 30', 'hyaluronate', 'peg 400', 'propylene glycol', 'سيستان هايدريشن وحدات', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'دموع صناعية مرطبة (وحدات أحادية الجرعة).',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 19) hydratears eye drops 10 ml
	{
		id: 'hydratears-sodium-hyaluronate-eye-drops-10ml',
		name: 'hydratears eye drops 10 ml',
		genericName: 'sodium hyaluronate',
		concentration: '10 ml',
		price: 53,
		matchKeywords: ['hydratears', 'hyaluronate', 'هيالورونات', 'هايدراتيرز', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة هيالورونات لترطيب العين وتقليل الشعور بالجفاف.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 20) aqualarm intensive ud eye drops 30 x 0.5ml sdu
	{
		id: 'aqualarm-intensive-ud-sodium-hyaluronate-eye-drops-sdu-30x0-5',
		name: 'aqualarm intensive ud eye drops 30 x 0.5ml sdu',
		genericName: 'sodium hyaluronate',
		concentration: '30 × 0.5ml SDU',
		price: 425,
		matchKeywords: ['aqualarm intensive ud', 'aqualarm ud', 'hyaluronate', 'اكوالارم', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة هيالورونات (وحدات أحادية الجرعة) لترطيب العين مع الجفاف المتكرر.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 21) aqualarm u.p. intensive eye drops 10 ml
	{
		id: 'aqualarm-up-intensive-sodium-hyaluronate-eye-drops-10ml',
		name: 'aqualarm u.p. intensive eye drops 10 ml',
		genericName: 'sodium hyaluronate',
		concentration: '10 ml',
		price: 365,
		matchKeywords: ['aqualarm u.p.', 'aqualarm', 'hyaluronate', 'اكوالارم', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة هيالورونات لترطيب العين وتقليل الحرقان/الإحساس بالرمل مع الجفاف.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 22) relivatear eye drops
	{
		id: 'relivatear-carmellose-glycerin-eye-drops',
		name: 'relivatear eye drops',
		genericName: 'carboxymethylcellulose sodium & glycerin',
		concentration: 'Eye drops',
		price: 46,
		matchKeywords: ['relivatear', 'glycerin', 'carmellose', 'ريليفاتير', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة (كارميلوز + جليسرين) لترطيب العين وتقليل أعراض الجفاف.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 23) optilubric 0.32% eye drops 30*0.5 ml sdu
	{
		id: 'optilubric-hypromellose-0-32-eye-drops-sdu-30x0-5',
		name: 'optilubric 0.32% eye drops 30*0.5 ml sdu',
		genericName: 'hypromellose',
		concentration: '0.32% (30 × 0.5ml SDU)',
		price: 96,
		matchKeywords: ['optilubric 0.32', 'optilubric sdu', 'hypromellose', 'اوبتي لوبريك', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية (هيبروميلوز) بوحدات أحادية الجرعة لترطيب العين.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 24) refresh tears 0.5% lubricant eye drops 15 ml
	{
		id: 'refresh-tears-carmellose-sodium-0-5-eye-drops-15ml',
		name: 'refresh tears 0.5% lubricant eye drops 15 ml',
		genericName: 'sodium carboxymethylcellulose (carmellose)',
		concentration: '0.5% (15 ml)',
		price: 36,
		matchKeywords: ['refresh tears 0.5', 'refresh tears', 'carmellose', 'ريفريش تيرز', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية (كارميلوز) لترطيب العين وتقليل أعراض الجفاف.',
		timing: 'نقطة في كل عين ٣ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٣ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 25) tears naturale eye drops 15 ml
	{
		id: 'tears-naturale-dextran-hypromellose-eye-drops-15ml',
		name: 'tears naturale eye drops 15 ml',
		genericName: 'dextran & hydroxypropyl methylcellulose (hypromellose)',
		concentration: '15 ml',
		price: 143,
		matchKeywords: ['tears naturale', 'dextran', 'hypromellose', 'تيرز ناتشرال', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية (ديكستران + هيبروميلوز) لترطيب العين وتقليل الحرقان/التهيج.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 26) normo tears eye drops 15 ml
	{
		id: 'normo-tears-dextran-hypromellose-eye-drops-15ml',
		name: 'normo tears eye drops 15 ml',
		genericName: 'dextran & hydroxypropyl methylcellulose (hypromellose)',
		concentration: '15 ml',
		price: 26,
		matchKeywords: ['normo tears', 'dextran', 'hypromellose', 'نورمو تيرز', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة دموع صناعية (ديكستران + هيبروميلوز) لجفاف العين.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...COMMON_EYE_LUBRICANT_WARNINGS],
	},

	// 27) lacricarmin 2mg/0.4ml eye drops 30 x 0.4 ml sdu
	{
		id: 'lacricarmin-carmellose-2mg-0-4ml-eye-drops-sdu-30x0-4',
		name: 'lacricarmin 2mg/0.4ml eye drops 30 x 0.4 ml sdu',
		genericName: 'carmellose sodium',
		concentration: '2mg/0.4ml (30 × 0.4ml SDU)',
		price: 72,
		matchKeywords: ['lacricarmin 2mg', 'lacricarmin sdu', 'carmellose', 'لاكريكـارمين', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة (كارميلوز) بوحدات أحادية الجرعة لجفاف العين.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 28) lacricarmin 4mg/0.4ml eye drops 30 x 0.4 ml sdu
	{
		id: 'lacricarmin-carmellose-4mg-0-4ml-eye-drops-sdu-30x0-4',
		name: 'lacricarmin 4mg/0.4ml eye drops 30 x 0.4 ml sdu',
		genericName: 'carmellose sodium',
		concentration: '4mg/0.4ml (30 × 0.4ml SDU)',
		price: 90,
		matchKeywords: ['lacricarmin 4mg', 'lacricarmin sdu', 'carmellose', 'لاكريكـارمين', '#eye lubricant', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة مرطبة (كارميلوز) بوحدات أحادية الجرعة لجفاف العين (تركيز أعلى).',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 2,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً.'),
		warnings: [...SDU_WARNINGS],
	},
];

