import { Medication, Category } from '../../types';

const fixed = (t: string) => () => t;

const COMMON_EYE_WARNINGS = [
	'لا تلمس طرف القطارة للعين/الرموش لتجنب تلوث العبوة.',
	'العدسات اللاصقة: تُزال قبل الاستخدام وتُعاد بعد ١٥ دقيقة (ويُفضل تجنبها أثناء الالتهاب).',
	'إذا وُجد ألم شديد/رهاب ضوء/ضعف نظر: يلزم تقييم عيون.',
];

const STEROID_EYE_WARNINGS = [
	...COMMON_EYE_WARNINGS,
	'يحتوي على كورتيزون: يُتجنب عند الاشتباه في عدوى فيروسية بالعين أو قرحة قرنية.',
	'لا يُستخدم لفترات طويلة دون إعادة تقييم (قد يرفع ضغط العين ويسبب مضاعفات).',
];

const QUINOLONE_EYE_WARNINGS = [
	...COMMON_EYE_WARNINGS,
	'قد يسبب حرقان/لسعة بسيطة مؤقتاً.',
];

const FUSIDIC_EYE_WARNINGS = [
	...COMMON_EYE_WARNINGS,
	'قطرات لزجة: قد تسبب زغللة بسيطة بعد الجرعة.',
];

export const OPHTHALMIC_ANTIBIOTICS_GROUP: Medication[] = [
	// 1) blephadexoline eye drops 10 ml
	{
		id: 'blephadexoline-eye-drops-10ml',
		name: 'Blephadexoline eye drops 10 ml',
		genericName: 'chloramphenicol & dexamethasone & tetrahydrozoline',
		concentration: '10 ml',
		price: 45,
		matchKeywords: [
			'blephadexoline',
			'chloramphenicol',
			'dexamethasone',
			'tetrahydrozoline',
			'eye drops',
			'احمرار',
			'التهاب عين',
			'#antibiotics',
			'#anti-inflammatory',
			'عين',
			'قطرة عين',
			'ophthalmic',
		],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون + مزيل احتقان) لالتهاب/عدوى بكتيرية مع التهاب واحمرار.',
		timing: '٣–٤ مرات يومياً لمدة قصيرة.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في العين المصابة ٣–٤ مرات يومياً لمدة ٥–٧ أيام ثم تقليل/إيقاف'),
		warnings: [...STEROID_EYE_WARNINGS],
	},

	// 2) ofusidic viscous eye drops 5 ml
	{
		id: 'ofusidic-viscous-eye-drops-5ml',
		name: 'Ofusidic viscous eye drops 5 ml',
		genericName: 'fusidic acid',
		concentration: '5 ml',
		price: 28,
		matchKeywords: [
			'ofusidic',
			'fusidic acid',
			'viscous',
			'fucithalmic',
			'eye drops',
			'التهاب ملتحمة',
			'#antibiotics',
			'عين',
			'قطرة عين',
			'ophthalmic',
		],
		usage: 'قطرة عين لزجة (فيوسيدك أسيد) لالتهاب الملتحمة البكتيري.',
		timing: 'مرتين يومياً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة مرتين يومياً لمدة ٧ أيام'),
		warnings: [...FUSIDIC_EYE_WARNINGS],
	},

	// 3) orchadexoline eye drops 5 ml
	{
		id: 'orchadexoline-eye-drops-5ml',
		name: 'Orchadexoline eye drops 5 ml',
		genericName: 'chloramphenicol & dexamethasone sodium phosphate',
		concentration: '5 ml',
		price: 27,
		matchKeywords: [
			'orchadexoline',
			'chloramphenicol',
			'dexamethasone',
			'eye drops',
			'#antibiotics',
			'#anti-inflammatory',
			'عين',
			'قطرة عين',
			'ophthalmic',
		],
		usage: 'قطرة عين (كلورامفينيكول + كورتيزون) لالتهاب/عدوى بكتيرية مع التهاب.',
		timing: '٤ مرات يومياً لمدة قصيرة.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٤ مرات يومياً لمدة ٥–٧ أيام ثم تقليل'),
		warnings: [...STEROID_EYE_WARNINGS],
	},

	// 4) tymer 0.3% eye drops 5 ml
	{
		id: 'tymer-0.3-eye-drops-5ml',
		name: 'Tymer 0.3% eye drops 5 ml',
		genericName: 'gatifloxacin',
		concentration: '0.3% (5 ml)',
		price: 66,
		matchKeywords: ['tymer', 'gatifloxacin', 'quinolone', 'eye drops', 'التهاب ملتحمة', '#antibiotics', '#quinolone', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين كينولون (جاتيفلوكساسين) لالتهاب الملتحمة البكتيري/التهاب القرنية حسب التشخيص.',
		timing: '٤ مرات يومياً عادةً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٤ مرات يومياً لمدة ٧ أيام'),
		warnings: [...QUINOLONE_EYE_WARNINGS],
	},

	// 5) ocubesiflox eye susp. drops 5 ml
	{
		id: 'ocubesiflox-eye-susp-drops-5ml',
		name: 'Ocubesiflox eye susp. drops 5 ml',
		genericName: 'besifloxacin',
		concentration: '5 ml',
		price: 82,
		matchKeywords: ['ocubesiflox', 'besifloxacin', 'eye drops', 'susp', '#antibiotics', '#quinolone', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين كينولون (بيسيفلوكساسين) لالتهاب الملتحمة البكتيري.',
		timing: '٣ مرات يومياً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...QUINOLONE_EYE_WARNINGS],
	},

	// 6) gatilox 0.3% ophthalmic soln. 15 ml
	{
		id: 'gatilox-0.3-ophthalmic-soln-15ml',
		name: 'Gatilox 0.3% ophthalmic soln. 15 ml',
		genericName: 'gatifloxacin',
		concentration: '0.3% (15 ml)',
		price: 18,
		matchKeywords: ['gatilox', 'gatifloxacin', 'eye drops', '#antibiotics', '#quinolone', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين كينولون (جاتيفلوكساسين) لالتهابات العين البكتيرية.',
		timing: '٤ مرات يومياً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٤ مرات يومياً لمدة ٧ أيام'),
		warnings: [...QUINOLONE_EYE_WARNINGS],
	},

	// 7) orchacin 0.3% eye drops 5 ml
	{
		id: 'orchacin-0.3-eye-drops-10ml',
		name: 'Orchacin 0.3% eye drops 5 ml',
		genericName: 'lomefloxacin',
		concentration: '0.3% (5 ml)',
		price: 10,
		matchKeywords: ['orchacin', 'lomefloxacin', 'eye drops', '#antibiotics', '#quinolone', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين كينولون (لوميفلوكساسين) لالتهاب الملتحمة البكتيري.',
		timing: '٤ مرات يومياً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٤ مرات يومياً لمدة ٧ أيام'),
		warnings: [...QUINOLONE_EYE_WARNINGS],
	},

	// 8) gatyxel 0.3% ophthalmic soln. 5 ml
	{
		id: 'gatyxel-0.3-ophthalmic-soln-5ml',
		name: 'Gatyxel 0.3% ophthalmic soln. 5 ml',
		genericName: 'gatifloxacin',
		concentration: '0.3% (5 ml)',
		price: 18,
		matchKeywords: ['gatyxel', 'gatifloxacin', 'eye drops', '#antibiotics', '#quinolone', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين كينولون (جاتيفلوكساسين) لالتهابات العين البكتيرية.',
		timing: '٤ مرات يومياً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٤ مرات يومياً لمدة ٧ أيام'),
		warnings: [...QUINOLONE_EYE_WARNINGS],
	},

	// 9) gatyxel eye ointment 5 gm
	{
		id: 'gatyxel-eye-oint-5gm',
		name: 'Gatyxel eye ointment 5 gm',
		genericName: 'gatifloxacin',
		concentration: '5 gm',
		price: 25.5,
		matchKeywords: ['gatyxel oint', 'gatifloxacin oint', 'eye ointment', '#antibiotics', '#quinolone', 'عين', 'مرهم عين', 'ophthalmic'],
		usage: 'مرهم عين كينولون (جاتيفلوكساسين) لالتهابات العين البكتيرية.',
		timing: '٢–٣ مرات يومياً لمدة ٥–٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('شريط صغير (~١ سم) داخل الجفن السفلي ٢–٣ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: [...QUINOLONE_EYE_WARNINGS],
	},

	// 10) dexathalm eye drops 5 ml
	{
		id: 'dexathalm-eye-drops-5ml',
		name: 'Dexathalm eye drops 5 ml',
		genericName: 'dexamethasone & netilmicin',
		concentration: '5 ml',
		price: 82,
		matchKeywords: ['dexathalm', 'netilmicin', 'dexamethasone', 'eye drops', '#antibiotics', '#glucocorticoid', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون) لالتهاب/عدوى بكتيرية بالعين.',
		timing: '٤ مرات يومياً لمدة قصيرة.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٤ مرات يومياً لمدة ٥–٧ أيام ثم تقليل'),
		warnings: [...STEROID_EYE_WARNINGS],
	},

	// 11) fucithalmic 1% viscous eye drops 5 gm
	{
		id: 'fucithalmic-1pct-viscous-eye-drops-5gm',
		name: 'Fucithalmic 1% viscous eye drops 5 gm',
		genericName: 'fusidic acid',
		concentration: '1% (5 gm)',
		price: 37,
		matchKeywords: ['fucithalmic', 'fusidic acid', 'viscous', 'eye drops', 'التهاب ملتحمة', '#antibiotics', 'عين', 'قطرة عين', 'ophthalmic'],
		usage: 'قطرة عين لزجة (فيوسيدك أسيد) لالتهاب الملتحمة البكتيري.',
		timing: 'مرتين يومياً لمدة ٧ أيام.',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة مرتين يومياً لمدة ٧ أيام'),
		warnings: [...FUSIDIC_EYE_WARNINGS],
	},
];

