import { Medication, Category } from '../../types';

const fixed = (t: string) => () => t;

const COMMON_EYE_WARNINGS = [
	'لا تلمس طرف القطارة/العبوة للعين أو الرموش لتجنب تلوث القطرة.',
	'العدسات اللاصقة: تُزال قبل الاستخدام وتُعاد بعد ١٥ دقيقة.',
	'إذا وُجد ألم شديد/رهاب ضوء/ضعف نظر أو إفرازات صديدية: يلزم تقييم عيون.',
];

const SDU_WARNINGS = [
	...COMMON_EYE_WARNINGS,
	'وحدات أحادية الجرعة: تُستخدم مرة واحدة ثم تُرمى.',
];

const VASOCONSTRICTOR_WARNINGS = [
	...COMMON_EYE_WARNINGS,
	'يحتوي على مزيل احتقان (Naphazoline): لا يُستخدم أكثر من ٣ أيام متتالية لتجنب ارتداد الاحمرار.',
	'يُتجنب مع جلوكوما ضيقة الزاوية.',
];

export const OPHTHALMIC_ANTIHISTAMINIC_GROUP: Medication[] = [
	// 1) conjyclear 0.1% eye drops 5 ml
	{
		id: 'conjyclear-olopatadine-0-1-eye-drops-5ml',
		name: 'conjyclear 0.1% eye drops 5 ml',
		genericName: 'olopatadine',
		concentration: '0.1% (5 ml)',
		price: 22,
		matchKeywords: ['conjyclear', 'olopatadine 0.1', 'olopatadine', 'كونجيكلير', 'حساسية العين', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين لتقليل الحكة والاحمرار مع حساسية الملتحمة.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 2) conjyclear forte 0.2% eye drops 5 ml
	{
		id: 'conjyclear-forte-olopatadine-0-2-eye-drops-5ml',
		name: 'conjyclear forte 0.2% eye drops 5 ml',
		genericName: 'olopatadine',
		concentration: '0.2% (5 ml)',
		price: 40,
		matchKeywords: ['conjyclear forte', 'olopatadine 0.2', 'كونجيكلير فورت', 'حساسية العين', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين (تركيز أعلى) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرة يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرة يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 3) conjyclear forte 0.2% eye drops 30 x 0.4 ml sdu
	{
		id: 'conjyclear-forte-olopatadine-0-2-eye-drops-sdu-30x0-4',
		name: 'conjyclear forte 0.2% eye drops 30 x 0.4 ml sdu',
		genericName: 'olopatadine',
		concentration: '0.2% (30 × 0.4 ml SDU)',
		price: 78,
		matchKeywords: ['conjyclear forte sdu', 'olopatadine 0.2 sdu', 'كونجيكلير فورت وحدات', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين (وحدات أحادية الجرعة) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرة يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرة يومياً.'),
		warnings: [...SDU_WARNINGS],
	},

	// 4) nostamine eye/nose drops 15 ml
	{
		id: 'nostamine-naphazoline-chlorpheniramine-eye-nose-drops-15ml',
		name: 'nostamine eye/nose drops 15 ml',
		genericName: 'naphazoline hydrochloride & chlorpheniramine',
		concentration: '15 ml',
		price: 22,
		matchKeywords: ['nostamine', 'naphazoline', 'chlorpheniramine', 'نوستامين', 'احمرار العين', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة (عين/أنف) لتقليل احمرار/حكة العين المرتبطة بالحساسية لفترة قصيرة.',
		timing: 'نقطة في العين المصابة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في العين المصابة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},

	// 5) olohistine 1mg/ml ophthalmic sol. 5 ml
	{
		id: 'olohistine-olopatadine-1mg-ml-eye-drops-5ml',
		name: 'olohistine 1mg/ml ophthalmic sol. 5 ml',
		genericName: 'olopatadine',
		concentration: '1mg/ml (5 ml)',
		price: 22.8,
		matchKeywords: ['olohistine', 'olopatadine', 'اولوهيستين', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين لتقليل الحكة والاحمرار مع حساسية الملتحمة.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 6) ocumethyl eye drops 10 ml
	{
		id: 'ocumethyl-zinc-naphazoline-diphenhydramine-eye-drops-10ml',
		name: 'ocumethyl eye drops 10 ml',
		genericName: 'zinc sulphate & naphazoline hydrochloride & diphenhydramine',
		concentration: '10 ml',
		price: 22,
		matchKeywords: ['ocumethyl', 'naphazoline', 'diphenhydramine', 'zinc', 'اوكيوميثيل', 'احمرار العين', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة عين لتقليل الحكة/الاحمرار التحسسي لفترة قصيرة.',
		timing: 'نقطة في العين المصابة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},

	// 7) prisoline eye/nasal drops 15 ml
	{
		id: 'prisoline-naphazoline-chlorpheniramine-eye-nasal-drops-15ml',
		name: 'prisoline eye/nasal drops 15 ml',
		genericName: 'naphazoline hydrochloride & chlorpheniramine maleate',
		concentration: '15 ml',
		price: 23,
		matchKeywords: ['prisoline', 'naphazoline', 'chlorpheniramine', 'بريزولين', 'احمرار العين', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة (عين/أنف) لتقليل احمرار/حكة العين المرتبطة بالحساسية لفترة قصيرة.',
		timing: 'نقطة في العين المصابة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في العين المصابة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},

	// 8) optozoline eye drops 10 ml
	{
		id: 'optozoline-chlorpheniramine-naphazoline-eye-drops-10ml',
		name: 'optozoline eye drops 10 ml',
		genericName: 'chlorpheniramine maleate & naphazoline hydrochloride',
		concentration: '10 ml',
		price: 24,
		matchKeywords: ['optozoline 10', 'optozoline', 'naphazoline', 'chlorpheniramine', 'اوبتوزولين', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة عين للحكة/الاحمرار التحسسي لفترة قصيرة.',
		timing: 'نقطة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في العين المصابة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},

	// 9) orchazid 0.025% eye dps. 10 ml
	{
		id: 'orchazid-ketotifen-0-025-eye-drops-10ml',
		name: 'orchazid 0.025% eye dps. 10 ml',
		genericName: 'ketotifen',
		concentration: '0.025% (10 ml)',
		price: 31,
		matchKeywords: ['orchazid 10ml', 'orchazid', 'ketotifen', 'اوركازيد', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (كيتوتيفين) لتقليل حكة واحمرار العين.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 10) ocuseellerge forte eye drops 5 ml
	{
		id: 'ocuseellerge-forte-epinastine-eye-drops-5ml',
		name: 'ocuseellerge forte eye drops 5 ml',
		genericName: 'epinastine hydrochloride',
		concentration: '5 ml',
		price: 44.5,
		matchKeywords: ['ocuseellerge forte', 'ocuseellerge', 'epinastine', 'اوكيـوسيليرج فورت', '#anti-allergic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (إبيناستين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 11) lergeblock 1.5% eye drops. 10 ml
	{
		id: 'lergeblock-bepotastine-1-5-eye-drops-10ml',
		name: 'lergeblock 1.5% eye drops. 10 ml',
		genericName: 'bepotastine besilate',
		concentration: '1.5% (10 ml)',
		price: 113,
		matchKeywords: ['lergeblock', 'bepotastine', 'ليرج بلوك', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (بيبوتاستين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 12) ocuseellerge 0.05% eye drops 5 ml
	{
		id: 'ocuseellerge-epinastine-0-05-eye-drops-5ml',
		name: 'ocuseellerge 0.05% eye drops 5 ml',
		genericName: 'epinastine hydrochloride',
		concentration: '0.05% (5 ml)',
		price: 30,
		matchKeywords: ['ocuseellerge 0.05', 'epinastine', 'اوكيـوسيليرج', '#h1 blocker', '#h2 blocker', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (إبيناستين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 13) optozoline eye drops 15 ml
	{
		id: 'optozoline-chlorpheniramine-naphazoline-eye-drops-15ml',
		name: 'optozoline eye drops 15 ml',
		genericName: 'chlorpheniramine maleate & naphazoline hydrochloride',
		concentration: '15 ml',
		price: 1.5,
		matchKeywords: ['optozoline 15', 'optozoline', 'naphazoline', 'chlorpheniramine', 'اوبتوزولين', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة عين للحكة/الاحمرار التحسسي لفترة قصيرة.',
		timing: 'نقطة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},

	// 14) orchazid 0.025% eye drops 30*0.4 ml sdu
	{
		id: 'orchazid-ketotifen-0-025-eye-drops-sdu-30x0-4',
		name: 'orchazid 0.025% eye drops 30*0.4 ml sdu',
		genericName: 'ketotifen',
		concentration: '0.025% (30 × 0.4 ml SDU)',
		price: 60,
		matchKeywords: ['orchazid sdu', 'ketotifen sdu', 'اوركازيد وحدات', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (كيتوتيفين) بوحدات أحادية الجرعة.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...SDU_WARNINGS],
	},

	// 15) orchinohist 0.25% eye dps. 3 ml
	{
		id: 'orchinohist-alcaftadine-0-25-eye-drops-3ml',
		name: 'orchinohist 0.25% eye dps. 3 ml',
		genericName: 'alcaftadine',
		concentration: '0.25% (3 ml)',
		price: 53,
		matchKeywords: ['orchinohist', 'alcaftadine', 'اوركينوهيست', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (ألكافتادين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرة يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرة يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 16) zelagap 0.05% eye drops 6 ml
	{
		id: 'zelagap-azelastine-0-05-eye-drops-6ml',
		name: 'zelagap 0.05% eye drops 6 ml',
		genericName: 'azelastine',
		concentration: '0.05% (6 ml)',
		price: 26.5,
		matchKeywords: ['zelagap', 'azelastine', 'زيلاجاب', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (أزيلاستين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 17) naphcozole eye drops 10 ml
	{
		id: 'naphcozole-naphazoline-pheniramine-eye-drops-10ml',
		name: 'naphcozole eye drops 10 ml',
		genericName: 'naphazoline hydrochloride & pheniramine maleate',
		concentration: '10 ml',
		price: 14,
		matchKeywords: ['naphcozole', 'naphazoline', 'pheniramine', 'نافكوزول', 'احمرار العين', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة عين للحكة/الاحمرار التحسسي لفترة قصيرة.',
		timing: 'نقطة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في العين المصابة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},

	// 18) ophilocond forte 0.2% eye drops 5 ml
	{
		id: 'ophilocond-forte-olopatadine-0-2-eye-drops-5ml',
		name: 'ophilocond forte 0.2% eye drops 5 ml',
		genericName: 'olopatadine',
		concentration: '0.2% (5 ml)',
		price: 56,
		matchKeywords: ['ophilocond forte', 'olopatadine 0.2', 'اوفيلوكند فورت', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين (أولوباتادين 0.2%) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرة يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرة يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 19) olopat 0.1% eye drops 5 ml
	{
		id: 'olopat-olopatadine-0-1-eye-drops-5ml',
		name: 'olopat 0.1% eye drops 5 ml',
		genericName: 'olopatadine',
		concentration: '0.1% (5 ml)',
		price: 18.6,
		matchKeywords: ['olopat', 'olopatadine 0.1', 'اولوپات', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 20) ophilocond 0.1% eye drops 5 ml
	{
		id: 'ophilocond-olopatadine-0-1-eye-drops-5ml',
		name: 'ophilocond 0.1% eye drops 5 ml',
		genericName: 'olopatadine',
		concentration: '0.1% (5 ml)',
		price: 22.5,
		matchKeywords: ['ophilocond 0.1', 'ophilocond', 'olopatadine 0.1', 'اوفيلوكند', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 21) patadoline 0.1% eye drops 5 ml
	{
		id: 'patadoline-olopatadine-0-1-eye-drops-5ml',
		name: 'patadoline 0.1% eye drops 5 ml',
		genericName: 'olopatadine',
		concentration: '0.1% (5 ml)',
		price: 38,
		matchKeywords: ['patadoline', 'olopatadine 0.1', 'پاتادولين', '#ophthalmic antihistaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة لحساسية العين لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً (كل ١٢ ساعة).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 22) epicrom 4% eye drops 10 ml
	{
		id: 'epicrom-sodium-cromoglycate-4-eye-drops-10ml',
		name: 'epicrom 4% eye drops 10 ml',
		genericName: 'sodium cromoglycate',
		concentration: '4% (10 ml)',
		price: 14.5,
		matchKeywords: ['epicrom 4', 'epicrom', 'cromoglycate', 'كروموجليكات', 'ايبيكروم', '#anti-histaminic', '#anti-allergic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (مثبت خلايا mast) للوقاية وتقليل أعراض حساسية العين.',
		timing: 'نقطة في كل عين ٤ مرات يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين ٤ مرات يومياً (كل ٦ ساعات).'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 23) optest 0.05% eye dps. 5 ml
	{
		id: 'optest-epinastine-0-05-eye-drops-5ml',
		name: 'optest 0.05% eye dps. 5 ml',
		genericName: 'epinastine',
		concentration: '0.05% (5 ml)',
		price: 28,
		matchKeywords: ['optest', 'epinastine 0.05', 'اوبتست', '#h1 blocker', '#h2 blocker', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (إبيناستين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 24) cornefresh 1.5% eye drops 5 ml
	{
		id: 'cornefresh-bepotastine-1-5-eye-drops-5ml',
		name: 'cornefresh 1.5% eye drops 5 ml',
		genericName: 'bepotastine',
		concentration: '1.5% (5 ml)',
		price: 67,
		matchKeywords: ['cornefresh', 'bepotastine 1.5', 'كورنيفريش', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (بيبوتاستين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرتين يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرتين يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 25) caftohist 0.25% eye drops 3 ml
	{
		id: 'caftohist-alcaftadine-0-25-eye-drops-3ml',
		name: 'caftohist 0.25% eye drops 3 ml',
		genericName: 'alcaftadine',
		concentration: '0.25% (3 ml)',
		price: 68,
		matchKeywords: ['caftohist', 'alcaftadine 0.25', 'كافتوهيست', '#anti-histaminic', 'عين', 'eye', 'ophthalmic', 'حساسية عين'],
		usage: 'قطرة مضادة للحساسية (ألكافتادين) لتقليل الحكة والاحمرار.',
		timing: 'نقطة في كل عين مرة يومياً.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 36,
		maxAgeMonths: 1200,
		minWeight: 12,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في كل عين مرة يومياً.'),
		warnings: [...COMMON_EYE_WARNINGS],
	},

	// 26) prisoline zinc eye drops 15 ml
	{
		id: 'prisoline-zinc-chlorpheniramine-naphazoline-eye-drops-15ml',
		name: 'prisoline zinc eye drops 15 ml',
		genericName: 'chlorpheniramine maleate & naphazoline hydrochloride & zinc sulphate',
		concentration: '15 ml',
		price: 5,
		matchKeywords: ['prisoline zinc', 'prisoline', 'naphazoline', 'chlorpheniramine', 'zinc', 'بريزولين زنك', '#anti-histaminic', '#alpha 1 agonist', 'عين', 'eye', 'ophthalmic'],
		usage: 'قطرة عين للحكة/الاحمرار التحسسي لفترة قصيرة.',
		timing: 'نقطة ٢–٣ مرات يومياً لمدة لا تتجاوز ٣ أيام.',
		category: Category.OPHTHALMIC,
		form: 'Eye Drops',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('نقطة واحدة في العين المصابة ٢–٣ مرات يومياً. لا تستخدمه أكثر من ٣ أيام متتالية.'),
		warnings: [...VASOCONSTRICTOR_WARNINGS],
	},
];

