import { Medication, Category } from '../../types';

const TAGS = {
  antiGout: ['anti-gout', '#anti-gout', 'gout', 'نقرس'],
  uricAcid: ['uric acid', '#uric acid', 'hyperuricemia', 'حمض اليوريك'],
  analgesics: ['analgesics', '#analgesics', 'pain', 'مسكن'],
  xoi: ['xanthine oxidase inhibitor', '#xanthine oxidase inhibitor', 'XOI'],
};

const commonAntiGoutWarnings = [
  'الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.',
  'اشرب سوائل كفاية وقلل الأطعمة عالية البيورين حسب التشخيص والحمية.',
];

const ANTIGOUT_RAW: Medication[] = [
  // 1. ur-aid eff. granul. 12 sachets (n/a)
  {
    id: 'ur-aid-eff-granules-12-sachets',
    name: 'ur-aid eff. granul. 12 sachets (n/a)',
    genericName: 'Piperazine & Colchicine & Atropine sulphate',
    concentration: 'Sachets',
    price: 38,
    matchKeywords: ['ur-aid', 'ur aid', 'يورايد', 'piperazine', 'colchicine', 'atropine', ...TAGS.antiGout, ...TAGS.uricAcid, ...TAGS.analgesics],
    usage: 'فوار يُستخدم كمساعد لأعراض النقرس/الأملاح حسب التشخيص والحالة.',
    timing: 'عادةً ٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كيس ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonAntiGoutWarnings,
      'تحذيرات: يحتوي على أتروبين (قد يسبب جفاف فم/زغللة) ويُتجنب في الجلوكوما/احتباس البول.',
      'تداخلات: لا تستخدمه مع أدوية أخرى تحتوي على كولشيسين دون إعادة تقييم.',
    ],
  },

  // 2. urosolvine eff. gran. 12 sachets
  {
    id: 'urosolvine-eff-granules-12-sachets',
    name: 'urosolvine eff. gran. 12 sachets',
    genericName: 'Colchicine & Piperazine citrate & Atropine sulphate',
    concentration: 'Sachets',
    price: 34,
    matchKeywords: ['urosolvine', 'يوروسولفين', 'colchicine', 'piperazine', 'atropine', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'فوار مساعد في حالات النقرس/الأملاح حسب التشخيص والحالة.',
    timing: '٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كيس ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonAntiGoutWarnings,
      'تحذيرات: أتروبين (يُتجنب في الجلوكوما/احتباس البول).',
    ],
  },

  // 3. uraid-n eff. granul. 12 sachets
  {
    id: 'uraid-n-eff-granules-12-sachets',
    name: 'uraid-n eff. granul. 12 sachets',
    genericName: 'Piperazine citrate & Colchicine',
    concentration: 'Sachets',
    price: 38,
    matchKeywords: ['uraid-n', 'uraid n', 'يورايد ان', 'piperazine', 'colchicine', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'فوار مساعد للنقرس/الأملاح حسب التشخيص والحالة.',
    timing: '٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كيس ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: لا تكرر كولشيسين من مصدر آخر دون إعادة تقييم.'],
  },

  // 4. colchicine 500mcg 100 tab
  {
    id: 'colchicine-0-5mg-tabs-100',
    name: 'colchicine 500mcg 100 tab',
    genericName: 'Colchicine',
    concentration: '0.5mg',
    price: 190,
    matchKeywords: ['colchicine 0.5', 'كولشيسين', '500mcg', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'لعلاج نوبات النقرس والوقاية منها حسب التشخيص.',
    timing: 'حسب الحالة (نوبة حادة/وقاية).',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'النوبة الحادة: حسب التشخيص والحالة. الوقاية: غالباً قرص 1–2 يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonAntiGoutWarnings,
      'تداخلات خطيرة: بعض المضادات الحيوية/مضادات الفطريات (مثل كلاريثروميسين/إريثروميسين/كيتوكونازول) قد ترفع مستوى الكولشيسين—لا تجمع دون إعادة تقييم.',
      'تحذيرات: يُستخدم بحذر مع أمراض كلى/كبد؛ قد يلزم تقليل الجرعة.',
    ],
  },

  // 5. feburic 80mg 30 f.c. tablets
  {
    id: 'feburic-febuxostat-80mg-fc-tabs-30',
    name: 'feburic 80mg 30 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 139.5,
    matchKeywords: ['feburic 80', 'فيبوريك', 'febuxostat', ...TAGS.antiGout, ...TAGS.uricAcid],
    usage: 'خفض حمض اليوريك في النقرس المزمن/فرط اليوريك (ليس لعلاج النوبة الحادة).',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد مرة يومياً (لا يُبدأ عادةً أثناء نوبة حادة إلا بعد إعادة تقييم).',
    warnings: [
      ...commonAntiGoutWarnings,
      'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين (تداخل خطير).',
      'تحذيرات: قد تزيد نوبات النقرس في البداية—لا توقف العلاج دون إعادة تقييم.',
    ],
  },

  // 6. xanthistop 120 mg 30 tablets
  {
    id: 'xanthistop-febuxostat-120mg-tabs-30',
    name: 'xanthistop 120 mg 30 tablets',
    genericName: 'Febuxostat',
    concentration: '120mg',
    price: 177,
    matchKeywords: ['xanthistop 120', 'زانثيستوب 120', 'febuxostat', ...TAGS.antiGout, ...TAGS.uricAcid],
    usage: 'خفض حمض اليوريك (جرعة أعلى) حسب التشخيص.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد مرة يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 7. xanthistop 80 mg 30 tablets
  {
    id: 'xanthistop-febuxostat-80mg-tabs-30',
    name: 'xanthistop 80 mg 30 tablets',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 147,
    matchKeywords: ['xanthistop 80', 'زانثيستوب 80', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك في النقرس المزمن.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 8. uricodrop 80 mg 30 f.c. tabs.
  {
    id: 'uricodrop-febuxostat-80mg-fc-tabs-30',
    name: 'uricodrop 80 mg 30 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 123,
    matchKeywords: ['uricodrop 80', 'يوريكودروب', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك في النقرس المزمن.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 9. feburic 120 mg 10 f.c. tablets
  {
    id: 'feburic-febuxostat-120mg-fc-tabs-10',
    name: 'feburic 120 mg 10 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '120mg',
    price: 73,
    matchKeywords: ['feburic 120 10', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة أعلى) حسب التشخيص.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 10. no-uric 300mg 20 tab.
  {
    id: 'no-uric-allopurinol-300mg-tabs-20',
    name: 'no-uric 300mg 20 tab.',
    genericName: 'Allopurinol',
    concentration: '300mg',
    price: 38,
    matchKeywords: ['no-uric 300', 'نو يوريك', 'allopurinol', ...TAGS.antiGout, ...TAGS.xoi, ...TAGS.uricAcid],
    usage: 'خفض حمض اليوريك في النقرس المزمن/فرط اليوريك (ليس لعلاج النوبة الحادة).',
    timing: 'مرة يومياً بعد الأكل.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً بعد الأكل (تُعدل الجرعة حسب الكلى وحمض اليوريك حسب التشخيص).',
    warnings: [
      ...commonAntiGoutWarnings,
      'تحذيرات: أوقفه وراجع فوراً عند طفح جلدي/حكة شديدة أو تورم (احتمال حساسية خطيرة).',
      'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين أو يلزم تقليل جرعتهم جداً حسب التشخيص والتحاليل.',
    ],
  },

  // 11. uricodrop 40 mg 20 f.c. tabs.
  {
    id: 'uricodrop-febuxostat-40mg-fc-tabs-20',
    name: 'uricodrop 40 mg 20 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 60,
    matchKeywords: ['uricodrop 40', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة بداية) في النقرس المزمن.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 12. feburic 40 mg 10 f.c. tablets
  {
    id: 'feburic-febuxostat-40mg-fc-tabs-10',
    name: 'feburic 40 mg 10 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 38,
    matchKeywords: ['feburic 40 10', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة بداية).',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 13. goutifade 40 mg 20 f.c. tablets
  {
    id: 'goutifade-febuxostat-40mg-fc-tabs-20',
    name: 'goutifade 40 mg 20 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 60,
    matchKeywords: ['goutifade 40', 'جوتيفايد', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 14. goutifade 80 mg 30 f.c. tabs.
  {
    id: 'goutifade-febuxostat-80mg-fc-tabs-30',
    name: 'goutifade 80 mg 30 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 123,
    matchKeywords: ['goutifade 80', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 15. no-uric 100mg 50 tab.
  {
    id: 'no-uric-allopurinol-100mg-tabs-50',
    name: 'no-uric 100mg 50 tab.',
    genericName: 'Allopurinol',
    concentration: '100mg',
    price: 65,
    matchKeywords: ['no-uric 100', 'allopurinol 100', ...TAGS.antiGout, ...TAGS.xoi, ...TAGS.uricAcid],
    usage: 'خفض حمض اليوريك (جرعة بداية/للكلى) في النقرس المزمن.',
    timing: 'مرة يومياً بعد الأكل.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً بعد الأكل (قد تُزاد تدريجياً حسب التشخيص والحالة).',
    warnings: [
      ...commonAntiGoutWarnings,
      'تحذيرات: طفح جلدي/حساسية شديدة—أوقفه وراجع فوراً.',
      'تداخلات: أزاثيوبرين/ميركابتوبورين تداخل خطير.',
    ],
  },

  // 16. xanthibux 80 mg 20 f.c. tabs.
  {
    id: 'xanthibux-febuxostat-80mg-fc-tabs-20',
    name: 'xanthibux 80 mg 20 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 63.75,
    matchKeywords: ['xanthibux 80', 'زانثيبوكس', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 17. goutifade 40 mg 30 f.c. tablets
  {
    id: 'goutifade-febuxostat-40mg-fc-tabs-30',
    name: 'goutifade 40 mg 30 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 90,
    matchKeywords: ['goutifade 40 30', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 18. goutifade 80 mg 20 f.c. tabs.
  {
    id: 'goutifade-febuxostat-80mg-fc-tabs-20',
    name: 'goutifade 80 mg 20 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 82,
    matchKeywords: ['goutifade 80 20', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 19. colchicine 1mg 30 tab
  {
    id: 'colchicine-1mg-tabs-30',
    name: 'colchicine 1mg 30 tab',
    genericName: 'Colchicine',
    concentration: '1mg',
    price: 15,
    matchKeywords: ['colchicine 1mg', 'كولشيسين 1', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'لعلاج نوبة النقرس والوقاية حسب التشخيص.',
    timing: 'حسب الحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'النوبة الحادة: حسب التشخيص والحالة. الوقاية: حسب التشخيص والحالة.',
    warnings: [
      ...commonAntiGoutWarnings,
      'تداخلات خطيرة: كلاريثروميسين/إريثروميسين/بعض مضادات الفطريات—لا تجمع دون إعادة تقييم.',
      'تحذيرات: الحذر مع الكلى/الكبد.',
    ],
  },

  // 20. donifoxate 80 mg 30 f.c. tablets
  {
    id: 'donifoxate-febuxostat-80mg-fc-tabs-30',
    name: 'donifoxate 80 mg 30 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 118.5,
    matchKeywords: ['donifoxate 80', 'دونيفاكسات', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 21. goutyless 30 tabs
  {
    id: 'goutyless-probenecid-colchicine-tabs-30',
    name: 'goutyless 30 tabs',
    genericName: 'Probenecid & Colchicine',
    concentration: 'Tablets',
    price: 135,
    matchKeywords: ['goutyless', 'جوتيليس', 'probenecid', 'colchicine', ...TAGS.antiGout, ...TAGS.uricAcid],
    usage: 'دواء للنقرس (يوركوسوريك + كولشيسين) حسب التشخيص.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'الجرعة تُحدد حسب البروتوكول.',
    warnings: [
      ...commonAntiGoutWarnings,
      'تحذيرات: قد يزيد خطر حصوات الكلى—يلزم سوائل ومتابعة.',
      'تداخلات: أدوية كثيرة قد تتأثر (بروبينسيد)؛ راجع تداخلات المريض.',
    ],
  },

  // 22. uricodrop 120 mg 10 f.c. tabs.
  {
    id: 'uricodrop-febuxostat-120mg-fc-tabs-10',
    name: 'uricodrop 120 mg 10 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '120mg',
    price: 53,
    matchKeywords: ['uricodrop 120 10', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة أعلى) حسب التشخيص والحالة.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 23. xanthibux 40 mg 20 f.c. tabs.
  {
    id: 'xanthibux-febuxostat-40mg-fc-tabs-20',
    name: 'xanthibux 40 mg 20 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 70,
    matchKeywords: ['xanthibux 40', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة بداية).',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 24. gouryst 0.5 mg 100 tabs.
  {
    id: 'gouryst-colchicine-0-5mg-tabs-100',
    name: 'gouryst 0.5 mg 100 tabs.',
    genericName: 'Colchicine',
    concentration: '0.5mg',
    price: 190,
    matchKeywords: ['gouryst', 'جوريست', 'colchicine', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'كولشيسين للنقرس حسب التشخيص.',
    timing: 'حسب الحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'حسب التشخيص والحالة (نوبة حادة/وقاية).',
    warnings: [
      ...commonAntiGoutWarnings,
      'تداخلات: ماكرولايد/آزول—لا تجمع دون إعادة تقييم.',
      'تحذيرات: الحذر مع الكلى/الكبد.',
    ],
  },

  // 25. andouristat 80 mg 20 f.c. tablets
  {
    id: 'andouristat-febuxostat-80mg-fc-tabs-20',
    name: 'andouristat 80 mg 20 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 80,
    matchKeywords: ['andouristat 80', 'اندوريستات', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 26. uricol plus 12 sachets
  {
    id: 'uricol-plus-12-sachets',
    name: 'uricol plus 12 sachets',
    genericName: 'Colchicine & Khellin & Piperazine citrate',
    concentration: 'Sachets',
    price: 6,
    matchKeywords: ['uricol plus', 'يوريكول بلس', 'khellin', 'piperazine', 'colchicine', ...TAGS.antiGout, ...TAGS.analgesics],
    usage: 'فوار مساعد للنقرس/الأملاح حسب التشخيص والحالة.',
    timing: '٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كيس ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: لا تكرر كولشيسين من مصدر آخر دون إعادة تقييم.'],
  },

  // 27. colmediten 0.5mg 100 tabs
  {
    id: 'colmediten-colchicine-0-5mg-tabs-100',
    name: 'colmediten 0.5mg 100 tabs',
    genericName: 'Colchicine',
    concentration: '0.5mg',
    price: 190,
    matchKeywords: ['colmediten', 'كولميديتين', 'colchicine', ...TAGS.antiGout],
    usage: 'كولشيسين للنقرس حسب التشخيص.',
    timing: 'حسب الحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'حسب التشخيص والحالة (نوبة حادة/وقاية).',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ماكرولايد/آزول—لا تجمع دون إعادة تقييم.'],
  },

  // 28. donifoxate 40 mg 30 f.c. tablets
  {
    id: 'donifoxate-febuxostat-40mg-fc-tabs-30',
    name: 'donifoxate 40 mg 30 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 102,
    matchKeywords: ['donifoxate 40', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 29. staturic 40mg 30 f.c. tabs.
  {
    id: 'staturic-febuxostat-40mg-fc-tabs-30',
    name: 'staturic 40mg 30 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '40mg',
    price: 93,
    matchKeywords: ['staturic 40', 'ستاتوريك', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 30. unsiatem 80 mg 30 tabs.
  {
    id: 'unsiatem-febuxostat-80mg-tabs-30',
    name: 'unsiatem 80 mg 30 tabs.',
    genericName: 'Febuxostat',
    concentration: '80mg',
    price: 114,
    matchKeywords: ['unsiatem 80', 'انسياتم', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 31. andouristat 120 mg 20 f.c. tablets
  {
    id: 'andouristat-febuxostat-120mg-fc-tabs-20',
    name: 'andouristat 120 mg 20 f.c. tablets',
    genericName: 'Febuxostat',
    concentration: '120mg',
    price: 104,
    matchKeywords: ['andouristat 120', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة أعلى) حسب التشخيص والحالة.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },

  // 32. goutifade 120 mg 30 f.c. tabs.
  {
    id: 'goutifade-febuxostat-120mg-fc-tabs-30',
    name: 'goutifade 120 mg 30 f.c. tabs.',
    genericName: 'Febuxostat',
    concentration: '120mg',
    price: 159,
    matchKeywords: ['goutifade 120', 'febuxostat', ...TAGS.antiGout],
    usage: 'خفض حمض اليوريك (جرعة أعلى) حسب التشخيص والحالة.',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً حسب التشخيص والحالة.',
    warnings: [...commonAntiGoutWarnings, 'تداخلات: ممنوع مع أزاثيوبرين/ميركابتوبورين.'],
  },
];

export const ANTIGOUT: Medication[] = ANTIGOUT_RAW.map((medication) => ({
  ...medication,
  category: Category.ANTI_GOUT,
}));

