import { Medication, Category } from '../../types';

const TAGS = {
  muscleRelaxant: ['muscle relaxants', 'muscle relaxant', '#muscle relaxants', 'مرخي عضلات', 'باسط عضلات'],
  analgesics: ['analgesics', '#analgesics', 'مسكن', 'pain'],
  cns: ['cns', '#cns', 'CNS', 'نعاس', 'دوخة'],
  alpha2: ['alpha2 agonist', '#alpha2 agonist', 'alpha-2 agonist', 'alpha2'],
  antimuscarinic: ['antimuscarinic', '#antimuscarinic', 'anticholinergic', 'جفاف', 'زغللة'],
  urinationDifficulty: ['urination difficulty', '#urination difficulty', 'BPH', 'تضخم البروستاتا', 'صعوبة التبول'],
  alphaBlocker: ['alpha blocker', '#alpha blocker', 'alpha-blocker'],
};

const commonMuscleRelaxantWarnings = [
  'قد يسبب نعاس/دوخة: تجنب القيادة والكحول.',
  'الحمل/الرضاعة: يُستخدم فقط حسب التشخيص.',
  'يُؤخذ بعد الأكل إذا سبب ألم معدة.',
];

const SKELETAL_MUSCLE_RELAXANTS_RAW: Medication[] = [
  // 1. dimra 20 f.c.tab.
  {
    id: 'dimra-diclofenac-potassium-methocarbamol-fc-tabs-20',
    name: 'dimra 20 f.c.tab.',
    genericName: 'Diclofenac potassium & Methocarbamol',
    concentration: 'Tablets',
    price: 70,
    matchKeywords: ['dimra', 'ديمرا', 'diclofenac potassium', 'methocarbamol', ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مسكن ومضاد التهاب + باسط للعضلات لآلام الظهر/الشد العضلي.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً حسب الألم.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد بعد الأكل ٢–٣ مرات يومياً (لا تجمعه مع NSAIDs أخرى).',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات: ممنوع الجمع مع مضادات التهاب أخرى أو مميعات؛ إن لزم فبفاصل ومتابعة (خطر نزيف).',
      'تحذيرات: أوقف وأعد التقييم عند براز أسود/قيء دموي/ألم معدة شديد.',
    ],
  },

  // 2. mark fast 30 capsules
  {
    id: 'mark-fast-chlorzoxazone-ibuprofen-caps-30',
    name: 'mark fast 30 capsules',
    genericName: 'Chlorzoxazone & Ibuprofen',
    concentration: 'Capsules',
    price: 54,
    matchKeywords: ['mark fast', 'مارك فاست', 'chlorzoxazone', 'ibuprofen', ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مسكن + باسط للعضلات لآلام العضلات والظهر.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً حسب الحاجة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كبسولة بعد الأكل ٢–٣ مرات يومياً (لا تجمعه مع NSAIDs أخرى).',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات: NSAIDs الأخرى/الكورتيزون/مضادات التجلط تزيد خطر النزيف.',
      'تحذيرات: يُتجنب في قرحة/نزيف معدي أو أمراض كلى شديدة.',
    ],
  },

  // 3. methoquick 50/500 mg 30 tabs.
  {
    id: 'methoquick-diclofenac-potassium-methocarbamol-50-500-tabs-30',
    name: 'methoquick 50/500 mg 30 tabs.',
    genericName: 'Diclofenac potassium & Methocarbamol',
    concentration: '50/500mg',
    price: 99,
    matchKeywords: ['methoquick', 'ميثوكويك', 'diclofenac potassium', 'methocarbamol', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مسكن ومضاد التهاب + باسط للعضلات.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد بعد الأكل ٢–٣ مرات يومياً (حسب شدة الألم).',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات: لا تجمعه مع مضادات التهاب أخرى. راجع تداخلات المريض (الضغط/المدرات).',
    ],
  },

  // 4. multi-relax 10mg 20 f.c.tab
  {
    id: 'multi-relax-cyclobenzaprine-10mg-fc-tabs-20',
    name: 'multi-relax 10mg 20 f.c.tab',
    genericName: 'Cyclobenzaprine',
    concentration: '10mg',
    price: 42,
    matchKeywords: ['multi-relax 10', 'مالتي ريلاكس', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات الحادة وآلام الظهر (قد يسبب نعاس).',
    timing: 'عادةً ٢–٣ مرات يومياً أو حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (10mg) ٢–٣ مرات يومياً لمدة قصيرة حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات: يُتجنب مع الجلوكوما/احتباس البول الشديد. ممنوع مع مثبطات MAO خلال آخر ١٤ يوم.',
    ],
  },

  // 5. multi-relax 5mg 20 f.c.tab.
  {
    id: 'multi-relax-cyclobenzaprine-5mg-fc-tabs-20',
    name: 'multi-relax 5mg 20 f.c.tab.',
    genericName: 'Cyclobenzaprine',
    concentration: '5mg',
    price: 36,
    matchKeywords: ['multi-relax 5', 'مالتي ريلاكس 5', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات (جرعة أقل) للشد العضلي.',
    timing: '٢–٣ مرات يومياً أو حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (5mg) ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات: ممنوع مع مثبطات MAO خلال آخر ١٤ يوم.',
    ],
  },

  // 6. myofen 30 caps
  {
    id: 'myofen-chlorzoxazone-ibuprofen-caps-30',
    name: 'myofen 30 caps',
    genericName: 'Chlorzoxazone & Ibuprofen',
    concentration: 'Capsules',
    price: 54,
    matchKeywords: ['myofen', 'ميوفين', 'chlorzoxazone', 'ibuprofen', ...TAGS.muscleRelaxant],
    usage: 'مسكن + باسط عضلات.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً حسب الحاجة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كبسولة بعد الأكل ٢–٣ مرات يومياً.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات: يُتجنب في قرحة/نزيف معدي أو فشل كلوي شديد.',
    ],
  },

  // 7. sirdalud 2mg 20 tab
  {
    id: 'sirdalud-tizanidine-2mg-tabs-20',
    name: 'sirdalud 2mg 20 tab',
    genericName: 'Tizanidine',
    concentration: '2mg',
    price: 54,
    matchKeywords: ['sirdalud 2', 'سيردالود 2', 'tizanidine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant, ...TAGS.alpha2],
    usage: 'مرخي عضلات (Alpha-2 agonist) للتشنجات/الشد العضلي.',
    timing: 'مرتين–ثلاث مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'عادةً يبدأ بـ قرص (2mg) ٢–٣ مرات يومياً ثم تُعدل الجرعة حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات مهمة: لا يؤخذ مع سيبروفلوكساسين أو فلوفوكسامين (قد يسبب هبوط ضغط شديد).',
      'تحذيرات: يُستخدم بحذر في أمراض الكبد؛ قد يلزم متابعة وظائف الكبد.',
    ],
  },

  // 8. sirdalud 4mg 20 tab
  {
    id: 'sirdalud-tizanidine-4mg-tabs-20',
    name: 'sirdalud 4mg 20 tab',
    genericName: 'Tizanidine',
    concentration: '4mg',
    price: 70,
    matchKeywords: ['sirdalud 4', 'سيردالود 4', 'tizanidine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant, ...TAGS.alpha2],
    usage: 'مرخي عضلات (Alpha-2 agonist).',
    timing: 'حسب التشخيص والحالة (قد تكون جرعة أعلى).',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'حسب التشخيص والحالة (قد يبدأ بـ 2mg ثم يزيد تدريجياً).',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات مهمة: سيبروفلوكساسين/فلوفوكسامين ممنوع.',
      'تحذيرات: خطر هبوط ضغط ونعاس شديد مع الجرعات الأعلى.',
    ],
  },

  // 9. movxir 500/50mg 20 f.c. tabs.
  {
    id: 'movxir-diclofenac-potassium-methocarbamol-500-50-fc-tabs-20',
    name: 'movxir 500/50mg 20 f.c. tabs.',
    genericName: 'Diclofenac potassium & Methocarbamol',
    concentration: '500/50mg',
    price: 78,
    matchKeywords: ['movxir', 'موفكسير', 'diclofenac potassium', 'methocarbamol', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مسكن + باسط للعضلات.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'قرص بعد الأكل ٢–٣ مرات يومياً.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 10. flexilax 30 f.c.tab
  {
    id: 'flexilax-diclofenac-potassium-methocarbamol-fc-tabs-30',
    name: 'flexilax 30 f.c.tab',
    genericName: 'Diclofenac potassium & Methocarbamol',
    concentration: 'Tablets',
    price: 84,
    matchKeywords: ['flexilax', 'فليكسيلاكس', 'diclofenac potassium', 'methocarbamol', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مسكن + باسط للعضلات.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'قرص بعد الأكل ٢–٣ مرات يومياً.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 11. moveasy 5 mg 30 f.c.tabs.
  {
    id: 'moveasy-cyclobenzaprine-5mg-fc-tabs-30',
    name: 'moveasy 5 mg 30 f.c.tabs.',
    genericName: 'Cyclobenzaprine',
    concentration: '5mg',
    price: 60,
    matchKeywords: ['moveasy 5 30', 'موف ايزي', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات الحادة.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (5mg) ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: ممنوع مع مثبطات MAO خلال آخر ١٤ يوم.'],
  },

  // 12. relaxon 30 caps.
  {
    id: 'relaxon-chlorzoxazone-paracetamol-caps-30',
    name: 'relaxon 30 caps.',
    genericName: 'Chlorzoxazone & Paracetamol',
    concentration: 'Capsules',
    price: 69,
    matchKeywords: ['relaxon', 'ريلاكسون', 'chlorzoxazone', 'paracetamol', ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات + مسكن (أخف على المعدة من NSAIDs).',
    timing: '٢–٣ مرات يومياً حسب الحاجة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كبسولة بعد الأكل ٢–٣ مرات يومياً.',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: لا تتجاوز الجرعة اليومية الآمنة من الباراسيتامول.'],
  },

  // 13. moveasy 5 mg 20 f.c.tabs.
  {
    id: 'moveasy-cyclobenzaprine-5mg-fc-tabs-20',
    name: 'moveasy 5 mg 20 f.c.tabs.',
    genericName: 'Cyclobenzaprine',
    concentration: '5mg',
    price: 27,
    matchKeywords: ['moveasy 5 20', 'موف ايزي 20', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات الحادة.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (5mg) ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 14. baclofen 10 mg 20 tabs. b.p.2011
  {
    id: 'baclofen-10mg-tabs-20-bp2011',
    name: 'baclofen 10 mg 20 tabs. b.p.2011',
    genericName: 'Baclofen',
    concentration: '10mg',
    price: 30,
    matchKeywords: ['baclofen 10', 'باكلوفين', 'spasticity', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتشنج/التقلصات (خاصة مشاكل الأعصاب) حسب التشخيص.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'يبدأ عادةً بجرعة صغيرة ثم تُزاد تدريجياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: الإيقاف المفاجئ قد يسبب أعراض انسحاب/تشنجات.'],
  },

  // 15. dantrelax 25mg 30 caps.
  {
    id: 'dantrelax-dantrolene-sodium-25mg-caps-30',
    name: 'dantrelax 25mg 30 caps.',
    genericName: 'Dantrolene sodium',
    concentration: '25mg',
    price: 147,
    matchKeywords: ['dantrelax 25', 'دانترلاكس', 'dantrolene', ...TAGS.muscleRelaxant, ...TAGS.analgesics],
    usage: 'مرخي عضلات للتشنج الشديد حسب التشخيص.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'الجرعة تُحدد حسب البروتوكول وتُزاد تدريجياً.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات خاصة: قد يسبب سمية كبدية—قد يلزم متابعة وظائف الكبد عند اللزوم.',
    ],
  },

  // 16. dantrelax compound 30 caps.
  {
    id: 'dantrelax-compound-dantrolene-paracetamol-caps-30',
    name: 'dantrelax compound 30 caps.',
    genericName: 'Dantrolene sodium & Paracetamol',
    concentration: 'Capsules',
    price: 153,
    matchKeywords: ['dantrelax compound', 'دانترلاكس كومباوند', 'dantrolene', 'paracetamol', ...TAGS.muscleRelaxant, ...TAGS.analgesics],
    usage: 'مرخي عضلات + مسكن حسب التشخيص.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'الجرعة تُحدد حسب البروتوكول.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات: سمية كبدية محتملة (دانترولين/باراسيتامول)—لا تتجاوز الجرعات.',
    ],
  },

  // 17. flexofan 20 caps
  {
    id: 'flexofan-chlorzoxazone-ketoprofen-caps-20',
    name: 'flexofan 20 caps',
    genericName: 'Chlorzoxazone & Ketoprofen',
    concentration: 'Capsules',
    price: 56,
    matchKeywords: ['flexofan', 'فليكسوفان', 'chlorzoxazone', 'ketoprofen', ...TAGS.muscleRelaxant, ...TAGS.analgesics],
    usage: 'مسكن + باسط للعضلات.',
    timing: 'بعد الأكل ٢–٣ مرات يومياً حسب الحاجة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كبسولة بعد الأكل ٢–٣ مرات يومياً (لا تجمعه مع NSAIDs أخرى).',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: يُتجنب في قرحة/نزيف معدي أو فشل كلوي شديد.'],
  },

  // 18. moveasy 10 mg 30 f.c.tabs.
  {
    id: 'moveasy-cyclobenzaprine-hcl-10mg-fc-tabs-30',
    name: 'moveasy 10 mg 30 f.c.tabs.',
    genericName: 'Cyclobenzaprine HCl',
    concentration: '10mg',
    price: 69,
    matchKeywords: ['moveasy 10 30', 'موف ايزي 10', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات الحادة.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (10mg) ٢–٣ مرات يومياً لمدة قصيرة حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: ممنوع مع مثبطات MAO خلال آخر ١٤ يوم.'],
  },

  // 19. mylobac 25mg 20 tabs.
  {
    id: 'mylobac-baclofen-25mg-tabs-20',
    name: 'mylobac 25mg 20 tabs.',
    genericName: 'Baclofen',
    concentration: '25mg',
    price: 34,
    matchKeywords: ['mylobac 25', 'ميلوباك 25', 'baclofen', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتشنج/التقلصات حسب التشخيص.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'الجرعة تُحدد حسب البروتوكول (عادةً تبدأ تدريجياً).',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: الإيقاف المفاجئ ممنوع.'],
  },

  // 20. norgesic 20 tab.
  {
    id: 'norgesic-orphenadrine-paracetamol-tabs-20',
    name: 'norgesic 20 tab.',
    genericName: 'Orphenadrine & Paracetamol',
    concentration: 'Tablets',
    price: 38,
    matchKeywords: ['norgesic', 'نورجيسك', 'orphenadrine', 'paracetamol', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant, ...TAGS.antimuscarinic],
    usage: 'مرخي عضلات + مسكن (له تأثير مضاد كولين).',
    timing: 'بعد الأكل ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص بعد الأكل ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات: يُتجنب في الجلوكوما واحتباس البول الشديد (مضاد كولين).',
    ],
  },

  // 21. cycloflex 5 mg 20 f.c. tablets
  {
    id: 'cycloflex-cyclobenzaprine-hcl-5mg-fc-tabs-20',
    name: 'cycloflex 5 mg 20 f.c. tablets',
    genericName: 'Cyclobenzaprine HCl',
    concentration: '5mg',
    price: 40,
    matchKeywords: ['cycloflex 5 20', 'سيكلوفليكس', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (5mg) ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 22. cycloflex 5 mg 30 f.c. tablets
  {
    id: 'cycloflex-cyclobenzaprine-hcl-5mg-fc-tabs-30',
    name: 'cycloflex 5 mg 30 f.c. tablets',
    genericName: 'Cyclobenzaprine HCl',
    concentration: '5mg',
    price: 69,
    matchKeywords: ['cycloflex 5 30', 'سيكلوفليكس 30', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (5mg) ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 23. moveasy 10 mg 20 f.c.tabs.
  {
    id: 'moveasy-cyclobenzaprine-10mg-fc-tabs-20',
    name: 'moveasy 10 mg 20 f.c.tabs.',
    genericName: 'Cyclobenzaprine',
    concentration: '10mg',
    price: 46,
    matchKeywords: ['moveasy 10 20', 'موف ايزي 10 20', 'cyclobenzaprine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتقلصات الحادة.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (10mg) ٢–٣ مرات يومياً لمدة قصيرة حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 24. norflex 100mg 20 tab.
  {
    id: 'norflex-orphenadrine-citrate-100mg-tabs-20',
    name: 'norflex 100mg 20 tab.',
    genericName: 'Orphenadrine citrate',
    concentration: '100mg',
    price: 26,
    matchKeywords: ['norflex', 'نورفليكس', 'orphenadrine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant, ...TAGS.antimuscarinic],
    usage: 'مرخي عضلات (مضاد كولين) للشد العضلي.',
    timing: 'مرتين يومياً أو حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 180,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد (100mg) مرتين يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تحذيرات: يُتجنب في الجلوكوما واحتباس البول الشديد.',
    ],
  },

  // 25. tamsulin plus 6/0.4mg 20 mr tabs
  {
    id: 'tamsulin-plus-tamsulosin-solifenacin-mr-tabs-20',
    name: 'tamsulin plus 6/0.4mg 20 mr tabs',
    genericName: 'Tamsulosin & Solifenacin',
    concentration: '6/0.4mg',
    price: 148,
    matchKeywords: ['tamsulin plus', 'تامسولين بلس', 'tamsulosin', 'solifenacin', ...TAGS.urinationDifficulty, ...TAGS.alphaBlocker, ...TAGS.antimuscarinic],
    usage: 'لتخفيف أعراض صعوبة التبول/فرط نشاط المثانة (حسب التشخيص).',
    timing: 'مرة يومياً بعد الأكل.',
    category: Category.URINARY_CARE,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص/كبسولة واحدة مرة يومياً بعد الأكل وفي نفس الميعاد.',
    warnings: [
      'الحمل/الرضاعة: غير مخصص عادةً؛ عند الضرورة بأقل جرعة وأقصر مدة.',
      'تحذيرات: تجنب في احتباس البول الكامل/الجلوكوما ضيقة الزاوية غير المعالجة.',
      'تداخلات: راجع تداخلات المريض (الضغط/أدوية البروستاتا).',
    ],
  },

  // 26. winterest cream 50 gm
  {
    id: 'winterest-cream-methyl-salicylate-magnesium-menthol-b6-e-50g',
    name: 'winterest cream 50 gm',
    genericName: 'Methyl salicylate & Magnesium & Menthol & Vitamin B6 & Vitamin E',
    concentration: 'Cream',
    price: 100,
    matchKeywords: ['winterest', 'وينتريست', 'methyl salicylate', 'menthol', 'cream', ...TAGS.muscleRelaxant, ...TAGS.analgesics],
    usage: 'كريم موضعي مسكن لآلام العضلات/المفاصل.',
    timing: '٢–٣ مرات يومياً عند اللزوم.',
    category: Category.MUSCULOSKELETAL,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: () => 'تدليك كمية مناسبة على المكان ٢–٣ مرات يومياً.',
    warnings: [
      'الحمل (خصوصاً الثلث الأخير): تجنب استخدام ساليسيلات على مساحات كبيرة إلا باستشارة.',
      'تداخلات: لا تستخدمه مع مصادر حرارة/ضمادات محكمة على نفس المكان.',
      'تحذيرات: أوقفه عند تهيج شديد/طفح.',
    ],
  },

  // 27. relax 30 caps.
  {
    id: 'relax-chlorzoxazone-paracetamol-caps-30',
    name: 'relax 30 caps.',
    genericName: 'Chlorzoxazone & Paracetamol',
    concentration: 'Capsules',
    price: 63,
    matchKeywords: ['relax 30', 'ريلاكس', 'chlorzoxazone', 'paracetamol', ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات + مسكن.',
    timing: '٢–٣ مرات يومياً حسب الحاجة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كبسولة بعد الأكل ٢–٣ مرات يومياً.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 28. prinorelax 30 mg 20 ext. rel. caps.
  {
    id: 'prinorelax-cyclobenzaprine-30mg-extended-release-caps-20',
    name: 'prinorelax 30 mg 20 ext. rel. caps.',
    genericName: 'Cyclobenzaprine',
    concentration: '30mg',
    price: 79,
    matchKeywords: ['prinorelax 30 20', 'برينوريلاكس', 'cyclobenzaprine', 'extended release', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات ممتد المفعول (حسب التشخيص).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'كبسولة واحدة مرة يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: ممنوع مع مثبطات MAO خلال آخر ١٤ يوم.'],
  },

  // 29. caredalud s.r. 6mg 30 f.c. tab.
  {
    id: 'caredalud-sr-tizanidine-6mg-fc-tabs-30',
    name: 'caredalud s.r. 6mg 30 f.c. tab.',
    genericName: 'Tizanidine',
    concentration: '6mg',
    price: 60,
    matchKeywords: ['caredalud', 'كيردالود', 'tizanidine', 'sr', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant, ...TAGS.alpha2],
    usage: 'مرخي عضلات ممتد المفعول (Alpha-2 agonist) حسب التشخيص.',
    timing: 'مرة يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Sustained-release Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'قرص واحد يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات مهمة: سيبروفلوكساسين/فلوفوكسامين ممنوع.',
      'تحذيرات: متابعة كبد/ضغط حسب التشخيص والحالة.',
    ],
  },

  // 30. methorelax 30 tab
  {
    id: 'methorelax-methocarbamol-paracetamol-tabs-30',
    name: 'methorelax 30 tab',
    genericName: 'Methocarbamol & Paracetamol',
    concentration: 'Tablets',
    price: 81,
    matchKeywords: ['methorelax', 'ميثوريلاكس', 'methocarbamol', 'paracetamol', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات + مسكن.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'قرص بعد الأكل ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 31. mylobac 10mg 20 tab.
  {
    id: 'mylobac-baclofen-10mg-tabs-20',
    name: 'mylobac 10mg 20 tab.',
    genericName: 'Baclofen',
    concentration: '10mg',
    price: 28,
    matchKeywords: ['mylobac 10', 'ميلوباك 10', 'baclofen', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات للتشنج/التقلصات حسب التشخيص.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'الجرعة تُحدد حسب البروتوكول (تدرج).',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: الإيقاف المفاجئ ممنوع.'],
  },

  // 32. s.m.r 2 mg 20 tab.
  {
    id: 'smr-tizanidine-2mg-tabs-20',
    name: 's.m.r 2 mg 20 tab.',
    genericName: 'Tizanidine',
    concentration: '2mg',
    price: 38,
    matchKeywords: ['s.m.r', 'smr', 'تيزانيدين', 'tizanidine', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant, ...TAGS.alpha2],
    usage: 'مرخي عضلات (Alpha-2 agonist).',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'قرص (2mg) ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [
      ...commonMuscleRelaxantWarnings,
      'تداخلات مهمة: سيبروفلوكساسين/فلوفوكسامين ممنوع.',
    ],
  },

  // 33. spinobac 5mg/5ml syrup 300ml
  {
    id: 'spinobac-baclofen-5mg-5ml-syrup-300ml',
    name: 'spinobac 5mg/5ml syrup 300ml',
    genericName: 'Baclofen',
    concentration: '5mg/5ml',
    price: 73,
    matchKeywords: ['spinobac 300', 'سبينوباكلوفين', 'baclofen syrup', ...TAGS.cns, ...TAGS.muscleRelaxant],
    usage: 'شراب مرخي عضلات للتشنج العصبي حسب التشخيص.',
    timing: 'عادةً ٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Syrup',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'تُحدد الجرعة حسب التشخيص (تدرج). لا توقف فجأة.',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: الإيقاف المفاجئ ممنوع.'],
  },

  // 34. prinorelax 30 mg 10 ext. release caps.
  {
    id: 'prinorelax-cyclobenzaprine-30mg-extended-release-caps-10',
    name: 'prinorelax 30 mg 10 ext. release caps.',
    genericName: 'Cyclobenzaprine',
    concentration: '30mg',
    price: 39.5,
    matchKeywords: ['prinorelax 30 10', 'برينوريلاكس 10', 'cyclobenzaprine', 'extended release', ...TAGS.cns, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات ممتد المفعول (حسب التشخيص).',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'كبسولة واحدة مرة يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 35. relatrolene 25 mg 20 caps.
  {
    id: 'relatrolene-dantrolene-sodium-25mg-caps-20',
    name: 'relatrolene 25 mg 20 caps.',
    genericName: 'Dantrolene sodium',
    concentration: '25mg',
    price: 98,
    matchKeywords: ['relatrolene', 'ريلاترولين', 'dantrolene', ...TAGS.muscleRelaxant, ...TAGS.analgesics],
    usage: 'مرخي عضلات للتشنج الشديد حسب التشخيص.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: () => 'الجرعة تُحدد حسب البروتوكول (تدرج).',
    warnings: [...commonMuscleRelaxantWarnings, 'تحذيرات: سمية كبدية محتملة—متابعة وظائف الكبد عند اللزوم.'],
  },

  // 36. relax 20 caps
  {
    id: 'relax-chlorzoxazone-paracetamol-caps-20',
    name: 'relax 20 caps',
    genericName: 'Chlorzoxazone & Paracetamol',
    concentration: 'Capsules',
    price: 42,
    matchKeywords: ['relax 20', 'ريلاكس 20', 'chlorzoxazone', 'paracetamol', ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات + مسكن.',
    timing: '٢–٣ مرات يومياً حسب الحاجة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'كبسولة بعد الأكل ٢–٣ مرات يومياً.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 37. prinorelax 15 mg 30 ext. rel. caps.
  {
    id: 'prinorelax-cyclobenzaprine-hcl-15mg-extended-release-caps-30',
    name: 'prinorelax 15 mg 30 ext. rel. caps.',
    genericName: 'Cyclobenzaprine HCl',
    concentration: '15mg',
    price: 103,
    matchKeywords: ['prinorelax 15 30', 'برينوريلاكس 15', 'cyclobenzaprine', 'extended release', ...TAGS.cns, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات ممتد المفعول (حسب التشخيص).',
    timing: 'مرة يومياً.',
    category: Category.MUSCULOSKELETAL,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'كبسولة واحدة مرة يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 38. spinobac 5mg/5ml syrup 120ml
  {
    id: 'spinobac-baclofen-5mg-5ml-syrup-120ml',
    name: 'spinobac 5mg/5ml syrup 120ml',
    genericName: 'Baclofen',
    concentration: '5mg/5ml',
    price: 39,
    matchKeywords: ['spinobac 120', 'سبينوباكلوفين 120', 'baclofen syrup', ...TAGS.cns, ...TAGS.muscleRelaxant],
    usage: 'شراب مرخي عضلات للتشنج العصبي حسب التشخيص.',
    timing: 'عادةً ٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'Syrup',
    minAgeMonths: 60,
    maxAgeMonths: 1200,
    minWeight: 15,
    maxWeight: 250,
    calculationRule: () => 'تُحدد الجرعة حسب التشخيص (تدرج). لا توقف فجأة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },

  // 39. flexpro extra 20 f.c.tabs.
  {
    id: 'flexpro-extra-methocarbamol-paracetamol-fc-tabs-20',
    name: 'flexpro extra 20 f.c.tabs.',
    genericName: 'Methocarbamol & Paracetamol',
    concentration: 'F.C. Tablets',
    price: 46,
    matchKeywords: ['flexpro extra', 'فليكس برو اكسترا', 'methocarbamol', 'paracetamol', ...TAGS.cns, ...TAGS.analgesics, ...TAGS.muscleRelaxant],
    usage: 'مرخي عضلات + مسكن.',
    timing: '٢–٣ مرات يومياً حسب التشخيص والحالة.',
    category: Category.MUSCULOSKELETAL,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: () => 'قرص بعد الأكل ٢–٣ مرات يومياً حسب التشخيص والحالة.',
    warnings: [...commonMuscleRelaxantWarnings],
  },
];

export const SKELETAL_MUSCLE_RELAXANTS: Medication[] = SKELETAL_MUSCLE_RELAXANTS_RAW.map((medication) => ({
  ...medication,
  category: Category.MUSCLE_RELAXANTS,
}));

