import { Medication, Category } from '../../types';

export const VACCINES_GROUP: Medication[] = [
	// 1) prevenar 13 - prefilled syringe for i.m. inj.
	{
		id: 'prevenar-13-prefilled-syringe-im',
		name: 'prevenar 13 - prefilled syringe for i.m. inj.',
		genericName: 'pneumococcal conjugate vaccine (13-valent)',
		concentration: 'prefilled syringe (0.5ml) for i.m. injection',
		price: 1125,
		matchKeywords: ['prevenar', 'prevenar 13', 'pneumococcal vaccine', 'لقاح المكورات الرئوية', 'بريفينار', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'رئوية'],
		usage: 'لقاح ضد المكورات الرئوية للمساعدة في الوقاية من عدوى المكورات الرئوية حسب جدول التطعيمات.',
		timing: 'يُعطى بجرعات حسب العمر وبرنامج التطعيم.',
		category: Category.VACCINES,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: () => 'الجرعة المعتادة: 0.5 مل حقن عضلي، وعدد الجرعات يعتمد على العمر وبرنامج التطعيم.',
		warnings: ['لا يُستخدم عند وجود حساسية شديدة سابقة للقاح أو لأي مكوّن.', 'يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.'],
	},

	// 2) rotarix oral vaccine 1.5 ml
	{
		id: 'rotarix-oral-vaccine-1-5ml',
		name: 'rotarix oral vaccine 1.5 ml',
		genericName: 'rotavirus vaccine (live attenuated)',
		concentration: '1.5ml oral vaccine',
		price: 646,
		matchKeywords: ['rotarix', 'rota vaccine', 'rotavirus', 'لقاح الروتا', 'روتاريكس', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'إسهال'],
		usage: 'لقاح الروتا للمساعدة في الوقاية من نزلات الإسهال الشديدة بسبب فيروس الروتا عند الرضع حسب جدول التطعيمات.',
		timing: 'يُعطى على جرعات حسب العمر في الشهور.',
		category: Category.VACCINES,
		form: 'Oral Suspension',
		minAgeMonths: 2,
		maxAgeMonths: 8,
		minWeight: 3,
		maxWeight: 20,
		calculationRule: () => 'الجرعة المعتادة: 1.5 مل بالفم لكل جرعة، وعدد الجرعات يعتمد على برنامج التطعيم.',
		warnings: ['يُعطى ضمن العمر الموصى به لجرعات الروتا.', 'يُؤجل التطعيم عند وجود قيء شديد/إسهال شديد وقت الجرعة.'],
	},

	// 3) havrix junior 720 i.u./0.5ml prefilled syringe
	{
		id: 'havrix-junior-720-0-5ml-prefilled-syringe',
		name: 'havrix junior 720 i.u./0.5ml prefilled syringe',
		genericName: 'hepatitis A vaccine (inactivated)',
		concentration: '720 IU/0.5ml prefilled syringe',
		price: 578,
		matchKeywords: ['havrix', 'havrix junior', 'hepatitis a vaccine', 'لقاح التهاب الكبد A', 'هافريكس', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'كبد وبائي'],
		usage: 'لقاح التهاب الكبد الوبائي A للمساعدة في الوقاية من العدوى حسب برنامج التطعيم/السفر.',
		timing: 'جرعات حسب العمر، مع جرعة تكميلية بعد فترة.',
		category: Category.VACCINES,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 12,
		maxAgeMonths: 216,
		minWeight: 8,
		maxWeight: 120,
		calculationRule: () => 'الجرعة المعتادة: 0.5 مل حقن عضلي. جرعة تكميلية لاحقاً حسب برنامج التطعيم.',
		warnings: ['لا يُستخدم عند وجود حساسية شديدة سابقة للقاح.', 'يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.'],
	},

	// 4) influvac tetra 1 pref.syringe susp. for in...
	{
		id: 'influvac-tetra-0-5ml-prefilled-syringe',
		name: 'influvac tetra 1 pref.syringe susp. for in...',
		genericName: 'influenza vaccine (quadrivalent)',
		concentration: 'prefilled syringe (0.5ml) suspension for injection',
		price: 322,
		matchKeywords: ['influvac tetra', 'influvac', 'influenza vaccine', 'flu shot', 'لقاح الانفلونزا', 'انفلوفاك', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'انفلونزا'],
		usage: 'لقاح الإنفلونزا الرباعي للمساعدة في الوقاية من الإنفلونزا الموسمية.',
		timing: 'عادة مرة سنوياً (يتحدد الموعد حسب الموسم والعمر).',
		category: Category.VACCINES,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 6,
		maxWeight: 250,
		calculationRule: () => 'الجرعة المعتادة: 0.5 مل حقن عضلي. قد يحتاج الأطفال الأصغر لجرعات وفق برنامج التطعيم.',
		warnings: ['يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.', 'حساسية شديدة سابقة لأي مكوّن تمنع إعادة التطعيم.'],
	},

	// 5) synflorix prefilled syringe for i.m. inj. 0.5 ml
	{
		id: 'synflorix-prefilled-syringe-im-0-5ml',
		name: 'synflorix prefilled syringe for i.m. inj. 0.5 ml',
		genericName: 'pneumococcal conjugate vaccine (10-valent)',
		concentration: 'prefilled syringe (0.5ml) for i.m. injection',
		price: 692,
		matchKeywords: ['synflorix', 'pneumococcal vaccine', 'لقاح المكورات الرئوية', 'سينفلوريكس', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'رئوية'],
		usage: 'لقاح ضد المكورات الرئوية للمساعدة في الوقاية من عدوى المكورات الرئوية حسب جدول التطعيمات.',
		timing: 'يُعطى بجرعات حسب العمر وبرنامج التطعيم.',
		category: Category.VACCINES,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: () => 'الجرعة المعتادة: 0.5 مل حقن عضلي، وعدد الجرعات يعتمد على العمر وبرنامج التطعيم.',
		warnings: ['لا يُستخدم عند وجود حساسية شديدة سابقة للقاح أو لأي مكوّن.', 'يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.'],
	},

	// 6) nimenrix vial powder for i.m.
	{
		id: 'nimenrix-vial-powder-im',
		name: 'nimenrix vial powder for i.m.',
		genericName: 'meningococcal conjugate vaccine (A,C,W,Y)',
		concentration: 'vial (powder) for i.m. injection',
		price: 1275,
		matchKeywords: ['nimenrix', 'meningococcal vaccine', 'meningitis vaccine', 'لقاح السحايا', 'نيمنريكس', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'سحائي', 'حمى شوكية'],
		usage: 'لقاح السحايا الرباعي للمساعدة في الوقاية من عدوى المكورات السحائية (A,C,W,Y) حسب برنامج التطعيم/السفر.',
		timing: 'جرعات حسب العمر/البرنامج.',
		category: Category.VACCINES,
		form: 'Vial',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: () => 'الجرعة تُحضّر وتُعطى بالعضل وفق تعليمات التحضير والبرنامج المناسب للعمر.',
		warnings: ['لا يُستخدم عند وجود حساسية شديدة سابقة للقاح.', 'يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.'],
	},

	// 7) hiberix vaccine 1mg 1ml
	{
		id: 'hiberix-vaccine-1mg-1ml',
		name: 'hiberix vaccine 1mg 1ml',
		genericName: 'hib conjugate vaccine (Haemophilus influenzae type b)',
		concentration: '1mg/1ml',
		price: 50,
		matchKeywords: ['hiberix', 'hib vaccine', 'haemophilus influenzae b', 'لقاح الهيموفيلس', 'هايبركس', '#vaccine', 'تطعيم', 'vaccine', 'لقاح'],
		usage: 'لقاح Hib للمساعدة في الوقاية من عدوى هيموفيلس إنفلونزا النوع b عند الرضع/الأطفال حسب جدول التطعيمات.',
		timing: 'جرعات حسب العمر وبرنامج التطعيم.',
		category: Category.VACCINES,
		form: 'Vial',
		minAgeMonths: 2,
		maxAgeMonths: 216,
		minWeight: 3,
		maxWeight: 120,
		calculationRule: () => 'الجرعة تُحضّر وتُعطى بالعضل وفق البرنامج المناسب للعمر.',
		warnings: ['يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.', 'حساسية شديدة سابقة للقاح تمنع إعادة التطعيم.'],
	},

	// 8) hiberix vaccine vial and prefilled syringe
	{
		id: 'hiberix-vial-and-prefilled-syringe',
		name: 'hiberix vaccine vial and prefilled syringe',
		genericName: 'hib conjugate vaccine (Haemophilus influenzae type b)',
		concentration: 'vial + prefilled syringe (for i.m. injection)',
		price: 186,
		matchKeywords: ['hiberix vial', 'hiberix syringe', 'hib vaccine', 'لقاح hib', 'هايبركس', '#vaccine', 'تطعيم', 'vaccine', 'لقاح'],
		usage: 'لقاح Hib للمساعدة في الوقاية من عدوى هيموفيلس إنفلونزا النوع b حسب جدول التطعيمات.',
		timing: 'جرعات حسب العمر وبرنامج التطعيم.',
		category: Category.VACCINES,
		form: 'Vial',
		minAgeMonths: 2,
		maxAgeMonths: 216,
		minWeight: 3,
		maxWeight: 120,
		calculationRule: () => 'الجرعة تُحضّر وتُعطى بالعضل وفق البرنامج المناسب للعمر.',
		warnings: ['يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.', 'حساسية شديدة سابقة للقاح تمنع إعادة التطعيم.'],
	},

	// 9) vaxigrip tetra 15mcg/0.5ml prefilled syringe
	{
		id: 'vaxigrip-tetra-15mcg-0-5ml-prefilled-syringe',
		name: 'vaxigrip tetra 15mcg/0.5ml prefilled syringe',
		genericName: 'influenza vaccine (quadrivalent)',
		concentration: '15mcg/0.5ml prefilled syringe',
		price: 370,
		matchKeywords: ['vaxigrip tetra', 'vaxigrip', 'influenza vaccine', 'لقاح الانفلونزا', 'فاكسيجريب', '#vaccine', 'تطعيم', 'vaccine', 'لقاح', 'انفلونزا'],
		usage: 'لقاح الإنفلونزا الرباعي للمساعدة في الوقاية من الإنفلونزا الموسمية.',
		timing: 'عادة مرة سنوياً (يتحدد الموعد حسب الموسم والعمر).',
		category: Category.VACCINES,
		form: 'Ampoule (IV/IM)',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 6,
		maxWeight: 250,
		calculationRule: () => 'الجرعة المعتادة: 0.5 مل حقن عضلي. قد يحتاج الأطفال الأصغر لجرعات وفق برنامج التطعيم.',
		warnings: ['يُؤجل التطعيم عند وجود حرارة مرتفعة شديدة.', 'حساسية شديدة سابقة لأي مكوّن تمنع إعادة التطعيم.'],
	},
];

