
import { Medication, Category } from '../../types';

const alfacalcidolDropsDose = () => '٢–٤ نقط (≈ ٠.٢٥–١ ميكروجرام) عن طريق الفم مرة يومياً مع أو بعد الأكل (مزمن) – تُضبط حسب Ca/P/PTH';

const alfacalcidolCapsDose = () => '١ كبسولة ١ ميكروجرام عن طريق الفم مرة يومياً مع أو بعد الأكل (مزمن) – تُضبط حسب Ca/P/PTH';

const alfacalcidolAmpDose = () => 'حقنة وريدية (IV) بعد جلسة الغسيل ٢–٣ مرات أسبوعياً (مزمن) – الجرعة حسب Ca/P/PTH';

const cinacalcetDose = () => '١ قرص ٣٠ مجم مع الأكل مرة يومياً (مزمن) – يُزاد تدريجياً كل ٢–٤ أسابيع حسب PTH/الكالسيوم';

const cinacalcet60Dose = () => '١ قرص ٦٠ مجم مع الأكل مرة يومياً (مزمن) – حسب PTH/الكالسيوم';

export const HYPERPARATHYROIDISM_MEDICATIONS: Medication[] = [
	{
		id: 'alfacalcidol-2mcg-ml-drops-10ml',
		name: 'alfacalcidol 2mcg/ml oral dps. 10 ml',
		genericName: 'alfacalcidol',
		concentration: '2 mcg/ml (10 ml)',
		price: 86,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'drops', 'oral drops', 'فيتامين د', 'الفاكالسيدول', 'كالسيوم', 'عظام', 'غدة جار درقية', 'parathyroid', 'هشاشة', 'كساح', 'rickets'],
		usage: 'نظير فيتامين د لعلاج اضطرابات الكالسيوم/العظام (حسب التشخيص والتحاليل).',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => alfacalcidolDropsDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ يلزم متابعة Ca/P/PTH.', 'تجنب أخذ مكملات كالسيوم/فيتامين د إضافية دون إعادة تقييم.'],
	},
	{
		id: 'alfacalcidol-2mcg-ml-drops-20ml',
		name: 'alfacalcidol 2mcg/ml oral dps. 20 ml',
		genericName: 'alfacalcidol',
		concentration: '2 mcg/ml (20 ml)',
		price: 156,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'drops', '20ml', 'فيتامين د', 'الفاكالسيدول', 'كالسيوم', 'عظام', 'غدة جار درقية', 'parathyroid'],
		usage: 'نظير فيتامين د لعلاج اضطرابات الكالسيوم/العظام (حسب التشخيص والتحاليل).',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => alfacalcidolDropsDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ يلزم متابعة Ca/P/PTH.'],
	},
	{
		id: 'bone-care-1mcg-30-caps',
		name: 'bone care 1mcg 30 caps.',
		genericName: 'alfacalcidol',
		concentration: '1 mcg (30 capsules)',
		price: 132,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'bone care', 'كبسولات', 'دعم العظام', 'كالسيوم', 'عظام', 'غدة جار درقية', 'parathyroid', 'فيتامين د', 'الفاكالسيدول'],
		usage: 'ألفاكالسيدول 1mcg لعلاج اضطرابات الكالسيوم/العظام حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Capsule',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 300,
		calculationRule: (_) => alfacalcidolCapsDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ متابعة التحاليل ضرورية.'],
	},
	{
		id: 'cinacalcet-60mg-10-fc-tabs',
		name: 'cinacalcet 60 mg 10 f.c. tab.',
		genericName: 'cinacalcet',
		concentration: '60 mg (10 F.C. tablets)',
		price: 433,
		matchKeywords: ['#calcimimetic', 'cinacalcet', 'سيناكالسيت', '60mg', 'secondary hyperparathyroidism', 'PTH', 'غدة جار درقية', 'parathyroid', 'فرط جار الدرقية', 'كالسيوم'],
		usage: 'Calcimimetic لتقليل PTH في فرط جار الدرقية الثانوي/أمراض الكلى حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Film-coated Tablet',
		minAgeMonths: 216, // 18y+ (cinacalcet)
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 300,
		calculationRule: (_) => cinacalcet60Dose(),
		warnings: ['راقب الكالسيوم: قد يسبب انخفاضه.', 'لا تبدأ/توقف دون إعادة تقييم.'],
	},
	{
		id: 'cinacalcet-30mg-10-fc-tabs',
		name: 'cinacalcet 30mg 10 f.c. tab.',
		genericName: 'cinacalcet',
		concentration: '30 mg (10 F.C. tablets)',
		price: 277,
		matchKeywords: ['#calcimimetic', 'cinacalcet', 'سيناكالسيت', '30mg', 'PTH', 'غدة جار درقية', 'parathyroid', 'فرط جار الدرقية', 'كالسيوم'],
		usage: 'Calcimimetic لتقليل PTH في فرط جار الدرقية حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Film-coated Tablet',
		minAgeMonths: 216, // 18y+ (cinacalcet)
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 300,
		calculationRule: (_) => cinacalcetDose(),
		warnings: ['راقب الكالسيوم لتجنب hypocalcemia.'],
	},
	{
		id: 'one-alpha-2mcg-ml-10-amps',
		name: 'one alpha 2mcg/ml 10 amps.',
		genericName: 'alfacalcidol',
		concentration: '2 mcg/ml (10 ampoules)',
		price: 236,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'one alpha', 'وان ألفا', 'ampoules', 'حقن', 'كالسيوم', 'عظام', 'فيتامين د', 'الفاكالسيدول'],
		usage: 'ألفاكالسيدول (أمبولات) لعلاج اضطرابات الكالسيوم/العظام حسب التشخيص والتحاليل.',
		timing: '٢–٣ مرات أسبوعياً IV – مزمن',
		category: Category.DIABETES,
		form: 'Ampoules',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 300,
		calculationRule: (_) => alfacalcidolAmpDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ متابعة التحاليل ضرورية.'],
	},
	{
		id: 'one-alpha-2mcg-ml-drops-10ml',
		name: 'one alpha 2mcg/ml oral drops 10ml',
		genericName: 'alfacalcidol',
		concentration: '2 mcg/ml (10 ml)',
		price: 221,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'one alpha', 'وان ألفا', 'oral drops', 'drops', 'كالسيوم', 'عظام', 'فيتامين د', 'الفاكالسيدول'],
		usage: 'ألفاكالسيدول نقط لعلاج اضطرابات الكالسيوم/العظام حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => alfacalcidolDropsDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ متابعة التحاليل ضرورية.'],
	},
	{
		id: 'one-alpha-2mcg-ml-drops-20ml',
		name: 'one alpha 2mcg/ml oral drops 20ml',
		genericName: 'alfacalcidol',
		concentration: '2 mcg/ml (20 ml)',
		price: 382,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'one alpha', 'وان ألفا', 'oral drops', '20ml', 'كالسيوم', 'عظام', 'فيتامين د', 'الفاكالسيدول'],
		usage: 'ألفاكالسيدول نقط لعلاج اضطرابات الكالسيوم/العظام حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => alfacalcidolDropsDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ متابعة التحاليل ضرورية.'],
	},
	{
		id: 'taminorig-2mcg-ml-drops-10ml',
		name: 'taminorig 2mcg/ml oral drops. 10 ml',
		genericName: 'alfacalcidol',
		concentration: '2 mcg/ml (10 ml)',
		price: 91,
		matchKeywords: ['#vitamin d supplement', 'alfacalcidol', 'taminorig', 'تامينوريج', 'oral drops', 'drops', 'كالسيوم', 'عظام', 'فيتامين د', 'الفاكالسيدول'],
		usage: 'ألفاكالسيدول نقط لعلاج اضطرابات الكالسيوم/العظام حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً مع الأكل – مزمن',
		category: Category.DIABETES,
		form: 'Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => alfacalcidolDropsDose(),
		warnings: ['خطر ارتفاع الكالسيوم؛ متابعة التحاليل ضرورية.'],
	},
];
