
import { Medication, Category } from '../../types';

const levothyroxineDose = () => '١ قرص مرة يومياً صباحاً على معدة فارغة قبل الأكل بـ٣٠ دقيقة (مزمن)';

export const THYROXINE_MEDICATIONS: Medication[] = [
	{
		id: 't4-thyro-100mcg-100-tabs',
		name: 't4-thyro 100mcg 100 tablets',
		genericName: 'levothyroxine sodium',
		concentration: '100 mcg (100 tablets)',
		price: 58,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 't4-thyro', 't4 thyro', 'thyroxine', 'ليفوثيروكسين', 'هرمون الغدة', 'قصور الغدة', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة'],
		usage: 'هرمون الغدة الدرقية (ليفوثيروكسين) لعلاج قصور الغدة الدرقية.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['الجرعة تُضبط حسب TSH/FT4 ولا تُغير دون إعادة تقييم.', 'زيادة الجرعة قد تسبب خفقان/رعشة/أرق.', 'يتداخل مع أدوية كثيرة (الحديد/الكالسيوم/مضادات الحموضة/أوميبرازول/الوارفارين)؛ فاصل ساعتين على الأقل.'],
	},
	{
		id: 't4-thyro-50mcg-100-tabs',
		name: 't4-thyro 50 mcg 100 tabs.',
		genericName: 'levothyroxine sodium',
		concentration: '50 mcg (100 tablets)',
		price: 46,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 't4-thyro', '50mcg', 'ليفوثيروكسين', 'هرمون الغدة', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'هرمون الغدة الدرقية (ليفوثيروكسين) لعلاج قصور الغدة الدرقية.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['الجرعة تُضبط حسب TSH/FT4 ولا تُغير دون إعادة تقييم.', 'زيادة الجرعة قد تسبب خفقان/رعشة/أرق.', 'يتداخل مع أدوية كثيرة (الحديد/الكالسيوم/مضادات الحموضة/أوميبرازول/الوارفارين)؛ فاصل ساعتين على الأقل.'],
	},
	{
		id: 'euthyrox-100mcg-100-tab',
		name: 'euthyrox 100mcg 100 tab',
		genericName: 'levothyroxine sodium',
		concentration: '100 mcg (100 tablets)',
		price: 70,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'euthyrox', 'يوثيروكس', '100mcg', 'ليفوثيروكسين', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين لعلاج قصور الغدة الدرقية.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['لا توقفه فجأة دون إعادة تقييم.', 'قد يتداخل مع الحديد/الكالسيوم/مضادات الحموضة.'],
	},
	{
		id: 'euthyrox-25mcg-50-tab',
		name: 'euthyrox 25mcg 50 tab.',
		genericName: 'levothyroxine sodium',
		concentration: '25 mcg (50 tablets)',
		price: 33,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'euthyrox', 'يوثيروكس', '25mcg', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين (جرعات منخفضة) لعلاج قصور الغدة أو لبدء العلاج تدريجياً.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['الجرعة تُضبط حسب التحاليل (TSH/FT4).'],
	},
	{
		id: 'euthyrox-50mcg-100-tab',
		name: 'euthyrox 50mcg 100 tab',
		genericName: 'levothyroxine sodium',
		concentration: '50 mcg (100 tablets)',
		price: 45,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'euthyrox', 'يوثيروكس', '50mcg', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين لعلاج قصور الغدة الدرقية.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['لا تُغير الجرعة قبل إعادة التحليل بعد 4–6 أسابيع.'],
	},
	{
		id: 'euthyrox-50mcg-50-tab',
		name: 'euthyrox 50mcg 50 tab',
		genericName: 'levothyroxine sodium',
		concentration: '50 mcg (50 tablets)',
		price: 46,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'euthyrox', 'يوثيروكس', '50mcg', '50 tab', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين لعلاج قصور الغدة الدرقية.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['الجرعة تُضبط حسب TSH/FT4.'],
	},
	{
		id: 'euthyrox-25mcg-100-tab',
		name: 'euthyrox 25mcg 100 tab.',
		genericName: 'levothyroxine sodium',
		concentration: '25 mcg (100 tablets)',
		price: 30,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'euthyrox', 'يوثيروكس', '25mcg', '100 tab', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين (جرعات منخفضة) لعلاج قصور الغدة أو بدء العلاج تدريجياً.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['المتابعة بالتحاليل ضرورية.'],
	},
	{
		id: 'euthyrox-100mcg-50-tab',
		name: 'euthyrox 100mcg 50 tab.',
		genericName: 'levothyroxine sodium',
		concentration: '100 mcg (50 tablets)',
		price: 70,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'euthyrox', 'يوثيروكس', '100mcg', '50 tab', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين لعلاج قصور الغدة الدرقية.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['قد يلزم تعديل الجرعة مع الحمل أو تغيير الوزن.'],
	},
	{
		id: 'thyroxine-50mcg-100-tab',
		name: 'thyroxine 50mcg 100 tab.',
		genericName: 'thyroxine',
		concentration: '50 mcg (100 tablets)',
		price: 46,
		matchKeywords: ['#thyroid hormone', 'thyroxine', 'ليفوثيروكسين', '50mcg', 'thyroxine 50', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'هرمون الغدة الدرقية لعلاج قصور الغدة.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['المتابعة بالتحاليل ضرورية لضبط الجرعة.'],
	},
	{
		id: 'eltroxin-100mcg-100-tabs',
		name: 'eltroxin 100 mcg 100 tabs.',
		genericName: 'thyroxine',
		concentration: '100 mcg (100 tablets)',
		price: 115,
		matchKeywords: ['#thyroid hormone', 'eltroxin', 'التركسين', 'thyroxine', 'levothyroxine', '100mcg', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'هرمون الغدة الدرقية (ليفوثيروكسين) لعلاج قصور الغدة.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['جرعة زائدة قد تسبب خفقان/قلق/أرق.'],
	},
	{
		id: 'eltroxin-50mcg-100-tabs',
		name: 'eltroxin 50mcg 100 tabs.',
		genericName: 'thyroxine',
		concentration: '50 mcg (100 tablets)',
		price: 78,
		matchKeywords: ['#thyroid hormone', 'eltroxin', 'التركسين', 'thyroxine', '50mcg', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'هرمون الغدة الدرقية لعلاج قصور الغدة.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['اتبع نتائج التحاليل لضبط الجرعة.'],
	},
	{
		id: 'thyroxine-100mcg-100-tab',
		name: 'thyroxine 100mcg 100 tab.',
		genericName: 'thyroxine',
		concentration: '100 mcg (100 tablets)',
		price: 58,
		matchKeywords: ['#thyroid hormone', 'thyroxine', 'ليفوثيروكسين', '100mcg', 'thyroxine 100', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'هرمون الغدة الدرقية لعلاج قصور الغدة.',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['الجرعة تُضبط حسب TSH/FT4.'],
	},
	{
		id: 'tyraxine-100mcg-100-tab',
		name: 'tyraxine 100mcg 100 tab. (n/a)',
		genericName: 'levothyroxine sodium',
		concentration: '100 mcg (100 tablets)',
		price: 11,
		matchKeywords: ['#thyroid hormone', 'levothyroxine', 'tyraxine', 'تيراكسين', '100mcg', 'غدة درقية', 'الغدة الدرقية', 'thyroid', 'hypothyroidism', 'خمول الغدة', 'قصور الغدة'],
		usage: 'ليفوثيروكسين لعلاج قصور الغدة الدرقية (حسب التوفر).',
		timing: 'مرة يومياً صباحاً – مزمن',
		category: Category.DIABETES,
		form: 'Tablet',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 300,
		calculationRule: () => levothyroxineDose(),
		warnings: ['تحقق من التوفر والسعر قبل الصرف.'],
	},
];
