import { Category, Medication } from '../../types';

const fixed = (t: string) => () => t;

const normalizeNameForKey = (name: string): string => name.trim().toLowerCase().replace(/\s+/g, ' ');

const dedupeByNameAndPriceKeepFirst = (meds: Medication[]): Medication[] => {
	const seen = new Set<string>();
	const result: Medication[] = [];

	for (const med of meds) {
		const key = `${normalizeNameForKey(med.name)}|${med.price}`;
		if (!seen.has(key)) {
			seen.add(key);
			result.push(med);
		}
	}

	return result;
};

const COMMON_TOPICAL_MASSAGE_WARNINGS = [
	'للاستعمال الخارجي فقط.',
	'تجنب العينين والأغشية المخاطية.',
	'لا يُستخدم على جروح/جلد متشقق أو ملتهب بشدة.',
	'اغسل اليدين بعد الاستعمال.',
	'أوقفه عند حدوث تهيّج شديد/حساسية.',
	'لا تُغطَّ المنطقة بكمادات ساخنة أو ضمادات محكمة (يزيد الامتصاص والسمية).',
];

const NSAID_TOPICAL_WARNINGS = [
	...COMMON_TOPICAL_MASSAGE_WARNINGS,
	'تجنب استخدام مضادات الالتهاب الموضعية على مساحات كبيرة لفترة طويلة.',
	'الحمل: تجنب NSAIDs الموضعية في الثلث الثالث؛ الثلث الأول/الثاني: بأقل كمية ولمدة قصيرة إن لزم.',
];

const MASSAGE_GROUP_RAW: Medication[] = [
	// 1
	{
		id: 'massage-moov-massage-cream-40gm',
		name: 'moov massage cream 40 gm',
		genericName: 'camphor & menthol & methyl salicylate',
		concentration: '40 gm',
		price: 35,
		matchKeywords: ['moov', 'massage', 'cream', 'camphor', 'menthol', 'methyl salicylate', '#massage', '#topical analgesic', '#muscle', 'مساج', 'تدليك', 'آلام عضلات', 'muscle pain'],
		usage: 'مسكن/مساج موضعي لتخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 2
	{
		id: 'massage-rx-massage-cream-50gm',
		name: 'rx massage cream 50 gm',
		genericName: 'glucosamine & chondroitin & msm & ginko',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['rx massage', 'cream', 'glucosamine', 'chondroitin', 'msm', 'ginkgo', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 3
	{
		id: 'massage-rx-massage-gel-50gm',
		name: 'rx massage gel 50 gm',
		genericName: 'glucosamine & chondroitin & msm & ginko',
		concentration: '50 gm',
		price: 80,
		matchKeywords: ['rx massage', 'gel', 'glucosamine', 'chondroitin', 'msm', 'ginkgo', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 4
	{
		id: 'massage-sulfax-plus-massage-gel-120gm',
		name: 'sulfax plus massage gel 120 gm',
		genericName: 'eucalyptus oil & menthol & camphor oil',
		concentration: '120 gm',
		price: 170,
		matchKeywords: ['sulfax plus', 'massage gel', 'eucalyptus', 'menthol', 'camphor', '#massage', '#muscle'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات والشدّ العضلي البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 5
	{
		id: 'massage-sulfax-plus-massage-gel-60gm',
		name: 'sulfax plus massage gel 60 gm',
		genericName: 'eucalyptus oil & menthol & camphor oil',
		concentration: '60 gm',
		price: 100,
		matchKeywords: ['sulfax plus', 'massage gel 60', 'eucalyptus', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات والشدّ العضلي البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 6
	{
		id: 'massage-moscow-massage-cream-100gm',
		name: 'moscow massage cream 100 gm',
		genericName: 'glucosamine & methyl salicylate & menthol & camphor',
		concentration: '100 gm',
		price: 95,
		matchKeywords: ['moscow', 'massage cream', 'glucosamine', 'menthol', 'camphor', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 7
	{
		id: 'massage-repaion-n-gel-100gm',
		name: 'repaion-n gel 100 gm',
		genericName: 'camphor oil & menthol crystals & eucalyptus oil & salicylic acid',
		concentration: '100 gm',
		price: 110,
		matchKeywords: ['repaion-n', 'repaion', 'gel', 'camphor', 'menthol', 'eucalyptus', 'salicylic acid', '#massage', '#salicylate'],
		usage: 'جل مساج/مسكن موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 8
	{
		id: 'massage-voltaren-1-emulgel-100gm',
		name: 'voltaren 1% emulgel 100 gm',
		genericName: 'diclofenac sodium',
		concentration: '1% (100 gm)',
		price: 101,
		matchKeywords: ['voltaren', 'emulgel', 'diclofenac', '1%', '100 gm', '#massage', '#nsaid'],
		usage: 'جل ديكلوفيناك موضعي لتخفيف ألم/التهاب العضلات والمفاصل (التواءات/شدّ).',
		timing: '٢–٣ مرات يومياً',
		category: Category.DICLOFENAC,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...NSAID_TOPICAL_WARNINGS],
	},

	// 9
	{
		id: 'massage-voltaren-1-emulgel-25gm',
		name: 'voltaren 1% emulgel 25 gm',
		genericName: 'diclofenac sodium',
		concentration: '1% (25 gm)',
		price: 39,
		matchKeywords: ['voltaren', 'emulgel', 'diclofenac', '1%', '25 gm', '#massage', '#nsaid'],
		usage: 'جل ديكلوفيناك موضعي لتخفيف ألم/التهاب العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.DICLOFENAC,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...NSAID_TOPICAL_WARNINGS],
	},

	// 10
	{
		id: 'massage-voltaren-1-emulgel-50gm',
		name: 'voltaren 1% emulgel 50 gm',
		genericName: 'diclofenac sodium',
		concentration: '1% (50 gm)',
		price: 68,
		matchKeywords: ['voltaren', 'emulgel', 'diclofenac', '1%', '50 gm', '#massage', '#nsaid'],
		usage: 'جل ديكلوفيناك موضعي لتخفيف ألم/التهاب العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.DICLOFENAC,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...NSAID_TOPICAL_WARNINGS],
	},

	// 11
	{
		id: 'massage-repaion-n-gel-50gm',
		name: 'repaion-n gel 50 gm',
		genericName: 'camphor oil & menthol crystals & eucalyptus oil & salicylic acid',
		concentration: '50 gm',
		price: 65,
		matchKeywords: ['repaion-n', '50', 'gel', 'camphor', 'menthol', 'eucalyptus', 'salicylic acid', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج/مسكن موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 12
	{
		id: 'massage-rx-massage-cream-100gm',
		name: 'rx massage cream 100 gm',
		genericName: 'glucosamine & chondroitin & msm & ginko',
		concentration: '100 gm',
		price: 80,
		matchKeywords: ['rx massage', 'cream', '100', 'glucosamine', 'chondroitin', 'msm', 'ginkgo', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 13
	{
		id: 'massage-rx-massage-gel-100gm',
		name: 'rx massage gel 100 gm',
		genericName: 'glucosamine & chondroitin & msm & ginko',
		concentration: '100 gm',
		price: 110,
		matchKeywords: ['rx massage', 'gel', '100', 'glucosamine', 'chondroitin', 'msm', 'ginkgo', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 14
	{
		id: 'massage-hi-cool-massage-cream-100gm',
		name: 'hi-cool massage cream 100 gm',
		genericName: 'camphor & menthol & eucalyptus & methyl salicylate',
		concentration: '100 gm',
		price: 79,
		matchKeywords: ['hi-cool', 'massage cream', 'camphor', 'menthol', 'eucalyptus', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 15
	{
		id: 'massage-universal-massage-spray-100ml',
		name: 'universal massage spray 100 ml',
		genericName: 'glucosamine & chondroitin sulphate & msm & emu oil',
		concentration: '100 ml',
		price: 145,
		matchKeywords: ['universal', 'massage spray', 'glucosamine', 'chondroitin', 'msm', 'emu oil', '#massage', '#muscle'],
		usage: 'سبراي مساج موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 16
	{
		id: 'massage-cybreak-massage-spray-100ml',
		name: 'cybreak massage spray 100 ml',
		genericName: 'menthol & eucalyptus & thyme oil & tea tree oil & ginkgo biloba',
		concentration: '100 ml',
		price: 85,
		matchKeywords: ['cybreak', 'massage spray', 'menthol', 'eucalyptus', 'thyme', 'tea tree', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 17
	{
		id: 'massage-oneceutik-massage-gel-50gm',
		name: 'oneceutik massage gel 50 gm',
		genericName: 'menthol & ginkgo biloba leaf extract & thymus vulgaris oil',
		concentration: '50 gm',
		price: 65,
		matchKeywords: ['oneceutik', 'massage gel', 'menthol', 'ginkgo', 'thyme', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لآلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 18
	{
		id: 'massage-linex-massage-cream-50gm',
		name: 'linex massage cream 50 gm',
		genericName: 'massage cream',
		concentration: '50 gm',
		price: 70,
		matchKeywords: ['linex', 'massage cream', '#massage', '#topical analgesic', '#muscle', 'مساج', 'تدليك', 'آلام عضلات', 'muscle pain'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 19
	{
		id: 'massage-spunky-massage-gel-50gm',
		name: 'spunky massage gel 50 gm',
		genericName: 'menthol & peg 400 & eucalyptus',
		concentration: '50 gm',
		price: 90,
		matchKeywords: ['spunky', 'massage gel', 'menthol', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 20
	{
		id: 'massage-sulfax-cmo-formula-massage-cream-120gm',
		name: 'sulfax (cmo formula) massage cream 120 gm',
		genericName: 'eucalyptus oil & menthol & camphor oil',
		concentration: '120 gm',
		price: 120,
		matchKeywords: ['sulfax', 'cmo', 'massage cream', 'eucalyptus', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 21
	{
		id: 'massage-movelex-plus-massage-gel-100gm',
		name: 'movelex plus massage gel 100 gm',
		genericName: 'magnesium',
		concentration: '100 gm',
		price: 150,
		matchKeywords: ['movelex plus', 'massage gel', 'magnesium', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 22
	{
		id: 'massage-woody-massage-gel-60gm',
		name: 'woody massage gel 60 gm',
		genericName: 'panthenol & thyme oil & peppermint oil & cinnamon oil',
		concentration: '60 gm',
		price: 80,
		matchKeywords: ['woody', 'massage gel', 'panthenol', 'peppermint', 'thyme', 'cinnamon', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لإنعاش وتهدئة آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 23
	{
		id: 'massage-qrockal-massage-cream-50mg',
		name: 'qrockal massage cream 50mg',
		genericName: 'menthol & camphor oil & eucalyptus oil & clove oil',
		concentration: '50 mg',
		price: 55,
		matchKeywords: ['qrockal', 'massage cream', 'menthol', 'camphor', 'eucalyptus', 'clove', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 24
	{
		id: 'massage-saj-relax-massage-gel-50gm',
		name: 'saj relax massage gel 50gm',
		genericName: 'menthol & arnica & campher & clove oil & eucalyptus',
		concentration: '50 gm',
		price: 65,
		matchKeywords: ['saj relax', 'massage gel', 'arnica', 'menthol', 'clove', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 25
	{
		id: 'massage-algesal-suractive-cream-40gm',
		name: 'algesal suractive cream 40 gm',
		genericName: 'diethylamine salicylate & myrtecaine',
		concentration: '40 gm',
		price: 46,
		matchKeywords: ['algesal', 'suractive', 'cream', 'salicylate', '#massage', '#topical analgesic', '#muscle', 'مساج', 'تدليك', 'آلام عضلات', 'muscle pain'],
		usage: 'كريم مسكن موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 26
	{
		id: 'massage-faster-gel-80gm',
		name: 'faster gel 80 gm',
		genericName: 'menthol & camphor',
		concentration: '80 gm',
		price: 40,
		matchKeywords: ['faster', 'gel', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 27
	{
		id: 'massage-myocool-cream-60gm',
		name: 'myocool cream 60 gm',
		genericName: 'winter green oil & peppermint oil',
		concentration: '60 gm',
		price: 85,
		matchKeywords: ['myocool', 'cream', 'wintergreen', 'peppermint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 28
	{
		id: 'massage-reparil-gel-n-40gm',
		name: 'reparil-gel n 40 gm',
		genericName: 'aescin & diethylamine salicylate',
		concentration: '40 gm',
		price: 58,
		matchKeywords: ['reparil-gel n', 'reparil', 'aescin', 'salicylate', '#massage', '#nsaid'],
		usage: 'جل موضعي للكدمات/التورم وآلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 29
	{
		id: 'massage-urgent-plus-cream-50gm',
		name: 'urgent plus cream 50gm',
		genericName: 'glucosamine & chondroitin & methyl sulfonyl methane',
		concentration: '50 gm',
		price: 80,
		matchKeywords: ['urgent plus', 'cream', 'glucosamine', 'chondroitin', 'msm', '#massage', '#muscle'],
		usage: 'كريم مساج لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 30
	{
		id: 'massage-yogin-cream-100gm',
		name: 'yogin 100 gm cream',
		genericName: 'stearic acid & triethanolamine & menthol & camphor',
		concentration: '100 gm',
		price: 68,
		matchKeywords: ['yogin', 'cream', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 31
	{
		id: 'massage-pomirja-gel-100gm',
		name: 'pomirja gel 100gm',
		genericName: 'menthol crystals & methyl salicylate & vitamin e & camphor',
		concentration: '100 gm',
		price: 149,
		matchKeywords: ['pomirja', 'gel', 'menthol', 'methyl salicylate', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 32
	{
		id: 'massage-pomirja-gel-50gm',
		name: 'pomirja gel 50 gm',
		genericName: 'menthol & vitamin e & camphor oil & eucalyptus oil',
		concentration: '50 gm',
		price: 65,
		matchKeywords: ['pomirja', 'gel 50', 'menthol', 'camphor', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 33
	{
		id: 'massage-relax-cream-50gm',
		name: 'relax cream 50 gm',
		genericName: 'massage cream',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['relax', 'cream', 'massage cream', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لآلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 34
	{
		id: 'massage-relax-gel-50gm',
		name: 'relax gel 50 gm',
		genericName: 'chondroitin & msm & camphor & glucosamine',
		concentration: '50 gm',
		price: 80,
		matchKeywords: ['relax', 'gel', 'chondroitin', 'msm', 'camphor', 'glucosamine', '#massage', '#muscle'],
		usage: 'جل مساج موضعي لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 35
	{
		id: 'massage-tulataj-gel-60gm',
		name: 'tulataj gel 60 gm',
		genericName: 'thyme extract & camphor & clove oil & peppermint oil',
		concentration: '60 gm',
		price: 68,
		matchKeywords: ['tulataj', 'gel', 'thyme', 'camphor', 'clove', 'peppermint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 36
	{
		id: 'massage-universal-cream-100gm',
		name: 'universal cream 100 gm',
		genericName: 'glucosamine & chondroitin sulphate & msm & emu oil',
		concentration: '100 gm',
		price: 95,
		matchKeywords: ['universal', 'cream', 'glucosamine', 'chondroitin', 'msm', 'emu oil', '#massage', '#muscle'],
		usage: 'كريم مساج موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 37
	{
		id: 'massage-fast-freeze-gel-100gm',
		name: 'fast freeze gel 100 gm',
		genericName: 'camphor & menthol',
		concentration: '100 gm',
		price: 160,
		matchKeywords: ['fast freeze', 'gel', 'camphor', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي بتأثير مبرد لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 38
	{
		id: 'massage-cosamine-massage-cream-50gm',
		name: 'cosamine massage cream 50 gm',
		genericName: 'glucosamine sulfate & chondroitin sulfate & msm',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['cosamine', 'massage cream', 'glucosamine', 'chondroitin', 'msm', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 39
	{
		id: 'massage-lusty-massage-gel-75gm',
		name: 'lusty massage gel 75 gm',
		genericName: 'camphor oil & clove oil & eucalyptus & menthol & lidocaine',
		concentration: '75 gm',
		price: 70,
		matchKeywords: ['lusty', 'massage gel', 'camphor', 'clove', 'eucalyptus', 'menthol', 'lidocaine', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة وقد يساعد مع الألم الموضعي.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 40
	{
		id: 'massage-saj-relax-massage-cream-60gm',
		name: 'saj relax massage cream 60gm',
		genericName: 'stearic acid & beeswax & camphor oil',
		concentration: '60 gm',
		price: 70,
		matchKeywords: ['saj relax', 'massage cream', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 41
	{
		id: 'massage-himax-massage-gel-30gm',
		name: 'himax massage gel 30 gm',
		genericName: 'menthol & eucalyptus & camphor & methyl salicylate',
		concentration: '30 gm',
		price: 55,
		matchKeywords: ['himax', 'massage gel', 'menthol', 'eucalyptus', 'camphor', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 42
	{
		id: 'massage-relironz-massage-gel-50gm',
		name: 'relironz 50 gm massage gel',
		genericName: 'menthol & camphor oil & clove oil & herbal extracts',
		concentration: '50 gm',
		price: 59,
		matchKeywords: ['relironz', 'massage gel', 'menthol', 'camphor', 'clove', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 43
	{
		id: 'massage-radian-massage-cream-100gm',
		name: 'radian massage cream 100 gm',
		genericName: 'camphor & capsicium oleoresin & menthol',
		concentration: '100 gm',
		price: 42.5,
		matchKeywords: ['radian', 'massage cream', 'camphor', 'capsicum', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي (قد يعطي إحساساً بالدفء) لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 44
	{
		id: 'massage-salgy-massage-cream-50gm',
		name: 'salgy massage cream 50 gm',
		genericName: 'camphor crystal & menthol crystal & clove extract & eucalyptus',
		concentration: '50 gm',
		price: 70,
		matchKeywords: ['salgy', 'massage cream', 'camphor', 'menthol', 'clove', 'eucalyptus', '#massage', '#muscle'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 45
	{
		id: 'massage-sulfax-cmo-formula-massage-cream-60gm',
		name: 'sulfax (cmo formula) massage cream 60 gm',
		genericName: 'eucalyptus oil & menthol & camphor oil',
		concentration: '60 gm',
		price: 95,
		matchKeywords: ['sulfax', 'cmo', 'massage cream 60', 'eucalyptus', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 46
	{
		id: 'massage-universal-massage-gel-50gm',
		name: 'universal massage gel 50 gm',
		genericName: 'glucosamine & chondroitin sulphate & msm & emu oil',
		concentration: '50 gm',
		price: 69,
		matchKeywords: ['universal', 'massage gel', 'glucosamine', 'chondroitin', 'msm', 'emu oil', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 47
	{
		id: 'massage-zondex-massage-spray-100ml',
		name: 'zondex massage spray 100 ml',
		genericName: 'eucalyptus & grape & willow & thyme & terpene oil',
		concentration: '100 ml',
		price: 85,
		matchKeywords: ['zondex', 'massage spray', 'eucalyptus', 'willow', 'thyme', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 48
	{
		id: 'massage-fast-freeze-massage-spray-150ml',
		name: 'fast freeze massage spray 150 ml',
		genericName: 'camphor & menthol',
		concentration: '150 ml',
		price: 250,
		matchKeywords: ['fast freeze', 'massage spray', 'camphor', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي بتأثير مبرد لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 49
	{
		id: 'massage-glasgow-massage-cream-60gm',
		name: 'glasgow massage cream 60 gm',
		genericName: 'methyl salicylate & menthol & camphor',
		concentration: '60 gm',
		price: 65,
		matchKeywords: ['glasgow', 'massage cream', 'methyl salicylate', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 50
	{
		id: 'massage-like-massage-cream-50gm',
		name: 'like massage cream 50 gm',
		genericName: 'menthol & camphor & eucalyptus',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['like', 'massage cream', 'menthol', 'camphor', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 51
	{
		id: 'massage-relacomp-massage-gel-100gm',
		name: 'relacomp massage gel 100 gm',
		genericName: 'camphor & menthol & eucalyptus oil & emu oil',
		concentration: '100 gm',
		price: 75,
		matchKeywords: ['relacomp', 'massage gel', 'camphor', 'menthol', 'eucalyptus', 'emu oil', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 52
	{
		id: 'massage-wellssage-massage-gel-30gm',
		name: 'wellssage massage gel 30gm',
		genericName: 'camphor oil & peppermint oil & eucalyptus oil',
		concentration: '30 gm',
		price: 40,
		matchKeywords: ['wellssage', 'massage gel', 'camphor', 'peppermint', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 53
	{
		id: 'massage-wellssage-massage-gel-50gm',
		name: 'wellssage massage gel 50gm',
		genericName: 'camphor oil & peppermint oil & eucalyptus oil',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['wellssage', 'massage gel 50', 'camphor', 'peppermint', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 54
	{
		id: 'massage-top-relax-massage-cream',
		name: 'top relax massage cr',
		genericName: 'lidocaine & aescin & methyl salicylate',
		concentration: 'N/A',
		price: 89,
		matchKeywords: ['top relax', 'massage', 'cream', 'lidocaine', 'aescin', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة وقد يساعد مع الألم الموضعي.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 55
	{
		id: 'massage-runner-massage-gel-50ml',
		name: 'runner massage gel 50 ml',
		genericName: 'menthol & camphor & eucalyptus & avocado oil',
		concentration: '50 ml',
		price: 55,
		matchKeywords: ['runner', 'massage gel', 'menthol', 'camphor', 'eucalyptus', 'avocado', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لإنعاش وتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 56
	{
		id: 'massage-eucal-cream-30gm',
		name: 'eucal cream 30 gm',
		genericName: 'eucalyptus globulus & gaultheria procumbens',
		concentration: '30 gm',
		price: 60,
		matchKeywords: ['eucal', 'cream', 'eucalyptus', 'gaultheria', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 57
	{
		id: 'massage-himax-cream-30gm',
		name: 'himax cream 30 gm',
		genericName: 'menthol & eucalyptus & camphor & methyl salicylate',
		concentration: '30 gm',
		price: 55,
		matchKeywords: ['himax', 'cream', 'menthol', 'eucalyptus', 'camphor', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 58
	{
		id: 'massage-mobiease-gel-60gm',
		name: 'mobiease gel 60 gm',
		genericName: 'glucosamine & chondroitin & msm & vitamin c & menthol',
		concentration: '60 gm',
		price: 80,
		matchKeywords: ['mobiease', 'gel', 'glucosamine', 'chondroitin', 'msm', 'vitamin c', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم تخفيف آلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 59
	{
		id: 'massage-mobinorm-cream-60gm',
		name: 'mobinorm cream 60 gm',
		genericName: 'camphor & horse chestnut & rosemary oil & lemon grass oil',
		concentration: '60 gm',
		price: 75,
		matchKeywords: ['mobinorm', 'cream', 'horse chestnut', 'rosemary', 'lemongrass', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات وتخفيف الشدّ البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 60
	{
		id: 'massage-sulfax-magnesium-cream-120gm',
		name: 'sulfax magnesium cream 120 gm',
		genericName: 'eucalyptus oil & menthol & camphor oil',
		concentration: '120 gm',
		price: 170,
		matchKeywords: ['sulfax', 'magnesium', 'massage cream', 'menthol', 'camphor', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات وتخفيف الألم البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 61
	{
		id: 'massage-lusty-joint-tabs-30',
		name: 'lusty joint 30 tabs',
		genericName: 'camphor oil & clove oil & eucalyptus & menthol & lidocaine',
		concentration: '30 tabs',
		price: 270,
		matchKeywords: ['lusty joint', 'tabs', 'joint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'أقراص لدعم راحة المفاصل (حسب الإرشادات على العبوة).',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: ['الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.', 'إذا لديك حساسية لأي مكوّن أوقف الاستخدام.', 'راجع التفاعلات مع مضادات التخثر/مميعات الدم والأدوية المماثلة؛ تجنب الجمع دون تقييم.'],
	},

	// 62
	{
		id: 'massage-repaion-n-spray-120ml',
		name: 'repaion-n spray 120 ml',
		genericName: 'camphor oil & menthol crystals & eucalyptus oil & salicylic acid',
		concentration: '120 ml',
		price: 130,
		matchKeywords: ['repaion-n', 'spray', 'camphor', 'menthol', 'eucalyptus', 'salicylic acid', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج/مسكن موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 63
	{
		id: 'massage-rayen-gel-120gm',
		name: 'rayen gel 120 gm',
		genericName: 'glucosamine & chondroitin sulfate & msm & gingko',
		concentration: '120 gm',
		price: 120,
		matchKeywords: ['rayen', 'gel', 'glucosamine', 'chondroitin', 'msm', 'ginkgo', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم راحة المفاصل والعضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 64
	{
		id: 'massage-eucal-gel-30gm',
		name: 'eucal gel 30 gm',
		genericName: 'eucalyptus oil & peppermint oil & camphor oil',
		concentration: '30 gm',
		price: 60,
		matchKeywords: ['eucal', 'gel 30', 'eucalyptus', 'peppermint', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 65
	{
		id: 'massage-finitrue-topical-gel-80gm',
		name: 'finitrue topical gel 80 gm',
		genericName: 'menthol oil & camphor oil & clove oil & eucalyptus oil & vitamin e',
		concentration: '80 gm',
		price: 89,
		matchKeywords: ['finitrue', 'topical gel', 'menthol', 'camphor', 'clove', 'eucalyptus', 'vitamin e', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج/مسكن موضعي لآلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 66
	{
		id: 'massage-frost-gel-100gm',
		name: 'frost gel 100 gm',
		genericName: 'menthol & chamomile & lavender',
		concentration: '100 gm',
		price: 110,
		matchKeywords: ['frost', 'gel', 'menthol', 'chamomile', 'lavender', '#massage', '#muscle'],
		usage: 'جل مساج موضعي (مبرد) لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 67
	{
		id: 'massage-maxi-care-cream-75gm',
		name: 'maxi care cream 75 gm',
		genericName: 'gaultheria oil & clove oil & eucalyptus oil & turpentine',
		concentration: '75 gm',
		price: 137,
		matchKeywords: ['maxi care', 'cream', 'gaultheria', 'clove', 'eucalyptus', 'turpentine', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 68
	{
		id: 'massage-myocool-cream-100gm',
		name: 'myocool cream 100 gm',
		genericName: 'winter green oil & peppermint oil',
		concentration: '100 gm',
		price: 125,
		matchKeywords: ['myocool', 'cream 100', 'wintergreen', 'peppermint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 69
	{
		id: 'massage-srilane-idrocilamide-5-cream-20gm',
		name: 'srilane 5% cream 20 gm',
		genericName: 'idrocilamide',
		concentration: '5% (20 gm)',
		price: 32.5,
		matchKeywords: ['srilane', 'idrocilamide', '5%', 'cream', '#massage', '#analgesics'],
		usage: 'كريم موضعي لتخفيف آلام/شدّ العضلات البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 70
	{
		id: 'massage-srilane-idrocilamide-5-cream-60gm',
		name: 'srilane 5% cream 60 gm',
		genericName: 'idrocilamide',
		concentration: '5% (60 gm)',
		price: 73,
		matchKeywords: ['srilane', 'idrocilamide', '5%', 'cream 60', '#massage', '#analgesics'],
		usage: 'كريم موضعي لتخفيف آلام/شدّ العضلات البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 71
	{
		id: 'massage-rx-spray-100ml',
		name: 'rx spray 100 ml',
		genericName: 'glucosamine & chondroitin & msm & ginko',
		concentration: '100 ml',
		price: 95,
		matchKeywords: ['rx', 'spray', 'glucosamine', 'chondroitin', 'msm', 'ginkgo', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي لدعم راحة العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 72
	{
		id: 'massage-universal-cream-50gm',
		name: 'universal cream 50 gm',
		genericName: 'glucosamine & chondroitin sulphate & msm & emu oil',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['universal', 'cream 50', 'glucosamine', 'chondroitin', 'msm', 'emu oil', '#massage', '#muscle'],
		usage: 'كريم مساج موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 73
	{
		id: 'massage-velaback-cream-50gm',
		name: 'velaback cream 50 gm',
		genericName: 'eucalyptus & camphor & cinnamon oil & menthol crystals',
		concentration: '50 gm',
		price: 55,
		matchKeywords: ['velaback', 'cream', 'eucalyptus', 'camphor', 'cinnamon', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 74
	{
		id: 'massage-zondex-gel-75gm',
		name: 'zondex gel 75 gm',
		genericName: 'gaultheria oil & willow bark extract & eucalyptus oil & turpentine',
		concentration: '75 gm',
		price: 69,
		matchKeywords: ['zondex', 'gel', 'gaultheria', 'willow', 'eucalyptus', 'turpentine', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 75
	{
		id: 'massage-mobiease-cream-60gm',
		name: 'mobiease cream 60 gm',
		genericName: 'glucosamine & chondroitin & msm & vitamin c & menthol',
		concentration: '60 gm',
		price: 40,
		matchKeywords: ['mobiease', 'cream', 'glucosamine', 'chondroitin', 'msm', 'vitamin c', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 76
	{
		id: 'massage-movelex-advance-caps-30',
		name: 'movelex advance 30 caps.',
		genericName: 'glucosamine & hydrolyzed marine collagen & chondroitin',
		concentration: '30 caps',
		price: 295,
		matchKeywords: ['movelex advance', 'caps', 'glucosamine', 'collagen', 'chondroitin', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كبسولات لدعم صحة المفاصل والغضاريف (حسب العبوة).',
		timing: '٢–٣ مرات يومياً',
		category: Category.BONE_SUPPORT,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: ['الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.', 'مرضى الحساسية للمأكولات البحرية: بحذر.', 'أوقفه عند أعراض حساسية.'],
	},

	// 77
	{
		id: 'massage-algason-massage-cream-40gm',
		name: 'algason massage cream 40 gm',
		genericName: 'camphor & menthol & diethylamine salicylate',
		concentration: '40 gm',
		price: 46,
		matchKeywords: ['algason', 'massage cream', 'camphor', 'menthol', 'salicylate', '#massage', '#analgesics'],
		usage: 'كريم مسكن/مساج موضعي لآلام العضلات والمفاصل البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 78
	{
		id: 'massage-flexjo-massage-cream-100gm',
		name: 'flexjo 100 gm massage cream',
		genericName: 'clove extract & herbal extracts',
		concentration: '100 gm',
		price: 100,
		matchKeywords: ['flexjo', 'massage cream', 'clove', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 79
	{
		id: 'massage-dromage-massage-cream-75gm',
		name: 'dromage massage cream 75 gm',
		genericName: 'peppermint oil & menthol crystals & clove extract & camphor',
		concentration: '75 gm',
		price: 55,
		matchKeywords: ['dromage', 'massage cream', 'peppermint', 'menthol', 'clove', 'camphor', '#massage', '#analgesics'],
		usage: 'كريم مسكن/مساج موضعي لآلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 80
	{
		id: 'massage-rostevo-massage-gel-50gm',
		name: 'rostevo 50 gm massage gel',
		genericName: 'camphor oil & menthol crystals & eucalyptus oil',
		concentration: '50 gm',
		price: 60,
		matchKeywords: ['rostevo', 'massage gel', 'camphor', 'menthol', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 81
	{
		id: 'massage-reva-lax-massage-gel-75gm',
		name: 'reva lax 75 gm massage gel',
		genericName: 'camphor & peppermint oil & menthol crystals & tea tree oil',
		concentration: '75 gm',
		price: 67,
		matchKeywords: ['reva lax', 'massage gel', 'camphor', 'peppermint', 'menthol', 'tea tree', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 82
	{
		id: 'massage-maxrone-massage-gel-50gm',
		name: 'maxrone massage gel 50 gm',
		genericName: 'glucosamine & chondroitin & methyl sulfonyl methane',
		concentration: '50 gm',
		price: 78,
		matchKeywords: ['maxrone', 'massage gel', 'glucosamine', 'chondroitin', 'msm', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم راحة المفاصل والعضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 83
	{
		id: 'massage-fast-freeze-magnesium-massage-spray-150ml',
		name: 'fast freeze magnesium massage spray 150 ml',
		genericName: 'camphor & menthol & magnesium',
		concentration: '150 ml',
		price: 250,
		matchKeywords: ['fast freeze', 'magnesium', 'massage spray', 'camphor', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي بتأثير مبرد لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 84
	{
		id: 'massage-everson-massage-spray-100ml',
		name: 'everson massage spray 100 ml',
		genericName: 'camphor oil & eucalyptus oil & diethanolamine salicylate',
		concentration: '100 ml',
		price: 95,
		matchKeywords: ['everson', 'massage spray', 'camphor', 'eucalyptus', 'salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 85
	{
		id: 'massage-mentophor-massage-cream-100gm',
		name: 'mentophor massage cream 100 gm',
		genericName: 'menthol crystals & eucalyptus oil & peppermint oil & camphor',
		concentration: '100 gm',
		price: 100,
		matchKeywords: ['mentophor', 'massage cream', 'menthol', 'eucalyptus', 'peppermint', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 86
	{
		id: 'massage-lusty-massage-gel-50gm',
		name: 'lusty massage gel 50 gm',
		genericName: 'camphor oil & clove oil & eucalyptus & menthol & lidocaine',
		concentration: '50 gm',
		price: 55,
		matchKeywords: ['lusty', 'massage gel 50', 'camphor', 'clove', 'eucalyptus', 'menthol', 'lidocaine', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 87
	{
		id: 'massage-mestal-massage-gel-30gm',
		name: 'mestal massage gel 30 gm',
		genericName: 'menthol & camphor & eucalyptus oil',
		concentration: '30 gm',
		price: 20,
		matchKeywords: ['mestal', 'massage gel', 'menthol', 'camphor', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 88
	{
		id: 'massage-reboss-massage-cream-50gm',
		name: 'reboss massage cream 50 gm',
		genericName: 'camphor & menthol & methyl salicylate & eucalyptus',
		concentration: '50 gm',
		price: 60,
		matchKeywords: ['reboss', 'massage cream', 'camphor', 'menthol', 'methyl salicylate', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 89
	{
		id: 'massage-urgent-massage-cream-50',
		name: 'urgent massage cream 50',
		genericName: 'capsicum annuum & camphor & menthol & methyl salicylate',
		concentration: 'N/A',
		price: 70,
		matchKeywords: ['urgent', 'massage cream', 'capsicum', 'camphor', 'menthol', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي (قد يعطي إحساساً بالدفء) لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 90
	{
		id: 'massage-zaffo-massage-gel-75gm',
		name: 'zaffo massage gel 75 gm',
		genericName: 'camphor oil & eucalyptus oil & menthol crystal',
		concentration: '75 gm',
		price: 85,
		matchKeywords: ['zaffo', 'massage gel', 'camphor', 'eucalyptus', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 91
	{
		id: 'massage-movelex-massage-cream-120gm',
		name: 'movelex massage cream 120 gm',
		genericName: 'peppermint oil & eucalyptus oil & camphor & tocopherol',
		concentration: '120 gm',
		price: 120,
		matchKeywords: ['movelex', 'massage cream', 'peppermint', 'eucalyptus', 'camphor', 'tocopherol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 92
	{
		id: 'massage-movelex-massage-cream-50gm',
		name: 'movelex massage cream 50 gm',
		genericName: 'peppermint oil & eucalyptus oil & camphor & tocopherol',
		concentration: '50 gm',
		price: 95,
		matchKeywords: ['movelex', 'massage cream 50', 'peppermint', 'eucalyptus', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 93
	{
		id: 'massage-parten-massage-spray',
		name: 'parten massage spray',
		genericName: 'lidocaine & aescin & methyl salicylate',
		concentration: 'N/A',
		price: 110,
		matchKeywords: ['parten', 'massage spray', 'lidocaine', 'aescin', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي لتخفيف الألم الموضعي البسيط.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 94
	{
		id: 'massage-frontkeen-massage-cream-sachets-30',
		name: 'frontkeen massage cream -30 sachets',
		genericName: 'peppermint oil & eucalyptus oil & vitamin e',
		concentration: '30 sachets',
		price: 150,
		matchKeywords: ['frontkeen', 'massage', 'sachets', 'peppermint', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'عبوات/ساشيهات كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 95
	{
		id: 'massage-movelex-active-massage-foam-200ml',
		name: 'movelex active massage foam 200 ml',
		genericName: 'emu oil & aloe vera extract & boswellia extract & nigella sativa',
		concentration: '200 ml',
		price: 295,
		matchKeywords: ['movelex active', 'massage foam', 'foam', 'emu oil', 'aloe vera', 'boswellia', 'nigella', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'فوم مساج موضعي لدعم راحة العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Foam',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 96
	{
		id: 'massage-flexfeel-massage-gel-75gm',
		name: 'flexfeel massage gel 75 gm',
		genericName: 'eucalyptus oil & menthol & camphor oil & clove oil',
		concentration: '75 gm',
		price: 75,
		matchKeywords: ['flexfeel', 'massage gel', 'eucalyptus', 'menthol', 'camphor', 'clove', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 97
	{
		id: 'massage-ososage-massage-gel-50gm',
		name: 'ososage massage gel 50gm',
		genericName: 'camphor extract & menthol extract & eucalyptus & thyme extract',
		concentration: '50 gm',
		price: 55,
		matchKeywords: ['ososage', 'massage gel', 'camphor', 'menthol', 'eucalyptus', 'thyme', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 98
	{
		id: 'massage-rapgado-massage-gel-100gm',
		name: 'rapgado massage gel 100 gm',
		genericName: 'glucosamine sulfate & chondroitin sulfate & methyl sulfonyl methane',
		concentration: '100 gm',
		price: 55,
		matchKeywords: ['rapgado', 'massage gel', 'glucosamine', 'chondroitin', 'msm', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم راحة المفاصل والعضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 99
	{
		id: 'massage-reboss-massage-cream-30gm',
		name: 'reboss massage cream 30 gm',
		genericName: 'camphor & menthol & methyl salicylate & eucalyptus',
		concentration: '30 gm',
		price: 40,
		matchKeywords: ['reboss', 'massage cream 30', 'camphor', 'menthol', 'methyl salicylate', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 100
	{
		id: 'massage-roflex-massage-gel-50gm',
		name: 'roflex massage gel 50gm',
		genericName: 'eucalyptus & clove & camphor & peppermint',
		concentration: '50 gm',
		price: 50,
		matchKeywords: ['roflex', 'massage gel', 'eucalyptus', 'clove', 'camphor', 'peppermint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 101
	{
		id: 'massage-relacomp-spray-100ml',
		name: 'relacomp 100ml spray',
		genericName: 'camphor & menthol & eucalyptus oil & omega 3',
		concentration: '100 ml',
		price: 120,
		matchKeywords: ['relacomp', 'spray', 'camphor', 'menthol', 'eucalyptus', 'omega 3', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 102
	{
		id: 'massage-eucal-gel-50gm',
		name: 'eucal gel 50 gm',
		genericName: 'eucalyptus globulus & gaultheria procumbens',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['eucal', 'gel 50', 'eucalyptus globulus', 'gaultheria', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 103
	{
		id: 'massage-linex-spray-120ml',
		name: 'linex spray 120 ml',
		genericName: 'massage formula',
		concentration: '120 ml',
		price: 120,
		matchKeywords: ['linex', 'spray', 'massage formula', '#massage', '#muscle'],
		usage: 'سبراي مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 104
	{
		id: 'massage-osteforte-cream-60gm',
		name: 'osteforte cream 60 gm',
		genericName: 'glucosamine sulfate & chondroitin sulfate',
		concentration: '60 gm',
		price: 69.95,
		matchKeywords: ['osteforte', 'cream', 'glucosamine', 'chondroitin', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة المفاصل والعضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.MUSCULOSKELETAL,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 105
	{
		id: 'massage-salex-gel-50gm',
		name: 'salex gel 50 gm',
		genericName: 'menthol & chamomile & camphor & methyl salicylate',
		concentration: '50 gm',
		price: 40,
		matchKeywords: ['salex', 'gel', 'menthol', 'chamomile', 'camphor', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 106
	{
		id: 'massage-voltaren-1-emulgel-15gm',
		name: 'voltaren 1% emulgel 15 gm',
		genericName: 'diclofenac sodium',
		concentration: '1% (15 gm)',
		price: 11.25,
		matchKeywords: ['voltaren', 'emulgel', 'diclofenac', '1%', '15 gm', '#massage', '#nsaid'],
		usage: 'جل ديكلوفيناك موضعي لتخفيف ألم/التهاب العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.DICLOFENAC,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...NSAID_TOPICAL_WARNINGS],
	},

	// 107
	{
		id: 'massage-mobi-zome-gel-100gm',
		name: 'mobi zome 100 gm gel',
		genericName: 'menthol & camphor & eucalyptus',
		concentration: '100 gm',
		price: 120,
		matchKeywords: ['mobi zome', 'gel', 'menthol', 'camphor', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 108
	{
		id: 'massage-azotec-max-gel-100gm',
		name: 'azotec max gel 100 gm',
		genericName: 'tocopherol & laurocapram & menthol & eucalyptus',
		concentration: '100 gm',
		price: 199,
		matchKeywords: ['azotec max', 'gel', 'tocopherol', 'menthol', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم راحة العضلات والمفاصل.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 109
	{
		id: 'massage-emux-cream-50gm',
		name: 'emux cream 50 gm',
		genericName: 'emu oil & beeswax & clove oil & mineral oil & menthol',
		concentration: '50 gm',
		price: 56,
		matchKeywords: ['emux', 'cream', 'emu oil', 'beeswax', 'clove', 'menthol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 110
	{
		id: 'massage-eucal-cream-50gm',
		name: 'eucal cream 50 gm',
		genericName: 'eucalyptus globulus & gaultheria procumbens',
		concentration: '50 gm',
		price: 75,
		matchKeywords: ['eucal', 'cream 50', 'eucalyptus globulus', 'gaultheria', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 111
	{
		id: 'massage-intarget-gel-75gm',
		name: 'intarget gel 75 gm',
		genericName: 'equisetum arvense & menthol & thymus & vitamin e & eucalyptus',
		concentration: '75 gm',
		price: 70,
		matchKeywords: ['intarget', 'gel', 'menthol', 'thymus', 'eucalyptus', 'vitamin e', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 112
	{
		id: 'massage-cordalen-oil-spray-100ml',
		name: 'cordalen 100 ml oil spray',
		genericName: 'paraffinium liquidum & clove oil & menthol & peppermint',
		concentration: '100 ml',
		price: 100,
		matchKeywords: ['cordalen', 'oil spray', 'clove', 'menthol', 'peppermint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'سبراي/زيت مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 113
	{
		id: 'massage-maestro-cream-75gm',
		name: 'maestro cream 75 gm',
		genericName: 'methyl salicylate & eucalyptus oil & menthol & camphor',
		concentration: '75 gm',
		price: 55,
		matchKeywords: ['maestro', 'cream', 'methyl salicylate', 'eucalyptus', 'menthol', 'camphor', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 114
	{
		id: 'massage-rechamond-gel-60gm',
		name: 'rechamond gel 60 gm',
		genericName: 'menthol & camphor & isopropanol',
		concentration: '60 gm',
		price: 90,
		matchKeywords: ['rechamond', 'gel', 'menthol', 'camphor', 'isopropanol', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 115
	{
		id: 'massage-rontax-cream-50gm',
		name: 'rontax cream 50 gm',
		genericName: 'rosemary & lavender & avocado oil & grapefruit seed',
		concentration: '50 gm',
		price: 50,
		matchKeywords: ['rontax', 'cream', 'rosemary', 'lavender', 'avocado', 'grapefruit', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 116
	{
		id: 'massage-rontax-cream-75gm',
		name: 'rontax cream 75 gm',
		genericName: 'rosemary & lavender & avocado oil & grapefruit seed',
		concentration: '75 gm',
		price: 65,
		matchKeywords: ['rontax', 'cream 75', 'rosemary', 'lavender', 'avocado', 'grapefruit', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لدعم راحة العضلات.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 117
	{
		id: 'massage-urgent-cream-75gm',
		name: 'urgent cream 75 gm',
		genericName: 'capsicum annuum & camphor & menthol & methyl salicylate',
		concentration: '75 gm',
		price: 95,
		matchKeywords: ['urgent', 'cream 75', 'capsicum', 'camphor', 'menthol', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي (دفء) لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 118
	{
		id: 'massage-redomax-plus-gel',
		name: 'redomax plus gel',
		genericName: 'thyme oil & camphor oil & clove oil & peppermint oil',
		concentration: 'N/A',
		price: 48,
		matchKeywords: ['redomax plus', 'gel', 'thyme', 'camphor', 'clove', 'peppermint', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 119
	{
		id: 'massage-soojez-cream-50gm',
		name: 'soojez cream 50 gm',
		genericName: 'menthol & camphor & eucalyptus',
		concentration: '50 gm',
		price: 39,
		matchKeywords: ['soojez', 'cream', 'menthol', 'camphor', 'eucalyptus', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'كريم مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.TOPICAL_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},

	// 120
	{
		id: 'massage-yoster-gel-50gm',
		name: 'yoster gel 50 gm',
		genericName: 'camphor oil & menthol oil & methyl salicylate',
		concentration: '50 gm',
		price: 40,
		matchKeywords: ['yoster', 'gel', 'camphor', 'menthol', 'methyl salicylate', '#massage', 'مساج', 'تدليك', 'آلام عضلات'],
		usage: 'جل مساج موضعي لتخفيف آلام العضلات البسيطة.',
		timing: '٢–٣ مرات يومياً',
		category: Category.ANALGESICS,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 30,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في المنطقة المؤلمة ٢–٣ مرات يومياً'),
		warnings: [...COMMON_TOPICAL_MASSAGE_WARNINGS],
	},
];

export const MASSAGE_GROUP: Medication[] = dedupeByNameAndPriceKeepFirst(MASSAGE_GROUP_RAW);

