import { Category, Medication } from '../../types';

const fixed = (t: string) => () => t;

const COMMON_ORAL_CARE_WARNINGS = [
	'للاستخدام الخارجي داخل الفم فقط. لا يُبتلع.',
	'تجنب ملامسة العينين.',
	'أوقف الاستخدام إذا حدث تهيّج شديد/حساسية.',
];

const CHLORHEXIDINE_WARNINGS = [
	...COMMON_ORAL_CARE_WARNINGS,
	'قد يسبب تصبغاً مؤقتاً بالأسنان/اللسان وتغيراً في الطعم مع الاستخدام لفترات طويلة.',
	'لا تزيد على ٧–١٤ يوماً متواصلة؛ إن لزم أكثر: راجع طبيب أسنان (خطر تصبغ/تغيّر طعم).',
	'لا تستخدمه مباشرة بعد معجون الأسنان؛ اترك فاصل ٣٠ دقيقة لتجنب تقليل الفاعلية.',
];

const LOCAL_ANESTHETIC_GEL_WARNINGS = [
	...COMMON_ORAL_CARE_WARNINGS,
	'يُستخدم بكمية صغيرة. تجنب الأكل/الشرب الساخن حتى زوال التخدير لتفادي العض/الحرق.',
	'الأطفال أقل من سنتين: كمية صغيرة جداً (حجم حبة الأرز) على موضع واحد؛ تجنب البلع.',
];

export const ORAL_CARE_GROUP: Medication[] = [
	// 1
	{
		id: 'hexitol-chlorhexidine-mouthwash-1-25mgml-100ml',
		name: 'hexitol 1.25mg/ml mouth wash 100 ml',
		genericName: 'chlorhexidine',
		concentration: '1.25 mg/ml (100 ml)',
		price: 49.9,
		matchKeywords: ['hexitol', 'chlorhexidine', 'mouth wash', 'mouthwash', 'غسول فم', 'مطهر', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر (كلورهكسيدين) للمساعدة في التهاب اللثة ورائحة الفم بعد إجراءات الأسنان.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 2
	{
		id: 'orovex-clove-mouthwash-250ml',
		name: 'orovex clove mouth wash 250 ml',
		genericName: 'thymol & menthol & glycerin',
		concentration: '250 ml',
		price: 85,
		matchKeywords: ['orovex', 'clove', 'mouth wash', 'thymol', 'menthol', 'غسول فم', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم منعش للمساعدة في رائحة الفم وتقليل البكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 3
	{
		id: 'orovex-delicate-mouthwash-250ml',
		name: 'orovex delicate mouth wash 250 ml',
		genericName: 'thymol & menthol & glycerin',
		concentration: '250 ml',
		price: 90,
		matchKeywords: ['orovex', 'delicate', 'mouth wash', 'thymol', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم لطيف للمساعدة في العناية اليومية ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 4
	{
		id: 'orovex-orange-mouthwash-250ml',
		name: 'orovex mouth wash orange 250 ml',
		genericName: 'thymol & menthol & glycerin',
		concentration: '250 ml',
		price: 85,
		matchKeywords: ['orovex', 'orange', 'mouth wash', 'thymol', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم منعش للمساعدة في رائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 5
	{
		id: 'orovex-smokers-mouthwash-250ml',
		name: 'orovex smokers mouth wash 250 ml',
		genericName: 'thymol & menthol & glycerin',
		concentration: '250 ml',
		price: 90,
		matchKeywords: ['orovex', 'smokers', 'mouth wash', 'thymol', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم للمساعدة في رائحة الفم (مناسب للمدخنين) حسب الاستخدام.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 6
	{
		id: 'b-fresh-cpc-mouthwash-0-05pct-250ml',
		name: 'b-fresh 0.05% mouthwash 250 ml',
		genericName: 'cetylpyridinium chloride',
		concentration: '0.05% (250 ml)',
		price: 27,
		matchKeywords: ['b-fresh', 'cetylpyridinium', 'CPC', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر (CPC) للمساعدة في تقليل رائحة الفم والبكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 7
	{
		id: 'b-fresh-cpc-mouthwash-0-05pct-500ml',
		name: 'b-fresh 0.05% mouthwash 500 ml',
		genericName: 'cetylpyridinium chloride',
		concentration: '0.05% (500 ml)',
		price: 37,
		matchKeywords: ['b-fresh', '500ml', 'cetylpyridinium', 'CPC', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر (CPC) للمساعدة في تقليل رائحة الفم والبكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 8
	{
		id: 'dg-wash-chlorhexidine-mouthwash-menthol-125ml',
		name: 'dg-wash mouth wash menthol 125 ml',
		genericName: 'chlorhexidine',
		concentration: '125 ml',
		price: 35,
		matchKeywords: ['dg-wash', 'chlorhexidine', 'menthol', 'mouth wash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر (كلورهكسيدين) للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 9
	{
		id: 'omit-c-mouth-spray-60ml',
		name: 'omit-c mouth spray 60ml',
		genericName: 'menthol & thymol & vitamin c & cetrimide & chlorhexidine gluconate',
		concentration: '60 ml',
		price: 45,
		matchKeywords: ['omit-c', 'mouth spray', 'chlorhexidine', 'cetrimide', 'thymol', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم للمساعدة في إنعاش النفس وتقليل البكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 10
	{
		id: 'oracure-oral-gel-30gm',
		name: 'oracure oral gel 30 gm',
		genericName: 'lidocaine hydrochloride & cetylpyridinium chloride',
		concentration: '30 gm',
		price: 24,
		matchKeywords: ['oracure', 'oral gel', 'lidocaine', 'cetylpyridinium', 'pain', 'قرح فم', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'جل للفم لتخفيف ألم/تهيج الفم واللثة (مخدر موضعي + مطهر).',
		timing: '٢–٣ مرات يومياً',
		category: Category.MOUTH_THROAT,
		form: 'Gel',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة على المنطقة المصابة ٢–٣ مرات يومياً'),
		warnings: [...LOCAL_ANESTHETIC_GEL_WARNINGS],
	},

	// 11
	{
		id: 'dg-wash-clove-mouthwash-125ml',
		name: 'dg-wash clove mouth wash 125ml',
		genericName: 'chlorhexidine & clove oil & propolis',
		concentration: '125 ml',
		price: 35,
		matchKeywords: ['dg-wash', 'clove', 'propolis', 'chlorhexidine', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر (كلورهكسيدين) مع القرنفل للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 12
	{
		id: 'oramax-mouth-spray-30ml',
		name: 'oramax mouth spray 30 ml',
		genericName: 'propylene glycol & ethanol & surfactants',
		concentration: '30 ml',
		price: 59.5,
		matchKeywords: ['oramax', 'mouth spray', 'oral spray', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم للمساعدة في إنعاش النفس وتقليل البكتيريا السطحية حسب الاستخدام.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 13
	{
		id: 'oramax-pediatrics-mouth-spray-30ml',
		name: 'oramax pediatrics mouth spray 30 ml',
		genericName: 'clove oil & sage oil & myrrh oil & peppermint oil',
		concentration: '30 ml',
		price: 59.5,
		matchKeywords: ['oramax pediatrics', 'kids', 'mouth spray', 'clove', 'sage', 'myrrh', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي فم للأطفال (مستخلصات) للمساعدة في إنعاش النفس وتهدئة تهيج بسيط حسب الاستخدام.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 24,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 14
	{
		id: 'orovex-h-mouthwash-150ml',
		name: 'orovex-h mouth wash 150 ml',
		genericName: 'thymol & menthol & glycerin',
		concentration: '150 ml',
		price: 150,
		matchKeywords: ['orovex-h', 'mouth wash', 'thymol', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم للمساعدة في العناية اليومية ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 15
	{
		id: 'orovex-mouthwash-120ml',
		name: 'orovex mouth wash 120 ml',
		genericName: 'thymol & menthol & glycerin',
		concentration: '120 ml',
		price: 45,
		matchKeywords: ['orovex', '120ml', 'mouth wash', 'thymol', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم للمساعدة في رائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 16
	{
		id: 'jogel-oral-gel-20gm',
		name: 'jogel oral gel 20 gm',
		genericName: 'jojoba oil & lidocaine hydrochloride',
		concentration: '20 gm',
		price: 7,
		matchKeywords: ['jogel', 'oral gel', 'lidocaine', 'jojoba', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'جل للفم لتخفيف ألم/تهيج الفم واللثة (مخدر موضعي).',
		timing: '٢–٣ مرات يومياً',
		category: Category.MOUTH_THROAT,
		form: 'Gel',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة على المنطقة المصابة ٢–٣ مرات يومياً'),
		warnings: [...LOCAL_ANESTHETIC_GEL_WARNINGS],
	},

	// 17
	{
		id: 'listerine-cool-mint-mouthwash-250ml',
		name: 'listerine cool mint mouth wash 250 ml',
		genericName: 'mouthwash',
		concentration: '250 ml',
		price: 138,
		matchKeywords: ['listerine', 'cool mint', 'mouth wash', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم منعش للمساعدة في رائحة الفم والعناية اليومية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 18
	{
		id: 'dg-wash-fluoride-mouthwash-125ml',
		name: 'dg-wash fluoride mouth wash 125ml',
		genericName: 'beepropolis & fluoride & menthol crystals',
		concentration: '125 ml',
		price: 35,
		matchKeywords: ['dg-wash', 'fluoride', 'propolis', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم يحتوي فلورايد للمساعدة في تقليل التسوس والعناية اليومية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 19
	{
		id: 'gum-c-mouthwash-120ml',
		name: 'gum-c mouth wash 120 ml',
		genericName: 'thyme extract & menthol & clove oil & vitamin c & glycerin',
		concentration: '120 ml',
		price: 29.5,
		matchKeywords: ['gum-c', 'thyme', 'clove', 'vitamin c', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم منعش للمساعدة في رائحة الفم والعناية اليومية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 20
	{
		id: 'listerine-mouthwash-250ml',
		name: 'listerine mouth wash 250 ml',
		genericName: 'mouthwash',
		concentration: '250 ml',
		price: 120,
		matchKeywords: ['listerine', 'mouth wash', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم منعش للمساعدة في رائحة الفم والعناية اليومية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 21
	{
		id: 'moony-mouthwash-120ml',
		name: 'moony mouth wash 120 ml',
		genericName: 'mouthwash',
		concentration: '120 ml',
		price: 49,
		matchKeywords: ['moony', 'mouth wash', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم للعناية اليومية ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 22
	{
		id: 'oracin-mouthwash-120ml',
		name: 'oracin mouth wash 120 ml',
		genericName: 'tegosorb & thymol & chlorhexidine & eugenol & menthol',
		concentration: '120 ml',
		price: 49,
		matchKeywords: ['oracin', 'mouth wash', 'chlorhexidine', 'thymol', 'eugenol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 23
	{
		id: 'unihalox-soothing-spray-30ml',
		name: 'unihalox soothing 30 ml spray',
		genericName: 'sea water & menthol & vitamin e & hyaluronic acid',
		concentration: '30 ml',
		price: 90,
		matchKeywords: ['unihalox', 'soothing', 'spray', 'hyaluronic acid', 'menthol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي مهدئ للفم/الحلق لدعم الترطيب وتهدئة التهيج البسيط.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 48,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 24
	{
		id: 'oracin-verde-mouthwash-125ml',
		name: 'oracin verde mouth wash 125ml',
		genericName: 'tegosorb & thymol & chlorhexidine & eugenol & menthol',
		concentration: '125 ml',
		price: 49,
		matchKeywords: ['oracin verde', 'chlorhexidine', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 25
	{
		id: 'gengigel-mouthrinse-mouthwash-150ml',
		name: 'gengigel mouthrinse mouth wash 150 ml',
		genericName: 'hyaluronan',
		concentration: '150 ml',
		price: 350,
		matchKeywords: ['gengigel', 'hyaluronan', 'mouthrinse', 'gum', 'mouth wash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم (هيالورونان) لدعم التئام اللثة وتهدئة التهيج بعد إجراءات الأسنان.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 26
	{
		id: 'listermix-plus-mouthwash-250ml',
		name: 'listermix plus mouth wash 250ml',
		genericName: 'chlorhexidine & thymol & eucalyptol & menthol & clove oil',
		concentration: '250 ml',
		price: 75,
		matchKeywords: ['listermix plus', 'chlorhexidine', 'eucalyptol', 'clove', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 27
	{
		id: 'no-plac-mouthwash-250ml',
		name: 'no plac mouth wash 250 ml',
		genericName: 'chlorhexidine & sodium monofluorophosphate',
		concentration: '250 ml',
		price: 65,
		matchKeywords: ['no plac', 'chlorhexidine', 'fluoride', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر مع فلورايد للعناية باللثة وتقليل البكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 28
	{
		id: 'parodontax-mouthwash-300ml',
		name: 'parodontax mouth wash 300ml',
		genericName: 'chlorhexidine & sodium fluoride',
		concentration: '300 ml',
		price: 45,
		matchKeywords: ['parodontax', 'chlorhexidine', 'fluoride', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر مع فلورايد لدعم صحة اللثة وتقليل البكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Mouthwash',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 29
	{
		id: 'pedro-mouth-spray-60ml',
		name: 'pedro mouth spray 60 ml',
		genericName: 'clove & menthol & chamomile & tea tree oil',
		concentration: '60 ml',
		price: 70,
		matchKeywords: ['pedro', 'mouth spray', 'clove', 'menthol', 'chamomile', 'tea tree', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم لإنعاش النفس ودعم العناية اليومية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 30
	{
		id: 'pepriclo-mouth-spray-50ml',
		name: 'pepriclo mouth spray 50 ml',
		genericName: 'clove oil & thymol & chamomile extract & menthol & green tea',
		concentration: '50 ml',
		price: 75,
		matchKeywords: ['pepriclo', 'mouth spray', 'clove', 'thymol', 'green tea', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم لإنعاش النفس ودعم العناية اليومية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 31
	{
		id: 'texor-care-oral-solution-50ml',
		name: 'texor care oral solution 50ml',
		genericName: 'chlorhexidine & slippery elm & glycerin',
		concentration: '50 ml',
		price: 89,
		matchKeywords: ['texor care', 'oral solution', 'chlorhexidine', 'slippery elm', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'محلول فموي للعناية بالفم وتهدئة التهيج (يُستخدم حسب العبوة).',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Solution',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 32
	{
		id: 'flurodam-mouth-spray',
		name: 'flurodam mouth spray',
		genericName: 'camphor & menthol & clove & chlorhexidine',
		concentration: 'N/A',
		price: 55,
		matchKeywords: ['flurodam', 'mouth spray', 'camphor', 'menthol', 'clove', 'chlorhexidine', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم للمساعدة في إنعاش النفس وتقليل البكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 33
	{
		id: 'oromap-spray-60ml',
		name: 'oromap spray 60ml',
		genericName: 'clove oil & hyaluronic acid & menthol & eucalyptus oil & chlorhexidine',
		concentration: '60 ml',
		price: 59,
		matchKeywords: ['oromap', 'oral fresh', 'spray', 'hyaluronic acid', 'clove', 'eucalyptus', 'chlorhexidine', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم لإنعاش النفس وتهدئة التهيج البسيط حسب الاستخدام.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 34
	{
		id: 'oracin-mouthwash-240ml',
		name: 'oracin mouth wash 240ml',
		genericName: 'tegosorb & thymol & chlorhexidine & eugenol & menthol',
		concentration: '240 ml',
		price: 64,
		matchKeywords: ['oracin', '240ml', 'chlorhexidine', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Mouthwash',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 35
	{
		id: 'oracure-oral-gel-15gm',
		name: 'oracure oral gel 15 gm',
		genericName: 'lidocaine hydrochloride & cetylpyridinium chloride',
		concentration: '15 gm',
		price: 17,
		matchKeywords: ['oracure', '15gm', 'oral gel', 'lidocaine', 'cetylpyridinium', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'جل للفم لتخفيف ألم/تهيج الفم واللثة (مخدر موضعي + مطهر).',
		timing: '٢–٣ مرات يومياً',
		category: Category.MOUTH_THROAT,
		form: 'Gel',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة على المنطقة المصابة ٢–٣ مرات يومياً'),
		warnings: [...LOCAL_ANESTHETIC_GEL_WARNINGS],
	},

	// 36
	{
		id: 'orasan-mouthwash-125ml',
		name: 'orasan mouth wash 125 ml',
		genericName: 'clove oil & menthol',
		concentration: '125 ml',
		price: 45,
		matchKeywords: ['orasan', 'clove', 'menthol', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم منعش للمساعدة في رائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Mouthwash',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},

	// 37
	{
		id: 'nody-orax-mouth-spray-60ml',
		name: 'nody orax mouth spray 60 ml',
		genericName: 'clove oil & menthol oil & chlorhexidine & cinnamon oil',
		concentration: '60 ml',
		price: 50,
		matchKeywords: ['nody orax', 'mouth spray', 'clove', 'menthol', 'cinnamon', 'chlorhexidine', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم لإنعاش النفس وتقليل البكتيريا السطحية.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 38
	{
		id: 'yago-mouthwash-250ml',
		name: 'yago mouth wash 250 ml',
		genericName: 'chlorhexidine & cetrimide & clove oil & menthol & eucalyptol',
		concentration: '250 ml',
		price: 55,
		matchKeywords: ['yago', 'mouth wash', 'chlorhexidine', 'cetrimide', 'eucalyptol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر للمساعدة في التهاب اللثة ورائحة الفم.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Mouthwash',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 39
	{
		id: 'atrosmen-mouthwash-250ml',
		name: 'atrosmen mouth wash 250 ml',
		genericName: 'hydrogen peroxide & chlorhexidine & fluoride',
		concentration: '250 ml',
		price: 70,
		matchKeywords: ['atrosmen', 'hydrogen peroxide', 'chlorhexidine', 'fluoride', 'mouthwash', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'غسول فم مطهر للمساعدة في التهاب اللثة ورائحة الفم (حسب الاستخدام).',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Mouthwash',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...CHLORHEXIDINE_WARNINGS],
	},

	// 40
	{
		id: 'corsoden-oral-spray-30ml',
		name: 'corsoden oral spray 30 ml',
		genericName: 'chlorhexidine & menthol & lidocaine & clove extract & chamomile',
		concentration: '30 ml',
		price: 25,
		matchKeywords: ['corsoden', 'oral spray', 'chlorhexidine', 'lidocaine', 'clove', 'chamomile', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي للفم لتخفيف الألم وتهدئة التهيج (مطهر + مخدر موضعي).',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...LOCAL_ANESTHETIC_GEL_WARNINGS],
	},

	// 41
	{
		id: 'octe-macro-oral-spray-30ml',
		name: 'octe macro oral spray 30 ml',
		genericName: 'octenidine & eucalyptol & methyl salicylate & thymol',
		concentration: '30 ml',
		price: 55,
		matchKeywords: ['octe macro', 'octenidine', 'oral spray', 'thymol', 'eucalyptol', '#oral_care', 'فم', 'أسنان', 'لثة', 'oral', 'teeth', 'gum'],
		usage: 'سبراي مطهر للفم/الحلق للمساعدة في تقليل البكتيريا السطحية وتهدئة تهيج بسيط.',
		timing: 'مرتين يومياً بعد الأكل',
		category: Category.MOUTH_THROAT,
		form: 'Spray',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('مرتين يومياً بعد الأكل'),
		warnings: [...COMMON_ORAL_CARE_WARNINGS],
	},
];

