import { Medication, Category } from '../../../types';

const TAGS = {
  osteoarthritis: ['osteoarthritis', '#osteoarthritis', 'OA', 'خشونة', 'خشونة المفاصل'],
  painRelief: ['pain relief', '#pain relief', 'pain', 'مسكن', 'ألم'],
  antirheumatic: ['antirheumatic', '#antirheumatic', 'anti-rheumatic', 'روماتيزم', 'مضاد روماتيزم'],
  immunosuppressive: ['immunosuppressive', '#immunosuppressive', 'immunomodulating', 'مثبط مناعة'],
  cartilage: ['cartilage', '#cartilage', 'joint', 'joints', 'غضاريف', 'مفاصل'],
};

const commonOAWarnings = [
  'الحمل/الرضاعة: يُستخدم عند الضرورة فقط؛ أقل جرعة وأقصر مدة.',
  'إذا لديك حساسية من مشتقات بحرية/محار: تجنب منتجات الجلوكوزامين من المحار.',
];

export const OSTEOARTHRITIS_ANTI_RHEUMATIC_2: Medication[] = [
  // 1) joflex 500mg 30 caps.
  {
    id: 'joflex-glucosamine-sulfate-500mg-caps-30',
    name: 'joflex 500mg 30 caps.',
    genericName: 'glucosamine sulfate',
    concentration: '500mg',
    price: 69,
    matchKeywords: ['joflex', 'جوفليكس', 'glucosamine sulfate', 'glucosamine', ...TAGS.osteoarthritis, ...TAGS.cartilage],
    usage: 'مكمل لدعم الغضاريف وتخفيف أعراض خشونة المفاصل كعلاج مساعد.',
    timing: 'يُستخدم يومياً حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'غالباً 1–3 كبسولات يومياً بعد الأكل أو حسب التشخيص والحالة.',
    warnings: [...commonOAWarnings],
  },

  // 2) remazamin 20 tabs
  {
    id: 'remazamin-calcium-fructoborate-glucosamine-chondroitin-msm-vitd-hyaluronic-acid-tabs-20',
    name: 'remazamin 20 tabs',
    genericName: 'calcium fructoborate & glucosamine & chondroitin & msm & vitamin d & hyaluronic acid',
    concentration: 'Tablets',
    price: 285,
    matchKeywords: ['remazamin', 'ريمازامين', 'calcium fructoborate', 'glucosamine', 'chondroitin', 'msm', 'vitamin d', 'hyaluronic acid', ...TAGS.osteoarthritis, ...TAGS.cartilage],
    usage: 'مكمل لدعم المفاصل والغضاريف في خشونة المفاصل كعلاج مساعد.',
    timing: 'يُستخدم يومياً حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'غالباً قرص 1–2 يومياً بعد الأكل أو حسب التشخيص والحالة.',
    warnings: [...commonOAWarnings],
  },

  // 3) orthomeric powder 10 sachets
  {
    id: 'orthomeric-msm-glucosamine-turmeric-collagen-sachets-10',
    name: 'orthomeric powder 10 sachets',
    genericName: 'msm & glucosamine & turmeric & collagen',
    concentration: 'Sachets',
    price: 329,
    matchKeywords: ['orthomeric', 'اورثوميريك', 'msm', 'glucosamine', 'turmeric', 'collagen', ...TAGS.painRelief, ...TAGS.osteoarthritis, ...TAGS.cartilage],
    usage: 'مكمل لدعم المفاصل وقد يساعد في تقليل ألم الخشونة كعلاج مساعد.',
    timing: 'مرة يومياً أو حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'غالباً كيس واحد يومياً بعد الأكل أو حسب التشخيص والحالة.',
    warnings: [...commonOAWarnings, 'الكركم قد يزيد سيولة الدم مع مميعات الدم: راجع الجرعة والتداخلات.'],
  },

  // 4) gluohoriz 30 tabs
  {
    id: 'gluohoriz-boron-hyaluronic-acid-glucosamin-chondroitin-tabs-30',
    name: 'gluohoriz 30 tabs',
    genericName: 'boron & hyaluronic acid & glucosamin & chondroitin',
    concentration: 'Tablets',
    price: 390,
    matchKeywords: ['gluohoriz', 'جلوهورايز', 'boron', 'hyaluronic acid', 'glucosamin', 'chondroitin', ...TAGS.osteoarthritis, ...TAGS.cartilage],
    usage: 'مكمل لدعم المفاصل والغضاريف في حالات الخشونة كعلاج مساعد.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'غالباً قرص واحد يومياً بعد الأكل أو حسب التشخيص والحالة.',
    warnings: [...commonOAWarnings],
  },

  // 5) hyalotoco 30 caps
  {
    id: 'hyalotoco-hyaluronic-acid-collagen-vitamin-c-vitamin-e-caps-30',
    name: 'hyalotoco 30 caps',
    genericName: 'hyaluronic acid & collagen & vitamin c & vitamin e',
    concentration: 'Capsules',
    price: 180,
    matchKeywords: ['hyalotoco', 'هيالوتوكو', 'hyaluronic acid', 'collagen', 'vitamin c', 'vitamin e', ...TAGS.osteoarthritis, ...TAGS.cartilage],
    usage: 'مكمل لدعم المفاصل والغضاريف كعلاج مساعد.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'غالباً كبسولة واحدة يومياً بعد الأكل أو حسب التشخيص والحالة.',
    warnings: [...commonOAWarnings],
  },

  // 6) matricoga 30 tabs.
  {
    id: 'matricoga-glucosamine-chondroitin-collagen-folic-acid-vitd3-tabs-30',
    name: 'matricoga 30 tabs.',
    genericName: 'glucosamine & chondroitin & collagen & folic acid & vitamin d3',
    concentration: 'Tablets',
    price: 230,
    matchKeywords: ['matricoga', 'ماتريكوجا', 'glucosamine', 'chondroitin', 'collagen', 'folic acid', 'vitamin d3', ...TAGS.osteoarthritis, ...TAGS.cartilage],
    usage: 'مكمل لدعم المفاصل والغضاريف كعلاج مساعد في الخشونة.',
    timing: 'حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'غالباً قرص واحد يومياً بعد الأكل أو حسب التشخيص والحالة.',
    warnings: [...commonOAWarnings],
  },

  // 7) arthfree 20mg 30 f.c. tab.
  {
    id: 'arthfree-leflunomide-20mg-fc-tabs-30',
    name: 'arthfree 20mg 30 f.c. tab.',
    genericName: 'leflunomide',
    concentration: '20mg',
    price: 261,
    matchKeywords: ['arthfree', 'ارثفري', 'leflunomide', ...TAGS.immunosuppressive, ...TAGS.antirheumatic],
    usage: 'دواء مضاد للروماتيزم (DMARD) مثبط مناعة لعلاج الروماتويد حسب التشخيص.',
    timing: 'مرة يومياً حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'حسب التشخيص والحالة: غالباً قرص 20mg مرة يومياً. قد يلزم جرعة تحميل/بدء حسب الحالة.',
    warnings: [
      'ممنوع في الحمل: يسبب تشوهات جنينية ويستلزم منع حمل فعال (للرجال والنساء) حسب البروتوكول.',
      'تحذيرات: خطر تسمم كبدي/ارتفاع إنزيمات كبد—يلزم تحاليل دورية. تجنب الكحول.',
      'تحذيرات: قد يسبب نقص كريات الدم/عدوى—أعد التقييم عند حرارة/التهاب حلق/كدمات غير مبررة.',
      'تداخلات: لا يُجمع مع أدوية كبدية/مثبطات مناعة أخرى إلا حسب التشخيص. راجع تداخلات المريض.',
    ],
  },

  // 8) apetoid 20mg 30 f.c.tab.
  {
    id: 'apetoid-leflunomide-20mg-fc-tabs-30',
    name: 'apetoid 20mg 30 f.c.tab.',
    genericName: 'leflunomide',
    concentration: '20mg',
    price: 180,
    matchKeywords: ['apetoid', 'ابيتويد', 'leflunomide', ...TAGS.immunosuppressive, ...TAGS.antirheumatic],
    usage: 'دواء مضاد للروماتيزم (DMARD) مثبط مناعة حسب التشخيص.',
    timing: 'مرة يومياً حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'حسب التشخيص والحالة: غالباً قرص 20mg مرة يومياً.',
    warnings: [
      'ممنوع في الحمل: يسبب تشوهات جنينية. استخدم منع حمل فعال حسب التشخيص.',
      'تحذيرات: متابعة كبد وصورة دم دورياً. تجنب الكحول.',
      'تحذيرات: أعد التقييم عند أعراض عدوى/نزيف/كدمات أو اصفرار العين.',
    ],
  },

  // 9) avara 20mg 30 f.c.tab.
  {
    id: 'avara-leflunomide-20mg-fc-tabs-30',
    name: 'avara 20mg 30 f.c.tab.',
    genericName: 'leflunomide',
    concentration: '20mg',
    price: 483,
    matchKeywords: ['avara', 'افارا', 'leflunomide', ...TAGS.immunosuppressive, ...TAGS.antirheumatic],
    usage: 'دواء مضاد للروماتيزم (DMARD) مثبط مناعة حسب التشخيص.',
    timing: 'مرة يومياً حسب التشخيص والحالة.',
    category: Category.ANTI_RHEUMATIC_OSTEOARTHRITIS,
    form: 'F.C. Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 50,
    maxWeight: 250,
    calculationRule: () => 'حسب التشخيص والحالة: غالباً قرص 20mg مرة يومياً.',
    warnings: [
      'ممنوع في الحمل: يسبب تشوهات جنينية ويستلزم منع حمل فعال.',
      'تحذيرات: خطر تسمم كبدي—تحاليل دورية وتجنب الكحول.',
      'تحذيرات: قد يزيد قابلية العدوى—أعد التقييم عند حرارة/سعال مستمر.',
    ],
  },
];

