import { Medication, Category } from '../../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const BASE_WARNINGS = [
  'قد يسبب دوخة/صداع أو اضطراب بالمعدة.',
  'لا تُوقِف الدواء فجأة.',
];

const CHOLINESTERASE_WARNINGS = [
  ...BASE_WARNINGS,
  'قد يسبب غثيان/إسهال أو فقدان شهية خاصة عند البداية.',
  'قد يبطئ ضربات القلب لدى بعض المرضى؛ يُستخدم بحذر مع أمراض القلب أو الإغماء.',
];

const MEMANTINE_WARNINGS = [
  ...BASE_WARNINGS,
  'قد يسبب دوخة/إمساك؛ غالباً يبدأ تدريجياً لتقليل الأعراض.',
];

export const DEMENTIA_DRUGS: Medication[] = [
  // 1
  {
    id: 'cerebrolysin-215-2mg-ml-5ml-5-amps-dem',
    name: 'cerebrolysin 215.2mg/ml 5ml (5 amps)',
    genericName: 'cerebrolysin',
    concentration: '215.2mg/ml',
    price: 550,
    matchKeywords: ['cerebrolysin', 'cerebrolysin 5ml', 'cerebrolysin ampoule', 'سيريبروليسين', 'حقن', 'memory', 'cognitive', 'dementia', 'alzheimers', 'alzheimer', 'الخرف', 'الزهايمر', '#nootropic'],
    usage: 'داعم وظيفي/عصبي في حالات ضعف الذاكرة والخرف.',
    timing: 'مرة يومياً حقن – ٥ أيام',
    category: Category.DEMENTIA,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('أمبول ٥ مل حقن وريدي/عضلي يومياً بدون اعتبار للأكل – لمدة ٥ أيام (كورس قصير).'),
    warnings: ['قد يسبب ألم موضعي بالحقن أو حساسية نادرة.'],
  },

  // 2
  {
    id: 'alzmenda-10mg-21-fc-tabs-dem',
    name: 'alzmenda 10mg 21 f.c. tab.',
    genericName: 'memantine hydrochloride',
    concentration: '10mg',
    price: 78,
    matchKeywords: ['alzmenda 10', 'memantine 10', 'ميمانتين', 'الزمندا', 'alzheimers', 'dementia', '#nootropic'],
    usage: 'لعلاج أعراض ألزهايمر المتوسط إلى الشديد (ميمانتين).',
    timing: 'مرة–مرتين يومياً بدون اعتبار للأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٠ مجم بتدرج أسبوعي بدون اعتبار للأكل: أسبوع ١: ٥ مجم صباحاً (نصف قرص). أسبوع ٢: ١٠ مجم صباحاً. أسبوع ٣: ١٠ مجم صباحاً + ٥ مجم مساءً. أسبوع ٤+: ١٠ مجم مرتين يومياً (٢٠ مجم/يوم) – علاج مزمن.'),
    warnings: MEMANTINE_WARNINGS,
  },

  // 3
  {
    id: 'alzmenda-drops-10mg-g-20ml-dem',
    name: 'alzmenda oral drops 10mg/gm 20 ml',
    genericName: 'memantine hydrochloride',
    concentration: '10mg/g',
    price: 55,
    matchKeywords: ['alzmenda drops', 'memantine drops', 'نقط', 'الزمندا نقط', 'ميمانتين نقط', '#nootropic'],
    usage: 'ميمانتين نقط للفم لأعراض ألزهايمر (بديل عند صعوبة البلع).',
    timing: 'مرة–مرتين يومياً بدون اعتبار للأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Oral Drops',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('نقط فموية بنفس تدرج الميمانتين بدون اعتبار للأكل: أسبوع ١: ٥ مجم يومياً. أسبوع ٢: ١٠ مجم يومياً. أسبوع ٣: ١٥ مجم/يوم. أسبوع ٤+: ٢٠ مجم/يوم – علاج مزمن.'),
    warnings: MEMANTINE_WARNINGS,
  },

  // 4
  {
    id: 'cerebrolysin-215-2mg-ml-1ml-10-amps-dem',
    name: 'cerebrolysin 215.2mg/ml 1ml (10 amps)',
    genericName: 'cerebrolysin',
    concentration: '215.2mg/ml',
    price: 240,
    matchKeywords: ['cerebrolysin 1ml', 'cerebrolysin ampoule 1ml', 'سيريبروليسين ١ مل', 'حقن', 'memory', 'dementia', 'alzheimers', '#nootropic'],
    usage: 'داعم وظيفي/عصبي في حالات ضعف الذاكرة والخرف.',
    timing: 'مرة يومياً حقن – ١٠ أيام',
    category: Category.DEMENTIA,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('أمبول ١ مل حقن وريدي/عضلي يومياً بدون اعتبار للأكل – لمدة ١٠ أيام (كورس قصير).'),
    warnings: ['قد يسبب ألم موضعي أو حساسية نادرة.'],
  },

  // 5
  {
    id: 'lidemtzil-5mg-30-odt-tabs-dem',
    name: 'lidemtzil 5mg 30 orally disp. tabs.',
    genericName: 'donepezil hydrochloride',
    concentration: '5mg',
    price: 78,
    matchKeywords: ['lidemtzil 5', 'lidemtzil', 'donepezil 5', 'donepezil', 'دونيبيزيل', 'ليديمتزِل', 'odt', 'orodispersible', 'alzheimers', 'alzheimer', 'dementia', 'الزهايمر', 'الخرف', '#nootropic'],
    usage: 'لعلاج أعراض ألزهايمر الخفيف إلى المتوسط (دونيبيزيل).',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Orodispersible Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص يتفتت بالفم ٥ مجم مساءً قبل النوم لمدة ٤–٦ أسابيع، ثم ١٠ مجم مساءً قبل النوم – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 6
  {
    id: 'stimulan-200mg-ml-120ml-syrup-dem',
    name: 'stimulan 200mg/ml 120ml syrup',
    genericName: 'piracetam',
    concentration: '200mg/ml',
    price: 54,
    matchKeywords: ['stimulan syrup', 'stimulan', 'piracetam syrup', 'piracetam 200mg/ml', 'بيراسيتام شراب', 'ستيمولان', 'memory', 'cognitive', 'dementia', 'alzheimers', '#nootropic'],
    usage: 'داعم وظيفي للذاكرة/القدرات الإدراكية (بيراسيتام).',
    timing: 'كل ٨ ساعات بدون اعتبار للأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Syrup',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('للبالغين: ٤–٨ مل شراب ٣ مرات يومياً بدون اعتبار للأكل (٢٫٤–٤٫٨ جم/يوم بتركيز ٢٠٠ مجم/مل) – علاج مزمن مع تقييم دوري.'),
    warnings: ['قد يسبب غثيان أو صداع. يُستخدم بحذر مع اضطرابات النزف أو مرضى الكلى.'],
  },

  // 7
  {
    id: 'mixmazil-14-10mg-28-mr-caps-dem',
    name: 'mixmazil 14/10 mg 28 ext. rel. caps.',
    genericName: 'memantine hydrochloride + donepezil hydrochloride',
    concentration: '14/10mg',
    price: 265,
    matchKeywords: ['mixmazil 14/10', 'memantine donepezil', 'مزيمازيل', 'combo', '#nootropic'],
    usage: 'تركيبة ميمانتين + دونيبيزيل لعلاج أعراض ألزهايمر.',
    timing: 'مرة يومياً مساءً – مزمن',
    category: Category.DEMENTIA,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة ممتدة المفعول واحدة يومياً مساءً بدون اعتبار للأكل – علاج مزمن.'),
    warnings: [...CHOLINESTERASE_WARNINGS, ...MEMANTINE_WARNINGS],
  },

  // 8
  {
    id: 'mixmazil-28-10mg-28-mr-caps-dem',
    name: 'mixmazil 28/10 mg 28 ext. rel. caps.',
    genericName: 'memantine hydrochloride + donepezil hydrochloride',
    concentration: '28/10mg',
    price: 320,
    matchKeywords: ['mixmazil 28/10', 'memantine donepezil 28/10', 'مزيمازيل ٢٨/١٠', 'combo', '#nootropic'],
    usage: 'تركيبة ميمانتين + دونيبيزيل لعلاج أعراض ألزهايمر.',
    timing: 'مرة يومياً مساءً – مزمن',
    category: Category.DEMENTIA,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة ممتدة المفعول واحدة يومياً مساءً بدون اعتبار للأكل – علاج مزمن.'),
    warnings: [...CHOLINESTERASE_WARNINGS, ...MEMANTINE_WARNINGS],
  },

  // 9
  {
    id: 'aricept-5mg-14-tabs-dem',
    name: 'aricept 5mg 14 tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '5mg',
    price: 75,
    matchKeywords: ['aricept 5', 'aricept', 'donepezil 5', 'donepezil', 'أريسبت', 'دونيبيزيل', 'alzheimers', 'alzheimer', 'dementia', 'الزهايمر', 'الخرف', '#nootropic'],
    usage: 'لعلاج أعراض ألزهايمر الخفيف إلى المتوسط (دونيبيزيل).',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٥ مجم مساءً قبل النوم بدون اعتبار للأكل لمدة ٤–٦ أسابيع، ثم ١٠ مجم مساءً – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 10
  {
    id: 'aricept-5mg-7-tabs-dem',
    name: 'aricept 5mg 7 tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '5mg',
    price: 40,
    matchKeywords: ['aricept 5 7', 'donepezil', 'أريسبت ٧', '#nootropic'],
    usage: 'دونيبيزيل لعلاج أعراض ألزهايمر.',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٥ مجم مساءً قبل النوم بدون اعتبار للأكل (جرعة البداية) – علاج مزمن مع التدرج.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 11
  {
    id: 'donhimer-5mg-30-fc-tabs-dem',
    name: 'donhimer 5mg 30 f.c. tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '5mg',
    price: 78,
    matchKeywords: ['donhimer 5', 'donepezil 5', 'دونهايمر', '#nootropic'],
    usage: 'دونيبيزيل لعلاج أعراض ألزهايمر.',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٥ مجم مساءً قبل النوم بدون اعتبار للأكل لمدة ٤–٦ أسابيع، ثم ١٠ مجم مساءً – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 12
  {
    id: 'memexa-drops-10mg-ml-15ml-dem',
    name: 'memexa 10mg/ml oral drops 15 ml',
    genericName: 'memantine hydrochloride',
    concentration: '10mg/ml',
    price: 33,
    matchKeywords: ['memexa drops', 'memexa', 'memantine drops', 'memantine 10mg/ml', 'ميميكسا نقط', 'ميمانتين نقط', 'alzheimers', 'dementia', '#nootropic'],
    usage: 'ميمانتين نقط للفم لأعراض ألزهايمر (بديل عند صعوبة البلع).',
    timing: 'مرة–مرتين يومياً بدون اعتبار للأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Oral Drops',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('نقط فموية بتدرج أسبوعي بدون اعتبار للأكل: أسبوع ١: ٠٫٥ مل صباحاً (٥ مجم). أسبوع ٢: ١ مل صباحاً (١٠ مجم). أسبوع ٣: ١ مل صباحاً + ٠٫٥ مل مساءً (١٥ مجم/يوم). أسبوع ٤+: ١ مل مرتين يومياً (٢٠ مجم/يوم) – علاج مزمن.'),
    warnings: MEMANTINE_WARNINGS,
  },

  // 13
  {
    id: 'cerebroforte-20pct-syrup-dem',
    name: 'cerebroforte syrup 20%',
    genericName: 'piracetam',
    concentration: '20%',
    price: 58.5,
    matchKeywords: ['cerebroforte syrup', 'piracetam', 'سيريبروفورت شراب', 'بيراسيتام', '#nootropic'],
    usage: 'داعم وظيفي للذاكرة/القدرات الإدراكية (بيراسيتام).',
    timing: 'كل ٨ ساعات بدون اعتبار للأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Syrup',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('شراب بتركيز ٢٠٪ ≈ ٢٠٠ مجم/مل: ٤–٨ مل ٣ مرات يومياً بدون اعتبار للأكل (٢٫٤–٤٫٨ جم/يوم) – علاج مزمن مع تقييم دوري.'),
    warnings: ['قد يسبب غثيان أو صداع. يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 14
  {
    id: 'donazil-10mg-20-odt-tabs-dem',
    name: 'donazil 10mg 20 odt tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '10mg',
    price: 72,
    matchKeywords: ['donazil 10', 'donepezil 10', 'دونازيل ١٠', 'odt', '#nootropic'],
    usage: 'دونيبيزيل ١٠ مجم لعلاج أعراض ألزهايمر (بعد مرحلة ٥ مجم).',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Orodispersible Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص يتفتت بالفم ١٠ مجم مساءً قبل النوم بدون اعتبار للأكل – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 15
  {
    id: 'donazil-5mg-20-odt-tabs-dem',
    name: 'donazil 5mg 20 odt tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '5mg',
    price: 45,
    matchKeywords: ['donazil 5', 'donepezil 5', 'دونازيل ٥', 'odt', '#nootropic'],
    usage: 'دونيبيزيل ٥ مجم (جرعة البداية) لعلاج أعراض ألزهايمر.',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Orodispersible Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص يتفتت بالفم ٥ مجم مساءً قبل النوم بدون اعتبار للأكل لمدة ٤–٦ أسابيع، ثم ١٠ مجم مساءً – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 16
  {
    id: 'alzimer-10mg-10-fc-tabs-dem',
    name: 'alzimer 10mg 10 f.c. tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '10mg',
    price: 30,
    matchKeywords: ['alzimer 10', 'donepezil 10', 'الزيمر ١٠', '#nootropic'],
    usage: 'دونيبيزيل ١٠ مجم لعلاج أعراض ألزهايمر (بعد مرحلة ٥ مجم).',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٠ مجم مساءً قبل النوم بدون اعتبار للأكل – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 17
  {
    id: 'donazil-5mg-30-fc-tabs-dem',
    name: 'donazil 5mg 30 f.c. tab.',
    genericName: 'donepezil hydrochloride',
    concentration: '5mg',
    price: 63,
    matchKeywords: ['donazil 5 30', 'donepezil 5', 'دونازيل ٣٠', '#nootropic'],
    usage: 'دونيبيزيل ٥ مجم لعلاج أعراض ألزهايمر.',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٥ مجم مساءً قبل النوم بدون اعتبار للأكل (جرعة البداية) – علاج مزمن مع التدرج.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 18
  {
    id: 'exelon-4-5mg-14-caps-dem',
    name: 'exelon 4.5mg 14 caps',
    genericName: 'rivastigmine',
    concentration: '4.5mg',
    price: 140,
    matchKeywords: ['exelon 4.5', 'rivastigmine 4.5', 'اكسيلون', 'ريفاستيجمين', '#nootropic'],
    usage: 'ريفاستيجمين لعلاج أعراض ألزهايمر/الخرف.',
    timing: 'كل ١٢ ساعة مع الأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة ٤٫٥ مجم مرتين يومياً مع الطعام (إجمالي ٩ مجم/يوم) – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 19
  {
    id: 'exelon-4-5mg-28-caps-dem',
    name: 'exelon 4.5mg 28 caps',
    genericName: 'rivastigmine',
    concentration: '4.5mg',
    price: 270,
    matchKeywords: ['exelon 4.5 28', 'rivastigmine', 'اكسيلون ٢٨', '#nootropic'],
    usage: 'ريفاستيجمين لعلاج أعراض الخرف.',
    timing: 'كل ١٢ ساعة مع الأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة ٤٫٥ مجم مرتين يومياً مع الطعام (إجمالي ٩ مجم/يوم) – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },

  // 20
  {
    id: 'serinomantine-7mg-30-mr-caps-dem',
    name: 'serinomantine 7mg 30 ext. rel. caps',
    genericName: 'memantine hydrochloride',
    concentration: '7mg',
    price: 210,
    matchKeywords: ['serinomantine 7', 'memantine 7', 'ميمانتين ممتد', 'سيرينومانتاين', '#nootropic'],
    usage: 'ميمانتين ممتد المفعول لأعراض ألزهايمر.',
    timing: 'مرة يومياً بدون اعتبار للأكل – مزمن',
    category: Category.DEMENTIA,
    form: 'Modified-release Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة ممتدة المفعول ٧ مجم بتدرج أسبوعي بدون اعتبار للأكل: أسبوع ١: كبسولة (٧ مجم) يومياً. أسبوع ٢: كبسولتان (١٤ مجم) يومياً. أسبوع ٣: ٣ كبسولات (٢١ مجم) يومياً. أسبوع ٤+: ٤ كبسولات (٢٨ مجم) يومياً – علاج مزمن.'),
    warnings: MEMANTINE_WARNINGS,
  },

  // 21
  {
    id: 'alkapezil-10mg-7-fc-tabs-dem',
    name: 'alkapezil 10mg 7 f.c.tabs.',
    genericName: 'donepezil hydrochloride',
    concentration: '10mg',
    price: 42,
    matchKeywords: ['alkapezil 10', 'donepezil 10', 'الكابيزيل', '#nootropic'],
    usage: 'دونيبيزيل ١٠ مجم لعلاج أعراض ألزهايمر (بعد مرحلة ٥ مجم).',
    timing: 'مرة يومياً مساءً قبل النوم – مزمن',
    category: Category.DEMENTIA,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٠ مجم مساءً قبل النوم بدون اعتبار للأكل – علاج مزمن.'),
    warnings: CHOLINESTERASE_WARNINGS,
  },
];
