import { Medication, Category } from '../../../../types';

const premixDose = () => '١٠–٢٠ وحدة تحت الجلد قبل الإفطار بـ٣٠ دقيقة و٥–١٠ وحدات قبل العشاء – مرتين يومياً (مزمن)';

const nphDose = () => '١٠ وحدات تحت الجلد قبل النوم مرة يومياً (أو مرتين) – (مزمن)';

const COMMON_INSULIN_WARNINGS = [
  'خطر هبوط السكر موجود—يُفضل قياس السكر بانتظام وحمل مصدر سكر سريع.',
  'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات وخطة العلاج.',
  'غيّر مكان الحقن باستمرار لتجنب تكتلات الدهون.',
  'التخزين: يُحفظ غير المفتوح في الثلاجة؛ المستحضر المفتوح غالباً يصلح بدرجة الغرفة ~4 أسابيع (غالباً ~٤ أسابيع).',
];

export const DIABETES_INSULIN_INTERMEDIATE_MIX: Medication[] = [
  {
    id: 'insulinagypt-70-30-100-5-cartridge',
    name: 'insulinagypt 70/30 100 i.u. 5 cartridge',
    genericName: 'human insulin soluble & human insulin isophane',
    concentration: '100 IU/ml (5 cartridges)',
    price: 135,
    matchKeywords: ['#anti-diabetic', '#insulin', 'insulinagypt', 'انسوليناجيبت', '70/30', 'premix', 'cartridge', 'penfill', 'cloudy insulin', 'انسولين مخلوط', 'معكر'],
    usage: 'أنسولين مخلوط 70/30 للتحكم في السكر (سريع + متوسط المفعول).',
    timing: 'مرتين قبل الأكل بـ٣٠ دقيقة – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [...COMMON_INSULIN_WARNINGS, 'يؤخذ قبل الأكل بنصف ساعة؛ لا تؤخر الوجبة بعد الحقن.'],
  },
  {
    id: 'mixtard-50-hm-100-5x3ml-penfills',
    name: 'mixtard 50 hm 100 i.u./ml 5*3 ml penfills',
    genericName: 'human insulin & isophane insulin (nph)',
    concentration: '100 IU/ml (5×3ml penfills)',
    price: 162.5,
    matchKeywords: ['#anti-diabetic', '#insulin', 'mixtard 50', 'ميكستارد ٥٠', '50', 'premix', 'penfill', 'cloudy insulin', 'انسولين مخلوط', 'معكر'],
    usage: 'ميكستارد 50 (أنسولين مخلوط) للتحكم في السكر.',
    timing: 'مرتين قبل الأكل بـ٣٠ دقيقة – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [...COMMON_INSULIN_WARNINGS, 'يؤخذ قبل الأكل بنصف ساعة؛ لا تؤخر الوجبة بعد الحقن.'],
  },
  {
    id: 'insulinagypt-70-30-100-10ml-vial',
    name: 'insulinagypt 70/30 100 i.u./ml (10ml) vial',
    genericName: 'insulin isophane protamine human & human insulin',
    concentration: '100 IU/ml (10ml vial)',
    price: 122,
    matchKeywords: ['#anti-diabetic', '#insulin', 'insulinagypt', 'انسوليناجيبت', '70/30', 'premix', 'vial', 'سرنجة', 'cloudy insulin', 'معكر'],
    usage: 'أنسولين مخلوط 70/30 (زجاجة) للتحكم في السكر.',
    timing: 'مرتين قبل الأكل بـ٣٠ دقيقة – مزمن',
    category: Category.DIABETES,
    form: 'Vial',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [...COMMON_INSULIN_WARNINGS, 'يؤخذ قبل الأكل بنصف ساعة؛ لا تؤخر الوجبة بعد الحقن.'],
  },
  {
    id: 'insulinagypt-n-100-10ml-vial',
    name: 'insulinagypt n 100 i.u./ml (10ml) vial',
    genericName: 'insulin nph',
    concentration: '100 IU/ml (10ml vial)',
    price: 77,
    matchKeywords: ['#anti-diabetic', '#insulin', 'insulinagypt n', 'انسوليناجيبت ان', 'nph', 'isophane', 'intermediate', 'vial', 'cloudy insulin', 'معكر'],
    usage: 'أنسولين NPH (متوسط المفعول) لضبط السكر القاعدي.',
    timing: 'مرة أو مرتين يومياً – مزمن',
    category: Category.DIABETES,
    form: 'Vial',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => nphDose(),
    warnings: [...COMMON_INSULIN_WARNINGS],
  },
  {
    id: 'mixtard-30-hm-100-10ml-vial',
    name: 'mixtard 30 hm 100 i.u./ml 10ml vial',
    genericName: 'isophane insulin (nph) & human insulin',
    concentration: '100 IU/ml (10ml vial)',
    price: 130,
    matchKeywords: ['#anti-diabetic', '#insulin', 'mixtard 30', 'ميكستارد ٣٠', '30/70', 'premix', 'vial', 'cloudy insulin', 'معكر'],
    usage: 'ميكستارد 30 (أنسولين مخلوط) للتحكم في السكر.',
    timing: 'مرتين قبل الأكل بـ٣٠ دقيقة – مزمن',
    category: Category.DIABETES,
    form: 'Vial',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [...COMMON_INSULIN_WARNINGS, 'يؤخذ قبل الأكل بنصف ساعة؛ لا تؤخر الوجبة بعد الحقن.'],
  },
  {
    id: 'insulin-h-mix-70-30-100-vial',
    name: 'insulin h mix 70/30 100 i.u vial',
    genericName: 'protamin insulin human & recombinant human insulin',
    concentration: '100 IU/ml (vial)',
    price: 122,
    matchKeywords: ['#anti-diabetic', '#insulin', 'insulin h mix', '70/30', 'premix', 'vial', 'cloudy insulin', 'معكر'],
    usage: 'أنسولين مخلوط 70/30 للتحكم في السكر.',
    timing: 'مرتين قبل الأكل بـ٣٠ دقيقة – مزمن',
    category: Category.DIABETES,
    form: 'Vial',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [...COMMON_INSULIN_WARNINGS, 'يؤخذ قبل الأكل بنصف ساعة؛ لا تؤخر الوجبة بعد الحقن.'],
  },
  {
    id: 'humulin-n-100-5-cartridge',
    name: 'humulin n 100 i.u./ml 5 cartridge',
    genericName: 'human insulin isophane',
    concentration: '100 IU/ml (5 cartridges)',
    price: 338,
    matchKeywords: ['#anti-diabetic', '#insulin', 'humulin n', 'هيوميلين ان', 'nph', 'isophane', 'cartridge', 'penfill', 'cloudy insulin', 'معكر'],
    usage: 'هيوميلين N (NPH) أنسولين متوسط المفعول لضبط السكر القاعدي.',
    timing: 'مرة أو مرتين يومياً – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => nphDose(),
    warnings: [...COMMON_INSULIN_WARNINGS],
  },
  {
    id: 'humulin-70-30-100-5-cartridge',
    name: 'humulin 70/30 100 i.u. 5 cartridge',
    genericName: 'biphasic isophane insulin',
    concentration: '100 IU/ml (5 cartridges)',
    price: 338,
    matchKeywords: ['#anti-diabetic', '#insulin', 'humulin 70/30', 'هيوميلين ٧٠/٣٠', '70/30', 'premix', 'cartridge', 'penfill', 'cloudy insulin', 'معكر'],
    usage: 'هيوميلين 70/30 (أنسولين مخلوط) لضبط السكر.',
    timing: 'مرتين قبل الأكل بـ٣٠ دقيقة – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [...COMMON_INSULIN_WARNINGS, 'يؤخذ قبل الأكل بنصف ساعة؛ لا تؤخر الوجبة بعد الحقن.'],
  },
  {
    id: 'insulatard-hm-100-5x3ml-penfills',
    name: 'insulatard hm 100i.u./ml 5*3ml penfills',
    genericName: 'insulin isophane protamine human',
    concentration: '100 IU/ml (5×3ml penfills)',
    price: 196,
    matchKeywords: ['#anti-diabetic', '#insulin', 'insulatard', 'انسولاتارد', 'nph', 'isophane', 'penfill', 'cloudy insulin', 'معكر'],
    usage: 'إنسولاتارد HM (NPH) أنسولين متوسط المفعول لضبط السكر القاعدي.',
    timing: 'مرة أو مرتين يومياً – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => nphDose(),
    warnings: [...COMMON_INSULIN_WARNINGS],
  },
  {
    id: 'insulatard-hm-100-10ml-vial',
    name: 'insulatard hm 100i.u./ml 10 ml vial',
    genericName: 'insulin isophane protamine human',
    concentration: '100 IU/ml (10ml vial)',
    price: 130,
    matchKeywords: ['#anti-diabetic', '#insulin', 'insulatard', 'انسولاتارد', 'nph', 'isophane', 'vial', 'cloudy insulin', 'معكر'],
    usage: 'إنسولاتارد HM (NPH) أنسولين متوسط المفعول لضبط السكر القاعدي.',
    timing: 'مرة أو مرتين يومياً – مزمن',
    category: Category.DIABETES,
    form: 'Vial',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => nphDose(),
    warnings: [...COMMON_INSULIN_WARNINGS],
  },
];
