
import { Medication, Category } from '../../../../types';

const basalDose = () => '١٠ وحدات تحت الجلد مرة يومياً ثابتة في نفس الوقت (مزمن)';

const coformulationDose = () => '١٠ وحدات تحت الجلد مع الوجبة الرئيسية مرة يومياً (مزمن) – تُعدل حسب قياسات السكر';

const comboInsulinGlp1Dose = () => '١٠ وحدات تحت الجلد مرة يومياً ثابتة في نفس الوقت (مزمن) – بدء ومعايرة حسب قراءات السكر';

const COMMON_BASAL_WARNINGS = [
	'خطر هبوط السكر موجود—يُفضل قياس السكر بانتظام وحمل مصدر سكر سريع.',
	'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات.',
	'غيّر مكان الحقن باستمرار لتجنب تكتلات الدهون.',
	'التخزين: يُحفظ غير المفتوح في الثلاجة؛ المفتوح غالباً ~٤ أسابيع بدرجة الغرفة (غالباً ~٤ أسابيع بدرجة الغرفة).',
];

export const DIABETES_INSULIN_LONG_ACTING: Medication[] = [
	{
		id: 'lantus-solostar-100-5pens',
		name: 'lantus solostar 100 i.u./ml 5 pens',
		genericName: 'insulin glargine',
		concentration: '100 IU/ml (5 pens)',
		price: 1244,
		matchKeywords: ['#anti-diabetic', '#insulin', 'lantus solostar', 'lantus', 'لانتوس', 'سولوستار', 'glargine', 'basal insulin', 'long acting'],
		usage: 'أنسولين قاعدي طويل المفعول (Glargine) لضبط السكر على مدار اليوم.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => basalDose(),
		warnings: [...COMMON_BASAL_WARNINGS],
	},
	{
		id: 'toujeo-solostar-300-1p5ml-3pens',
		name: 'toujeo solostar 300 i.u./ml 1.5 ml 3 pens',
		genericName: 'insulin glargine',
		concentration: '300 IU/ml (1.5ml pens ×3)',
		price: 1416,
		matchKeywords: ['#anti-diabetic', '#insulin', 'toujeo', 'توجيو', 'glargine', '300', 'concentrated insulin', 'basal insulin', 'long acting'],
		usage: 'أنسولين قاعدي (Glargine) مركز 300 وحدة/مل طويل المفعول.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => basalDose(),
		warnings: [...COMMON_BASAL_WARNINGS],
	},
	{
		id: 'toujeo-solostar-300-1p5ml-5pens',
		name: 'toujeo solostar 300 i.u./ml 1.5 ml 5 pens',
		genericName: 'insulin glargine',
		concentration: '300 IU/ml (1.5ml pens ×5)',
		price: 2360,
		matchKeywords: ['#anti-diabetic', '#insulin', 'toujeo', 'توجيو', 'glargine', '300', 'concentrated insulin', 'basal insulin', 'long acting'],
		usage: 'أنسولين قاعدي (Glargine) مركز 300 وحدة/مل طويل المفعول.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => basalDose(),
		warnings: [...COMMON_BASAL_WARNINGS],
	},
	{
		id: 'ryzodeg-flextouch-100-pen',
		name: 'ryzodeg 100 i.u./ml flextouch pre-filled pen',
		genericName: 'insulin degludec & insulin aspart',
		concentration: '100 IU/ml',
		price: 618,
		matchKeywords: ['#anti-diabetic', '#insulin', 'ryzodeg', 'ريزوديج', 'degludec', 'aspart', 'flextouch', 'co-formulation'],
		usage: 'أنسولين مركب (ديجلوديك + أسبارت) لتغطية قاعدية + جرعة وجبة (حسب الخطة).',
		timing: 'مرة يومياً مع الوجبة الرئيسية – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => coformulationDose(),
		warnings: [...COMMON_BASAL_WARNINGS, 'قد يسبب هبوط/ارتفاع السكر إذا لم تُضبط الوجبات والجرعات بدقة.'],
	},
	{
		id: 'tresiba-flextouch-100-pen',
		name: 'tresiba 100 i.u./ml flextouch pre-filled pen',
		genericName: 'insulin degludec',
		concentration: '100 IU/ml',
		price: 550,
		matchKeywords: ['#anti-diabetic', '#insulin', 'tresiba', 'تريسيبا', 'degludec', 'flextouch', 'ultra long acting', 'basal insulin'],
		usage: 'أنسولين قاعدي طويل جداً المفعول (Degludec) لضبط السكر.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => basalDose(),
		warnings: [...COMMON_BASAL_WARNINGS],
	},
	{
		id: 'glargivin-100-5-cartridges',
		name: 'glargivin 100 i.u./ml 5 cartridges',
		genericName: 'insulin glargine',
		concentration: '100 IU/ml (5 cartridges)',
		price: 910,
		matchKeywords: ['#anti-diabetic', '#insulin', 'glargivin', 'جلارجيفين', 'glargine', 'cartridge', 'penfill', 'basal insulin', 'long acting'],
		usage: 'أنسولين قاعدي طويل المفعول (Glargine) في صورة خراطيش.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => basalDose(),
		warnings: [...COMMON_BASAL_WARNINGS],
	},
	{
		id: 'soliqua-100-33-3-pens',
		name: 'soliqua 100 units+33 mcg/ml 3 prefilled pen',
		genericName: 'insulin glargine & lixisenatide',
		concentration: '100 units + 33 mcg/ml (3 pens)',
		price: 1785,
		matchKeywords: ['#anti-diabetic', 'soliqua', 'سوليكوا', 'glargine', 'lixisenatide', 'fixed ratio', 'basal + glp1'],
		usage: 'مركب (Glargine + Lixisenatide) لتحسين التحكم في السكر لدى بعض مرضى النوع الثاني.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => comboInsulinGlp1Dose(),
		warnings: [
			...COMMON_BASAL_WARNINGS,
			'ملاحظة: يحتوي على GLP-1؛ قد يسبب أعراض جهاز هضمي (غثيان/قيء) خصوصاً بالبداية.',
		],
	},
	{
		id: 'soliqua-100-50-3-pens',
		name: 'soliqua 100 units+50 mcg/ml 3 prefilled pen',
		genericName: 'insulin glargine & lixisenatide',
		concentration: '100 units + 50 mcg/ml (3 pens)',
		price: 2531,
		matchKeywords: ['#anti-diabetic', 'soliqua', 'سوليكوا', 'glargine', 'lixisenatide', 'fixed ratio', 'basal + glp1'],
		usage: 'مركب (Glargine + Lixisenatide) لتحسين التحكم في السكر لدى بعض مرضى النوع الثاني.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => comboInsulinGlp1Dose(),
		warnings: [
			...COMMON_BASAL_WARNINGS,
			'ملاحظة: يحتوي على GLP-1؛ قد يسبب أعراض جهاز هضمي (غثيان/قيء) خصوصاً بالبداية.',
		],
	},
	{
		id: 'lantus-100-5-cartridges',
		name: 'lantus 100 i.u./ml 5 cartridges',
		genericName: 'insulin glargine',
		concentration: '100 IU/ml (5 cartridges)',
		price: 1107,
		matchKeywords: ['#anti-diabetic', '#insulin', 'lantus', 'لانتوس', 'glargine', 'cartridge', 'penfill', 'basal insulin', 'long acting'],
		usage: 'أنسولين قاعدي طويل المفعول (Glargine) في صورة خراطيش.',
		timing: 'مرة يومياً مساءً – مزمن',
		category: Category.DIABETES,
		form: 'Pen',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 200,
		calculationRule: (_) => basalDose(),
		warnings: [...COMMON_BASAL_WARNINGS],
	},
];
