
import { Medication, Category } from '../../../../types';

const rapidBolusDose = () => '٥ وحدات تحت الجلد قبل الأكل بـ١٥ دقيقة – ٣ مرات يومياً (مزمن)';

const premixDose = () => '١٠–٢٠ وحدة تحت الجلد قبل الإفطار و٥–١٠ وحدات قبل العشاء – مرتين يومياً (مزمن)';

export const DIABETES_INSULIN_RAPID: Medication[] = [
  {
    id: 'novorapid-penfill',
    name: 'Novorapid 100 i.u./ml 5 penfill',
    genericName: 'Insulin Aspart',
    concentration: '100 IU/ml',
    price: 1075,
    matchKeywords: ['#anti-diabetic', '#insulin', 'type 1 diabetes', 'type 2 diabetes', 'meal insulin', 'bolus', 'rapid insulin', 'insulin aspart', 'aspart', 'سكر نوع اول', 'انسولين مائي', 'نوفورابيد', 'نوفورابيد بنفيل'],
    usage: 'أنسولين سريع المفعول (مائي) للتحكم في السكر بعد الوجبات مباشرة.',
    timing: '٣ مرات قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 200,
    calculationRule: (_) => rapidBolusDose(),
    warnings: [
        'خطر هبوط السكر إذا لم يتم تناول الطعام فوراً.',
        'يجب أن يكون السائل صافي وشفاف (Clear).',
        'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
        'يجب تغيير مكان الحقن باستمرار.'
    ]
  },
  {
    id: 'novorapid-flexpen',
    name: 'Novorapid 100 i.u./ml 5 flexpen',
    genericName: 'Insulin Aspart',
    concentration: '100 IU/ml',
    price: 1260,
    matchKeywords: ['#anti-diabetic', '#insulin', 'rapid insulin pen', 'diabetes', 'fast acting', 'insulin aspart', 'aspart', 'نوفورابيد', 'نوفورابيد قلم', 'flexpen'],
    usage: 'أقلام أنسولين جاهزة سريعة المفعول (أسهل في الاستخدام).',
    timing: '٣ مرات قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 5,
    maxWeight: 200,
    calculationRule: (_) => rapidBolusDose(),
    warnings: ['لا تشارك القلم مع مريض آخر.', 'يحفظ في الثلاجة قبل الفتح.', 'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.']
  },
  {
    id: 'humalog-mix25-kwikpen-100-5pens',
    name: 'humalog mix25 kwikpen 100i.u./ml (5 pens)',
    genericName: 'insulin lispro',
    concentration: '100 IU/ml (5 pens)',
    price: 1237,
    matchKeywords: ['#anti-diabetic', '#insulin', 'humalog mix25', 'هيومالوج ميكس ٢٥', 'kwikpen', 'premix'],
    usage: 'أنسولين مخلوط (Premix) لضبط السكر قبل/بعد الوجبات حسب الخطة.',
    timing: 'مرتين قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [
      'خطر هبوط السكر خصوصاً إذا تأخرت الوجبة.',
      'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
      'غيّر مكان الحقن باستمرار.',
    ],
  },
  {
    id: 'humalog-mix50-kwikpen-100-5pens',
    name: 'humalog mix50 kwikpen 100i.u./ml (5 pens)',
    genericName: 'insulin lispro protamine & insulin lispro',
    concentration: '100 IU/ml (5 pens)',
    price: 1237,
    matchKeywords: ['#anti-diabetic', '#insulin', 'humalog mix50', 'هيومالوج ميكس ٥٠', 'kwikpen', 'premix'],
    usage: 'أنسولين مخلوط (Premix) لضبط السكر قبل/بعد الوجبات حسب الخطة.',
    timing: 'مرتين قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [
      'خطر هبوط السكر خصوصاً إذا تأخرت الوجبة.',
      'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
      'غيّر مكان الحقن باستمرار.',
    ],
  },
  {
    id: 'humalog-mix25-100-5cartridges',
    name: 'humalog mix25 100i.u./ml (5 cartridges)',
    genericName: 'insulin lispro',
    concentration: '100 IU/ml (5 cartridges)',
    price: 928,
    matchKeywords: ['#anti-diabetic', '#insulin', 'humalog mix25', 'هيومالوج ميكس ٢٥', 'cartridge', 'penfill', 'premix'],
    usage: 'أنسولين مخلوط (Premix) بخراطيش للأقلام المعاد تعبئتها.',
    timing: 'مرتين قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [
      'خطر هبوط السكر خصوصاً إذا تأخرت الوجبة.',
      'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
      'غيّر مكان الحقن باستمرار.',
    ],
  },
  {
    id: 'novomix-50-100-5-flexpen',
    name: 'novomix 50 100 i.u./ml 5 flexpen',
    genericName: 'insulin aspartate protamine',
    concentration: '100 IU/ml',
    price: 637,
    matchKeywords: ['#anti-diabetic', '#insulin', 'novomix 50', 'نوفومكس ٥٠', 'aspart protamine', 'premix', 'flexpen'],
    usage: 'أنسولين مخلوط (Premix) من نوفونوردسك لضبط السكر.',
    timing: 'مرتين قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [
      'خطر هبوط السكر إذا تأخرت الوجبة.',
      'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
      'غيّر مكان الحقن باستمرار.',
    ],
  },
  {
    id: 'novomix-30-100-5-flexpen',
    name: 'novomix 30 100 i.u./ml 5 flexpen',
    genericName: 'insulin aspart',
    concentration: '100 IU/ml',
    price: 1260,
    matchKeywords: ['#anti-diabetic', '#insulin', 'novomix 30', 'نوفومكس ٣٠', 'aspart', 'premix', 'flexpen'],
    usage: 'أنسولين مخلوط (Premix) لضبط السكر قبل/بعد الوجبات حسب الخطة.',
    timing: 'مرتين قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [
      'خطر هبوط السكر إذا تأخرت الوجبة.',
      'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
      'غيّر مكان الحقن باستمرار.',
    ],
  },
  {
    id: 'novomix-30-100-5-penfills',
    name: 'novomix 30 100 i.u./ml 5 penfills',
    genericName: 'insulin aspart',
    concentration: '100 IU/ml (5 penfills)',
    price: 330,
    matchKeywords: ['#anti-diabetic', '#insulin', 'novomix 30', 'نوفومكس ٣٠', 'penfill', 'cartridge', 'premix', 'aspart'],
    usage: 'أنسولين مخلوط (Premix) بخراطيش للأقلام المعاد تعبئتها.',
    timing: 'مرتين قبل الأكل – مزمن',
    category: Category.DIABETES,
    form: 'Pen',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 200,
    calculationRule: (_) => premixDose(),
    warnings: [
      'خطر هبوط السكر إذا تأخرت الوجبة.',
      'تنبيه: لا تعتمد على “حسبة تلقائية” للأنسولين—الجرعة تُحدد حسب القياسات والتحاليل.',
      'غيّر مكان الحقن باستمرار.',
    ],
  }
];
