import { Medication, Category } from '../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, (d) => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const round = (n: number, digits = 1) => {
	const p = 10 ** digits;
	return Math.round(n * p) / p;
};
const roundVol = (ml: number) => round(ml, 1);
const clamp = (n: number, min: number, max: number) => Math.min(max, Math.max(min, n));
const fixed = (text: string) => (_w: number, _a: number) => text;

const COMMON_ANTIBIOTIC_WARNINGS = [
	'حساسية: أوقف الدواء واطلب مساعدة إذا ظهر طفح شديد/تورم/ضيق نفس.',
	'لا يفيد في نزلات البرد والإنفلونزا (عدوى فيروسية).',
];

const COMMON_TOPICAL_WARNINGS = [
	'للاستخدام الخارجي فقط.',
	'تجنب ملامسة العين/الفم إلا إذا كان المنتج مخصصاً لذلك.',
	'إذا زاد الاحمرار/الحكة أو ظهر تهيج شديد: أوقفه وأعد التقييم (حساسية، عدوى ثانوية، أو استبدال الدواء).',
];

const COMMON_STEROID_TOPICAL_WARNINGS = [
	...COMMON_TOPICAL_WARNINGS,
	'كورتيزون: لا يُستخدم لأكثر من ٧–١٤ يوماً على الوجه/حول العين؛ على الثنيات/مناطق واسعة: بأقل جرعة ولمدة محدودة.',
	'لا يُستخدم على عدوى فيروسية (هربس) أو فطريات غير مُشخّصة.',
];

const COMMON_EYE_DROP_WARNINGS = [
	'لا تلمس طرف القطارة للعين/الرموش لتجنب تلوث العبوة.',
	'العدسات اللاصقة: تُزال قبل الاستخدام وتُعاد بعد ١٥ دقيقة (ويُفضل تجنبها أثناء الالتهاب).',
	'إذا لم تتحسن الأعراض خلال ٤٨–٧٢ ساعة أو وُجد ألم شديد/ضعف نظر: راجع طبيب عيون.',
];

const COMMON_STEROID_EYE_WARNINGS = [
	...COMMON_EYE_DROP_WARNINGS,
	'يحتوي على كورتيزون: لا يُستخدم دون إشراف عند الاشتباه في عدوى فيروسية بالعين أو قرحة قرنية.',
	'قد يرفع ضغط العين مع الاستعمال المطوّل؛ لا تطوّل المدة دون متابعة.',
];

const aminoglycosideInjectionWarnings = [
	...COMMON_ANTIBIOTIC_WARNINGS,
	'سمّية كلوية: راقب وظائف الكلى (Cr، BUN) قبل البدء وكل ٣–٥ أيام.',
	'سمّية سمعية (ototoxicity): راقب السمع مع الجرعات العالية أو المدد >٧ أيام. أوقف عند طنين أو نقص سمع.',
	'يُفضل الجرعة الواحدة يومياً (once-daily dosing) لتقليل السمية الكلوية وزيادة الفعالية.',
	'يُتجنب أو يُستخدم بحذر شديد مع: فشل كلوي، جفاف شديد، أدوية تضر الكلى (مثل بعض المدرات/NSAIDs/فانكومايسين).',
	'الحمل: يُستخدم عند الضرورة القصوى فقط؛ يُفضل تجنب الأمينوغليكوزيدات (سمية سمعية محتملة للجنين).',
	'قياس مستوى الدواء بالدم (TDM) مُستحسن مع المدد الطويلة أو الفشل الكلوي.',
];

const parseMgMl = (c: string): number => {
	const m = c.trim().toLowerCase().match(/(\d+)\s*mg\s*\/\s*(\d+(?:\.\d+)?)\s*ml/i);
	if (!m) return 0;
	const mg = Number(m[1]);
	const ml = Number(m[2]);
	return ml > 0 ? mg / ml : 0;
};

const amikacinDose = (weightKg: number, ageMonths: number, concentration: string): string => {
	if (ageMonths < 1) return 'حديثي الولادة: جرعات خاصة—يلزم بروتوكول.';
	const mgPerMl = parseMgMl(concentration);
	if (!mgPerMl) return 'جرعة غير متاحة لهذا التركيز.';
	const isAdult = ageMonths >= 144 || weightKg >= 40;
	const mgMin = isAdult ? 500 : clamp(weightKg * 15, 0, 1500);
	const mgMax = isAdult ? 500 : clamp(weightKg * 20, 0, 1500);
	const mlMin = Math.round((mgMin / mgPerMl) * 10) / 10;
	const mlMax = Math.round((mgMax / mgPerMl) * 10) / 10;
	const dur = 'لمدة ٥–٧ أيام (بول) أو ٧–١٠ أيام (شديدة)';
	if (Math.abs(mlMin - mlMax) < 0.1) return `${toAr(mlMin)} مل عضل/وريد كل ٢٤ ساعة ${dur}`;
	return `${toAr(mlMin)}–${toAr(mlMax)} مل عضل/وريد كل ٢٤ ساعة ${dur}`;
};

const gentamicinDose = (weightKg: number, ageMonths: number, concentration: string): string => {
	if (ageMonths < 1) return 'حديثي الولادة: جرعات خاصة—يلزم بروتوكول.';
	const mgPerMl = parseMgMl(concentration);
	if (!mgPerMl) return 'جرعة غير متاحة لهذا التركيز.';
	const isAdult = ageMonths >= 144 || weightKg >= 40;
	const mgMin = isAdult ? 240 : clamp(weightKg * 5, 0, 480);
	const mgMax = isAdult ? 240 : clamp(weightKg * 7, 0, 480);
	const mlMin = Math.round((mgMin / mgPerMl) * 10) / 10;
	const mlMax = Math.round((mgMax / mgPerMl) * 10) / 10;
	const dur = 'لمدة ٥–٧ أيام (بول) أو ٧–١٠ أيام (شديدة)';
	if (Math.abs(mlMin - mlMax) < 0.1) return `${toAr(mlMin)} مل عضل/وريد كل ٢٤ ساعة ${dur}`;
	return `${toAr(mlMin)}–${toAr(mlMax)} مل عضل/وريد كل ٢٤ ساعة ${dur}`;
};

const amikacin = (conc: string) => (w: number, a: number) => amikacinDose(w, a, conc);
const gentamicin = (conc: string) => (w: number, a: number) => gentamicinDose(w, a, conc);

export const AMINOGLYCOSIDES_GROUP: Medication[] = [
	// =============================
	// TOPICAL / DERMATOLOGY
	// =============================

	// 1) bivatracin 150mg powder spray
	{
		id: 'bivatracin-150mg-powder-spray',
		name: 'bivatracin 150mg powder spray',
		genericName: 'bacitracin zinc & neomycin sulphate',
		concentration: 'powder spray',
		price: 83,
		matchKeywords: ['bivatracin', 'بيفاتراسين', 'bacitracin', 'neomycin', 'spray', 'بودرة سبراي', 'جرح', 'جروح', 'خدش', 'خدوش', 'infected wound', 'skin infection', 'impetigo', '#topical antibiotic', '#antibiotics'],
		usage: 'مضاد حيوي موضعي للجروح/الخدوش السطحية الملوثة (للاستخدام الخارجي فقط).',
		timing: '٢–٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Spray',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 250,
		calculationRule: fixed('رش طبقة خفيفة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS, 'تجنب استخدامه على مساحات كبيرة أو حروق واسعة دون إعادة تقييم (امتصاص/حساسية).'],
	},

	// 2) quadriderm cream 30 gm
	{
		id: 'quadriderm-cream-30gm',
		name: 'quadriderm cream 30 gm',
		genericName: 'betamethasone valerate & gentamicin (as sulfate) & tolnaftate',
		concentration: 'cream',
		price: 48,
		matchKeywords: ['quadriderm 30', 'quadriderm', 'كوادراديرم', 'betamethasone', 'gentamicin', 'tolnaftate', 'fungal', 'tinea', 'eczema infected', 'intertrigo', 'التهاب فطري', 'فطريات', 'التهاب جلدي', 'حكة', 'التهاب مع عدوى', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون + مضاد حيوي + مضاد فطري) لالتهاب جلدي مُلتهب مع عدوى سطحية بكتيرية/فطرية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 3) garamycin 0.1% oint. 15 gm
	{
		id: 'garamycin-0.1-oint-15gm',
		name: 'garamycin 0.1% oint. 15 gm',
		genericName: 'gentamicin',
		concentration: '0.1%',
		price: 22,
		matchKeywords: ['garamycin oint', 'garamycin 0.1', 'جارامايسين مرهم', 'gentamicin ointment', 'infected wound', 'folliculitis', 'impetigo', 'جروح ملتهبة', 'التهاب بصيلات', 'حصف', '#aminoglycoside antibiotic'],
		usage: 'مرهم جنتاميسين موضعي لعدوى جلدية بكتيرية سطحية.',
		timing: '٢–٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Ointment',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS],
	},

	// 4) kenacomb topical oint. 15 gm
	{
		id: 'kenacomb-oint-15gm',
		name: 'kenacomb topical oint. 15 gm',
		genericName: 'triamcinolone acetonide & neomycin sulphate & gramicidin & nystatin',
		concentration: 'ointment',
		price: 21.5,
		matchKeywords: ['kenacomb oint', 'kenacomb', 'كيناكومب مرهم', 'triamcinolone', 'neomycin', 'nystatin', 'eczema infected', 'dermatitis', 'intertrigo', 'التهاب جلدي', 'حكة', 'فطريات', '#antibiotics'],
		usage: 'مرهم مركب (كورتيزون + مضاد حيوي + مضاد فطري) لالتهاب جلدي ملتهب مع عدوى سطحية بكتيرية/فطرية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Ointment',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 6) garamycin 0.1% cream 15 gm
	{
		id: 'garamycin-0.1-cream-15gm',
		name: 'garamycin 0.1% cream 15 gm',
		genericName: 'gentamicin',
		concentration: '0.1%',
		price: 22,
		matchKeywords: ['garamycin cream', 'garamycin 0.1', 'جارامايسين كريم', 'gentamicin cream', 'infected wound', 'impetigo', 'folliculitis', 'جروح ملتهبة', 'حصف', 'التهاب بصيلات', '#aminoglycoside antibiotic'],
		usage: 'كريم جنتاميسين موضعي لعدوى جلدية بكتيرية سطحية (أنسب للجلد الرطب/الوجه).',
		timing: '٢–٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS],
	},

	// 7) kenacomb topical cream 15 gm
	{
		id: 'kenacomb-cream-15gm',
		name: 'kenacomb topical cream 15 gm',
		genericName: 'nystatin & neomycin & gramicidin & triamcinolone',
		concentration: 'cream',
		price: 36,
		matchKeywords: ['kenacomb cream', 'kenacomb', 'كيناكومب كريم', 'nystatin', 'neomycin', 'triamcinolone', 'eczema infected', 'intertrigo', 'التهاب جلدي', 'حكة', 'فطريات', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون + مضاد حيوي + مضاد فطري) لالتهاب جلدي ملتهب مع عدوى سطحية بكتيرية/فطرية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 8) quadriderm cream 15 gm
	{
		id: 'quadriderm-cream-15gm',
		name: 'quadriderm cream 15 gm',
		genericName: 'betamethasone valerate & gentamicin (as sulfate) & tolnaftate',
		concentration: 'cream',
		price: 32,
		matchKeywords: ['quadriderm 15', 'quadriderm', 'كوادراديرم', 'betamethasone', 'gentamicin', 'tolnaftate', 'fungal', 'tinea', 'eczema infected', 'التهاب فطري', 'فطريات', 'التهاب جلدي', 'حكة', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون + مضاد حيوي + مضاد فطري) لالتهاب جلدي مُلتهب مع عدوى سطحية بكتيرية/فطرية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 11) amikacin spray 100 ml
	{
		id: 'amikacin-spray-100ml',
		name: 'amikacin spray 100 ml',
		genericName: 'amikacin',
		concentration: 'spray 100 ml',
		price: 53,
		matchKeywords: ['amikacin spray', 'amikacin', 'أميكاسين سبراي', 'spray', 'wound', 'burn', 'infected wound', 'جروح', 'حروق', 'التهاب جرح', '#antibiotics'],
		usage: 'مضاد حيوي موضعي (أميكاسين) للجروح والعدوى الجلدية السطحية.',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Spray',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 250,
		calculationRule: fixed('رش طبقة خفيفة على المنطقة المصابة ٣ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS],
	},

	// 14) mixderm cream 15 gm
	{
		id: 'mixderm-cream-15gm',
		name: 'mixderm cream 15 gm',
		genericName: 'betamethasone valerate & gentamicin & clioquinol & tolnaftate',
		concentration: 'cream',
		price: 24,
		matchKeywords: ['mixderm 15', 'mixderm', 'ميكسديرم', 'betamethasone', 'gentamicin', 'clioquinol', 'tolnaftate', 'eczema infected', 'fungal', 'dermatitis', 'التهاب جلدي', 'حكة', 'فطريات', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون + مضاد حيوي + مضادات فطر/مطهر) للالتهابات الجلدية الملتهبة مع عدوى سطحية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 15) momenta cream 30 gm
	{
		id: 'momenta-cream-30gm',
		name: 'momenta cream 30 gm',
		genericName: 'mometasone & miconazole & gentamicin',
		concentration: 'cream',
		price: 55,
		matchKeywords: ['momenta', 'momenta cream', 'مومنتا', 'mometasone', 'miconazole', 'gentamicin', 'fungal', 'tinea', 'eczema infected', 'intertrigo', 'التهاب فطري', 'فطريات', 'حكة', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون + مضاد فطري + مضاد حيوي) لالتهاب جلدي مُلتهب مع فطريات/عدوى سطحية.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرة يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 18) mixderm cream 30 gm
	{
		id: 'mixderm-cream-30gm',
		name: 'mixderm cream 30 gm',
		genericName: 'betamethasone valerate & gentamicin & clioquinol & tolnaftate',
		concentration: 'cream',
		price: 41,
		matchKeywords: ['mixderm 30', 'mixderm', 'ميكسديرم', 'eczema infected', 'fungal', 'intertrigo', 'التهاب جلدي', 'حكة', 'فطريات', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون + مضاد حيوي + مضادات فطر/مطهر) للالتهابات الجلدية الملتهبة مع عدوى سطحية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 21) propamethone top. cream. 20 gm
	{
		id: 'propamethone-top-cream-20gm',
		name: 'propamethone top. cream. 20 gm',
		genericName: 'betamethasone dipropionate & gentamicin & clotrimazole',
		concentration: 'cream',
		price: 30,
		matchKeywords: ['propamethone', 'propamethone cream', 'بروباميثون', 'betamethasone', 'gentamicin', 'clotrimazole', 'fungal', 'eczema infected', 'intertrigo', 'التهاب فطري', 'فطريات', 'حكة', '#antibiotics'],
		usage: 'كريم مركب (كورتيزون قوي + مضاد فطري + مضاد حيوي) لالتهاب جلدي شديد.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS, 'يحتوي على كورتيزون قوي (Betamethasone dipropionate).'],
	},

	// 28) farcocin 0.1% oint. 20 gm
	{
		id: 'farcocin-oint-20',
		name: 'Farcocin 0.1% oint. 20 gm',
		genericName: 'gentamicin',
		concentration: '0.1%',
		price: 23,
		matchKeywords: ['farcocin oint', 'farcocin 0.1', 'فاركوسين مرهم', 'gentamicin', 'infected wound', 'folliculitis', 'impetigo', 'جروح ملتهبة', 'التهاب بصيلات', 'حصف', '#aminoglycoside antibiotic'],
		usage: 'مرهم جنتاميسين موضعي لعدوى جلدية بكتيرية سطحية.',
		timing: '٣–٤ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Ointment',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS],
	},

	// 30) gentazone cream 15 gm
	{
		id: 'gentazone-cream-15gm',
		name: 'gentazone cream 15 gm',
		genericName: 'betamethasone & gentamicin',
		concentration: 'cream',
		price: 17,
		matchKeywords: ['gentazone', 'gentazone cream', 'جنتازون', 'betamethasone', 'gentamicin', 'eczema infected', 'dermatitis', 'التهاب جلدي', 'حكة', '#glucocorticoid'],
		usage: 'كريم (كورتيزون + مضاد حيوي) لالتهاب جلدي ملتهب مع عدوى سطحية بكتيرية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 37) borgasone trio cream 15 gm
	{
		id: 'borgasone-trio-cream-15gm',
		name: 'borgasone trio cream 15 gm',
		genericName: 'gentamicin & miconazole nitrate & mometasone furoate',
		concentration: 'cream',
		price: 30.5,
		matchKeywords: ['borgasone trio', 'borgasone', 'بورجازون', 'mometasone', 'miconazole', 'gentamicin', 'fungal', 'intertrigo', 'التهاب فطري', 'فطريات', 'حكة', '#glucocorticoid'],
		usage: 'كريم مركب (كورتيزون + مضاد فطري + مضاد حيوي) للالتهابات الجلدية المختلطة.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرة يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 39) farcocin 0.1% cream 20 gm
	{
		id: 'farcocin-0.1-cream-20gm',
		name: 'farcocin 0.1% cream 20 gm',
		genericName: 'gentamicin',
		concentration: '0.1%',
		price: 23,
		matchKeywords: ['farcocin cream', 'farcocin 0.1', 'فاركوسين كريم', 'gentamicin', 'infected wound', 'folliculitis', 'impetigo', 'جروح ملتهبة', 'التهاب بصيلات', 'حصف'],
		usage: 'كريم جنتاميسين موضعي لعدوى جلدية بكتيرية سطحية.',
		timing: '٣–٤ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS],
	},

	// 40) epicomb topical oint 15 gm
	{
		id: 'epicomb-oint-15gm',
		name: 'epicomb topical oint 15 gm',
		genericName: 'gramicidin & neomycin & nystatin & triamcinolone',
		concentration: 'ointment',
		price: 22,
		matchKeywords: ['epicomb oint', 'epicomb', 'ايبيكومب مرهم', 'triamcinolone', 'neomycin', 'nystatin', 'eczema infected', 'intertrigo', 'التهاب جلدي', 'حكة', 'فطريات'],
		usage: 'مرهم مركب (كورتيزون + مضاد حيوي + مضاد فطري) لالتهابات جلدية ملتهبة مع عدوى سطحية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Ointment',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 41) tri-betapronate cream 30 gm
	{
		id: 'tri-betapronate-cream-30gm',
		name: 'tri-betapronate cream 30 gm',
		genericName: 'gentamicin & betamethasone & clotrimazole',
		concentration: 'cream',
		price: 36,
		matchKeywords: ['tri-betapronate', 'betapronate', 'تراي بيتابرونيت', 'gentamicin', 'betamethasone', 'clotrimazole', 'fungal', 'intertrigo', 'eczema infected', 'فطريات', 'حكة'],
		usage: 'كريم مركب (كورتيزون + مضاد فطري + مضاد حيوي) للالتهابات الجلدية المختلطة.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 42) epicomb topical cream 15 gm
	{
		id: 'epicomb-cream-15gm',
		name: 'epicomb topical cream 15 gm',
		genericName: 'gramicidin & triamcinolone acetonide & neomycin sulphate & nystatin',
		concentration: 'cream',
		price: 22,
		matchKeywords: ['epicomb cream', 'epicomb', 'ايبيكومب كريم', 'triamcinolone', 'neomycin', 'nystatin', 'eczema infected', 'intertrigo', 'التهاب جلدي', 'حكة', 'فطريات'],
		usage: 'كريم مركب (كورتيزون + مضاد حيوي + مضاد فطري) لالتهابات جلدية ملتهبة مع عدوى سطحية.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 44) elecortin plus cream 15 gm
	{
		id: 'elecortin-plus-cream-15gm',
		name: 'elecortin plus cream 15 gm',
		genericName: 'mometasone furoate & gentamicin & miconazole nitrate',
		concentration: 'cream',
		price: 41,
		matchKeywords: ['elecortin plus', 'elecortin', 'اليكورتين بلس', 'mometasone', 'gentamicin', 'miconazole', 'fungal', 'intertrigo', 'eczema infected', 'فطريات', 'حكة'],
		usage: 'كريم مركب (كورتيزون + مضاد فطري + مضاد حيوي) للالتهابات الجلدية المختلطة.',
		timing: 'مرة يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرة يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 48) dermotracin aerosol powder 150 ml
	{
		id: 'dermotracin-aerosol-powder-150ml',
		name: 'dermotracin aerosol powder 150 ml',
		genericName: 'bacitracin & neomycin sulphate',
		concentration: 'aerosol powder',
		price: 70,
		matchKeywords: ['dermotracin', 'ديرموتراسين', 'aerosol', 'powder', 'bacitracin', 'neomycin', 'wound', 'burn', 'جروح', 'حروق', 'التهاب جرح'],
		usage: 'بودرة/سبراي موضعي مضاد حيوي للجروح والخدوش السطحية.',
		timing: '٢–٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Spray',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 250,
		calculationRule: fixed('رش طبقة خفيفة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS, 'تجنب الاستنشاق والاقتراب من العين.'],
	},

	// 54) trivatracin aerosol powder
	{
		id: 'trivatracin-aerosol-powder',
		name: 'trivatracin aerosol powder',
		genericName: 'neomycin sulphate & bacitracin & polymyxin b',
		concentration: 'aerosol powder',
		price: 37.5,
		matchKeywords: ['trivatracin', 'تريفاتراسين', 'neomycin', 'bacitracin', 'polymyxin', 'aerosol', 'wound', 'burn', 'جروح', 'حروق'],
		usage: 'بودرة/سبراي موضعي مضاد حيوي مركب للجروح والخدوش السطحية.',
		timing: '٢–٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Spray',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 250,
		calculationRule: fixed('رش طبقة خفيفة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS, 'تجنب الاستنشاق والاقتراب من العين.'],
	},

	// 55) polyderm top. cream 20 gm
	{
		id: 'polyderm-top-cream-20gm',
		name: 'polyderm top. cream 20 gm',
		genericName: 'beclomethasone dipropionate & miconazole nitrate & neomycin',
		concentration: 'cream',
		price: 21,
		matchKeywords: ['polyderm', 'بوليديرم', 'beclomethasone', 'miconazole', 'neomycin', 'fungal', 'intertrigo', 'eczema infected', 'فطريات', 'حكة'],
		usage: 'كريم مركب (كورتيزون + مضاد فطري + مضاد حيوي) لالتهابات جلدية مختلطة.',
		timing: 'مرتين يومياً – ٧–١٤ يوم',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Cream',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة مرتين يومياً لمدة ٧–١٤ يوم'),
		warnings: [...COMMON_STEROID_TOPICAL_WARNINGS],
	},

	// 59) zadmicin 0.1% topical oint 20 gm
	{
		id: 'zadmicin-0.1-oint-20gm',
		name: 'zadmicin 0.1% topical oint 20 gm',
		genericName: 'gentamicin',
		concentration: '0.1%',
		price: 26,
		matchKeywords: ['zadmicin', 'زادمايسين', 'gentamicin', 'ointment', 'جنتاميسين مرهم', 'infected wound', 'folliculitis', 'impetigo', 'جروح ملتهبة', 'التهاب بصيلات', 'حصف'],
		usage: 'مرهم جنتاميسين موضعي لعدوى جلدية بكتيرية سطحية.',
		timing: '٢–٣ مرات يومياً – ٧ أيام',
		category: Category.TOPICAL_ANTIBIOTICS,
		form: 'Ointment',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٢–٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_TOPICAL_WARNINGS],
	},

	// =============================
	// OPHTHALMIC / EAR
	// =============================

	// 9) tobradex eye susp. drops 5 ml
	{
		id: 'tobradex-eye-susp-drops-5ml',
		name: 'tobradex eye susp. drops 5 ml',
		genericName: 'dexamethasone & tobramycin',
		concentration: '5 ml',
		price: 76,
		matchKeywords: ['tobradex drops', 'tobradex', 'توبرادكس', 'tobramycin', 'dexamethasone', 'conjunctivitis', 'red eye', 'eye infection', 'التهاب عين', 'رمد', 'احمرار'],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون) لعلاج التهاب/عدوى بكتيرية بالعين.',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٠ أيام ثم تقليل تدريجي'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 10) tobradex eye oint. 3.5 gm
	{
		id: 'tobradex-eye-oint-3.5gm',
		name: 'tobradex eye oint. 3.5 gm',
		genericName: 'tobramycin & dexamethasone',
		concentration: '3.5 gm',
		price: 63,
		matchKeywords: ['tobradex oint', 'tobradex', 'توبرادكس مرهم', 'tobramycin', 'dexamethasone', 'stye', 'blepharitis', 'التهاب جفن', 'شعيرة'],
		usage: 'مرهم عين (مضاد حيوي + كورتيزون) لالتهاب/عدوى بكتيرية بالجفن/الملتحمة.',
		timing: '٣ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 12) dexatobrin eye susp. drops 5 ml
	{
		id: 'dexatobrin-drops-ophthalmic',
		name: 'Dexatobrin eye susp. drops 5 ml',
		genericName: 'dexamethasone micronized & tobramycin',
		concentration: '5 ml',
		price: 37,
		matchKeywords: ['dexatobrin drops', 'dexatobrin', 'ديكساتوبرين', 'tobramycin', 'dexamethasone', 'eye infection', 'red eye', 'التهاب عين', 'احمرار'],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون) للالتهاب/العدوى البكتيرية.',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 13) dexatrol eye oint. 5 gm
	{
		id: 'dexatrol-eye-oint-5gm',
		name: 'dexatrol eye oint. 5 gm',
		genericName: 'dexamethasone & neomycin sulphate & polymyxin b sulphate',
		concentration: '5 gm',
		price: 27,
		matchKeywords: ['dexatrol oint', 'dexatrol', 'ديكساترول مرهم', 'neomycin', 'polymyxin', 'dexamethasone', 'eye infection', 'blepharitis', 'التهاب جفن', 'التهاب عين'],
		usage: 'مرهم عين (مضاد حيوي مركب + كورتيزون) للالتهاب/العدوى البكتيرية.',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 16) tobrin 0.3% eye.oint. 5 gm
	{
		id: 'tobrin-0.3-eye-oint-5gm',
		name: 'tobrin 0.3% eye.oint. 5 gm',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 23,
		matchKeywords: ['tobrin oint', 'tobrin 0.3', 'توبرين مرهم', 'tobramycin ointment', 'stye', 'conjunctivitis', 'رمد', 'شعيرة', 'التهاب عين'],
		usage: 'مرهم توبراسين للعين لعلاج الالتهابات البكتيرية.',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS],
	},

	// 17) dexatrol eye/ear drops 5 ml
	{
		id: 'dexatrol-eye-ear-drops-5ml',
		name: 'dexatrol eye/ear drops 5 ml',
		genericName: 'dexamethasone & neomycin sulphate & polymyxin b sulphate',
		concentration: '5 ml',
		price: 27,
		matchKeywords: ['dexatrol drops', 'dexatrol', 'ديكساترول', 'ear drops', 'eye drops', 'otitis externa', 'التهاب اذن خارجية', 'التهاب عين', 'احمرار'],
		usage: 'قطرة (عين/أذن) مضاد حيوي + كورتيزون.',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('عين: قطرة واحدة ٤ مرات يومياً / أذن: ٣ قطرات ٤ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS, 'الأذن: يُتجنب عند ثقب طبلة الأذن.'],
	},

	// 19) optidex -t eye drops 5 ml
	{
		id: 'optidex-t-eye-drops-5ml',
		name: 'optidex -t eye drops 5 ml',
		genericName: 'dexamethasone & tobramycin',
		concentration: '5 ml',
		price: 48,
		matchKeywords: ['optidex t', 'optidex', 'اوبتيدكس', 'tobramycin', 'dexamethasone', 'red eye', 'eye infection', 'التهاب عين', 'احمرار'],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون).',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 20) otal ear drops 5 ml
	{
		id: 'otal-ear-drops-5ml',
		name: 'otal ear drops 5 ml',
		genericName: 'dexamethasone & gramicidin & framycetin & cinchocaine',
		concentration: '5 ml',
		price: 19,
		matchKeywords: ['otal', 'اوتال', 'ear drops', 'otitis externa', 'ear pain', 'itching ear', 'التهاب اذن خارجية', 'وجع اذن', 'حكة اذن'],
		usage: 'قطرة أذن (مضاد حيوي + كورتيزون + مخدر موضعي) لتخفيف ألم/التهاب الأذن الخارجية.',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.EAR_CARE,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('٣ قطرات في الأذن المصابة ٣ مرات يومياً لمدة ٧ أيام'),
		warnings: ['يحتوي على كورتيزون ومخدر موضعي.', 'ممنوع الاستخدام عند ثقب طبلة الأذن.'],
	},

	// 22) tobrex 0.3% eye oint. 3.5 gm
	{
		id: 'tobrex-eye-oint-3.5',
		name: 'Tobrex 0.3% eye oint. 3.5 gm',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 18.7,
		matchKeywords: ['tobrex oint', 'tobrex', 'توبركس مرهم', 'tobramycin', 'stye', 'conjunctivitis', 'رمد', 'شعيرة', 'التهاب عين'],
		usage: 'مرهم توبراسين للعين لعلاج الالتهابات البكتيرية.',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS],
	},
	{
		id: 'tobrin-0.3-eye-drops-5ml',
		name: 'tobrin 0.3% eye drops 5 ml',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 23,
		matchKeywords: ['tobrin drops', 'tobrin 0.3', 'توبرين قطرة', 'tobramycin', 'conjunctivitis', 'eye infection', 'رمد', 'التهاب عين'],
		usage: 'قطرة توبراسين لعلاج التهابات العين البكتيرية.',
		timing: 'كل ٤ ساعات – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة كل ٤ ساعات لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS],
	},

	// 27) dexatobrin eye oint. 5 gm
	{
		id: 'dexatobrin-eye-oint-5gm',
		name: 'dexatobrin eye oint. 5 gm',
		genericName: 'dexamethasone & tobramycin',
		concentration: '5 gm',
		price: 37,
		matchKeywords: ['dexatobrin oint', 'dexatobrin', 'ديكساتوبرين مرهم', 'tobramycin', 'dexamethasone', 'blepharitis', 'stye', 'التهاب جفن', 'شعيرة'],
		usage: 'مرهم عين (مضاد حيوي + كورتيزون).',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 31) neopol eye/ear drops 10 ml
	{
		id: 'neopol-eye-ear-drops-10ml',
		name: 'neopol eye/ear drops 10 ml',
		genericName: 'neomycin & polymyxin',
		concentration: '10 ml',
		price: 23,
		matchKeywords: ['neopol', 'نيوبول', 'neomycin', 'polymyxin', 'ear drops', 'eye drops', 'otitis externa', 'conjunctivitis', 'التهاب اذن خارجية', 'التهاب عين'],
		usage: 'قطرة (عين/أذن) مضاد حيوي مركب.',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('عين: قطرة واحدة ٤ مرات يومياً / أذن: ٣ قطرات ٤ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS, 'ممنوع الاستخدام عند ثقب طبلة الأذن.'],
	},

	// 36) avazir 0.3% eye oint. 5 gm
	{
		id: 'avazir-0.3-eye-oint-5gm',
		name: 'avazir 0.3% eye oint. 5 gm',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 26,
		matchKeywords: ['avazir oint', 'avazir', 'افازير مرهم', 'tobramycin', 'conjunctivitis', 'stye', 'رمد', 'شعيرة'],
		usage: 'مرهم توبراسين للعين لعلاج الالتهابات البكتيرية.',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS],
	},

	// 38) co- avazir eye oint. 5 gm
	{
		id: 'co-avazir-eye-oint-5gm',
		name: 'co- avazir eye oint. 5 gm',
		genericName: 'dexamethasone base (micronized) & tobramycin',
		concentration: '5 gm',
		price: 30,
		matchKeywords: ['co-avazir oint', 'co avazir', 'افازير كومبو مرهم', 'tobramycin', 'dexamethasone', 'eye infection', 'red eye', 'التهاب عين', 'احمرار'],
		usage: 'مرهم عين (مضاد حيوي + كورتيزون).',
		timing: '٣ مرات يومياً – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Ointment',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('شريط رفيع في الجفن السفلي للعين المصابة ٣ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 43) avazir 0.3% eye drops 10 ml
	{
		id: 'avazir-0.3-eye-drops-10ml',
		name: 'avazir 0.3% eye drops 10 ml',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 20,
		matchKeywords: ['avazir drops', 'avazir 0.3', 'افازير قطرة', 'tobramycin', 'conjunctivitis', 'eye infection', 'رمد', 'التهاب عين'],
		usage: 'قطرة توبراسين لعلاج التهابات العين البكتيرية.',
		timing: 'كل ٤ ساعات – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة كل ٤ ساعات لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS],
	},

	// 45) loteranol comp eye susp. drops 5 ml
	{
		id: 'loteranol-comp-eye-susp-drops-5ml',
		name: 'loteranol comp eye susp. drops 5 ml',
		genericName: 'loteprednol etabonate & tobramycin',
		concentration: '5 ml',
		price: 51,
		matchKeywords: ['loteranol comp', 'loteranol', 'لوتيرانول', 'loteprednol', 'tobramycin', 'eye inflammation', 'eye infection', 'التهاب عين', 'احمرار'],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون).',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 46) tobrex 0.3% eye drops 5 ml
	{
		id: 'tobrex-0.3-drops',
		name: 'Tobrex 0.3% eye drops 5 ml',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 32.5,
		matchKeywords: ['tobrex drops', 'tobrex 0.3', 'توبركس قطرة', 'tobramycin', 'conjunctivitis', 'eye infection', 'رمد', 'التهاب عين'],
		usage: 'قطرة توبراسين لعلاج التهابات العين البكتيرية.',
		timing: 'كل ٤ ساعات – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة كل ٤ ساعات لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS, 'صلاحية القطرة بعد الفتح شهر واحد.'],
	},

	// 47) co- avazir eye susp. drops 10 ml
	{
		id: 'co-avazir-eye-susp-drops-10ml',
		name: 'co- avazir eye susp. drops 10 ml',
		genericName: 'tobramycin & dexamethasone',
		concentration: '10 ml',
		price: 39,
		matchKeywords: ['co-avazir drops', 'co avazir', 'افازير كومبو قطرة', 'tobramycin', 'dexamethasone', 'red eye', 'eye infection', 'التهاب عين', 'احمرار'],
		usage: 'قطرة عين (مضاد حيوي + كورتيزون).',
		timing: '٤ مرات يومياً – ٧–١٠ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 24,
		maxAgeMonths: 1200,
		minWeight: 10,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: [...COMMON_STEROID_EYE_WARNINGS],
	},

	// 57) tobractiva 0.3% eye drops 5 ml
	{
		id: 'tobractiva-0.3-eye-drops-5ml',
		name: 'tobractiva 0.3% eye drops 5 ml',
		genericName: 'tobramycin',
		concentration: '0.3%',
		price: 18,
		matchKeywords: ['tobractiva', 'توبركتيفا', 'tobramycin', 'conjunctivitis', 'eye infection', 'رمد', 'التهاب عين'],
		usage: 'قطرة توبراسين لعلاج التهابات العين البكتيرية.',
		timing: 'كل ٤ ساعات – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة كل ٤ ساعات لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS],
	},

	// 58) tobrex 2x 0.3% eye drops 5 ml
	{
		id: 'tobrex-2x-0.3-eye-drops-5ml',
		name: 'tobrex 2x 0.3% eye drops 5 ml',
		genericName: 'tobramycin',
		concentration: '0.3% (2 bottles)',
		price: 30,
		matchKeywords: ['tobrex 2x', 'tobrex 2', 'توبركس ٢', 'tobramycin', 'conjunctivitis', 'eye infection', 'رمد', 'التهاب عين'],
		usage: 'قطرة توبراسين لعلاج التهابات العين البكتيرية (عبوتين).',
		timing: 'كل ٤ ساعات – ٧ أيام',
		category: Category.ANTIBIOTICS_OPHTHALMIC,
		form: 'Drops',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('قطرة واحدة في العين المصابة كل ٤ ساعات لمدة ٧ أيام'),
		warnings: [...COMMON_EYE_DROP_WARNINGS, 'صلاحية القطرة بعد الفتح شهر واحد.'],
	},

	// =============================
	// GIT (Streptoquin)
	// =============================

	// 5) streptoquin 20 tabs.
	{
		id: 'streptoquin-20-tabs',
		name: 'streptoquin 20 tabs.',
		genericName: 'di-iodoquinoilin & phthalyl sulfathiazole & streptomycin sulphate',
		concentration: 'tabs',
		price: 46,
		matchKeywords: ['streptoquin', 'ستربتوكين', 'diarrhea', 'antidiarrheal', 'intestinal antiseptic', 'amoebiasis', 'cramps', 'اسهال', 'مطهر معوي', 'اميبا', 'مغص', '#diarrhea'],
		usage: 'مطهر معوي مركب لعلاج الإسهال البكتيري/الأميبي المصحوب بمغص—يُستخدم للبالغين فقط غالباً.',
		timing: 'كل ٨ ساعات بعد الأكل – ٥–٧ أيام',
		category: Category.ANTIDIARRHEAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد كل ٨ ساعات بعد الأكل لمدة ٥–٧ أيام'),
		warnings: [
			'الحمل/الرضاعة: يُتجنب؛ إن لزم: أقل جرعة وأقصر مدة.',
			'قد يسبب دوخة/طنين أذن: أوقفه وراجع طبيب.',
			'مرضى حساسية السلفا/اضطرابات الغدة/حساسية اليود: يُستعمل بحذر أو يُتجنب.',
		],
	},

	// 56) streptoquin dry suspension 60 ml
	{
		id: 'streptoquin-dry-susp-60ml',
		name: 'streptoquin dry suspension 60 ml',
		genericName: 'homatropine methylbromide & streptomycin sulphate & phthalyl sulfathiazole',
		concentration: 'dry suspension',
		price: 18,
		matchKeywords: ['streptoquin suspension', 'streptoquin dry suspension', 'ستربتوكين شراب', 'diarrhea', 'cramps', 'intestinal antiseptic', 'اسهال', 'مغص', 'مطهر معوي'],
		usage: 'معلق مركب للإسهال المصحوب بمغص. الجرعة: ٥–١٠ مل ٣ مرات يومياً للبالغين. يُفضّل بدائل أحدث للأطفال.',
		timing: 'كل ٨ ساعات بعد الأكل – ٥–٧ أيام',
		category: Category.ANTIDIARRHEAL,
		form: 'Suspension',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('٥–١٠ مل كل ٨ ساعات بعد الأكل لمدة ٥–٧ أيام (بالغين)'),
		warnings: ['غير مفضل للأطفال بسبب التركيبة (مضادات/مضاد كولين).', 'الحمل/الرضاعة: يُتجنب؛ إن لزم: أقل جرعة وأقصر مدة.'],
	},

	// =============================
	// HEMORRHOIDS
	// =============================

	// 32) sediproct 6 supp.
	{
		id: 'sediproct-6-supp',
		name: 'sediproct 6 supp.',
		genericName: 'cinchocaine hydrochloride & hydrocortisone & framycetin',
		concentration: 'suppositories',
		price: 26,
		matchKeywords: ['sediproct', 'سيديبروكت', 'hemorrhoids', 'piles', 'anal pain', 'itching', 'بواسير', 'حكة شرج', 'ألم شرج'],
		usage: 'لبوس للبواسير (مخدر موضعي + كورتيزون + مضاد حيوي) لتقليل الألم/الحكة والالتهاب.',
		timing: 'مرتين يومياً – ٥–٧ أيام',
		category: Category.FIRST_AID,
		form: 'Suppositories',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('لبوسة شرجية مرتين يومياً (صباحاً ومساءً) لمدة ٥–٧ أيام'),
		warnings: ['يحتوي على كورتيزون: لا تطوّل الاستخدام.', 'إذا يوجد نزيف شديد/دوخة: اطلب تقييم طبي.'],
	},

	// =============================
	// SYSTEMIC INJECTABLES
	// =============================

	// 24) amikacin amoun 100mg/2ml i.v. vial
	{
		id: 'amikacin-amoun-100mg-2ml-vial',
		name: 'amikacin amoun 100mg/2ml i.v. vial',
		genericName: 'amikacin',
		concentration: '100mg/2ml',
		price: 5,
		matchKeywords: ['amikacin 100 iv', 'amikacin iv', 'amikacin 100', 'amikacin amoun 100', 'amoun amikacin', 'amikacin injection', 'أميكاسين ١٠٠', 'أمبول', 'حقن', 'iv', 'حقن وريد', 'sepsis', 'uti', 'severe infection', 'تجرثم دم', 'عدوى شديدة', 'التهاب مجرى البول', '#antibiotics', '#aminoglycoside'],
		usage: 'أميكاسين حقن وريد فقط لعدوى شديدة—للاستخدام بالمستشفى/العيادة فقط؛ يُعطى وريد/عضل مع متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('100mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// amikacin amoun 100mg/2ml i.m. vial
	{
		id: 'amikacin-amoun-100mg-2ml-im-vial',
		name: 'amikacin amoun 100mg/2ml i.m. vial',
		genericName: 'amikacin',
		concentration: '100mg/2ml',
		price: 5,
		matchKeywords: ['amikacin 100 im', 'amikacin im', 'amikacin 100', 'amikacin amoun 100', 'amoun amikacin', 'amikacin injection', 'أميكاسين ١٠٠', 'أمبول', 'حقن', 'im', 'حقن عضل', 'sepsis', 'uti', 'severe infection'],
		usage: 'أميكاسين حقن عضل فقط لعدوى شديدة—للاستخدام بالمستشفى/العيادة فقط؛ يُعطى وريد/عضل مع متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('100mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 33) amikacin amoun 250mg/2ml i.v. vial
	{
		id: 'amikacin-amoun-250mg-2ml-vial',
		name: 'amikacin amoun 250mg/2ml i.v. vial',
		genericName: 'amikacin',
		concentration: '250mg/2ml',
		price: 6.5,
		matchKeywords: ['amikacin 250 iv', 'amikacin iv', 'amikacin 250', 'amikacin amoun 250', 'أميكاسين ٢٥٠', 'حقن', 'vial', 'iv', 'حقن وريد'],
		usage: 'أميكاسين حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('250mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// amikacin amoun 250mg/2ml i.m. vial
	{
		id: 'amikacin-amoun-250mg-2ml-im-vial',
		name: 'amikacin amoun 250mg/2ml i.m. vial',
		genericName: 'amikacin',
		concentration: '250mg/2ml',
		price: 6.5,
		matchKeywords: ['amikacin 250 im', 'amikacin im', 'amikacin 250', 'amikacin amoun 250', 'أميكاسين ٢٥٠', 'حقن', 'vial', 'im', 'حقن عضل'],
		usage: 'أميكاسين حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('250mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 25) amikacin 500mg/2ml i.v. vial (Amoun)
	{
		id: 'amikacin-amoun-500mg-vial',
		name: 'amikacin 500mg/2ml i.v. vial (Amoun)',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 34,
		matchKeywords: ['amikacin 500 iv', 'amikacin iv', 'amikacin 500', 'amikacin 500mg/2ml', 'amikacin amoun 500', 'أميكاسين ٥٠٠', 'حقن', 'vial', 'iv', 'حقن وريد'],
		usage: 'أميكاسين حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// amikacin 500mg/2ml i.m. vial (Amoun)
	{
		id: 'amikacin-amoun-500mg-im-vial',
		name: 'amikacin 500mg/2ml i.m. vial (Amoun)',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 34,
		matchKeywords: ['amikacin 500 im', 'amikacin im', 'amikacin 500', 'amikacin 500mg/2ml', 'amikacin amoun 500', 'أميكاسين ٥٠٠', 'حقن', 'vial', 'im', 'حقن عضل'],
		usage: 'أميكاسين حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 26) amikin 500mg/2ml i.v. vial (n/a)
	{
		id: 'amikin-500mg-2ml-vial',
		name: 'amikin 500mg/2ml i.v. vial (n/a)',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 18,
		matchKeywords: ['amikin 500 iv', 'amikin iv', 'amikin 500', 'amikin', 'amikacin 500 2ml', 'اميكن', 'أميكاسين', 'حقن', 'iv', 'حقن وريد'],
		usage: 'أميكاسين حقن وريد فقط (Amikin) لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// amikin 500mg/2ml i.m. vial (n/a)
	{
		id: 'amikin-500mg-2ml-im-vial',
		name: 'amikin 500mg/2ml i.m. vial (n/a)',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 18,
		matchKeywords: ['amikin 500 im', 'amikin im', 'amikin 500', 'amikin', 'amikacin 500 2ml', 'اميكن', 'أميكاسين', 'حقن', 'im', 'حقن عضل'],
		usage: 'أميكاسين حقن عضل فقط (Amikin) لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 29) garamycin 80mg/2ml i.v. 3 amps.
	{
		id: 'garamycin-80mg-2ml-3-amps',
		name: 'garamycin 80mg/2ml i.v. 3 amps.',
		genericName: 'gentamicin',
		concentration: '80mg/2ml',
		price: 60,
		matchKeywords: ['garamycin 80 iv', 'garamycin iv', 'garamycin 80', 'gentamicin 80 2ml', 'جارامايسين ٨٠', 'أمبول', 'حقن', 'iv', 'حقن وريد', 'sepsis', 'uti'],
		usage: 'جنتاميسين حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('80mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// garamycin 80mg/2ml i.m. 3 amps.
	{
		id: 'garamycin-80mg-2ml-3-amps-im',
		name: 'garamycin 80mg/2ml i.m. 3 amps.',
		genericName: 'gentamicin',
		concentration: '80mg/2ml',
		price: 60,
		matchKeywords: ['garamycin 80 im', 'garamycin im', 'garamycin 80', 'gentamicin 80 2ml', 'جارامايسين ٨٠', 'أمبول', 'حقن', 'im', 'حقن عضل', 'sepsis', 'uti'],
		usage: 'جنتاميسين حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('80mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 51) epigent 20mg/2ml i.v. 3 amp.
	{
		id: 'epigent-20mg-2ml-3-amp',
		name: 'epigent 20mg/2ml i.v. 3 amp.',
		genericName: 'gentamicin (as sulfate)',
		concentration: '20mg/2ml',
		price: 24,
		matchKeywords: ['epigent 20 iv', 'epigent iv', 'epigent 20', 'epigent', 'ايبيجنت ٢٠', 'gentamicin 20', 'أمبول', 'حقن', 'iv', 'حقن وريد'],
		usage: 'جنتاميسين (Epigent) حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('20mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// epigent 20mg/2ml i.m. 3 amp.
	{
		id: 'epigent-20mg-2ml-3-amp-im',
		name: 'epigent 20mg/2ml i.m. 3 amp.',
		genericName: 'gentamicin (as sulfate)',
		concentration: '20mg/2ml',
		price: 24,
		matchKeywords: ['epigent 20 im', 'epigent im', 'epigent 20', 'epigent', 'ايبيجنت ٢٠', 'gentamicin 20', 'أمبول', 'حقن', 'im', 'حقن عضل'],
		usage: 'جنتاميسين (Epigent) حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('20mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 52) epigent 80mg/2ml i.v. 3 amps.
	{
		id: 'epigent-80mg-2ml-3-amps',
		name: 'epigent 80mg/2ml i.v. 3 amps.',
		genericName: 'gentamicin',
		concentration: '80mg/2ml',
		price: 15,
		matchKeywords: ['epigent 80 iv', 'epigent iv', 'epigent 80', 'epigent', 'ايبيجنت ٨٠', 'gentamicin 80', 'أمبول', 'حقن', 'iv', 'حقن وريد'],
		usage: 'جنتاميسين (Epigent) حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('80mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// epigent 80mg/2ml i.m. 3 amps.
	{
		id: 'epigent-80mg-2ml-3-amps-im',
		name: 'epigent 80mg/2ml i.m. 3 amps.',
		genericName: 'gentamicin',
		concentration: '80mg/2ml',
		price: 15,
		matchKeywords: ['epigent 80 im', 'epigent im', 'epigent 80', 'epigent', 'ايبيجنت ٨٠', 'gentamicin 80', 'أمبول', 'حقن', 'im', 'حقن عضل'],
		usage: 'جنتاميسين (Epigent) حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('80mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 53) garamycin 20mg/2ml i.v. 6 amp.
	{
		id: 'garamycin-20mg-2ml-6-amp',
		name: 'garamycin 20mg/2ml i.v. 6 amp.',
		genericName: 'gentamicin',
		concentration: '20mg/2ml',
		price: 66,
		matchKeywords: ['garamycin 20 iv', 'garamycin iv', 'garamycin 20', 'gentamicin 20 2ml', 'جارامايسين ٢٠', 'أمبول', 'حقن', 'iv', 'حقن وريد'],
		usage: 'جنتاميسين حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('20mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// garamycin 20mg/2ml i.m. 6 amp.
	{
		id: 'garamycin-20mg-2ml-6-amp-im',
		name: 'garamycin 20mg/2ml i.m. 6 amp.',
		genericName: 'gentamicin',
		concentration: '20mg/2ml',
		price: 66,
		matchKeywords: ['garamycin 20 im', 'garamycin im', 'garamycin 20', 'gentamicin 20 2ml', 'جارامايسين ٢٠', 'أمبول', 'حقن', 'im', 'حقن عضل'],
		usage: 'جنتاميسين حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Ampoules',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: gentamicin('20mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 34) amikacin eipico 100mg/2ml i.v. vial
	{
		id: 'amikacin-eipico-100mg-2ml-vial',
		name: 'amikacin eipico 100mg/2ml i.v. vial',
		genericName: 'amikacin',
		concentration: '100mg/2ml',
		price: 7.5,
		matchKeywords: ['amikacin eipico 100 iv', 'eipico amikacin 100 iv', 'amikacin eipico 100', 'eipico amikacin 100', 'أميكاسين ايبيكو ١٠٠', 'حقن', 'iv', 'حقن وريد'],
		usage: 'أميكاسين (Eipico) حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('100mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// amikacin eipico 100mg/2ml i.m. vial
	{
		id: 'amikacin-eipico-100mg-2ml-im-vial',
		name: 'amikacin eipico 100mg/2ml i.m. vial',
		genericName: 'amikacin',
		concentration: '100mg/2ml',
		price: 7.5,
		matchKeywords: ['amikacin eipico 100 im', 'eipico amikacin 100 im', 'amikacin eipico 100', 'eipico amikacin 100', 'أميكاسين ايبيكو ١٠٠', 'حقن', 'im', 'حقن عضل'],
		usage: 'أميكاسين (Eipico) حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('100mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 35) amikacin eipico 500mg/2ml i.v. vial
	{
		id: 'amikacin-eipico-500mg-2ml-vial',
		name: 'amikacin eipico 500mg/2ml i.v. vial',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 16.5,
		matchKeywords: ['amikacin eipico 500 iv', 'eipico amikacin 500 iv', 'amikacin eipico 500', 'eipico amikacin 500', 'أميكاسين ايبيكو ٥٠٠', 'حقن', 'iv', 'حقن وريد'],
		usage: 'أميكاسين (Eipico) حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// amikacin eipico 500mg/2ml i.m. vial
	{
		id: 'amikacin-eipico-500mg-2ml-im-vial',
		name: 'amikacin eipico 500mg/2ml i.m. vial',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 16.5,
		matchKeywords: ['amikacin eipico 500 im', 'eipico amikacin 500 im', 'amikacin eipico 500', 'eipico amikacin 500', 'أميكاسين ايبيكو ٥٠٠', 'حقن', 'im', 'حقن عضل'],
		usage: 'أميكاسين (Eipico) حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 49) emijectacin 100mg/2ml i.v. vial
	{
		id: 'emijectacin-100mg-2ml-vial',
		name: 'emijectacin 100mg/2ml i.v. vial',
		genericName: 'amikacin',
		concentration: '100mg/2ml',
		price: 13,
		matchKeywords: ['emijectacin 100 iv', 'emijectacin iv', 'emijectacin 100', 'emijectacin', 'اميجكتاسين ١٠٠', 'amikacin', 'حقن', 'iv', 'حقن وريد'],
		usage: 'أميكاسين (Emijectacin) حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('100mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// emijectacin 100mg/2ml i.m. vial
	{
		id: 'emijectacin-100mg-2ml-im-vial',
		name: 'emijectacin 100mg/2ml i.m. vial',
		genericName: 'amikacin',
		concentration: '100mg/2ml',
		price: 13,
		matchKeywords: ['emijectacin 100 im', 'emijectacin im', 'emijectacin 100', 'emijectacin', 'اميجكتاسين ١٠٠', 'amikacin', 'حقن', 'im', 'حقن عضل'],
		usage: 'أميكاسين (Emijectacin) حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('100mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// 50) emijectacin 500mg/2ml i.v. vial
	{
		id: 'emijectacin-500mg-2ml-vial',
		name: 'emijectacin 500mg/2ml i.v. vial',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 26,
		matchKeywords: ['emijectacin 500 iv', 'emijectacin iv', 'emijectacin 500', 'emijectacin', 'اميجكتاسين ٥٠٠', 'amikacin', 'حقن', 'iv', 'حقن وريد'],
		usage: 'أميكاسين (Emijectacin) حقن وريد فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},

	// emijectacin 500mg/2ml i.m. vial
	{
		id: 'emijectacin-500mg-2ml-im-vial',
		name: 'emijectacin 500mg/2ml i.m. vial',
		genericName: 'amikacin',
		concentration: '500mg/2ml',
		price: 26,
		matchKeywords: ['emijectacin 500 im', 'emijectacin im', 'emijectacin 500', 'emijectacin', 'اميجكتاسين ٥٠٠', 'amikacin', 'حقن', 'im', 'حقن عضل'],
		usage: 'أميكاسين (Emijectacin) حقن عضل فقط لعدوى شديدة. للاستخدام بالمستشفى/العيادة فقط؛ متابعة وظائف الكلى.',
		timing: 'كل ٢٤ ساعة – ٥–١٠ أيام',
		category: Category.AMINOGLYCOSIDES,
		form: 'Vial',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: amikacin('500mg/2ml'),
		warnings: [...aminoglycosideInjectionWarnings],
	},
];

