import { Medication, Category } from '../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);

const COMMON_FQ_WARNINGS = [
	'ممنوع للأطفال أقل من ١٨ سنة (خطر على الأوتار والمفاصل والغضاريف).',
	'ممنوع أثناء الحمل والرضاعة.',
	'يُفصل عن الألبان/الكالسيوم/الحديد/مضادات الحموضة بساعتين على الأقل.',
	'خطر التهاب/تمزق الأوتار (خاصة وتر أخيل)—يزداد مع الكورتيزون وكبار السن. أوقف فوراً عند ألم/تورم الأوتار.',
	'قد يسبب اعتلال الأعصاب الطرفية (تنميل/وخز/ضعف بالأطراف)—أوقفه فوراً عند الظهور.',
	'قد يطيل QT interval—حذر مع أدوية القلب/اضطراب نظم القلب.',
	'يسبب حساسية للضوء—تجنب التعرض المباشر للشمس واستخدم واقي شمس.',
	'شرب سوائل كافية (٢–٣ لتر يومياً) لتقليل خطر ترسبات الكلى.',
	'خطر نادر: تمدد/تسلخ الشريان الأورطي—أوقفه واطلب طوارئ عند ألم صدر/بطن مفاجئ شديد.',
];

const EYE_FQ_WARNINGS = [
	'للاستخدام الخارجي للعين فقط—لا تُستخدم في الفم أو الأذن.',
	'لا تلمس طرف القطارة بالعين/الرموش لتجنب تلوث العبوة.',
	'اغسل يديك قبل الاستخدام.',
	'إذا لم تتحسن الأعراض خلال ٤٨–٧٢ ساعة: راجع طبيب عيون.',
];

const EAR_FQ_WARNINGS = [
	'للأذن فقط—لا تُستخدم في العين.',
	'يُدفأ القطرة بوضعها في اليد قبل الاستخدام.',
	'ممنوع عند ثقب طبلة الأذن أو الشك فيه؛ استخدم بديل فموي أو قطرة أذن غير أوتوتوكسيك.',
];

const MOXIFLOXACIN_WARNINGS = [
	...COMMON_FQ_WARNINGS,
	'موكسيفلوكساسين أعلى خطورة لإطالة QT من بقية الفلوروكينولونات—ممنوع مع أدوية تطيل QT.',
	'يُراقب ECG في المرضى المعرضين للخطر (كبار السن، نقص بوتاسيوم/ماغنسيوم، أدوية قلب).',
];

const METRONIDAZOLE_COMBO_WARNINGS = [
	...COMMON_FQ_WARNINGS,
	'يمنع الكحول تماماً—قد يسبب تفاعل شديد (غثيان/قيء/احمرار/خفقان).',
	'قد يسبب طعم معدني في الفم—هذا طبيعي.',
	'أكمل المدة المقررة (٧–١٤ يوم غالباً)؛ لا تُوقف مبكراً حتى مع تحسّن الأعراض.',
];

const TINIDAZOLE_COMBO_WARNINGS = [
	...COMMON_FQ_WARNINGS,
	'يمنع الكحول—قد يسبب تفاعل شديد.',
	'أكمل المدة المقررة (٧–١٤ يوم غالباً)؛ لا تُوقف مبكراً حتى مع تحسّن الأعراض.',
];

const fixed = (t: string) => () => t;

export const FLUOROQUINOLONES_GROUP: Medication[] = [
	// ==================== CIPROFLOXACIN ====================
	{ id: 'ciproquin-500mg-10-tab', name: 'ciproquin 500mg 10 tab', genericName: 'ciprofloxacin', concentration: '500mg', price: 50, matchKeywords: ['ciproquin', 'ciprofloxacin', 'سيبروكين', 'سيبروفلوكساسين', 'uti', 'typhoid', 'التهاب مجرى البول', 'التهاب بروستاتا', 'تيفود', 'اسهال السفر', "traveler's diarrhea", 'prostatitis', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة/تيفود) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'cipro-500mg-20-fc-tab', name: 'cipro 500mg 20 f.c.tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 54, matchKeywords: ['cipro 500', 'ciprofloxacin', 'سيبرو', 'سيبروفلوكساسين', 'uti', 'التهاب مجرى البول', 'التهاب بروستاتا', 'تيفود', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/الجهاز الهضمي/التيفود.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'cipro-500mg-10-fc-tab', name: 'cipro 500mg 10 f.c.tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 53, matchKeywords: ['cipro 500', 'سيبرو', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofar-500mg-10-fc-tab', name: 'ciprofar 500mg 10 f.c.tab', genericName: 'ciprofloxacin', concentration: '500mg', price: 69, matchKeywords: ['ciprofar 500', 'سيبروفار', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofar-750mg-10-fc-tab', name: 'ciprofar 750mg 10 f.c. tab.', genericName: 'ciprofloxacin', concentration: '750mg', price: 86, matchKeywords: ['ciprofar 750', 'سيبروفار ٧٥٠', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciproquin-750mg-10-fc-tab', name: 'ciproquin 750mg 10 f.c. tab.', genericName: 'ciprofloxacin', concentration: '750mg', price: 74, matchKeywords: ['ciproquin 750', 'سيبروكين ٧٥٠', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprocin-500mg-10-fc-tab', name: 'ciprocin 500mg 10 f.c.tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 53, matchKeywords: ['ciprocin 500', 'سيبروسين', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprocin-750mg-10-fc-tab', name: 'ciprocin 750mg 10 f.c. tab.', genericName: 'ciprofloxacin', concentration: '750mg', price: 68.5, matchKeywords: ['ciprocin 750', 'سيبروسين ٧٥٠', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofloxacin-organo-500mg-10-fc-tab', name: 'ciprofloxacin-organo 500 mg 10 f.c.tabs.', genericName: 'ciprofloxacin', concentration: '500mg', price: 63, matchKeywords: ['ciprofloxacin organo', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofloxacin-amriya-500mg-10-fc-tab', name: 'ciprofloxacin-amriya 500mg 10 f.c. tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 63, matchKeywords: ['ciprofloxacin amriya', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofloxacin-organo-750mg-10-tab', name: 'ciprofloxacin-organo 750 mg 10 tab', genericName: 'ciprofloxacin', concentration: '750mg', price: 89, matchKeywords: ['ciprofloxacin organo 750', '#antibiotics'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'cipro-ear-drops-10ml', name: 'cipro 0.3% ear drops 10 ml', genericName: 'ciprofloxacin', concentration: '0.3%', price: 15, matchKeywords: ['cipro ear', 'ear drops', 'قطرة اذن', 'otitis externa', 'التهاب اذن خارجية', '#antibiotics', '#quinolone'], usage: 'قطرة أذن سيبروفلوكساسين لالتهاب الأذن الخارجية.', timing: '٣–٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('٣–٤ نقط في الأذن المصابة كل ٦–٨ ساعات لمدة ٧ أيام'), warnings: [...EAR_FQ_WARNINGS] },
	// ==================== CIPROFLOXACIN COMBINATIONS ====================
	{ id: 'ciprodiazole-500-500mg-20-fc-tabs', name: 'ciprodiazole 500/500mg 20 f.c. tabs', genericName: 'ciprofloxacin hydrochloride & metronidazole', concentration: '500mg/500mg', price: 148, matchKeywords: ['ciprodiazole', 'سيبروديازول', 'dental', 'خراج', 'diabetic foot', 'قدم سكري', 'خراج اسنان', 'التهاب بروستاتا', 'عدوى بطن', '#antibiotics', '#antiprotozoal'], usage: 'سيبروفلوكساسين + ميترونيدازول لخراج الأسنان/القدم السكري/عدوى البطن الشديدة.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص كل ١٢ ساعة لمدة ٧–١٤ يوم بعد الأكل'), warnings: METRONIDAZOLE_COMBO_WARNINGS },
	{ id: 'queenciprozole-500-600mg-20-tabs', name: 'queenciprozole 500/600mg 20 tabs.', genericName: 'ciprofloxacin & tinidazole', concentration: '500mg/600mg', price: 124, matchKeywords: ['queenciprozole', 'كوين سيبروزول', '#antibiotics'], usage: 'سيبروفلوكساسين + تينيدازول لعدوى الجهاز الهضمي/الأميبا.', timing: 'كل ١٢ ساعة – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص كل ١٢ ساعة لمدة ٥–٧ أيام بعد الأكل'), warnings: TINIDAZOLE_COMBO_WARNINGS },
	{ id: 'tinifloxacin-10-tab', name: 'tinifloxacin 10 tab.', genericName: 'ciprofloxacin & tinidazole', concentration: '500mg/600mg', price: 76, matchKeywords: ['tinifloxacin', 'تينيفلوكساسين', '#antibiotics', '#antiprotozoal'], usage: 'سيبروفلوكساسين + تينيدازول لعدوى الجهاز الهضمي/الأميبا.', timing: 'كل ١٢ ساعة – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص كل ١٢ ساعة لمدة ٥–٧ أيام بعد الأكل'), warnings: TINIDAZOLE_COMBO_WARNINGS },
	{ id: 'tinifloxacin-20-tab', name: 'tinifloxacin 20 tab.', genericName: 'ciprofloxacin & tinidazole', concentration: '500mg/600mg', price: 152, matchKeywords: ['tinifloxacin 20', '#quinolone', '#antiprotozoal'], usage: 'سيبروفلوكساسين + تينيدازول لعدوى الجهاز الهضمي/الأميبا.', timing: 'كل ١٢ ساعة – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص كل ١٢ ساعة لمدة ٥–٧ أيام بعد الأكل'), warnings: TINIDAZOLE_COMBO_WARNINGS },
	{ id: 'conafutal-500-600mg-20-fc-tabs', name: 'conafutal 500/600 mg 20 f.c.tabs.', genericName: 'ciprofloxacin & tinidazole', concentration: '500mg/600mg', price: 148, matchKeywords: ['conafutal', 'كونافيوتال', '#quinolone', '#antiprotozoal'], usage: 'سيبروفلوكساسين + تينيدازول لعدوى الجهاز الهضمي/الأميبا.', timing: 'كل ١٢ ساعة – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص كل ١٢ ساعة لمدة ٥–٧ أيام بعد الأكل'), warnings: TINIDAZOLE_COMBO_WARNINGS },
	// ==================== LEVOFLOXACIN ====================
	{ id: 'tavacin-500mg-5-fc-tab', name: 'tavacin 500mg 5 f.c. tab', genericName: 'levofloxacin', concentration: '500mg', price: 90, matchKeywords: ['tavacin 500', 'تافاسين', 'levofloxacin', 'ليفوفلوكساسين', 'pneumonia', 'التهاب رئوي', 'sinusitis', 'جيوب', 'التهاب مجرى البول', 'التهاب بروستاتا', 'prostatitis', 'uti', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب الأنفية/المسالك البولية/البروستاتا.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–٧ أيام (UTI/جيوب) أو ٧–١٤ يوم (رئوي) بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tavanic-500mg-5-tab', name: 'tavanic 500mg 5 tab', genericName: 'levofloxacin', concentration: '500mg', price: 192, matchKeywords: ['tavanic 500', 'تافانيك', 'levofloxacin', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب الأنفية/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tavacin-750mg-5-tab', name: 'tavacin 750mg 5 tab', genericName: 'levofloxacin', concentration: '750mg', price: 96, matchKeywords: ['tavacin 750', 'تافاسين ٧٥٠', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'kevork-500mg-5-fc-tab', name: 'kevork 500mg 5 f.c. tab.', genericName: 'levofloxacin', concentration: '500mg', price: 35, matchKeywords: ['kevork 500', 'كيفورك', '#antibiotics'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'kevork-500mg-10-fc-tabs', name: 'kevork 500 mg 10 f.c.tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 93, matchKeywords: ['kevork 500 10', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'kevork-750mg-5-fc-tab', name: 'kevork 750mg 5 f.c. tab.', genericName: 'levofloxacin', concentration: '750mg', price: 40.5, matchKeywords: ['kevork 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'kevork-750mg-10-fc-tabs', name: 'kevork 750 mg 10 f.c.tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 121, matchKeywords: ['kevork 750 10', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–١٠ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levanic-500mg-5-fc-tab', name: 'levanic 500mg 5 f.c. tab.', genericName: 'levofloxacin', concentration: '500mg', price: 35, matchKeywords: ['levanic 500', 'ليفانيك', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levanic-500mg-7-fc-tab', name: 'levanic 500mg 7 f.c. tab.', genericName: 'levofloxacin', concentration: '500mg', price: 92, matchKeywords: ['levanic 500 7', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levanic-750mg-5-tab', name: 'levanic 750 mg 5 tab', genericName: 'levofloxacin', concentration: '750mg', price: 66, matchKeywords: ['levanic 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levodel-250mg-5-fc-tabs', name: 'levodel 250mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '250mg', price: 12.75, matchKeywords: ['levodel 250', 'ليفوديل', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة منخفضة للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٢٥٠ مجم) مرة يومياً لمدة ٣ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levodel-500mg-5-fc-tabs', name: 'levodel 500mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 67, matchKeywords: ['levodel 500', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levodel-750mg-5-fc-tabs', name: 'levodel 750mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 86, matchKeywords: ['levodel 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levoxin-250mg-5-fc-tabs', name: 'levoxin 250 mg 5 f.c.tabs.', genericName: 'levofloxacin', concentration: '250mg', price: 45, matchKeywords: ['levoxin 250', 'ليفوكسين', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة منخفضة للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٢٥٠ مجم) مرة يومياً لمدة ٣ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levoxin-500mg-5-fc-tab', name: 'levoxin 500mg 5 f.c. tab.', genericName: 'levofloxacin', concentration: '500mg', price: 76, matchKeywords: ['levoxin 500', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'targofloxin-750mg-5-fc-tab', name: 'targofloxin 750 mg 5 f.c.tab.', genericName: 'levofloxacin', concentration: '750mg', price: 94, matchKeywords: ['targofloxin 750', 'تارجوفلوكسين', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'targofloxin-750mg-10-fc-tabs', name: 'targofloxin 750 mg 10 f.c.tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 188, matchKeywords: ['targofloxin 750 10', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–١٠ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'unibiotic-500mg-5-fc-tab', name: 'unibiotic 500mg 5 f.c.tab.', genericName: 'levofloxacin', concentration: '500mg', price: 66, matchKeywords: ['unibiotic', 'يونيبايوتيك', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'quinostarmax-500mg-10-tabs', name: 'quinostarmax 500 mg 10 tabs.', genericName: 'levofloxacin & levofloxacin hemihydate', concentration: '500mg', price: 104, matchKeywords: ['quinostarmax 500', 'كينوستارماكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'quinostarmax-750mg-5-tabs', name: 'quinostarmax 750 mg 5 tabs', genericName: 'levofloxacin', concentration: '750mg', price: 76, matchKeywords: ['quinostarmax 750 5', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'quinostarmax-750mg-10-tabs', name: 'quinostarmax 750 mg 10 tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 152, matchKeywords: ['quinostarmax 750 10', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–١٠ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levofloxacin-500mg-10-tabs', name: 'levofloxacin 500mg 10 tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 104, matchKeywords: ['levofloxacin 500 10', 'ليفوفلوكساسين', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levofloxacin-750mg-5-fc-tabs', name: 'levofloxacin 750 mg 5 f.c.tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 67, matchKeywords: ['levofloxacin 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'larivex-500mg-5-tab', name: 'larivex 500 mg 5 tab.', genericName: 'levofloxacin', concentration: '500mg', price: 66, matchKeywords: ['larivex', 'لاريفكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'lee-flox-250mg-5-tab', name: 'lee-flox 250mg 5 tab.', genericName: 'levofloxacin', concentration: '250mg', price: 86, matchKeywords: ['lee-flox 250', 'لي فلوكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة منخفضة للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٢٥٠ مجم) مرة يومياً لمدة ٣ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'lee-flox-500mg-5-fc-tab', name: 'lee-flox 500mg 5 f.c tab', genericName: 'levofloxacin', concentration: '500mg', price: 107, matchKeywords: ['lee-flox 500', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'lee-flox-750mg-7-fc-tab', name: 'lee-flox 750mg 7 f.c.tab.', genericName: 'levofloxacin', concentration: '750mg', price: 145, matchKeywords: ['lee-flox 750', '#antibiotics'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levoflox-500mg-5-tab', name: 'levoflox 500 mg 5 tab', genericName: 'levofloxacin', concentration: '500mg', price: 66, matchKeywords: ['levoflox', 'ليفوفلوكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tavoniflox-750mg-7-fc-tabs', name: 'tavoniflox 750mg 7 f.c. tabs', genericName: 'levofloxacin', concentration: '750mg', price: 66, matchKeywords: ['tavoniflox', 'تافونيفلوكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'venaxan-250mg-5-fc-tab', name: 'venaxan 250mg 5 f.c.tab.', genericName: 'levofloxacin', concentration: '250mg', price: 18, matchKeywords: ['venaxan 250', 'فيناكسان', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة منخفضة للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٢٥٠ مجم) مرة يومياً لمدة ٣ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'venaxan-500mg-5-fc-tabs', name: 'venaxan 500 mg 5 f.c.tabs', genericName: 'levofloxacin', concentration: '500mg', price: 48, matchKeywords: ['venaxan 500', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'cinoflokeen-500mg-5-fc-tabs', name: 'cinoflokeen 500mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 52, matchKeywords: ['cinoflokeen', 'سينوفلوكين', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// LEVOFLOXACIN IV
	{ id: 'tavanic-500mg-100ml-iv', name: 'tavanic 500mg/100ml vial for i.v. inf.', genericName: 'levofloxacin', concentration: '500mg/100ml', price: 305, matchKeywords: ['tavanic iv', 'تافانيك حقن', 'iv', 'infusion', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٥٠٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٤ يوم (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	{ id: 'venaxan-500mg-100ml-vial', name: 'venaxan 500mg vial 100 ml', genericName: 'levofloxacin', concentration: '500mg/100ml', price: 62, matchKeywords: ['venaxan iv', 'فيناكسان حقن', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٥٠٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٤ يوم (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	// ==================== MOXIFLOXACIN ====================
	{ id: 'fluroflox-400mg-5-fc-tabs', name: 'fluroflox 400mg 5 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 92, matchKeywords: ['fluroflox 400', 'فلوروفلوكس', 'moxifloxacin', 'موكسيفلوكساسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–٧ أيام (جيوب) أو ٧–١٤ يوم (رئوي) بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'fluroflox-400mg-10-fc-tabs', name: 'fluroflox 400mg 10 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 184, matchKeywords: ['fluroflox 400 10', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'kinomoxi-400mg-5-fc-tablets', name: 'kinomoxi 400 mg 5 f.c. tablets', genericName: 'moxifloxacin', concentration: '400mg', price: 45, matchKeywords: ['kinomoxi 400', 'كينوموكسي', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'kinomoxi-400mg-10-fc-tabs', name: 'kinomoxi 400 mg 10 f.c.tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 176, matchKeywords: ['kinomoxi 400 10', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'moflox-400mg-5-fc-tabs', name: 'moflox 400mg 5 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 54, matchKeywords: ['moflox 400', 'موفلوكس', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/القدم السكري.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'moflox-400mg-10-fc-tabs', name: 'moflox 400mg 10 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 184, matchKeywords: ['moflox 400 10', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/القدم السكري.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'moxiflox-400mg-10-fc-tabs', name: 'moxiflox 400 mg 10 f.c.tabs', genericName: 'moxifloxacin', concentration: '400mg', price: 180, matchKeywords: ['moxiflox 400', 'موكسيفلوكس', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'adwifloxacen-400mg-7-fc-tabs', name: 'adwifloxacen 400 mg 7 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 99, matchKeywords: ['adwifloxacen', 'أدويفلوكساسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	// MOXIFLOXACIN IV
	{ id: 'moxiflox-400mg-250ml-inf', name: 'moxiflox 400mg/250ml sol. for inf.', genericName: 'moxifloxacin', concentration: '400mg/250ml', price: 245, matchKeywords: ['moxiflox iv', 'موكسيفلوكس حقن', 'infusion', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٤٠٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٤ يوم (بالمستشفى فقط)'), warnings: [...MOXIFLOXACIN_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	// ==================== OFLOXACIN ====================
	{ id: 'tarivid-200mg-10-fc-tab', name: 'tarivid 200mg 10 f.c. tab.', genericName: 'ofloxacin', concentration: '200mg', price: 82, matchKeywords: ['tarivid', 'تاريفيد', 'ofloxacin', 'أوفلوكساسين', '#antibiotics', '#quinolone'], usage: 'أوفلوكساسين لالتهابات المسالك البولية/الجهاز التنفسي.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٢٠٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tariflox-400mg-10-tabs', name: 'tariflox 400 mg 10 tabs.', genericName: 'ofloxacin', concentration: '400mg', price: 45, matchKeywords: ['tariflox', 'تاريفلوكس', '#antibiotics', '#quinolone'], usage: 'أوفلوكساسين لالتهابات المسالك البولية/الجهاز التنفسي.', timing: 'مرة يومياً – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablet', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// ==================== EYE DROPS ====================
	{ id: 'vigamox-0.5-eye-drops-5ml', name: 'vigamox 0.5% eye drops 5 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 128, matchKeywords: ['vigamox', 'فيجاموكس', 'eye drops', 'قطرة عين', 'conjunctivitis', 'رمد', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'fortymox-plus-ophthalmic-5ml', name: 'fortymox plus ophthalmic sol. 5 ml', genericName: 'moxifloxacin & dexamethasone', concentration: '5ml', price: 39, matchKeywords: ['fortymox plus', 'فورتيموكس بلس', 'eye surgery', 'عمليات عيون', '#antibiotics', '#glucocorticoid'], usage: 'قطرة عين (موكسيفلوكساسين + ديكساميثازون) لما بعد عمليات العيون/التهاب شديد.', timing: '٤ مرات يومياً – ٧–١٤ يوم ثم تقليل تدريجي', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 24, maxAgeMonths: 1200, minWeight: 10, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٤ يوم ثم تقليل تدريجي (٣ ثم ٢ ثم ١ مرة يومياً) حتى زوال الالتهاب'), warnings: [...EYE_FQ_WARNINGS, 'تحتوي على كورتيزون—لا تُستخدم لفترات طويلة دون متابعة طبية.'] },
	{ id: 'fortymox-0.5-eye-drops-10ml', name: 'fortymox 0.5% eye drops 10 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 62, matchKeywords: ['fortymox', 'فورتيموكس', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'fluroquinomox-0.5-ophthalmic-5ml', name: 'fluroquinomox 0.5% ophthalmic sol. 5 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 66, matchKeywords: ['fluroquinomox', 'فلوروكينوموكس', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'moxiflox-0.5-eye-drops-5ml', name: 'moxiflox 0.5% eye drops 5 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 33, matchKeywords: ['moxiflox eye', 'موكسيفلوكس قطرة', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'dexaflox-eye-drops-5ml', name: 'dexaflox eye drops 5 ml', genericName: 'dexamethazone micronized & ofloxacin', concentration: '5ml', price: 53, matchKeywords: ['dexaflox', 'ديكسافلوكس', 'eye surgery', '#antibiotics', '#glucocorticoid'], usage: 'قطرة عين (أوفلوكساسين + ديكساميثازون) لما بعد عمليات العيون/التهاب شديد.', timing: '٤ مرات يومياً – ٧–١٤ يوم ثم تقليل تدريجي', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 24, maxAgeMonths: 1200, minWeight: 10, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٤ يوم ثم تقليل تدريجي (٣ ثم ٢ ثم ١ مرة يومياً) حتى زوال الالتهاب'), warnings: [...EYE_FQ_WARNINGS, 'تحتوي على كورتيزون—لا تُستخدم لفترات طويلة دون متابعة طبية.'] },
	{ id: 'optiflox-0.3-eye-drops-5ml', name: 'optiflox 0.3% eye drops 5ml', genericName: 'ofloxacin', concentration: '0.3%', price: 19.5, matchKeywords: ['optiflox', 'أوبتيفلوكس', '#antibiotics', '#quinolone'], usage: 'قطرة عين أوفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	// ==================== EAR DROPS ====================
	{ id: 'dropiflox-otic-drops-15ml', name: 'dropiflox otic drops 15 ml', genericName: 'ciprofloxacin & dexamethasone', concentration: '15ml', price: 39, matchKeywords: ['dropiflox', 'دروبيفلوكس', 'ear drops', 'قطرة اذن', 'otitis externa', '#antibiotics', '#glucocorticoid'], usage: 'قطرة أذن (سيبروفلوكساسين + ديكساميثازون) لالتهاب الأذن الخارجية.', timing: '٣–٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('٣–٤ نقط في الأذن المصابة كل ٦–٨ ساعات لمدة ٧ أيام'), warnings: [...EAR_FQ_WARNINGS, 'تحتوي على كورتيزون—لا تُستخدم لفترات طويلة دون متابعة طبية.'] },
];
