import { Medication, Category } from '../../types';

const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);

const COMMON_FQ_WARNINGS = [
	'ممنوع للأطفال أقل من ١٨ سنة (خطر على الأوتار والمفاصل والغضاريف).',
	'ممنوع أثناء الحمل والرضاعة.',
	'يُفصل عن الألبان/الكالسيوم/الحديد/مضادات الحموضة بساعتين على الأقل.',
	'خطر التهاب/تمزق الأوتار (خاصة وتر أخيل)—يزداد مع الكورتيزون وكبار السن. أوقف فوراً عند ألم/تورم الأوتار.',
	'قد يسبب اعتلال الأعصاب الطرفية (تنميل/وخز/ضعف بالأطراف)—أوقفه فوراً عند الظهور.',
	'قد يطيل QT interval—حذر مع أدوية القلب/اضطراب نظم القلب.',
	'يسبب حساسية للضوء—تجنب التعرض المباشر للشمس واستخدم واقي شمس.',
	'شرب سوائل كافية (٢–٣ لتر يومياً) لتقليل خطر ترسبات الكلى.',
	'خطر نادر: تمدد/تسلخ الشريان الأورطي—أوقفه واطلب طوارئ عند ألم صدر/بطن مفاجئ شديد.',
];

const EYE_FQ_WARNINGS = [
	'للاستخدام الخارجي للعين فقط—لا تُستخدم في الفم أو الأذن.',
	'لا تلمس طرف القطارة بالعين/الرموش لتجنب تلوث العبوة.',
	'اغسل يديك قبل الاستخدام.',
	'إذا لم تتحسن الأعراض خلال ٤٨–٧٢ ساعة: راجع طبيب عيون.',
];

const EAR_FQ_WARNINGS = [
	'للأذن فقط—لا تُستخدم في العين.',
	'يُدفأ القطرة بوضعها في اليد قبل الاستخدام.',
	'ممنوع عند ثقب طبلة الأذن أو الشك فيه؛ استخدم بديل فموي أو قطرة أذن غير أوتوتوكسيك.',
];

const MOXIFLOXACIN_WARNINGS = [
	...COMMON_FQ_WARNINGS,
	'موكسيفلوكساسين أعلى خطورة لإطالة QT من بقية الفلوروكينولونات—ممنوع مع أدوية تطيل QT.',
	'يُراقب ECG في المرضى المعرضين للخطر (كبار السن، نقص بوتاسيوم/ماغنسيوم، أدوية قلب).',
];

const fixed = (t: string) => () => t;

export const FLUOROQUINOLONES_GROUP_PART2: Medication[] = [
	// ==================== LEVOFLOXACIN (Tablets) ====================
	{ id: 'levotavin-500mg-7-fc-tabs', name: 'levotavin 500 mg 7 f.c.tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 92, matchKeywords: ['levotavin 500', 'ليفوتافين', 'levofloxacin', 'ليفوفلوكساسين', 'التهاب رئوي', 'جيوب', 'التهاب مجرى البول', 'التهاب بروستاتا', 'prostatitis', 'uti', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levotavin-750mg-7-fc-tabs', name: 'levotavin 750 mg 7 f.c.tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 108, matchKeywords: ['levotavin 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'royafloxacin-500mg-10-fc-tabs', name: 'royafloxacin 500mg 10 f.c. tabs', genericName: 'levofloxacin anhydrous', concentration: '500mg', price: 92, matchKeywords: ['royafloxacin', 'رويافلوكساسين', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'awadilevo-500mg-10-tabs', name: 'awadilevo 500 mg 10tabs', genericName: 'levofloxacin', concentration: '500mg', price: 92, matchKeywords: ['awadilevo', 'أواديليفو', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levofloxacin-eva-500mg-10-fc-tabs', name: 'levofloxacin-eva 500 mg 10 f.c.tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 104, matchKeywords: ['levofloxacin eva', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tavoniflox-500mg-7-fc-tabs-v2', name: 'tavoniflox 500mg 7 f.c. tabs', genericName: 'levofloxacin', concentration: '500mg', price: 52, matchKeywords: ['tavoniflox 500 7', 'تافونيفلوكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'volitractin-500mg-5-tabs', name: 'volitractin 500mg 5 tabs', genericName: 'levofloxacin', concentration: '500mg', price: 68.5, matchKeywords: ['volitractin', 'فوليتراكتين', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'levoflox-250mg-5-fc-tabs', name: 'levoflox 250 mg 5 f.c.tabs.', genericName: 'levofloxacin', concentration: '250mg', price: 36, matchKeywords: ['levoflox 250', 'ليفوفلوكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة منخفضة للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٢٥٠ مجم) مرة يومياً لمدة ٣ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'megabio-500mg-5-fc-tabs', name: 'megabio 500 mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 46, matchKeywords: ['megabio 500', 'ميجابيو', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'megabio-750mg-5-fc-tabs', name: 'megabio 750 mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 60, matchKeywords: ['megabio 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'uniloxam-500mg-10-fc-tabs', name: 'uniloxam 500mg 10 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 66, matchKeywords: ['uniloxam 500', 'يونيلوكسام', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'uniloxam-750mg-10-fc-tabs', name: 'uniloxam 750mg 10 f.c. tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 86, matchKeywords: ['uniloxam 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–١٠ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tavixinor-500mg-5-fc-tabs', name: 'tavixinor 500 mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 64.5, matchKeywords: ['tavixinor 500', 'تافيكسينور', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'tavixinor-750mg-5-fc-tabs', name: 'tavixinor 750 mg 5 f.c. tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 86, matchKeywords: ['tavixinor 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'volitracin-500mg-7-fc-tabs', name: 'volitracin 500 mg 7 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 100, matchKeywords: ['volitracin 500 7', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'bioticaflox-500mg-7-fc-tabs', name: 'bioticaflox 500 mg 7 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 92, matchKeywords: ['bioticaflox 500', 'بيوتيكافلوكس', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'bioticaflox-750mg-7-fc-tabs', name: 'bioticaflox 750 mg 7 f.c. tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 92, matchKeywords: ['bioticaflox 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–٧ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'debacolev-500mg-10-fc-tabs', name: 'debacolev 500mg 10 f.c. tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 37, matchKeywords: ['debacolev 500', 'ديباكوليف', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'debacolev-750mg-10-fc-tabs', name: 'debacolev 750mg 10 f.c. tabs.', genericName: 'levofloxacin', concentration: '750mg', price: 95, matchKeywords: ['debacolev 750', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين جرعة مكثفة للالتهاب الرئوي الحاد.', timing: 'مرة يومياً – ٥–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) مرة يومياً لمدة ٥–١٠ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'lebactovo-500mg-5-fc-tabs', name: 'lebactovo 500 mg 5 f.c.tabs.', genericName: 'levofloxacin', concentration: '500mg', price: 76, matchKeywords: ['lebactovo', 'ليباكتوفو', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين للالتهاب الرئوي/الجيوب/المسالك البولية.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) مرة يومياً لمدة ٥ أيام بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// ==================== LEVOFLOXACIN (IV/Vials) ====================
	{ id: 'levoflotanet-750mg-30ml-vial', name: 'levoflotanet 750mg/30ml concentrate vial for i.v.', genericName: 'levofloxacin', concentration: '750mg/30ml', price: 102, matchKeywords: ['levoflotanet', 'ليفوفلوتانيت', 'iv', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٥٠٠–٧٥٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٠ أيام (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	{ id: 'levoflox-500mg-vial-iv', name: 'levoflox 500mg vial for i.v. inf.', genericName: 'levofloxacin', concentration: '500mg', price: 39.25, matchKeywords: ['levoflox iv', 'ليفوفلوكس حقن', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٥٠٠–٧٥٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٠ أيام (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	{ id: 'levoxin-500mg-vial-100ml', name: 'levoxin 500mg vial 100 ml', genericName: 'levofloxacin', concentration: '500mg/100ml', price: 72, matchKeywords: ['levoxin iv', 'ليفوكسين حقن', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٥٠٠–٧٥٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٠ أيام (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	{ id: 'tavacin-500mg-vial-100ml', name: 'tavacin 500mg vial 100ml', genericName: 'levofloxacin', concentration: '500mg/100ml', price: 90, matchKeywords: ['tavacin iv', 'تافاسين حقن', '#antibiotics', '#quinolone'], usage: 'ليفوفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'مرة يومياً – ٧–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٥٠٠–٧٥٠ مجم تسريب وريدي خلال ٦٠ دقيقة مرة يومياً لمدة ٧–١٠ أيام (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	// ==================== MOXIFLOXACIN (Tablets) ====================
	{ id: 'moxavidex-400mg-5-fc-tabs', name: 'moxavidex 400 mg 5 f.c.tabs', genericName: 'moxifloxacin', concentration: '400mg', price: 92, matchKeywords: ['moxavidex 400', 'موكسافيدكس', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'moxavidex-400mg-10-fc-tabs', name: 'moxavidex 400 mg 10 f.c.tabs', genericName: 'moxifloxacin', concentration: '400mg', price: 184, matchKeywords: ['moxavidex 400 10', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'primoxizar-400mg-5-fc-tab', name: 'primoxizar 400 mg 5 f.c. tab.', genericName: 'moxifloxacin', concentration: '400mg', price: 80, matchKeywords: ['primoxizar', 'بريموكسيزار', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'advoxin-400mg-5-fc-tabs', name: 'advoxin 400 mg 5 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 67.5, matchKeywords: ['advoxin', 'أدفوكسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'moxacin-400mg-5-fc-tabs', name: 'moxacin 400 mg 5 f.c.tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 92, matchKeywords: ['moxacin', 'موكساسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'moxifloxacin-400mg-5-fc-tab', name: 'moxifloxacin 400mg 5 f.c. tab.', genericName: 'moxifloxacin', concentration: '400mg', price: 54, matchKeywords: ['moxifloxacin 400', 'موكسيفلوكساسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'quinomoxin-400mg-5-fc-tab', name: 'quinomoxin 400mg 5 f.c. tab.', genericName: 'moxifloxacin', concentration: '400mg', price: 54, matchKeywords: ['quinomoxin', 'كينوموكسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'rowamoxiflox-400mg-5-fc-tabs', name: 'rowamoxiflox 400mg 5 f.c. tabs.', genericName: 'moxifloxacin', concentration: '400mg', price: 85.5, matchKeywords: ['rowamoxiflox', 'روواموكسيفلوكس', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'floxepci-400mg-10-fc-tab', name: 'floxepci 400mg 10 f.c. tab', genericName: 'moxifloxacin', concentration: '400mg', price: 176, matchKeywords: ['floxepci 400 10', 'فلوكسيبسي', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'floxepci-400mg-5-fc-tab', name: 'floxepci 400mg 5 f.c. tab (n/a)', genericName: 'moxifloxacin', concentration: '400mg', price: 40, matchKeywords: ['floxepci 400 5', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'dolabactin-400mg-5-fc-tab', name: 'dolabactin 400 mg 5 f.c.tab.', genericName: 'moxifloxacin', concentration: '400mg', price: 80, matchKeywords: ['dolabactin', 'دولاباكتين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'raspelocin-400mg-10-fc-tab', name: 'raspelocin 400mg 10 f.c.tab', genericName: 'moxifloxacin', concentration: '400mg', price: 160, matchKeywords: ['raspelocin', 'راسبيلوسين', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'shamsomox-400mg-5-fc-tabs', name: 'shamsomox 400 mg 5 f.c. tabs', genericName: 'moxifloxacin', concentration: '400mg', price: 89, matchKeywords: ['shamsomox', 'شمسوموكس', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'delmoxa-400mg-5-fc-tab', name: 'delmoxa 400 mg 5 f.c.tab.', genericName: 'moxifloxacin', concentration: '400mg', price: 79, matchKeywords: ['delmoxa', 'دلموكسا', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	{ id: 'idelox-400mg-10-fc-tab', name: 'idelox 400mg 10 f.c. tab.', genericName: 'moxifloxacin', concentration: '400mg', price: 116, matchKeywords: ['idelox 400 tab', 'إيديلوكس', '#antibiotics', '#quinolone'], usage: 'موكسيفلوكساسين للالتهاب الرئوي/الجيوب/التهاب الحوض.', timing: 'مرة يومياً – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) مرة يومياً لمدة ٥–١٤ يوم بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: MOXIFLOXACIN_WARNINGS },
	// ==================== CIPROFLOXACIN (Tablets) ====================
	{ id: 'rancif-500mg-10-fc-tab', name: 'rancif 500mg 10 f.c.tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 69, matchKeywords: ['rancif', 'رانسيف', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة/تيفود) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofloxiraz-750mg-10-fc-tab', name: 'ciprofloxiraz 750mg 10 f.c. tab.', genericName: 'ciprofloxacin', concentration: '750mg', price: 89, matchKeywords: ['ciprofloxiraz 750', 'سيبروفلوكسيراز', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'heroxacin-500mg-10-scored-fc-tab', name: 'heroxacin 500mg 10 scored f.c. tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 69, matchKeywords: ['heroxacin', 'هيروكساسين', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'cipromax-750mg-10-fc-tab', name: 'cipromax 750mg 10 f.c.tab.', genericName: 'ciprofloxacin', concentration: '750mg', price: 60, matchKeywords: ['cipromax', 'سيبروماكس', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciprofloxiraz-500mg-10-fc-tab', name: 'ciprofloxiraz 500mg 10 f.c. tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 27, matchKeywords: ['ciprofloxiraz 500', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'elmodoxacin-500mg-10-tab', name: 'elmodoxacin 500 mg 10 tab', genericName: 'ciprofloxacin', concentration: '500mg', price: 20, matchKeywords: ['elmodoxacin 500', 'المودوكساسين', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'elmodoxacin-750mg-10-fc-tab', name: 'elmodoxacin 750mg 10 f.c.tab.', genericName: 'ciprofloxacin', concentration: '750mg', price: 29, matchKeywords: ['elmodoxacin 750', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة عالية للعدوى الشديدة/التيفود.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٧٥٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'serviflox-250mg-10-fc-tab', name: 'serviflox 250 mg 10 f.c.tab.', genericName: 'ciprofloxacin', concentration: '250mg', price: 18, matchKeywords: ['serviflox', 'سيرفيفلوكس', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين جرعة منخفضة للمسالك البولية غير المعقدة.', timing: 'كل ١٢ ساعة – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٢٥٠ مجم) كل ١٢ ساعة لمدة ٣ أيام على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'quinospan-500mg-10-tabs', name: 'quinospan 500 mg 10 tabs.', genericName: 'ciprofloxacin', concentration: '500mg', price: 34, matchKeywords: ['quinospan', 'كينوسبان', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين لالتهابات المسالك البولية/التيفود/النزلات المعوية.', timing: 'كل ١٢ ساعة – ٥–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) كل ١٢ ساعة لمدة ٥–٧ أيام (UTI) أو ٧–١٤ يوم (عدوى شديدة) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// ==================== CIPROFLOXACIN (Extended Release) ====================
	{ id: 'cipromega-xl-500mg-10-er-fc-tab', name: 'cipromega xl 500mg 10 ext. rel. f.c.tab.', genericName: 'ciprofloxacin', concentration: '500mg', price: 48, matchKeywords: ['cipromega xl 500', 'سيبروميجا اكس ال', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين ممتد المفعول للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) ممتد المفعول مرة يومياً لمدة ٣ أيام (يُبلع كاملاً) بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'cipromega-xl-1000mg-14-er-fc-tabs', name: 'cipromega xl 1000 mg 14 ext. rel. f.c.tabs.', genericName: 'ciprofloxacin', concentration: '1000mg', price: 128, matchKeywords: ['cipromega xl 1000', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين ممتد المفعول للعدوى الشديدة/التيفود.', timing: 'مرة يومياً – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (١٠٠٠ مجم) ممتد المفعول مرة يومياً لمدة ٧–١٤ يوم (يُبلع كاملاً) بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ciproxil-xl-500mg-10-tab', name: 'ciproxil-xl 500 mg 10 tab', genericName: 'ciprofloxacin', concentration: '500mg', price: 40.5, matchKeywords: ['ciproxil xl', 'سيبروكسيل', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين ممتد المفعول للمسالك البولية غير المعقدة.', timing: 'مرة يومياً – ٣ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٥٠٠ مجم) ممتد المفعول مرة يومياً لمدة ٣ أيام (يُبلع كاملاً) بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'ultracipro-er-1gm-5-fc-tabs', name: 'ultracipro e.r. 1 gm 5 f.c. tabs.', genericName: 'ciprofloxacin', concentration: '1gm', price: 31, matchKeywords: ['ultracipro', 'الترا سيبرو', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين ممتد المفعول للعدوى الشديدة.', timing: 'مرة يومياً – ٥ أيام', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (١ جم) ممتد المفعول مرة يومياً لمدة ٥ أيام (يُبلع كاملاً) بدون اعتبار للأكل، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// ==================== CIPROFLOXACIN (IV) ====================
	{ id: 'arabcofloroquin-200mg-100ml-vial', name: 'arabcofloroquin 200mg/100ml vial', genericName: 'ciprofloxacin', concentration: '200mg/100ml', price: 52, matchKeywords: ['arabcofloroquin', 'عربكو فلوروكين', 'iv', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'كل ١٢ ساعة – ٧–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٢٠٠–٤٠٠ مجم تسريب وريدي خلال ٦٠ دقيقة كل ١٢ ساعة لمدة ٧–١٠ أيام (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	{ id: 'ciprofloxacin-200mg-100ml-vial', name: 'ciprofloxacin 200mg/100ml vial', genericName: 'ciprofloxacin', concentration: '200mg/100ml', price: 30.5, matchKeywords: ['ciprofloxacin iv', 'سيبروفلوكساسين حقن', '#antibiotics', '#quinolone'], usage: 'سيبروفلوكساسين وريدي للعدوى الشديدة/المستشفيات.', timing: 'كل ١٢ ساعة – ٧–١٠ أيام', category: Category.FLUOROQUINOLONES, form: 'Vial', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('٢٠٠–٤٠٠ مجم تسريب وريدي خلال ٦٠ دقيقة كل ١٢ ساعة لمدة ٧–١٠ أيام (بالمستشفى فقط)'), warnings: [...COMMON_FQ_WARNINGS, 'للاستخدام بالمستشفى/العيادة فقط؛ يُعطى تسريب وريدي وفق التشخيص وتعليمات الإعطاء.'] },
	// ==================== NORFLOXACIN ====================
	{ id: 'epinor-400mg-14-tab', name: 'epinor 400mg 14 tab.', genericName: 'norfloxacin', concentration: '400mg', price: 35, matchKeywords: ['epinor', 'إبينور', 'norfloxacin', 'نورفلوكساسين', 'uti', 'التهاب مجرى البول', 'صديد بول', '#antibiotics', '#quinolone'], usage: 'نورفلوكساسين لالتهابات المسالك البولية غير المعقدة/المعقدة.', timing: 'كل ١٢ ساعة – ٣–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 45, maxWeight: 250, calculationRule: fixed('١ قرص (٤٠٠ مجم) كل ١٢ ساعة لمدة ٣ أيام (UTI غير معقد) أو ٧ أيام (معقد) على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// ==================== OFLOXACIN (Tablets) ====================
	{ id: 'tariflox-200mg-10-tab', name: 'tariflox 200 mg 10 tab.', genericName: 'ofloxacin', concentration: '200mg', price: 26, matchKeywords: ['tariflox 200', 'تاريفلوكس', 'ofloxacin', 'أوفلوكساسين', 'uti', 'التهاب مجرى البول', '#antibiotics', '#quinolone'], usage: 'أوفلوكساسين لالتهابات المسالك البولية/الجهاز التنفسي.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٢٠٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	{ id: 'epicoflocin-200mg-10-fc-tab', name: 'epicoflocin 200 mg 10 f.c.tab.', genericName: 'ofloxacin', concentration: '200mg', price: 18, matchKeywords: ['epicoflocin', 'إيبكوفلوسين', '#antibiotics', '#quinolone'], usage: 'أوفلوكساسين لالتهابات المسالك البولية/الجهاز التنفسي.', timing: 'كل ١٢ ساعة – ٧–١٤ يوم', category: Category.FLUOROQUINOLONES, form: 'F.C. Tablets', minAgeMonths: 216, maxAgeMonths: 1200, minWeight: 50, maxWeight: 250, calculationRule: fixed('١ قرص (٢٠٠ مجم) كل ١٢ ساعة لمدة ٧–١٤ يوم على معدة فارغة، بعيداً عن الألبان/الكالسيوم/الحديد بساعتين'), warnings: [...COMMON_FQ_WARNINGS] },
	// ==================== EYE DROPS ====================
	{ id: 'ciprocin-0.3-eye-ear-drops-5ml', name: 'ciprocin 0.3% eye/ear drops 5 ml', genericName: 'ciprofloxacin', concentration: '0.3%', price: 21, matchKeywords: ['ciprocin drops', 'سيبروسين قطرة', 'eye ear', 'عين اذن', '#antibiotics', '#quinolone'], usage: 'قطرة سيبروفلوكساسين للعين والأذن لالتهاب الملتحمة/الأذن الخارجية.', timing: '٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('للعين: قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧ أيام. للأذن: ٣–٤ نقط في الأذن المصابة كل ٦–٨ ساعات لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS, ...EAR_FQ_WARNINGS] },
	{ id: 'ciprocin-0.3-eye-oint-5gm', name: 'ciprocin 0.3% eye oint. 5 gm', genericName: 'ciprofloxacin', concentration: '0.3%', price: 21, matchKeywords: ['ciprocin oint', 'سيبروسين مرهم', 'eye ointment', 'مرهم عين', '#antibiotics', '#quinolone'], usage: 'مرهم عين سيبروفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Ointment', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('شريط رفيع (١ سم) من المرهم في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'idelox-0.5-eye-drops-5ml', name: 'idelox 0.5% eye drops 5 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 38, matchKeywords: ['idelox drops', 'إيديلوكس قطرة', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'moxyseyaro-0.5-eye-drops-5ml', name: 'moxyseyaro 0.5% eye drops 5 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 16.5, matchKeywords: ['moxyseyaro', 'موكسيسيارو', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'moxyseyaro-0.5-eye-drops-10ml', name: 'moxyseyaro 0.5% eye drops 10 ml', genericName: 'moxifloxacin', concentration: '0.5%', price: 57, matchKeywords: ['moxyseyaro 10', '#antibiotics', '#quinolone'], usage: 'قطرة عين موكسيفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٣ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٣ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'moxyseyaro-plus-eye-drops-5ml', name: 'moxyseyaro plus eye drops 5 ml', genericName: 'dexamethasone & moxifloxacin', concentration: '5ml', price: 39, matchKeywords: ['moxyseyaro plus', 'موكسيسيارو بلس', '#antibiotics', '#glucocorticoid'], usage: 'قطرة عين (موكسيفلوكساسين + ديكساميثازون) لما بعد عمليات العيون/التهاب شديد.', timing: '٤ مرات يومياً – ٧–١٤ يوم ثم تقليل تدريجي', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 24, maxAgeMonths: 1200, minWeight: 10, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٤ يوم ثم تقليل تدريجي (٣ ثم ٢ ثم ١ مرة يومياً) حتى زوال الالتهاب'), warnings: [...EYE_FQ_WARNINGS, 'تحتوي على كورتيزون—لا تُستخدم لفترات طويلة دون متابعة طبية.'] },
	{ id: 'duoeffectum-eye-drops-10ml', name: 'duoeffectum eye drops 10 ml', genericName: 'ofloxacin & dexamethasone', concentration: '10ml', price: 32, matchKeywords: ['duoeffectum', 'ديوإيفكتم', '#antibiotics', '#corticosteroids'], usage: 'قطرة عين (أوفلوكساسين + ديكساميثازون) لما بعد عمليات العيون/التهاب شديد.', timing: '٤ مرات يومياً – ٧–١٤ يوم ثم تقليل تدريجي', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 24, maxAgeMonths: 1200, minWeight: 10, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧–١٤ يوم ثم تقليل تدريجي (٣ ثم ٢ ثم ١ مرة يومياً) حتى زوال الالتهاب'), warnings: [...EYE_FQ_WARNINGS, 'تحتوي على كورتيزون—لا تُستخدم لفترات طويلة دون متابعة طبية.'] },
	{ id: 'sanolevox-1.5-eye-drops-5ml', name: 'sanolevox 1.5% eye drops 5 ml', genericName: 'levofloxacin', concentration: '1.5%', price: 59, matchKeywords: ['sanolevox', 'سانوليفوكس', '#antibiotics', '#quinolone'], usage: 'قطرة عين ليفوفلوكساسين تركيز عالي لالتهابات العين الشديدة.', timing: 'كل ٢ ساعة يوم ١–٢ ثم ٤ مرات يومياً – ٥–٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة كل ٢ ساعة اليومين الأولين، ثم ٤ مرات يومياً لمدة ٥–٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'levoxin-5mg-ophth-drops-5ml', name: 'levoxin 5mg ophth. drops 5 ml', genericName: 'levofloxacin', concentration: '0.5%', price: 12.75, matchKeywords: ['levoxin drops', 'ليفوكسين قطرة', '#antibiotics', '#quinolone'], usage: 'قطرة عين ليفوفلوكساسين لالتهاب الملتحمة البكتيري.', timing: '٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧ أيام'), warnings: [...EYE_FQ_WARNINGS] },
	{ id: 'monoshield-0.5-eye-drops-sdu', name: 'monoshield 0.5% eye drops 10*0.5 ml sdu', genericName: 'levofloxacin', concentration: '0.5%', price: 52, matchKeywords: ['monoshield', 'مونوشيلد', 'single dose', '#antibiotics', '#quinolone'], usage: 'قطرة عين ليفوفلوكساسين (جرعات أحادية) لالتهاب الملتحمة.', timing: '٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('قطرة واحدة في العين المصابة ٤ مرات يومياً لمدة ٧ أيام (وحدة واحدة لكل استخدام، تُهمل بعد الفتح)'), warnings: [...EYE_FQ_WARNINGS, 'خالية من المواد الحافظة—آمنة للاستخدام المطول.'] },
	// ==================== EAR DROPS ====================
	{ id: 'dropiflox-otic-drops-7.5ml', name: 'dropiflox otic drops 7.5 ml', genericName: 'ciprofloxacin & dexamethasone', concentration: '7.5ml', price: 12, matchKeywords: ['dropiflox 7.5', 'دروبيفلوكس', 'ear drops', 'قطرة اذن', '#antibiotics', '#glucocorticoid'], usage: 'قطرة أذن (سيبروفلوكساسين + ديكساميثازون) لالتهاب الأذن الخارجية.', timing: '٣–٤ مرات يومياً – ٧ أيام', category: Category.FLUOROQUINOLONES, form: 'Drops', minAgeMonths: 12, maxAgeMonths: 1200, minWeight: 5, maxWeight: 250, calculationRule: fixed('٣–٤ نقط في الأذن المصابة كل ٦–٨ ساعات لمدة ٧ أيام'), warnings: [...EAR_FQ_WARNINGS, 'تحتوي على كورتيزون—لا تُستخدم لفترات طويلة دون متابعة طبية.'] },
];
