
import { Medication, Category } from '../../types';

// Helper
const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;

export const SULFONAMIDES_GROUP: Medication[] = [
	// ==========================================
	// SYSTEMIC (TMP-SMX) + TOPICAL (Silver Sulfadiazine / Burns)
	// ==========================================

	// 1) Hyalo 4 Control Cream 25 gm
	{
		id: 'hyalo-4-control-cream-25',
		name: 'Hyalo 4 control cream 25 gm',
		genericName: 'silver sulfadiazine & sodium hyaluronate',
		concentration: '25gm',
		price: 319,
		matchKeywords: [
			'hyalo 4', 'hyalo4', 'hyalo 4 control', 'هيالو ٤', 'هيالو 4',
			'burn', 'wound', 'ulcer', 'diabetic foot', 'bedsore',
			'حروق', 'جروح', 'قرح', 'قدم سكري', 'قرح فراش',
			'#antibiotics', '#sulfonamides', '#topical bactericidal',
		],
		usage: 'كريم للحروق والجروح وقرح القدم السكري (هيالورونات + سلفاديازين فضة).',
		timing: 'مرة يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.', 'للاستعمال الخارجي فقط.'],
	},

	// 2) Septazole Suspension 100 ml
	{
		id: 'septazole-susp-100',
		name: 'Septazole susp. 100 ml',
		genericName: 'sulfamethoxazole & trimethoprim',
		concentration: '200mg/40mg per 5ml',
		price: 36,
		matchKeywords: [
			'septazole', 'septazole susp', 'سبتازول', 'سبتازول شراب',
			'co-trimoxazole', 'cotrimoxazole', 'trimethoprim', 'sulfamethoxazole',
			'uti', 'respiratory infection', 'diarrhea', 'shigella', 'pneumocystis',
			'صديد بول', 'نزلة معوية', 'التهاب بول', 'التهاب مجرى البول',
			'#antibiotics', '#sulfonamides',
		],
		usage: 'مضاد حيوي (TMP-SMX) لالتهابات المسالك/النزلات المعوية/التنفسي.',
		timing: 'كل ١٢ ساعة – ٥–١٠ أيام',
		category: Category.SULFONAMIDES,
		form: 'Suspension',
		minAgeMonths: 2,
		maxAgeMonths: 144,
		minWeight: 4,
		maxWeight: 45,
		// TMP component: 40mg/5ml. Pediatric common: TMP 4mg/kg/day divided BID.
		// Volume per dose = weight * 0.25 ml
		calculationRule: (w) => `${toAr(roundVol(w * 0.25))} مل كل ١٢ ساعة بعد الأكل لمدة ٥–١٠ أيام`,
		warnings: ['ممنوع لمرضى أنيميا الفول (G6PD).', 'ممنوع لمن لديهم حساسية السلفا.', 'ممنوع للأطفال أقل من شهرين.', 'خطر نادر: متلازمة ستيفنز-جونسون (طفح شديد بالجلد/الفم/العيون)—أوقف فوراً.', 'قد يسبب ارتفاع البوتاسيوم—حذر مع مرضى الكلى وأدوية ACE/ARB.'],
	},

	// 3) Revivoderm cream 60 gm
	{
		id: 'revivoderm-cream-60',
		name: 'Revivoderm cream 60 gm',
		genericName: 'silver sulphadiazine & sodium hyaluronate',
		concentration: '60gm',
		price: 114,
		matchKeywords: [
			'revivoderm', 'ريفيفوديرم',
			'burn', 'wound', 'ulcer',
			'حروق', 'جروح', 'قرح',
			'#sulfonamides', '#topical bactericidal',
		],
		usage: 'كريم للحروق والجروح (هيالورونات + سلفاديازين فضة).',
		timing: 'مرة أو مرتين يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة أو مرتين يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.'],
	},

	// 4) Silvirburn 1% cream 250 gm
	{
		id: 'silvirburn-1pct-cream-250',
		name: 'Silvirburn 1% cream 250 gm',
		genericName: 'silver sulfadiazine',
		concentration: '1%',
		price: 64,
		matchKeywords: ['silvirburn', 'silvirburn 250', 'سيلفربيرن', 'حروق واسعة', 'burns', '#topical bactericidal'],
		usage: 'كريم سلفاديازين فضة للحروق والجروح (عبوة كبيرة).',
		timing: 'مرة أو مرتين يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة أو مرتين يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.', 'للاستعمال الخارجي فقط.'],
	},

	// 5) Hyalo 4 Control Cream 100 gm
	{
		id: 'hyalo-4-control-cream-100',
		name: 'Hyalo 4 control cream 100 gm',
		genericName: 'silver sulfadiazine & sodium hyaluronate',
		concentration: '100gm',
		price: 977,
		matchKeywords: [
			'hyalo 4', 'hyalo4', 'hyalo 4 control 100', 'هيالو ٤ ١٠٠',
			'burn', 'wound', 'ulcer', 'diabetic foot',
			'حروق', 'جروح', 'قرح', 'قدم سكري',
			'#topical bactericidal', '#sulfonamides',
		],
		usage: 'كريم (عبوة كبيرة) للحروق والجروح (هيالورونات + سلفاديازين فضة).',
		timing: 'مرة يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.'],
	},

	// 6) Silvirburn 1% cream 30 gm
	{
		id: 'silvirburn-1pct-cream-30',
		name: 'Silvirburn 1% cream 30 gm',
		genericName: 'silver sulfadiazine',
		concentration: '1%',
		price: 38,
		matchKeywords: ['silvirburn', 'silvirburn 30', 'سيلفربيرن ٣٠', 'burn cream', 'حروق', '#topical bactericidal'],
		usage: 'كريم سلفاديازين فضة للحروق والجروح (عبوة صغيرة).',
		timing: 'مرة أو مرتين يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة أو مرتين يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.', 'للاستعمال الخارجي فقط.'],
	},

	// 7) Kapect compound susp. 120 ml
	{
		id: 'kapect-compound-susp-120',
		name: 'Kapect compound susp. 120 ml',
		genericName: 'trimethoprim & kaolin & pectin & sulfamethoxazole',
		concentration: '120ml',
		price: 24,
		matchKeywords: ['kapect', 'kapect compound', 'كابكت', 'اسهال', 'diarrhea', '#diarrhea', '#sulfonamides'],
		usage: 'معلق للإسهال/النزلات المعوية.',
		timing: 'كل ٨ ساعات – ٣–٥ أيام',
		category: Category.SULFONAMIDES,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 7,
		maxWeight: 200,
		calculationRule: () => 'جرعة حسب العمر/الوزن كل ٨ ساعات بعد الأكل لمدة ٣–٥ أيام',
		warnings: ['تحسس السلفا/أنيميا الفول: يُمنع عند وجود مكونات سلفا.'],
	},

	// 8) Septazole forte 800/160mg 20 tab.
	{
		id: 'septazole-forte-800-160-20-tab',
		name: 'Septazole forte 800/160mg 20 tab.',
		genericName: 'sulfamethoxazole & trimethoprim',
		concentration: '800mg/160mg',
		price: 18,
		matchKeywords: ['septazole forte', 'septazole 800 160', 'سبتازول فورت', 'tmp-smx', 'cotrimoxazole', 'التهاب مجرى البول', 'uti', 'صديد بول', '#antibiotics', '#sulfonamides'],
		usage: 'مضاد حيوي (TMP-SMX فورت).',
		timing: 'كل ١٢ ساعة – ٥–١٠ أيام',
		category: Category.SULFONAMIDES,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 200,
		calculationRule: () => 'قرص فورت ٨٠٠/١٦٠ مجم كل ١٢ ساعة بعد الأكل لمدة ٥–١٠ أيام',
		warnings: ['ممنوع لمرضى أنيميا الفول (G6PD).', 'ممنوع لمن لديهم حساسية السلفا.', 'خطر نادر: متلازمة ستيفنز-جونسون—أوقف فوراً عند طفح شديد.', 'قد يسبب ارتفاع البوتاسيوم—حذر مع مرضى الكلى وأدوية ACE/ARB.'],
	},

	// 9) Co-trimoxazole 20 tabs
	{
		id: 'co-trimoxazole-400-80-20-tab',
		name: 'Co-trimoxazole 20 tabs',
		genericName: 'sulfamethoxazole & trimethoprim',
		concentration: '400mg/80mg',
		price: 36,
		matchKeywords: ['co-trimoxazole', 'cotrimoxazole', 'كوتريموكسازول', 'tmp-smx', 'التهاب مجرى البول', 'uti', 'صديد بول', '#antibiotics', '#sulfonamides'],
		usage: 'مضاد حيوي (TMP-SMX).',
		timing: 'كل ١٢ ساعة – ٥–١٠ أيام',
		category: Category.SULFONAMIDES,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 200,
		calculationRule: () => 'قرص ٤٠٠/٨٠ مجم كل ١٢ ساعة بعد الأكل لمدة ٥–١٠ أيام',
		warnings: ['ممنوع لمرضى أنيميا الفول (G6PD).', 'ممنوع لمن لديهم حساسية السلفا.', 'خطر نادر: متلازمة ستيفنز-جونسون—أوقف فوراً عند طفح شديد.', 'قد يسبب ارتفاع البوتاسيوم—حذر مع مرضى الكلى وأدوية ACE/ARB.'],
	},

	// 10) Co-trimoxazole 200/40mg susp. 120ml
	{
		id: 'co-trimoxazole-susp-120',
		name: 'Co-trimoxazole 200/40mg susp. 120ml',
		genericName: 'sulfamethoxazole & trimethoprim',
		concentration: '200mg/40mg per 5ml',
		price: 24,
		matchKeywords: ['co-trimoxazole susp', 'cotrimoxazole susp', 'كوتريموكسازول شراب', 'tmp-smx', 'التهاب مجرى البول', 'uti', 'صديد بول', '#antibiotics', '#sulfonamides'],
		usage: 'مضاد حيوي (TMP-SMX) معلق.',
		timing: 'كل ١٢ ساعة – ٥–١٠ أيام',
		category: Category.SULFONAMIDES,
		form: 'Suspension',
		minAgeMonths: 2,
		maxAgeMonths: 144,
		minWeight: 4,
		maxWeight: 45,
		calculationRule: (w) => `${toAr(roundVol(w * 0.25))} مل كل ١٢ ساعة بعد الأكل لمدة ٥–١٠ أيام`,
		warnings: ['ممنوع لمرضى أنيميا الفول (G6PD).', 'ممنوع لمن لديهم حساسية السلفا.', 'ممنوع للأطفال أقل من شهرين.', 'خطر نادر: متلازمة ستيفنز-جونسون—أوقف فوراً عند طفح شديد.', 'قد يسبب ارتفاع البوتاسيوم—حذر مع مرضى الكلى وأدوية ACE/ARB.'],
	},

	// 11) Medihyalo cream 30 gm
	{
		id: 'medihyalo-cream-30',
		name: 'Medihyalo cream 30 gm',
		genericName: 'sodium hyaluronate & silver sulfadiazine',
		concentration: '30gm',
		price: 81,
		matchKeywords: ['medihyalo', 'ميدي هيالو', 'burn', 'ulcer', 'diabetic foot', 'حروق', 'قدم سكري', '#topical bactericidal', '#sulfonamides'],
		usage: 'كريم للحروق وقرح الفراش والقدم السكري (هيالورونات + سلفاديازين فضة).',
		timing: 'مرة يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 5,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.', 'للاستعمال الخارجي فقط.'],
	},

	// 12) Septazole forte 800/160mg 10 tabs.
	{
		id: 'septazole-forte-800-160-10-tab',
		name: 'Septazole forte 800/160mg 10 tabs.',
		genericName: 'sulfamethoxazole & trimethoprim',
		concentration: '800mg/160mg',
		price: 9,
		matchKeywords: ['septazole forte 10', 'septazole 800 160', 'سبتازول فورت ١٠', 'tmp-smx', 'التهاب مجرى البول', 'uti', '#antibiotics', '#sulfonamides'],
		usage: 'مضاد حيوي (TMP-SMX فورت).',
		timing: 'كل ١٢ ساعة – ٥–١٠ أيام',
		category: Category.SULFONAMIDES,
		form: 'Tablet',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 200,
		calculationRule: () => 'قرص فورت ٨٠٠/١٦٠ مجم كل ١٢ ساعة بعد الأكل لمدة ٥–١٠ أيام',
		warnings: ['ممنوع لمرضى أنيميا الفول (G6PD).', 'ممنوع لمن لديهم حساسية السلفا.', 'خطر نادر: متلازمة ستيفنز-جونسون—أوقف فوراً عند طفح شديد.', 'قد يسبب ارتفاع البوتاسيوم—حذر مع مرضى الكلى وأدوية ACE/ARB.'],
	},

	// 13) Silvazine 1% cream 30 gm
	{
		id: 'silvazine-1pct-cream-30',
		name: 'Silvazine 1% cream 30 gm',
		genericName: 'silver sulfadiazine',
		concentration: '1%',
		price: 28,
		matchKeywords: ['silvazine', 'سيلفازين', 'silver sulfadiazine', 'burn cream', 'حروق', '#topical bactericidal', '#sulfonamides'],
		usage: 'كريم سلفاديازين فضة للحروق والجروح.',
		timing: 'مرة أو مرتين يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة أو مرتين يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.', 'للاستعمال الخارجي فقط.'],
	},

	// 14) Sulphargin 1% cream 20 gm
	{
		id: 'sulphargin-1pct-cream-20',
		name: 'Sulphargin 1% cream 20 gm',
		genericName: 'silver sulfadiazine',
		concentration: '1%',
		price: 26,
		matchKeywords: ['sulphargin', 'sulfargin', 'سلفارجين', 'silver sulfadiazine', 'burn cream', 'حروق', '#topical bactericidal', '#sulfonamides'],
		usage: 'كريم سلفاديازين فضة للحروق والجروح.',
		timing: 'مرة أو مرتين يومياً – ١٠–١٤ يوم',
		category: Category.SULFONAMIDES,
		form: 'Cream',
		minAgeMonths: 2,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 200,
		calculationRule: () => 'طبقة رقيقة على المنطقة المصابة مرة أو مرتين يومياً لمدة ١٠–١٤ يوم',
		warnings: ['ممنوع لمرضى حساسية السلفا.', 'للاستعمال الخارجي فقط.'],
	},
];

