import { Category, Medication } from '../../../types';

const fixed = (t: string) => () => t;

const COMMON_HAIR_CARE_WARNINGS = [
	'تجنب ملامسة العينين. عند حدوث تلامس تُشطف العين جيداً بالماء.',
	'أوقف الاستخدام إذا حدث تهيّج شديد/حكة شديدة/حساسية.',
];

const ANTI_DANDRUFF_SHAMPOO_WARNINGS = [
	...COMMON_HAIR_CARE_WARNINGS,
	'للقشرة/التهاب فروة الرأس: إذا لم تتحسن الحالة خلال ٢–٤ أسابيع يُفضّل تقييم طبي.',
];

const MINOXIDIL_WARNINGS = [
	'للاستخدام الخارجي على فروة الرأس فقط. لا يُستخدم على جلد ملتهب/مجروح.',
	'يُغسل اليدان بعد الاستخدام. تجنب ملامسة العينين/الفم.',
	'قد يحدث تساقط مؤقت أول ٢–٨ أسابيع (Shedding) ثم يبدأ التحسن تدريجياً.',
	'مينوكسيديل: يُتجنب في الحمل/الرضاعة (غير مُثبت الأمان).',
	'دوار/خفقان/تورم يدين أو قدمين/ضيق نفس: أوقف؛ أعد التقييم (ضغط، وذمة، قصور قلب).',
	'محاليل المينوكسيديل قابلة للاشتعال: تُترك لتجف تماماً قبل التدخين/الحرارة.',
];

export const HAIR_CARE_LGT_PART_1_GROUP: Medication[] = [
	// 1
	{
		id: 'justin-blue-hair-shampoo-175ml',
		name: 'justin blue hair shampoo 175 ml',
		genericName: 'selenium sulfide & piroctone olamine & rosemary extract',
		concentration: '175 ml',
		price: 360,
		matchKeywords: ['justin blue', 'selenium sulfide', 'piroctone olamine', 'rosemary', 'dandruff', 'قشرة', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مضاد للقشرة وتقليل الحكة ودهنية فروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 2
	{
		id: 'penduline-kids-hair-cream-150ml',
		name: 'penduline kids hair cream 150ml',
		genericName: 'argan oil & jojoba oil & aloe vera & olive oil & almond oil',
		concentration: '150 ml',
		price: 150,
		matchKeywords: ['penduline', 'penduline kids', 'hair cream', 'argan', 'jojoba', 'aloe vera', 'كريم شعر', 'اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم ترطيب وتنعيم للشعر للأطفال لتقليل الهيشان والتشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 3
	{
		id: 'hepta-panthenol-hair-cream-100gm',
		name: 'hepta panthenol hair cream 100 gm',
		genericName: 'panthenol & vitamin e & jojoba oil & argan oil & shea butter',
		concentration: '100 gm',
		price: 149,
		matchKeywords: ['hepta panthenol', 'panthenol', 'vitamin e', 'hair cream', 'كريم بانثينول', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم شعر مرطب لتقليل الجفاف والتقصف وتحسين نعومة الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 4
	{
		id: 'aloekita-anti-dandruff-shampoo-200ml',
		name: 'aloekita anti-dandruff shampoo 200ml',
		genericName: 'caffeine & saw palmetto & amla & aloe vera & tea tree oil',
		concentration: '200 ml',
		price: 159,
		matchKeywords: ['aloekita', 'anti-dandruff', 'tea tree', 'caffeine', 'شامبو', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مضاد للقشرة وتهدئة الحكة وتنظيف فروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 5
	{
		id: 'aloekita-hair-conditioner-200ml',
		name: 'aloekita hair conditioner 200ml',
		genericName: 'caffeine & saw palmetto & amla & aloe vera & tea tree oil',
		concentration: '200 ml',
		price: 249,
		matchKeywords: ['aloekita conditioner', 'conditioner', 'بلسم', 'ترطيب', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'بلسم لترطيب الشعر وتقليل التشابك والهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 6
	{
		id: 'panthenol-2pct-topical-cream-15gm',
		name: 'panthenol 2% topical cream 15 gm',
		genericName: 'panthenol',
		concentration: '2% (15 gm)',
		price: 32,
		matchKeywords: ['panthenol 2%', 'panthenol cream', 'بانثينول', 'ترطيب', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم مرطب ومُلطف للجلد (قد يُستخدم لتهدئة جفاف/تهيج بسيط حول فروة الرأس).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 7
	{
		id: 'selengena-anti-dandruff-shampoo-220ml',
		name: 'selengena anti-dandruff shampoo 220 ml',
		genericName: 'selenium sulphide',
		concentration: '220 ml',
		price: 165,
		matchKeywords: ['selengena', 'selenium sulphide', 'anti-dandruff', 'شامبو', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو سيلينيوم سلفايد للقشرة/التهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 8
	{
		id: 'hepta-panthenol-hair-oil-120ml',
		name: 'hepta panthenol hair oil 120 ml',
		genericName: 'panthenol & shea oil & beta sitosterol & pumpkin oil',
		concentration: '120 ml',
		price: 175,
		matchKeywords: ['hepta panthenol oil', 'hair oil', 'panthenol', 'زيت شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/لوشن مغذي للشعر لتقليل الجفاف والتقصف وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 10
	{
		id: 'aloekita-hair-shampoo-200ml',
		name: 'aloekita hair shampoo 200ml',
		genericName: 'caffeine & saw palmetto & amla & aloe vera & tea tree oil',
		concentration: '200 ml',
		price: 199,
		matchKeywords: ['aloekita', 'hair shampoo', 'شامبو', 'تنظيف', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 11
	{
		id: 'aloekita-hair-spray-200ml',
		name: 'aloekita hair spray 200 ml',
		genericName: 'caffeine & saw palmetto & amla & aloe vera & tea tree oil',
		concentration: '200 ml',
		price: 359,
		matchKeywords: ['aloekita spray', 'hair spray', 'سبراي شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي للشعر/الفروة لدعم المظهر وتقليل الهيشان حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 12
	{
		id: 'hair-plus-back-5pct-foam-100ml',
		name: 'hair plus-back 5% foam 100 ml',
		genericName: 'minoxidil',
		concentration: '5% (100 ml)',
		price: 237,
		matchKeywords: ['hair plus-back', 'minoxidil 5%', 'foam', 'hair regrowth', 'تساقط الشعر', 'صلع وراثي', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ لإعادة إنبات الشعر في الصلع الوراثي (Androgenetic alopecia).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Foam',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 13
	{
		id: 'hair-plus-back-5pct-lotion',
		name: 'hair plus-back 5% lotion',
		genericName: 'minoxidil',
		concentration: '5% (topical)',
		price: 237,
		matchKeywords: ['hair plus-back', 'minoxidil 5%', 'lotion', 'solution', 'hair regrowth', 'تساقط الشعر', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ محلول/لوشن لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 14
	{
		id: 'herbamix-anti-dandruff-shampoo-200ml',
		name: 'herbamix anti-dandruff shampoo 200 ml',
		genericName: 'phyto-extract-bio-active oils',
		concentration: '200 ml',
		price: 190,
		matchKeywords: ['herbamix', 'anti-dandruff', 'shampoo', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مضاد للقشرة وتهدئة الحكة (تركيبة عشبية).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 15
	{
		id: 'ketoral-plus-hair-shampoo-125ml',
		name: 'ketoral plus hair shampoo 125ml',
		genericName: 'pirocotone olamine & cleansing base',
		concentration: '125 ml',
		price: 95,
		matchKeywords: ['ketoral plus', 'octopirox', 'piroctone', 'anti-dandruff', 'شامبو', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مضاد للقشرة وتقليل الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 16
	{
		id: 'kitadan-hair-shampoo-200ml',
		name: 'kitadan hair shampoo 200ml',
		genericName: 'zinc pyrithione & octopirox & green tea & papaya',
		concentration: '200 ml',
		price: 199,
		matchKeywords: ['kitadan shampoo', 'zinc pyrithione', 'octopirox', 'anti-dandruff', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بفروة الرأس وتقليل القشرة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 17
	{
		id: 'kitadan-hair-spray-120ml',
		name: 'kitadan hair spray 120 ml',
		genericName: 'piroctone olamine & tea tree oil & biotin',
		concentration: '120 ml',
		price: 249,
		matchKeywords: ['kitadan spray', 'hair spray', 'biotin', 'tea tree', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي للعناية بفروة الرأس وتقليل الدهون/القشرة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 18
	{
		id: 'minoxilook-5pct-hair-spray-100ml',
		name: 'minoxilook 5% hair spray 100 ml',
		genericName: 'minoxidil',
		concentration: '5% (100 ml)',
		price: 144,
		matchKeywords: ['minoxilook', 'minoxidil 5%', 'hair spray', 'hair regrowth', 'تساقط الشعر', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 19
	{
		id: 'new-akim-hair-oil-120ml',
		name: 'new akim hair oil 120 ml',
		genericName: 'tea tree oil & lavender oil & rosemary oil & thyme oil',
		concentration: '120 ml',
		price: 100,
		matchKeywords: ['new akim', 'hair oil', 'tea tree', 'rosemary', 'زيت شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/لوشن شعر للعناية بالفروة وتقليل الجفاف وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 20
	{
		id: 'new-akim-hair-oil-60ml',
		name: 'new akim hair oil 60ml',
		genericName: 'tea tree oil & lavender oil & rosemary oil & thyme oil',
		concentration: '60 ml',
		price: 80,
		matchKeywords: ['new akim', 'hair oil', '60ml', 'زيت شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/لوشن شعر للعناية بالفروة وتقليل الجفاف وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 21
	{
		id: 'penduline-kids-hair-mask-300ml',
		name: 'penduline kids hair mask 300 ml',
		genericName: 'argan oil & jojoba oil & pumpkin oil & sesame oil & almond oil',
		concentration: '300 ml',
		price: 95,
		matchKeywords: ['penduline mask', 'penduline kids', 'hair mask', 'ماسك شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك ترطيب عميق للأطفال لتقليل الهيشان والتشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 22
	{
		id: 'penduline-kids-hair-oil-120ml',
		name: 'penduline kids hair oil 120ml',
		genericName: 'sesame oil & wheat germ oil & coconut oil & eruca sativa oil',
		concentration: '120 ml',
		price: 210,
		matchKeywords: ['penduline kids oil', 'hair oil', 'زيت شعر', 'اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/لوشن شعر للأطفال لتغذية وترطيب الشعر وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 23
	{
		id: 'penduline-kids-shampoo-250ml',
		name: 'penduline kids shampoo 250ml',
		genericName: 'argan oil & jojoba oil & hydrolyzed protein',
		concentration: '250 ml',
		price: 170,
		matchKeywords: ['penduline kids shampoo', 'penduline', 'kids shampoo', 'شامبو اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو أطفال لطيف لتنظيف الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 24
	{
		id: 'penduline-kids-shampoo-450ml',
		name: 'penduline kids shampoo 450ml',
		genericName: 'argan oil & jojoba oil & hydrolyzed protein',
		concentration: '450 ml',
		price: 220,
		matchKeywords: ['penduline kids shampoo', '450ml', 'شامبو اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو أطفال لطيف لتنظيف الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 25
	{
		id: 'penduline-shea-kids-hair-cream-150ml',
		name: 'penduline shea kids hair cream 150ml',
		genericName: 'shea butter & avocado oil & banana extract & jojoba oil',
		concentration: '150 ml',
		price: 135,
		matchKeywords: ['penduline shea', 'kids hair cream', 'shea butter', 'كريم شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم شعر للأطفال لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 26
	{
		id: 'perfectodil-5pct-top-solution-60ml',
		name: 'perfectodil 5% top.solution 60 ml',
		genericName: 'minoxidil',
		concentration: '5% (60 ml)',
		price: 97,
		matchKeywords: ['perfectodil', 'minoxidil 5%', 'topical solution', 'hair regrowth', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ محلول لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 27
	{
		id: 'performa-extra-strength-5pct-topical-solution-60ml',
		name: 'performa extra strength 5% topical solution 60 ml',
		genericName: 'minoxidil',
		concentration: '5% (60 ml)',
		price: 156,
		matchKeywords: ['performa', 'extra strength', 'minoxidil 5%', 'topical solution', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ محلول لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 28
	{
		id: 'rozalia-hair-lotion-120ml',
		name: 'rozalia hair lotion 120 ml',
		genericName: 'ginseng extract & ginkgo biloba extract & grape seed extract & caffeine',
		concentration: '120 ml',
		price: 300,
		matchKeywords: ['rozalia lotion', 'hair lotion', 'ginseng', 'caffeine', 'لوشن شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن للشعر/الفروة لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 29
	{
		id: 'rozalia-hair-oil-120ml',
		name: 'rozalia hair oil 120 ml',
		genericName: 'silicon & amla oil & coconut oil & olive oil & almond oil',
		concentration: '120 ml',
		price: 161,
		matchKeywords: ['rozalia oil', 'hair oil', 'amla', 'coconut oil', 'زيت شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/سيروم زيتي لتغذية الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 30
	{
		id: 'rozalia-hair-serum-120ml',
		name: 'rozalia hair serum 120 ml',
		genericName: 'silicon & amla oil & coconut oil & olive oil & almond oil',
		concentration: '120 ml',
		price: 300,
		matchKeywords: ['rozalia serum', 'hair serum', 'silicon', 'سيروم شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتقليل الهيشان والتقصف وتحسين نعومة ولمعان الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 31
	{
		id: 'rozalia-hair-shampoo-200ml',
		name: 'rozalia hair shampoo 200 ml',
		genericName: '3g2c peptide complex & caffeine',
		concentration: '200 ml',
		price: 235,
		matchKeywords: ['rozalia shampoo', 'peptide', 'caffeine', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهر الكثافة وتقليل الضعف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 32
	{
		id: 'selengena-anti-dandruff-shampoo-120ml',
		name: 'selengena anti-dandruff shampoo 120 ml',
		genericName: 'selenium sulphide',
		concentration: '120 ml',
		price: 105,
		matchKeywords: ['selengena', 'selenium sulphide', 'anti-dandruff', '120ml', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو سيلينيوم سلفايد للقشرة/التهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},
];

