import { Category, Medication } from '../../../types';

const fixed = (t: string) => () => t;

const COMMON_HAIR_CARE_WARNINGS = [
	'تجنب ملامسة العينين. عند حدوث تلامس تُشطف العين جيداً بالماء.',
	'أوقف الاستخدام إذا حدث تهيّج شديد/حكة شديدة/حساسية.',
];

const ANTI_DANDRUFF_SHAMPOO_WARNINGS = [
	...COMMON_HAIR_CARE_WARNINGS,
	'للقشرة/التهاب فروة الرأس: إذا لم تتحسن الحالة خلال ٢–٤ أسابيع يُفضّل تقييم طبي.',
];

const MINOXIDIL_WARNINGS = [
	'للاستخدام الخارجي على فروة الرأس فقط. لا يُستخدم على جلد ملتهب/مجروح.',
	'يُغسل اليدان بعد الاستخدام. تجنب ملامسة العينين/الفم.',
	'قد يحدث تساقط مؤقت أول ٢–٨ أسابيع (Shedding) ثم يبدأ التحسن تدريجياً.',
	'مينوكسيديل: يُتجنب في الحمل/الرضاعة (غير مُثبت الأمان).',
	'إذا حدث دوخة/خفقان/تورم باليدين أو القدمين/ضيق نفس: أوقفه واستشر طبيباً.',
	'محاليل/رغوة المينوكسيديل قابلة للاشتعال: تُترك لتجف تماماً قبل التدخين/الحرارة.',
];

const ORAL_HAIR_SUPPLEMENT_WARNINGS = [
	'مكمل غذائي: لا يغني عن الغذاء المتوازن.',
	'الحمل/الرضاعة: يُستشار الطبيب قبل الاستخدام.',
	'راجع التفاعلات مع الأدوية الجهازية (مميعات، سكري، ضغط، إلخ)؛ تجنب الجمع دون تقييم.',
];

export const HAIR_CARE_LGT_PART_3_GROUP: Medication[] = [
	// 89
	{
		id: 'clear-scalp-shampoo-180ml',
		name: 'clear- scalp 180 ml shampoo',
		genericName: 'polyquaternium-7 & argan oil & vitamin e',
		concentration: '180 ml',
		price: 97,
		matchKeywords: ['clear scalp', 'scalp shampoo', 'argan', 'vitamin e', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس وترطيب الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 90
	{
		id: 'yonyrex-hair-tonic-spray-120ml',
		name: 'yonyrex 120 ml hair tonic spray',
		genericName: 'aloe vera extract & panthenol & ginseng extract',
		concentration: '120 ml',
		price: 180,
		matchKeywords: ['yonyrex', 'hair tonic', 'tonic spray', 'ginseng', 'panthenol', 'تونك', '#hair_tonic', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'تونك سبراي لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 91
	{
		id: 'alojoba-hair-serum-120ml',
		name: 'alojoba hair serum 120 ml',
		genericName: 'argan oil & olive oil & vitamin e & silicone mixture',
		concentration: '120 ml',
		price: 250,
		matchKeywords: ['alojoba', 'hair serum', 'argan', 'olive oil', 'vitamin e', 'سيروم', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 92
	{
		id: 'alojoba-hair-shampoo-120ml',
		name: 'alojoba hair shampoo 120 ml',
		genericName: 'jojoba oil & aloe vera oil & ostrich oil & garlic oil',
		concentration: '120 ml',
		price: 70,
		matchKeywords: ['alojoba shampoo', 'jojoba', 'aloe vera', 'garlic', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 93
	{
		id: 'blockopecia-5pct-topical-solution-60ml',
		name: 'blockopecia 5% topical solution 60 ml',
		genericName: 'minoxidil',
		concentration: '5% (60 ml)',
		price: 107,
		matchKeywords: ['blockopecia', 'minoxidil 5%', 'topical solution', 'hair regrowth', '#hair_regrowth', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'مينوكسيديل ٥٪ محلول لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 94
	{
		id: 'cafa-ds-hair-cream-120gm',
		name: 'cafa ds hair cream 120 gm',
		genericName: 'caffeine & olive oil & panthenol & aloe vera',
		concentration: '120 gm',
		price: 199,
		matchKeywords: ['cafa ds', 'hair cream', 'caffeine', 'panthenol', 'aloe vera', 'كريم', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم للشعر لترطيب وتنعيم وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 95
	{
		id: 'dan-off-hair-shampoo-250ml',
		name: 'dan off hair shampoo 250ml',
		genericName: 'piroctone olamine & chamomile extract & rosemary',
		concentration: '250 ml',
		price: 185,
		matchKeywords: ['dan off', 'piroctone olamine', 'anti-dandruff', 'شامبو', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مضاد للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 96
	{
		id: 'dandivera-hair-shampoo-100ml',
		name: 'dandivera hair shampoo 100ml',
		genericName: 'zinc pyrithione & aloe vera & resorcinol',
		concentration: '100 ml',
		price: 35,
		matchKeywords: ['dandivera', '100ml', 'zinc pyrithione', 'resorcinol', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة والتهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 97
	{
		id: 'dandivera-hair-spray-120ml',
		name: 'dandivera hair spray 120 ml',
		genericName: 'piroctone olamine & cetrimide & triclosan & tea tree oil',
		concentration: '120 ml',
		price: 80,
		matchKeywords: ['dandivera spray', 'piroctone', 'tea tree', 'hair spray', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي للعناية بفروة الرأس وتقليل القشرة/الحكة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 98
	{
		id: 'daryan-hair-shampoo-100ml',
		name: 'daryan hair shampoo 100 ml',
		genericName: 'selenium sulfide & zinc pyrithione & chamomile',
		concentration: '100 ml',
		price: 95,
		matchKeywords: ['daryan', 'selenium sulfide', 'zinc pyrithione', 'قشرة', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة/التهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 99
	{
		id: 'top-hair-lotion-120ml',
		name: 'top hair lotion 120 ml',
		genericName: 'caffeine & argan oil & ginseng & wheat germ oil',
		concentration: '120 ml',
		price: 180,
		matchKeywords: ['top hair lotion', 'caffeine', 'ginseng', 'لوشن', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 100
	{
		id: 'ebafix-hair-conditioning-shampoo-200ml',
		name: 'ebafix hair conditioning shampoo 200 ml',
		genericName: 'keratin & hydrolyzed soy protein & silicone oil',
		concentration: '200 ml',
		price: 209,
		matchKeywords: ['ebafix shampoo', 'conditioning shampoo', 'keratin', 'soy protein', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مُكيف للشعر (تنظيف + تقليل التشابك).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 101
	{
		id: 'ebafix-hair-serum-120ml',
		name: 'ebafix hair serum 120 ml',
		genericName: 'cyclopentasiloxane & vitamin e & amla',
		concentration: '120 ml',
		price: 219,
		matchKeywords: ['ebafix serum', 'cyclopentasiloxane', 'amla', 'vitamin e', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 102
	{
		id: 'emmyrosa-hair-lotion-120ml',
		name: 'emmyrosa hair lotion 120 ml',
		genericName: 'saw palmetto & garlic & lavender & chamomile',
		concentration: '120 ml',
		price: 249,
		matchKeywords: ['emmyrosa', 'hair lotion', 'saw palmetto', 'لوشن', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 103
	{
		id: 'girly-hair-oil-120ml',
		name: 'girly hair oil 120ml',
		genericName: 'lavender oil & thyme extract & garlic extract',
		concentration: '120 ml',
		price: 125,
		matchKeywords: ['girly hair oil', 'lavender', 'thyme', 'garlic', 'زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 104
	{
		id: 'hairodex-anti-dandruff-shampoo-250ml',
		name: 'hairodex anti-dandruff shampoo 250 ml',
		genericName: 'zinc pyrithione & panthenol & wheat germ oil',
		concentration: '250 ml',
		price: 160,
		matchKeywords: ['hairodex anti-dandruff', 'zinc pyrithione', 'panthenol', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 105
	{
		id: 'hairodex-hair-cream-100gm',
		name: 'hairodex hair cream 100 gm',
		genericName: 'silicone oil & jojoba oil & olive oil & almond oil',
		concentration: '100 gm',
		price: 160,
		matchKeywords: ['hairodex cream', 'jojoba', 'almond oil', 'hair cream', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 106
	{
		id: 'hairodex-hair-shampoo-250ml',
		name: 'hairodex hair shampoo 250 ml',
		genericName: 'panthenol & ginkgo extract & jojoba oil & rosemary extract',
		concentration: '250 ml',
		price: 180,
		matchKeywords: ['hairodex shampoo', 'panthenol', 'ginkgo', 'rosemary', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف الفروة والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 107
	{
		id: 'hairvogine-hair-lotion-100ml',
		name: 'hairvogine hair lotion 100 ml',
		genericName: 'caffeine',
		concentration: '100 ml',
		price: 490,
		matchKeywords: ['hairvogine', 'caffeine', 'hair lotion', 'لوشن', '#hair_care', '#hair_tonic'],
		usage: 'لوشن/تونك لفروة الرأس (كافيين) لدعم تقليل التساقط وتحسين نشاط البصيلات.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 108
	{
		id: 'intepline-bath-cream-150ml',
		name: 'intepline bath cream 150 ml',
		genericName: 'cetrimonium chloride',
		concentration: '150 ml',
		price: 165,
		matchKeywords: ['intepline', 'bath cream', 'cetrimonium chloride', 'cream', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم/بديل زيت لترطيب وتنعيم الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 109
	{
		id: 'investa-oil-replacement-120gm',
		name: 'investa oil replacement 120 gm',
		genericName: 'jojoba oil & castor oil & caffeine & saw palmetto',
		concentration: '120 gm',
		price: 130,
		matchKeywords: ['investa oil replacement', 'jojoba', 'castor', 'caffeine', 'cream', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'بديل زيت/كريم للشعر لترطيب وتنعيم وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 110
	{
		id: 'keraket-hair-shampoo-250ml',
		name: 'keraket hair shampoo 250 ml',
		genericName: 'keratin & panthenol & castor oil & olive oil & aloe vera',
		concentration: '250 ml',
		price: 165,
		matchKeywords: ['keraket', 'keratin', 'panthenol', 'shampoo', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف الشعر والعناية به (كيراتين + بانثينول).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 111
	{
		id: 'keranty-shampoo-250ml',
		name: 'keranty shampoo 250 ml',
		genericName: 'biotin & keratin & caffeine & argan oil',
		concentration: '250 ml',
		price: 240,
		matchKeywords: ['keranty', 'biotin', 'keratin', 'caffeine', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهر الكثافة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 112
	{
		id: 'marleoce-shampoo-150ml',
		name: 'marleoce shampoo 150 ml',
		genericName: 'coal tar & zinc pyrithione & tea tree oil & caffeine',
		concentration: '150 ml',
		price: 195,
		matchKeywords: ['marleoce', 'coal tar', 'zinc pyrithione', 'tea tree', 'tar', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة الشديدة/التهاب الجلد الدهني وقد يفيد في الصدفية بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 113
	{
		id: 'new-jolly-hair-oil-120ml',
		name: 'new jolly hair oil 120 ml',
		genericName: 'olive oil & chamomile oil & coconut oil & sage oil',
		concentration: '120 ml',
		price: 110,
		matchKeywords: ['new jolly', 'hair oil', 'olive oil', 'coconut', 'زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 114
	{
		id: 'o-pedal-hair-serum-spray-120ml',
		name: 'o-pedal hair serum spray 120 ml',
		genericName: 'polydimethylsiloxanes & lavender oil & herbal fragrance',
		concentration: '120 ml',
		price: 195,
		matchKeywords: ['o-pedal', 'hair serum spray', 'polydimethylsiloxane', 'lavender', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 115
	{
		id: 'panthenol-hair-shampoo-215ml',
		name: 'panthenol hair shampoo 215ml',
		genericName: 'panthenol (vitamin b5)',
		concentration: '215 ml',
		price: 75,
		matchKeywords: ['panthenol shampoo', 'vitamin b5', 'شامبو بانثينول', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لطيف لترطيب الشعر وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 116
	{
		id: 'pross-hair-lotion-250ml',
		name: 'pross hair lotion 250 ml',
		genericName: 'saw palmetto & caffeine & ginkgo & royal jelly',
		concentration: '250 ml',
		price: 260,
		matchKeywords: ['pross hair lotion', 'saw palmetto', 'caffeine', 'ginkgo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 117
	{
		id: 'pross-hair-oil-250ml',
		name: 'pross hair oil 250 ml',
		genericName: 'grape seed oil & rosemary oil & jojoba oil & thyme',
		concentration: '250 ml',
		price: 260,
		matchKeywords: ['pross hair oil', 'grape seed', 'rosemary', 'jojoba', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 118
	{
		id: 'pross-hair-serum-250ml',
		name: 'pross hair serum 250 ml',
		genericName: 'dimethicone & oils blend',
		concentration: '250 ml',
		price: 350,
		matchKeywords: ['pross hair serum', 'dimethicone', 'serum', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 119
	{
		id: 'pross-hair-shampoo-250ml',
		name: 'pross hair shampoo 250 ml',
		genericName: 'panthenol & caffeine & saw palmetto extract',
		concentration: '250 ml',
		price: 220,
		matchKeywords: ['pross shampoo', 'panthenol', 'caffeine', 'saw palmetto', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس ودعم مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 120
	{
		id: 'selenika-shampoo-120ml',
		name: 'selenika shampoo 120 ml',
		genericName: 'selenium sulfide & piroctone olamine & tea tree oil',
		concentration: '120 ml',
		price: 75,
		matchKeywords: ['selenika', 'selenium sulfide', 'piroctone olamine', 'tea tree', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة/التهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 121
	{
		id: 'selenix-shampoo-conditioner-150ml',
		name: 'selenix shampoo & conditioner 150 ml',
		genericName: 'piroctone olamine & selenium sulphide & neem extract',
		concentration: '150 ml',
		price: 160,
		matchKeywords: ['selenix', 'shampoo conditioner', 'neem', 'piroctone', 'selenium', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو + بلسم (٢ في ١) للمساعدة في القشرة وتنظيف الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 122
	{
		id: 'seroleze-hair-serum-120ml',
		name: 'seroleze hair serum 120 ml',
		genericName: 'dimethicone & dimethiconol & soy bean oil & olive oil',
		concentration: '120 ml',
		price: 300,
		matchKeywords: ['seroleze', 'hair serum', 'dimethiconol', 'soy bean oil', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 123
	{
		id: 'mi-kids-lotion-110ml',
		name: 'mi kids lotion 110 ml',
		genericName: 'biotin & caffeine & green coffee & saw palmetto',
		concentration: '110 ml',
		price: 175,
		matchKeywords: ['mi kids lotion', 'kids', 'biotin', 'caffeine', 'loشن', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن/تونك للأطفال للعناية بالشعر والفروة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 124
	{
		id: 'tola-hair-lotion-120ml',
		name: 'tola hair lotion 120 ml',
		genericName: 'avocado oil & castor oil & jojoba oil & garlic',
		concentration: '120 ml',
		price: 219,
		matchKeywords: ['tola', 'hair lotion', 'avocado', 'castor', 'jojoba', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس/الشعر للعناية وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 125
	{
		id: 'tonika-shampoo-200ml',
		name: 'tonika shampoo 200 ml',
		genericName: 'caffeine & rosemary & eruca oil & olive oil & aloe vera',
		concentration: '200 ml',
		price: 185,
		matchKeywords: ['tonika', 'caffeine', 'rosemary', 'eruca', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف الفروة ودعم مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 126
	{
		id: 'treato-hair-serum-120ml',
		name: 'treato hair serum 120 ml',
		genericName: 'silicone oil & jojoba oil & olive extract & rosemary',
		concentration: '120 ml',
		price: 300,
		matchKeywords: ['treato', 'hair serum', 'jojoba', 'rosemary', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 127
	{
		id: 'villakord-hair-oil-120ml',
		name: 'villakord hair oil 120 ml',
		genericName: 'caffeine & argan oils & aloe oils & castor oils',
		concentration: '120 ml',
		price: 165,
		matchKeywords: ['villakord hair oil', 'argan', 'aloe', 'castor', 'زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 128
	{
		id: 'vital-hair-oil-120ml',
		name: 'vital hair oil 120 ml',
		genericName: 'eruca oil & jojoba oil & nigella oil & garlic oil',
		concentration: '120 ml',
		price: 220,
		matchKeywords: ['vital hair oil', 'eruca', 'jojoba', 'nigella', 'garlic', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 129
	{
		id: 'anaforten-hair-shampoo-200ml',
		name: 'anaforten hair shampoo 200 ml',
		genericName: 'saw palmetto & vitamins b6 & vitamins b12',
		concentration: '200 ml',
		price: 165,
		matchKeywords: ['anaforten', 'saw palmetto', 'vitamin b6', 'vitamin b12', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهر الكثافة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 130
	{
		id: 'coffee-zinc-shampoo-200ml-hc3',
		name: 'coffee zinc shampoo 200ml',
		genericName: 'caffeine & zinc pyrithione & piroctone olamine',
		concentration: '200 ml',
		price: 179,
		matchKeywords: ['coffee zinc shampoo', 'caffeine', 'zinc pyrithione', 'piroctone olamine', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 131
	{
		id: 'concreta-hair-mask-200gm',
		name: 'concreta hair mask 200 gm',
		genericName: 'avocado extract & shea butter & coconut oil',
		concentration: '200 gm',
		price: 160,
		matchKeywords: ['concreta', 'hair mask', 'avocado', 'shea', 'coconut', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك لترطيب عميق وتقليل الهيشان والتشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 132
	{
		id: 'dago-plus-hair-shampoo-200ml',
		name: 'dago plus hair shampoo 200ml',
		genericName: 'selenium sulphide & zinc pyrithione',
		concentration: '200 ml',
		price: 199,
		matchKeywords: ['dago plus', 'selenium sulphide', 'zinc pyrithione', 'anti-dandruff', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 133
	{
		id: 'villakord-hair-serum-100ml',
		name: 'villakord hair serum 100 ml',
		genericName: 'caffeine & argan oils & aloe oils & castor oils',
		concentration: '100 ml',
		price: 180,
		matchKeywords: ['villakord serum', 'hair serum', 'argan', 'aloe', 'castor', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 134
	{
		id: 'weedobon-hair-shampoo-200ml',
		name: 'weedobon hair shampoo 200 ml',
		genericName: 'keratin & coconut & panthenol & saw palmetto extract',
		concentration: '200 ml',
		price: 120,
		matchKeywords: ['weedobon', 'keratin', 'panthenol', 'saw palmetto', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهره.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 135
	{
		id: 'new-jolly-hair-tonic-serum-120ml',
		name: 'new jolly hair tonic serum 120 ml',
		genericName: 'caffeine & dimethicone & cyclopentasiloxane',
		concentration: '120 ml',
		price: 190,
		matchKeywords: ['new jolly tonic', 'hair tonic', 'caffeine', 'serum', '#hair_care', '#hair_tonic'],
		usage: 'تونك/سيروم لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 136
	{
		id: 'grow-max-lotion-125ml',
		name: 'grow max lotion 125ml',
		genericName: 'procapil & caffeine & saw palmetto extract & argan',
		concentration: '125 ml',
		price: 197,
		matchKeywords: ['grow max', 'procapil', 'caffeine', 'saw palmetto', 'lotion', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 137
	{
		id: 'alojoba-hair-shampoo-250ml',
		name: 'alojoba hair shampoo 250 ml',
		genericName: 'jojoba oil & aloe vera oil & ostrich oil & garlic oil',
		concentration: '250 ml',
		price: 105,
		matchKeywords: ['alojoba shampoo', '250ml', 'jojoba', 'garlic', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 138
	{
		id: 'cranby-20-caps',
		name: 'cranby 20 caps.',
		genericName: 'cranberry extract & d-mannose',
		concentration: '20 caps',
		price: 130,
		matchKeywords: ['cranby', 'cranberry', 'd-mannose', 'caps', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'مكمل غذائي (كرانبيري) — يستخدم حسب الحاجة الغذائية/الإرشاد.',
		timing: 'مرة يومياً مع الأكل – ٣ شهور',
		category: Category.HAIR_CARE,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة ٣ شهور'),
		warnings: [...ORAL_HAIR_SUPPLEMENT_WARNINGS],
	},

	// 139
	{
		id: 'rostevo-hair-cream-100gm',
		name: 'rostevo hair cream 100 gram',
		genericName: 'caffeine & olive oil & vitamin e & rosemary oil',
		concentration: '100 gm',
		price: 140,
		matchKeywords: ['rostevo hair cream', 'caffeine', 'rosemary', 'cream', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم لترطيب وتنعيم وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 140
	{
		id: 'rostevo-shampoo-caffeine-keratin-250ml',
		name: 'rostevo shampoo with caffeine & keratin 250ml',
		genericName: 'caffeine & hydrolyzed keratin & garlic extract',
		concentration: '250 ml',
		price: 100,
		matchKeywords: ['rostevo shampoo', 'caffeine', 'keratin', 'garlic', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهره.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 141
	{
		id: 'rostevo-shea-butter-100gm',
		name: 'rostevo shea butter 100gm',
		genericName: 'shea butter & vitamin e',
		concentration: '100 gm',
		price: 150,
		matchKeywords: ['rostevo shea', 'shea butter', 'vitamin e', 'shea', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زبدة شيا لترطيب الشعر الجاف وتقليل الهيشان (تُستخدم بكميات صغيرة).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 142
	{
		id: 'wonder-hair-serum-100ml',
		name: 'wonder hair serum 100ml',
		genericName: 'ceramide & argan oil',
		concentration: '100 ml',
		price: 150,
		matchKeywords: ['wonder hair serum', 'ceramide', 'argan', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 143
	{
		id: 'wonder-hair-shampoo-200ml',
		name: 'wonder hair shampoo 200ml',
		genericName: 'caffeine & saw palmetto & biotin',
		concentration: '200 ml',
		price: 170,
		matchKeywords: ['wonder shampoo', 'caffeine', 'saw palmetto', 'biotin', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهر الكثافة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 144
	{
		id: 'dago-hair-shampoo-250ml',
		name: 'dago hair shampoo 250ml',
		genericName: 'zinc pyrithione & aloe vera & tea tree oil & panthenol',
		concentration: '250 ml',
		price: 250,
		matchKeywords: ['dago shampoo', 'zinc pyrithione', 'tea tree', 'panthenol', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 145
	{
		id: 'complete-hair-oil-60ml',
		name: 'complete hair oil 60 ml',
		genericName: 'panthenol & salicylic acid & piroctone olamine',
		concentration: '60 ml',
		price: 105,
		matchKeywords: ['complete hair oil', '60ml', 'panthenol', 'salicylic', 'piroctone', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/لوشن لفروة الرأس للمساعدة في القشرة والحكة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 146
	{
		id: 'final-2-hair-shampoo-240ml',
		name: 'final 2 hair shampoo 240ml',
		genericName: 'aloe vera extract & olive oil & resorcinol',
		concentration: '240 ml',
		price: 95,
		matchKeywords: ['final 2', 'resorcinol', 'aloe vera', 'olive oil', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بفروة الرأس وتقليل القشرة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 147
	{
		id: 'follitone-hair-spray-120ml',
		name: 'follitone hair spray 120ml',
		genericName: 'rosemary extract & jojoba oil & thyme extract',
		concentration: '120 ml',
		price: 225,
		matchKeywords: ['follitone spray', 'rosemary', 'jojoba', 'thyme', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي تونك/عناية لفروة الرأس لدعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 148
	{
		id: 'follitone-hair-spray-100ml',
		name: 'follitone hair spray 100ml',
		genericName: 'rosemary extract & jojoba oil & thyme extract',
		concentration: '100 ml',
		price: 64.75,
		matchKeywords: ['follitone spray', '100ml', 'rosemary', 'jojoba', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي تونك/عناية لفروة الرأس لدعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 149
	{
		id: 'follitone-hair-oil-120ml',
		name: 'follitone hair oil 120ml',
		genericName: 'rosemary extract & jojoba oil & thyme extract',
		concentration: '120 ml',
		price: 190,
		matchKeywords: ['follitone hair oil', 'rosemary', 'jojoba', 'thyme', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 150
	{
		id: 'troya-care-hair-shampoo-200ml',
		name: 'troya care hair shampoo 200 ml',
		genericName: 'caffeine & panthenol & biotin & keratin & argan',
		concentration: '200 ml',
		price: 125,
		matchKeywords: ['troya care', 'biotin', 'keratin', 'argan', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهر الكثافة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 151
	{
		id: 'magic-hair-oil-60ml',
		name: 'magic hair oil 60 ml',
		genericName: 'olive oil & almond oil & eruca oil',
		concentration: '60 ml',
		price: 90,
		matchKeywords: ['magic hair oil', 'olive', 'almond', 'eruca', 'زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},
];

