import { Category, Medication } from '../../../types';

const fixed = (t: string) => () => t;

const COMMON_HAIR_CARE_WARNINGS = [
	'تجنب ملامسة العينين. عند حدوث تلامس تُشطف العين جيداً بالماء.',
	'أوقف الاستخدام إذا حدث تهيّج شديد/حكة شديدة/حساسية.',
];

const ANTI_DANDRUFF_SHAMPOO_WARNINGS = [
	...COMMON_HAIR_CARE_WARNINGS,
	'للقشرة/التهاب فروة الرأس: إذا لم تتحسن الحالة خلال ٢–٤ أسابيع يُفضّل تقييم طبي.',
];

const MINOXIDIL_WARNINGS = [
	'للاستخدام الخارجي على فروة الرأس فقط. لا يُستخدم على جلد ملتهب/مجروح.',
	'يُغسل اليدان بعد الاستخدام. تجنب ملامسة العينين/الفم.',
	'قد يحدث تساقط مؤقت أول ٢–٨ أسابيع (Shedding) ثم يبدأ التحسن تدريجياً.',
	'مينوكسيديل: يُتجنب في الحمل/الرضاعة (غير مُثبت الأمان).',
	'إذا حدث دوخة/خفقان/تورم باليدين أو القدمين/ضيق نفس: أوقفه واستشر طبيباً.',
	'محاليل/رغوة المينوكسيديل قابلة للاشتعال: تُترك لتجف تماماً قبل التدخين/الحرارة.',
];

export const HAIR_CARE_LGT_PART_4_GROUP: Medication[] = [
	// 152
	{
		id: 'magic-hair-oil-120ml',
		name: 'magic hair oil 120 ml',
		genericName: 'olive oil & almond oil & eruca oil',
		concentration: '120 ml',
		price: 125,
		matchKeywords: ['magic hair oil', 'olive oil', 'almond oil', 'eruca', 'زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 153
	{
		id: 'panthovera-hair-lotion-spray-110ml',
		name: 'panthovera hair lotion spray 110 ml',
		genericName: 'saw palmetto & ginkgo extract & aloe vera & panthenol',
		concentration: '110 ml',
		price: 170,
		matchKeywords: ['panthovera', 'hair lotion spray', 'saw palmetto', 'ginkgo', 'panthenol', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن/سبراي لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 154
	{
		id: 'prominexil-lotion-120ml',
		name: 'prominexil 120 ml lotion',
		genericName: 'aminexil & procapil & fiberhance bm solution & caffeine',
		concentration: '120 ml',
		price: 230,
		matchKeywords: ['prominexil', 'aminexil', 'procapil', 'caffeine', 'hair fall', 'تساقط الشعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل تساقط الشعر وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 155
	{
		id: 'active-hair-lotion-250ml',
		name: 'active hair lotion 250 ml',
		genericName: 'garlic extract-oil & aloe vera extract & thyme extract & peppermint',
		concentration: '250 ml',
		price: 125,
		matchKeywords: ['active hair lotion', 'garlic', 'aloe vera', 'thyme', 'peppermint', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس/الشعر للعناية وتقليل الجفاف وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 156
	{
		id: 'bearfast-hair-tonic-5-vials-10ml',
		name: 'bearfast hair tonic 5 vials 10 ml',
		genericName: 'argan oil & caffeine & aloe vera & panthenol & keratin & vitamins',
		concentration: '5 vials x 10 ml',
		price: 550,
		matchKeywords: ['bearfast', 'hair tonic', 'vials', 'ampoules', 'caffeine', 'keratin', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'تونك على هيئة فيالات لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 157
	{
		id: 'bye-dan-hair-shampoo-250ml',
		name: 'bye-dan hair shampoo 250 ml',
		genericName: 'st. john wort extract & sage extract & oats extract & piroctone olamine',
		concentration: '250 ml',
		price: 110,
		matchKeywords: ['bye-dan', 'anti-dandruff', 'piroctone', 'shampoo', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 158
	{
		id: 'cafa-hair-cream-50gm',
		name: 'cafa hair cream 50 gm',
		genericName: 'caffeine & olive oil & panthenol & aloe vera & vitamin a & vitamins',
		concentration: '50 gm',
		price: 110,
		matchKeywords: ['cafa hair cream', 'caffeine', 'panthenol', 'aloe vera', 'cream', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم للشعر لترطيب وتنعيم وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 159
	{
		id: 'cefix-hair-spray-120ml',
		name: 'cefix hair spray 120 ml',
		genericName: 'biotin & vitamin e & panthenol & jojoba oil & wheat germ oil',
		concentration: '120 ml',
		price: 350,
		matchKeywords: ['cefix hair spray', 'biotin', 'panthenol', 'jojoba', 'spray', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي للشعر/الفروة لدعم المظهر وتقليل الهيشان حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 160
	{
		id: 'firstvoc-frizz-control-shampoo-conditioner',
		name: 'firstvoc frizz control shampoo & conditioner ...',
		genericName: 'dow corning & vital hair & scalp complex & vitamin h & argan',
		concentration: 'N/A',
		price: 185,
		matchKeywords: ['firstvoc frizz control', 'shampoo', 'conditioner', 'argan', 'frizz', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو + بلسم (٢ في ١) لتقليل الهيشان والتحكم في التجعد.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 161
	{
		id: 'charmalure-hair-oil-200ml',
		name: 'charmalure hair oil 200 ml',
		genericName: 'vitamin e & rosemary & coconut oil & olive oil & tea tree',
		concentration: '200 ml',
		price: 175,
		matchKeywords: ['charmalure hair oil', 'rosemary', 'coconut', 'olive oil', 'tea tree', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 162
	{
		id: 'charmalure-hair-shampoo-250ml',
		name: 'charmalure hair shampoo 250 ml',
		genericName: 'caffeine & emla oil & tea tree oil & sesame oil & dimethicone',
		concentration: '250 ml',
		price: 150,
		matchKeywords: ['charmalure shampoo', 'caffeine', 'tea tree', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 163
	{
		id: 'cuti-care-anti-dandruff-shampoo-150ml',
		name: 'cuti-care anti-dandruff shampoo 150 ml',
		genericName: 'zinc pyrithione & climbazole & selenium sulphide & tea tree',
		concentration: '150 ml',
		price: 125,
		matchKeywords: ['cuti-care', 'anti-dandruff', 'climbazole', 'selenium sulphide', 'tea tree', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو علاجي للقشرة/التهاب الجلد الدهني وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 164
	{
		id: 'dago-hair-shampoo-200ml-hc4',
		name: 'dago hair shampoo 200ml',
		genericName: 'zinc pyrithione & caffeine & aloe vera & tea tree oil & panthenol',
		concentration: '200 ml',
		price: 200,
		matchKeywords: ['dago shampoo', '200ml', 'zinc pyrithione', 'caffeine', 'tea tree', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بفروة الرأس وقد يساعد في القشرة الخفيفة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 165
	{
		id: 'fast-care-p-hair-shampoo-250ml',
		name: 'fast care p. hair shampoo 250ml',
		genericName: 'olive oil & vitamin e & vitamin a & chamomile extract & jojoba',
		concentration: '250 ml',
		price: 175,
		matchKeywords: ['fast care p', 'hair shampoo', 'chamomile', 'jojoba', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس وترطيب الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 166
	{
		id: 'final-2-hair-lotion-120ml',
		name: 'final 2 hair lotion 120ml',
		genericName: 'aloe vera extract & resorcinol & vitamin c & vitamin e & panthenol',
		concentration: '120 ml',
		price: 95,
		matchKeywords: ['final 2 lotion', 'aloe vera', 'resorcinol', 'panthenol', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس للعناية وتقليل القشرة/الحكة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 167
	{
		id: 'final-2-hair-shampoo-180ml',
		name: 'final 2 hair shampoo 180ml',
		genericName: 'abriol & aloe vera extract & olive oil & resorcinol',
		concentration: '180 ml',
		price: 60,
		matchKeywords: ['final 2 shampoo', '180ml', 'resorcinol', 'aloe vera', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بفروة الرأس وتقليل القشرة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 168
	{
		id: 'firstvoc-hair-lotion-120ml',
		name: 'firstvoc hair lotion 120 ml',
		genericName: 'argan oil & biotin & caviar & caffeine & keratin & saw palmetto',
		concentration: '120 ml',
		price: 150,
		matchKeywords: ['firstvoc hair lotion', 'argan', 'biotin', 'caviar', 'caffeine', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 169
	{
		id: 'folligant-hair-lotion-spray-250ml',
		name: 'folligant hair lotion spray 250 ml',
		genericName: 'saw palmetto & caffeine & rosemary & ginkgo & nettle',
		concentration: '250 ml',
		price: 218,
		matchKeywords: ['folligant', 'hair lotion spray', 'saw palmetto', 'caffeine', 'rosemary', 'ginkgo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن/سبراي لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 170
	{
		id: 'folligant-hair-shampoo-250ml',
		name: 'folligant hair shampoo 250 ml',
		genericName: 'saw palmetto & caffeine & rosemary & ginkgo & nettle',
		concentration: '250 ml',
		price: 190,
		matchKeywords: ['folligant shampoo', 'saw palmetto', 'caffeine', 'rosemary', 'ginkgo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس ودعم مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 171
	{
		id: 'follitone-hair-bath-oil-150ml',
		name: 'follitone hair bath oil 150 ml',
		genericName: 'rosemary extract & jojoba oil & thyme extract & olive oil',
		concentration: '150 ml',
		price: 64.75,
		matchKeywords: ['follitone bath oil', 'rosemary', 'jojoba', 'thyme', 'olive oil', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت حمام/بديل زيت للشعر لترطيب وتنعيم وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 172
	{
		id: 'friston-hair-lotion-120ml',
		name: 'friston hair lotion 120 ml',
		genericName: 'biotin & saw palmetto & aloe vera & jojoba & wheat germ',
		concentration: '120 ml',
		price: 330,
		matchKeywords: ['friston', 'hair lotion', 'biotin', 'saw palmetto', 'jojoba', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 173
	{
		id: 'girly-hair-cream-100gm',
		name: 'girly hair cream 100 gm',
		genericName: 'lavender oil & thyme extract & garlic extract & rosemary oil',
		concentration: '100 gm',
		price: 145,
		matchKeywords: ['girly hair cream', 'lavender', 'thyme', 'garlic', 'rosemary', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 174
	{
		id: 'girly-hair-shampoo-180ml',
		name: 'girly hair shampoo 180 ml',
		genericName: 'lavender oil & thyme extract & garlic extract & rosemary oil',
		concentration: '180 ml',
		price: 55,
		matchKeywords: ['girly shampoo', '180ml', 'lavender', 'thyme', 'garlic', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 175
	{
		id: 'girly-hair-shampoo-250ml',
		name: 'girly hair shampoo 250 ml',
		genericName: 'garlic oil & aloe vera extract',
		concentration: '250 ml',
		price: 170,
		matchKeywords: ['girly shampoo', '250ml', 'garlic', 'aloe vera', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 176
	{
		id: 'hydrolav-shampoo-250ml',
		name: 'hydrolav shampoo 250 ml',
		genericName: 'keratin & silicon & pumpkin oil & almond oil & tea tree oil & vitamins',
		concentration: '250 ml',
		price: 140,
		matchKeywords: ['hydrolav', 'keratin', 'pumpkin oil', 'almond', 'tea tree', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر (كيراتين + زيوت).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 177
	{
		id: 'integrado-hair-loss-lotion-150ml',
		name: 'integrado hair loss lotion 150 ml',
		genericName: 'trichogen complex & sophora angustifolia extract & vital hair complex',
		concentration: '150 ml',
		price: 420,
		matchKeywords: ['integrado', 'hair loss lotion', 'trichogen', 'sophora', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين كثافة الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 178
	{
		id: 'logipact-hair-mask-150gm',
		name: 'logipact hair mask 150 gm',
		genericName: 'argan oil & shea butter & grape seed oil & aloe vera',
		concentration: '150 gm',
		price: 220,
		matchKeywords: ['logipact hair mask', 'argan', 'shea', 'grape seed', 'mask', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك لترطيب عميق وتقليل الهيشان والتشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 179
	{
		id: 'magic-hair-cream-100gm',
		name: 'magic hair cream 100 gm',
		genericName: 'olive oil & almond oil & eruca oil & rose oil',
		concentration: '100 gm',
		price: 130,
		matchKeywords: ['magic hair cream', 'olive oil', 'almond', 'eruca', 'rose oil', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 180
	{
		id: 'new-tonoscalpine-scalp-lotion-190ml',
		name: 'new tonoscalpine scalp lotion 190 ml',
		genericName: 'pilocarpine nitrate & quinine hydrochloride & salicylic acid',
		concentration: '190 ml',
		price: 22,
		matchKeywords: ['tonoscalpine', 'scalp lotion', 'pilocarpine', 'quinine', 'salicylic acid', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس للعناية وتقليل القشور/الدهون حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 181
	{
		id: 'no-hair-cream-75ml',
		name: 'no hair cream 75 ml',
		genericName: 'ceteareth-23 & glyceryl monostearate & decyl oleate',
		concentration: '75 ml',
		price: 50,
		matchKeywords: ['no hair cream', 'depilatory', 'hair inhibitor', 'كريم', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم موضعي (قد يُستخدم لتقليل نمو الشعر غير المرغوب/بعد إزالة الشعر حسب العبوة).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [
			'اختبار حساسية على مساحة صغيرة قبل الاستخدام الأول.',
			'لا يُستخدم على الجلد المتهيج/المجروح أو بعد الحلاقة مباشرة إذا سبب تهيجاً.',
			...COMMON_HAIR_CARE_WARNINGS,
		],
	},

	// 182
	{
		id: 'pantex-hair-shampoo-120ml',
		name: 'pantex hair shampoo 120 ml',
		genericName: 'salicylic acid & octopirox',
		concentration: '120 ml',
		price: 60,
		matchKeywords: ['pantex shampoo', 'salicylic acid', 'octopirox', 'anti-dandruff', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتقليل القشور/الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 183
	{
		id: 'panthenol-2pct-hair-lotion-190ml',
		name: 'panthenol 2% hair lotion 190 ml',
		genericName: 'panthenol',
		concentration: '2% (190 ml)',
		price: 50,
		matchKeywords: ['panthenol 2%', 'hair lotion', 'vitamin b5', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن للشعر/الفروة لترطيب وتقليل الجفاف وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 184
	{
		id: 'pross-hair-lotion-120ml',
		name: 'pross hair lotion 120 ml',
		genericName: 'saw palmetto & caffeine & ginkgo & ginseng & royal jelly',
		concentration: '120 ml',
		price: 175,
		matchKeywords: ['pross hair lotion', '120ml', 'saw palmetto', 'caffeine', 'ginseng', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 185
	{
		id: 'pross-hair-oil-120ml',
		name: 'pross hair oil 120 ml',
		genericName: 'grape seed oil & rosemary oil & jojoba oil & thyme oil & lavender',
		concentration: '120 ml',
		price: 175,
		matchKeywords: ['pross hair oil', '120ml', 'grape seed', 'rosemary', 'jojoba', 'thyme', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 186
	{
		id: 'pross-hair-serum-120ml',
		name: 'pross hair serum 120 ml',
		genericName: 'dimethicone & oils blend & silicone blend',
		concentration: '120 ml',
		price: 240,
		matchKeywords: ['pross hair serum', '120ml', 'dimethicone', 'serum', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 187
	{
		id: 'seltop-hair-shampoo-250ml',
		name: 'seltop hair shampoo 250 ml',
		genericName: 'olive oil & tea tree oil & panthenol',
		concentration: '250 ml',
		price: 175,
		matchKeywords: ['seltop', 'tea tree', 'panthenol', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 188
	{
		id: 'silkren-hair-cream-gel-120ml',
		name: 'silkren hair cream gel 120 ml',
		genericName: 'zinc pyrithione & coconut oil & salicylic acid & sulphur',
		concentration: '120 ml',
		price: 85,
		matchKeywords: ['silkren', 'cream gel', 'zinc pyrithione', 'salicylic acid', 'sulphur', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'جل/كريم لفروة الرأس للمساعدة في القشرة والحكة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Gel',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 189
	{
		id: 'tola-hair-oil-replacement-100ml',
		name: 'tola hair oil replacement 100 ml',
		genericName: 'avocado oil & coconut oil & jojoba oil & aloe vera oil',
		concentration: '100 ml',
		price: 219,
		matchKeywords: ['tola oil replacement', 'avocado', 'coconut', 'jojoba', 'aloe vera', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'بديل زيت/لوشن للشعر لترطيب وتنعيم وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 190
	{
		id: 'trix-anti-dandruff-hair-shampoo-200ml',
		name: 'trix anti-dandruff hair shampoo 200 ml',
		genericName: 'amino acids & aminexil & biotin & caffeine & argan oil',
		concentration: '200 ml',
		price: 238,
		matchKeywords: ['trix', 'anti-dandruff', 'aminexil', 'biotin', 'caffeine', 'argan', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 191
	{
		id: 'trook-line-hair-serum-120ml',
		name: 'trook line hair serum 120 ml',
		genericName: 'keratin & protein & collagen & caviar',
		concentration: '120 ml',
		price: 160,
		matchKeywords: ['trook line', 'hair serum', 'keratin', 'collagen', 'caviar', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 192
	{
		id: 'valido-hair-serum-75ml',
		name: 'valido hair serum 75 ml',
		genericName: 'cyclopentasiloxane & amino silicone & vitamin e & paraffin',
		concentration: '75 ml',
		price: 73,
		matchKeywords: ['valido', 'hair serum', 'cyclopentasiloxane', 'vitamin e', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 193
	{
		id: 'akema-hair-oil-120ml',
		name: 'akema hair oil 120 ml',
		genericName: 'lavender oil & basil oil & jojoba oil & olive oil & geranium oil',
		concentration: '120 ml',
		price: 120,
		matchKeywords: ['akema hair oil', 'lavender', 'basil', 'jojoba', 'olive oil', 'geranium', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 194
	{
		id: 'anaforten-hair-lotion-spray-120ml',
		name: 'anaforten hair lotion spray 120 ml',
		genericName: 'saw palmetto & vitamins b6 & vitamins b12 & omega 3',
		concentration: '120 ml',
		price: 240,
		matchKeywords: ['anaforten spray', 'saw palmetto', 'omega 3', 'vitamin b6', 'vitamin b12', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن/سبراي لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 195
	{
		id: 'capixy-hair-volumizing-spray-125ml',
		name: 'capixy hair volumizing spray 125 ml',
		genericName: 'capixyl & glycerin & aloe vera & shea butter & caffeine',
		concentration: '125 ml',
		price: 550,
		matchKeywords: ['capixy', 'capixyl', 'volumizing spray', 'caffeine', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي لفروة الرأس/الشعر لدعم مظهر الكثافة وتحسين المظهر العام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 196
	{
		id: 'cortex-shampoo-120ml',
		name: 'cortex shampoo 120 ml',
		genericName: 'selenium sulfide & zinc pyrithione & clotrimazole',
		concentration: '120 ml',
		price: 105,
		matchKeywords: ['cortex shampoo', 'selenium sulfide', 'zinc pyrithione', 'clotrimazole', 'anti-dandruff', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو علاجي للقشرة/التهاب الجلد الدهني وقد يفيد في الفطريات السطحية بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 197
	{
		id: 'firstvoc-hair-5-amps-10ml',
		name: 'firstvoc hair 5 amps. x 10 ml',
		genericName: 'argan oil & biotin & caviar & caffeine & keratin & saw palmetto',
		concentration: '5 amps x 10 ml',
		price: 349,
		matchKeywords: ['firstvoc hair ampoules', 'amps', 'biotin', 'caffeine', 'keratin', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'أمبولات لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 198
	{
		id: 'lc-naturals-hair-tonic-spray',
		name: 'lc naturals hair tonic spray',
		genericName: 'panax ginseng & ginkgo biloba & l-arginine & phytosterols',
		concentration: 'N/A',
		price: 450,
		matchKeywords: ['lc naturals', 'hair tonic spray', 'ginseng', 'ginkgo', 'arginine', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'تونك سبراي لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 199
	{
		id: 'rivadon-hair-serum-120ml',
		name: 'rivadon hair serum 120 ml',
		genericName: 'silicone oil & emu oil & argan oil & caviar extract',
		concentration: '120 ml',
		price: 290,
		matchKeywords: ['rivadon', 'hair serum', 'emu oil', 'argan', 'caviar', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 200
	{
		id: 'siera-intensive-hair-growth-serum',
		name: 'siera intensive hair growth serum',
		genericName: 'biotin & caffeine & beta-sitosterol & argan oil & jojoba',
		concentration: 'N/A',
		price: 250,
		matchKeywords: ['siera intensive', 'hair growth serum', 'biotin', 'caffeine', 'beta-sitosterol', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لفروة الرأس/الشعر لدعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 201
	{
		id: 'siera-intensive-hair-growth-serum-6',
		name: 'siera intensive hair growth serum 6',
		genericName: 'biotin & caffeine & beta-sitosterol & argan oil & jojoba',
		concentration: 'N/A',
		price: 420,
		matchKeywords: ['siera intensive', 'hair growth serum 6', 'biotin', 'caffeine', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لفروة الرأس/الشعر لدعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 202
	{
		id: 'treato-serum-80ml',
		name: 'treato serum 80 ml',
		genericName: 'procapil & stem cells & hydrolyzed glycosaminoglycan',
		concentration: '80 ml',
		price: 155,
		matchKeywords: ['treato serum', 'procapil', 'stem cells', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لفروة الرأس لدعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 203
	{
		id: 'weedobon-hair-serum-100ml',
		name: 'weedobon hair serum 100 ml',
		genericName: 'almond oil & argan oil & dimethiconol & vitamin e',
		concentration: '100 ml',
		price: 150,
		matchKeywords: ['weedobon hair serum', 'almond oil', 'argan', 'dimethiconol', 'vitamin e', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 204
	{
		id: 'logipact-hair-mask-250gm',
		name: 'logipact hair mask 250 gm',
		genericName: 'argan oil & shea butter & grape seed oil & aloe vera',
		concentration: '250 gm',
		price: 230,
		matchKeywords: ['logipact hair mask', '250gm', 'argan', 'shea', 'grape seed', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك لترطيب عميق وتقليل الهيشان والتشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 205
	{
		id: 'keraveda-hair-shampoo-250ml',
		name: 'keraveda hair shampoo 250 ml',
		genericName: 'jojoba oil & olive oil & keratin & aloe vera extract & argan oil',
		concentration: '250 ml',
		price: 225,
		matchKeywords: ['keraveda', 'keratin', 'jojoba', 'argan', 'shampoo', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس والعناية بالشعر (كيراتين + زيوت).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 206
	{
		id: 'scaling-vit-hair-serum-120ml',
		name: 'scaling vit hair serum 120 ml',
		genericName: 'argan oil & aloe vera extract & emu oil & saw palmetto & keratin',
		concentration: '120 ml',
		price: 300,
		matchKeywords: ['scaling vit', 'hair serum', 'emu oil', 'argan', 'keratin', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لفروة الرأس/الشعر لدعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 207
	{
		id: 'alejon-hair-15-vials-3ml',
		name: 'alejon hair 15 vials x 3 ml',
		genericName: 'aminixil 2% & trichogen & liposomal caffeine',
		concentration: '15 vials x 3 ml',
		price: 450,
		matchKeywords: ['alejon vials', 'aminixil', 'trichogen', 'caffeine', 'vials', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'فيالات لفروة الرأس لدعم تقليل التساقط وتحسين كثافة الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 208
	{
		id: 'daryan-coal-hair-shampoo-200ml',
		name: 'daryan coal hair shampoo 200 ml',
		genericName: 'selenium sulfide & zinc pyrithione & chamomile & coal tar',
		concentration: '200 ml',
		price: 140,
		matchKeywords: ['daryan coal', 'coal tar', 'selenium sulfide', 'zinc pyrithione', 'anti-dandruff', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة الشديدة/التهاب الجلد الدهني وقد يفيد في الصدفية بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 209
	{
		id: 'logipact-hair-repair-serum-50ml',
		name: 'logipact hair repair serum 50 ml',
		genericName: 'argan & jojoba oil & vitamin e & panthenol',
		concentration: '50 ml',
		price: 255,
		matchKeywords: ['logipact repair serum', 'argan', 'jojoba', 'vitamin e', 'panthenol', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لإصلاح/تغذية الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 210
	{
		id: 'minoxidil-mup-5pct-foam-150ml',
		name: 'minoxidil-mup 5% foam 150 ml',
		genericName: 'minoxidil',
		concentration: '5% (150 ml)',
		price: 181,
		matchKeywords: ['minoxidil-mup', 'minoxidil 5%', 'foam', 'hair regrowth', '#hair_regrowth', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'مينوكسيديل ٥٪ رغوة لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Foam',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 211
	{
		id: 'relat-hair-lotion-120ml',
		name: 'relat hair lotion 120 ml',
		genericName: 'caffeine & vital hair & scalp complex & ginseng extract',
		concentration: '120 ml',
		price: 250,
		matchKeywords: ['relat hair lotion', 'caffeine', 'ginseng', 'hair scalp complex', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 212
	{
		id: 'relat-hair-oil-120ml',
		name: 'relat hair oil 120 ml',
		genericName: 'cyclopentasiloxane & dimethiconol & silicon oil',
		concentration: '120 ml',
		price: 210,
		matchKeywords: ['relat hair oil', 'cyclopentasiloxane', 'dimethiconol', 'oil', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 213
	{
		id: 'revitacare-hair-cream-100gm',
		name: 'revitacare hair cream 100 gm',
		genericName: 'caffeine & olive oil & biotin',
		concentration: '100 gm',
		price: 220,
		matchKeywords: ['revitacare hair cream', 'caffeine', 'biotin', 'cream', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 214
	{
		id: 'rostevo-hair-serum-150ml',
		name: 'rostevo hair serum 150ml',
		genericName: 'keratin & coconut oil & vitamin e & aloe vera oil & almond oil',
		concentration: '150 ml',
		price: 150,
		matchKeywords: ['rostevo hair serum', '150ml', 'keratin', 'coconut oil', 'vitamin e', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 215
	{
		id: 'seropipe-hair-dropper-10ml-7-vials',
		name: 'seropipe hair dropper 10 ml x 7 vials',
		genericName: 'kamigen e & kamigen k & biotin & keratin & argan oil',
		concentration: '10 ml x 7 vials',
		price: 455,
		matchKeywords: ['seropipe dropper', 'vials', 'biotin', 'keratin', 'argan', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'فيالات/دروبر لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Vial',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 216
	{
		id: 'solodex-roots-elixir-60ml',
		name: 'solodex roots elixir 60 ml',
		genericName: 'kopexil & liposomal caffeine & quaternized panthenol',
		concentration: '60 ml',
		price: 450,
		matchKeywords: ['solodex roots elixir', 'kopexil', 'caffeine', 'panthenol', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'إليكسير/سيروم للجذور لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 217
	{
		id: 'solodex-roots-lotion-accelerator-60ml',
		name: 'solodex roots lotion (accelerator) 60 ml',
		genericName: 'amino acids & pisum sativum peptide & vitamins & beta-sitosterol',
		concentration: '60 ml',
		price: 360,
		matchKeywords: ['solodex roots accelerator', 'pisum sativum peptide', 'beta-sitosterol', 'lotion', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن للجذور لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},
];

