import { Category, Medication } from '../../../types';

const fixed = (t: string) => () => t;

const COMMON_HAIR_CARE_WARNINGS = [
	'تجنب ملامسة العينين. عند حدوث تلامس تُشطف العين جيداً بالماء.',
	'أوقف الاستخدام إذا حدث تهيّج شديد/حكة شديدة/حساسية.',
];

const ANTI_DANDRUFF_SHAMPOO_WARNINGS = [
	...COMMON_HAIR_CARE_WARNINGS,
	'للقشرة/التهاب فروة الرأس: إذا لم تتحسن الحالة خلال ٢–٤ أسابيع يُفضّل تقييم طبي.',
];

const MINOXIDIL_WARNINGS = [
	'للاستخدام الخارجي على فروة الرأس فقط. لا يُستخدم على جلد ملتهب/مجروح.',
	'يُغسل اليدان بعد الاستخدام. تجنب ملامسة العينين/الفم.',
	'قد يحدث تساقط مؤقت أول ٢–٨ أسابيع (Shedding) ثم يبدأ التحسن تدريجياً.',
	'مينوكسيديل: يُتجنب في الحمل/الرضاعة (غير مُثبت الأمان).',
	'إذا حدث دوخة/خفقان/تورم باليدين أو القدمين/ضيق نفس: أوقفه واستشر طبيباً.',
	'محاليل/رغوة المينوكسيديل قابلة للاشتعال: تُترك لتجف تماماً قبل التدخين/الحرارة.',
];

const ORAL_HAIR_SUPPLEMENT_WARNINGS = [
	'مكمل غذائي: لا يغني عن الغذاء المتوازن.',
	'الحمل/الرضاعة: يُستشار الطبيب قبل الاستخدام.',
	'راجع التفاعلات مع الأدوية الجهازية (مميعات، سكري، ضغط، إلخ)؛ تجنب الجمع دون تقييم.',
];

export const HAIR_CARE_LGT_PART_2_GROUP: Medication[] = [
	// 33
	{
		id: 'seropipe-hair-serum-100ml',
		name: 'seropipe hair serum 100 ml',
		genericName: 'kamigen e & kamigen k & hydrolyzed lupin protein & hordeum vulgare',
		concentration: '100 ml',
		price: 255,
		matchKeywords: ['seropipe serum', 'seropipe', 'hair serum', 'kamigen', 'lupin', 'hordeum vulgare', 'سيروبايب', 'سيروم شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم للشعر لتقليل الهيشان والتقصف وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 34
	{
		id: 'seropipe-hair-spray-200ml',
		name: 'seropipe hair spray 200 ml',
		genericName: 'kamigen e & kamigen k & hydrolyzed lupin protein & hordeum vulgare',
		concentration: '200 ml',
		price: 265,
		matchKeywords: ['seropipe spray', 'hair spray', 'kamigen', 'سبراي شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي للشعر/الفروة لدعم المظهر وتقليل الهيشان حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 35
	{
		id: 'hepta-panthenol-kids-hair-cream-100gm',
		name: 'hepta panthenol kids hair cream 100 gm',
		genericName: 'panthenol & vitamin e & jojoba oil & argan oil & shea butter',
		concentration: '100 gm',
		price: 149,
		matchKeywords: ['hepta panthenol kids', 'panthenol', 'kids hair cream', 'كريم شعر اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم شعر للأطفال لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 36
	{
		id: 'alejon-hair-lotion-150ml',
		name: 'alejon hair lotion 150 ml',
		genericName: 'aminexil & liposomal caffeine & ginkgo biloba & amla oil',
		concentration: '150 ml',
		price: 350,
		matchKeywords: ['alejon lotion', 'aminexil', 'caffeine', 'ginkgo', 'hair lotion', 'لوشن شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين كثافة الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 37
	{
		id: 'clary-leave-in-cream-300gm',
		name: 'clary leave in cream 300 gm',
		genericName: 'procapil & argan oil & vitamins',
		concentration: '300 gm',
		price: 300,
		matchKeywords: ['clary', 'leave in', 'procapil', 'كريم ليف ان', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم ليف-إن لترطيب الشعر وتقليل الهيشان ودعم مظهره.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 38
	{
		id: 'dandivera-hair-shampoo-180ml',
		name: 'dandivera hair shampoo 180ml',
		genericName: 'zinc pyrithione & aloe vera & resorcinol',
		concentration: '180 ml',
		price: 100,
		matchKeywords: ['dandivera', 'zinc pyrithione', 'resorcinol', 'anti-dandruff', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة والتهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 39
	{
		id: 'hairtonic-60-caps',
		name: 'hairtonic 60 caps.',
		genericName: 'biotin & calcium pantothenate & cysteine & keratin',
		concentration: '60 caps',
		price: 190,
		matchKeywords: ['hairtonic', 'biotin', 'cysteine', 'keratin', 'hair fall', 'تساقط الشعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'مكمل لدعم الشعر وتقليل التساقط المرتبط بنقص العناصر.',
		timing: 'مرة يومياً مع الأكل – ٣ شهور',
		category: Category.HAIR_CARE,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة ٣ شهور'),
		warnings: [...ORAL_HAIR_SUPPLEMENT_WARNINGS],
	},

	// 40
	{
		id: 'alejon-bi-phase-hair-spray-200ml',
		name: 'alejon bi phase hair spray 200 ml',
		genericName: 'argan oil & grape seed oil & hydrolyzed keratin',
		concentration: '200 ml',
		price: 275,
		matchKeywords: ['alejon bi phase', 'hair spray', 'keratin', 'argan', 'سبراي ثنائي', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي ثنائي المرحلة لترطيب الشعر وفك التشابك وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 41
	{
		id: 'minoxidil-forte-5pct-topical-gel-60gm',
		name: 'minoxidil forte 5% topical gel 60 gm',
		genericName: 'minoxidil',
		concentration: '5% (60 gm)',
		price: 127,
		matchKeywords: ['minoxidil forte', 'minoxidil 5%', 'gel', 'hair regrowth', 'صلع', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ جل لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Gel',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 42
	{
		id: 'alejon-anti-dandruff-shampoo-200ml',
		name: 'alejon anti-dandruff shampoo 200 ml',
		genericName: 'selenium sulphide & salicylic acid & zinc pyrithione',
		concentration: '200 ml',
		price: 175,
		matchKeywords: ['alejon anti-dandruff', 'selenium sulphide', 'salicylic', 'zinc pyrithione', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة/التهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 43
	{
		id: 'pantogar-90-caps',
		name: 'pantogar 90 caps',
		genericName: 'calcium-d-pantothenate & l-cystine & keratin',
		concentration: '90 caps',
		price: 364.5,
		matchKeywords: ['pantogar', 'hair fall', 'cystine', 'keratin', 'بانتوجار', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'مكمل لدعم الشعر وتقليل التساقط (خاصة مع هشاشة/تكسر الشعر).',
		timing: 'مرة يومياً مع الأكل – ٣ شهور',
		category: Category.HAIR_CARE,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة ٣ شهور'),
		warnings: [...ORAL_HAIR_SUPPLEMENT_WARNINGS],
	},

	// 44
	{
		id: 'narji-hair-tonic-lotion-120ml',
		name: 'narji hair tonic lotion 120 ml',
		genericName: 'keratin & panthenol & lactic acid & tea tree oil & caffeine',
		concentration: '120 ml',
		price: 247,
		matchKeywords: ['narji', 'hair tonic', 'tonic lotion', 'caffeine', 'لوشن تونك', '#hair_care', '#hair_fall'],
		usage: 'تونك لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 45
	{
		id: 'tress-hair-oil-250ml',
		name: 'tress hair oil 250 ml',
		genericName: 'cyclopentasiloxane & matricaria flower extract',
		concentration: '250 ml',
		price: 190,
		matchKeywords: ['tress hair oil', 'cyclopentasiloxane', 'زيت تريس', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/سيروم زيتي لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 46
	{
		id: 'seropipe-hair-leave-in-conditioner-200ml',
		name: 'seropipe hair leave-in conditioner 200 ml',
		genericName: 'kamigen e & kamigen k & hydrolyzed lupin protein & hordeum vulgare',
		concentration: '200 ml',
		price: 250,
		matchKeywords: ['seropipe leave-in', 'leave in conditioner', 'بلسم بدون شطف', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'بلسم بدون شطف لترطيب الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 47
	{
		id: 'vividol-hair-oil-250ml',
		name: 'vividol hair oil 250 ml',
		genericName: 'vegetable oils blend',
		concentration: '250 ml',
		price: 180,
		matchKeywords: ['vividol hair oil', 'زيت فيفيدول', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتقليل الجفاف وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 49
	{
		id: 'alejon-hair-mask-200ml',
		name: 'alejon hair mask 200 ml',
		genericName: 'caffeine & oils blend',
		concentration: '200 ml',
		price: 275,
		matchKeywords: ['alejon mask', 'hair mask', 'ماسك شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك لترطيب عميق وتقليل الهيشان والتشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 50
	{
		id: 'alejon-hair-serum-50ml',
		name: 'alejon hair serum 50 ml',
		genericName: 'keratin & ginseng & oils blend',
		concentration: '50 ml',
		price: 295,
		matchKeywords: ['alejon serum', 'hair serum', 'سيروم', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 51
	{
		id: 'alejon-hair-shampoo-200ml',
		name: 'alejon hair shampoo 200 ml',
		genericName: 'keratin & collagen & caffeine & panthenol',
		concentration: '200 ml',
		price: 180,
		matchKeywords: ['alejon shampoo', 'keratin', 'caffeine', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر وتنظيف الفروة وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 52
	{
		id: 'aloekita-ds-hair-shampoo-250ml',
		name: 'aloekita ds hair shampoo 250 ml',
		genericName: 'caffeine & saw palmetto & amla & aloe vera & tea tree oil',
		concentration: '250 ml',
		price: 229,
		matchKeywords: ['aloekita ds', 'ds shampoo', 'dandruff', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بفروة الرأس الدهنية والقشرة (DS).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 53
	{
		id: 'black-again-n-hair-cream-150ml',
		name: 'black again-n hair cream 150 ml',
		genericName: 'cetearyl alcohol & glycerin & cetrimonium chloride',
		concentration: '150 ml',
		price: 300,
		matchKeywords: ['black again-n', 'hair cream', 'cetrimonium chloride', 'كريم شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم ترطيب وتنعيم للشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 54
	{
		id: 'gone-anti-dandruff-shampoo-250ml',
		name: 'gone anti-dandruff shampoo 250 ml',
		genericName: 'caffeine & zinc pyrithione & piroctone olamine',
		concentration: '250 ml',
		price: 150,
		matchKeywords: ['gone shampoo', 'anti-dandruff', 'zinc pyrithione', 'piroctone', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو مضاد للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 55
	{
		id: 'jolary-hair-shampoo-250ml',
		name: 'jolary hair shampoo 250ml',
		genericName: 'jojoba oil & amla oil & piroctone olamine',
		concentration: '250 ml',
		price: 165,
		matchKeywords: ['jolary', 'piroctone olamine', 'شامبو', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر وتقليل القشرة حسب الاستخدام.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 56
	{
		id: 'keraqouz-shampoo-conditioner-250ml',
		name: 'keraqouz shampoo & conditioner 250 ml',
		genericName: 'keratin & hydrolyzed wheat protein & silicon & tocopherol',
		concentration: '250 ml',
		price: 160,
		matchKeywords: ['keraqouz', 'shampoo conditioner', 'keratin', '2 in 1', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو + بلسم (٢ في ١) لتنظيف الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 57
	{
		id: 'lindo-hair-oil-spray-120ml',
		name: 'lindo hair oil spray 120 ml',
		genericName: 'siloxane & emu oil & wheat germ oil & jojoba oil',
		concentration: '120 ml',
		price: 160,
		matchKeywords: ['lindo oil spray', 'hair oil spray', 'سبراي زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي زيت للشعر لتنعيم وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 58
	{
		id: 'lindo-hair-oil-spray-250ml',
		name: 'lindo hair oil spray 250 ml',
		genericName: 'siloxane & emu oil & wheat germ oil & jojoba oil',
		concentration: '250 ml',
		price: 190,
		matchKeywords: ['lindo oil spray', '250ml', 'سبراي زيت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سبراي زيت للشعر لتنعيم وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 59
	{
		id: 'penduline-plus-children-hair-oil-120ml',
		name: 'penduline plus children hair oil 120 ml',
		genericName: 'argan oil & jojoba oil & almond oil & olive oil & coconut oil',
		concentration: '120 ml',
		price: 220,
		matchKeywords: ['penduline plus', 'children hair oil', 'زيت شعر اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/لوشن شعر للأطفال لتغذية وترطيب الشعر وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 60
	{
		id: 'polytar-hair-shampoo-150ml',
		name: 'polytar hair shampoo 150 ml',
		genericName: 'coal tar & cade oil',
		concentration: '150 ml',
		price: 130,
		matchKeywords: ['polytar', 'coal tar', 'tar shampoo', 'شامبو قطران', 'psoriasis', 'صدفية', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو قطران لعلاج القشرة الشديدة/التهاب الجلد الدهني وقد يفيد في الصدفية بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 61
	{
		id: 'quick-roots-hair-lotion-60ml',
		name: 'quick roots hair lotion 60 ml',
		genericName: 'caffeine & aloe vera & wheat germ & jojoba & rosemary',
		concentration: '60 ml',
		price: 350,
		matchKeywords: ['quick roots', 'hair lotion', 'caffeine', 'rosemary', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 62
	{
		id: 'regaine-5pct-topical-foam-73ml',
		name: 'regaine 5 % topical foam 73 ml',
		genericName: 'minoxidil',
		concentration: '5% (73 ml)',
		price: 610,
		matchKeywords: ['regaine', 'rogaine', 'minoxidil 5%', 'foam', '#hair_regrowth'],
		usage: 'مينوكسيديل ٥٪ رغوة لفروة الرأس لتحفيز إنبات الشعر في الصلع الوراثي.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Foam',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 63
	{
		id: 'seropipe-hair-mask-300ml',
		name: 'seropipe hair mask 300 ml',
		genericName: 'kamigen e & kamigen k & biotin & keratin & argan oil',
		concentration: '300 ml',
		price: 285,
		matchKeywords: ['seropipe mask', 'hair mask', 'biotin', 'keratin', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك لترطيب عميق وتقليل الهيشان ودعم مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 64
	{
		id: 'seropipe-hair-shampoo-300ml',
		name: 'seropipe hair shampoo 300 ml',
		genericName: 'kamigen e & kamigen k & biotin & keratin & argan oil',
		concentration: '300 ml',
		price: 210,
		matchKeywords: ['seropipe shampoo', 'biotin', 'keratin', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو لتنظيف فروة الرأس وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 65
	{
		id: 'supolack-hair-shampoo-200ml',
		name: 'supolack hair shampoo 200 ml',
		genericName: 'zinc pyrithione',
		concentration: '200 ml',
		price: 150,
		matchKeywords: ['supolack', 'zinc pyrithione', 'anti-dandruff', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 66
	{
		id: 'mi-kids-shampoo-90ml',
		name: 'mi kids shampoo 90 ml',
		genericName: 'biotin & coconut oil & almond oil & panthenol & aloe vera',
		concentration: '90 ml',
		price: 100,
		matchKeywords: ['mi kids shampoo', 'kids shampoo', 'شامبو اطفال', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو أطفال لطيف لتنظيف الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 67
	{
		id: 'vividol-hair-cream-100gm',
		name: 'vividol hair cream 100 gm',
		genericName: 'dimethicone & panthenol & tea tree oil',
		concentration: '100 gm',
		price: 170,
		matchKeywords: ['vividol hair cream', 'dimethicone', 'panthenol', 'كريم فيفيدول', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم لترطيب وتنعيم الشعر وتقليل الهيشان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 68
	{
		id: 'capixy-hair-cream-120ml',
		name: 'capixy hair cream 120 ml',
		genericName: 'capixyl & shea butter & caffeine',
		concentration: '120 ml',
		price: 275,
		matchKeywords: ['capixy cream', 'capixyl', 'caffeine', 'كريم كابيكسى', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'كريم للعناية بالشعر ودعم تقليل التساقط وتحسين المظهر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 69
	{
		id: 'capixy-hair-shampoo-250ml',
		name: 'capixy hair shampoo 250 ml',
		genericName: 'capixyl & caffeine',
		concentration: '250 ml',
		price: 275,
		matchKeywords: ['capixy shampoo', 'capixyl', 'caffeine', 'شامبو كابيكسى', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهر الكثافة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 70
	{
		id: 'capixy-hair-tonic-spray-250ml',
		name: 'capixy hair tonic spray 250 ml',
		genericName: 'capixyl & caffeine',
		concentration: '250 ml',
		price: 375,
		matchKeywords: ['capixy tonic', 'tonic spray', 'capixyl', 'تونك كابيكسى', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'تونك سبراي لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Spray',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 71
	{
		id: 'coffee-zinc-hair-tonic-liquid-250ml',
		name: 'coffee zinc hair tonic liquid 250 ml',
		genericName: 'caffeine & argan oil & rosemary oil',
		concentration: '250 ml',
		price: 245,
		matchKeywords: ['coffee zinc', 'hair tonic', 'caffeine', 'rosemary', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'تونك/لوشن لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 72
	{
		id: 'keraqouz-hair-serum-4-amp-x-10ml',
		name: 'keraqouz hair serum 4 amp. x 10 ml',
		genericName: 'keratin & hydrolyzed wheat protein & silicon & tocopherol',
		concentration: '4 amp. x 10 ml',
		price: 185,
		matchKeywords: ['keraqouz ampoules', 'hair serum amp', 'ampoule', 'امبولات شعر', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'أمبولات/سيروم لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 73
	{
		id: 'keraqouz-hair-tonic-10-amp-x-5ml',
		name: 'keraqouz hair tonic 10 amp. x 5 ml',
		genericName: 'keratin & hydrolyzed wheat protein & silicon & tocopherol',
		concentration: '10 amp. x 5 ml',
		price: 250,
		matchKeywords: ['keraqouz tonic ampoules', '10 amp', 'امبولات تونك', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'أمبولات تونك لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 74
	{
		id: 'seropipe-hair-conditioner-200ml',
		name: 'seropipe hair conditioner 200 ml',
		genericName: 'kamigen e & kamigen k & hydrolyzed lupin protein & hordeum vulgare',
		concentration: '200 ml',
		price: 215,
		matchKeywords: ['seropipe conditioner', 'conditioner', 'بلسم', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'بلسم لترطيب الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 75
	{
		id: 'investa-hair-serum-120ml',
		name: 'investa hair serum 120 ml',
		genericName: 'saw palmetto & caffeine & castor oil',
		concentration: '120 ml',
		price: 160,
		matchKeywords: ['investa', 'hair serum', 'saw palmetto', 'caffeine', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم/لوشن لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 76
	{
		id: 'rostevo-anti-frizz-hair-mask-250ml',
		name: 'rostevo anti-frizz hair mask 250ml',
		genericName: 'conditioning agents',
		concentration: '250 ml',
		price: 85,
		matchKeywords: ['rostevo anti-frizz', 'hair mask', 'anti frizz', 'ماسك', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'ماسك مضاد للهيشان لترطيب الشعر وتنعيمه.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 77
	{
		id: 'rostevo-hair-conditioner-250ml',
		name: 'rostevo hair conditioner 250ml',
		genericName: 'conditioning base',
		concentration: '250 ml',
		price: 100,
		matchKeywords: ['rostevo conditioner', 'conditioner', 'بلسم', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'بلسم لترطيب الشعر وتقليل التشابك.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cream',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 78
	{
		id: 'rostevo-hair-oil-100ml',
		name: 'rostevo 100 ml hair oil',
		genericName: 'oils blend',
		concentration: '100 ml',
		price: 150,
		matchKeywords: ['rostevo hair oil', '100ml', 'زيت روستيفو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتقليل الجفاف وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 79
	{
		id: 'relat-hair-tonic-lotion-120ml',
		name: 'relat hair tonic lotion 120 ml',
		genericName: 'caffeine & ginseng extract',
		concentration: '120 ml',
		price: 220,
		matchKeywords: ['relat', 'hair tonic', 'caffeine', 'ginseng', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'تونك لفروة الرأس لدعم تقليل التساقط وتحسين صحة الفروة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 80
	{
		id: 'complete-hair-oil-120ml',
		name: 'complete hair oil 120 ml',
		genericName: 'olive oil & emu oil & sesame oil & wheat germ oil & rocket oil',
		concentration: '120 ml',
		price: 175,
		matchKeywords: ['complete hair oil', 'rocket oil', 'زيت كومبليت', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت للشعر لتغذية وترطيب وتقليل الجفاف.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 81
	{
		id: 'dandel-hair-shampoo-250ml',
		name: 'dandel hair shampoo 250ml',
		genericName: 'zinc pyrithione & selenium sulphide & aloe vera',
		concentration: '250 ml',
		price: 180,
		matchKeywords: ['dandel shampoo', 'selenium sulphide', 'zinc pyrithione', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة/التهاب الجلد الدهني بفروة الرأس.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 82
	{
		id: 'dago-plus-hair-shampoo-250ml',
		name: 'dago plus hair shampoo 250ml',
		genericName: 'selenium sulphide & zinc pyrithione',
		concentration: '250 ml',
		price: 300,
		matchKeywords: ['dago plus', 'selenium sulphide', 'zinc pyrithione', 'anti-dandruff', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 83
	{
		id: 'hair-plus-back-2pct-scalp-lotion-100ml',
		name: 'hair plus-back 2% scalp lotion 100 ml',
		genericName: 'minoxidil',
		concentration: '2% (100 ml)',
		price: 164,
		matchKeywords: ['hair plus-back 2%', 'minoxidil 2%', 'scalp lotion', '#hair_regrowth'],
		usage: 'مينوكسيديل ٢٪ محلول لفروة الرأس لتحفيز إنبات الشعر (قد يُستخدم خاصة للنساء حسب الإرشاد).',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Solution',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...MINOXIDIL_WARNINGS],
	},

	// 84
	{
		id: 'hairodex-hair-serum-120ml',
		name: 'hairodex hair serum 120 ml',
		genericName: 'silicone oil & oleanolic acid & gamma linolenic acid',
		concentration: '120 ml',
		price: 240,
		matchKeywords: ['hairodex', 'hair serum', 'oleanolic acid', 'سيروم هايرودكس', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'سيروم/لوشن لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 85
	{
		id: 'panthovera-hair-shampoo-250ml',
		name: 'panthovera hair shampoo 250 ml',
		genericName: 'l-arginine & saw palmetto extract & ginkgo biloba extract & rosemary',
		concentration: '250 ml',
		price: 185,
		matchKeywords: ['panthovera shampoo', 'arginine', 'saw palmetto', 'شامبو', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للعناية بالشعر ودعم مظهره.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 86
	{
		id: 'seboral-hair-shampoo-125ml',
		name: 'seboral hair shampoo 125ml',
		genericName: 'zinc pyrithione',
		concentration: '125 ml',
		price: 75,
		matchKeywords: ['seboral', 'anti-dandruff', 'zinc pyrithione', 'قشرة', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'شامبو للقشرة وتهدئة الحكة.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Cleanser',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...ANTI_DANDRUFF_SHAMPOO_WARNINGS],
	},

	// 87
	{
		id: 'top-hair-lotion-plus-120ml',
		name: 'top hair lotion plus 120 ml',
		genericName: 'caffeine & argan oil & ginseng & wheat germ oil & vitamin e',
		concentration: '120 ml',
		price: 230,
		matchKeywords: ['top hair lotion plus', 'caffeine', 'ginseng', 'لوشن', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'لوشن لفروة الرأس لدعم تقليل التساقط وتحسين مظهر الشعر.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 40,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},

	// 88
	{
		id: 'tress-hair-oil-120ml',
		name: 'tress hair oil 120 ml',
		genericName: 'cyclopentasiloxane & matricaria flower extract',
		concentration: '120 ml',
		price: 160,
		matchKeywords: ['tress hair oil', '120ml', 'زيت تريس', '#hair_care', 'شعر', 'hair', 'فروة الرأس', 'scalp'],
		usage: 'زيت/سيروم زيتي لتنعيم الشعر وتقليل الهيشان وتحسين اللمعان.',
		timing: '٣ مرات أسبوعياً',
		category: Category.HAIR_CARE,
		form: 'Lotion',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 15,
		maxWeight: 250,
		calculationRule: fixed('يُدلَّك في فروة الرأس ٣ مرات أسبوعياً ويُترك ٥ دقائق ثم يُشطف'),
		warnings: [...COMMON_HAIR_CARE_WARNINGS],
	},
];

