
import { Medication, Category } from '../../types';

const normalizeSpaces = (input: string) =>
	(input || '')
		.replace(/\s+/g, ' ')
		.replace(/\s+([،.؛:!؟)\]])/g, '$1')
		.replace(/([(\[])\s+/g, '$1')
		.replace(/\(\s*\)/g, '')
		.trim();

const stripDoctorPhrases = (input: string) => {
	let text = input || '';
	const patterns: RegExp[] = [
		/\(\s*حسب\s+الطبيب\s*\)/g,
		/\(\s*أو\s+حسب\s+الطبيب\s*\)/g,
		/\(\s*بوصفة\s+طبيب\s*\)/g,
		/حسب\s+الطبيب/g,
		/بتوجيه\s+طبي/g,
		/استشارة\s+طبيب/g,
		/استشر\s+الطبيب/g,
		/راجع\s+الطبيب/g,
		/بوصفة\s+طبيب/g,
		/تحت\s+إشراف\s+طبي/g,
	];
	for (const p of patterns) text = text.replace(p, '');
	return normalizeSpaces(text);
};

const sanitizeText = (input: string) => {
	let text = stripDoctorPhrases(input || '');
	text = text
		.replace(/\bلا\s+تتجاوز\b/g, 'الحد الأعلى')
		.replace(/\bممنوع\b/g, 'غير مناسب')
		.replace(/\bيُمنع\b/g, 'غير مناسب')
		.replace(/\bأوقف\b/g, 'الإيقاف')
		.replace(/\bتوقف\b/g, 'الإيقاف');
	return normalizeSpaces(text);
};

const wrapRule = (rule?: Medication['calculationRule']): Medication['calculationRule'] | undefined => {
	if (!rule) return rule;
	return (weight, ageMonths) => sanitizeText(rule(weight, ageMonths));
};

const buildWarnings = (...parts: Array<string | string[] | undefined | null>) => {
	const out: string[] = [];
	for (const part of parts) {
		if (!part) continue;
		if (Array.isArray(part)) out.push(...part);
		else out.push(part);
	}
	return out.map(sanitizeText).filter(Boolean);
};

const sanitizeMedication = (m: Medication): Medication => {
	const { instructions: _omit, ...rest } = m as Medication & { instructions?: unknown };
	return {
		...rest,
		usage: sanitizeText(m.usage),
		timing: sanitizeText(m.timing),
		warnings: m.warnings ? m.warnings.map(sanitizeText).filter(Boolean) : m.warnings,
		calculationRule: wrapRule(m.calculationRule)!,
		matchKeywords: m.matchKeywords?.map(sanitizeText).filter(Boolean),
	};
};

const fixed = (text: string) => (_w: number, _a: number) => text;

const uniq = (values: Array<string | undefined | null>) => {
	const out: string[] = [];
	const seen = new Set<string>();
	for (const v of values) {
		const s = (v || '').toString().trim();
		if (!s) continue;
		const key = s.toLowerCase();
		if (seen.has(key)) continue;
		seen.add(key);
		out.push(s);
	}
	return out;
};

const baseKeywords = (...extras: string[]) =>
	uniq([
		'#antiviral',
		'antiviral',
		'viral',
		'virus',
		'مضاد فيروسات',
		'فيروسات',
		...extras,
	]);

const W_ALLERGY = ['حساسية شديدة (طفح منتشر/تورم/ضيق تنفس) تستلزم الإيقاف والتقييم العاجل.'];
const W_PREG_LACT = ['الحمل/الرضاعة: قد يلزم تقييم قبل الاستخدام.'];
const W_KIDNEY = ['القصور الكلوي: قد يلزم تعديل الجرعة للأشكال الفموية/الوريدية.'];
const W_HYDRATION = ['الترطيب الكافي (شرب سوائل وافرة) ضروري أثناء العلاج لتقليل خطر ترسب الدواء في الكلى.'];
const W_EXTERNAL_ONLY = ['للاستخدام الخارجي فقط. تجنب ملامسة العين/الفم إلا إذا كان المستحضر مخصصاً لذلك.'];
const W_EYE_ONLY = ['للاستخدام العيني فقط.'];
const W_IV_ONLY = ['للاستخدام بالمستشفى/المنشآت الصحية فقط.'];

const KW_COMMON = baseKeywords('فيروس', 'عدوى فيروسية');
const KW_HERPES = ['herpes', 'HSV', 'herpes simplex', 'zoster', 'shingles', 'varicella', 'chickenpox', 'هربس', 'حزام ناري', 'جدري مائي'];
const KW_EYE_HERPES = ['herpetic keratitis', 'keratitis', 'التهاب قرنية', 'عدوى قرنية'];
const KW_FLU = ['influenza', 'flu', 'إنفلونزا', 'برد شديد'];
const KW_COVID = ['covid', 'covid-19', 'كورونا', 'كوفيد'];
const KW_HBV_HIV = ['hepatitis b', 'HBV', 'hiv', 'AIDS', 'التهاب كبدي', 'فيروس كبدي', 'فيروس ب', 'فيروس نقص المناعة'];
const KW_RHEUM = ['rheumatoid arthritis', 'RA', 'روماتويد', 'التهاب مفاصل روماتويدي'];

const RAW_ANTIVIRAL_GROUP: Medication[] = [
	{
		id: 'zovirax-5pct-cream-10g',
		name: 'Zovirax 5% topical cream 10 gm',
		genericName: 'acyclovir',
		concentration: '5% cream 10 gm',
		price: 27,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'zovirax', 'زوفيراكس', 'زوفيراكس كريم', 'أسيكلوفير', ...KW_HERPES, 'topical', 'cream', 'كريم']),
		usage: 'مضاد فيروسات موضعي (Acyclovir) لعدوى الهربس الجلدية.',
		timing: '٥ مرات يومياً – ٤–٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'Cream',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٥ مرات يومياً لمدة ٤–٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_EXTERNAL_ONLY, W_PREG_LACT),
	},
	{
		id: 'zovirax-ds-400mg-5ml-susp-100ml',
		name: 'Zovirax d.s 400mg/5ml susp. 100 ml',
		genericName: 'acyclovir',
		concentration: '400mg/5ml',
		price: 96,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'zovirax', 'زوفيراكس', 'زوفيراكس شراب', 'أسيكلوفير', ...KW_HERPES, 'suspension', 'شراب', 'معلق']),
		usage: 'مضاد فيروسات (Acyclovir) معلق فموي لعدوى الهربس/الجدري المائي حسب العمر والوزن.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Suspension',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('٥ مل (٤٠٠ مجم) ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'pk-merz-100mg-30-fc-tab',
		name: 'PK-Merz 100mg 30 f.c. tab',
		genericName: 'amantadine sulphate',
		concentration: '100mg',
		price: 81,
		matchKeywords: uniq([...KW_COMMON, '#uncoating inhibitor', 'amantadine', 'amantadine sulphate', 'pk-merz', 'بي كي ميرز', 'amantadine', ...KW_FLU]),
		usage: 'مضاد فيروسات (Amantadine) مثبط فك الغلاف الفيروسي، وقد يُستخدم في بعض عدوى الإنفلونزا.',
		timing: 'مرتين يومياً – ٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرتين يومياً لمدة ٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT),
	},
	{
		id: 'arthfree-20mg-30-fc-tab',
		name: 'Arthfree 20mg 30 f.c. tab.',
		genericName: 'leflunomide',
		concentration: '20mg',
		price: 261,
		matchKeywords: uniq([...KW_COMMON, '#immunosuppressive', '#antirheumatic', 'leflunomide', 'arthfree', 'أرث فري', 'ارثفري', 'ليفلو نوميد', ...KW_RHEUM]),
		usage: 'دواء مثبط مناعة/مضاد روماتيزم (Leflunomide) لالتهاب المفاصل الروماتويدي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIVIRAL,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة طويلة'),
		warnings: buildWarnings(
			W_ALLERGY,
			'أمراض الكبد/ارتفاع إنزيمات الكبد: قد يلزم تقييم قبل الاستخدام.',
			'الحمل: غير مناسب.',
			'قد يقلل المناعة؛ العدوى الشديدة تستلزم تقييماً عاجلاً.',
		),
	},
	{
		id: 'lovir-400mg-10-disp-tab',
		name: 'Lovir 400mg 10 disp. tab.',
		genericName: 'acyclovir',
		concentration: '400mg',
		price: 76,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'lovir', 'لوفير', 'أسيكلوفير ٤٠٠', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) لعدوى الهربس/الحزام الناري.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'virustat-200mg-5ml-susp-120ml',
		name: 'Virustat 200mg/5ml susp. 120 ml',
		genericName: 'acyclovir',
		concentration: '200mg/5ml',
		price: 61,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'virustat', 'فيروستات', 'أسيكلوفير', ...KW_HERPES, 'suspension', 'شراب', 'معلق']),
		usage: 'مضاد فيروسات (Acyclovir) معلق فموي لعدوى الهربس/الجدري المائي حسب العمر والوزن.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Suspension',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('٥ مل (٢٠٠ مجم) ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'zovirax-400mg-10-tab',
		name: 'Zovirax 400mg 10 tab.',
		genericName: 'acyclovir',
		concentration: '400mg',
		price: 49,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'zovirax', 'زوفيراكس ٤٠٠', 'أسيكلوفير', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) لعدوى الهربس/الحزام الناري.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'acyclovir-misr-5pct-cream-10g',
		name: 'Acyclovir-Misr 5% topical cream 10 gm',
		genericName: 'acyclovir',
		concentration: '5% cream 10 gm',
		price: 23,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'acyclovir misr', 'أسيكلوفير مصر', 'كريم أسيكلوفير', ...KW_HERPES, 'topical', 'cream']),
		usage: 'مضاد فيروسات موضعي (Acyclovir) لعدوى الهربس الجلدية.',
		timing: '٥ مرات يومياً – ٤–٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'Cream',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٥ مرات يومياً لمدة ٤–٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_EXTERNAL_ONLY, W_PREG_LACT),
	},
	{
		id: 'virustat-5pct-cream-5g',
		name: 'Virustat 5% cream 5 gm',
		genericName: 'acyclovir',
		concentration: '5% cream 5 gm',
		price: 13,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'virustat', 'فيروستات كريم', 'أسيكلوفير كريم', ...KW_HERPES, 'topical', 'cream']),
		usage: 'مضاد فيروسات موضعي (Acyclovir) لعدوى الهربس الجلدية.',
		timing: '٥ مرات يومياً – ٤–٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'Cream',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('طبقة رقيقة على المنطقة المصابة ٥ مرات يومياً لمدة ٤–٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_EXTERNAL_ONLY, W_PREG_LACT),
	},
	{
		id: 'acyclovir-800-stada-35-tab',
		name: 'Acyclovir 800 stada 35 tab.',
		genericName: 'acyclovir',
		concentration: '800mg',
		price: 280,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'stada', 'أسيكلوفير ٨٠٠', 'acyclovir 800', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) تركيز ٨٠٠ مجم لعدوى الهربس/الحزام الناري.',
		timing: 'كل ٤ ساعات – ٧–١٠ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٧–١٠ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'acyclovir-3pct-eye-ointment-5g',
		name: 'Acyclovir 3% eye oint. 5 gm',
		genericName: 'acyclovir',
		concentration: '3% eye ointment 5 gm',
		price: 5.75,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'eye ointment', 'مرهم عين أسيكلوفير', ...KW_EYE_HERPES, ...KW_HERPES]),
		usage: 'مرهم عيني مضاد فيروسات (Acyclovir) لعدوى الهربس بالعين.',
		timing: '٥ مرات يومياً – حتى الالتئام',
		category: Category.ANTIVIRAL,
		form: 'Ointment',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('شريط صغير داخل الجفن السفلي ٥ مرات يومياً حتى الالتئام'),
		warnings: buildWarnings(W_ALLERGY, W_EYE_ONLY, W_PREG_LACT),
	},
	{
		id: 'apetoid-20mg-30-fc-tab',
		name: 'Apetoid 20mg 30 f.c.tab.',
		genericName: 'leflunomide',
		concentration: '20mg',
		price: 180,
		matchKeywords: uniq([...KW_COMMON, '#immunosuppressive', '#antirheumatic', 'leflunomide', 'apetoid', 'ابيتويد', 'ليفلو نوميد', ...KW_RHEUM]),
		usage: 'دواء مثبط مناعة/مضاد روماتيزم (Leflunomide) لالتهاب المفاصل الروماتويدي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIVIRAL,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة طويلة'),
		warnings: buildWarnings(
			W_ALLERGY,
			'أمراض الكبد/ارتفاع إنزيمات الكبد: قد يلزم تقييم قبل الاستخدام.',
			'الحمل: غير مناسب.',
			'قد يقلل المناعة؛ العدوى الشديدة تستلزم تقييماً عاجلاً.',
		),
	},
	{
		id: 'avara-20mg-30-fc-tab',
		name: 'Avara 20mg 30 f.c.tab.',
		genericName: 'leflunomide',
		concentration: '20mg',
		price: 483,
		matchKeywords: uniq([...KW_COMMON, '#immunosuppressive', '#antirheumatic', 'leflunomide', 'avara', 'افارا', 'ليفلو نوميد', ...KW_RHEUM]),
		usage: 'دواء مثبط مناعة/مضاد روماتيزم (Leflunomide) لالتهاب المفاصل الروماتويدي.',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIVIRAL,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة طويلة'),
		warnings: buildWarnings(
			W_ALLERGY,
			'أمراض الكبد/ارتفاع إنزيمات الكبد: قد يلزم تقييم قبل الاستخدام.',
			'الحمل: غير مناسب.',
			'قد يقلل المناعة؛ العدوى الشديدة تستلزم تقييماً عاجلاً.',
		),
	},
	{
		id: 'lamidine-100mg-30-fc-tab',
		name: 'Lamidine 100mg 30 f.c. tab.',
		genericName: 'lamivudine',
		concentration: '100mg',
		price: 123,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'lamivudine', 'lamidine', 'لاميدين', 'لاميفودين', ...KW_HBV_HIV]),
		usage: 'مضاد فيروسات (Lamivudine).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIVIRAL,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً لمدة طويلة'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'zovirax-250mg-5-vial-iv-infusion',
		name: 'Zovirax 250mg 5 vial i.v. infusion',
		genericName: 'acyclovir',
		concentration: '250mg',
		price: 910,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'zovirax', 'zovirax iv', 'زوفيراكس وريدي', 'infusion', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) للحقن الوريدي للحالات الشديدة.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.ANTIVIRAL,
		form: 'I.V. Infusion Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('تسريب وريدي حسب الوزن كل ٨ ساعات لمدة ٧–١٤ يوم'),
		warnings: buildWarnings(W_ALLERGY, W_IV_ONLY, W_KIDNEY),
	},
	{
		id: 'acivirax-400mg-30-tabs',
		name: 'Acivirax 400mg 30 tabs.',
		genericName: 'acyclovir',
		concentration: '400mg',
		price: 162,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'acivirax', 'اسيفيراكس', 'أسيكلوفير ٤٠٠', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) لعدوى الهربس/الحزام الناري.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'acyclovir-400-stada-35-tabs',
		name: 'Acyclovir 400 stada 35 tabs.',
		genericName: 'acyclovir',
		concentration: '400mg',
		price: 210,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'stada', 'أسيكلوفير ٤٠٠', 'acyclovir 400', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) لعدوى الهربس/الحزام الناري.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'ganvir-0-15pct-ophthalmic-gel-10g',
		name: 'Ganvir 0.15% ophthalmic gel 10 gm',
		genericName: 'ganciclovir',
		concentration: '0.15% gel 10 gm',
		price: 55,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'ganciclovir', 'ganvir', 'جانفير', 'جل عين', ...KW_EYE_HERPES, ...KW_HERPES]),
		usage: 'جل عيني مضاد فيروسات (Ganciclovir) لالتهاب القرنية الهربسي الحاد (قرح شجرية).',
		timing: '٥ مرات يومياً – حتى الالتئام',
		category: Category.ANTIVIRAL,
		form: 'Gel',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('نقطة في العين ٥ مرات يومياً حتى الالتئام ثم ٣ مرات يومياً لمدة ٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_EYE_ONLY, 'العدسات اللاصقة: غير مناسب أثناء العدوى أو طوال فترة العلاج.', W_PREG_LACT),
	},
	{
		id: 'pk-merz-200mg-500ml-iv-infusion',
		name: 'PK-Merz 200mg/500ml sol. for iv inf.',
		genericName: 'amantadine sulphate',
		concentration: '200mg/500ml',
		price: 500,
		matchKeywords: uniq([...KW_COMMON, '#uncoating inhibitor', 'amantadine', 'pk-merz', 'بي كي ميرز', 'iv infusion']),
		usage: 'Amantadine sulphate محلول للحقن الوريدي.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.ANTIVIRAL,
		form: 'I.V. Infusion Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('تسريب وريدي كل ٨ ساعات لمدة ٧–١٤ يوم'),
		warnings: buildWarnings(W_ALLERGY, W_IV_ONLY, W_PREG_LACT),
	},
	{
		id: 'virustat-200mg-20-tab',
		name: 'Virustat 200mg 20 tab.',
		genericName: 'acyclovir',
		concentration: '200mg',
		price: 24,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'virustat', 'فيروستات ٢٠٠', 'أسيكلوفير ٢٠٠', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) ٢٠٠ مجم لعدوى الهربس.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'virustat-400mg-5ml-susp-120ml',
		name: 'Virustat 400mg/5ml susp. 120 ml',
		genericName: 'acyclovir',
		concentration: '400mg/5ml',
		price: 70,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'virustat', 'فيروستات شراب', 'أسيكلوفير', '400/5', ...KW_HERPES, 'suspension', 'معلق']),
		usage: 'مضاد فيروسات (Acyclovir) معلق فموي لعدوى الهربس/الجدري المائي حسب العمر والوزن.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Suspension',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('٥ مل (٤٠٠ مجم) ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'zovirax-200mg-5ml-susp-125ml',
		name: 'Zovirax 200mg/5ml susp. 125ml',
		genericName: 'acyclovir',
		concentration: '200mg/5ml',
		price: 143.05,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'zovirax', 'zovirax suspension', 'زوفيراكس شراب', '200/5', ...KW_HERPES, 'suspension', 'معلق']),
		usage: 'مضاد فيروسات (Acyclovir) معلق فموي لعدوى الهربس/الجدري المائي حسب العمر والوزن.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Suspension',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('٥ مل (٢٠٠ مجم) ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'zovirax-500mg-5-iv-inf-vial',
		name: 'Zovirax 500 mg 5 i.v. inf. vial',
		genericName: 'acyclovir',
		concentration: '500mg',
		price: 1135,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'zovirax', 'zovirax iv', 'زوفيراكس ٥٠٠ وريدي', 'infusion', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) للحقن الوريدي للحالات الشديدة.',
		timing: 'كل ٨ ساعات – ٧–١٤ يوم',
		category: Category.ANTIVIRAL,
		form: 'I.V. Infusion Vial',
		minAgeMonths: 0,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('تسريب وريدي حسب الوزن كل ٨ ساعات لمدة ٧–١٤ يوم'),
		warnings: buildWarnings(W_ALLERGY, W_IV_ONLY, W_KIDNEY),
	},
	{
		id: 'virustat-400mg-35-tab',
		name: 'Virustat 400mg 35 tab.',
		genericName: 'acyclovir',
		concentration: '400mg',
		price: 35,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'acyclovir', 'virustat', 'فيروستات ٤٠٠', '35 tab', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Acyclovir) لعدوى الهربس/الحزام الناري.',
		timing: 'كل ٤ ساعات – ٥–٧ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص ٥ مرات يومياً لمدة ٥–٧ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'tamiflu-75mg-10-caps',
		name: 'Tamiflu 75mg 10caps.',
		genericName: 'oseltamivir',
		concentration: '75mg',
		price: 345,
		matchKeywords: uniq([...KW_COMMON, 'oseltamivir', 'tamiflu', 'تاميفلو', ...KW_FLU]),
		usage: 'مضاد فيروسات (Oseltamivir) للإنفلونزا.',
		timing: 'كل ١٢ ساعة – ٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ كبسولة مرتين يومياً لمدة ٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'tenaviron-300mg-30-tablets',
		name: 'Tenaviron 300 mg 30 tablets',
		genericName: 'tenofovir disoproxil fumarate',
		concentration: '300mg',
		price: 489,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'tenofovir', 'tenofovir disoproxil fumarate', 'tenaviron', 'تينافيرون', 'تينوفوفير', ...KW_HBV_HIV]),
		usage: 'مضاد فيروسات (Tenofovir disoproxil fumarate).',
		timing: 'مرة يومياً – مزمن',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرة يومياً مع الأكل لمدة طويلة'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'valtrex-500mg-42-tab',
		name: 'Valtrex 500mg 42 tab.',
		genericName: 'valaciclovir',
		concentration: '500mg',
		price: 789,
		matchKeywords: uniq([...KW_COMMON, '#nucleoside', 'valaciclovir', 'valtrex', 'فالتريكس', 'فالاسيكلوفير', ...KW_HERPES]),
		usage: 'مضاد فيروسات (Valaciclovir) لعدوى الهربس/الحزام الناري.',
		timing: 'كل ١٢ ساعة – ٥–١٠ أيام',
		category: Category.ANTIVIRAL,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('١ قرص مرتين يومياً لمدة ٥–١٠ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_KIDNEY, W_HYDRATION),
	},
	{
		id: 'covapravir-200mg-40-caps-hospital-only',
		name: 'Covapravir 200 mg 40 caps. (hospital only)',
		genericName: 'molnupiravir',
		concentration: '200mg',
		price: 420,
		matchKeywords: uniq([...KW_COMMON, 'molnupiravir', 'covapravir', 'كوفابرافير', ...KW_COVID, 'hospital']),
		usage: 'مضاد فيروسات (Molnupiravir).',
		timing: 'كل ١٢ ساعة – ٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٤ كبسولات (٨٠٠ مجم) كل ١٢ ساعة لمدة ٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT, W_IV_ONLY),
	},
	{
		id: 'covapravir-200mg-40-caps',
		name: 'Covapravir 200 mg 40 caps.',
		genericName: 'molnupiravir',
		concentration: '200mg',
		price: 420,
		matchKeywords: uniq([...KW_COMMON, 'molnupiravir', 'covapravir', 'كوفابرافير', ...KW_COVID]),
		usage: 'مضاد فيروسات (Molnupiravir).',
		timing: 'كل ١٢ ساعة – ٥ أيام',
		category: Category.ANTIVIRAL,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٤ كبسولات (٨٠٠ مجم) كل ١٢ ساعة لمدة ٥ أيام'),
		warnings: buildWarnings(W_ALLERGY, W_PREG_LACT),
	},
];

export const ANTIVIRAL_GROUP: Medication[] = RAW_ANTIVIRAL_GROUP.map(sanitizeMedication);
