import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
	'لا تتجاوز الجرعة اليومية الموصى بها.',
	'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
	'افصل ساعتين عن الحديد/الليفوثيروكسين/بعض المضادات الحيوية (مثل التتراسيكلين والكينولون) لتجنب تقليل الامتصاص.',
];

const CALCIUM_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'لا تتجاوز ٥٠٠ مجم كالسيوم في الجرعة الواحدة لضمان الامتصاص الأمثل؛ وزّع الجرعات خلال اليوم.',
	'افصل ساعتين على الأقل عن مكملات الحديد لتجنب تقليل امتصاص كلا المعدنين.',
	'مرضى حصوات الكلى/فرط كالسيوم الدم: يُفضّل إعادة تقييم قبل الاستخدام.',
	'الجرعة الزائدة من فيتامين د (إن وُجد بالمكمل) قد تسبب ارتفاع الكالسيوم (غثيان/عطش شديد/ضعف).',
];

const SYRUP_AGE_RULE_5_OR_10_ML = (_w: number, ageMonths: number) => (ageMonths < 144 ? '٥ مل مرة يومياً بعد الأكل' : '١٠ مل مرة يومياً بعد الأكل');

export const CALCIUM_GROUP: Medication[] = [
	// 1
	{
		id: 'egy-pedical-plus-syrup-100ml-calcium',
		name: 'egy pedical plus syrup 100 ml',
		genericName: 'vitamin d & calcium & menakion & vitamin k2 & vitamin b12',
		concentration: '100 ml syrup',
		price: 65,
		matchKeywords: ['egy pedical plus', 'pedical plus', 'ايجي بيديكال', 'كالسيوم', 'vitamin d', 'vitamin k2', 'b12', '#calcium', '#bone', '#growth'],
		usage: 'شراب كالسيوم + فيتامين د مع K2 وB12 لدعم العظام والنمو وتعويض النقص.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: CALCIUM_WARNINGS,
	},

	// 2
	{
		id: 'janca-z-30-fc-tabs-calcium',
		name: 'janca-z 30 f.c. tab.',
		genericName: 'calcium & vitamin d3 & magnesium & zinc & boron & c...',
		concentration: '30 F.C. tablets',
		price: 75,
		matchKeywords: ['janca-z', 'جانكا زد', 'calcium', 'vitamin d3', 'magnesium', 'zinc', 'boron', '#calcium', '#magnesium'],
		usage: 'أقراص كالسيوم مع فيتامين د٣ ومعادن (ماغنسيوم/زنك/بورون) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 3
	{
		id: 'maronal-30-tabs-calcium',
		name: 'maronal 30 tab',
		genericName: 'calcium',
		concentration: '30 tablets',
		price: 110,
		matchKeywords: ['maronal', 'مارونال', 'calcium', 'كالسيوم', '#calcium', '#bone'],
		usage: 'أقراص كالسيوم لدعم العظام وتعويض نقص الكالسيوم.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 4
	{
		id: 'carla-extra-30-tabs-calcium',
		name: 'carla extra 30 tabs.',
		genericName: 'calcium & magnesium & vitamin d3 & zinc',
		concentration: '30 tablets',
		price: 125,
		matchKeywords: ['carla extra', 'كارلا اكسترا', 'calcium', 'magnesium', 'vitamin d3', 'zinc', '#calcium', '#magnesium'],
		usage: 'أقراص كالسيوم + ماغنسيوم + زنك + فيتامين د٣ لدعم العظام والعضلات.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 5
	{
		id: 'boston-cal-vitamin-syrup-100ml-calcium',
		name: 'boston cal vitamin syrup 100 ml',
		genericName: 'calcium',
		concentration: '100 ml syrup',
		price: 99,
		matchKeywords: ['boston cal', 'بوستن كال', 'calcium syrup', 'كالسيوم شراب', '#calcium'],
		usage: 'شراب كالسيوم لدعم العظام وتعويض نقص الكالسيوم.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: CALCIUM_WARNINGS,
	},

	// 6
	{
		id: 'fantocal-20-tabs-calcium',
		name: 'fantocal 20 tabs.',
		genericName: 'calcium & vitamin d3 & magnesium & zinc & boron & s...',
		concentration: '20 tablets',
		price: 95,
		matchKeywords: ['fantocal', 'فانتوكال', 'calcium', 'vitamin d3', 'magnesium', 'zinc', 'boron', '#calcium'],
		usage: 'أقراص كالسيوم مع فيتامين د٣ ومعادن لدعم صحة العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 7
	{
		id: 'hacaci-oral-susp-120ml-calcium',
		name: 'hacaci oral susp. 120 ml',
		genericName: 'calcium & zinc & vitamin d3',
		concentration: '120 ml oral suspension',
		price: 49,
		matchKeywords: ['hacaci', 'هاكاسي', 'calcium', 'zinc', 'vitamin d3', 'deficiency', 'نقص كالسيوم', '#calcium', '#calcium_deficiency'],
		usage: 'معلق فموي كالسيوم + زنك + فيتامين د٣ لدعم علاج نقص الكالسيوم ودعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Oral Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 1200,
		minWeight: 6,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: CALCIUM_WARNINGS,
	},

	// 8
	{
		id: 'janca-z-kids-syrup-120ml-calcium',
		name: 'janca-z kids syrup 120ml',
		genericName: 'calcium & vitamin d3 & magnesium & zinc & boron & c...',
		concentration: '120 ml syrup',
		price: 40,
		matchKeywords: ['janca-z kids', 'جانكا زد كيدز', 'calcium', 'vitamin d3', 'magnesium', 'zinc', 'kids', 'نمو', '#calcium'],
		usage: 'شراب للأطفال لدعم العظام والنمو (كالسيوم + فيتامين د٣ + معادن).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 216,
		minWeight: 8,
		maxWeight: 80,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: CALCIUM_WARNINGS,
	},

	// 9
	{
		id: 'tocadon-fc-30-tabs-calcium',
		name: 'tocadon f.c.t 30 tablets',
		genericName: 'calcium & magnesium & zinc & vitamin d3 & vitamin k',
		concentration: '30 F.C. tablets',
		price: 95,
		matchKeywords: ['tocadon', 'توكادون', 'calcium', 'magnesium', 'zinc', 'vitamin d3', 'vitamin k', '#calcium', '#magnesium'],
		usage: 'أقراص دعم العظام (كالسيوم + ماغنسيوم + زنك + فيتامين د٣ + فيتامين ك).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 10
	{
		id: 'heptacal-20-tabs-calcium',
		name: 'heptacal 20 tabs',
		genericName: 'calcium & magnesium & vitamin d3',
		concentration: '20 tablets',
		price: 80,
		matchKeywords: ['heptacal', 'هيبتاكال', 'calcium', 'magnesium', 'vitamin d3', '#calcium', '#magnesium'],
		usage: 'أقراص كالسيوم + ماغنسيوم + فيتامين د٣ لدعم العظام والعضلات.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 11
	{
		id: 'baby-calcium-syrup-120ml-calcium',
		name: 'baby calcium syrup 120 ml',
		genericName: 'calcium',
		concentration: '120 ml syrup',
		price: 72,
		matchKeywords: ['baby calcium', 'بيبي كالسيوم', 'calcium syrup', 'كالسيوم للاطفال', 'نمو', '#calcium'],
		usage: 'شراب كالسيوم للأطفال لدعم النمو وتعويض نقص الكالسيوم.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 216,
		minWeight: 8,
		maxWeight: 80,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: CALCIUM_WARNINGS,
	},

	// 12
	{
		id: 'egy-cal-30-tabs-calcium',
		name: 'egy cal 30 tabs',
		genericName: 'calcium',
		concentration: '30 tablets',
		price: 75,
		matchKeywords: ['egy cal', 'ايجي كال', 'calcium', 'كالسيوم', '#calcium', '#bone'],
		usage: 'أقراص كالسيوم لتعويض نقص الكالسيوم ودعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 13
	{
		id: 'stravita-cal-1000mg-30-fc-tabs-calcium',
		name: 'stravita cal 1000 mg calcium 30 f.c. tab',
		genericName: 'calcium carbonate & magnesium & zinc & vitamin d...',
		concentration: '1000 mg calcium (30 F.C. tablets)',
		price: 90,
		matchKeywords: ['stravita cal', 'سترافيتا كال', '1000 mg calcium', 'calcium carbonate', 'magnesium', 'zinc', 'vitamin d', '#calcium'],
		usage: 'أقراص كالسيوم (١٠٠٠ مجم كالسيوم) مع معادن/فيتامينات لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},
];

