
import { Medication, Category } from '../../types';
import { DIETARY_SUPPLEMENTS_3 } from './dietary_supplements_3';
import { DIETARY_SUPPLEMENTS_4 } from './dietary_supplements_4';
import { DIETARY_SUPPLEMENTS_5 } from './dietary_supplements_5';
import { DIETARY_SUPPLEMENTS_6 } from './dietary_supplements_6';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
	'لا تتجاوز الجرعة اليومية الموصى بها.',
	'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
	'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين D أو A أو E أو K بجرعات عالية.',
];

const IRON_SUPPLEMENT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
	'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
	'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const ZINC_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const CALCIUM_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
	'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const INJECTION_WARNINGS = [
	'للإعطاء بالمستشفى/العيادة فقط (حقن وريد/عضل).',
	'قد يسبب تفاعل تحسسي؛ توفر أدوية الطوارئ عند ضيق نفس/تورم/طفح شديد.',
];

const D3_DAILY_GENERAL_RULE = (_w: number, ageMonths: number) => {
	if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
	if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
	return '١٠٠٠ وحدة دولية يومياً';
};

const DIVITON_D_200IU_PER_DROP_RULE = (_w: number, ageMonths: number) => {
	if (ageMonths < 12) return '٢ نقط يومياً (٤٠٠ وحدة دولية)';
	if (ageMonths < 216) return '٣ نقط يومياً (٦٠٠ وحدة دولية)';
	return '٥ نقط يومياً (١٠٠٠ وحدة دولية)';
};

export const DIETARY_SUPPLEMENTS_1: Medication[] = [
	// ==========================================
	// Dietary supplements - Part 1
	// Items: 1 → 57
	// ==========================================

	// 1
	{
		id: 'devarol-s-200000iu-ampoule-ds1',
		name: 'devarol-s 200000 i.u ampoule',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '200000 IU (1 ampoule)',
		price: 34,
		matchKeywords: ['devarol', 'devarol-s', 'ديفارول', 'vitamin d', 'd3', 'cholecalciferol', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لعلاج/تصحيح نقص فيتامين د (حقن).',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('أمبول عضل جرعة واحدة أو حسب البروتوكول.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 2
	{
		id: 'feroglobin-30-caps-ds1',
		name: 'feroglobin 30 caps',
		genericName: 'folic acid & iron & zinc & copper & vitamin b12 & vitamin b6',
		concentration: '30 caps',
		price: 180,
		matchKeywords: ['feroglobin', 'فيروجلوبين', 'iron', 'folic acid', 'b12', 'zinc', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل حديد مع فوليك وفيتامينات ب ومعادن لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 3
	{
		id: 'haemojet-100mg-2ml-6-amps-ds1',
		name: 'haemojet 100mg/2ml 6 amps.',
		genericName: 'elemental iron',
		concentration: '100mg/2ml (6 amps)',
		price: 130,
		matchKeywords: ['haemojet', 'haemo jet', 'هيموجيت', 'iron injection', 'elemental iron', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد حقن لعلاج نقص الحديد حسب التشخيص والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 4
	{
		id: 'osteocare-30-tabs-ds1',
		name: 'osteocare 30 tabs',
		genericName: 'calcium carbonate & magnesium hydroxide & zinc & vitamin d3',
		concentration: '30 tabs',
		price: 150,
		matchKeywords: ['osteocare', 'اوستيوكير', 'calcium', 'vitamin d3', 'zinc', 'bones', 'عظام', '#calcium'],
		usage: 'كالسيوم/ماغنسيوم/زنك + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 5
	{
		id: 'haemojet-50mg-5ml-syrup-100ml-ds1',
		name: 'haemojet 50mg/5ml syrup 100ml',
		genericName: 'elemental iron',
		concentration: '50mg/5ml (100ml)',
		price: 54,
		matchKeywords: ['haemojet syrup', 'himojet syrup', 'هيموجيت شراب', 'iron syrup', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب حديد لعلاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول/التحاليل).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 6
	{
		id: 'limitless-ossofortin-d3-5000iu-30-tabs-ds1',
		name: 'limitless ossofortin d3 (5000 i.u.) 30 tabs.',
		genericName: 'cholecalciferol',
		concentration: '5000 IU (30 tabs)',
		price: 115,
		matchKeywords: ['ossofortin', 'ossofortin d3', 'limitless ossofortin', '5000', 'vitamin d', 'd3', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح نقص فيتامين د.',
		timing: 'مرة يومياً أو أسبوعياً حسب البروتوكول والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً لمدة قصيرة أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 7
	{
		id: 'limitless-ossofortin-d3-2000iu-30-tabs-ds1',
		name: 'limitless ossofortin d3 (2000 i.u.) 30 tabs.',
		genericName: 'cholecalciferol',
		concentration: '2000 IU (30 tabs)',
		price: 64,
		matchKeywords: ['ossofortin', 'ossofortin d3', '2000', 'vitamin d', 'd3', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 8
	{
		id: 'limitless-c-zinc-original-30-lozenges-ds1',
		name: 'limitless c-zinc original 30 lozenges',
		genericName: 'vitamin c & zinc gluconate',
		concentration: '30 lozenges',
		price: 76,
		matchKeywords: ['c-zinc', 'c zinc', 'limitless c-zinc', 'lozenges', 'zinc gluconate', 'vitamin c', 'immunity', 'مناعة', '#zinc'],
		usage: 'فيتامين C + زنك لدعم المناعة والحلق.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Lozenge',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص استحلاب واحد يومياً (يمص ببطء).'),
		warnings: ZINC_WARNINGS,
	},

	// 9
	{
		id: 'twins-d3-drops-ds1',
		name: 'twins d3 drops',
		genericName: 'vitamin d3 & vitamin k2',
		concentration: 'oral drops',
		price: 60,
		matchKeywords: ['twins d3', 'twins drops', 'توينز د٣', 'vitamin k2', 'vitamin d3', 'drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 مع K2 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 10
	{
		id: 'bone-care-0-5mcg-30-caps-ds1',
		name: 'bone care 0.5 mcg 30 caps. 30 cap.',
		genericName: 'alfacalcidol',
		concentration: '0.5 mcg (30 caps)',
		price: 129,
		matchKeywords: ['bone care 0.5', 'bone care', 'alfacalcidol', 'active vitamin d', 'عظام', '#vitamin_d'],
		usage: 'ألفاكالسيدول (فيتامين د نشط) لدعم اضطرابات العظام/الكلى؛ الجرعة حسب الكالسيوم والـ PTH.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً حسب التشخيص والتحاليل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 11
	{
		id: 'broncho-vaxom-children-3-5mg-10-sachets-ds1',
		name: 'broncho-vaxom children 3.5mg 10 sachets',
		genericName: 'bacterial lysate',
		concentration: '3.5mg (10 sachets)',
		price: 114,
		matchKeywords: ['broncho-vaxom children', 'broncho vaxom', 'برونكو فاكسوم', 'bacterial lysate', 'immunity', 'مناعة'],
		usage: 'دعم مناعة الجهاز التنفسي وتقليل تكرار العدوى؛ كيس يومياً ١٠ أيام (دورات حسب البروتوكول).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('كيس واحد يومياً لمدة ١٠ أيام (حسب البروتوكول).'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 12
	{
		id: 'broncho-vaxom-children-3-5mg-10-caps-ds1',
		name: 'broncho-vaxom children 3.5mg 10 caps',
		genericName: 'bacterial lysate',
		concentration: '3.5mg (10 caps)',
		price: 158,
		matchKeywords: ['broncho-vaxom children caps', 'broncho vaxom caps', 'برونكو فاكسوم كبسول', 'bacterial lysate', 'immunity', 'مناعة'],
		usage: 'دعم مناعة الجهاز التنفسي؛ كبسولة يومياً ١٠ أيام (دورات حسب البروتوكول).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 72,
		maxAgeMonths: 144,
		minWeight: 18,
		maxWeight: 60,
		calculationRule: fixed('كبسولة واحدة يومياً لمدة ١٠ أيام (حسب البروتوكول).'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 13
	{
		id: 'calcitron-30-caps-ds1',
		name: 'calcitron 30 caps.',
		genericName: 'manganese & ascorbic acid (vitamin c) & vitamin a (retinol)',
		concentration: '30 caps',
		price: 144,
		matchKeywords: ['calcitron', 'كالسيترون', 'manganese', 'vitamin c', 'vitamin a', 'bones', 'عظام', '#calcium'],
		usage: 'مكمل دعم العظام/الغضاريف (معادن + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 14
	{
		id: 'caldin-c-30-tabs-ds1',
		name: 'caldin c 30 tabs.',
		genericName: 'calcium & ascorbic acid (vitamin c) & magnesium & vitamin d3',
		concentration: '30 tabs',
		price: 73,
		matchKeywords: ['caldin c', 'كالدين سي', 'calcium', 'vitamin d3', 'magnesium', 'vitamin c', '#calcium', '#vitamin_d'],
		usage: 'كالسيوم + ماغنسيوم + D3 + فيتامين C لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 15
	{
		id: 'cal-mag-30-fc-tablets-ds1',
		name: 'cal-mag 30 f.c. tablets',
		genericName: 'calcium & magnesium',
		concentration: '30 F.C. tablets',
		price: 177,
		matchKeywords: ['cal-mag', 'cal mag', 'كال ماج', 'calcium', 'magnesium', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم لدعم العظام والعضلات.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 16
	{
		id: 'cal-preg-30-fc-tabs-ds1',
		name: 'cal-preg 30 f.c. tabs.',
		genericName: 'calcium',
		concentration: '30 F.C. tabs',
		price: 99,
		matchKeywords: ['cal-preg', 'cal preg', 'كال بريج', 'calcium', 'pregnancy', 'حامل', '#calcium'],
		usage: 'كالسيوم لدعم العظام (خصوصاً للحمل/الرضاعة حسب الحاجة).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 17
	{
		id: 'ferrotron-30-caps-ds1',
		name: 'ferrotron 30 caps.',
		genericName: 'copper & zinc & molybdenum & vitamin b(1), thiamine & riboflavin',
		concentration: '30 caps',
		price: 159,
		matchKeywords: ['ferrotron', 'فيروترون', 'zinc', 'copper', 'molybdenum', 'b1', 'riboflavin', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل لدعم الدم والطاقة يحتوي معادن وفيتامينات ب.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 18
	{
		id: 'hydroferrin-50mg-ml-oral-drops-30ml-ds1',
		name: 'hydroferrin 50mg/ml oral drops 30 ml',
		genericName: 'elemental iron',
		concentration: '50mg/ml (30ml)',
		price: 44,
		matchKeywords: ['hydroferrin drops', 'hydroferrin', 'هيدروفيرين نقط', 'iron drops', 'anemia', 'انيميا', '#iron'],
		usage: 'نقط حديد لعلاج أنيميا نقص الحديد للأطفال.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 144,
		minWeight: 3,
		maxWeight: 60,
		calculationRule: fixed('حسب التشخيص والتحاليل (تعتمد على الجرعة المطلوبة بالمجم).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 19
	{
		id: 'hydroferrin-50mg-syrup-100ml-ds1',
		name: 'hydroferrin 50mg syrup 100 ml',
		genericName: 'iron',
		concentration: '50mg (100ml)',
		price: 32,
		matchKeywords: ['hydroferrin syrup', 'hydroferrin', 'هيدروفيرين شراب', 'iron syrup', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب حديد لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 20
	{
		id: 'marcal-30-tablets-ds1',
		name: 'marcal 30 tablets',
		genericName: 'calcium acetate',
		concentration: '30 tablets',
		price: 90,
		matchKeywords: ['marcal', 'ماركال', 'calcium acetate', 'calcium', '#calcium'],
		usage: 'كالسيوم لدعم العظام/حسب الحاجة.',
		timing: 'مرة إلى مرتين يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص ١–٢ مرة يومياً بعد الأكل حسب احتياج الكالسيوم.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 21
	{
		id: 'octozinc-25mg-20-caps-ds1',
		name: 'octozinc 25mg 20 caps',
		genericName: 'zinc',
		concentration: '25mg (20 caps)',
		price: 30,
		matchKeywords: ['octozinc', 'octo zinc', 'اوكتوزنك', 'zinc 25', '#zinc'],
		usage: 'مكمل زنك لدعم المناعة والجلد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 22
	{
		id: 'one-alpha-0-5mcg-30-caps-ds1',
		name: 'one alpha 0.5 mcg 30 caps.',
		genericName: 'alfacalcidol',
		concentration: '0.5 mcg (30 caps)',
		price: 178,
		matchKeywords: ['one alpha 0.5', 'one alpha', 'وان الفا', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'ألفاكالسيدول (فيتامين د نشط) حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً حسب التشخيص والتحاليل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 23
	{
		id: 'one-alpha-1mcg-30-caps-ds1',
		name: 'one alpha 1 mcg 30 caps.',
		genericName: 'alfacalcidol',
		concentration: '1 mcg (30 caps)',
		price: 200,
		matchKeywords: ['one alpha 1', 'one alpha', 'وان الفا', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'ألفاكالسيدول (فيتامين د نشط) حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً حسب التشخيص والتحاليل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 24
	{
		id: 'osteocare-liquid-120ml-ds1',
		name: 'osteocare liquid 120 ml',
		genericName: 'calcium & magnesium & zinc & vitamin d3 (cholecalciferol)',
		concentration: '120ml',
		price: 65,
		matchKeywords: ['osteocare liquid', 'اوستيوكير شراب', 'calcium', 'magnesium', 'zinc', 'vitamin d3', '#calcium'],
		usage: 'شراب معادن + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 25
	{
		id: 'phara-fero-27-20-chocolate-pills-ds1',
		name: 'phara fero 27 - 20 chocolate pills',
		genericName: 'amino acids & chelated minerals & vitamins',
		concentration: '20 chocolate pills',
		price: 160,
		matchKeywords: ['phara fero 27', 'phara fero', 'فارا فيرو', 'chelated minerals', 'iron', 'chocolate', '#iron'],
		usage: 'مكمل حديد/معادن مخلبة وفيتامينات في صورة شوكولاتة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 26
	{
		id: 'sacrofer-100mg-5ml-5-amp-iv-ds1',
		name: 'sacrofer 100mg/5ml 5 amp for i.v. inj.',
		genericName: 'elemental iron',
		concentration: '100mg/5ml (5 amps)',
		price: 275,
		matchKeywords: ['sacrofer', 'ساكروفير', 'iron iv', 'iron injection', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد وريدي لعلاج نقص الحديد؛ الجرعة حسب الهيموجلوبين والوزن (بروتوكول الحقن).',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 27
	{
		id: 'sulfozinc-20mg-5ml-syrup-80ml-ds1',
		name: 'sulfozinc 20mg/5ml syrup 80ml',
		genericName: 'zinc',
		concentration: '20mg/5ml (80ml)',
		price: 15.5,
		matchKeywords: ['sulfozinc', 'سلفوزنك', 'zinc syrup', 'diarrhea', 'اسهال', '#zinc'],
		usage: 'شراب زنك لدعم المناعة وقد يُستخدم مع الإسهال حسب الإرشادات.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول).'),
		warnings: ZINC_WARNINGS,
	},

	// 28
	{
		id: 'zinctron-30-caps-ds1',
		name: 'zinctron 30 caps',
		genericName: 'copper & ascorbic acid (vitamin c) & zinc & pyridoxine hydrochloride',
		concentration: '30 caps',
		price: 126,
		matchKeywords: ['zinctron', 'زينكترون', 'zinc', 'vitamin c', 'b6', '#zinc'],
		usage: 'زنك مع فيتامين C وB6 ومعادن لدعم المناعة والجلد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 29
	{
		id: 'davalindi-200000iu-ml-1-im-amp-ds1',
		name: 'davalindi 200.000 i.u./ml 1 i.m amp.',
		genericName: 'cholecalciferol',
		concentration: '200000 IU/ml (1 IM amp)',
		price: 28,
		matchKeywords: ['davalindi', 'دافاليندي', '200000', 'vitamin d', 'd3', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة (حقن عضل) لتصحيح النقص.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('أمبول عضل جرعة واحدة أو حسب البروتوكول.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 30
	{
		id: 'davalindi-10000iu-30-tabs-ds1',
		name: 'davalindi 10.000 i.u. 30 tabs.',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (30 tabs)',
		price: 78,
		matchKeywords: ['davalindi 10000', 'دافاليندي 10000', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح النقص.',
		timing: 'أسبوعياً أو حسب بروتوكول تصحيح النقص.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 31
	{
		id: 'davalindi-5000iu-30-tabs-ds1',
		name: 'davalindi 5000 i.u. 30 tabs.',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '5000 IU (30 tabs)',
		price: 55,
		matchKeywords: ['davalindi 5000', 'دافاليندي 5000', 'vitamin d 5000', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د.',
		timing: 'مرة يومياً أو حسب بروتوكول التصحيح.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً لمدة قصيرة أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 32
	{
		id: 'bone-care-0-25mcg-30-cap-ds1',
		name: 'bone care 0.25mcg 30 cap',
		genericName: 'alfacalcidol',
		concentration: '0.25 mcg (30 caps)',
		price: 72,
		matchKeywords: ['bone care 0.25', 'bone care', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'ألفاكالسيدول (فيتامين د نشط) حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً حسب التشخيص والتحاليل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 33
	{
		id: 'cal-preg-d-30-fc-tabs-ds1',
		name: 'cal-preg d 30 f.c. tabs.',
		genericName: 'calcium & vitamin d3',
		concentration: '30 F.C. tabs',
		price: 105,
		matchKeywords: ['cal-preg d', 'cal preg d', 'كال بريج د', 'calcium', 'vitamin d3', '#calcium', '#vitamin_d'],
		usage: 'كالسيوم + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 34
	{
		id: 'osteo-zad-syrup-120ml-ds1',
		name: 'osteo zad syrup 120 ml',
		genericName: 'calcium & magnesium & zinc & vitamin d3',
		concentration: '120ml',
		price: 80,
		matchKeywords: ['osteo zad', 'اوستيو زاد', 'calcium', 'magnesium', 'zinc', 'vitamin d3', '#calcium'],
		usage: 'شراب دعم العظام للأطفال (كالسيوم + معادن + D3).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 35
	{
		id: 'davalindi-1000iu-100-tabs-ds1',
		name: 'davalindi 1000 i.u. 100 tabs.',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '1000 IU (100 tabs)',
		price: 77,
		matchKeywords: ['davalindi 1000', 'دافاليندي 1000', 'vitamin d 1000', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 36
	{
		id: 'davalindi-200000iu-ml-2-amp-im-ds1',
		name: 'davalindi 200.000 i.u./ml 1 i.m 2 amp.',
		genericName: 'cholecalciferol',
		concentration: '200000 IU/ml (2 amp)',
		price: 56,
		matchKeywords: ['davalindi 200000 2 amp', 'دافاليندي 200000', 'vitamin d injection', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة (حقن عضل) لتصحيح النقص.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('أمبول عضل جرعة واحدة أو حسب البروتوكول.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 37
	{
		id: 'diviton-d-forte-10000iu-ml-oral-drops-20ml-ds1',
		name: 'diviton-d forte 10.000 i.u./ml oral drops 20 ml',
		genericName: 'cholecalciferol',
		concentration: '10000 IU/ml (20ml)',
		price: 93,
		matchKeywords: ['diviton d forte', 'diviton-d forte', 'ديفيتون د فورت', 'vitamin d drops', '#vitamin_d'],
		usage: 'نقط D3 عالية التركيز لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'مرة يومياً أو حسب بروتوكول التصحيح.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('الجرعة تعتمد على تركيز (IU/نقطة) والبروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 38
	{
		id: 'euronemia-100mg-5ml-5-amp-iv-inf-ds1',
		name: 'euronemia 100mg/5ml 5 amp for i.v. or inf.',
		genericName: 'elemental iron & iron sucrose',
		concentration: '100mg/5ml (5 amps)',
		price: 275,
		matchKeywords: ['euronemia', 'يورونيميا', 'iron sucrose', 'iv iron', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد سكروز وريدي لعلاج نقص الحديد؛ الجرعة حسب الهيموجلوبين والوزن (بروتوكول الحقن).',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 39
	{
		id: 'feroglobin-liquid-120ml-ds1',
		name: 'feroglobin liquid 120 ml',
		genericName: 'vitamin b(1), thiamine & riboflavin,vitamin b2 & pyridoxine',
		concentration: '120ml',
		price: 65,
		matchKeywords: ['feroglobin liquid', 'feroglobin syrup', 'فيروجلوبين شراب', 'b vitamins', 'iron', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب مكمل للدم والطاقة (قد يحتوي مكونات داعمة للحديد/فيتامينات ب حسب العبوة).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 40
	{
		id: 'ferroduonal-30-cap-ds1',
		name: 'ferroduonal 30 cap',
		genericName: 'ferrous (ii) glycine sulphate complex',
		concentration: '30 caps',
		price: 135,
		matchKeywords: ['ferroduonal', 'فيروديونال', 'ferrous glycine sulphate', 'iron', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد (مركب جلايسين سلفات) لعلاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 41
	{
		id: 'ferroduonal-gyn-30-caps-ds1',
		name: 'ferroduonal gyn 30 caps.',
		genericName: 'ferrous glycine sulphate complex & folic acid',
		concentration: '30 caps',
		price: 39,
		matchKeywords: ['ferroduonal gyn', 'فيروديونال جين', 'iron', 'folic acid', 'pregnancy', 'حامل', '#iron'],
		usage: 'حديد + فوليك لدعم الدم؛ مناسب للحمل بجرعة حديد يومية (٧٥–١٢٠ مجم عنصري) حسب الهيموجلوبين.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 42
	{
		id: 'ferrotron-20-caps-ds1',
		name: 'ferrotron 20 caps',
		genericName: 'copper & zinc & molybdenum & vitamin b1 (thiamine) & ribofl',
		concentration: '20 caps',
		price: 106,
		matchKeywords: ['ferrotron 20', 'ferrotron', 'فيروترون', 'zinc', 'copper', 'b1', '#iron'],
		usage: 'مكمل لدعم الدم والطاقة يحتوي معادن وفيتامينات ب.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 43
	{
		id: 'hydroferrin-100mg-2ml-3-amp-ds1',
		name: 'hydroferrin 100mg/2ml 3 amp.',
		genericName: 'iron',
		concentration: '100mg/2ml (3 amp)',
		price: 33,
		matchKeywords: ['hydroferrin amp', 'hydroferrin injection', 'هيدروفيرين حقن', 'iron injection', '#iron'],
		usage: 'حديد حقن لعلاج نقص الحديد؛ الجرعة حسب الهيموجلوبين والوزن (بروتوكول الحقن).',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 44
	{
		id: 'immuno-mash-30-fc-tabs-ds1',
		name: 'immuno-mash 30 f.c. tabs',
		genericName: 'vitamin c & zinc gluconate',
		concentration: '30 F.C. tabs',
		price: 120,
		matchKeywords: ['immuno-mash', 'immunomash', 'ايمينو ماش', 'vitamin c', 'zinc gluconate', 'immunity', 'مناعة', '#zinc'],
		usage: 'فيتامين C + زنك لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 45
	{
		id: 'irospect-20-pieces-ds1',
		name: 'irospect 20 pieces',
		genericName: 'iron & zinc & vitamin d3 & copper & vitamin a & vitamin',
		concentration: '20 pieces',
		price: 140,
		matchKeywords: ['irospect', 'ايروسبكت', 'iron', 'zinc', 'vitamin d3', 'immunity', 'مناعة', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل متعدد (حديد + زنك + فيتامينات) لدعم الدم والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 46
	{
		id: 'kalobin-oral-drops-20ml-ds1',
		name: 'kalobin oral drops 20 ml',
		genericName: 'pelargonium sidoides dry extract (1:8-10)',
		concentration: '20ml',
		price: 70,
		matchKeywords: ['kalobin drops', 'kalobin', 'كالوبين', 'pelargonium sidoides', 'immunity', 'برد', 'cold', 'cough'],
		usage: 'مستخلص بلارجونيوم لدعم أعراض نزلات البرد/الحلق (نقط).',
		timing: '3 مرات يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٢٠ نقطة ٣ مرات يومياً' : '٣٠ نقطة ٣ مرات يومياً'),
		warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'أوقفه إذا ظهر طفح/حساسية.'],
	},

	// 47
	{
		id: 'octozinc-25mg-100x10-caps-ds1',
		name: 'octozinc 25 mg 100*10 caps.',
		genericName: 'zinc',
		concentration: '25mg (bulk pack)',
		price: 850,
		matchKeywords: ['octozinc 25 bulk', 'octozinc', 'zinc 25', '#zinc'],
		usage: 'مكمل زنك لدعم المناعة (عبوة كبيرة).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 48
	{
		id: 'one-alpha-0-25mcg-30-caps-ds1',
		name: 'one alpha 0.25mcg 30 caps',
		genericName: 'alfacalcidol',
		concentration: '0.25 mcg (30 caps)',
		price: 108,
		matchKeywords: ['one alpha 0.25', 'one alpha', 'وان الفا', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'ألفاكالسيدول (فيتامين د نشط) حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً حسب التشخيص والتحاليل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 49
	{
		id: 'phara-fero-27-plus-20-chocolate-pills-ds1',
		name: 'phara fero 27 plus - 20 chocolate pills',
		genericName: 'lactoferrin & amino acids & chelated minerals & vitamins',
		concentration: '20 chocolate pills',
		price: 185,
		matchKeywords: ['phara fero 27 plus', 'phara fero plus', 'lactoferrin', 'iron', 'chocolate', '#iron'],
		usage: 'مكمل يحتوي لاكتوفرّين ومعادن/فيتامينات لدعم الدم.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 50
	{
		id: 'pravotin-100mg-7-sachets-ds1',
		name: 'pravotin 100mg 7 sachets',
		genericName: 'lactoferrin',
		concentration: '100mg (7 sachets)',
		price: 55,
		matchKeywords: ['pravotin 7', 'pravotin', 'براڤوتين', 'lactoferrin', 'iron support', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ٧ أيام.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 51
	{
		id: 'pravotin-100mg-14-sachets-ds1',
		name: 'pravotin 100mg 14 sachets',
		genericName: 'lactoferrin',
		concentration: '100mg (14 sachets)',
		price: 180,
		matchKeywords: ['pravotin 14', 'pravotin', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 52
	{
		id: 'pravotin-100mg-30-sachets-ds1',
		name: 'pravotin 100mg 30 sachets',
		genericName: 'lactoferrin',
		concentration: '100mg (30 sachets)',
		price: 360,
		matchKeywords: ['pravotin 30', 'pravotin', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ٣٠ يوم.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 53
	{
		id: 'ziafer-30-pieces-ds1',
		name: 'ziafer 30 pieces',
		genericName: 'iron & folic acid & vitamin c & vitamin b6 & vitamin b12 & zi',
		concentration: '30 pieces',
		price: 130,
		matchKeywords: ['ziafer', 'زيافير', 'iron', 'folic acid', 'vitamin c', 'b6', 'b12', 'zinc', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك + فيتامينات ومعادن لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 54
	{
		id: 'zinc-origin-0-2gm-100ml-syrup-120ml-ds1',
		name: 'zinc origin 0.2gm/100ml syrup 120 ml',
		genericName: 'zinc',
		concentration: '0.2g/100ml (120ml)',
		price: 31,
		matchKeywords: ['zinc origin', 'زينك اوريجن', 'zinc syrup', '#zinc'],
		usage: 'شراب زنك لدعم المناعة للأطفال.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول).'),
		warnings: ZINC_WARNINGS,
	},

	// 55
	{
		id: 'calcitron-20-caps-ds1',
		name: 'calcitron 20 caps.',
		genericName: 'amino acids & chelated minerals & vitamins',
		concentration: '20 caps',
		price: 96,
		matchKeywords: ['calcitron 20', 'calcitron', 'كالسيترون', 'chelated minerals', 'bones', 'عظام', '#calcium'],
		usage: 'مكمل دعم العظام/الغضاريف (معادن مخلبة + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 56
	{
		id: 'decapreno-200000iu-1ml-solution-im-oral-2-amp-ds1',
		name: 'decapreno 200.000 i.u / 1 ml sol. for i.m / oral 2 a...',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '200000 IU/1ml (2 amps)',
		price: 58,
		matchKeywords: ['decapreno', 'ديكابرينو', 'vitamin d3', '200000', 'solution', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة (محلول) لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Solution',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة واحدة أو حسب البروتوكول (عضل/فموي حسب العبوة).'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 57
	{
		id: 'diviton-d-200iu-drop-oral-drops-10ml-ds1',
		name: 'diviton-d 200 i.u./drop oral drops 10 ml',
		genericName: 'cholecalciferol',
		concentration: '200 IU/drop (10ml)',
		price: 40,
		matchKeywords: ['diviton d 200', 'diviton-d', 'ديفيتون د', '200 iu per drop', 'vitamin d drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: DIVITON_D_200IU_PER_DROP_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},
];

export const DIETARY_SUPPLEMENTS_2: Medication[] = [
	// ==========================================
	// Dietary supplements - Part 2
	// Items: 58 → 110
	// ==========================================

	// 58
	{
		id: 'vitonex-30-caps-ds2',
		name: 'vitonex 30 caps.',
		genericName: 'lactoferrin & zinc & vitamin c & vitamin d & vitamin b complex',
		concentration: '30 caps',
		price: 75,
		matchKeywords: ['vitonex', 'فيتونكس', 'lactoferrin', 'iron support', 'zinc', 'vitamin c', 'vitamin d', '#iron'],
		usage: 'لاكتوفرّين + فيتامينات ومعادن لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 59
	{
		id: 'vitonex-20-caps-ds2',
		name: 'vitonex 20 caps.',
		genericName: 'iron & folic acid & vitamin c & vitamin b12',
		concentration: '20 caps',
		price: 100,
		matchKeywords: ['vitonex 20', 'vitonex', 'فيتونكس', 'iron', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك + B12 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 60
	{
		id: 'joy-extra-30-tabs-ds2',
		name: 'joy extra 30 tabs.',
		genericName: 'iron & zinc & vitamin c & vitamin b complex & folic acid',
		concentration: '30 tabs',
		price: 135,
		matchKeywords: ['joy extra', 'joy', 'جوي اكسترا', 'iron', 'zinc', 'folic acid', 'vitamin c', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل متعدد لدعم الدم والطاقة (حديد + زنك + فوليك + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 61
	{
		id: 'sulfozinc-10mg-5ml-susp-80ml-ds2',
		name: 'sulfozinc 10mg/5ml pd. for susp. 80ml',
		genericName: 'zinc',
		concentration: '10mg/5ml (80ml)',
		price: 22,
		matchKeywords: ['sulfozinc 10', 'sulfozinc', 'سلفوزنك', 'zinc suspension', '#zinc'],
		usage: 'معلق زنك للأطفال لدعم المناعة وقد يُستخدم مع الإسهال حسب الإرشادات.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Suspension',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول).'),
		warnings: ZINC_WARNINGS,
	},

	// 62
	{
		id: 'd-dep-1000iu-30-caps-ds2',
		name: 'd.dep 1000 i.u. 30 caps.',
		genericName: 'cholecalciferol',
		concentration: '1000 IU (30 caps)',
		price: 200,
		matchKeywords: ['d.dep 1000', 'd dep 1000', 'دي ديب 1000', 'vitamin d', 'd3', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 63
	{
		id: 'alfacalcidol-2mcg-ml-oral-drops-10ml-ds2',
		name: 'alfacalcidol 2mcg/ml oral dps. 10 ml',
		genericName: 'alfacalcidol',
		concentration: '2mcg/ml (10ml)',
		price: 86,
		matchKeywords: ['alfacalcidol drops 10', 'alfacalcidol', 'الفاكالسيدول', 'active vitamin d', '#vitamin_d'],
		usage: 'فيتامين د نشط (ألفاكالسيدول) نقط للفم حسب التشخيص والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.CALCIUM_GROWTH,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('الجرعة حسب الكالسيوم والـ PTH ووظائف الكلى؛ راقب الكالسيوم كل ٢–٤ أسابيع.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 64
	{
		id: 'alfacalcidol-2mcg-ml-oral-drops-20ml-ds2',
		name: 'alfacalcidol 2mcg/ml oral dps. 20 ml',
		genericName: 'alfacalcidol',
		concentration: '2mcg/ml (20ml)',
		price: 156,
		matchKeywords: ['alfacalcidol drops 20', 'alfacalcidol', 'الفاكالسيدول', 'active vitamin d', '#vitamin_d'],
		usage: 'فيتامين د نشط (ألفاكالسيدول) نقط للفم حسب التشخيص والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.CALCIUM_GROWTH,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('الجرعة حسب الكالسيوم والـ PTH ووظائف الكلى؛ راقب الكالسيوم كل ٢–٤ أسابيع.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 65
	{
		id: 'alfacareno-2mcg-ml-oral-drops-10ml-ds2',
		name: 'alfacareno 2mcg/ml oral drops. 10 ml',
		genericName: 'alfacalcidol',
		concentration: '2mcg/ml (10ml)',
		price: 152,
		matchKeywords: ['alfacareno', 'الفاكارينو', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'ألفاكالسيدول (فيتامين د نشط) نقط للفم؛ الجرعة حسب الكالسيوم والـ PTH ووظائف الكلى.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.CALCIUM_GROWTH,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 1200,
		minWeight: 3,
		maxWeight: 250,
		calculationRule: fixed('الجرعة حسب الكالسيوم والـ PTH ووظائف الكلى؛ راقب الكالسيوم كل ٢–٤ أسابيع.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 66
	{
		id: 'broncho-vaxom-adults-7mg-10-caps-ds2',
		name: 'broncho-vaxom adults 7mg 10 caps',
		genericName: 'bacterial lysate',
		concentration: '7mg (10 caps)',
		price: 217,
		matchKeywords: ['broncho-vaxom adults', 'broncho vaxom adults', 'برونكو فاكسوم adults', 'bacterial lysate', 'immunity', 'مناعة'],
		usage: 'دعم مناعة الجهاز التنفسي وتقليل تكرار العدوى؛ كيس يومياً ١٠ أيام (دورات حسب البروتوكول).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً لمدة ١٠ أيام (حسب البروتوكول).'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 67
	{
		id: 'calcimate-500mg-20-chewable-tabs-ds2',
		name: 'calcimate 500mg 20 chew. tab. (n/a)',
		genericName: 'calcium carbonate',
		concentration: '500mg (20 chewable tabs)',
		price: 6,
		matchKeywords: ['calcimate 20', 'calcimate', 'كالسيمايت', 'calcium carbonate', 'chew', '#calcium'],
		usage: 'كالسيوم كربونات لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 68
	{
		id: 'calcimate-500mg-12-caps-ds2',
		name: 'calcimate 500 mg 12 caps.',
		genericName: 'calcium carbonate',
		concentration: '500mg (12 caps)',
		price: 20,
		matchKeywords: ['calcimate 12', 'calcimate', 'كالسيمايت', 'calcium carbonate', '#calcium'],
		usage: 'كالسيوم كربونات لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 69
	{
		id: 'caltonex-20-tabs-ds2',
		name: 'caltonex 20 tabs.',
		genericName: 'calcium & vitamin d3 & magnesium & zinc',
		concentration: '20 tabs',
		price: 84,
		matchKeywords: ['caltonex', 'كالتونكس', 'calcium', 'vitamin d3', 'magnesium', 'zinc', '#calcium'],
		usage: 'كالسيوم + D3 + ماغنسيوم + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 70
	{
		id: 'osavidin-300000iu-ml-im-amp-ds2',
		name: 'osavidin 300,000 i.u/ ml i.m. amp.',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '300000 IU/ml (1 IM amp)',
		price: 38,
		matchKeywords: ['osavidin 300000', 'osavidin', 'اوسافيدين', 'vitamin d injection', '300000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة (حقن عضل) لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('أمبول عضل جرعة واحدة أو حسب البروتوكول.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 71
	{
		id: 'lokaglobin-30ml-oral-drops-ds2',
		name: 'lokaglobin 30 ml drops',
		genericName: 'iron & vitamin c & vitamin b12 & folic acid',
		concentration: '30ml',
		price: 60,
		matchKeywords: ['lokaglobin', 'لوكا جلو بين', 'iron drops', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'نقط حديد مع فوليك وB12 للأطفال لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 144,
		minWeight: 3,
		maxWeight: 60,
		calculationRule: fixed('حسب التشخيص والتحاليل (تعتمد على الجرعة المطلوبة بالمجم وتركيز العبوة).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 72
	{
		id: 'enrich-oral-drops-30ml-ds2',
		name: 'enrich oral drops 30 ml',
		genericName: 'iron',
		concentration: '30ml',
		price: 40,
		matchKeywords: ['enrich drops', 'enrich', 'اينريتش نقط', 'iron drops', 'anemia', 'انيميا', '#iron'],
		usage: 'نقط حديد للأطفال لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 144,
		minWeight: 3,
		maxWeight: 60,
		calculationRule: fixed('حسب التشخيص والتحاليل (تعتمد على الجرعة المطلوبة بالمجم).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 73
	{
		id: 'extreme-axiona-chocolate-20-soft-chews-ds2',
		name: 'extreme axiona chocolate 20 soft chews pieces',
		genericName: 'calcium & vitamin d3 & vitamin k',
		concentration: '20 soft chews',
		price: 75,
		matchKeywords: ['axiona', 'extreme axiona', 'اكسيوونا', 'calcium', 'vitamin d3', 'vitamin k', 'chews', '#calcium'],
		usage: 'كالسيوم + D3 + K لدعم العظام (قطع قابلة للمضغ).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 74
	{
		id: 'lipoferric-folic-30-caps-ds2',
		name: 'lipoferric folic 30 caps.',
		genericName: 'liposomal iron & vitamin c & folic acid & vitamin b6 & vitamin b12',
		concentration: '30 caps',
		price: 145,
		matchKeywords: ['lipoferric', 'lipoferric folic', 'ليبو فيريك', 'liposomal iron', 'folic acid', 'b6', 'b12', '#iron'],
		usage: 'حديد ليبوسومال + فوليك وفيتامينات لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 75
	{
		id: 'geo-pota-k-600-sr-30-tabs-ds2',
		name: 'geo pota-k 600 sr 30 tabs.',
		genericName: 'potassium chloride',
		concentration: '600mg SR (30 tabs)',
		price: 60,
		matchKeywords: ['geo pota-k', 'pota-k', 'بوتا ك', 'potassium', 'k chloride'],
		usage: 'مكمل بوتاسيوم (كلوريد البوتاسيوم) حسب احتياج/تحاليل والبروتوكول.',
		timing: 'الجرعة حسب مستوى البوتاسيوم ووظائف الكلى (عادة قرص–قرصين يومياً).',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Prolonged Release Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('الجرعة حسب البوتاسيوم والـ GFR: راقب البوتاسيوم قبل البدء وكل ١–٤ أسابيع.'),
		warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب تهيج المعدة؛ يفضل بعد الأكل.'],
	},

	// 76
	{
		id: 'immuguard-7-sachets-ds2',
		name: 'immuguard 7 sachets',
		genericName: 'high concentration bovine colostrum & vitamins & minerals',
		concentration: '7 sachets',
		price: 115,
		matchKeywords: ['immuguard 7', 'immuguard', 'ايميوجارد', 'colostrum', 'immunity', 'مناعة'],
		usage: 'كولوستروم + فيتامينات/معادن لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ٧ أيام.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 77
	{
		id: 'immulant-20-caps-ds2',
		name: 'immulant 20 caps',
		genericName: 'echinaceae purpurea',
		concentration: '20 caps',
		price: 45,
		matchKeywords: ['immulant', 'ايميولانت', 'echinacea', 'immunity', 'مناعة'],
		usage: 'إشنيسيا لدعم المناعة وتقليل مدة نزلات البرد (مكمل).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 78
	{
		id: 'immulant-plus-20-caps-ds2',
		name: 'immulant plus 20 caps',
		genericName: 'echinacea & goldenseal, hydrastis canadensis',
		concentration: '20 caps',
		price: 45,
		matchKeywords: ['immulant plus', 'immulant+', 'ايميولانت بلس', 'echinacea', 'goldenseal', 'hydrastis', 'immunity'],
		usage: 'مزيج أعشاب لدعم المناعة (إشنيسيا + جولدن سيل).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 79
	{
		id: 'intrafer-b-30-tablets-ds2',
		name: 'intrafer b 30 tablets',
		genericName: 'folic acid & iron & vitamin c & vitamin b12 & histidin',
		concentration: '30 tablets',
		price: 135,
		matchKeywords: ['intrafer b', 'intrafer', 'انترافر', 'iron', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك + B12 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 80
	{
		id: 'intrafer-30-tablets-ds2',
		name: 'intrafer 30 tablets',
		genericName: 'folic acid & iron',
		concentration: '30 tablets',
		price: 45,
		matchKeywords: ['intrafer', 'انترافر', 'iron', 'folic acid', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 81
	{
		id: 'maxical-30-tabs-ds2',
		name: 'maxical 30 tabs',
		genericName: 'calcium carbonate & vitamin d3',
		concentration: '30 tabs',
		price: 120,
		matchKeywords: ['maxical', 'ماكسيكال', 'calcium', 'vitamin d3', '#calcium', '#vitamin_d'],
		usage: 'كالسيوم + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 82
	{
		id: 'maxical-d-suspension-120ml-ds2',
		name: 'maxical d suspension 120 ml',
		genericName: 'calcium & vitamin d3 (cholecalciferol) & magnesium',
		concentration: '120ml',
		price: 65,
		matchKeywords: ['maxical d', 'maxical suspension', 'ماكسيكال د', 'calcium', 'vitamin d3', 'magnesium', '#calcium'],
		usage: 'معلق كالسيوم + D3 + ماغنسيوم لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Suspension',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 83
	{
		id: 'dixvit-10000iu-30-tabs-ds2',
		name: 'dixvit 10.000 i.u. 30 tabs.',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (30 tabs)',
		price: 110,
		matchKeywords: ['dixvit 10000', 'dixvit', 'ديكسفيت', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 84
	{
		id: 'ossofortin-original-5000iu-30-tabs-ds2',
		name: 'ossofortin original d3 (5000 i.u.) 30 tabs',
		genericName: 'ergocalciferol',
		concentration: '5000 IU (30 tabs)',
		price: 92,
		matchKeywords: ['ossofortin original', 'ossofortin', 'اوسوفورتين', 'ergocalciferol', 'vitamin d', 'd2', '#vitamin_d'],
		usage: 'فيتامين D (إرجوكالسيفيرول) لدعم/علاج نقص فيتامين د.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً لمدة قصيرة أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 85
	{
		id: 'osavidin-100000iu-ml-im-amp-ds2',
		name: 'osavidin 100,000 i.u/ ml i.m. amp.',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '100000 IU/ml (1 IM amp)',
		price: 28,
		matchKeywords: ['osavidin 100000', 'osavidin', 'اوسافيدين', 'vitamin d injection', '100000', '#vitamin_d'],
		usage: 'فيتامين D3 (حقن عضل) لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('أمبول عضل جرعة واحدة أو حسب البروتوكول.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 86
	{
		id: 'ampofer-20mg-ml-5-amp-iv-ds2',
		name: 'ampofer 20mg/ml 5 amp. for i.v. inj./inf.',
		genericName: 'iron',
		concentration: '20mg/ml (5 amps)',
		price: 275,
		matchKeywords: ['ampofer', 'امبوفر', 'iv iron', 'iron injection', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد وريدي لعلاج نقص الحديد؛ الجرعة حسب الهيموجلوبين والوزن (بروتوكول الحقن).',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 87
	{
		id: 'xahaem-20-caps-ds2',
		name: 'xahaem 20 caps.',
		genericName: 'iron bisglycinate & folic acid & vitamin c & vitamin b12',
		concentration: '20 caps',
		price: 98,
		matchKeywords: ['xahaem', 'xahaem 20', 'iron bisglycinate', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد بيسجليسينات + فوليك + B12 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 88
	{
		id: 'calcao-20-chew-pieces-ds2',
		name: 'calcao 20 chew. pieces',
		genericName: 'calcium & vitamin d3 & vitamin k',
		concentration: '20 chew pieces',
		price: 78,
		matchKeywords: ['calcao', 'كالكاو', 'calcium', 'vitamin d3', 'vitamin k', '#calcium'],
		usage: 'كالسيوم + D3 + K لدعم العظام (قطع للمضغ).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 89
	{
		id: 'calcium-d3f-30-tab-ds2',
		name: 'calcium d3f 30 tab.',
		genericName: 'sodium fluoride & calcium & vitamin d3 (cholecalciferol)',
		concentration: '30 tabs',
		price: 51,
		matchKeywords: ['calcium d3f', 'd3f', 'calcium', 'vitamin d3', 'fluoride', '#calcium'],
		usage: 'كالسيوم + D3 (مع فلورايد) لدعم العظام والأسنان.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 90
	{
		id: 'caldin-zinc-susp-120ml-ds2',
		name: 'caldin zinc susp. 120 ml',
		genericName: 'calcium carbonate & magnesium hydroxide & zinc',
		concentration: '120ml',
		price: 55,
		matchKeywords: ['caldin zinc', 'caldin', 'كالدين زنك', 'calcium', 'magnesium', 'zinc', '#calcium'],
		usage: 'معلق كالسيوم + ماغنسيوم + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Suspension',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS],
	},

	// 91
	{
		id: 'cal-d-mag-30-chocolate-pieces-ds2',
		name: 'cal-d-mag 30 chocolate pieces',
		genericName: 'calcium carbonate & vitamin d3 & magnesium',
		concentration: '30 chocolate pieces',
		price: 147,
		matchKeywords: ['cal-d-mag', 'cal d mag', 'كال دي ماج', 'calcium', 'vitamin d3', 'magnesium', 'chocolate', '#calcium'],
		usage: 'كالسيوم + D3 + ماغنسيوم (قطع شوكولاتة) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 92
	{
		id: 'd-dep-5000iu-30-caps-ds2',
		name: 'd.dep 5000 i.u. 30 caps',
		genericName: 'cholecalciferol',
		concentration: '5000 IU (30 caps)',
		price: 250,
		matchKeywords: ['d.dep 5000', 'd dep 5000', 'دي ديب 5000', 'vitamin d', 'd3', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً لمدة قصيرة أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 93
	{
		id: 'l-c-plus-oral-drops-10ml-ds2',
		name: 'l.c plus oral drops 10 ml',
		genericName: 'lactobacillus & vitamin d3',
		concentration: '10ml',
		price: 120,
		matchKeywords: ['l.c plus', 'lc plus', 'ال سي بلس', 'lactobacillus', 'probiotic', 'vitamin d3', '#vitamin_d'],
		usage: 'بروبيوتك + فيتامين D3 لدعم الهضم والمناعة (نقط).',
		timing: 'مرة يومياً.',
		category: Category.PROBIOTICS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: fixed('حسب إرشادات العبوة (عادةً جرعة يومية واحدة).'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 94
	{
		id: 'enrich-syrup-100ml-ds2',
		name: 'enrich syrup 100 ml',
		genericName: 'iron',
		concentration: '100ml',
		price: 34,
		matchKeywords: ['enrich syrup', 'enrich', 'اينريتش شراب', 'iron syrup', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب حديد لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 95
	{
		id: 'feramix-fe-20-tab-ds2',
		name: 'feramix fe 20 tab',
		genericName: 'ferrous fumarate & folic acid & vitamin c & zinc & copper',
		concentration: '20 tabs',
		price: 110,
		matchKeywords: ['feramix', 'feramix fe', 'فيراميكس', 'iron', 'folic acid', 'zinc', 'vitamin c', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل حديد مع فوليك وفيتامين C ومعادن لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 96
	{
		id: 'golden-fer-100mg-30-chewable-tabs-ds2',
		name: 'golden fer 100 mg 30 chew. tablets',
		genericName: 'iron',
		concentration: '100mg (30 chewable tabs)',
		price: 40.5,
		matchKeywords: ['golden fer', 'جولدن فير', 'iron', 'chew', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد قابل للمضغ لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 97
	{
		id: 'golden-fer-f-30-chewable-tabs-ds2',
		name: 'golden fer-f 30 chew. tabs.',
		genericName: 'iron & folic acid',
		concentration: '30 chewable tabs',
		price: 40.5,
		matchKeywords: ['golden fer-f', 'golden fer f', 'جولدن فير اف', 'iron', 'folic acid', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك (قابل للمضغ) لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 98
	{
		id: 'hi-cal-1200mg-5ml-syrup-100ml-ds2',
		name: 'hi-cal 1200mg/5ml syrup 100ml',
		genericName: 'calcium',
		concentration: '1200mg/5ml (100ml)',
		price: 50,
		matchKeywords: ['hi-cal', 'hi cal', 'هاي كال', 'calcium syrup', '#calcium'],
		usage: 'شراب كالسيوم لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: CALCIUM_WARNINGS,
	},

	// 99
	{
		id: 'immuguard-14-sachets-ds2',
		name: 'immuguard 14 sachets',
		genericName: 'high concentration bovine colostrum & vitamins & minerals',
		concentration: '14 sachets',
		price: 195,
		matchKeywords: ['immuguard 14', 'immuguard', 'colostrum', 'immunity', 'مناعة'],
		usage: 'كولوستروم + فيتامينات/معادن لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 100
	{
		id: 'irolamin-30-caps-ds2',
		name: 'irolamin 30 caps.',
		genericName: 'polysaccharide iron complex & folic acid & vitamin b12',
		concentration: '30 caps',
		price: 138,
		matchKeywords: ['irolamin', 'ايرولامين', 'iron complex', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'مركب حديد + فوليك + B12 لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 101
	{
		id: 'ironoglor-max-30-tabs-ds2',
		name: 'ironoglor-max 30 tabs',
		genericName: 'ferrous bisglycinate chelate & folic acid & vitamin b12',
		concentration: '30 tabs',
		price: 195,
		matchKeywords: ['ironoglor-max', 'ironoglor', 'ايرونوجلور', 'bisglycinate', 'folic acid', 'b12', '#iron'],
		usage: 'حديد بيسجليسينات + فوليك + B12 لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 102
	{
		id: 'irontec-20-chew-pieces-ds2',
		name: 'irontec 20 chew. pieces',
		genericName: 'iron & zinc & folic acid',
		concentration: '20 chew pieces',
		price: 85,
		matchKeywords: ['irontec', 'ايرونتك', 'iron', 'zinc', 'folic acid', 'chew', '#iron'],
		usage: 'حديد + زنك + فوليك (قطع للمضغ) لدعم الدم.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 103
	{
		id: 'itoferrose-100mg-5ml-5-amp-iv-ds2',
		name: 'itoferrose 100mg/5ml 5 amp. for iv inj. or inf.',
		genericName: 'iron',
		concentration: '100mg/5ml (5 amps)',
		price: 255,
		matchKeywords: ['itoferrose', 'ايتوفرروز', 'iv iron', 'iron injection', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد وريدي لعلاج نقص الحديد؛ الجرعة حسب الهيموجلوبين والوزن (بروتوكول الحقن).',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 104
	{
		id: 'irospect-syrup-120ml-ds2',
		name: 'irospect syrup 120 ml',
		genericName: 'iron & zinc & vitamin d3 & copper & vitamin a & vitamin b complex',
		concentration: '120ml',
		price: 75,
		matchKeywords: ['irospect syrup', 'irospect', 'ايروسبكت شراب', 'iron', 'zinc', 'vitamin d3', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب مكمل متعدد (حديد + زنك + فيتامينات) لدعم الدم والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 105
	{
		id: 'pravotin-plus-30-caps-ds2',
		name: 'pravotin plus 30 caps',
		genericName: 'lactoferrin',
		concentration: '30 caps',
		price: 390,
		matchKeywords: ['pravotin plus', 'pravotin', 'براڤوتين', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 106
	{
		id: 'potassium-m-3-3gm-100ml-syrup-120ml-ds2',
		name: 'potassium m 3.3gm/ 100ml syrup 120ml',
		genericName: 'potassium chloride',
		concentration: '3.3g/100ml (120ml)',
		price: 29,
		matchKeywords: ['potassium m', 'بوتاسيوم ام', 'potassium syrup', 'k chloride'],
		usage: 'شراب بوتاسيوم (كلوريد البوتاسيوم) حسب احتياج/تحاليل والبروتوكول.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('الجرعة حسب البوتاسيوم والـ GFR: راقب البوتاسيوم قبل البدء وكل ١–٤ أسابيع.'),
		warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب تهيج المعدة؛ يفضل بعد الأكل.'],
	},

	// 107
	{
		id: 'promax-plus-12-sachets-20gm-ds2',
		name: 'promax plus 12 sachets 20 gm',
		genericName: 'pure protein',
		concentration: '20gm (12 sachets)',
		price: 150,
		matchKeywords: ['promax plus', 'promax', 'بروماكس', 'protein', 'dietary supplement'],
		usage: 'مكمل بروتين لدعم الاحتياج الغذائي (حسب الهدف الغذائي).',
		timing: 'مرة يومياً أو حسب الاحتياج.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً (يمكن زيادته حسب الاحتياج الغذائي/الرياضة).'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 108
	{
		id: 'maxical-plus-30-tabs-ds2',
		name: 'maxical plus 30 tabs.',
		genericName: 'calcium & magnesium & vitamin d3 & zinc',
		concentration: '30 tabs',
		price: 135,
		matchKeywords: ['maxical plus', 'maxical', 'ماكسيكال بلس', 'calcium', 'magnesium', 'vitamin d3', 'zinc', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 109
	{
		id: 'd-dep-10000iu-30-caps-ds2',
		name: 'd.dep 10000 i.u. 30 caps',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (30 caps)',
		price: 300,
		matchKeywords: ['d.dep 10000', 'd dep 10000', 'دي ديب 10000', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح النقص؛ الجرعة حسب مستوى D والتحاليل.',
		timing: 'الجرعة/التكرار حسب التحاليل والبروتوكول.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة عالية: الجرعة والمدة تُحدد حسب التحاليل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 110
	{
		id: 'sansoimune-syrup-200ml-ds2',
		name: 'sansoimune syrup 200 ml',
		genericName: 'echinaceae purpurea & ascorbic acid (vitamin c) & zinc',
		concentration: '200ml',
		price: 160,
		matchKeywords: ['sansoimune', 'سانسوايميون', 'echinacea', 'vitamin c', 'zinc', 'immunity', 'مناعة', '#zinc'],
		usage: 'شراب لدعم المناعة (إشنيسيا + فيتامين C + زنك).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 24,
		maxAgeMonths: 144,
		minWeight: 10,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...GENERAL_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},
];

// Backward-compatible export used by constants.ts
export const DIETARY_SUPPLEMENTS: Medication[] = [
	...DIETARY_SUPPLEMENTS_1,
	...DIETARY_SUPPLEMENTS_2,
	...DIETARY_SUPPLEMENTS_3,
	...DIETARY_SUPPLEMENTS_4,
	...DIETARY_SUPPLEMENTS_5,
	...DIETARY_SUPPLEMENTS_6,
];

