import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
	'لا تتجاوز الجرعة اليومية الموصى بها.',
	'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
	'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين D أو A أو E أو K بجرعات عالية.',
];

const IRON_SUPPLEMENT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
	'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
	'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const ZINC_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const CALCIUM_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
	'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const INJECTION_WARNINGS = [
	'للاستخدام في منشأة صحية.',
	'قد يسبب تفاعل تحسسي؛ اطلب مساعدة طبية عند ضيق نفس/تورم/طفح شديد.',
];

const D3_DAILY_GENERAL_RULE = (_w: number, ageMonths: number) => {
	if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
	if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
	return '١٠٠٠ وحدة دولية يومياً';
};

export const DIETARY_SUPPLEMENTS_5: Medication[] = [
	// ==========================================
	// Dietary supplements - Part 5
	// Items: 211 → 256
	// ==========================================

	// 211
	{
		id: 'zinc-picolinate-50mg-120-veg-caps-ds5',
		name: 'zinc picolinate 50 mg 120 veg. caps. (now)',
		genericName: 'zinc',
		concentration: '50 mg (120 veg caps)',
		price: 1300,
		matchKeywords: ['zinc picolinate 50', 'picolinate', 'zinc 50', 'veg caps', '#zinc'],
		usage: 'مكمل زنك (بيكولينات) لدعم المناعة والجلد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل أو حسب إرشادات العبوة.'),
		warnings: ZINC_WARNINGS,
	},

	// 212
	{
		id: 'zinkeem-20-tabs-ds5',
		name: 'zinkeem 20 tabs.',
		genericName: 'zinc',
		concentration: '20 tabs',
		price: 48,
		matchKeywords: ['zinkeem', 'زينكيم', 'zinc', '#zinc'],
		usage: 'مكمل زنك لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 213
	{
		id: 'phara-fero-18-20-caps-ds5',
		name: 'phara fero 18 - 20 caps.',
		genericName: 'iron & zinc & copper & molybdenum & vitamins b1 & ...',
		concentration: '20 caps',
		price: 64,
		matchKeywords: ['phara fero 18', 'phara fero', 'فارا فيرو 18', 'iron', 'zinc', '#iron'],
		usage: 'مكمل حديد ومعادن وفيتامينات لدعم الدم والطاقة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 214
	{
		id: 'brovitacan-joint-30-fc-tabs-ds5',
		name: 'brovitacan joint 30 f.c.tabs.',
		genericName: 'glucosamine sulfate & chondroitin sulfate & hydrolyz...',
		concentration: '30 F.C. tabs',
		price: 180,
		matchKeywords: ['brovitacan joint', 'brovitacan', 'joint', 'glucosamine', 'chondroitin', 'خشونة', '#joint'],
		usage: 'مكمل لدعم المفاصل والغضاريف.',
		timing: 'مرة يومياً.',
		category: Category.MUSCULOSKELETAL,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل أو حسب إرشادات العبوة.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 215
	{
		id: 'lactoferrin-saja-100mg-30-caps-ds5',
		name: 'lactoferrin saja 100 mg 30 caps',
		genericName: 'bovine lactoferrin',
		concentration: '100 mg (30 caps)',
		price: 285,
		matchKeywords: ['lactoferrin saja', 'saja lactoferrin', 'لاكتوفرين ساجا', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 216
	{
		id: 'calcinex-plus-30-pills-ds5',
		name: 'calcinex plus 30 pills',
		genericName: 'calcium carbonate & vitamin d3',
		concentration: '30 tablets',
		price: 150,
		matchKeywords: ['calcinex plus 30', 'calcinex plus', 'calcium carbonate', 'vitamin d3', '#calcium', '#vitamin_d'],
		usage: 'كالسيوم كربونات + فيتامين D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 217
	{
		id: 'cholelage-30ml-oral-drops-ds5',
		name: 'cholelage 30 ml oral drops',
		genericName: 'vitamin d3',
		concentration: 'oral drops (30ml)',
		price: 45,
		matchKeywords: ['cholelage', 'كوليج', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 218
	{
		id: 'dalkino-20-tabs-ds5',
		name: 'dalkino 20 tabs',
		genericName: 'calcium & zinc & vitamin d3 & magnesium & copper & manga...',
		concentration: '20 tabs',
		price: 50,
		matchKeywords: ['dalkino', 'دالكينو', 'calcium', 'zinc', 'vitamin d3', 'magnesium', '#calcium'],
		usage: 'كالسيوم ومعادن مع D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 219
	{
		id: 'dedera-oral-drops-30ml-ds5',
		name: 'dedera oral drops 30 ml',
		genericName: 'vitamin d3 & vitamin k2',
		concentration: 'oral drops (30ml)',
		price: 60,
		matchKeywords: ['dedera drops', 'dedera', 'ديديرا', 'vitamin d3', 'vitamin k2', '#vitamin_d'],
		usage: 'نقط فيتامين D3 مع K2 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 220
	{
		id: 'partenza-20-tab-ds5',
		name: 'partenza 20 tab.',
		genericName: 'calcium & magnesium & vitamin d3 & zinc & manganese & cop...',
		concentration: '20 tabs',
		price: 68,
		matchKeywords: ['partenza', 'بارتنزا', 'calcium', 'magnesium', 'vitamin d3', 'zinc', '#calcium'],
		usage: 'كالسيوم ومعادن مع D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 221
	{
		id: 'reemablast-20-tabs-ds5',
		name: 'reemablast 20 tabs.',
		genericName: 'calcium & magnesium & vitamin d3 & zinc',
		concentration: '20 tabs',
		price: 102,
		matchKeywords: ['reemablast 20', 'reemablast', 'ريما بلاست', 'calcium', 'vitamin d3', 'zinc', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 222
	{
		id: 'reemablast-syrup-120ml-ds5',
		name: 'reemablast syrup 120 ml',
		genericName: 'calcium & magnesium & vitamin d3 & zinc',
		concentration: '120ml syrup',
		price: 69,
		matchKeywords: ['reemablast syrup', 'reemablast', 'ريما بلاست شراب', 'calcium syrup', '#calcium'],
		usage: 'شراب كالسيوم ومعادن مع D3 وزنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 24,
		maxAgeMonths: 216,
		minWeight: 10,
		maxWeight: 80,
		calculationRule: fixed('حسب إرشادات العبوة/الطبيب.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 223
	{
		id: 'foxilage-30ml-oral-drops-ds5',
		name: 'foxilage 30 ml oral drops',
		genericName: 'iron & vitamin b 6 & vitamin b 12 & folate',
		concentration: 'oral drops (30ml)',
		price: 65,
		matchKeywords: ['foxilage drops', 'foxilage', 'فوكسلاج', 'iron drops', 'folate', 'b6', 'b12', '#iron'],
		usage: 'نقط حديد مع فيتامينات لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('حسب إرشادات العبوة/الطبيب (تعتمد على تركيز الحديد).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 224
	{
		id: 'fash-co-20-chewable-tabs-ds5',
		name: 'fash-co 20 chewable tablets',
		genericName: 'amino acid chelated iron & folic acid & vitamin b1 & vitamin b...',
		concentration: '20 chewable tabs',
		price: 100,
		matchKeywords: ['fash-co', 'fash co', 'فاش كو', 'chelated iron', 'folic acid', 'chewable', '#iron'],
		usage: 'حديد مخلب + فوليك + فيتامينات (قابل للمضغ) لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 225
	{
		id: 'dronalo-30ml-drops-ds5',
		name: 'dronalo 30 ml drops',
		genericName: 'vitamin d3',
		concentration: 'oral drops (30ml)',
		price: 52,
		matchKeywords: ['dronalo', 'درونالو', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 226
	{
		id: 'for-kids-d3-oral-drops-15ml-ds5',
		name: 'for kids d3 oral drops 15 ml',
		genericName: 'vitamin d3',
		concentration: 'oral drops (15ml)',
		price: 47,
		matchKeywords: ['for kids d3', 'kids d3 drops', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للأطفال.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 227
	{
		id: 'sanso-d3-400iu-ml-oral-drops-60ml-ds5',
		name: 'sanso d3 400 i.u./ml oral drops 60 ml',
		genericName: 'cholecalciferol',
		concentration: '400 IU/ml (60ml)',
		price: 120,
		matchKeywords: ['sanso d3 400 iu/ml 60', 'sanso d3 60', 'vitamin d3 400 iu/ml', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 228
	{
		id: 'extreme-axiona-chocolate-40-soft-chews-ds5',
		name: 'extreme axiona chocolate 40 soft chews pieces',
		genericName: 'calcium & vitamin d3 & vitamin k',
		concentration: '40 soft chews',
		price: 80,
		matchKeywords: ['axiona', 'extreme axiona', 'soft chews', 'calcium', 'vitamin d3', 'vitamin k', '#calcium'],
		usage: 'مكمل كالسيوم مع D3 وK (قطع للمضغ) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 18,
		maxWeight: 250,
		calculationRule: fixed('حسب إرشادات العبوة (غالباً قطعة يومياً).'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 229
	{
		id: 'flown-10-sachets-ds5',
		name: 'flown 10 sachets',
		genericName: 'iron & lactoferrin & folic acid & vitamin b6 & vita...',
		concentration: '10 sachets',
		price: 110,
		matchKeywords: ['flown', 'فلوون', 'iron', 'lactoferrin', 'folic acid', '#iron'],
		usage: 'حديد + لاكتوفرّين + فوليك + فيتامينات لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 230
	{
		id: 'ferose-50mg-5ml-100ml-syrup-ds5',
		name: 'ferose 50mg/5ml 100ml syrup',
		genericName: 'iron',
		concentration: '50mg/5ml (100ml)',
		price: 16.2,
		matchKeywords: ['ferose syrup 50mg/5ml', 'ferose', 'فيروز', 'iron syrup', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب حديد لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('حسب التشخيص والتحاليل (تعتمد على تركيز الحديد والجرعة المطلوبة).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 231
	{
		id: 'ferose-f-30-chewable-tab-ds5',
		name: 'ferose-f 30 chewable tab.',
		genericName: 'folic acid & iron',
		concentration: '30 chewable tabs',
		price: 42,
		matchKeywords: ['ferose-f', 'ferose f', 'فيروز-ف', 'folic acid', 'iron', '#iron'],
		usage: 'حديد + فوليك (قابل للمضغ) لدعم أنيميا نقص الحديد خاصة مع نقص الفولات.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 232 (cancelled)
	{
		id: 'ferose-100mg-30-chewable-tab-cancelled-ds5',
		name: 'ferose 100mg 30 chewable tab. (cancelled)',
		genericName: 'iron',
		concentration: '100mg (30 chewable tabs)',
		price: 17.5,
		matchKeywords: ['ferose 100mg chewable', 'ferose 100', 'cancelled', 'iron', '#iron'],
		usage: 'منتج مُدرج كـ (cancelled) — يُفضّل التأكد من التوفر قبل الوصف.',
		timing: 'حسب التوفر ووصفة الطبيب.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('حسب التشخيص والتحاليل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 233
	{
		id: 'folifer-30-tab-ds5',
		name: 'folifer 30 tab',
		genericName: 'ferrous fumarate & folic acid',
		concentration: '30 tabs',
		price: 7.2,
		matchKeywords: ['folifer', 'فوليفير', 'ferrous fumarate', 'folic acid', '#iron'],
		usage: 'حديد + فوليك لدعم علاج أنيميا نقص الحديد خاصة بالحمل/نقص الفولات.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 234
	{
		id: 'nelex-1000iu-30-tabs-ds5',
		name: 'nelex 1.000 iu 30 tabs',
		genericName: 'vitamin d3',
		concentration: '1000 IU (30 tabs)',
		price: 73,
		matchKeywords: ['nelex 1000', 'nelex', 'نيلكس', 'vitamin d3 1000', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د بجرعة متوسطة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل أو حسب التشخيص والتحاليل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 235
	{
		id: 'haemopower-100mg-2ml-5-amp-im-ds5',
		name: 'haemopower 100mg/2ml 5 amp. for i.m inj',
		genericName: 'elemental iron & ferric (iron iii) hydroxide polymaltose complex',
		concentration: '100mg/2ml (5 amps)',
		price: 75,
		matchKeywords: ['haemopower', 'هيموباور', 'im iron', 'polymaltose', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد للحقن العضلي لعلاج نقص الحديد حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('يحدد الطبيب الجرعة والجدول حسب التحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 236
	{
		id: 'fertona-30-tab-ds5',
		name: 'fertona 30 tab',
		genericName: 'iron & folic acid & zinc & vitamin c & lactoferrin & vita...',
		concentration: '30 tabs',
		price: 149,
		matchKeywords: ['fertona', 'فيرتونا', 'iron', 'folic acid', 'zinc', 'lactoferrin', '#iron'],
		usage: 'مكمل حديد + لاكتوفرّين + فوليك + زنك + فيتامين C لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 237
	{
		id: 'hush-10-sachets-ds5',
		name: 'hush 10 sachets',
		genericName: 'calcium & vitamin d3 & vitamin c & magnesium',
		concentration: '10 sachets',
		price: 90,
		matchKeywords: ['hush', 'هاش', 'calcium', 'vitamin d3', 'vitamin c', 'magnesium', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + فيتامين C وD3 (أكياس) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Sachets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 18,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 238
	{
		id: 'sterogyl-15h-600000iu-1-5ml-amp-ds5',
		name: 'sterogyl 15 h 600.000 i.u./1.5ml i.m./oral amp.',
		genericName: 'ergocalciferol (vitamin d2)',
		concentration: '600,000 IU/1.5ml (amp)',
		price: 65.5,
		matchKeywords: ['sterogyl 15 h', 'sterogyl 600000', 'vitamin d2 600000', 'ergocalciferol', '#vitamin_d'],
		usage: 'فيتامين D2 حقنة/أمبول جرعة عالية جداً حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة عالية جداً: يحدد الطبيب الجرعة وتكرارها حسب التحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 239
	{
		id: 'roval-20-pieces-ds5',
		name: 'roval 20 pieces',
		genericName: 'lactoferrin & iron & vitamin b complex & vitamin c & folic acid',
		concentration: '20 pieces',
		price: 94,
		matchKeywords: ['roval', 'روفال', 'lactoferrin', 'iron', 'b complex', 'vitamin c', 'folic acid', '#iron'],
		usage: 'لاكتوفرّين + حديد + فيتامينات لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 240
	{
		id: 'ferzy-20-sachets-ds5',
		name: 'ferzy 20 sachets',
		genericName: 'iron & lactoferrin & zinc & folic acid',
		concentration: '20 sachets',
		price: 120,
		matchKeywords: ['ferzy', 'فيرزي', 'iron', 'lactoferrin', 'zinc', 'folic acid', '#iron'],
		usage: 'حديد + لاكتوفرّين + زنك + فوليك لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 241
	{
		id: 'ferromack-20-caps-ds5',
		name: 'ferromack 20 caps.',
		genericName: 'iron & zinc & copper & folic acid & vitamin b complex',
		concentration: '20 caps',
		price: 98,
		matchKeywords: ['ferromack', 'فيروماك', 'iron', 'zinc', 'copper', 'folic acid', 'b complex', '#iron'],
		usage: 'مكمل متعدد (حديد + زنك + نحاس + فوليك + فيتامينات ب) لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 242
	{
		id: 'vidrop-2800iu-ml-oral-drops-15ml-ds5',
		name: 'vidrop 2800 i.u./ml oral drops 15 ml',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '2800 IU/ml (15ml)',
		price: 26,
		matchKeywords: ['vidrop 2800', 'vidrop', 'في دروب', 'vitamin d3 drops 2800', '#vitamin_d'],
		usage: 'نقط فيتامين D3 (تركيز ٢٨٠٠ IU/مل) للوقاية/علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 243
	{
		id: 'zimacal-30-tablets-ds5',
		name: 'zimacal 30 tablets',
		genericName: 'zinc & calcium & magnesium',
		concentration: '30 tablets',
		price: 81,
		matchKeywords: ['zimacal', 'زيماكال', 'zinc', 'calcium', 'magnesium', '#calcium', '#zinc'],
		usage: 'كالسيوم + ماغنسيوم + زنك لدعم العظام والعضلات.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS],
	},

	// 244
	{
		id: 'rangier-20-chew-tabs-ds5',
		name: 'rangier 20 chew. tabs.',
		genericName: 'iron & zinc & molybdneum & copper & vitamins a & vitamin...',
		concentration: '20 chewable tabs',
		price: 85,
		matchKeywords: ['rangier', 'رانجير', 'iron', 'zinc', 'chewable', '#iron'],
		usage: 'مكمل أنيميا (حديد + زنك + نحاس + موليبدينوم + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 245
	{
		id: 'bonefit-10000iu-ml-oral-drops-15ml-ds5',
		name: 'bonefit 10.000 i.u./ml oral drops 15 ml',
		genericName: 'cholecalciferol',
		concentration: '10000 IU/ml (15ml)',
		price: 120,
		matchKeywords: ['bonefit drops 10000', 'bonefit', 'vitamin d3 10000 iu/ml', '#vitamin_d'],
		usage: 'نقط فيتامين D3 بتركيز عالي (للخطة العلاجية حسب التشخيص والتحاليل).',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 12,
		maxAgeMonths: 216,
		minWeight: 8,
		maxWeight: 80,
		calculationRule: fixed('تركيز عالي: الجرعة تُحدد حسب تركيز القياس والبروتوكول (نقط/مل).'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 246
	{
		id: 'nelex-vit-d3-5000iu-30-tabs-ds5',
		name: 'nelex vit. d3 5000 i.u. 30 tabs',
		genericName: 'vitamin d3',
		concentration: '5000 IU (30 tabs)',
		price: 90,
		matchKeywords: ['nelex d3 5000', 'nelex 5000', 'vitamin d3 5000', '#vitamin_d'],
		usage: 'فيتامين D3 جرعة عالية نسبياً لعلاج النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥٠٠٠ وحدة: غالباً قرص يومياً لفترة محددة أو حسب التشخيص والتحاليل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 247
	{
		id: 'ferropolyn-30-caps-ds5',
		name: 'ferropolyn 30 caps',
		genericName: 'ferrous fumarate & folic acid & vitamin b12 & vitamin c',
		concentration: '30 caps',
		price: 105,
		matchKeywords: ['ferropolyn', 'فيروبولين', 'ferrous fumarate', 'folic acid', 'b12', 'vitamin c', '#iron'],
		usage: 'حديد + فوليك + B12 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 248
	{
		id: 'ziadev-d3-10000-30-tab-ds5',
		name: 'ziadev d3 10.000 30 tab',
		genericName: 'vitamin d3',
		concentration: '10000 IU (30 tabs)',
		price: 120,
		matchKeywords: ['ziadev d3 10000', 'ziadev', 'vitamin d3 10000', '#vitamin_d'],
		usage: 'فيتامين D3 جرعة عالية لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة عالية: غالباً قرص أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 249
	{
		id: 'mb-otto-30-film-coated-tablets-ds5',
		name: 'mb-otto 30 film coated tablets',
		genericName: 'calcium & magnesium & zinc & boron & copper & manganese ...',
		concentration: '30 film-coated tabs',
		price: 120,
		matchKeywords: ['mb-otto', 'mb otto', 'film coated', 'calcium', 'magnesium', 'zinc', 'boron', '#calcium'],
		usage: 'مكمل معادن متعدد لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS],
	},

	// 250
	{
		id: 'calci-mash-30-fc-tabs-ds5',
		name: 'calci-mash 30 f.c. tabs.',
		genericName: 'calcium carbonate & magnesium & vitamin d3 & zinc',
		concentration: '30 F.C. tabs',
		price: 90,
		matchKeywords: ['calci-mash', 'calci mash', 'كالسي ماش', 'calcium carbonate', 'vitamin d3', 'zinc', '#calcium'],
		usage: 'كالسيوم كربونات + ماغنسيوم + D3 + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 251
	{
		id: 'calcinex-plus-20-chew-pieces-ds5',
		name: 'calcinex plus 20 chew. pieces',
		genericName: 'calcium carbonate & vitamin d3',
		concentration: '20 chew pieces',
		price: 69,
		matchKeywords: ['calcinex plus 20', 'calcinex chew', 'calcium carbonate', 'vitamin d3', '#calcium', '#vitamin_d'],
		usage: 'كالسيوم كربونات + D3 (قطع للمضغ) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 18,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل أو حسب إرشادات العبوة.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 252
	{
		id: 'calcionate-6-amps-ds5',
		name: 'calcionate 6 amps.',
		genericName: 'calcium gluconate & calcium levulinate',
		concentration: '6 amps',
		price: 138,
		matchKeywords: ['calcionate', 'كالسيونات', 'calcium gluconate', 'ampoules', '#calcium'],
		usage: 'كالسيوم حقن (جلوكونات/ليفولينات) حسب التشخيص.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.CALCIUM_GROWTH,
		form: 'Ampoules',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('يحدد الطبيب الجرعة وطريقة الإعطاء.'),
		warnings: [...INJECTION_WARNINGS, ...CALCIUM_WARNINGS],
	},

	// 253
	{
		id: 'calcium-pharco-115mg-5ml-syrup-120ml-ds5',
		name: 'calcium pharco 115mg/5ml syrup 120ml',
		genericName: 'calcium glubionate',
		concentration: '115mg/5ml (120ml)',
		price: 8.5,
		matchKeywords: ['calcium pharco', 'فاركو كالسيوم', 'calcium glubionate', 'syrup', '#calcium'],
		usage: 'شراب كالسيوم للأطفال لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 216,
		minWeight: 6,
		maxWeight: 80,
		calculationRule: fixed('حسب إرشادات العبوة/الطبيب.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 254
	{
		id: 'cempion-10-sachets-ds5',
		name: 'cempion 10 sachets',
		genericName: 'lactoferrin & colostrum & iron & vitamin b complex & folic acid...',
		concentration: '10 sachets',
		price: 125,
		matchKeywords: ['cempion', 'سيمبيون', 'lactoferrin', 'colostrum', 'iron', 'b complex', 'folic acid', '#iron'],
		usage: 'لاكتوفرّين + كولوستروم + حديد + فيتامينات لدعم علاج الأنيميا والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 255
	{
		id: 'd3-tag-1000iu-ml-oral-drops-30ml-ds5',
		name: 'd3-tag 1000 iu/ml oral drops 30ml',
		genericName: 'cholecalciferol',
		concentration: '1000 IU/ml (30ml)',
		price: 69,
		matchKeywords: ['d3-tag', 'd3 tag', 'دي3 تاج', '1000 iu/ml', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 بتركيز ١٠٠٠ IU/مل.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 256
	{
		id: 'defonta-10ml-oral-drops-ds5',
		name: 'defonta 10 ml oral drops',
		genericName: 'cholecalciferol',
		concentration: 'oral drops (10ml)',
		price: 50,
		matchKeywords: ['defonta', 'ديفونتا', 'vitamin d3 drops', '10 ml', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},
];

