import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
	'لا تتجاوز الجرعة اليومية الموصى بها.',
	'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
	'إذا لديك مرض مزمن/حساسية شديدة أو تتناول أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين D أو A أو E أو K بجرعات عالية.',
];

const IRON_SUPPLEMENT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
	'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
	'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const ZINC_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const CALCIUM_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
	'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const INJECTION_WARNINGS = [
	'للاستخدام في منشأة صحية.',
	'قد يسبب تفاعل تحسسي؛ اطلب مساعدة طبية عند ضيق نفس/تورم/طفح شديد.',
];

const D3_DAILY_GENERAL_RULE = (_w: number, ageMonths: number) => {
	if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
	if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
	return '١٠٠٠ وحدة دولية يومياً';
};

export const DIETARY_SUPPLEMENTS_3: Medication[] = [
	// ==========================================
	// Dietary supplements - Part 3
	// Items: 111 → 156
	// ==========================================

	// 111
	{
		id: 'kemstical-syrup-120ml-ds3',
		name: 'kemstical syrup 120 ml',
		genericName: 'calcium & magnesium & zinc & vitamin d3',
		concentration: '120ml',
		price: 75,
		matchKeywords: ['kemstical', 'كيمستيكل', 'calcium', 'magnesium', 'zinc', 'vitamin d3', '#calcium'],
		usage: 'شراب دعم العظام (كالسيوم + ماغنسيوم + زنك + D3).',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 112
	{
		id: 'immuniphar-20-fc-tabs-ds3',
		name: 'immuniphar 20 f.c. tabs.',
		genericName: 'vitamin c & vitamin d & vitamin e & vitamin a & zinc oxide',
		concentration: '20 F.C. tabs',
		price: 87,
		matchKeywords: ['immuniphar', 'ايميونيفار', 'vitamin c', 'vitamin d', 'vitamin e', 'vitamin a', 'zinc', 'immunity', 'مناعة'],
		usage: 'مكمل متعدد لدعم المناعة (فيتامينات A/D/E/C + زنك).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 113
	{
		id: 'choletrix-d3-400iu-oral-drops-30ml-ds3',
		name: 'choletrix-d3 400 iu oral drops 30ml',
		genericName: 'cholecalciferol',
		concentration: 'oral drops (30ml)',
		price: 75,
		matchKeywords: ['choletrix', 'choletrix d3', 'كوليتركس', 'vitamin d3', 'drops', '400 iu', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: fixed('٤٠٠ وحدة دولية يومياً (تحقق من تركيز العبوة وطريقة القياس).'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 114
	{
		id: 'copad-10000iu-30-caps-ds3',
		name: 'copad 10.000 i.u. 30 caps.',
		genericName: 'vitamin d & vitamin c',
		concentration: '10000 IU (30 caps)',
		price: 215,
		matchKeywords: ['copad', 'كو باد', 'vitamin d 10000', 'vitamin c', '#vitamin_d'],
		usage: 'فيتامين D عالي الجرعة مع فيتامين C لدعم المناعة/تصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة عالية: يحدد الطبيب الجرعة والمدة حسب التحاليل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 115
	{
		id: 'ferrodep-30-caps-ds3',
		name: 'ferrodep 30 caps.',
		genericName: 'sunactive iron & vitamin c',
		concentration: '30 caps',
		price: 295,
		matchKeywords: ['ferrodep', 'فيروديب', 'sunactive iron', 'vitamin c', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد (Sunactive) + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 116
	{
		id: 'ferrodep-syrup-150ml-ds3',
		name: 'ferrodep syrup 150 ml',
		genericName: 'sunactive iron pyrophosphate & vitamin c & pido-zinc',
		concentration: '150ml',
		price: 250,
		matchKeywords: ['ferrodep syrup', 'ferrodep', 'فيروديب شراب', 'iron syrup', 'zinc', '#iron'],
		usage: 'شراب حديد (Sunactive) + فيتامين C + زنك لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 117
	{
		id: 'kidzona-d3-30ml-oral-drops-ds3',
		name: 'kidzona d3 30ml oral drops',
		genericName: 'cholecalciferol',
		concentration: 'oral drops (30ml)',
		price: 135,
		matchKeywords: ['kidzona', 'kidzona d3', 'كيدزونا', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للأطفال للوقاية/علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 118
	{
		id: 'lipoferric-folic-30-sachets-ds3',
		name: 'lipoferric folic 30 sachets',
		genericName: 'liposomal iron & vitamin c & folic acid & vitamin b6 & vitamin b12',
		concentration: '30 sachets',
		price: 175,
		matchKeywords: ['lipoferric folic sachets', 'lipoferric', 'liposomal iron', 'folic acid', 'b6', 'b12', '#iron'],
		usage: 'حديد ليبوسومال + فوليك وفيتامينات ب لدعم علاج أنيميا نقص الحديد (أكياس).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 119
	{
		id: 'sekem-immune-boosting-tea-10-filter-bags-ds3',
		name: 'sekem immune boosting tea 10 filter bags',
		genericName: 'echinacea & ginger & sage',
		concentration: '10 filter bags',
		price: 19.5,
		matchKeywords: ['sekem', 'سيكم', 'immune tea', 'echinacea', 'ginger', 'sage', 'tea', 'immunity', 'مناعة'],
		usage: 'شاي أعشاب لدعم المناعة (إشنيسيا + زنجبيل + ميرمية).',
		timing: 'مرة إلى مرتين يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كيس/فلتر يُنقع في ماء ساخن مرة–مرتين يومياً.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 120
	{
		id: 'osavidin-200000iu-ml-im-amp-ds3',
		name: 'osavidin 200,000 i.u/ ml i.m. amp.',
		genericName: 'vitamin d3 (cholecalciferol)',
		concentration: '200000 IU/ml (1 IM amp)',
		price: 36,
		matchKeywords: ['osavidin 200000', 'osavidin', 'اوسافيدين', 'vitamin d injection', '200000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة (حقن عضل) لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('أمبول عضل جرعة واحدة أو حسب البروتوكول.'),
		warnings: [...INJECTION_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 121
	{
		id: 'ergopreno-600000iu-1-5ml-3-amp-im-oral-ds3',
		name: 'ergopreno 600.000 i.u./ 1.5ml 3 i.m./oral amp.',
		genericName: 'ergocalciferol (vitamin d2)',
		concentration: '600000 IU/1.5ml (3 amp)',
		price: 63,
		matchKeywords: ['ergopreno', 'ارجوبرينو', 'ergocalciferol', 'vitamin d2', '600000', '#vitamin_d'],
		usage: 'فيتامين D2 عالي الجرعة (أمبولات) لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('جرعة عالية: يحدد الطبيب الجرعة وطريقة الاستخدام (عضل/فموي) حسب العبوة.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 122
	{
		id: 'infarais-oral-drops-ds3',
		name: 'infarais oral drops',
		genericName: 'iron & vitamin d & vitamin a & vitamin b complex',
		concentration: 'oral drops',
		price: 65,
		matchKeywords: ['infarais', 'انفارايز', 'iron drops', 'vitamin d', 'vitamin a', 'b complex', 'anemia', 'انيميا', '#iron'],
		usage: 'نقط متعددة لدعم الدم والمناعة (حديد + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 1,
		maxAgeMonths: 144,
		minWeight: 3,
		maxWeight: 60,
		calculationRule: fixed('حسب التشخيص والتحاليل (تعتمد على تركيز العبوة).'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 123
	{
		id: 'irovast-30-fc-tabs-ds3',
		name: 'irovast 30 f.c. tabs.',
		genericName: 'ferrous bisglycinate & vitamin c',
		concentration: '30 F.C. tabs',
		price: 145,
		matchKeywords: ['irovast', 'ايروفاست', 'ferrous bisglycinate', 'vitamin c', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد بيسجليسينات + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'F.C. Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 124
	{
		id: 'janpro-drops-15ml-ds3',
		name: 'janpro drops 15 ml',
		genericName: 'probiotics & zinc & vitamin d3',
		concentration: '15ml',
		price: 70,
		matchKeywords: ['janpro', 'جان برو', 'probiotics', 'zinc', 'vitamin d3', 'drops'],
		usage: 'نقط بروبيوتك + زنك + فيتامين D3 لدعم الهضم والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.PROBIOTICS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: fixed('حسب إرشادات العبوة (عادةً جرعة يومية واحدة).'),
		warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 125
	{
		id: 'neutra-feritin-30-caps-ds3',
		name: 'neutra feritin 30 caps.',
		genericName: 'iron & vitamin b6 & vitamin b12 & folic acid',
		concentration: '30 caps',
		price: 135,
		matchKeywords: ['neutra feritin', 'neutra', 'فيريتين', 'iron', 'b6', 'b12', 'folic acid', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك + فيتامينات ب لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 126
	{
		id: 'sansoimune-plus-syrup-200ml-ds3',
		name: 'sansoimune plus syrup 200 ml',
		genericName: 'echinacea purpurea & vitamin c & zinc',
		concentration: '200ml',
		price: 45,
		matchKeywords: ['sansoimune plus', 'sansoimune', 'سانسوايميون بلس', 'echinacea', 'vitamin c', 'zinc', 'immunity', 'مناعة'],
		usage: 'شراب لدعم المناعة (إشنيسيا + فيتامين C + زنك).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 24,
		maxAgeMonths: 144,
		minWeight: 10,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...GENERAL_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 127
	{
		id: 'totacal-30-tabs-ds3',
		name: 'totacal 30 tabs',
		genericName: 'calcium & magnesium & vitamin d3 & zinc & selenium',
		concentration: '30 tabs',
		price: 120,
		matchKeywords: ['totacal', 'توتاكال', 'calcium', 'magnesium', 'vitamin d3', 'zinc', 'selenium', '#calcium'],
		usage: 'كالسيوم + معادن + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 128
	{
		id: 'vitamin-d3-k2-30-tabs-ds3',
		name: 'vitamin d3 & k2 30 tabs',
		genericName: 'vitamin d3 & vitamin k',
		concentration: '30 tabs',
		price: 270,
		matchKeywords: ['d3 k2', 'vitamin d3 k2', 'vitamin k2', 'vitamin d3', '#vitamin_d'],
		usage: 'فيتامين D3 مع K2 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 129
	{
		id: 'vitosel-syrup-30ml-ds3',
		name: 'vitosel syrup 30 ml',
		genericName: 'lactoferrin & ferrous fumarate & colostrum & vitamins',
		concentration: '30ml',
		price: 110,
		matchKeywords: ['vitosel', 'فيتوسيل', 'lactoferrin', 'colostrum', 'iron', 'syrup', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب لدعم الدم والمناعة (لاكتوفرّين + حديد + كولوستروم + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: fixed('حسب إرشادات العبوة/الطبيب.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 130
	{
		id: 'vidoxflic-120ml-oral-syrup-ds3',
		name: 'vidoxflic 120 ml oral syrup',
		genericName: 'vitamin c & zinc',
		concentration: '120ml',
		price: 45,
		matchKeywords: ['vidoxflic', 'فيدوكسفليك', 'vitamin c', 'zinc', 'syrup', 'immunity', 'مناعة', '#zinc'],
		usage: 'شراب فيتامين C + زنك لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 24,
		maxAgeMonths: 144,
		minWeight: 10,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: ZINC_WARNINGS,
	},

	// 131
	{
		id: 'calcipino-20-tab-ds3',
		name: 'calcipino 20 tab',
		genericName: 'liposomal cal & calcium carbonate & vitamin d3',
		concentration: '20 tabs',
		price: 100,
		matchKeywords: ['calcipino', 'كالسيبينو', 'liposomal calcium', 'calcium carbonate', 'vitamin d3', '#calcium'],
		usage: 'كالسيوم (قد يكون ليبوسومال) + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 132
	{
		id: 'rangier-line-20-tabs-ds3',
		name: 'rangier line 20 tabs.',
		genericName: 'iron & zinc & molybdenum & copper & vitamins a & vitamin b complex',
		concentration: '20 tabs',
		price: 105,
		matchKeywords: ['rangier line', 'rangier', 'رانجير', 'iron', 'zinc', 'molybdenum', 'copper', 'vitamin a', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل متعدد لدعم الدم (حديد + زنك + معادن + فيتامينات).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 133
	{
		id: 'bon-one-0-5mcg-30-tabs-ds3',
		name: 'bon-one 0.5 mcg 30 tabs.',
		genericName: 'alfacalcidol',
		concentration: '0.5 mcg (30 tabs)',
		price: 123,
		matchKeywords: ['bon-one 0.5', 'bon-one', 'bon one', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'فيتامين د نشط (ألفاكالسيدول) لدعم اضطرابات العظام حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يحدد الطبيب الجرعة حسب التحاليل (لتجنب ارتفاع الكالسيوم).'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 134
	{
		id: 'iron-direct-20-sachets-ds3',
		name: 'iron direct 20 sachets',
		genericName: 'iron & folic acid & vitamin b6 & vitamin c',
		concentration: '20 sachets',
		price: 500,
		matchKeywords: ['iron direct', 'ايرون دايركت', 'iron', 'folic acid', 'b6', 'vitamin c', 'sachets', '#iron'],
		usage: 'أكياس حديد + فوليك + B6 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 135
	{
		id: 'bon-one-0-25mcg-30-tabs-ds3',
		name: 'bon-one 0.25 mcg 30 tabs.',
		genericName: 'alfacalcidol',
		concentration: '0.25 mcg (30 tabs)',
		price: 90,
		matchKeywords: ['bon-one 0.25', 'bon-one', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'فيتامين د نشط (ألفاكالسيدول) حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يحدد الطبيب الجرعة حسب التحاليل (لتجنب ارتفاع الكالسيوم).'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 136
	{
		id: 'calcidol-calcium-20-tabs-ds3',
		name: 'calcidol calcium 20 tabs.',
		genericName: 'calcium & vitamin d & magnesium & zinc',
		concentration: '20 tabs',
		price: 89,
		matchKeywords: ['calcidol calcium', 'calcidol', 'كالسي دول', 'calcium', 'vitamin d', 'magnesium', 'zinc', '#calcium'],
		usage: 'كالسيوم + D + ماغنسيوم + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 137
	{
		id: 'calcimax-plus-30-fc-tabs-ds3',
		name: 'calcimax plus 30 f.c.tabs.',
		genericName: 'calcium carbonate natural & citrus bioflavonide',
		concentration: '30 F.C. tabs',
		price: 120,
		matchKeywords: ['calcimax plus', 'calcimax', 'كالسيماكس', 'calcium carbonate', 'bioflavonoid', '#calcium'],
		usage: 'كالسيوم كربونات (طبيعي) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: CALCIUM_WARNINGS,
	},

	// 138
	{
		id: 'caltera-plus-30-tabs-ds3',
		name: 'caltera plus 30 tabs',
		genericName: 'calcium & magnesium & vitamin d3',
		concentration: '30 tabs',
		price: 110,
		matchKeywords: ['caltera plus', 'caltera', 'كالتره', 'calcium', 'magnesium', 'vitamin d3', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 139
	{
		id: 'sanso-d3-10000iu-28-tabs-ds3',
		name: 'sanso d3 10000 i.u. 28 tabs.',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (28 tabs)',
		price: 180,
		matchKeywords: ['sanso d3 10000', 'sanso d3', 'سانسو د3', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 140
	{
		id: 'cosmofer-50mg-ml-infusion-5-amps-ds3',
		name: 'cosmofer 50mg/ml for inf. 5 amps.',
		genericName: 'iron',
		concentration: '50mg/ml (5 amps)',
		price: 470,
		matchKeywords: ['cosmofer', 'كوزموفير', 'iv iron', 'iron infusion', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد للحقن/المحلول الوريدي لعلاج نقص الحديد حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('تُحدد الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 141
	{
		id: 'calcitrix-20-tabs-ds3',
		name: 'calcitrix 20 tabs.',
		genericName: 'calcium & magnesium & vitamin d3 & vitamin c',
		concentration: '20 tabs',
		price: 100,
		matchKeywords: ['calcitrix', 'كالسيتركس', 'calcium', 'magnesium', 'vitamin d3', 'vitamin c', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 (مع فيتامين C) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 142
	{
		id: 'phara-fero-18-30-caps-ds3',
		name: 'phara fero 18 - 30 caps.',
		genericName: 'iron & zinc & copper & molybdenum & vitamins b1 & b2 & b6',
		concentration: '30 caps',
		price: 114,
		matchKeywords: ['phara fero 18', 'phara fero', 'فارا فيرو', 'iron', 'zinc', 'copper', 'molybdenum', '#iron'],
		usage: 'مكمل حديد ومعادن وفيتامينات ب لدعم الدم والطاقة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 143
	{
		id: 'wellfemme-cal-30-tabs-ds3',
		name: 'wellfemme cal 30tabs',
		genericName: 'calcium & magnesium & zinc & boron & manganese & copper',
		concentration: '30 tabs',
		price: 150,
		matchKeywords: ['wellfemme cal', 'wellfemme', 'calcium', 'magnesium', 'zinc', 'boron', '#calcium'],
		usage: 'كالسيوم ومعادن لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS],
	},

	// 144
	{
		id: 'irolivatal-30-caps-ds3',
		name: 'irolivatal 30 caps',
		genericName: 'iron & vitamin c & folic acid & vitamin b12',
		concentration: '30 caps',
		price: 105,
		matchKeywords: ['irolivatal', 'ايروليفاتال', 'iron', 'vitamin c', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك + B12 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 145
	{
		id: 'haemactin-30-caps-ds3',
		name: 'haemactin 30 caps.',
		genericName: 'ferrous fumarate & folic acid & vitamin b12',
		concentration: '30 caps',
		price: 150,
		matchKeywords: ['haemactin', 'هيم اكتين', 'ferrous fumarate', 'folic acid', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد فومارات + فوليك + B12 لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 146
	{
		id: 'immulant-n-syrup-120ml-ds3',
		name: 'immulant n syrup 120 ml',
		genericName: 'echinacea dry extract & nigella sativa oil',
		concentration: '120ml',
		price: 50,
		matchKeywords: ['immulant n', 'immulant', 'ايميولانت ان', 'echinacea', 'nigella', 'black seed', 'immunity', 'مناعة'],
		usage: 'شراب أعشاب لدعم المناعة (إشنيسيا + حبة البركة).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 24,
		maxAgeMonths: 144,
		minWeight: 10,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 147
	{
		id: 'matrix-20-caps-ds3',
		name: 'matrix 20 caps.',
		genericName: 'minerals & vitamins',
		concentration: '20 caps',
		price: 140,
		matchKeywords: ['matrix', 'ماتريكس', 'minerals', 'vitamins', 'supplement'],
		usage: 'مكمل متعدد فيتامينات ومعادن.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 148
	{
		id: 'limitless-baby-d-1600iu-ml-oral-drops-15ml-ds3',
		name: 'limitless baby d drops 1600 i.u./ml 15 ml',
		genericName: 'cholecalciferol',
		concentration: '1600 IU/ml (15ml)',
		price: 53,
		matchKeywords: ['limitless baby d', 'baby d', 'limitless', 'vitamin d3 drops', '1600 iu/ml', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 149
	{
		id: 'ferro-saja-orange-syrup-120ml-ds3',
		name: 'ferro-saja orange syrup 120 ml',
		genericName: 'iron & vitamin b1 & vitamin b2 & vitamin b3 & folic acid & zinc',
		concentration: '120ml',
		price: 35,
		matchKeywords: ['ferro-saja', 'ferro saja', 'فيرو ساجا', 'iron syrup', 'folic acid', 'zinc', '#iron'],
		usage: 'شراب حديد مع فيتامينات ب وفوليك وزنك لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 150
	{
		id: 'ossofortin-original-d2-10000iu-30-tabs-ds3',
		name: 'ossofortin original d2 (10.000 i.u.) 30 tabs',
		genericName: 'ergocalciferol',
		concentration: '10000 IU (30 tabs)',
		price: 84,
		matchKeywords: ['ossofortin d2', 'ossofortin original d2', 'ergocalciferol', 'vitamin d2 10000', '#vitamin_d'],
		usage: 'فيتامين D2 عالي الجرعة لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 151
	{
		id: 'nel-d3-30ml-drops-ds3',
		name: 'nel d3 30 ml drops',
		genericName: 'cholecalciferol',
		concentration: 'oral drops (30ml)',
		price: 52,
		matchKeywords: ['nel d3', 'nel', 'نيل د3', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للأطفال للوقاية/علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 152
	{
		id: 'super-cal-zinc-20-tabs-ds3',
		name: 'super cal zinc 20 tabs.',
		genericName: 'magnesium oxide & calcium carbonate & zinc sulphate',
		concentration: '20 tabs',
		price: 30,
		matchKeywords: ['super cal zinc', 'super cal', 'سوبر كال زنك', 'calcium', 'magnesium', 'zinc', '#calcium', '#zinc'],
		usage: 'كالسيوم + ماغنسيوم + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS],
	},

	// 153
	{
		id: 'nelex-vit-d3-50000iu-4-tabs-ds3',
		name: 'nelex vit. d3 50000 i.u. 4 tabs',
		genericName: 'vitamin d3',
		concentration: '50000 IU (4 tabs)',
		price: 185,
		matchKeywords: ['nelex d3 50000', 'nelex', 'نيليكس', 'vitamin d3 50000', '#vitamin_d'],
		usage: 'فيتامين D3 جرعة عالية جداً لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥٠,٠٠٠ وحدة: غالباً كبسولة/قرص أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 154
	{
		id: 'jointdrive-30-tablets-ds3',
		name: 'jointdrive 30 tablets',
		genericName: 'glucosamine & avocado-soybean unsaponifiables',
		concentration: '30 tablets',
		price: 290,
		matchKeywords: ['jointdrive', 'joint drive', 'جويت درايف', 'glucosamine', 'avocado soybean', 'joint', 'خشونة'],
		usage: 'مكمل لدعم المفاصل والغضاريف (جلوكوزامين + ASU).',
		timing: 'مرة يومياً.',
		category: Category.MUSCULOSKELETAL,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 155
	{
		id: 'zincomist-10mg-5ml-syrup-120ml-ds3',
		name: 'zincomist 10mg/5ml syrup 120 ml',
		genericName: 'zinc',
		concentration: '10mg/5ml (120ml)',
		price: 50,
		matchKeywords: ['zincomist', 'زينكو ميست', 'zinc syrup', '#zinc'],
		usage: 'شراب زنك لدعم المناعة للأطفال.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('٥ مل يومياً بعد الأكل (أو حسب البروتوكول).'),
		warnings: ZINC_WARNINGS,
	},

	// 156
	{
		id: 'vitamin-d3-sublingual-30-tablets-ds3',
		name: 'vitamin d3 sublingual 30 tablets',
		genericName: 'vitamin d3',
		concentration: '30 tablets',
		price: 150,
		matchKeywords: ['vitamin d3 sublingual', 'sublingual d3', 'vitamin d3', 'د3 تحت اللسان', '#vitamin_d'],
		usage: 'فيتامين D3 أقراص تحت اللسان لدعم/علاج نقص فيتامين د.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Orodispersible Tablet',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً حسب الجرعة المدونة على العبوة.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},
];

