import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
	'لا تتجاوز الجرعة اليومية الموصى بها.',
	'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
	'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين D أو A أو E أو K بجرعات عالية.',
];

const IRON_SUPPLEMENT_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
	'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
	'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const ZINC_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const CALCIUM_WARNINGS = [
	...GENERAL_SUPPLEMENT_WARNINGS,
	'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
	'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const INJECTION_WARNINGS = [
	'للاستخدام في منشأة صحية.',
	'قد يسبب تفاعل تحسسي؛ اطلب مساعدة طبية عند ضيق نفس/تورم/طفح شديد.',
];

const D3_DAILY_GENERAL_RULE = (_w: number, ageMonths: number) => {
	if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
	if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
	return '١٠٠٠ وحدة دولية يومياً';
};

export const DIETARY_SUPPLEMENTS_4: Medication[] = [
	// ==========================================
	// Dietary supplements - Part 4
	// Items: 157 → 210
	// ==========================================

	// 157
	{
		id: 'sanso-d3-10000iu-30-tabs-ds4',
		name: 'sanso d3 10.000 i.u. 30 tabs.',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (30 tabs)',
		price: 65,
		matchKeywords: ['sanso d3 10000 30', 'sanso d3', 'سانسو د3', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح نقص فيتامين د حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 158
	{
		id: 'tronic-d3-oral-drops-15ml-ds4',
		name: 'tronic d3 oral drops 15 ml',
		genericName: 'vitamin d3',
		concentration: 'oral drops (15ml)',
		price: 54,
		matchKeywords: ['tronic d3', 'ترونيك', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 159
	{
		id: 'aviron-24-tabs-ds4',
		name: 'aviron 24 tabs.',
		genericName: 'iron & folic acid & vitamin b6 & vitamin b12',
		concentration: '24 tabs',
		price: 58,
		matchKeywords: ['aviron', 'افيرون', 'iron', 'folic acid', 'b6', 'b12', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد + فوليك + فيتامينات ب لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 160
	{
		id: 'idomaltol-30mg-56-caps-ds4',
		name: 'idomaltol 30 mg 56 caps.',
		genericName: 'iron',
		concentration: '30mg (56 caps)',
		price: 218,
		matchKeywords: ['idomaltol', 'ايدومالتول', 'iron', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل/علاج حديد لعلاج أنيميا نقص الحديد حسب التشخيص.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('الجرعة تُحدد حسب الحالة والتحاليل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 161
	{
		id: 'bone-care-1mcg-30-caps-ds4',
		name: 'bone care 1mcg 30 caps.',
		genericName: 'alfacalcidol',
		concentration: '1 mcg (30 caps)',
		price: 132,
		matchKeywords: ['bone care 1mcg', 'bone care', 'alfacalcidol', 'active vitamin d', '#vitamin_d'],
		usage: 'فيتامين د نشط (ألفاكالسيدول) لدعم اضطرابات العظام حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('يحدد الطبيب الجرعة حسب التحاليل (لتجنب ارتفاع الكالسيوم).'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 162
	{
		id: 'demas-d3-10000iu-30-fc-tabs-ds4',
		name: 'demas d3 10.000 i.u. 30 f.c.tabs.',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (30 F.C. tabs)',
		price: 150,
		matchKeywords: ['demas d3 10000', 'demas d3', 'ديماس د3', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح نقص فيتامين د حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 163
	{
		id: 'd3-k2-20-film-coated-tabs-ds4',
		name: 'd3&k2 20 film coated tabs',
		genericName: 'vitamin d3 & vitamin k2',
		concentration: '20 film-coated tabs',
		price: 195,
		matchKeywords: ['d3&k2', 'd3 k2', 'vitamin k2', 'vitamin d3', 'film coated', '#vitamin_d'],
		usage: 'فيتامين D3 مع K2 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Film-coated Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 164
	{
		id: 'calcitrix-30-tabs-ds4',
		name: 'calcitrix 30 tabs',
		genericName: 'calcium & magnesium & vitamin d3 & vitamin c & vitamin k2',
		concentration: '30 tabs',
		price: 84,
		matchKeywords: ['calcitrix 30', 'calcitrix', 'كالسيتركس', 'calcium', 'magnesium', 'vitamin d3', 'vitamin k2', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 + C + K2 لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 165
	{
		id: 'densitin-30-caps-ds4',
		name: 'densitin 30 caps',
		genericName: 'ascorbic acid (vitamin c) & vitamin d & calcium carbonate',
		concentration: '30 caps',
		price: 144,
		matchKeywords: ['densitin', 'دينسيتين', 'calcium carbonate', 'vitamin d', 'vitamin c', '#calcium', '#vitamin_d'],
		usage: 'كالسيوم كربونات + فيتامين D + فيتامين C لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 166
	{
		id: 'davazia-d3-oral-drops-30ml-ds4',
		name: 'davazia d3 oral drops 30 ml',
		genericName: 'vitamin d',
		concentration: 'oral drops (30ml)',
		price: 65,
		matchKeywords: ['davazia', 'دافازيا', 'vitamin d drops', '#vitamin_d'],
		usage: 'نقط فيتامين D للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 167
	{
		id: 'egy-tron-10-sachets-ds4',
		name: 'egy-tron 10 sachets',
		genericName: 'lactoferrin',
		concentration: '10 sachets',
		price: 100,
		matchKeywords: ['egy-tron', 'ايجي ترون', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 168
	{
		id: 'ferosac-100mg-5ml-5-amp-ds4',
		name: 'ferosac 100mg/5ml 5 amp.',
		genericName: 'iron',
		concentration: '100mg/5ml (5 amps)',
		price: 470,
		matchKeywords: ['ferosac', 'فيروساك', 'iron injection', 'iv iron', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد حقن/وريدي لعلاج نقص الحديد حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('تُحدد الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 169
	{
		id: 'ferronex-plus-iron-lozenges-24-tabs-ds4',
		name: 'ferronex plus iron lozenges 24 tabs.',
		genericName: 'ferrous fumarate & sucrose & cellulose & cocoa powder',
		concentration: '24 lozenges',
		price: 110,
		matchKeywords: ['ferronex', 'ferronex plus', 'فيرونيكس', 'iron lozenges', 'ferrous fumarate', '#iron'],
		usage: 'حديد استحلاب لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Lozenge',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص استحلاب واحد يومياً (يمص ببطء).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 170
	{
		id: 'fosavance-once-weekly-2-tab-ds4',
		name: 'fosavance once weekly 2 tab.',
		genericName: 'alendronate & vitamin d3',
		concentration: '2 tabs (once weekly)',
		price: 105,
		matchKeywords: ['fosavance', 'فوسافانس', 'alendronate', 'vitamin d3', 'osteoporosis'],
		usage: 'لعلاج/وقاية هشاشة العظام (دواء) + فيتامين D3 حسب التشخيص والتحاليل.',
		timing: 'مرة أسبوعياً.',
		category: Category.BONE_SUPPORT,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً صباحاً على معدة فارغة مع كوب ماء كبير، مع البقاء واقفاً/جالساً ٣٠ دقيقة.'),
		warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب تهيج/التهاب المريء؛ التزم بطريقة الاستخدام بدقة.'],
	},

	// 171
	{
		id: 'golden-fer-10mg-ml-syrup-100ml-ds4',
		name: 'golden fer 10 mg/ml syrup 100 ml',
		genericName: 'iron',
		concentration: '10mg/ml (100ml)',
		price: 34,
		matchKeywords: ['golden fer syrup', 'golden fer', 'جولدن فير', 'iron syrup', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب حديد لدعم/علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 6,
		maxAgeMonths: 144,
		minWeight: 6,
		maxWeight: 60,
		calculationRule: fixed('حسب التشخيص والتحاليل (تعتمد على الجرعة المطلوبة بالمجم).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 172
	{
		id: 'haemactin-20-caps-ds4',
		name: 'haemactin 20 caps.',
		genericName: 'ferrous fumarate & folic acid & vitamin b12',
		concentration: '20 caps',
		price: 36,
		matchKeywords: ['haemactin 20', 'haemactin', 'هيم اكتين', 'ferrous fumarate', 'folic acid', 'b12', '#iron'],
		usage: 'حديد + فوليك + B12 لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 173
	{
		id: 'zolo-baby-4000iu-ml-15ml-drops-ds4',
		name: 'zolo baby 4000 i.u./ml 15 ml drops',
		genericName: 'cholecalciferol',
		concentration: '4000 IU/ml (15ml)',
		price: 49,
		matchKeywords: ['zolo baby', 'زولو بيبي', 'vitamin d3', '4000 iu/ml', 'drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال (تركيز عالي).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 174
	{
		id: 'hyalgan-20mg-2ml-intra-articular-prefilled-syringe-ds4',
		name: 'hyalgan 20mg/2ml intra-articular prefilled syringe',
		genericName: 'sodium hyaluronate',
		concentration: '20mg/2ml (prefilled syringe)',
		price: 531,
		matchKeywords: ['hyalgan', 'هيالجان', 'hyaluronate', 'hyaluronic', 'knee injection', 'joint'],
		usage: 'حقن داخل المفصل لتقليل ألم/خشونة المفاصل حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.MUSCULOSKELETAL,
		form: 'Vial',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('حقن داخل المفصل حسب التشخيص والتحاليل (غالباً مرة أسبوعياً لعدة أسابيع).'),
		warnings: INJECTION_WARNINGS,
	},

	// 175
	{
		id: 'immunvita-20-caps-ds4',
		name: 'immunvita 20 caps',
		genericName: 'echinacea',
		concentration: '20 caps',
		price: 28.5,
		matchKeywords: ['immunvita', 'ايميونفيتا', 'echinacea', 'immunity', 'مناعة'],
		usage: 'إشنيسيا لدعم المناعة وتقليل مدة نزلات البرد (مكمل).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 176
	{
		id: 'innofer-10-sachets-ds4',
		name: 'innofer 10 sachets',
		genericName: 'lactoferrin & iron & vitamin b complex & folic acid',
		concentration: '10 sachets',
		price: 110,
		matchKeywords: ['innofer', 'اينوفر', 'lactoferrin', 'iron', 'folic acid', 'b complex', '#iron'],
		usage: 'لاكتوفرّين + حديد + فوليك + فيتامينات ب لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 177
	{
		id: 'interofer-100mg-5ml-5-amp-iv-ds4',
		name: 'interofer 100mg/5ml 5 amp for i.v. inj.',
		genericName: 'iron salts',
		concentration: '100mg/5ml (5 amps)',
		price: 120,
		matchKeywords: ['interofer', 'انتروفير', 'iv iron', 'iron salts', 'anemia', 'انيميا', '#iron'],
		usage: 'حديد للحقن الوريدي لعلاج نقص الحديد حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Ampoule (IV)',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('تُحدد الجرعة وطريقة الإعطاء حسب الحالة والتحاليل.'),
		warnings: [...INJECTION_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
	},

	// 178
	{
		id: 'lacrim-14-sachets-ds4',
		name: 'lacrim 14 sachets',
		genericName: 'lactoferrin & chelated iron & folic acid & vitamin c',
		concentration: '14 sachets',
		price: 125,
		matchKeywords: ['lacrim', 'لاكرم', 'lactoferrin', 'chelated iron', 'folic acid', 'vitamin c', '#iron'],
		usage: 'لاكتوفرّين + حديد مخلب + فوليك + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 179
	{
		id: 'limitless-kids-multivitamins-calcium-gummy-ds4',
		name: 'limitless kids multivitamins & calcium gummy',
		genericName: 'calcium',
		concentration: 'gummy',
		price: 110,
		matchKeywords: ['limitless kids calcium gummy', 'limitless kids', 'gummy', 'calcium', '#calcium'],
		usage: 'مكمل كالسيوم للأطفال (جُمّي) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 36,
		maxAgeMonths: 144,
		minWeight: 12,
		maxWeight: 60,
		calculationRule: fixed('حسب إرشادات العبوة (عادةً قطعة يومياً).'),
		warnings: CALCIUM_WARNINGS,
	},

	// 180
	{
		id: 'limitless-kids-multivitamins-iron-30-ds4',
		name: 'limitless kids multivitamins & iron 30 ...',
		genericName: 'iron',
		concentration: '30 pieces',
		price: 95,
		matchKeywords: ['limitless kids iron', 'limitless kids', 'iron gummy', 'iron', '#iron'],
		usage: 'مكمل حديد للأطفال (قد يكون جُمّي) لدعم الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 36,
		maxAgeMonths: 144,
		minWeight: 12,
		maxWeight: 60,
		calculationRule: fixed('حسب إرشادات العبوة (عادةً قطعة يومياً).'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 181
	{
		id: 'magnatob-24-tablets-ds4',
		name: 'magnatob 24 tablets',
		genericName: 'calcium & vitamin d3 & magnesium & amino acids',
		concentration: '24 tablets',
		price: 90,
		matchKeywords: ['magnatob', 'مجناتوب', 'calcium', 'vitamin d3', 'magnesium', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 لدعم العظام والعضلات.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 182
	{
		id: 'nixeleco-10-sachets-ds4',
		name: 'nixeleco 10 sachets',
		genericName: 'lactoferrin & colostrum & vitamin a & vitamin c',
		concentration: '10 sachets',
		price: 69,
		matchKeywords: ['nixeleco', 'نيكسليكو', 'lactoferrin', 'colostrum', 'vitamin a', 'vitamin c', 'immunity'],
		usage: 'لاكتوفرّين + كولوستروم + فيتامينات لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 183
	{
		id: 'oravar-100mg-10-sachets-ds4',
		name: 'oravar 100 mg 10 sachets',
		genericName: 'lactoferrin',
		concentration: '100mg (10 sachets)',
		price: 110,
		matchKeywords: ['oravar', 'اورافار', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 184
	{
		id: 'ossofortin-1-25mg-50000iu-30-tabs-ds4',
		name: 'ossofortin 1.25mg (50.000 i.u.) 30 tabs',
		genericName: 'ergocalciferol (vitamin d2)',
		concentration: '50000 IU (30 tabs)',
		price: 54,
		matchKeywords: ['ossofortin 50000', 'ossofortin', 'ergocalciferol', 'vitamin d2 50000', '#vitamin_d'],
		usage: 'فيتامين D2 جرعة عالية جداً لتصحيح النقص حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('٥٠,٠٠٠ وحدة: غالباً قرص أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 185
	{
		id: 'protimax-fe-plus-10x10g-sachets-ds4',
		name: 'protimax (fe+) 10g*10 sachets',
		genericName: 'lactoferrin & iron & vitamins',
		concentration: '10g (10 sachets)',
		price: 160,
		matchKeywords: ['protimax fe+', 'protimax', 'بروتيماكس', 'lactoferrin', 'iron', 'sachets', '#iron'],
		usage: 'لاكتوفرّين + حديد + فيتامينات لدعم علاج نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 186
	{
		id: 'provan-100mg-14-sachets-ds4',
		name: 'provan 100mg 14 sachets',
		genericName: 'lactoferrin',
		concentration: '100mg (14 sachets)',
		price: 140,
		matchKeywords: ['provan 14', 'provan', 'بروفان', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 187
	{
		id: 'provan-100mg-30-sachets-ds4',
		name: 'provan 100 mg 30 sachets',
		genericName: 'lactoferrin',
		concentration: '100mg (30 sachets)',
		price: 190,
		matchKeywords: ['provan 30', 'provan', 'lactoferrin', '#iron'],
		usage: 'لاكتوفرّين لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ٣٠ يوم.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 188
	{
		id: 'range-cal-24-chewable-tabs-ds4',
		name: 'range cal 24 chew. tabs',
		genericName: 'calcium & magnesium & vitamin d3 & vitamin e & folic acid',
		concentration: '24 chewable tabs',
		price: 90,
		matchKeywords: ['range cal', 'رينج كال', 'calcium', 'magnesium', 'vitamin d3', 'vitamin e', 'folic acid', '#calcium'],
		usage: 'كالسيوم + معادن + D3 (ومع فيتامين E وفوليك) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Chewable Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 189
	{
		id: 'omex-100mg-20-caps-ds4',
		name: 'omex 100 mg 20 caps.',
		genericName: 'lactoferrin & vitamin c',
		concentration: '100mg (20 caps)',
		price: 160,
		matchKeywords: ['omex', 'اوميكس', 'lactoferrin', 'vitamin c', '#iron'],
		usage: 'لاكتوفرّين + فيتامين C لدعم امتصاص الحديد والمناعة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: GENERAL_SUPPLEMENT_WARNINGS,
	},

	// 190
	{
		id: 'rofitin-24-chewable-pieces-ds4',
		name: 'rofitin 24 chew. pieces',
		genericName: 'ferrous fumarate & vitamin c & vitamin b12 & folic acid',
		concentration: '24 chew pieces',
		price: 84,
		matchKeywords: ['rofitin', 'روفاتين', 'iron', 'ferrous fumarate', 'vitamin c', 'b12', 'folic acid', '#iron'],
		usage: 'قطع للمضغ لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 191
	{
		id: 'rotone-complex-20-tabs-ds4',
		name: 'rotone complex 20 tabs',
		genericName: 'iron & zinc & copper & vitamin b1 & vitamin b2 & vitamin b6',
		concentration: '20 tabs',
		price: 110,
		matchKeywords: ['rotone complex 20', 'rotone', 'روتون', 'iron', 'zinc', 'copper', '#iron'],
		usage: 'مكمل متعدد لدعم الدم والطاقة (حديد + زنك + نحاس + فيتامينات ب).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 192
	{
		id: 'sanoplex-24-chewable-tabs-ds4',
		name: 'sanoplex 24 chewable tabs.',
		genericName: 'ferrous fumarate & vitamin b12 & folic acid & vitamin b6',
		concentration: '24 chewable tabs',
		price: 139,
		matchKeywords: ['sanoplex', 'سانوبلكس', 'iron', 'ferrous fumarate', 'b12', 'folic acid', 'b6', '#iron'],
		usage: 'حديد + فوليك + فيتامينات ب (قابل للمضغ) لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص مضغ واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 193
	{
		id: 'sanso-d3-10000iu-60-tabs-ds4',
		name: 'sanso d3 10.000 i.u. 60 tabs.',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (60 tabs)',
		price: 180,
		matchKeywords: ['sanso d3 10000 60', 'sanso d3 60', 'سانسو د3 60', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح نقص فيتامين د حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد أسبوعياً أو حسب البروتوكول.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 194
	{
		id: 'solvazinc-50mg-30-caps-ds4',
		name: 'solvazinc 50 mg 30 caps.',
		genericName: 'zinc',
		concentration: '50mg (30 caps)',
		price: 45,
		matchKeywords: ['solvazinc', 'سولفازنك', 'zinc 50', '#zinc'],
		usage: 'مكمل زنك لدعم المناعة والجلد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: ZINC_WARNINGS,
	},

	// 195
	{
		id: 'phara-fero-18-plus-20-caps-ds4',
		name: 'phara fero 18 plus - 20 caps.',
		genericName: 'iron & zinc & copper & molybdenum & vitamins b1',
		concentration: '20 caps',
		price: 275,
		matchKeywords: ['phara fero 18 plus', 'phara fero plus', 'فارا فيرو 18 بلس', 'iron', 'zinc', '#iron'],
		usage: 'مكمل حديد ومعادن وفيتامينات ب لدعم الدم والطاقة.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 196
	{
		id: 'reemablast-30-tabs-ds4',
		name: 'reemablast 30 tabs.',
		genericName: 'calcium & magnesium & vitamin d3 & zinc',
		concentration: '30 tabs',
		price: 132,
		matchKeywords: ['reemablast', 'ريما بلاست', 'calcium', 'magnesium', 'vitamin d3', 'zinc', '#calcium'],
		usage: 'كالسيوم + ماغنسيوم + D3 + زنك لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 197
	{
		id: 'calciload-30-tabs-ds4',
		name: 'calciload 30 tabs',
		genericName: 'calcium & magnesium & zinc & boron & manganese & copper',
		concentration: '30 tabs',
		price: 82.5,
		matchKeywords: ['calciload', 'كالسي لود', 'calcium', 'magnesium', 'zinc', 'boron', '#calcium'],
		usage: 'كالسيوم ومعادن لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...ZINC_WARNINGS],
	},

	// 198
	{
		id: 'sanso-d3-2500iu-28-tabs-ds4',
		name: 'sanso d3 2500 i.u. 28 tabs.',
		genericName: 'cholecalciferol',
		concentration: '2500 IU (28 tabs)',
		price: 50,
		matchKeywords: ['sanso d3 2500', 'سانسو د3 2500', 'vitamin d 2500', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د حسب التشخيص والتحاليل.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 199
	{
		id: 'calciux-plus-30-tabs-ds4',
		name: 'calciux plus 30 tabs.',
		genericName: 'calcium & vitamin d3 & vitamin e',
		concentration: '30 tabs',
		price: 105,
		matchKeywords: ['calciux plus', 'calciux', 'كالسييوكس', 'calcium', 'vitamin d3', 'vitamin e', '#calcium'],
		usage: 'كالسيوم + D3 (مع فيتامين E) لدعم العظام.',
		timing: 'مرة يومياً.',
		category: Category.CALCIUM_GROWTH,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...CALCIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
	},

	// 200
	{
		id: 'ferrosky-30-caps-ds4',
		name: 'ferrosky 30 caps.',
		genericName: 'ferrous bisglycinate & folic acid & vitamin b12 & vitamin c',
		concentration: '30 caps',
		price: 120,
		matchKeywords: ['ferrosky', 'فيروسكاي', 'bisglycinate', 'folic acid', 'b12', 'vitamin c', '#iron'],
		usage: 'حديد بيسجليسينات + فوليك + B12 + فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 201
	{
		id: 'fortiferrum-14-sachets-ds4',
		name: 'fortiferrum 14 sachets',
		genericName: 'iron & vitamin c',
		concentration: '14 sachets',
		price: 255,
		matchKeywords: ['fortiferrum', 'فورتيفيرم', 'iron sachets', 'vitamin c', '#iron'],
		usage: 'حديد + فيتامين C (أكياس) لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 202
	{
		id: 'galtin-sachets-10x10gm-ds4',
		name: 'galtin sachets 10 sachets *10gm',
		genericName: 'lactoferrin & iron & vitamin c & zinc & vitamin b complex',
		concentration: '10g (10 sachets)',
		price: 95,
		matchKeywords: ['galtin', 'جالتين', 'lactoferrin', 'iron', 'zinc', 'b complex', '#iron'],
		usage: 'لاكتوفرّين + حديد + زنك + فيتامينات لدعم علاج نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Sachets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 203
	{
		id: 'iroferin-30-caps-ds4',
		name: 'iroferin 30 caps.',
		genericName: 'iron & vitamin b6 & vitamin b12 & folic acid & zinc & copper',
		concentration: '30 caps',
		price: 99,
		matchKeywords: ['iroferin', 'ايروفيرين', 'iron', 'b6', 'b12', 'folic acid', 'zinc', '#iron'],
		usage: 'مكمل حديد مع فوليك وفيتامينات ب ومعادن لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 204
	{
		id: 'iroxen-syrup-120ml-ds4',
		name: 'iroxen syrup 120 ml',
		genericName: 'ferrous bisglycinate & vitamin c & vitamin b12 & vitamin b6',
		concentration: '120ml',
		price: 100,
		matchKeywords: ['iroxen syrup', 'iroxen', 'ايروكسين', 'bisglycinate', 'iron syrup', '#iron'],
		usage: 'شراب حديد (بيسجليسينات) مع فيتامينات لدعم علاج نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 144,
		minWeight: 8,
		maxWeight: 60,
		calculationRule: fixed('حسب إرشادات العبوة/الطبيب.'),
		warnings: IRON_SUPPLEMENT_WARNINGS,
	},

	// 205
	{
		id: 'liposom-d3-10000iu-30-caps-ds4',
		name: 'liposom-d3 10.000 i.u. 30 caps',
		genericName: 'cholecalciferol',
		concentration: '10000 IU (30 caps)',
		price: 180,
		matchKeywords: ['liposom-d3', 'liposom d3', 'ليپوسوم د3', 'vitamin d 10000', '#vitamin_d'],
		usage: 'فيتامين D3 عالي الجرعة لتصحيح نقص فيتامين د حسب التشخيص والتحاليل.',
		timing: 'حسب التشخيص والتحاليل.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('جرعة عالية: يحدد الطبيب الجرعة والمدة حسب التحاليل.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 206
	{
		id: 'octa-d3-oral-drops-30ml-ds4',
		name: 'octa d3 oral drops 30 ml',
		genericName: 'cholecalciferol',
		concentration: 'oral drops (30ml)',
		price: 69,
		matchKeywords: ['octa d3', 'اوكتا د3', 'vitamin d3 drops', '#vitamin_d'],
		usage: 'نقط فيتامين D3 للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 207
	{
		id: 'oneferol-bone-2800iu-ml-oral-drops-30ml-ds4',
		name: 'oneferol bone 2800 i.u./ml oral drops 30 ml',
		genericName: 'cholecalciferol',
		concentration: '2800 IU/ml (30ml)',
		price: 46,
		matchKeywords: ['oneferol bone', 'oneferol', 'وانفيرول', 'vitamin d3 drops', '2800 iu/ml', '#vitamin_d'],
		usage: 'نقط فيتامين D3 (تركيز محدد) للوقاية/علاج النقص حسب الإرشاد.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: D3_DAILY_GENERAL_RULE,
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 208
	{
		id: 'renovo-d3-tab-ds4',
		name: 'renovo d3 tab',
		genericName: 'vitamin d3',
		concentration: 'tablets',
		price: 139,
		matchKeywords: ['renovo d3', 'renovo', 'رينوفو', 'vitamin d3', '#vitamin_d'],
		usage: 'فيتامين D3 لدعم/علاج نقص فيتامين د.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً حسب الجرعة المدونة على العبوة.'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},

	// 209
	{
		id: 'rotone-complex-30-tabs-ds4',
		name: 'rotone complex 30 tabs',
		genericName: 'iron & zinc & copper & vitamin b1 & vitamin b2 & vitamin b6',
		concentration: '30 tabs',
		price: 99,
		matchKeywords: ['rotone complex 30', 'rotone', 'روتون', 'iron', 'zinc', 'copper', '#iron'],
		usage: 'مكمل متعدد لدعم الدم والطاقة (حديد + زنك + نحاس + فيتامينات ب).',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 250,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
	},

	// 210
	{
		id: 'three-drops-400iu-0-5ml-30ml-ds4',
		name: 'three drops 400 i.u./0.5ml 30 ml',
		genericName: 'cholecalciferol',
		concentration: '400 IU/0.5ml (30ml)',
		price: 49,
		matchKeywords: ['three drops', 'ثري دروبس', 'vitamin d3', '400 iu', '0.5ml', '#vitamin_d'],
		usage: 'نقط/محلول فيتامين D3 للرضع/الأطفال للوقاية أو علاج النقص.',
		timing: 'مرة يومياً.',
		category: Category.DIETARY_SUPPLEMENTS,
		form: 'Oral Drops',
		minAgeMonths: 0,
		maxAgeMonths: 216,
		minWeight: 2.5,
		maxWeight: 80,
		calculationRule: fixed('٠.٥ مل يومياً = ٤٠٠ وحدة دولية (تحقق من طريقة القياس على العبوة).'),
		warnings: FAT_SOLUBLE_VIT_WARNINGS,
	},
];

