
import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_IMMUNITY_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
];

const PROBIOTIC_WARNINGS = [
  ...GENERAL_IMMUNITY_WARNINGS,
  'افصل ٢–٣ ساعات عن المضاد الحيوي.',
  'لا يُؤخذ مع مشروب ساخن جداً.',
];

const HERBAL_IMMUNITY_WARNINGS = [
  ...GENERAL_IMMUNITY_WARNINGS,
  'في أمراض المناعة الذاتية أو عند استخدام أدوية مثبطة للمناعة: يُفضّل إعادة تقييم قبل الاستخدام.',
];

const OROPHARYNGEAL_LOZENGE_RULE = fixed('قرص استحلاب واحد يومياً بعد الأكل.');
const SYRUP_AGE_RULE_5_OR_10_ML = (_w: number, ageMonths: number) => (ageMonths < 144 ? '٥ مل مرة يومياً بعد الأكل' : '١٠ مل مرة يومياً بعد الأكل');

const BRONCHO_VAXOM_RULE = fixed('جرعة يومية واحدة لمدة ١٠ أيام متتالية كل شهر لمدة ٣ شهور (نظام ثابت).');

export const IMMUNITY_GROUP: Medication[] = [
  // 1
  {
    id: 'linex-adult-14-caps-immunity',
    name: 'linex adult 14 caps.',
    genericName: 'probiotic',
    concentration: '14 capsules',
    price: 225,
    matchKeywords: ['linex adult', 'linex', 'لينكس', 'probiotic', 'antibiotic', 'diarrhea', '#immunity', '#probiotic'],
    usage: 'بروبيوتيك (بكتيريا نافعة) لدعم المناعة المعوية وتقليل الإسهال المرتبط بالمضاد الحيوي.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: PROBIOTIC_WARNINGS,
  },

  // 5
  {
    id: 'broncho-vaxom-adults-7mg-10-caps-immunity',
    name: 'broncho-vaxom adults 7mg 10 caps',
    genericName: 'bacterial lysate',
    concentration: '7 mg (10 capsules)',
    price: 217,
    matchKeywords: ['broncho-vaxom adults', 'broncho vaxom', 'bacterial lysate', '#immunity'],
    usage: 'محفز مناعي (مستحضر بكتيري) لتقليل التهابات الجهاز التنفسي المتكررة في البالغين.',
    timing: 'مرة يومياً (نظام ١٠ أيام/شهر).',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: BRONCHO_VAXOM_RULE,
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 8
  {
    id: 'lacto-apex-5-20-caps-immunity',
    name: 'lacto-apex 5 - 20 caps.',
    genericName: 'lactoferrin & vitamin c & vitamin d3 & zinc & echinacea...',
    concentration: '20 capsules',
    price: 230,
    matchKeywords: ['lacto-apex', 'لاكتو ابكس', 'lactoferrin', 'zinc', 'vitamin d3', '#immunity'],
    usage: 'كبسولات لدعم المناعة (لاكتوفرين + فيتامينات/زنك + إكيناسيا).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 9
  {
    id: 'linex-10-sticks-powder-oral-susp-immunity',
    name: 'linex 10 sticks of pd. for oral susp.',
    genericName: 'probiotic',
    concentration: '10 sticks',
    price: 200,
    matchKeywords: ['linex sticks', 'linex', 'لينكس اكياس', 'probiotic', '#immunity', '#probiotic'],
    usage: 'بروبيوتيك على هيئة أكياس لدعم المناعة المعوية (مناسب لمن لا يفضل الكبسولات).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Powder for Oral Suspension Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٠ أيام.'),
    warnings: PROBIOTIC_WARNINGS,
  },

  // 10
  {
    id: 'immuguard-7-sachets-immunity',
    name: 'immuguard 7 sachets',
    genericName: 'high concentration bovine colostrum & vitamins & miner...',
    concentration: '7 sachets',
    price: 115,
    matchKeywords: ['immuguard 7', 'immuguard', 'ايميوجارد', 'colostrum', '#immunity'],
    usage: 'أكياس كولوستروم عالي التركيز مع فيتامينات/معادن لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ٧ أيام.'),
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 11
  {
    id: 'immulant-plus-20-caps-immunity',
    name: 'immulant plus 20 caps',
    genericName: 'echinacea & goldenseal, hydrastis canadensis',
    concentration: '20 capsules',
    price: 45,
    matchKeywords: ['immulant plus', 'ايمولانت بلس', 'echinacea', 'goldenseal', '#immunity'],
    usage: 'كبسولات عشبية لدعم المناعة خلال نزلات البرد المتكررة.',
    timing: '٣ مرات يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة ٣ مرات يومياً بعد الأكل لمدة ١٠ أيام.'),
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 12
  {
    id: 'linex-complex-14-capsules-immunity',
    name: 'linex complex 14 capsules',
    genericName: 'probiotic',
    concentration: '14 capsules',
    price: 300,
    matchKeywords: ['linex complex', 'linex', 'probiotic', '#immunity', '#probiotic'],
    usage: 'بروبيوتيك مركّز لدعم المناعة المعوية وتوازن البكتيريا النافعة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: PROBIOTIC_WARNINGS,
  },

  // 13
  {
    id: 'immuguard-14-sachets-immunity',
    name: 'immuguard 14 sachets',
    genericName: 'high concentration bovine colostrum & vitamins & miner...',
    concentration: '14 sachets',
    price: 195,
    matchKeywords: ['immuguard 14', 'immuguard', 'colostrum', '#immunity'],
    usage: 'أكياس كولوستروم عالي التركيز لدعم المناعة لمدة ١٤ يوم.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 14
  {
    id: 'lacto-apex-5-30-capsules-immunity',
    name: 'lacto-apex 5 - 30 capsules',
    genericName: 'lactoferrin & vitamin c & vitamin d3 & zinc & echinacea...',
    concentration: '30 capsules',
    price: 230,
    matchKeywords: ['lacto-apex 30', 'lacto-apex', 'lactoferrin', '#immunity'],
    usage: 'كبسولات لدعم المناعة (عبوة ٣٠ كبسولة).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 15
  {
    id: 'sansoimune-syrup-200-ml-immunity',
    name: 'sansoimune syrup 200 ml',
    genericName: 'echinaceae purpurea & ascorbic acid (vitamin c) & zin...',
    concentration: '200 ml syrup',
    price: 160,
    matchKeywords: ['sansoimune', 'سانسو ايميون', 'echinacea', 'vitamin c', 'zinc', 'syrup', '#immunity'],
    usage: 'شراب إكيناسيا + فيتامين C + زنك لدعم المناعة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 16
  {
    id: 'stravita-imune-120-ml-syrup-immunity',
    name: 'stravita imune 120 ml syrup',
    genericName: 'echinacea extract & elderberry extract & beta glucan & zinc s...',
    concentration: '120 ml syrup',
    price: 75,
    matchKeywords: ['stravita imune', 'stravita', 'سترافيتا ايميون', 'elderberry', 'beta glucan', 'honey', '#immunity', '#honey'],
    usage: 'شراب دعم المناعة (إكيناسيا + إيلدربيري + بيتا جلوكان + زنك).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 17
  {
    id: 'lactogemikan-30-hg-caps-immunity',
    name: 'lactogemikan 30 h.g. caps.',
    genericName: 'lactobacillus plantarum',
    concentration: '30 capsules',
    price: 255,
    matchKeywords: ['lactogemikan', 'لاكتوجيميكان', 'lactobacillus plantarum', 'probiotic', '#immunity', '#probiotic'],
    usage: 'بروبيوتيك (L. plantarum) لدعم المناعة المعوية وتقليل الانتفاخ.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: PROBIOTIC_WARNINGS,
  },

  // 18
  {
    id: 'isoca-10-sachets-immunity',
    name: 'isoca 10 sachets',
    genericName: 'liposomal bovine colostrum & liposomal lactoferrin & prps &...',
    concentration: '10 sachets',
    price: 500,
    matchKeywords: ['isoca', 'ايسوكا', 'liposomal colostrum', 'lactoferrin', '#immunity'],
    usage: 'أكياس مناعة (كولوستروم/لاكتوفرين ليبوسومال) لدعم المناعة بشكل مكثف.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٠ أيام.'),
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 19
  {
    id: 'linex-baby-drops-8-ml-immunity',
    name: 'linex baby drops 8 ml',
    genericName: 'probiotic',
    concentration: '8 ml oral drops',
    price: 350,
    matchKeywords: ['linex baby drops', 'linex baby', 'لينكس بيبي', 'probiotic drops', 'colic', 'غازات', '#immunity', '#probiotic'],
    usage: 'نقط بروبيوتيك للرضع لدعم المناعة المعوية وتقليل المغص.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 24,
    minWeight: 2,
    maxWeight: 12,
    calculationRule: fixed('٦ نقط مرة يومياً بعد الرضاعة.'),
    warnings: PROBIOTIC_WARNINGS,
  },

  // 20
  {
    id: 'chestokey-120-ml-syrup-immunity',
    name: 'chestokey 120 ml syrup',
    genericName: 'grapefruit seed extract & dark honey & vitamin c & zinc & vit...',
    concentration: '120 ml syrup',
    price: 69,
    matchKeywords: ['chestokey', 'تشستوكي', 'honey', 'grapefruit seed', 'cough', '#immunity', '#cough', '#honey'],
    usage: 'شراب عسل داكن مع فيتامينات/زنك لدعم المناعة وتهدئة الحلق.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: [...HERBAL_IMMUNITY_WARNINGS, 'العسل لا يُعطى للأطفال أقل من سنة.'],
  },

  // 21
  {
    id: 'cistapront-c-syrup-120-ml-immunity',
    name: 'cistapront c syurp 120 ml',
    genericName: 'cistus incanus dry extract & vitamin c',
    concentration: '120 ml syrup',
    price: 57,
    matchKeywords: ['cistapront c', 'cistapront', 'سيستابرونت', 'cistus', 'vitamin c', '#immunity'],
    usage: 'شراب Cistus + فيتامين C لدعم المناعة وتقليل أعراض البرد.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 22
  {
    id: 'immuno-mash-vitamin-c-zinc-30-tablets-immunity',
    name: 'immuno mash vitamin c + zinc 30 tablets',
    genericName: 'vitamin c & zinc',
    concentration: '30 tablets',
    price: 90,
    matchKeywords: ['immuno mash', 'ايمونو ماش', 'vitamin c', 'zinc', '#immunity', '#vitamin_c', '#zinc'],
    usage: 'أقراص فيتامين C + زنك لدعم المناعة (عبوة ٣٠ قرص).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_IMMUNITY_WARNINGS,
  },

  // 23
  {
    id: 'immunizzare-kids-syrup-120-ml-immunity',
    name: 'immunizzare kids syrup 120 ml',
    genericName: 'epicor & vitamin c & vitamin d & zinc',
    concentration: '120 ml syrup',
    price: 380,
    matchKeywords: ['immunizzare kids', 'immunizzare', 'ايمنيزاير', 'epicor', 'vitamin d', 'zinc', '#immunity'],
    usage: 'شراب مناعة للأطفال (EpiCor + فيتامينات + زنك).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: HERBAL_IMMUNITY_WARNINGS,
  },

  // 24
  {
    id: 'immunizzare-30-caps-immunity',
    name: 'immunizzare 30 caps.',
    genericName: 'epicor & vitamin c & vitamin d & zinc',
    concentration: '30 capsules',
    price: 550,
    matchKeywords: ['immunizzare', 'ايمنيزاير', 'epicor', 'vitamin c', 'vitamin d', 'zinc', '#immunity'],
    usage: 'كبسولات مناعة للبالغين (EpiCor + فيتامينات + زنك).',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_IMMUNITY_WARNINGS,
  },

  // 25
  {
    id: 'vivolat-10-sachets-immunity',
    name: 'vivolat 10 sachets',
    genericName: 'probiotic & prebiotic & zinc & lactoferrin',
    concentration: '10 sachets',
    price: 100,
    matchKeywords: ['vivolat', 'فيفولات', 'probiotic', 'prebiotic', 'zinc', 'lactoferrin', '#immunity', '#probiotic'],
    usage: 'أكياس بروبيوتيك + بريبيوتيك مع زنك ولاكتوفرين لدعم المناعة المعوية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٠ أيام.'),
    warnings: PROBIOTIC_WARNINGS,
  },
];

