
import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;
const toAr = (n: number | string) => n.toString().replace(/\d/g, d => '٠١٢٣٤٥٦٧٨٩'[parseInt(d, 10)]);
const roundVol = (vol: number): number => Math.round(vol * 2) / 2;

const GENERAL_LIVER_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
];

const URSO_WARNINGS = [
  ...GENERAL_LIVER_WARNINGS,
  'انسداد كامل بالقنوات المرارية: لا يُستخدم.',
];

export const LIVER_SUPPORT_GROUP: Medication[] = [
  // 1
  {
    id: 'hipamax-20-cap-liver',
    name: 'hipamax 20 cap',
    genericName: 'ascorbic acid & thiamine & riboflavin,vitamin b2 & pyridox...',
    concentration: '20 capsules',
    price: 66,
    matchKeywords: ['hipamax', 'هيباماكس', 'liver support', 'vitamin b', 'vitamin c', '#liver_support'],
    usage: 'كبسولات دعم للكبد مع فيتامينات مضادة للأكسدة.',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 2
  {
    id: 'ursoplus-20-cap-liver',
    name: 'ursoplus 20 cap.',
    genericName: 'silymarin & ursodeoxycholic acid',
    concentration: '20 capsules',
    price: 174,
    matchKeywords: ['ursoplus', 'اورسوبلس', 'ursodeoxycholic acid', 'silymarin', 'fatty liver', '#liver_support', '#fatty_liver'],
    usage: 'كبسولات لدعم الكبد والمرارة (سيليمارين + أورسوديوكسيكوليك).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: URSO_WARNINGS,
  },

  // 4
  {
    id: 'bional-30-cap-liver',
    name: 'bional 30 cap',
    genericName: 'milk thistle & astragalus root extract & zinc & selenium & vi...',
    concentration: '30 capsules',
    price: 192,
    matchKeywords: ['bional', 'بيونال', 'milk thistle', 'silymarin', 'zinc', 'selenium', '#liver_support'],
    usage: 'مركب عشبي/معدني لدعم الكبد (Milk thistle + مضادات أكسدة).',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 5
  {
    id: 'levanox-n-20-caps-liver',
    name: 'levanox n 20 caps.',
    genericName: 'milk thistle & catechu tincture & turmeric (curcuma longa l) r...',
    concentration: '20 capsules',
    price: 130,
    matchKeywords: ['levanox n', 'ليفانوكس', 'milk thistle', 'turmeric', '#liver_support'],
    usage: 'كبسولات دعم للكبد بمستخلصات عشبية (Milk thistle + Turmeric).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 6
  {
    id: 'lolawest-concentrate-5g-10ml-5-amp-liver',
    name: 'lolawest concentrate 5g/ 10ml 5 amp.',
    genericName: 'l-ornithine-l-aspartate',
    concentration: '5 g/10 ml (5 ampoules)',
    price: 185,
    matchKeywords: ['lolawest concentrate', 'lolawest', 'l-ornithine l-aspartate', 'ammonia', '#liver_support'],
    usage: 'أمبولات L-ornithine L-aspartate لدعم خفض الأمونيا في حالات الكبد المزمن.',
    timing: 'مرة يومياً (استخدام طبي).',
    category: Category.LIVER_SUPPORT,
    form: 'Ampoules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('أمبول واحد يومياً (استخدام داخل منشأة صحية).'),
    warnings: [...GENERAL_LIVER_WARNINGS, 'مخصص للاستخدام الطبي (حقن/تسريب) وليس للاستخدام المنزلي.'],
  },

  // 7
  {
    id: 'farcovit-b12-30-caps-liver',
    name: 'farcovit b12 30 caps.',
    genericName: 'cynara dry extract & inositol & orotic acid & phospholipids & s...',
    concentration: '30 capsules',
    price: 45,
    matchKeywords: ['farcovit b12', 'فاركوفيت', 'fatty liver', 'phospholipids', '#liver_support', '#fatty_liver'],
    usage: 'مركب لدعم الكبد الدهني وتجديد خلايا الكبد (فسفوليبيدات + مكونات داعمة).',
    timing: '3 مرات يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة 3 مرات يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 9
  {
    id: 'hepamarin-140mg-30-caps-liver',
    name: 'hepamarin 140mg 30 caps.',
    genericName: 'silymarin',
    concentration: '140 mg (30 capsules)',
    price: 150,
    matchKeywords: ['hepamarin', 'هيبامارين', 'silymarin', 'milk thistle', '#liver_support'],
    usage: 'سيليمارين لدعم وحماية خلايا الكبد من الإجهاد التأكسدي.',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 10
  {
    id: 'hepanox-20-caps-liver',
    name: 'hepanox 20 caps.',
    genericName: 'vitamin a (retinol palmitate) & vitamin e & ascorbic acid (vita...',
    concentration: '20 capsules',
    price: 150,
    matchKeywords: ['hepanox', 'هيبانوكس', 'vitamin a', 'vitamin e', '#liver_support'],
    usage: 'مركب فيتامينات مضادة للأكسدة لدعم الكبد.',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...GENERAL_LIVER_WARNINGS, 'يحتوي على فيتامين A: تجنب الجمع مع مصادر عالية من فيتامين A.'],
  },

  // 11
  {
    id: 'liverin-20-caps-liver',
    name: 'liverin 20 caps',
    genericName: 'silymarin & dl-methionine & inositol & thiamine hydrochlor...',
    concentration: '20 capsules',
    price: 125,
    matchKeywords: ['liverin', 'ليفريـن', 'silymarin', 'methionine', '#liver_support'],
    usage: 'كبسولات دعم للكبد (سيليمارين + ميثيونين + إينوزيتول + فيتامينات).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 12
  {
    id: 'selectival-20-capsules-liver',
    name: 'selectival 20 capsules',
    genericName: 'vitamin a & vitamin b12 & ascorbic acid & vitamin e & fo...',
    concentration: '20 capsules',
    price: 100,
    matchKeywords: ['selectival', 'سيليكتيفال', 'vitamins', '#liver_support'],
    usage: 'كبسولات فيتامينات ومضادات أكسدة لدعم الكبد.',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...GENERAL_LIVER_WARNINGS, 'يحتوي على فيتامين A: تجنب الجمع مع مصادر عالية من فيتامين A.'],
  },

  // 13
  {
    id: 'silipex-30-capsules-liver',
    name: 'silipex 30 capsules',
    genericName: 'silymarin & lecithin',
    concentration: '30 capsules',
    price: 90,
    matchKeywords: ['silipex', 'سيليبيكس', 'silymarin', 'lecithin', '#liver_support'],
    usage: 'كبسولات سيليمارين + ليسيثين لدعم الكبد والدهون.',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 14
  {
    id: 'hepachain-30-fc-tabs-liver',
    name: 'hepachain 30 f.c.tabs.',
    genericName: 'liver support formula',
    concentration: '30 F.C. tablets',
    price: 185,
    matchKeywords: ['hepachain 30', 'هيباشين', 'liver support', '#liver_support'],
    usage: 'أقراص دعم للكبد (تركيبة متعددة).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 15
  {
    id: 'high-nox-20-caps-liver',
    name: 'high nox 20 caps.',
    genericName: 'silymarin & ascorbic acid (vitamin c) & vitamin a (retino...',
    concentration: '20 capsules',
    price: 120,
    matchKeywords: ['high nox', 'هاي نوكس', 'silymarin', 'vitamin c', 'vitamin a', '#liver_support'],
    usage: 'كبسولات دعم للكبد مع مضادات أكسدة.',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...GENERAL_LIVER_WARNINGS, 'يحتوي على فيتامين A: تجنب الجمع مع مصادر عالية من فيتامين A.'],
  },

  // 16
  {
    id: 'suplfect-30-caps-liver',
    name: 'suplfect 30 caps.',
    genericName: 'echinacea & milk thistle & dandelion root',
    concentration: '30 capsules',
    price: 120,
    matchKeywords: ['suplfect', 'سوبلفكت', 'milk thistle', 'dandelion', '#liver_support'],
    usage: 'كبسولات دعم للكبد بمكونات عشبية (Milk thistle + Dandelion).',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 17
  {
    id: 'hepatic-forte-30-soft-gelatin-caps-liver',
    name: 'hepatic forte 30 soft gelatin caps.',
    genericName: 'orotic acid & phospholipids & silymarin',
    concentration: '30 soft gelatin capsules',
    price: 21,
    matchKeywords: ['hepatic forte', 'هيباتيك فورت', 'phospholipids', 'silymarin', '#liver_support'],
    usage: 'سوفت جل لدعم الكبد (فسفوليبيدات + سيليمارين).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('سوفت جل واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 18
  {
    id: 'hepaticum-10mg-ml-susp-120ml-liver',
    name: 'hepaticum 10mg/ml susp. 120ml',
    genericName: 'silymarin',
    concentration: '10 mg/ml (120 ml suspension)',
    price: 50,
    matchKeywords: ['hepaticum', 'هيباتيكم', 'silymarin', 'pediatric', '#liver_support'],
    usage: 'معلق سيليمارين للأطفال لدعم الكبد.',
    timing: '3 مرات يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Suspension',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 50,
    calculationRule: (w) => `${toAr(roundVol(w / 4))} مل ٣ مرات يومياً`,
    warnings: [...GENERAL_LIVER_WARNINGS, 'يُرج جيداً قبل الاستخدام.'],
  },

  // 19
  {
    id: 'hepato-forte-30-caps-liver',
    name: 'hepato-forte 30 caps.',
    genericName: 'phospholipids & nicotinamide & vitamin b{1}, thiamine & ribofl...',
    concentration: '30 capsules',
    price: 81,
    matchKeywords: ['hepato-forte', 'هيباتو فورت', 'phospholipids', '#liver_support'],
    usage: 'كبسولات فسفوليبيدات وفيتامينات ب لدعم الكبد الدهني.',
    timing: '3 مرات يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة 3 مرات يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 20
  {
    id: 'liver-albumin-plus-20-caps-liver',
    name: 'liver albumin plus 20 caps',
    genericName: 'l-glutamine & glutathione & l-methionine & milk thistle & ...',
    concentration: '20 capsules',
    price: 120,
    matchKeywords: ['liver albumin plus', 'جلوتاثيون', 'milk thistle', '#liver_support'],
    usage: 'كبسولات دعم للكبد بمضادات أكسدة وأحماض أمينية (جلوتاثيون/ميثيونين).',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 21
  {
    id: 'aspatrend-5gm-10ml-5-vials-iv-liver',
    name: 'aspatrend 5gm/10ml 5 vials . i.v. inf.',
    genericName: 'l-ornithine-l-aspartate',
    concentration: '5 g/10 ml (5 vials)',
    price: 190,
    matchKeywords: ['aspatrend vials', 'aspatrend', 'l-ornithine l-aspartate', 'iv infusion', '#liver_support'],
    usage: 'فيالات تسريب وريدي L-ornithine L-aspartate لدعم خفض الأمونيا.',
    timing: 'مرة يومياً (استخدام طبي).',
    category: Category.LIVER_SUPPORT,
    form: 'I.V. Infusion Vial',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('فيال واحد يومياً بالتسريب الوريدي (استخدام داخل منشأة صحية).'),
    warnings: [...GENERAL_LIVER_WARNINGS, 'مخصص للاستخدام الطبي (تسريب وريدي).'],
  },

  // 22
  {
    id: 'essentiale-300mg-30-caps-liver',
    name: 'essentiale 300mg 30 caps.',
    genericName: 'phospholipids',
    concentration: '300 mg (30 capsules)',
    price: 195,
    matchKeywords: ['essentiale', 'ايسينشيال', 'phospholipids', '#liver_support', '#fatty_liver'],
    usage: 'فسفوليبيدات لدعم الكبد الدهني وتجديد الخلايا.',
    timing: '3 مرات يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة 3 مرات يومياً مع الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 23
  {
    id: 'ursodiol-250mg-20-caps-liver',
    name: 'ursodiol 250mg 20 caps',
    genericName: 'ursodeoxycholic acid',
    concentration: '250 mg (20 capsules)',
    price: 162,
    matchKeywords: ['ursodiol', 'اورسوديول', 'ursodeoxycholic acid', 'cholestasis', '#liver_support'],
    usage: 'أورسوديوكسيكوليك أسيد لدعم حالات ركود الصفراء وبعض اضطرابات المرارة.',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: URSO_WARNINGS,
  },

  // 24
  {
    id: 'aspatrend-10-sachets-liver',
    name: 'aspatrend 10 sachets',
    genericName: 'l-ornithine-l-aspartate',
    concentration: '10 sachets',
    price: 160,
    matchKeywords: ['aspatrend 10 sachets', 'aspatrend', 'l-ornithine l-aspartate', '#liver_support'],
    usage: 'أكياس L-ornithine L-aspartate لدعم الكبد وتقليل الأمونيا.',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 25
  {
    id: 'cyncholine-plus-20-caps-liver',
    name: 'cyncholine plus 20 caps.',
    genericName: 'cynara dry extract & silymarin & mentha & magnesium oxide',
    concentration: '20 capsules',
    price: 45,
    matchKeywords: ['cyncholine plus', 'سينكولين بلس', 'cynara', 'silymarin', '#liver_support'],
    usage: 'كبسولات دعم للكبد والمرارة (خرشوف + سيليمارين).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 26
  {
    id: 'aspatrend-6-sachets-liver',
    name: 'aspatrend 6 sachets',
    genericName: 'l-ornithine-l-aspartate',
    concentration: '6 sachets',
    price: 96,
    matchKeywords: ['aspatrend 6 sachets', 'aspatrend', '#liver_support'],
    usage: 'أكياس L-ornithine L-aspartate لدعم الكبد.',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 27
  {
    id: 'cemixo-live-30-caps-liver',
    name: 'cemixo live 30 caps.',
    genericName: 'milk thistle & liquorice & sodium selenate',
    concentration: '30 capsules',
    price: 75,
    matchKeywords: ['cemixo live', 'سيميكسو', 'milk thistle', 'selenium', '#liver_support'],
    usage: 'مركب لدعم الكبد (Milk thistle + سيلينيوم).',
    timing: 'مرة يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 28
  {
    id: 'cyncholine-20-caps-liver',
    name: 'cyncholine 20caps.',
    genericName: 'cynara dry extract & silymarin & mentha & magnesium oxide',
    concentration: '20 capsules',
    price: 35,
    matchKeywords: ['cyncholine', 'سينكولين', 'cynara', 'silymarin', '#liver_support'],
    usage: 'كبسولات دعم للكبد والمرارة (خرشوف + سيليمارين).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },

  // 29
  {
    id: 'hepachain-60-fc-tabs-liver',
    name: 'hepachain 60 f.c.tabs.',
    genericName: 'liver support formula',
    concentration: '60 F.C. tablets',
    price: 350,
    matchKeywords: ['hepachain 60', 'هيباشين', 'liver support', '#liver_support'],
    usage: 'أقراص دعم للكبد (عبوة ٦٠ قرص).',
    timing: 'مرتين يومياً.',
    category: Category.LIVER_SUPPORT,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_LIVER_WARNINGS,
  },
];

