import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
  'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين A أو D أو E أو K بجرعات عالية.',
  'الجرعات الزائدة من فيتامينات A/D/E/K قد تسبب أعراض تسمم أو اضطرابات نزف.',
];

const IRON_SUPPLEMENT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
  'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
  'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const OMEGA_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'يُستخدم بحذر مع أدوية السيولة أو اضطرابات النزف.',
  'قد يسبب تجشؤ بطعم السمك/اضطراب معدة؛ يؤخذ مع الطعام.',
];

const HERBAL_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'أوقف الاستخدام إذا ظهرت حساسية (طفح/حكة/تورم).',
];

const ZINC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const BONE_SUPPORT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
  'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const MELATONIN_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب نعاس صباحي إذا زادت الجرعة أو تأخر وقت النوم.',
  'تجنب استخدامه نهاراً أو قبل قيادة/تشغيل آلات.',
];

export const MULTIVITAMINS_SUPPLEMENTS_3: Medication[] = [
  // ==========================================
  // multivitamins + supplements 3
  // Items: 130 → 194
  // ==========================================

  // 130
  {
    id: 'gamastiene-10-sachets-mvs3',
    name: 'gamastiene 10 sachets',
    genericName: 'acetylcysteine & thyme & vitamin c',
    concentration: '10 sachets',
    price: 75,
    matchKeywords: ['gamastiene', 'جاماستين', 'acetylcysteine', 'nac', 'thyme', 'vitamin c', 'cough', 'كحة', 'phlegm', 'بلغم', 'respiratory', 'صدر', '#multi_vitamins'],
    usage: 'دعم الجهاز التنفسي وتقليل لزوجة البلغم (NAC + زعتر + C).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد بعد الأكل مرة إلى مرتين يومياً لمدة ٥–٧ أيام.'),
    warnings: [...HERBAL_WARNINGS, 'إذا كان لديك ربو/قرحة معدة نشطة استخدمه بحذر.'],
  },

  // 131
  {
    id: 'grodesire-syrup-120ml-mvs3',
    name: 'grodesire syrup 120 ml',
    genericName: 'vitamin b1 & vitamin b2 & vitamin b3 & vitamin b6 & fennel oil',
    concentration: '120ml',
    price: 65,
    matchKeywords: ['grodesire', 'جرو ديزاير', 'b1', 'b2', 'b3', 'b6', 'fennel oil', 'شمر', 'appetite', 'فاتح شهية', 'digestive', 'مهضم', '#appetizer', '#multi_vitamins'],
    usage: 'شراب فيتامينات ب مع زيت الشمر لدعم الشهية والهضم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: HERBAL_WARNINGS,
  },

  // 132
  {
    id: 'vitalox-complete-a-z-30-tabs-mvs3',
    name: 'vitalox complete a-z 30 tabs.',
    genericName: 'multivitamins & minerals',
    concentration: '30 tabs',
    price: 420,
    matchKeywords: ['vitalox complete', 'vitalox a-z', 'فيتالوكس', 'a-z', 'multivitamins', 'minerals', 'مولتي فيتامين', 'معادن', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن (A–Z) لدعم الطاقة والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 133
  {
    id: 'banod-10-sachets-mvs3',
    name: 'banod 10 sachets',
    genericName: 'colostrum & zinc & omega 3 & lactoferrin',
    concentration: '10 sachets',
    price: 130,
    matchKeywords: ['banod 10', 'banod', 'بانود', 'colostrum', 'lactoferrin', 'zinc', 'omega 3', 'immunity', 'مناعة', '#multi_vitamins', '#immunity'],
    usage: 'دعم المناعة (لاكتوفرّين + كولوستروم + زنك + أوميجا).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...ZINC_WARNINGS, 'غير مناسب لحساسية بروتين اللبن.'],
  },

  // 134
  {
    id: 'romsey-120ml-syrup-mvs3',
    name: 'romsey 120 ml syrup',
    genericName: 'omega 3 fatty acid & epa & dha & omega 6 fatty acid & gla & vitamin e',
    concentration: '120ml',
    price: 115,
    matchKeywords: ['romsey', 'رومسي', 'omega 3', 'epa', 'dha', 'gla', 'omega 6', 'vitamin e', 'kids omega', 'اوميجا اطفال', '#multi_vitamins', '#omega3'],
    usage: 'شراب أوميجا 3/6 مع فيتامين E لدعم المخ والتركيز.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 135
  {
    id: 'vistava-30-tabs-mvs3',
    name: 'vistava 30 tabs',
    genericName: 'lutein & zeaxanthin & lycopene & vitamin c & vitamin d & vitamin e',
    concentration: '30 tabs',
    price: 155,
    matchKeywords: ['vistava', 'فيستافا', 'lutein', 'zeaxanthin', 'lycopene', 'eye', 'عين', 'macula', 'شبكية', 'antioxidant', 'مضاد اكسدة', '#multi_vitamins', '#antioxidants'],
    usage: 'مضادات أكسدة للعين (لوتين + زياكسانثين) مع فيتامينات.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 136
  {
    id: 'vitalogy-b-30-tab-mvs3',
    name: 'vitalogy b 30 tab',
    genericName: 'vitamin b12 & vitamin b6 & folic acid & calcium',
    concentration: '30 tabs',
    price: 97,
    matchKeywords: ['vitalogy b', 'فيتالوجي ب', 'b12', 'b6', 'folic acid', 'calcium', 'neuropathy', 'تنميل', '#multi_vitamins', '#vitamin_b'],
    usage: 'دعم الأعصاب وتكوين الدم (B12 + B6 + فوليك) مع كالسيوم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 137
  {
    id: 'heligrow-30-fc-tabs-mvs3',
    name: 'heligrow 30 f.c.tabs.',
    genericName: 'zinc & biotin & vitamin b & folic acid & vitamin c',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['heligrow', 'هيلي جرو', 'zinc', 'biotin', 'folic acid', 'vitamin c', 'hair', 'شعر', 'nails', 'اظافر', '#multi_vitamins', '#zinc'],
    usage: 'دعم الشعر والأظافر (زنك + بيوتين + فيتامينات).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 138
  {
    id: 'afromed-30-caps-mvs3',
    name: 'afromed 30 caps.',
    genericName: 'tribulus & ginseng & maca root extract & ginkgo & zinc',
    concentration: '30 caps',
    price: 240,
    matchKeywords: ['afromed', 'افروميد', 'tribulus', 'ginseng', 'maca', 'ginkgo', 'zinc', 'energy', 'طاقة', 'libido', 'رغبة', '#multi_vitamins'],
    usage: 'مكمل للطاقة والقدرة (مزيج أعشاب + زنك).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, ...ZINC_WARNINGS, 'قد يزيد النزف مع مسيلات الدم (جينكو). قد يسبب أرق/خفقان.'],
  },

  // 139
  {
    id: 'mr-bear-omega-syrup-400ml-mvs3',
    name: 'mr. bear omega syrup 400 ml',
    genericName: 'multivitamins',
    concentration: '400ml',
    price: 1400,
    matchKeywords: ['mr bear omega', 'مستر بير اوميجا', 'omega syrup', 'kids', 'فيتامينات اطفال', 'focus', 'تركيز', '#multi_vitamins', '#omega3'],
    usage: 'شراب فيتامينات وأوميجا للأطفال لدعم التركيز والنمو.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: OMEGA_WARNINGS,
  },

  // 140
  {
    id: 'fuelkd-120ml-syrup-mvs3',
    name: 'fuelkd 120ml syrup',
    genericName: 'vitamin c & inositol & vitamin b3 & choline & vitamin b1 & vitamin b2',
    concentration: '120ml',
    price: 200,
    matchKeywords: ['fuelkd', 'فيويل كيد', 'inositol', 'choline', 'b1', 'b2', 'b3', 'vitamin c', 'appetite', 'فاتح شهية', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'شراب فيتامينات لدعم الشهية والطاقة (B + C + كولين/إينوزيتول).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 141
  {
    id: 'cobafolic-ino-30-tabs-mvs3',
    name: 'cobafolic ino 30 tabs',
    genericName: 'myo-inositol & d-chiro inositol & quatrefolic & cholecalciferol',
    concentration: '30 tabs',
    price: 375,
    matchKeywords: ['cobafolic ino', 'كوبافوليك اينو', 'inositol', 'd-chiro', 'quatrefolic', 'methylfolate', 'vitamin d3', 'pcos', 'تكيس', '#multi_vitamins'],
    usage: 'دعم تكيس المبايض وتنظيم الدورة (إينوزيتول + ميثيل فولات + D3).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 142
  {
    id: 'relanta-20-tabs-mvs3',
    name: 'relanta 20 tabs',
    genericName: 'calcium carbonate & magnesium & copper & zinc',
    concentration: '20 tabs',
    price: 86.75,
    matchKeywords: ['relanta', 'ريلانتا', 'calcium carbonate', 'magnesium', 'zinc', 'copper', 'bones', 'عظام', 'cramps', 'تقلصات', '#multi_vitamins', '#calcium'],
    usage: 'مكمل معادن لدعم العظام والتقلصات (كالسيوم/ماغنسيوم/زنك/نحاس).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 143
  {
    id: 'avefox-30-tab-mvs3',
    name: 'avefox 30 tab',
    genericName: 'vitamin b1 & vitamin b6 & vitamin b7 & vitamin b12 & folic acid',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['avefox', 'افيفوكس', 'b1', 'b6', 'b7', 'biotin', 'b12', 'folic', 'neuropathy', 'تنميل', 'hair', 'شعر', '#multi_vitamins'],
    usage: 'دعم الأعصاب والشعر (فيتامينات ب + بيوتين + فوليك).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 144
  {
    id: 'isoglobin-syrup-120ml-mvs3',
    name: 'isoglobin syrup 120 ml',
    genericName: 'lysine & vitamin c & vitamin b3 & iron & zinc & vitamin b6 & vitamin b12',
    concentration: '120ml',
    price: 65,
    matchKeywords: ['isoglobin', 'ايسوجلوبين', 'lysine', 'iron', 'zinc', 'b12', 'b6', 'vitamin c', 'appetite', 'فاتح شهية', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب فاتح شهية مع دعم للدم (ليسين + حديد + زنك + فيتامينات).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 145
  {
    id: 'utp-kromicat-30-tablet-mvs3',
    name: 'utp kromicat 30 tablet',
    genericName: 'chromium & vitamin a & vitamin c & vitamin d & vitamin e',
    concentration: '30 tabs',
    price: 165,
    matchKeywords: ['utp kromicat', 'kromicat', 'كروميكت', 'chromium', 'vitamin a', 'vitamin d', 'vitamin e', 'sugar', 'سكر', 'cravings', 'اشتهاء', '#multi_vitamins'],
    usage: 'كروميوم مع فيتامينات لدعم تنظيم الشهية والتمثيل الغذائي.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 146
  {
    id: 'roson-20-tabs-mvs3',
    name: 'roson 20 tabs',
    genericName: 'folic acid & vitamin b12 & vitamin b6',
    concentration: '20 tabs',
    price: 64,
    matchKeywords: ['roson', 'روسون', 'folic', 'b12', 'b6', 'neuropathy', 'تنميل', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'فوليك + B12 + B6 لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 147
  {
    id: 'movinerve-sublingual-30-tabs-mvs3',
    name: 'movinerve sub lingual 30 tablets',
    genericName: 'vitamin b12 & vitamin b6 & folic acid',
    concentration: '30 tablets',
    price: 110,
    matchKeywords: ['movinerve', 'موفينيرف', 'sublingual', 'تحت اللسان', 'b12', 'b6', 'folic', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'B12 + B6 + فوليك تحت اللسان لدعم الأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 148
  {
    id: 'dugofertin-20-tabs-mvs3',
    name: 'dugofertin 20 tabs',
    genericName: 'l-taurine & glutathione & l-arginine & l-carnitine & magnesium',
    concentration: '20 tabs',
    price: 260,
    matchKeywords: ['dugofertin', 'دوجوفرتين', 'taurine', 'glutathione', 'arginine', 'carnitine', 'magnesium', 'fertility', 'خصوبة', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'مكمل لدعم الطاقة والخصوبة (أحماض أمينية + مضادات أكسدة + ماغنسيوم).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 149
  {
    id: 'rafada-b-complex-odf-mvs3',
    name: 'rafada b complex odf',
    genericName: 'vitamin b12 & vitamin b6 & folic acid & biotin',
    concentration: 'Orodispersible film',
    price: 79,
    matchKeywords: ['rafada', 'رافادا', 'odf', 'film', 'شريط فموي', 'b12', 'b6', 'folic', 'biotin', 'hair', 'شعر', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'شريط فموي سريع الذوبان لدعم الأعصاب والشعر (B + فوليك + بيوتين).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Orodispersible Film',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('شريط واحد يومياً يوضع على اللسان حتى يذوب.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 150
  {
    id: 'landymo-120ml-syrup-mvs3',
    name: 'landymo 120 ml syrup',
    genericName: 'liposomal iron & vitamin c & zinc & vitamin e & vitamin b-complex',
    concentration: '120ml',
    price: 50,
    matchKeywords: ['landymo', 'لاندايمو', 'liposomal iron', 'iron syrup', 'vitamin c', 'zinc', 'b complex', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب حديد ليبوسومال مع فيتامينات لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 151
  {
    id: 'mandsolex-120ml-syrup-mvs3',
    name: 'mandsolex 120 ml syrup',
    genericName: 'vitamin b1 & vitamin b2 & vitamin b6 & vitamin b3 & peppermint oil',
    concentration: '120ml',
    price: 85,
    matchKeywords: ['mandsolex', 'ماندسوليكس', 'peppermint oil', 'نعناع', 'b vitamins', 'appetite', 'فاتح شهية', 'bloating', 'انتفاخ', '#multi_vitamins'],
    usage: 'شراب فيتامينات ب مع زيت النعناع لدعم الهضم وتقليل الانتفاخ.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: HERBAL_WARNINGS,
  },

  // 152
  {
    id: 'mesky-10ml-drops-mvs3',
    name: 'mesky 10 ml drops',
    genericName: 'wheat germ oil',
    concentration: '10ml',
    price: 75,
    matchKeywords: ['mesky', 'مسكي', 'wheat germ oil', 'vitamin e', 'hair', 'شعر', 'skin', 'بشرة', '#multi_vitamins'],
    usage: 'زيت جنين القمح نقط لدعم البشرة والشعر.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('٠.٥ مل يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 153
  {
    id: 'vegalacap-20-caps-mvs3',
    name: 'vegalacap 20 caps',
    genericName: 'vitamin c & copper & iron & vitamin b12 & folate dfe & lactoferrin',
    concentration: '20 caps',
    price: 280,
    matchKeywords: ['vegalacap', 'فيجالا كاب', 'lactoferrin', 'iron', 'b12', 'folate', 'copper', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل دعم للدم (حديد + لاكتوفرّين + B12 + فولات + C).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 154
  {
    id: 'ostonajo-30-tab-mvs3',
    name: 'ostonajo 30 tab',
    genericName: 'calcium & magnesium & vitamin d3 & zinc & selenium',
    concentration: '30 tabs',
    price: 120,
    matchKeywords: ['ostonajo', 'اوستوناجو', 'calcium', 'magnesium', 'vitamin d3', 'zinc', 'selenium', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'دعم العظام (كالسيوم + ماغنسيوم + D3 + زنك + سيلينيوم).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 155
  {
    id: 'medixir-d3-k2-15ml-oral-drops-mvs3',
    name: 'medixir d3+k2 15 ml oral drops',
    genericName: 'vitamin d3 & vitamin k2',
    concentration: '15ml',
    price: 60,
    matchKeywords: ['medixir', 'ميدكسير', 'd3 k2 drops', 'vitamin d3', 'vitamin k2', 'bones', 'عظام', '#multi_vitamins', '#vitamin_d', '#vitamin_k'],
    usage: 'نقط D3 + K2 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٠.٥ مل يومياً بعد الأكل' : '١ مل يومياً بعد الأكل'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين ومضادات التجلط.'],
  },

  // 156
  {
    id: 'k2-calcirave-30-fc-tabs-mvs3',
    name: 'k2-calcirave 30 f.c. tabs.',
    genericName: 'vitamin k & vitamin d & calcium & magnesium & vitamin c',
    concentration: '30 tabs',
    price: 147,
    matchKeywords: ['k2-calcirave 30 fc', 'k2 calcirave', 'calcirave', 'vitamin k', 'vitamin d', 'calcium', 'magnesium', 'vitamin c', '#multi_vitamins', '#calcium'],
    usage: 'مكمل عظام (K + D + كالسيوم + ماغنسيوم + C).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K قد يتداخل مع الوارفارين.'],
  },

  // 157
  {
    id: 'limitless-c-zinc-plus-20-fc-tabs-mvs3',
    name: 'limitless c-zinc plus 20 f.c. tabs.',
    genericName: 'vitamin c & zinc & vitamin d3 & magnesium & echinacea & elderberry',
    concentration: '20 tabs',
    price: 114,
    matchKeywords: ['limitless c-zinc plus', 'limitless', 'ليميتلس', 'c zinc', 'vitamin d3', 'magnesium', 'echinacea', 'elderberry', 'cold', 'برد', 'immunity', 'مناعة', '#vitamin_c', '#multi_vitamins'],
    usage: 'دعم المناعة أثناء نزلات البرد (C + زنك + D3 + أعشاب).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة ١٠–١٤ يوم.'),
    warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, ...HERBAL_WARNINGS],
  },

  // 158
  {
    id: 'olysre-20-tabs-mvs3',
    name: 'olysre 20 tabs',
    genericName: 'methylfolate & vitamin b12',
    concentration: '20 tabs',
    price: 150,
    matchKeywords: ['olysre', 'اوليسري', 'methylfolate', 'l-methylfolate', 'b12', 'neuropathy', 'تنميل', 'pregnancy', 'حمل', '#multi_vitamins'],
    usage: 'ميثيل فولات + B12 لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 159
  {
    id: 'gapivent-syrup-100ml-mvs3',
    name: 'gapivent syrup 100ml',
    genericName: 'ivy extract & licorice extract & thyme extract',
    concentration: '100ml',
    price: 60,
    matchKeywords: ['gapivent', 'جابيڤنت', 'ivy', 'licorice', 'thyme', 'cough', 'كحة', 'bronchitis', 'شعب', '#respiratory', '#multi_vitamins'],
    usage: 'شراب عشبي لدعم السعال وتهدئة الشعب (لبلاب + عرقسوس + زعتر).',
    timing: '٣ مرات يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل ٣ مرات يومياً' : '١٠ مل ٣ مرات يومياً'),
    warnings: [...HERBAL_WARNINGS, 'غير مناسب للأطفال أقل من سنتين.'],
  },

  // 160
  {
    id: 'incan-b-comb-30-fc-tabs-mvs3',
    name: 'incan-b comb 30 f.c.tabs.',
    genericName: 'methylcobalamin & benfotiamine & vitamin b6',
    concentration: '30 tabs',
    price: 129,
    matchKeywords: ['incan-b', 'incan b comb', 'انكان بي', 'methylcobalamin', 'benfotiamine', 'b6', 'neuropathy', 'اعصاب السكر', 'diabetic neuropathy', '#multi_vitamins', '#vitamin_b'],
    usage: 'دعم الأعصاب الطرفية (ميثيل كوبالامين + بنفوتيامين + B6).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 161
  {
    id: 'osinohance-20-tabs-mvs3',
    name: 'osinohance 20 tabs',
    genericName: 'calcium bisglycinate & vitamin k2 & vitamin d3',
    concentration: '20 tabs',
    price: 85,
    matchKeywords: ['osinohance', 'اوسينوهانس', 'calcium bisglycinate', 'vitamin k2', 'vitamin d3', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'دعم العظام (كالسيوم + D3 + K2).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين.'],
  },

  // 162
  {
    id: 'yummyfort-120ml-syrup-mvs3',
    name: 'yummyfort 120 ml syrup',
    genericName: 'folic acid & vitamin b1 & vitamin b2 & vitamin b6 & minerals',
    concentration: '120ml',
    price: 60,
    matchKeywords: ['yummyfort', 'يامي فورت', 'folic acid', 'b1', 'b2', 'b6', 'minerals', 'appetite', 'فاتح شهية', 'kids vitamins', 'فيتامين اطفال', '#multi_vitamins'],
    usage: 'شراب فيتامينات ومعادن للأطفال لدعم الشهية والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 163
  {
    id: 'dexcoba-30-sublingual-tab-mvs3',
    name: 'dexcoba 30 sublingual tab',
    genericName: 'vitamin b12 & folic acid & vitamin b6',
    concentration: '30 tabs',
    price: 135,
    matchKeywords: ['dexcoba', 'ديكسكوبا', 'sublingual', 'تحت اللسان', 'b12', 'folic', 'b6', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'B12 + فوليك + B6 تحت اللسان لدعم الأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 164
  {
    id: 'kiddijunior-120ml-syrup-mvs3',
    name: 'kiddijunior 120 ml syrup',
    genericName: 'calcium & magnesium & vitamin c & niacin & vitamin e & dexapanthenol',
    concentration: '120ml',
    price: 55,
    matchKeywords: ['kiddijunior', 'كيدي جونيور', 'calcium', 'magnesium', 'vitamin c', 'niacin', 'vitamin e', 'bones', 'عظام', 'growth', 'نمو', '#multi_vitamins', '#calcium'],
    usage: 'شراب فيتامينات ومعادن للأطفال لدعم النمو والعظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 165
  {
    id: 'banod-7-sachets-mvs3',
    name: 'banod 7 sachets',
    genericName: 'colostrum & zinc & omega 3 & lactoferrin',
    concentration: '7 sachets',
    price: 148,
    matchKeywords: ['banod 7', 'banod', 'بانود', 'colostrum', 'lactoferrin', 'zinc', 'omega 3', 'immunity', 'مناعة', '#multi_vitamins', '#immunity'],
    usage: 'دعم المناعة (لاكتوفرّين + كولوستروم + زنك + أوميجا).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...ZINC_WARNINGS, 'غير مناسب لحساسية بروتين اللبن.'],
  },

  // 166
  {
    id: 'bebe-vit-oral-drops-30ml-mvs3',
    name: 'bebe-vit oral drops 30 ml',
    genericName: 'vitamin a palmitate & vitamin d3 (cholecalciferol) & vitamin e acetate',
    concentration: '30ml',
    price: 15,
    matchKeywords: ['bebe-vit', 'bebe vit', 'بيبي فيت', 'vitamin a', 'vitamin d3', 'vitamin e', 'infant', 'رضع', 'drops', 'نقط', '#multi_vitamins'],
    usage: 'نقط فيتامينات للرضع (A + D3 + E).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 24,
    minWeight: 2,
    maxWeight: 15,
    calculationRule: fixed('٠.٥ مل يومياً بعد الرضاعة.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 167
  {
    id: 'biovita-60-gummies-mvs3',
    name: 'biovita 60 gummies',
    genericName: 'multivitamin & biotin & antioxidants',
    concentration: '60 gummies',
    price: 250,
    matchKeywords: ['biovita gummies', 'biovita', 'بايوفيتا', 'gummies', 'multivitamin', 'biotin', 'antioxidants', 'kids', 'اطفال', '#multi_vitamins'],
    usage: 'جُمّي مولتي فيتامين مع بيوتين ومضادات أكسدة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? 'قطعة واحدة يومياً' : 'قطعتان يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 168
  {
    id: 'methylzila-1000-1000mg-30-tab-mvs3',
    name: 'methylzila 1000/1000 mg 30 tab',
    genericName: 'methylfolate & methylcobalamin',
    concentration: '30 tabs',
    price: 95,
    matchKeywords: ['methylzila', 'ميثيلزيلا', 'methylfolate', 'methylcobalamin', 'b12', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'ميثيل فولات + ميثيل كوبالامين لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 169
  {
    id: 'dugofola-20-sublingual-tabs-mvs3',
    name: 'dugofola 20 sublingual tablets',
    genericName: '5-methyl tetrahydrofolate & methylcobalamin & vitamin b6',
    concentration: '20 tabs',
    price: 125,
    matchKeywords: ['dugofola', 'دوجوفولا', 'sublingual', 'تحت اللسان', 'methylfolate', 'methylcobalamin', 'b6', '#multi_vitamins'],
    usage: 'ميثيل فولات + ميثيل كوبالامين + B6 تحت اللسان لدعم الأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 170
  {
    id: 'kode-joints-30-tab-mvs3',
    name: 'kode joints 30 tab',
    genericName: 'glucosamine & chondroitin & hyaluronic acid & calcium',
    concentration: '30 tabs',
    price: 225,
    matchKeywords: ['kode joints', 'كود جوينتس', 'glucosamine', 'chondroitin', 'hyaluronic acid', 'calcium', 'joints', 'مفاصل', 'knee', 'خشونة', '#multi_vitamins', '#joint_support'],
    usage: 'دعم المفاصل والغضاريف (جلوكوزامين/كوندرويتين/هيالورونيك).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 171
  {
    id: 'c-plus-30-tab-mvs3',
    name: 'c-plus 30 tab',
    genericName: 'ascorbic acid (vitamin c) & bioflavonoids & calcium & hesperidin',
    concentration: '30 tabs',
    price: 225,
    matchKeywords: ['c-plus', 'سي بلس', 'vitamin c', 'bioflavonoids', 'hesperidin', 'calcium', 'immunity', 'مناعة', '#multi_vitamins', '#vitamin_c'],
    usage: 'فيتامين C مع بيوفلافونويدز لدعم المناعة والأوعية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 172
  {
    id: 'optacado-30-cap-mvs3',
    name: 'optacado 30 cap',
    genericName: 'avocado oil & soya bean oil',
    concentration: '30 caps',
    price: 202,
    matchKeywords: ['optacado', 'اوبتاكادو', 'avocado oil', 'soybean oil', 'hair', 'شعر', 'skin', 'بشرة', '#multi_vitamins'],
    usage: 'زيوت نباتية لدعم البشرة والشعر.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 173
  {
    id: 'ginkonoro-30-tablet-mvs3',
    name: 'ginkonoro 30 tablet',
    genericName: 'ginkgo biloba & choline chloride & lecithin & vitamin b complex',
    concentration: '30 tabs',
    price: 170,
    matchKeywords: ['ginkonoro', 'جينكونورو', 'ginkgo', 'choline', 'lecithin', 'b complex', 'memory', 'ذاكرة', 'concentration', 'تركيز', '#multi_vitamins'],
    usage: 'دعم التركيز والذاكرة (جينكو + كولين + ليسيثين + فيتامينات ب).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد النزف مع مسيلات الدم (جينكو).'],
  },

  // 174
  {
    id: 'easyron-30-tablets-mvs3',
    name: 'easyron 30 tablets',
    genericName: 'natural iron & zinc & copper & vitamin c & vitamin d3 & beta carotene',
    concentration: '30 tabs',
    price: 105,
    matchKeywords: ['easyron', 'ايزي رون', 'iron', 'natural iron', 'zinc', 'copper', 'vitamin c', 'vitamin d3', 'beta carotene', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع معادن وفيتامينات لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 175
  {
    id: 'enera-collagen-10-sachets-mvs3',
    name: 'enera collagen 10 sachets',
    genericName: 'collagen & magnesium & calcium & vitamin c',
    concentration: '10 sachets',
    price: 300,
    matchKeywords: ['enera collagen', 'انيرا كولاجين', 'collagen', 'magnesium', 'calcium', 'vitamin c', 'joints', 'مفاصل', 'skin', 'بشرة', '#multi_vitamins'],
    usage: 'كولاجين مع معادن وفيتامين C لدعم المفاصل والبشرة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ماء بعد الأكل.'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 176
  {
    id: 'estoza-chocolate-24-pieces-mvs3',
    name: 'estoza (chocolate) 24 pieces',
    genericName: 'iron & zinc & folic acid & selenium & biotin & vitamin c',
    concentration: '24 pieces',
    price: 125,
    matchKeywords: ['estoza', 'استوزا', 'chocolate', 'iron', 'zinc', 'folic', 'selenium', 'biotin', 'vitamin c', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد ومعادن وفيتامينات (قطع شوكولاتة).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 177
  {
    id: 'we-kids-30ml-oral-drops-mvs3',
    name: 'we kids 30ml oral drops',
    genericName: 'omega3 & vitamin d3 & vitamin e',
    concentration: '30ml',
    price: 50,
    matchKeywords: ['we kids', 'وي كيدز', 'omega3 drops', 'vitamin d3', 'vitamin e', 'kids', 'اطفال', 'focus', 'تركيز', '#multi_vitamins', '#omega3'],
    usage: 'نقط أوميجا 3 مع فيتامين D3 وE للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٠.٥ مل يومياً بعد الأكل' : '١ مل يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 178
  {
    id: 'florax-20-caps-mvs3',
    name: 'florax 20 caps',
    genericName: 'vitamin c & vitamin d & zinc',
    concentration: '20 caps',
    price: 110,
    matchKeywords: ['florax', 'فلوراكس', 'vitamin c', 'vitamin d', 'zinc', 'immunity', 'مناعة', 'cold', 'برد', '#multi_vitamins', '#zinc'],
    usage: 'فيتامين C + D + زنك لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 179
  {
    id: 'jc-ferr-30-cap-mvs3',
    name: 'jc. ferr 30 cap',
    genericName: 'iron & zinc & folate & vitamin b6 & vitamin b12 & copper',
    concentration: '30 caps',
    price: 135,
    matchKeywords: ['jc ferr', 'jc. ferr', 'جي سي فير', 'iron', 'zinc', 'folate', 'b12', 'b6', 'copper', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد مع معادن وفيتامينات ب لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 180
  {
    id: 'khamera-30-tabs-mvs3',
    name: 'khamera 30 tabs.',
    genericName: 'yeast',
    concentration: '30 tabs',
    price: 27,
    matchKeywords: ['khamera', 'خميرة', 'yeast tabs', 'b vitamins', 'hair', 'شعر', 'skin', 'بشرة', '#multi_vitamins'],
    usage: 'خميرة لدعم البشرة والشعر والشهية.',
    timing: 'مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 181
  {
    id: 'squibash-30-capsules-mvs3',
    name: 'squibash 30 capsules',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12',
    concentration: '30 caps',
    price: 84,
    matchKeywords: ['squibash', 'سكويباش', 'iron', 'vitamin c', 'b6', 'folic', 'b12', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فوليك وب١٢ لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 182
  {
    id: 'marnys-royal-jelly-1000mg-with-lecithin-30-caps-mvs3',
    name: 'marnys royal jelly 1000 mg with lecithin 30 caps.',
    genericName: 'royal jelly & soy lecithin',
    concentration: '1000mg',
    price: 900,
    matchKeywords: ['marnys', 'مارنيس', 'royal jelly 1000', 'lecithin', 'soy', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'غذاء ملكات مع ليسيثين لدعم الطاقة والتركيز.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد تسبب حساسية شديدة لدى بعض الأشخاص.'],
  },

  // 183
  {
    id: 'mextra-20-pieces-mvs3',
    name: 'mextra 20 pieces',
    genericName: 'iron & zinc & copper',
    concentration: '20 pieces',
    price: 80,
    matchKeywords: ['mextra', 'ميكسترا', 'iron', 'zinc', 'copper', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد ومعادن لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 184
  {
    id: 'morisweet-50-sachets-1-5gm-mvs3',
    name: 'morisweet 50 sachets 1.5gm',
    genericName: 'sucralose & sorbitol',
    concentration: '50 sachets',
    price: 38,
    matchKeywords: ['morisweet', 'موري سويت', 'sucralose', 'sorbitol', 'sweetener', 'سكر دايت', 'diabetes', 'سكر', '#dietary_supplements'],
    usage: 'مُحلي بديل للسكر.',
    timing: 'عند الحاجة.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد لتحلية مشروب/وجبة عند الحاجة.'),
    warnings: ['قد يسبب انتفاخ/إسهال إذا زادت الكمية (بسبب السوربيتول).', 'غير مناسب للأطفال الصغار.'],
  },

  // 185
  {
    id: 'mr-bear-fruta-juice-mango-400ml-mvs3',
    name: 'mr. bear fruta juice mango 400 ml',
    genericName: 'multivitamins',
    concentration: '400ml',
    price: 240,
    matchKeywords: ['mr bear fruta', 'mr bear 400', 'مستر بير ٤٠٠', 'multivitamin syrup', 'kids vitamins', 'فيتامين اطفال', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النشاط والشهية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 186
  {
    id: 'puramax-10gm-10-sachets-mvs3',
    name: 'puramax 10 gm 10 sachets',
    genericName: 'lactoferrin & iron & vitamin b complex & vitamin c',
    concentration: '10 sachets',
    price: 120,
    matchKeywords: ['puramax', 'بيوراماكس', 'lactoferrin', 'iron', 'b complex', 'vitamin c', 'anemia', 'انيميا', 'immunity', 'مناعة', '#multi_vitamins', '#iron'],
    usage: 'لاكتوفرّين مع حديد وفيتامينات لدعم تكوين الدم والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 187
  {
    id: 'vepicle-20-tabs-mvs3',
    name: 'vepicle 20 tabs',
    genericName: 'l-carnitine & coenzyme q10 & beta-carotene & flaxseed oil',
    concentration: '20 tabs',
    price: 260,
    matchKeywords: ['vepicle', 'فيبيكل', 'carnitine', 'coq10', 'beta carotene', 'flaxseed oil', 'energy', 'طاقة', 'heart', 'قلب', '#multi_vitamins'],
    usage: 'دعم الطاقة (كارنيتين + CoQ10) مع مضادات أكسدة وزيوت.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 188
  {
    id: 'omegaseef-30-sg-cap-mvs3',
    name: 'omegaseef 30 s.g. cap',
    genericName: 'fish oil & vitamin e & flax seed oil & borage oil',
    concentration: '30 caps',
    price: 250,
    matchKeywords: ['omegaseef', 'اوميجاسيف', 'fish oil', 'flaxseed', 'borage', 'vitamin e', 'omega', 'اوميجا', '#multi_vitamins', '#omega3'],
    usage: 'زيوت أوميجا متعددة مع فيتامين E لدعم القلب والمفاصل.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 189
  {
    id: 'safwa-vit-30-tabs-mvs3',
    name: 'safwa vit 30 tabs',
    genericName: 'vitamins & minerals & bio elements',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['safwa vit', 'سفوة فيت', 'vitamins', 'minerals', 'bio elements', 'multivitamin', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن لدعم الطاقة والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 190
  {
    id: 'immuoncostra-20-tabs-mvs3',
    name: 'immuoncostra 20 tabs',
    genericName: 'vitamin a & vitamin d3 & vitamin e & vitamin k & vitamin c',
    concentration: '20 tabs',
    price: 320,
    matchKeywords: ['immuoncostra', 'ايميونكوسترا', 'vitamin a', 'vitamin d3', 'vitamin e', 'vitamin k', 'vitamin c', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'فيتامينات مناعية (A + C + D3 + E + K).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K قد يتداخل مع الوارفارين.'],
  },

  // 191
  {
    id: 'egy-meal-20-sachets-mvs3',
    name: 'egy meal 20 sachets',
    genericName: 'whey protein & calcium & copper & magnesium & zinc',
    concentration: '20 sachets',
    price: 140,
    matchKeywords: ['egy meal', 'ايجي ميل', 'whey protein', 'protein', 'calcium', 'magnesium', 'zinc', 'meal replacement', 'بديل وجبة', '#multi_vitamins'],
    usage: 'مكمل بروتين ومعادن لدعم التغذية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠–٢٥٠ مل ماء/لبن بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.'],
  },

  // 192
  {
    id: 'nerotonex-20-caps-mvs3',
    name: 'nerotonex 20 caps',
    genericName: 'vitamin b1 & vitamin b2 & vitamin b6 & vitamin b12 & vitamin c',
    concentration: '20 caps',
    price: 225,
    matchKeywords: ['nerotonex', 'نيروتونيكس', 'b1', 'b2', 'b6', 'b12', 'vitamin c', 'neuropathy', 'تنميل', 'fatigue', 'ارهاق', '#multi_vitamins', '#vitamin_b'],
    usage: 'دعم الأعصاب والطاقة (فيتامينات ب + C).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 193
  {
    id: 'sideral-forte-30-caps-mvs3',
    name: 'sideral forte 30 caps',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12',
    concentration: '30 caps',
    price: 400,
    matchKeywords: ['sideral forte', 'سيدرال فورت', 'iron', 'vitamin c', 'b6', 'folic', 'b12', 'anemia', 'انيميا', 'ferritin', 'مخزون الحديد', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فوليك وب١٢ لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 194
  {
    id: 'omega-tebt-30-capsules-mvs3',
    name: 'omega tebt 30 capsules',
    genericName: 'fish oil & vitamin e',
    concentration: '30 caps',
    price: 150,
    matchKeywords: ['omega tebt', 'اوميجا تبت', 'fish oil', 'vitamin e', 'omega 3', 'heart', 'قلب', '#multi_vitamins', '#omega3'],
    usage: 'أوميجا 3 (زيت سمك) مع فيتامين E لدعم القلب والدهون الثلاثية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },
];

