import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
  'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين A أو D بجرعات عالية.',
  'جرعات فيتامين A/D الزائدة قد تسبب أعراض تسمم (غثيان/صداع/إمساك/عطش شديد).',
];

const IRON_SUPPLEMENT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
  'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
  'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const OMEGA_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'يُستخدم بحذر مع أدوية السيولة أو اضطرابات النزف.',
  'قد يسبب تجشؤ بطعم السمك/اضطراب معدة؛ يؤخذ مع الطعام.',
];

const HERBAL_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'أوقف الاستخدام إذا ظهرت حساسية (طفح/حكة/تورم).',
];

const ZINC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const BONE_SUPPORT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
  'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

export const MULTIVITAMINS_SUPPLEMENTS_2: Medication[] = [
  // ==========================================
  // multivitamins + supplements 2
  // ==========================================

  // 65
  {
    id: 'egunaz-d3-k2-20-caps-mvs2',
    name: 'egunaz d3&k2 20 capsules',
    genericName: 'vitamin d3 & vitamin k2',
    concentration: '20 capsules',
    price: 128,
    matchKeywords: ['egunaz', 'ايجوناز', 'd3 k2', 'vitamin d3', 'vitamin k2', 'bones', 'عظام', 'calcium', 'كالسيوم', '#multi_vitamins', '#vitamin_d', '#vitamin_k'],
    usage: 'دعم العظام والأسنان (فيتامين D3 + K2).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين ومضادات التجلط.'],
  },

  // 66
  {
    id: 'neurawhite-30-sublingual-tabs-mvs2',
    name: 'neurawhite 30 sublingual tablets',
    genericName: 'vitamin b12 & vitamin b6 & folic acid & biotin',
    concentration: '30 tablets',
    price: 110,
    matchKeywords: ['neurawhite', 'نيروايت', 'b12', 'b6', 'folic', 'biotin', 'sublingual', 'تحت اللسان', 'neuropathy', 'تنميل', 'hair', 'سقوط الشعر', '#multi_vitamins', '#vitamin_b'],
    usage: 'دعم الأعصاب وتكوين الدم والشعر (B12 + B6 + فوليك + بيوتين) تحت اللسان.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 67
  {
    id: 'rozone-forte-20-tab-mvs2',
    name: 'rozone forte 20 tab',
    genericName: 'vitamin b complex & vitamin b6 & vitamin b12 & vitamin a',
    concentration: '20 tabs',
    price: 140,
    matchKeywords: ['rozone forte', 'rozone', 'روزون', 'b complex', 'b12', 'b6', 'vitamin a', 'fatigue', 'ارهاق', 'neuropathy', 'اعصاب', '#multi_vitamins'],
    usage: 'مجموعة فيتامين ب مع فيتامين A لدعم الطاقة والأعصاب.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الإفطار.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 68
  {
    id: 'c-zinc-30-caps-mvs2',
    name: 'c zinc 30 caps.',
    genericName: 'vitamin c & zinc bisglycinate chelate',
    concentration: '30 caps',
    price: 90,
    matchKeywords: ['c zinc', 'czinc', 'سي زنك', 'vitamin c', 'zinc bisglycinate', 'cold', 'برد', 'immunity', 'مناعة', 'hair', 'سقوط الشعر', '#multi_vitamins', '#zinc'],
    usage: 'فيتامين C مع زنك لدعم المناعة وتقليل أعراض البرد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 69
  {
    id: 'c-retard-zinc-20-caps-mvs2',
    name: 'c-retard + zinc 20 caps.',
    genericName: 'vitamin c & zinc',
    concentration: '20 caps',
    price: 80,
    matchKeywords: ['c-retard zinc', 'c retard', 'سي ريتارد', 'vitamin c', 'zinc', 'immunity', 'مناعة', 'cold', 'برد', '#multi_vitamins', '#zinc'],
    usage: 'فيتامين C ممتد المفعول مع زنك لدعم المناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 70
  {
    id: 'ecoto-20-pieces-mvs2',
    name: 'ecoto 20 pieces',
    genericName: 'calcium & magnesium & vitamin b6 & vitamin b12 & vitamin d3',
    concentration: '20 pieces',
    price: 135,
    matchKeywords: ['ecoto', 'ايكوتو', 'calcium', 'magnesium', 'b6', 'b12', 'd3', 'cramps', 'تقلصات', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'مكمل للعظام والتقلصات العضلية (كالسيوم + ماغنسيوم + D3 + فيتامينات ب).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 71
  {
    id: 'e-yeast-20-caps-mvs2',
    name: 'e-yeast 20 caps',
    genericName: 'wheat germ oil & dry yeast',
    concentration: '20 caps',
    price: 125,
    matchKeywords: ['e-yeast', 'e yeast', 'اي ييست', 'wheat germ oil', 'yeast', 'hair', 'سقوط الشعر', 'skin', 'بشرة', '#multi_vitamins'],
    usage: 'مكمل لدعم البشرة والشعر (زيت جنين القمح + خميرة).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 72
  {
    id: 'trinutrex-30-caps-mvs2',
    name: 'trinutrex 30 caps.',
    genericName: 'royal jelly & ginseng & ginko biloba',
    concentration: '30 caps',
    price: 210,
    matchKeywords: ['trinutrex', 'ترينوتركس', 'royal jelly', 'ginseng', 'ginkgo', 'energy', 'طاقة', 'memory', 'ذاكرة', '#multi_vitamins'],
    usage: 'مكمل للطاقة والتركيز (غذاء ملكات + جينسنغ + جينكو).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد النزف مع مسيلات الدم. قد يسبب أرق/خفقان.'],
  },

  // 73
  {
    id: 'kiddy-cal-gummy-ca-d3-20-pcs-mvs2',
    name: 'kiddy cal children gummy (ca+d3) 20 pieces',
    genericName: 'calcium & vitamin d3',
    concentration: '20 gummies',
    price: 100,
    matchKeywords: ['kiddy cal', 'كيدي كال', 'gummy calcium', 'calcium d3', 'bones', 'عظام', 'growth', 'نمو', '#multi_vitamins', '#calcium'],
    usage: 'كالسيوم + فيتامين D3 للأطفال لدعم النمو والعظام (Gummy).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? 'قطعة واحدة يومياً' : 'قطعتان يومياً'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 74
  {
    id: 'vinax-24-tab-mvs2',
    name: 'vinax 24 tab',
    genericName: 'iron & zinc & vitamin c & vitamin b',
    concentration: '24 tabs',
    price: 50,
    matchKeywords: ['vinax 24', 'vinax', 'فينكس ٢٤', 'iron', 'حديد', 'zinc', 'vitamin c', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد مع زنك وفيتامينات لدعم تكوين الدم والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 75
  {
    id: 'mr-bear-fruta-juice-mango-160ml-mvs2',
    name: 'mr. bear fruta juice mango 160 ml',
    genericName: 'multivitamins',
    concentration: '160ml',
    price: 145,
    matchKeywords: ['mr bear', 'mr. bear', 'مستر بير', 'fruta juice', 'mango', 'multivitamin', 'kids', 'فيتامين اطفال', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النشاط والشهية.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 76
  {
    id: 'omepure-oral-dps-10ml-mvs2',
    name: 'omepure oral dps 10 ml',
    genericName: 'wheat germ oil & omega 3 & omega 9 & vitamin b & zinc & iron',
    concentration: '10ml',
    price: 75,
    matchKeywords: ['omepure', 'اوميبور', 'omega 3', 'omega 9', 'wheat germ oil', 'iron', 'zinc', 'memory', 'تركيز', '#multi_vitamins', '#omega3', '#iron'],
    usage: 'نقط متعددة لدعم التركيز والمناعة (أوميجا + زنك + حديد + فيتامينات).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٠.٥ مل يومياً' : '١ مل يومياً'),
    warnings: [...OMEGA_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
  },

  // 77
  {
    id: 'pregnacare-30-fc-tabs-mvs2',
    name: 'pregnacare 30 f.c. tabs.',
    genericName: 'beta-carotene & thiamine mononitrate & riboflavin & vitamin b6 & vitamin b12',
    concentration: '30 tabs',
    price: 200,
    matchKeywords: ['pregnacare', 'بريجناكير', 'pregnancy', 'حمل', 'prenatal', 'فيتامين حمل', 'b6', 'b12', 'beta carotene', '#multi_vitamins'],
    usage: 'مولتي فيتامين للحمل لدعم الأم والجنين.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً مع وجبة رئيسية.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 78
  {
    id: 'sansovit-with-iron-syrup-120gm-mvs2',
    name: 'sansovit with iron syrup 120gm',
    genericName: 'retinopalmitate & pyridoxine hydrochloride (vitamin b6) & vitamin d3',
    concentration: '120ml',
    price: 17.25,
    matchKeywords: ['sansovit with iron', 'sansovit iron', 'سانسوفيت حديد', 'iron syrup', 'انيميا', 'anemia', 'appetite', 'فاتح شهية', '#multi_vitamins', '#iron'],
    usage: 'شراب فيتامينات مع دعم للدم والشهية للأطفال.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 79
  {
    id: 'selona-20-sachets-mvs2',
    name: 'selona 20 sachets',
    genericName: 'vitamin c & vitamin e & vitamin a & zinc & magnesium & selenium',
    concentration: '20 sachets',
    price: 45,
    matchKeywords: ['selona', 'سيلونا', 'selenium', 'vitamin c', 'vitamin e', 'zinc', 'antioxidant', 'مضاد اكسدة', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مضادات أكسدة ومعادن لدعم المناعة والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ماء بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 80
  {
    id: 'sideral-active-20-capsules-mvs2',
    name: 'sideral active 20 capsules',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12 & vitamin d3',
    concentration: '20 caps',
    price: 235,
    matchKeywords: ['sideral active 20', 'sideral active', 'سيدرال اكتيف', 'iron', 'anemia', 'انيميا', 'folic', 'فوليك', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فوليك وفيتامينات لدعم تكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 81
  {
    id: 'trinutrex-20-caps-mvs2',
    name: 'trinutrex 20 caps.',
    genericName: 'royal jelly & ginseng & ginko biloba',
    concentration: '20 caps',
    price: 34,
    matchKeywords: ['trinutrex 20', 'trinutrex', 'ترينوتركس ٢٠', 'ginseng', 'ginkgo', 'royal jelly', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'مكمل للطاقة والتركيز (غذاء ملكات + جينسنغ + جينكو).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد النزف مع مسيلات الدم. قد يسبب أرق/خفقان.'],
  },

  // 82
  {
    id: 'vitalochoc-10-sachet-mvs2',
    name: 'vitalochoc 10 sachet',
    genericName: 'iron & magnesium & folic acid & vitamin c & protein',
    concentration: '10 sachets',
    price: 79,
    matchKeywords: ['vitalochoc', 'فيتالوشوك', 'iron sachet', 'anemia', 'انيميا', 'protein', 'بروتين', 'fatigue', 'ارهاق', '#multi_vitamins', '#iron'],
    usage: 'ساشيه حديد مع مغنيسيوم وبروتين لدعم الطاقة وتكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ماء/حليب بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 83
  {
    id: 'vitalochoc-plus-10-sachet-mvs2',
    name: 'vitalochoc plus 10 sachet',
    genericName: 'iron & lactoferrin & vitamin b complex',
    concentration: '10 sachets',
    price: 125,
    matchKeywords: ['vitalochoc plus', 'فيتالوشوك بلس', 'lactoferrin', 'iron', 'anemia', 'انيميا', 'immunity', 'مناعة', '#multi_vitamins', '#iron', '#anemia', '#immunity'],
    usage: 'ساشيه حديد مع لاكتوفرّين وفيتامينات ب لدعم المناعة ومخزون الحديد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 84
  {
    id: 'vitatron-30-caps-mvs2',
    name: 'vitatron 30 caps',
    genericName: 'riboflavin, vitamin b2 & vitamin b1 (thiamine) & vitamin a (retinol palmitate)',
    concentration: '30 caps',
    price: 195,
    matchKeywords: ['vitatron 30', 'vitatron', 'فيتاترون ٣٠', 'b1', 'b2', 'vitamin a', 'appetite', 'فاتح شهية', 'fatigue', 'ارهاق', '#multi_vitamins'],
    usage: 'فيتامينات لدعم الطاقة والشهية (B1 + B2 + A).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 85
  {
    id: 'yesvt-plex-120ml-syrup-mvs2',
    name: 'yesvt plex 120 ml syrup',
    genericName: 'vitamin c & inositol & vitamin b3 & choline & vitamin b1 & vitamin b2 & vitamin b6',
    concentration: '120ml',
    price: 280,
    matchKeywords: ['yesvt plex', 'plex syrup', 'يسفت بليكس', 'inositol', 'choline', 'b vitamins', 'fatigue', 'ارهاق', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'شراب فيتامينات ب مع C وكولين لدعم الشهية والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 86
  {
    id: 'egy-totavit-syrup-100ml-mvs2',
    name: 'egy totavit syrup 100 ml',
    genericName: 'vitamin b1 (thiamine) & vitamin a (retinol palmitate) & vitamin d3',
    concentration: '100ml',
    price: 65,
    matchKeywords: ['egy totavit', 'totavit syrup', 'ايجي توتافيت', 'b1', 'vitamin a', 'vitamin d3', 'growth', 'نمو', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النمو والشهية (A + D3 + B1).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 87
  {
    id: 'kidzona-cal-120ml-syrup-mvs2',
    name: 'kidzona cal 120 ml syrup',
    genericName: 'calcium citrate & magnesium citrate & vitamin c & zinc gluconate & vitamin d3',
    concentration: '120ml',
    price: 45,
    matchKeywords: ['kidzona cal', 'kidzona', 'كيدزونا كال', 'calcium citrate', 'magnesium', 'zinc', 'vitamin d3', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'شراب معادن وفيتامينات للأطفال لدعم العظام (كالسيوم + D3 + ماغنسيوم + زنك).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 88
  {
    id: 'kidzona-fer-120ml-syrup-mvs2',
    name: 'kidzona fer 120 ml syrup',
    genericName: 'ferrous gluconate & vitamin b1 & vitamin b2 & vitamin b6 & vitamin b12',
    concentration: '120ml',
    price: 55,
    matchKeywords: ['kidzona fer', 'كidzona fer', 'كيدزونا حديد', 'iron syrup', 'ferrous gluconate', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب حديد مع فيتامينات ب لدعم تكوين الدم للأطفال.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٢.٥–٥ مل يومياً' : '٥–١٠ مل يومياً'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 89
  {
    id: 'safetrium-30-fc-tabs-mvs2',
    name: 'safetrium 30 f.c. tabs.',
    genericName: 'multivitamins & minerals',
    concentration: '30 tabs',
    price: 135,
    matchKeywords: ['safetrium', 'سيفيتريوم', 'multivitamin', 'minerals', 'فيتامينات', 'معادن', 'fatigue', 'ارهاق', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن لدعم الطاقة والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 90
  {
    id: 'sideral-bimbi-10-orodispersible-sticks-mvs2',
    name: 'sideral bimbi 10 orodispersible sticks',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12 & vitamin d3',
    concentration: '10 sticks',
    price: 100,
    matchKeywords: ['sideral bimbi', 'سيدرال بيمبي', 'iron sticks kids', 'anemia', 'انيميا', 'ferritin', 'مخزون الحديد', '#multi_vitamins', '#iron'],
    usage: 'حديد للأطفال على هيئة sticks سريعة الذوبان لدعم مخزون الحديد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 50,
    calculationRule: fixed('Stick واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 91
  {
    id: 'zovix-30-tablets-mvs2',
    name: 'zovix 30 tablets',
    genericName: 'iron & folic acid & vitamin b1 & vitamin b6 & vitamin b7 & vitamin b12',
    concentration: '30 tabs',
    price: 59,
    matchKeywords: ['zovix', 'زوفيكس', 'iron', 'folic', 'b12', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد مع فوليك وفيتامينات ب لدعم تكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 92
  {
    id: 'kidstron-120ml-syrup-mvs2',
    name: 'kidstron 120 ml syrup',
    genericName: 'vitamins & iron',
    concentration: '120ml',
    price: 75,
    matchKeywords: ['kidstron', 'كيدسترون', 'iron syrup kids', 'anemia', 'انيميا', 'appetite', 'فاتح شهية', '#multi_vitamins', '#iron'],
    usage: 'شراب فيتامينات مع حديد للأطفال لدعم الشهية وتكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 93
  {
    id: 'kids-sleep-melatonin-syrup-60ml-mvs2',
    name: 'kids sleep (kids daily vit sleep ) syrup 60 ml',
    genericName: 'melatonin',
    concentration: '60ml',
    price: 70,
    matchKeywords: ['kids sleep', 'melatonin syrup', 'ميلاتونين', 'sleep', 'نوم', 'insomnia', 'أرق', 'bedtime', 'قبل النوم', '#multi_vitamins'],
    usage: 'ميلاتونين للمساعدة على تنظيم النوم للأطفال.',
    timing: 'قبل النوم.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 36,
    maxAgeMonths: 144,
    minWeight: 12,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٢.٥ مل قبل النوم بـ ٣٠ دقيقة' : '٥ مل قبل النوم بـ ٣٠ دقيقة'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب نعاس صباحي إذا تأخر وقت النوم أو زادت الجرعة.'],
  },

  // 94
  {
    id: 'braytoflex-30-tablets-mvs2',
    name: 'braytoflex 30 tablets',
    genericName: 'glucosamine & chondroitin & collagen & ginkobiloba & msm',
    concentration: '30 tabs',
    price: 420,
    matchKeywords: ['braytoflex', 'برايتوفليكس', 'glucosamine', 'chondroitin', 'msm', 'collagen', 'joints', 'مفاصل', 'knee pain', 'خشونة', '#multi_vitamins', '#joint_support'],
    usage: 'دعم المفاصل والغضاريف في خشونة الركبة وآلام المفاصل.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).', 'قد يزيد النزف مع مسيلات الدم (جينكو).'],
  },

  // 95
  {
    id: 'choletrix-d3-1000iu-20-chew-tabs-mvs2',
    name: 'choletrix-d3 1000 iu 20 chew. tabs.',
    genericName: 'cholecalciferol',
    concentration: '1000 IU',
    price: 60,
    matchKeywords: ['choletrix d3 chew', 'choletrix 1000 chew', 'vitamin d chewable', 'فيتامين د مضغ', 'bones', 'عظام', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 أقراص قابلة للمضغ لدعم العظام والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 216 ? 'قرص واحد (١٠٠٠ وحدة) يومياً' : 'قرص واحد يومياً'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'الزيادة المفرطة قد ترفع الكالسيوم وتسبب أعراض تسمم.'],
  },

  // 96
  {
    id: 'choletrix-d3-400iu-oral-drops-10ml-mvs2',
    name: 'choletrix-d3 400 iu oral drops 10ml',
    genericName: 'cholecalciferol',
    concentration: '400 IU/ml',
    price: 50,
    matchKeywords: ['choletrix d3 400', 'vitamin d drops 400', 'فيتامين د نقط ٤٠٠', 'infant d3', 'رضع', 'bones', 'عظام', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 نقط للرضع/الأطفال (جرعة يومية).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 144,
    minWeight: 2,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 12) return '١ مل يومياً (٤٠٠ وحدة)';
      if (ageMonths < 216) return '١.٥ مل يومياً (٦٠٠ وحدة)';
      return '٢.٥ مل يومياً (١٠٠٠ وحدة)';
    },
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'لا تجمع مع فيتامين D آخر بجرعات عالية.'],
  },

  // 97
  {
    id: 'sano-joy-30-caps-mvs2',
    name: 'sano joy 30 caps.',
    genericName: 'glucosamine & ginko biloba & vitamin d & copper & selenium & vitamin c',
    concentration: '30 caps',
    price: 165,
    matchKeywords: ['sano joy', 'سانو جوي', 'glucosamine', 'ginkgo', 'vitamin d', 'joints', 'مفاصل', 'antioxidant', 'مضاد اكسدة', '#multi_vitamins'],
    usage: 'دعم المفاصل مع مضادات أكسدة ومعادن.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد النزف مع مسيلات الدم (جينكو).'],
  },

  // 98
  {
    id: 'kids-appetite-syrup-125ml-mvs2',
    name: 'kids appetite (kids daily vit appetite) syrup 125ml',
    genericName: 'l-lysine & vitamin b complex & iron & zink & omega 3',
    concentration: '125ml',
    price: 110,
    matchKeywords: ['kids appetite', 'فاتح شهية اطفال', 'lysine', 'iron', 'zinc', 'omega 3', 'thinness', 'نحافة', '#multi_vitamins', '#iron', '#omega3'],
    usage: 'شراب فاتح شهية للأطفال (ليسين + فيتامينات + حديد + زنك + أوميجا).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
  },

  // 99
  {
    id: 'bloom-ville-30-tabs-mvs2',
    name: 'bloom ville 30 tabs.',
    genericName: 'vitamin c & vitamin d3 & vitamin e & vitamin b1 & vitamin b2 & vitamin b6',
    concentration: '30 tabs',
    price: 275,
    matchKeywords: ['bloom ville', 'بلوم فيل', 'vitamin c', 'vitamin d3', 'vitamin e', 'b complex', 'fatigue', 'ارهاق', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مولتي فيتامين لدعم الطاقة والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 100
  {
    id: 'centrum-silver-with-lutein-100-tabs-mvs2',
    name: 'centrum silver with lutein 100 tabs.',
    genericName: 'ascorbic acid & vitamin k1 & dibasic calcium phosphate & biotin',
    concentration: '100 tabs',
    price: 780,
    matchKeywords: ['centrum silver 100', 'centrum silver with lutein 100', 'سنتروم سيلفر ١٠٠', 'lutein', 'biotin', 'senior', 'كبار السن', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن لكبار السن مع لوتين لدعم العين والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً مع وجبة.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'فيتامين K1 قد يتداخل مع الوارفارين.'],
  },

  // 101
  {
    id: 'iq-plus-30-sachet-mvs2',
    name: 'iq plus 30 sachet',
    genericName: 'acetyl_l_carnitine & ginko biloba & st.john wart & phosphatidylserine',
    concentration: '30 sachets',
    price: 450,
    matchKeywords: ['iq plus', 'اي كيو بلس', 'acetyl l carnitine', 'ginkgo', 'phosphatidylserine', 'memory', 'ذاكرة', 'concentration', 'تركيز', '#multi_vitamins'],
    usage: 'مكمل لدعم التركيز والذاكرة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً صباحاً بعد الإفطار.'),
    warnings: [
      ...HERBAL_WARNINGS,
      'St. John\'s wort قد يتداخل مع كثير من الأدوية (مضادات الاكتئاب/حبوب منع الحمل/مضادات التجلط).',
      'قد يزيد النزف مع مسيلات الدم (جينكو).',
    ],
  },

  // 102
  {
    id: 'milkita-30-tab-mvs2',
    name: 'milkita 30 tab',
    genericName: 'calcium & magnesium & vitamin d',
    concentration: '30 tabs',
    price: 100,
    matchKeywords: ['milkita', 'ميلكيتا', 'calcium', 'magnesium', 'vitamin d', 'bones', 'عظام', 'cramps', 'تقلصات', '#multi_vitamins', '#calcium'],
    usage: 'كالسيوم + ماغنسيوم + فيتامين D لدعم العظام والتقلصات.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 103
  {
    id: 'q-rizm-30-caps-mvs2',
    name: 'q-rizm 30 caps.',
    genericName: 'coenzyme q10 & vitamin d3',
    concentration: '30 caps',
    price: 405,
    matchKeywords: ['q-rizm', 'q rizm', 'coq10', 'vitamin d3', 'energy', 'طاقة', 'heart', 'قلب', '#multi_vitamins'],
    usage: 'CoQ10 مع فيتامين D3 لدعم الطاقة وصحة القلب.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'CoQ10 قد يقلل تأثير الوارفارين لدى بعض الحالات.'],
  },

  // 104
  {
    id: 'redferx-30-capsules-mvs2',
    name: 'redferx 30 capsules',
    genericName: 'ferrous bisglycinate & vitamin c & vitamin b6 & folic acid & vitamin b12',
    concentration: '30 caps',
    price: 195,
    matchKeywords: ['redferx', 'ريدفيركس', 'ferrous bisglycinate', 'iron', 'anemia', 'انيميا', 'ferritin', 'مخزون الحديد', '#multi_vitamins', '#iron'],
    usage: 'حديد (Bisglycinate) مع فوليك وب١٢ لدعم تكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 105
  {
    id: 'sansovit-calcium-syrup-100ml-mvs2',
    name: 'sansovit calcium syrup 100 ml',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vitamin b6',
    concentration: '100ml',
    price: 70,
    matchKeywords: ['sansovit calcium', 'sansovit', 'سانسوفيت كالسيوم', 'vitamin d3', 'growth', 'نمو', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النمو والعظام.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 106
  {
    id: 'helpa-mix-600mg-20-tab-mvs2',
    name: 'helpa mix 600 mg 20 tab',
    genericName: 'fenugreek & fennel & dill seed & caraway',
    concentration: '20 tabs',
    price: 110,
    matchKeywords: ['helpa mix', 'هلبا ميكس', 'fenugreek', 'حلبة', 'fennel', 'شمر', 'caraway', 'كراوية', 'appetite', 'فاتح شهية', 'gas', 'غازات', '#dietary_supplements'],
    usage: 'مكمل عشبي لفتح الشهية وتقليل الغازات.',
    timing: 'مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد بعد الأكل مرتين يومياً.'),
    warnings: HERBAL_WARNINGS,
  },

  // 107
  {
    id: 'meralgo-20-caps-mvs2',
    name: 'meralgo 20 caps',
    genericName: 'undenaturated collagen type 2 & turmeric rhizome powder & vitamin c',
    concentration: '20 caps',
    price: 425,
    matchKeywords: ['meralgo', 'ميرالجو', 'uc-ii', 'collagen type 2', 'turmeric', 'curcumin', 'joints', 'مفاصل', 'arthritis', 'التهاب مفاصل', '#dietary_supplements', '#joint_support'],
    usage: 'دعم المفاصل والغضاريف (كولاجين نوع ٢ + كركم + فيتامين C).',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...HERBAL_WARNINGS, 'الكركم يُستخدم بحذر مع مسيلات الدم أو حصوات المرارة.'],
  },

  // 108
  {
    id: 'dancran-30-caps-mvs2',
    name: 'dancran 30 caps',
    genericName: 'cranberry extract & fructooligosaccharides & vitamin c',
    concentration: '30 caps',
    price: 120,
    matchKeywords: ['dancran', 'دانكران', 'cranberry', 'uti', 'التهاب بول', 'burning', 'حرقان بول', 'urinary', 'مسالك', '#herbal_supplements'],
    usage: 'دعم المسالك البولية وتقليل تكرار التهابات البول (Cranberry).',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع الوارفارين أو تاريخ حصوات كلى.'],
  },

  // 109
  {
    id: 'hydrafeet-cream-60gm-mvs2',
    name: 'hydrafeet cream 60 gm',
    genericName: 'aqua & salicylic acid & panthenol & glycerin & paraffin oil',
    concentration: '60gm',
    price: 60,
    matchKeywords: ['hydrafeet', 'هيدرافيت', 'foot cream', 'cracked heels', 'تشقق كعب', 'salicylic acid', 'panthenol', '#topical'],
    usage: 'كريم لترطيب وتنعيم القدمين وتشقق الكعبين.',
    timing: 'مرتين يومياً.',
    category: Category.TOPICAL_CARE,
    form: 'Cream',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: fixed('تُوضع طبقة رقيقة مرتين يومياً.'),
    warnings: ['للاستخدام الخارجي فقط.', 'تجنب وضعه على الجروح المفتوحة أو بين أصابع القدم إذا كان هناك التهاب.'],
  },

  // 110
  {
    id: 'spertility-14-sachets-mvs2',
    name: 'spertility 14 sachets',
    genericName: 'd-aspartic acid & coenzyme q10 & zinc',
    concentration: '14 sachets',
    price: 550,
    matchKeywords: ['spertility', 'سبيرتيليتي', 'fertility', 'خصوبة', 'male fertility', 'تحسين السائل', 'coq10', 'zinc', '#dietary_supplements'],
    usage: 'مكمل لدعم خصوبة الرجال (D-aspartic acid + CoQ10 + زنك).',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 111
  {
    id: 'api-grow-powder-10-sachets-mvs2',
    name: 'api-grow powder 10 sachets',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & sodium',
    concentration: '10 sachets',
    price: 145,
    matchKeywords: ['api-grow', 'api grow', 'ابي جرو', 'weight gain', 'زيادة وزن', 'protein', 'بروتين', 'malnutrition', 'سوء تغذية', '#dietary_supplements'],
    usage: 'مكمل غذائي عالي السعرات لدعم زيادة الوزن.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠ مل لبن/ماء بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.', 'يُستخدم بحذر مع السكري (قد يحتوي سكريات).'],
  },

  // 112
  {
    id: 'egy-growth-powder-200gm-sachet-mvs2',
    name: 'egy growth powder 200 gm sachet',
    genericName: 'high protein drink powder',
    concentration: '200g',
    price: 105,
    matchKeywords: ['egy growth', 'ايجي جروث', 'protein powder', 'بروتين', 'weight gain', 'زيادة الوزن', '#dietary_supplements'],
    usage: 'بودرة بروتين لدعم التغذية وزيادة السعرات.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: fixed('٢ ملعقة كبيرة تُذاب في ٢٠٠ مل لبن/ماء مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 113
  {
    id: 'extra-protein-powder-10-sachets-mvs2',
    name: 'extra protein powder 10 sachets',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & sodium',
    concentration: '10 sachets',
    price: 220,
    matchKeywords: ['extra protein', 'اكسترا بروتين', 'protein sachet', 'بروتين', 'muscle', 'عضلات', 'weight gain', 'زيادة الوزن', '#dietary_supplements'],
    usage: 'مكمل بروتين لدعم التغذية وزيادة البروتين اليومي.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠ مل ماء/لبن بعد الأكل أو بعد التمرين.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 114
  {
    id: 'growth-formula-kids-250g-powder-mvs2',
    name: 'growth formula for kids 250 gm powder',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & sodium',
    concentration: '250g',
    price: 69.5,
    matchKeywords: ['growth formula 250', 'growth formula kids 250', 'نحافة اطفال', 'weight gain kids', 'protein', 'بروتين', '#dietary_supplements'],
    usage: 'مكمل تغذية للأطفال لزيادة الوزن ودعم السعرات.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: fixed('٢ ملعقة كبيرة تُذاب في ٢٠٠ مل لبن مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.', 'يُستخدم بحذر مع السكري (قد يحتوي سكريات).'],
  },

  // 115
  {
    id: 'ginkoravia-80mg-20-capsules-mvs2',
    name: 'ginkoravia 80mg 20capsules',
    genericName: 'dietary supplement',
    concentration: '80mg',
    price: 110,
    matchKeywords: ['ginkoravia 80', 'ginkoravia', 'جينكورافيا', 'ginkgo', 'circulation', 'دورة دموية', 'memory', 'ذاكرة', '#dietary_supplements'],
    usage: 'مكمل جينكو بيلوبا لدعم التركيز والدورة الدموية الطرفية.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد النزف مع مسيلات الدم/الأسبرين.'],
  },

  // 116
  {
    id: 'prima-growth-powder-8-sachets-mvs2',
    name: 'prima growth powder 8 sachets',
    genericName: 'skimmed milk & whey protein & sucrose & potassium sorbate & sodium',
    concentration: '8 sachets',
    price: 136,
    matchKeywords: ['prima growth', 'بريما جروث', 'weight gain', 'زيادة الوزن', 'protein', 'بروتين', '#dietary_supplements'],
    usage: 'مكمل غذائي لدعم زيادة الوزن.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 30,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠ مل لبن/ماء بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.'],
  },

  // 117
  {
    id: 'prima-growth-children-8-sachets-mvs2',
    name: 'prima growth powder for children 8 sachets',
    genericName: 'skimmed milk & whey protein & sucrose & potassium sorbate & sodium',
    concentration: '8 sachets',
    price: 92,
    matchKeywords: ['prima growth children', 'بريما جروث اطفال', 'underweight child', 'نحافة اطفال', 'protein', 'بروتين', '#dietary_supplements'],
    usage: 'مكمل غذائي للأطفال لزيادة الوزن ودعم السعرات.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: fixed('كيس واحد يومياً يُذاب في لبن بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.'],
  },

  // 118
  {
    id: 'promax-plus-12-sachets-20gm-mvs2',
    name: 'promax plus 12 sachets 20 gm',
    genericName: 'pure protein',
    concentration: '12 sachets',
    price: 150,
    matchKeywords: ['promax plus', 'بروماكس بلس', 'pure protein', 'protein', 'بروتين', 'muscle', 'عضلات', '#dietary_supplements'],
    usage: 'بروتين نقي لدعم الاحتياج اليومي من البروتين.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ماء/لبن بعد الأكل أو بعد التمرين.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 119
  {
    id: 'jeno-compound-600mg-20-capsules-mvs2',
    name: 'jeno compound 600 mg 20 capsules',
    genericName: 'alpha lipoic acid & vitamin b1 & vitamin b6 & folic acid & vitamin b12',
    concentration: '20 caps',
    price: 198,
    matchKeywords: ['jeno compound', 'جينو كومباوند', 'alpha lipoic acid', 'ala', 'neuropathy', 'التهاب اعصاب', 'diabetic neuropathy', 'اعصاب السكر', '#dietary_supplements'],
    usage: 'دعم الأعصاب كمضاد أكسدة مع فيتامينات ب.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 120
  {
    id: 'g-xir-d3-10000iu-30-tablets-mvs2',
    name: 'g.xir (d310000iu) 30 tablets',
    genericName: 'cholecalciferol',
    concentration: '10000 IU',
    price: 179,
    matchKeywords: ['g.xir', 'g xir', 'd3 10000', 'vitamin d 10000', 'فيتامين د ١٠٠٠٠', 'deficiency', 'نقص فيتامين د', '#dietary_supplements', '#vitamin_d'],
    usage: 'فيتامين D3 بجرعة عالية لعلاج نقص فيتامين د (كورسات قصيرة).',
    timing: 'أسبوعياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد (١٠٠٠٠ وحدة) مرة أسبوعياً لمدة ٨ أسابيع، ثم جرعة محافظة: ١٠٠٠ وحدة يومياً.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'لا يُستخدم يومياً لفترات طويلة بسبب خطر ارتفاع الكالسيوم.'],
  },

  // 121
  {
    id: 'g-vera-30-chew-tablets-mvs2',
    name: 'g.vera 30 chew tablets',
    genericName: 'calcium carbonate & magnesium oxide',
    concentration: '30 chew tabs',
    price: 149,
    matchKeywords: ['g.vera', 'g vera', 'جي فيرا', 'calcium carbonate', 'magnesium oxide', 'chewable calcium', 'عظام', 'bones', '#dietary_supplements', '#calcium'],
    usage: 'كالسيوم + ماغنسيوم قابل للمضغ لدعم العظام والتقلصات.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرة يومياً بعد الأكل. عند التقلصات: قرص صباحاً وقرص مساءً.'),
    warnings: BONE_SUPPORT_WARNINGS,
  },

  // 122
  {
    id: 'pro-efu-120ml-syrup-mvs2',
    name: 'pro efu 120 ml syrup',
    genericName: 'dark honey & thyme leaf extract & ivy leaf extract & grapefruit seed extract',
    concentration: '120ml',
    price: 45,
    matchKeywords: ['pro efu', 'برو ايفو', 'ivy', 'thyme', 'honey', 'cough', 'كحة', 'bronchitis', 'شعب', '#dietary_supplements'],
    usage: 'شراب عشبي لدعم السعال وتهدئة الحلق.',
    timing: '٣ مرات يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل ٣ مرات يومياً' : '١٠ مل ٣ مرات يومياً'),
    warnings: [...HERBAL_WARNINGS, 'غير مناسب للأطفال أقل من سنتين.'],
  },

  // 123
  {
    id: 'redand-20-capsules-mvs2',
    name: 'redand 20 capsules',
    genericName: 'iron & lactoferrin & folic acid & vitamin b12 & vitamin b6 & vitamin c',
    concentration: '20 caps',
    price: 225,
    matchKeywords: ['redand', 'ريداند', 'lactoferrin', 'iron', 'anemia', 'انيميا', 'immunity', 'مناعة', '#dietary_supplements', '#iron'],
    usage: 'حديد مع لاكتوفرّين وفوليك وفيتامينات لدعم تكوين الدم والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 124
  {
    id: 'k2-calcirave-30-cap-mvs2',
    name: 'k2 -calcirave 30 cap',
    genericName: 'vitamin k2 & calcium & zinc & vitamin d',
    concentration: '30 caps',
    price: 114,
    matchKeywords: ['k2 calcirave', 'calcirave', 'كالسي ريف', 'vitamin k2', 'calcium', 'vitamin d', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'دعم العظام (كالسيوم + فيتامين D + K2 + زنك).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين.'],
  },

  // 125
  {
    id: 'appegreek-syrup-100ml-mvs2',
    name: 'appegreek syrup 100 ml',
    genericName: 'ferrous bisglycinate & l lysine & vitamin c & vitamin e & vitamin b complex',
    concentration: '100ml',
    price: 120,
    matchKeywords: ['appegreek', 'ابي جريك', 'appetite', 'فاتح شهية', 'lysine', 'iron syrup', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب فاتح شهية مع دعم للدم (ليسين + حديد + فيتامينات).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 126
  {
    id: 'romaglobin-120ml-syrup-mvs2',
    name: 'romaglobin 120 ml syrup',
    genericName: 'vitamin c & vitamin b1 & vitamin b2 & niacin & vitamin b6 & vitamin b12',
    concentration: '120ml',
    price: 65,
    matchKeywords: ['romaglobin', 'روماجلوبين', 'b vitamins syrup', 'niacin', 'fatigue', 'ارهاق', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'شراب فيتامينات ب مع C لدعم الطاقة والشهية.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً' : '١٠ مل يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 127
  {
    id: 'd-carni-20-tablet-mvs2',
    name: 'd-carni 20 tablet',
    genericName: 'vitamin d3 & l-carnitine',
    concentration: '20 tabs',
    price: 150,
    matchKeywords: ['d-carni', 'دي كارني', 'l-carnitine', 'vitamin d3', 'energy', 'طاقة', 'fatigue', 'ارهاق', '#multi_vitamins'],
    usage: 'كارنيتين مع فيتامين D3 لدعم الطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 128
  {
    id: 'dugofem-30-sachets-mvs2',
    name: 'dugofem 30 sachets',
    genericName: 'myo-inositol & d-chiro-inositol & coenzyme q10 & vitamin d3 & folic acid',
    concentration: '30 sachets',
    price: 350,
    matchKeywords: ['dugofem', 'دوجوفيم', 'myo-inositol', 'd-chiro-inositol', 'pcos', 'تكيس المبايض', 'fertility', 'خصوبة', 'coq10', 'folic', '#multi_vitamins'],
    usage: 'مكمل لدعم تنظيم التبويض وتكيس المبايض (Inositol + CoQ10 + فوليك + D3).',
    timing: 'مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد مرتين يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 129
  {
    id: 'caly-ibm-120ml-syrup-mvs2',
    name: 'caly ibm 120 ml syrup',
    genericName: 'calcium & vitamin d3 & zinc',
    concentration: '120ml',
    price: 69,
    matchKeywords: ['caly ibm', 'كالي اي بي ام', 'calcium syrup', 'zinc', 'vitamin d3', 'bones', 'عظام', 'growth', 'نمو', '#multi_vitamins', '#calcium'],
    usage: 'شراب كالسيوم مع زنك وفيتامين D3 للأطفال لدعم العظام والنمو.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: BONE_SUPPORT_WARNINGS,
  },
];

