import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
  'إذا لديك مرض مزمن/حساسية شديدة أو تتناول أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين A أو D أو E أو K بجرعات عالية.',
  'الجرعات الزائدة من فيتامينات A/D/E/K قد تسبب أعراض تسمم أو اضطرابات نزف.',
];

const IRON_SUPPLEMENT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
  'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
  'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const OMEGA_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'يُستخدم بحذر مع أدوية السيولة أو اضطرابات النزف.',
  'قد يسبب تجشؤ بطعم السمك/اضطراب معدة؛ يؤخذ مع الطعام.',
];

const ZINC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const BONE_SUPPORT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
  'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const PROBIOTIC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'إن وُجد نقص مناعة شديد أو علاج كيماوي/كورتيزون عالي الجرعة: استخدم بحذر.',
];

const MAGNESIUM_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إسهال/مغص خاصة مع الجرعات العالية.',
  'يُستخدم بحذر مع مرضى الكلى.',
];

const HERBAL_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'أوقف الاستخدام إذا ظهرت حساسية (طفح/حكة/تورم).',
];

const D3_GENERAL_DOSING_RULE = (_w: number, ageMonths: number) => {
  if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
  if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
  return '١٠٠٠ وحدة دولية يومياً';
};

export const MULTIVITAMINS_SUPPLEMENTS_6: Medication[] = [
  // ==========================================
  // multivitamins + supplements 6
  // Items: 326 → 387
  // ==========================================

  // 326
  {
    id: 'c-zinc-glob-20-chew-tabs-mvs6',
    name: 'c-zinc glob 20 chew. tabs.',
    genericName: 'vitamin c & zinc bisglycinate chelate',
    concentration: '20 chew tabs',
    price: 50,
    matchKeywords: ['c-zinc glob', 'c zinc glob', 'سي زنك جلوب', 'vitamin c', 'zinc bisglycinate', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'فيتامين C + زنك لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 327
  {
    id: 'domy-30-tabs-mvs6',
    name: 'domy 30 tabs',
    genericName: 'polysaccharide iron & lactoferrin & folic acid & vitamin',
    concentration: '30 tabs',
    price: 95,
    matchKeywords: ['domy', 'دومي', 'polysaccharide iron', 'lactoferrin', 'folic acid', 'iron', 'anemia', 'انيميا', '#iron', '#multi_vitamins'],
    usage: 'حديد مع لاكتوفرّين وفوليك لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 328
  {
    id: 'empirg-b12-30-chew-tab-mvs6',
    name: 'empirg b12 30 chew.tab',
    genericName: 'methylcobalamin & folic acid',
    concentration: '30 chew tabs',
    price: 85,
    matchKeywords: ['empirg b12', 'امبيرج ب١٢', 'methylcobalamin', 'folic acid', 'b12', 'folate', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'B12 (ميثيل) + فوليك لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 329
  {
    id: 'ertha-iron-20-pieces-mvs6',
    name: 'ertha iron 20 pieces',
    genericName: 'iron & zinc & vitamins',
    concentration: '20 pieces',
    price: 50,
    matchKeywords: ['ertha iron', 'ارثا ايرون', 'iron', 'zinc', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع زنك وفيتامينات لدعم الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 330
  {
    id: 'fohali-folic-acid-vitamin-b12-30-tabs-mvs6',
    name: 'fohali folic acid vitamin b12 - 30 tabs.',
    genericName: 'folic acid & vitamin b12',
    concentration: '30 tabs',
    price: 79,
    matchKeywords: ['fohali', 'فوهالي', 'folic acid', 'vitamin b12', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'فوليك + B12 لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 331
  {
    id: 'furag-6-sachets-mvs6',
    name: 'furag 6 sachets',
    genericName: 'lactobacillus acidophilus & beta glucan & inulin & zinc',
    concentration: '6 sachets',
    price: 54,
    matchKeywords: ['furag', 'فوراج', 'lactobacillus', 'beta glucan', 'inulin', 'zinc', 'probiotic', 'بروبيوتك', 'ibs', 'قولون', '#multi_vitamins'],
    usage: 'بروبيوتك + بريبايوتك + بيتا جلوكان + زنك لدعم الهضم والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.PROBIOTICS,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ٦ أيام.'),
    warnings: [...PROBIOTIC_WARNINGS, ...ZINC_WARNINGS],
  },

  // 332
  {
    id: 'irfe-14-sachets-mvs6',
    name: 'irfe 14 sachets',
    genericName: 'ferrous fumarate & lactoferrin & folic acid & vitamin c & vitami',
    concentration: '14 sachets',
    price: 89,
    matchKeywords: ['irfe', 'ايرفي', 'ferrous fumarate', 'lactoferrin', 'folic acid', 'vitamin c', 'iron', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'أكياس حديد مع لاكتوفرّين وفيتامينات لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 333
  {
    id: 'ordex-30-pieces-mvs6',
    name: 'ordex 30 pieces',
    genericName: 'vitamin a & vitamin b1 & vitamin b3 & vitamin b6 & biot',
    concentration: '30 pieces',
    price: 75,
    matchKeywords: ['ordex', 'اورديكس', 'vitamin a', 'b1', 'b3', 'b6', 'biotin', 'hair', 'شعر', '#multi_vitamins'],
    usage: 'مكمل فيتامينات (A + مجموعة ب + بيوتين).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 334
  {
    id: 'orgiron-30-pieces-mvs6',
    name: 'orgiron 30 pieces',
    genericName: 'lactofirn & iron & vitamin c',
    concentration: '30 pieces',
    price: 150,
    matchKeywords: ['orgiron', 'اورجي ايرون', 'lactoferrin', 'iron', 'vitamin c', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'لاكتوفرّين + حديد + فيتامين C لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 335
  {
    id: 'p-iron-30mg-20-tab-jar-mvs6',
    name: 'p-iron 30 mg 20 tab jar',
    genericName: 'iron & fully reacted amino acid chelated minerals & vitamin c',
    concentration: '30mg (20 tabs)',
    price: 110,
    matchKeywords: ['p-iron 30', 'p iron', 'بي ايرون', 'chelated iron', 'vitamin c', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'حديد مخلّب مع فيتامين C لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 336
  {
    id: 'rotal-10-sachets-mvs6',
    name: 'rotal 10 sachets',
    genericName: 'omega 3 & iron & folic acid & vitamin b complex & vitamin c',
    concentration: '10 sachets',
    price: 120,
    matchKeywords: ['rotal', 'روتال', 'omega 3', 'iron', 'folic acid', 'b complex', 'vitamin c', '#multi_vitamins'],
    usage: 'أكياس أوميجا 3 + حديد + فيتامينات لدعم الدم والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...OMEGA_WARNINGS],
  },

  // 337
  {
    id: 'ruby-liquid-chocolate-200gm-mvs6',
    name: 'ruby liquid chocolate 200 gm',
    genericName: 'iron & lactoferrin & zinc & folic acid',
    concentration: '200 gm',
    price: 69,
    matchKeywords: ['ruby liquid chocolate', 'ruby chocolate', 'روبي شوكولاتة', 'iron', 'lactoferrin', 'zinc', 'folic acid', '#multi_vitamins'],
    usage: 'شوكولاتة سائلة مُدعّمة بالحديد واللاكتوفرّين لدعم الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Solution',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: fixed('ملعقة كبيرة مرة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 338
  {
    id: 'terna-30-tabs-mvs6',
    name: 'terna 30 tabs',
    genericName: 'vitamin a & vitamin d & vitamin e & vitamin k & vitamin b1 & v',
    concentration: '30 tabs',
    price: 140,
    matchKeywords: ['terna', 'تيرنا', 'vitamin a', 'vitamin d', 'vitamin e', 'vitamin k', 'b1', '#multi_vitamins'],
    usage: 'مولتي فيتامينات تشمل A/D/E/K + مجموعة ب.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 339
  {
    id: 'avalon-vitamin-d-30-capsules-mvs6',
    name: 'avalon vitamin d 30 capsules',
    genericName: 'vitamin d3',
    concentration: '30 caps',
    price: 110,
    matchKeywords: ['avalon vitamin d', 'avalon d3', 'افالون فيتامين د', 'vitamin d3', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل (حسب تركيز العبوة).'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 340
  {
    id: 'globrind-17mg-20-caps-mvs6',
    name: 'globrind 17 mg 20 caps',
    genericName: 'iron & zinc & folic acid & vitamin b12',
    concentration: '17mg (20 caps)',
    price: 80,
    matchKeywords: ['globrind', 'جلوبرايند', 'iron 17mg', 'zinc', 'folic acid', 'b12', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'حديد مع زنك وفوليك وB12 لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 341
  {
    id: 'tulango-vit-syrup-120ml-mvs6',
    name: 'tulango-vit syrup 120 ml',
    genericName: 'royal jelly & vitamin b complex & vitamin c & vitamin d3 & vita',
    concentration: '120ml',
    price: 95,
    matchKeywords: ['tulango-vit', 'tulango vit', 'تولانجو فيت', 'royal jelly', 'b complex', 'vitamin c', 'vitamin d3', 'kids', 'اطفال', '#multi_vitamins'],
    usage: 'شراب مولتي فيتامين مع منتجات نحل لدعم المناعة والشهية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, ...HERBAL_WARNINGS],
  },

  // 342
  {
    id: 'ivy-spir-syrup-100ml-mvs6',
    name: 'ivy spir syrup 100 ml',
    genericName: 'ivy & thyum & liquorice',
    concentration: '100ml',
    price: 59,
    matchKeywords: ['ivy spir', 'ايفي سبير', 'ivy', 'thyme', 'liquorice', 'cough', 'كحة', 'phlegm', 'بلغم', '#cough'],
    usage: 'شراب عشبي للكحة وطرد البلغم (لبلاب + زعتر + عرقسوس).',
    timing: '٣ مرات يومياً.',
    category: Category.HERBAL_COUGH,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل ٣ مرات يومياً' : '١٠ مل ٣ مرات يومياً'),
    warnings: [...HERBAL_WARNINGS, 'غير مناسب للأطفال أقل من سنتين.'],
  },

  // 343
  {
    id: 'ezenervac-350mg-30-tabs-mvs6',
    name: 'ezenervac 350 mg 30 tabs',
    genericName: 'alpha lipoic acid & benfotiamin & vitamin b12',
    concentration: '350mg',
    price: 195,
    matchKeywords: ['ezenervac', 'ايزينيرفاك', 'alpha lipoic acid', 'benfotiamine', 'vitamin b12', 'neuropathy', 'اعصاب السكر', '#multi_vitamins'],
    usage: 'دعم الأعصاب الطرفية (ALA + بنفوتيامين + B12).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 344
  {
    id: 'obaxo-30-tabs-mvs6',
    name: 'obaxo 30 tabs.',
    genericName: 'vitamin c & vitamin e & vitamin a & beta-carotene & selenium',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['obaxo', 'اوباكسو', 'vitamin c', 'vitamin e', 'vitamin a', 'beta-carotene', 'selenium', 'antioxidant', 'مضاد اكسدة', '#multi_vitamins'],
    usage: 'مضادات أكسدة (C + E + A/بيتاكاروتين + سيلينيوم).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 345
  {
    id: 'atlanto-3-20-caps-mvs6',
    name: 'atlanto 3 20 caps',
    genericName: 'fish oil & epa & dha',
    concentration: '20 caps',
    price: 190,
    matchKeywords: ['atlanto 3', 'atlanto', 'اتلانتو', 'fish oil', 'epa', 'dha', 'omega 3', '#multi_vitamins', '#omega3'],
    usage: 'أوميجا 3 (EPA/DHA) لدعم القلب والمخ.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 346
  {
    id: 'atlantohem-20-caps-mvs6',
    name: 'atlantohem 20 caps',
    genericName: 'lactoferrin & ferrous sulphate & vitamin c & folic acid & vitami',
    concentration: '20 caps',
    price: 130,
    matchKeywords: ['atlantohem', 'اتلانتو هيم', 'lactoferrin', 'ferrous sulphate', 'vitamin c', 'folic acid', 'iron', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'لاكتوفرّين + حديد + فيتامينات لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 347
  {
    id: 'biotin-10000mcg-100-tabs-natrol-mvs6',
    name: 'biotin 10.000 mcg 100 tabs. (natrol)',
    genericName: 'biotin',
    concentration: '10000mcg',
    price: 630,
    matchKeywords: ['biotin 10000 natrol', 'natrol biotin', 'بيوتين ناترول', 'hair', 'شعر', 'nails', 'اظافر', '#multi_vitamins'],
    usage: 'بيوتين لدعم الشعر والأظافر.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 348
  {
    id: 'bondiga-30-tablets-mvs6',
    name: 'bondiga 30tablets',
    genericName: 'calcium carbonate & vitamin d3 & zinc & magnesium',
    concentration: '30 tabs',
    price: 78,
    matchKeywords: ['bondiga', 'بونديجا', 'calcium carbonate', 'vitamin d3', 'zinc', 'magnesium', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'دعم العظام (كالسيوم + D3 + ماغنسيوم + زنك).',
    timing: 'مرة يومياً.',
    category: Category.CALCIUM_GROWTH,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 349
  {
    id: 'calcium-3-20-tabs-mvs6',
    name: 'calcium 3 - 20 tabs.',
    genericName: 'calcium & magnesium & vitamin d3',
    concentration: '20 tabs',
    price: 95,
    matchKeywords: ['calcium 3', 'كالسيوم 3', 'calcium', 'magnesium', 'vitamin d3', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'كالسيوم + ماغنسيوم + D3 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.CALCIUM_GROWTH,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 350
  {
    id: 'cola-chond-30-tabs-mvs6',
    name: 'cola - chond 30 tabs',
    genericName: 'vitamin c & vitamin d3 & collagen & glucosamine sulfate',
    concentration: '30 tabs',
    price: 255,
    matchKeywords: ['cola chond', 'كولا كوند', 'collagen', 'glucosamine sulfate', 'vitamin c', 'vitamin d3', 'joints', 'مفاصل', '#multi_vitamins'],
    usage: 'دعم المفاصل (كولاجين + جلوكوزامين + فيتامينات).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.BONE_SUPPORT,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 351
  {
    id: 'dendra-30-tabs-mvs6',
    name: 'dendra 30 tabs.',
    genericName: 'alpha lipoic acid & vitamin b1 & vitamin b6 & folic acid & vit',
    concentration: '30 tabs',
    price: 315,
    matchKeywords: ['dendra', 'ديندرا', 'alpha lipoic acid', 'b1', 'b6', 'folic acid', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'دعم الأعصاب والطاقة (ALA + فيتامينات ب + فوليك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 352
  {
    id: 'loxymune-junior-syrup-200ml-mvs6',
    name: 'loxymune junior syrup 200 ml',
    genericName: 'vitamin c & vitamin a & vitamin d & vitamin b6 & copper & sel',
    concentration: '200ml',
    price: 540,
    matchKeywords: ['loxymune junior', 'لوكسيميون جونيور', 'kids vitamins', 'vitamin c', 'vitamin a', 'vitamin d', 'b6', 'copper', 'selenium', '#multi_vitamins'],
    usage: 'شراب مولتي فيتامينات ومعادن للأطفال لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 353
  {
    id: 'moratx-120ml-syrup-mvs6',
    name: 'moratx 120 ml syrup',
    genericName: 'multivitamins',
    concentration: '120ml',
    price: 43.9,
    matchKeywords: ['moratx', 'موراتيكس', 'multivitamins syrup', 'kids', 'اطفال', '#multi_vitamins'],
    usage: 'شراب مولتي فيتامين للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 354
  {
    id: 'q-cyrva-health-100ml-syrup-mvs6',
    name: 'q cyrva health 100 ml syrup',
    genericName: 'omega 3 & vitamin d3 & vitamin b1 & vitamin b2 & vitamin b3',
    concentration: '100ml',
    price: 95,
    matchKeywords: ['q cyrva health', 'cyrva health', 'سيرفا هيلث', 'omega 3', 'vitamin d3', 'b1', 'b2', 'b3', '#multi_vitamins'],
    usage: 'شراب أوميجا 3 مع فيتامينات لدعم التركيز والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 355
  {
    id: 'regnadex-30-tabs-mvs6',
    name: 'regnadex 30 tabs',
    genericName: 'folic acid & zink & vitamin c & vitamin b12 & vitamin b6 & le',
    concentration: '30 tabs',
    price: 75,
    matchKeywords: ['regnadex', 'ريجناديكس', 'folic acid', 'zinc', 'vitamin c', 'b12', 'b6', '#multi_vitamins'],
    usage: 'فوليك + زنك + فيتامينات لدعم الأعصاب والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 356
  {
    id: 'sansovit-calcium-syrup-100ml-chocolate-mvs6',
    name: 'sansovit calcium syrup 100 ml (chocolate)',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vita',
    concentration: '100ml',
    price: 32,
    matchKeywords: ['sansovit calcium 100 chocolate', 'sansovit calcium 100', 'سانسوفيت كالسيوم ١٠٠', 'chocolate', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النمو (نكهة شوكولاتة).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 357
  {
    id: 'sansovit-calcium-syrup-320ml-mvs6',
    name: 'sansovit calcium syrup 320 ml',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vita',
    concentration: '320ml',
    price: 80,
    matchKeywords: ['sansovit calcium 320', 'سانسوفيت كالسيوم ٣٢٠', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النمو.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 358
  {
    id: 'sansovit-calcium-syrup-320ml-chocolate-mvs6',
    name: 'sansovit calcium syrup 320 ml (chocolate)',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vita',
    concentration: '320ml',
    price: 85,
    matchKeywords: ['sansovit calcium 320 chocolate', 'سانسوفيت كالسيوم ٣٢٠ شوكولاتة', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال (نكهة شوكولاتة) لدعم النمو.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 359
  {
    id: 'sansovit-plus-syrup-480ml-mvs6',
    name: 'sansovit plus syrup 480 ml',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vit',
    concentration: '480ml',
    price: 100,
    matchKeywords: ['sansovit plus 480', 'sansovit plus', 'سانسوفيت بلس ٤٨٠', '#multi_vitamins'],
    usage: 'شراب مولتي فيتامين للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 360
  {
    id: 'semabella-syrup-125ml-mvs6',
    name: 'semabella syrup 125 ml',
    genericName: 'calcium & magnesium & vitamin c & zinc & vitamin d3 & manga',
    concentration: '125ml',
    price: 95,
    matchKeywords: ['semabella', 'سيمابيلا', 'calcium', 'magnesium', 'vitamin c', 'zinc', 'vitamin d3', 'manganese', '#multi_vitamins'],
    usage: 'شراب معادن وفيتامينات لدعم العظام والمناعة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.CALCIUM_GROWTH,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 361
  {
    id: 'tresolyse-120ml-syrup-mvs6',
    name: 'tresolyse 120 ml syrup',
    genericName: 'lysine & niacin & iron & zinc & vitamin b1 & vitamin b2 & vit',
    concentration: '120ml',
    price: 78,
    matchKeywords: ['tresolyse', 'تريسولايز', 'lysine', 'niacin', 'iron', 'zinc', 'b1', 'b2', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'شراب فاتح شهية ودعم نمو/دم (ليسين + حديد + زنك + فيتامينات).',
    timing: 'مرة يومياً.',
    category: Category.DIGESTIVE,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 362
  {
    id: 'jomato-20-pieces-mvs6',
    name: 'jomato 20 pieces',
    genericName: 'lactoferrin & zinc & selenium & vitamin c',
    concentration: '20 pieces',
    price: 70,
    matchKeywords: ['jomato', 'جوميتو', 'lactoferrin', 'zinc', 'selenium', 'vitamin c', 'immunity', 'مناعة', '#dietary_supplements'],
    usage: 'لاكتوفرّين + زنك + سيلينيوم + C لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 363
  {
    id: 'ivy-prandy-120ml-syrup-mvs6',
    name: 'ivy prandy 120 ml syrup',
    genericName: 'n-acetyl cysteine & ivy extract & thyme extract & licorice extr',
    concentration: '120ml',
    price: 60,
    matchKeywords: ['ivy prandy', 'ايفي براندي', 'n-acetyl cysteine', 'nac', 'ivy', 'thyme', 'licorice', 'cough', 'كحة', 'phlegm', 'بلغم', '#cough'],
    usage: 'شراب للكحة والبلغم (NAC + لبلاب + زعتر + عرقسوس).',
    timing: '٣ مرات يومياً.',
    category: Category.HERBAL_COUGH,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل ٣ مرات يومياً' : '١٠ مل ٣ مرات يومياً'),
    warnings: [...HERBAL_WARNINGS, 'غير مناسب للأطفال أقل من سنتين.'],
  },

  // 364
  {
    id: 'ferroflav-120ml-syrup-mvs6',
    name: 'ferroflav 120ml syrup',
    genericName: 'ferric pyrophosphate & vitamin b1 & vitamin b6 & vitamin b12',
    concentration: '120ml',
    price: 89,
    matchKeywords: ['ferroflav', 'فيروفلاف', 'ferric pyrophosphate', 'b1', 'b6', 'b12', 'iron syrup', 'anemia', 'انيميا', '#dietary_supplements'],
    usage: 'شراب حديد مع فيتامينات ب لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 365
  {
    id: 'hanzagink-30-tabs-mvs6',
    name: 'hanzagink 30 tabs',
    genericName: 'ginko biloba',
    concentration: '30 tabs',
    price: 140,
    matchKeywords: ['hanzagink', 'هانزاجينك', 'ginkgo biloba', 'focus', 'تركيز', 'memory', 'ذاكرة', '#dietary_supplements'],
    usage: 'جنكو بيلوبا لدعم الذاكرة والتركيز.',
    timing: 'مرة يومياً صباحاً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد خطر النزف مع أدوية السيولة (جنكو).'],
  },

  // 366
  {
    id: 'vhc-joints-30-tabs-mvs6',
    name: 'vhc joints 30 tabs',
    genericName: 'glucosamine & vitamin c & bromaline & chondroitin & gin',
    concentration: '30 tabs',
    price: 349,
    matchKeywords: ['vhc joints', 'vhc', 'glucosamine', 'chondroitin', 'bromelain', 'vitamin c', 'joints', 'مفاصل', '#dietary_supplements'],
    usage: 'دعم المفاصل والغضاريف (جلوكوزامين + كوندرويتين + بروميلين).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 367
  {
    id: 'astroheam-10-capsules-mvs6',
    name: 'astroheam 10 capsules',
    genericName: 'lactoferrin & iron & vitamin c & folic acid & vitamin b12',
    concentration: '10 caps',
    price: 150,
    matchKeywords: ['astroheam', 'استروهيم', 'lactoferrin', 'iron', 'vitamin c', 'folic acid', 'b12', 'anemia', 'انيميا', '#dietary_supplements'],
    usage: 'لاكتوفرّين + حديد + فيتامينات لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ١٠ أيام.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 368
  {
    id: 'adipomove-30-tablet-mvs6',
    name: 'adipomove 30 tablet',
    genericName: 'chitosan & l-ascorbic acid & chromium chloride hexa hydra',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['adipomove', 'ادايبوموف', 'chitosan', 'vitamin c', 'chromium', 'weight', 'تخسيس', '#dietary_supplements'],
    usage: 'مكمل (كيتوزان + كروم + فيتامين C) لدعم التحكم بالوزن.',
    timing: 'مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد قبل الأكل مرتين يومياً (مع كوب ماء).'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 369
  {
    id: 'cartiojo-30-caps-mvs6',
    name: 'cartiojo 30 caps',
    genericName: 'glucoseamine sulphate & ginko biloba extract leaf & vitamin c',
    concentration: '30 caps',
    price: 150,
    matchKeywords: ['cartiojo', 'كارتيوجو', 'glucosamine sulphate', 'ginkgo biloba', 'vitamin c', 'joints', 'مفاصل', '#dietary_supplements'],
    usage: 'دعم المفاصل (جلوكوزامين + C) مع جنكو.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).', 'قد يزيد خطر النزف مع أدوية السيولة (جنكو).'],
  },

  // 370
  {
    id: 'enera-shots-10-drinkable-ampoules-25ml-mvs6',
    name: 'enera shots 10 drinkable ampoules x 25 ml',
    genericName: 'marine collagen & chondroitin sulfate & glucosamine sulfate',
    concentration: '10 drinkable ampoules',
    price: 390,
    matchKeywords: ['enera shots', 'انيرا شوتس', 'drinkable ampoules', 'marine collagen', 'chondroitin', 'glucosamine', 'joints', 'مفاصل', '#dietary_supplements'],
    usage: 'أمبولات للشرب لدعم المفاصل (كولاجين + كوندرويتين + جلوكوزامين).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Ampoules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('أمبول فموي واحد يومياً بعد الأكل.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية المأكولات البحرية (كولاجين بحري).', 'يُستخدم بحذر مع حساسية القشريات (جلوكوزامين).'],
  },

  // 371
  {
    id: 'kodomeg-30-cap-mvs6',
    name: 'kodomeg 30 cap',
    genericName: 'triple omega & vitamin e',
    concentration: '30 caps',
    price: 195,
    matchKeywords: ['kodomeg', 'كودوميج', 'triple omega', 'omega', 'vitamin e', '#dietary_supplements', '#omega3'],
    usage: 'تربل أوميجا مع فيتامين E لدعم القلب والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 372
  {
    id: 'bio-gainers-510g-powder-mvs6',
    name: 'bio-gainers 510 gram powder',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose &',
    concentration: '510g',
    price: 290,
    matchKeywords: ['bio-gainers', 'bio gainers', 'زيادة وزن', 'gainer', 'milk', 'whey', 'maltodextrin', '#dietary_supplements'],
    usage: 'مكمل زيادة وزن/سعرات (بروتين + كربوهيدرات).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('٢–٣ ملاعق تُذاب في ٢٥٠–٣٠٠ مل ماء/لبن مرة يومياً بعد الأكل أو بعد التمرين.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى أو السكري (قد يحتوي سكريات).'],
  },

  // 373
  {
    id: 'choco-monster-powder-10-sachets-mvs6',
    name: 'choco monster powder 10 sachets',
    genericName: 'skimmed milk & whey protein & bovine colostrum & vitamin',
    concentration: '10 sachets',
    price: 200,
    matchKeywords: ['choco monster', 'تشوكو مونستر', 'whey protein', 'colostrum', 'weight gain', 'زيادة وزن', '#dietary_supplements'],
    usage: 'أكياس مكمل تغذية/زيادة وزن (بروتين + كولوستروم).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠–٢٥٠ مل لبن/ماء بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى أو السكري (قد يحتوي سكريات).'],
  },

  // 374
  {
    id: 'camixer-syrup-120ml-mvs6',
    name: 'camixer syrup 120 ml',
    genericName: 'calcium & magnesium & vitamin d & zinc',
    concentration: '120ml',
    price: 89,
    matchKeywords: ['camixer', 'كاميكسر', 'calcium', 'magnesium', 'vitamin d', 'zinc', 'bones', 'عظام', '#dietary_supplements'],
    usage: 'شراب معادن لدعم العظام للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 375
  {
    id: 'centravita-colin-100ml-syrup-mvs6',
    name: 'centravita colin 100 ml syrup',
    genericName: 'citicoline',
    concentration: '100ml',
    price: 250,
    matchKeywords: ['centravita colin', 'centravita', 'citicoline', 'focus', 'تركيز', 'memory', 'ذاكرة', '#dietary_supplements'],
    usage: 'سيتيكولين لدعم التركيز والذاكرة (مكمل/دعم عصبي).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Syrup',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 18,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل مرة يومياً' : '١٠ مل مرة يومياً'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 376
  {
    id: 'mobilex-10-sachets-mvs6',
    name: 'mobilex 10 sachets',
    genericName: 'milk protein concentrate & casein',
    concentration: '10 sachets',
    price: 160,
    matchKeywords: ['mobilex', 'موبيليكس', 'milk protein', 'casein', 'protein', 'بروتين', '#dietary_supplements'],
    usage: 'أكياس بروتين/كازين لدعم التغذية.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠–٢٥٠ مل ماء/لبن بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 377
  {
    id: 'promix-junior-chocolate-milk-powder-400gm-mvs6',
    name: 'promix junior (chocolate & milk) powder 400 gm',
    genericName: 'protein & multivitamins & carbohydrates',
    concentration: '400 gm',
    price: 95,
    matchKeywords: ['promix junior', 'برو ميكس جونيور', 'kids formula', 'protein', 'multivitamins', 'carbohydrates', 'weight gain kids', 'زيادة وزن', '#dietary_supplements'],
    usage: 'مكمل تغذية للأطفال (بروتين + فيتامينات + كربوهيدرات).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: fixed('٢ ملعقة كبيرة تُذاب في ٢٠٠ مل لبن مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/عدم تحمل اللاكتوز.', 'قد يحتوي سكريات.'],
  },

  // 378
  {
    id: 'spego-10-sachets-mvs6',
    name: 'spego 10 sachets',
    genericName: 'whey protein & skimmed milk & selenium & zinc & magnesiu',
    concentration: '10 sachets',
    price: 175,
    matchKeywords: ['spego', 'سبيجو', 'whey protein', 'selenium', 'zinc', 'magnesium', '#dietary_supplements'],
    usage: 'أكياس بروتين مع معادن لدعم التغذية.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠–٢٥٠ مل ماء/لبن بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...MAGNESIUM_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 379
  {
    id: 'umatone-30-sachets-mvs6',
    name: 'umatone 30 sachets',
    genericName: 'cystidine diphosphate choline & pyroloquinoline quinone & p',
    concentration: '30 sachets',
    price: 450,
    matchKeywords: ['umatone', 'يوماتون', 'cdp choline', 'pqq', 'focus', 'تركيز', 'energy', 'طاقة', '#dietary_supplements'],
    usage: 'مكمل لدعم الطاقة والتركيز (CDP-Choline + PQQ ...).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً صباحاً بعد الإفطار.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 380
  {
    id: 'bronchoneer-30-tab-mvs6',
    name: 'bronchoneer 30 tab',
    genericName: 'n -actyl-l-cysteine & resvitrol & quercetin & garlic extract &',
    concentration: '30 tabs',
    price: 147,
    matchKeywords: ['bronchoneer', 'برونكونير', 'n-acetyl cysteine', 'resveratrol', 'quercetin', 'garlic', 'immunity', 'مناعة', '#dietary_supplements'],
    usage: 'مكمل لدعم الجهاز التنفسي/المناعة (NAC + مضادات أكسدة + ثوم).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: HERBAL_WARNINGS,
  },

  // 381
  {
    id: 'super-formula-200g-powder-mvs6',
    name: 'super formula 200 gram powder',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & s',
    concentration: '200g',
    price: 125,
    matchKeywords: ['super formula 200', 'سوبر فورميولا', 'milk', 'whey', 'maltodextrin', 'weight gain', 'زيادة وزن', '#dietary_supplements'],
    usage: 'مكمل تغذية/زيادة سعرات (بروتين + كربوهيدرات).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('٢–٣ ملاعق تُذاب في ٢٥٠ مل ماء/لبن مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى أو السكري (قد يحتوي سكريات).'],
  },

  // 382
  {
    id: 'menestro-1000mg-20-caps-mvs6',
    name: 'menestro 1000 mg 20 caps',
    genericName: 'evening primrose oil & vitamin e',
    concentration: '1000mg (20 caps)',
    price: 180,
    matchKeywords: ['menestro', 'مينسترو', 'evening primrose oil', 'vitamin e', 'pms', 'دورة', '#herbal_supplements'],
    usage: 'زيت زهرة الربيع المسائية مع فيتامين E لدعم أعراض ما قبل الدورة.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: [...HERBAL_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 383
  {
    id: 'c-vall-10-tablet-mvs6',
    name: 'c vall 10 tablet',
    genericName: 'vitamin c & citrus bioflavonoids & rutin',
    concentration: '10 tabs',
    price: 110,
    matchKeywords: ['c vall', 'سي فال', 'vitamin c', 'bioflavonoids', 'rutin', 'immunity', 'مناعة', '#dietary_supplements'],
    usage: 'فيتامين C مع بيوفلافونويدز لدعم المناعة والشعيرات الدموية.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 384
  {
    id: 'proli-10-sachets-mvs6',
    name: 'proli 10 sachets',
    genericName: 'probiotic & zinc & vitamin c & lactofrin',
    concentration: '10 sachets',
    price: 80,
    matchKeywords: ['proli', 'برولي', 'probiotic', 'zinc', 'vitamin c', 'lactoferrin', 'ibs', 'قولون', '#dietary_supplements'],
    usage: 'بروبيوتك مع زنك وC ولاكتوفرّين لدعم الهضم والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.PROBIOTICS,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٠ أيام.'),
    warnings: [...PROBIOTIC_WARNINGS, ...ZINC_WARNINGS],
  },

  // 385
  {
    id: 'makgy-collagen-10-sachets-mvs6',
    name: 'makgy collagen 10 sachets',
    genericName: 'collagen & calcium & vitamin d3 & vitamins c',
    concentration: '10 sachets',
    price: 270,
    matchKeywords: ['makgy collagen', 'ماكجي كولاجين', 'collagen', 'calcium', 'vitamin d3', 'vitamin c', 'bones', 'عظام', 'skin', 'بشرة', '#dietary_supplements', '#collagen'],
    usage: 'أكياس كولاجين مع كالسيوم وفيتامينات لدعم العظام/البشرة.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 386
  {
    id: 'octo-g-omega-3-30ml-syrup-mvs6',
    name: 'octo-g (omega-3) 30 ml syrup',
    genericName: 'omega 3 fish oil',
    concentration: '30ml',
    price: 70,
    matchKeywords: ['octo-g', 'octo g', 'اوكتو جي', 'omega 3', 'fish oil', 'syrup', '#dietary_supplements', '#omega3'],
    usage: 'أوميجا 3 زيت سمك لدعم المخ والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٢.٥–٥ مل يومياً بعد الأكل' : '٥ مل يومياً بعد الأكل'),
    warnings: OMEGA_WARNINGS,
  },

  // 387
  {
    id: 'oianda-120ml-syrup-mvs6',
    name: 'oianda 120 ml syrup',
    genericName: 'carawy seed & dill seed oil & chamomile',
    concentration: '120ml',
    price: 30,
    matchKeywords: ['oianda', 'اوياندا', 'caraway', 'dill', 'chamomile', 'colic', 'مغص', 'gas', 'غازات', '#dietary_supplements'],
    usage: 'شراب عشبي للمغص والغازات.',
    timing: 'عند اللزوم.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Syrup',
    minAgeMonths: 1,
    maxAgeMonths: 144,
    minWeight: 3,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 12 ? '٢.٥ مل ٣ مرات يومياً عند اللزوم' : '٥ مل ٣ مرات يومياً عند اللزوم'),
    warnings: HERBAL_WARNINGS,
  },
];

