import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
  'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين A أو D أو E أو K بجرعات عالية.',
  'الجرعات الزائدة من فيتامينات A/D/E/K قد تسبب أعراض تسمم أو اضطرابات نزف.',
];

const IRON_SUPPLEMENT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
  'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
  'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const OMEGA_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'يُستخدم بحذر مع أدوية السيولة أو اضطرابات النزف.',
  'قد يسبب تجشؤ بطعم السمك/اضطراب معدة؛ يؤخذ مع الطعام.',
];

const ZINC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const BONE_SUPPORT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
  'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const PROBIOTIC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'إن وُجد نقص مناعة شديد أو علاج كيماوي/كورتيزون عالي الجرعة: استخدم بحذر.',
];

const MAGNESIUM_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إسهال/مغص خاصة مع الجرعات العالية.',
  'يُستخدم بحذر مع مرضى الكلى.',
];

const HERBAL_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'أوقف الاستخدام إذا ظهرت حساسية (طفح/حكة/تورم).',
];

const D3_GENERAL_DOSING_RULE = (_w: number, ageMonths: number) => {
  if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
  if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
  return '١٠٠٠ وحدة دولية يومياً';
};

export const MULTIVITAMINS_SUPPLEMENTS_5: Medication[] = [
  // ==========================================
  // multivitamins + supplements 5
  // Items: 260 → 325
  // ==========================================

  // 260
  {
    id: 'actimar-30-caps-mvs5',
    name: 'actimar 30 caps.',
    genericName: 'l-glutamine & l-taurine & thiamine & pyridoxine & zinc',
    concentration: '30 caps',
    price: 90,
    matchKeywords: ['actimar', 'اكتيمار', 'glutamine', 'taurine', 'b1', 'b6', 'zinc', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'مكمل لدعم الطاقة والأعصاب (أحماض أمينية + فيتامينات ب + زنك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 261
  {
    id: 'mixo-tetra-20-caps-mvs5',
    name: 'mixo tetra 20 caps',
    genericName: 'l-methylfolat & methyl cobalamin & vitamin b6',
    concentration: '20 caps',
    price: 110,
    matchKeywords: ['mixo tetra', 'ميكسو تيترا', 'methylfolate', 'methylcobalamin', 'b6', 'b12', 'folate', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'ميثيل فولات + ميثيل كوبالامين + B6 لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 262
  {
    id: 'chromova-30-caps-mvs5',
    name: 'chromova 30 caps',
    genericName: 'myo inositol & chromium & methyl folate',
    concentration: '30 caps',
    price: 240,
    matchKeywords: ['chromova', 'كروموفا', 'myo inositol', 'chromium', 'methyl folate', 'pcos', 'تكيس', '#multi_vitamins', '#minerals'],
    usage: 'مكمل يحتوي ميو-إينوزيتول وكروم لدعم تنظيم السكر/تكيس المبايض.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة مرة يومياً بعد الأكل (قد تُستخدم مرتين حسب الإرشاد).'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 263
  {
    id: 'renkare-30-tabs-mvs5',
    name: 'renkare 30 tabs',
    genericName: 'ferrous bisglycinate & zinc & copper & vitamin b6 & vitamin',
    concentration: '30 tabs',
    price: 130,
    matchKeywords: ['renkare', 'رينكير', 'ferrous bisglycinate', 'iron', 'zinc', 'copper', 'b6', 'anemia', 'انيميا', '#iron', '#minerals', '#multi_vitamins'],
    usage: 'حديد بيسجليسينات مع زنك ونحاس لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 264
  {
    id: 'vitalox-complete-a-z-100-tabs-mvs5',
    name: 'vitalox complete a-z 100 tabs.',
    genericName: 'multivitamins & minerals',
    concentration: '100 tabs',
    price: 890,
    matchKeywords: ['vitalox complete a-z', 'vitalox a-z', 'فيتالوكس كومبليت', 'a-z', 'multivitamins', 'minerals', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن شامل.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 265
  {
    id: 'lifeglobin-syrup-120ml-mvs5',
    name: 'lifeglobin syrup 120 ml',
    genericName: 'iron & zinc & vitamin c & folate & vitamin b12 & cu & lysine',
    concentration: '120ml',
    price: 65,
    matchKeywords: ['lifeglobin', 'لايف جلوبين', 'iron syrup', 'zinc', 'vitamin c', 'folate', 'b12', 'lysine', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب حديد مع فيتامينات ومعادن لدعم الدم والشهية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 266
  {
    id: 'hya-junga-30-cap-mvs5',
    name: 'hya-junga 30 cap',
    genericName: 'hydrolyzed collagen & co-enzyme q10 & hyaluronic acid',
    concentration: '30 caps',
    price: 450,
    matchKeywords: ['hya-junga', 'هيا-جونجا', 'collagen', 'coenzyme q10', 'hyaluronic acid', 'skin', 'بشرة', 'joints', 'مفاصل', '#multi_vitamins'],
    usage: 'دعم البشرة/المفاصل (كولاجين + هيالورونيك + CoQ10).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 267
  {
    id: 'nutritu-fe-14-caps-mvs5',
    name: 'nutritu fe 14 caps.',
    genericName: 'iron & copper & magnesium & calcium & vitamin b12 & vitam',
    concentration: '14 caps',
    price: 60,
    matchKeywords: ['nutritu fe', 'نيوتريتو اف اي', 'iron', 'copper', 'magnesium', 'calcium', 'b12', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'مكمل مع حديد ومعادن لدعم الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 268
  {
    id: 'lactotri-30-capsules-mvs5',
    name: 'lactotri 30 capsules',
    genericName: 'lactoferrin & zinc & vitamin c',
    concentration: '30 caps',
    price: 280,
    matchKeywords: ['lactotri', 'لاكتوتري', 'lactoferrin', 'zinc', 'vitamin c', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'لاكتوفرّين مع زنك وفيتامين C لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 269
  {
    id: 'sleevar-30-caps-mvs5',
    name: 'sleevar 30 caps.',
    genericName: 'vitamin b complex & vitamin e & vitamin a & vitamin k1 & vit',
    concentration: '30 caps',
    price: 350,
    matchKeywords: ['sleevar', 'سليفار', 'b complex', 'vitamin e', 'vitamin a', 'vitamin k1', 'sleep', 'نوم', '#multi_vitamins'],
    usage: 'مولتي فيتامينات (ب + A/E/K) قد يساعد على دعم الأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 270
  {
    id: 'marvy-d-oral-drops-15ml-mvs5',
    name: 'marvy d oral drops 15 ml',
    genericName: 'vitamin d3 & vitamin k',
    concentration: '15ml oral drops',
    price: 60,
    matchKeywords: ['marvy d', 'مارفي د', 'vitamin d3', 'vitamin k', 'drops', 'نقط', '#multi_vitamins', '#vitamin_d'],
    usage: 'نقط فيتامين D3 مع فيتامين K لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 2,
    maxWeight: 250,
    calculationRule: D3_GENERAL_DOSING_RULE,
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K قد يتداخل مع الوارفارين.'],
  },

  // 271
  {
    id: 'ennervita-14-capsules-mvs5',
    name: 'ennervita 14 capsules',
    genericName: 'vitamin a (retinol palmitate) & vitamin d3 (cholecalciferol) &',
    concentration: '14 caps',
    price: 210,
    matchKeywords: ['ennervita', 'انيرفيتا', 'vitamin a', 'vitamin d3', 'retinol palmitate', '#multi_vitamins'],
    usage: 'مكمل فيتامينات (A + D3 ...).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 272
  {
    id: 'ginkofit-30-caps-mvs5',
    name: 'ginkofit 30 caps.',
    genericName: 'royal jelly & ginseng & ginko biloba',
    concentration: '30 caps',
    price: 117,
    matchKeywords: ['ginkofit', 'جينكوفِت', 'ginkgo biloba', 'ginseng', 'royal jelly', 'focus', 'تركيز', '#multi_vitamins'],
    usage: 'منتجات نحل + جنسنج + جنكو لدعم النشاط والتركيز.',
    timing: 'مرة يومياً صباحاً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يزيد خطر النزف مع أدوية السيولة (جنكو).', 'قد يسبب حساسية لمن لديهم حساسية من منتجات النحل.'],
  },

  // 273
  {
    id: 'fedesaforol-20ml-drops-mvs5',
    name: 'fedesaforol 20 ml drops',
    genericName: 'vitamin d3 & vitamin k2',
    concentration: '20ml drops',
    price: 37.5,
    matchKeywords: ['fedesaforol', 'فيديسافورول', 'vitamin d3', 'vitamin k2', 'drops', 'نقط', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 + K2 نقط لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 2,
    maxWeight: 250,
    calculationRule: D3_GENERAL_DOSING_RULE,
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين.'],
  },

  // 274
  {
    id: 'marnys-royal-provite-5000-10-oral-bottles-mvs5',
    name: 'marnys royal provite 5000 - 10 oral bottles',
    genericName: 'royal jelly & bee pollen & bee propolis & vitamin e',
    concentration: '10 oral bottles',
    price: 550,
    matchKeywords: ['marnys royal provite 5000', 'marnys', 'رويال بروفايت', 'royal jelly', 'bee pollen', 'propolis', 'vitamin e', '#multi_vitamins'],
    usage: 'مكمل للطاقة ودعم المناعة (منتجات نحل + فيتامين E).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Ampoules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('زجاجة/أمبول فموي واحد يومياً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية شديدة لمن لديهم حساسية من منتجات النحل.'],
  },

  // 275
  {
    id: 'redcelcare-20-fc-tabs-mvs5',
    name: 'redcelcare 20 f.c. tabs.',
    genericName: 'folic acid & vitamin b12',
    concentration: '20 F.C. tabs',
    price: 70,
    matchKeywords: ['redcelcare', 'ريدسيل كير', 'folic acid', 'vitamin b12', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'فوليك + B12 لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة ٢٠ يوم.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 276
  {
    id: 'vitronal-20-caps-mvs5',
    name: 'vitronal 20 caps',
    genericName: 'ferrous glycinate & vitamin c & folate & vitamin b12',
    concentration: '20 caps',
    price: 110,
    matchKeywords: ['vitronal', 'فيترونال', 'ferrous glycinate', 'iron', 'vitamin c', 'folate', 'b12', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد جليسينات مع فيتامينات لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 277
  {
    id: 'carnitozala-for-men-30-hard-gelatin-caps-mvs5',
    name: 'carnitozala for men 30 hard gelatin capsules',
    genericName: 'l- carnitine & l-arginine & coenzyme q_10 & n_ acetyle',
    concentration: '30 caps',
    price: 585,
    matchKeywords: ['carnitozala for men', 'carnitozala men', 'كارنيتوزالا رجال', 'carnitine', 'arginine', 'coq10', 'fertility', 'خصوبة', '#multi_vitamins'],
    usage: 'دعم خصوبة الرجال والطاقة (كارنيتين + أرجينين + CoQ10 ...).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 278
  {
    id: 'carnitozala-for-women-30-hard-gelatin-caps-mvs5',
    name: 'carnitozala for women 30 hard gelatin capsules',
    genericName: 'myo_inositol & vitamin c & coq10 & alpha lipoic acid & d_',
    concentration: '30 caps',
    price: 585,
    matchKeywords: ['carnitozala for women', 'carnitozala women', 'كارنيتوزالا سيدات', 'myo inositol', 'vitamin c', 'coq10', 'alpha lipoic acid', 'pcos', 'تكيس', '#multi_vitamins'],
    usage: 'دعم الطاقة/الخصوبة للسيدات (ميو-إينوزيتول + مضادات أكسدة).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 279
  {
    id: 'minvitros-30-tablet-mvs5',
    name: 'minvitros 30 tablet',
    genericName: 'coq10 & l carnitine & lutein & alpha lipolic acid & phosphati',
    concentration: '30 tablets',
    price: 360,
    matchKeywords: ['minvitros', 'مينفيتروس', 'coq10', 'carnitine', 'lutein', 'alpha lipoic acid', 'antioxidant', 'مضاد اكسدة', '#antioxidants', '#minerals', '#multi_vitamins'],
    usage: 'مضادات أكسدة ودعم الطاقة/العين (CoQ10 + لوتين + ALA ...).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 280
  {
    id: 'galena-10-sachets-mvs5',
    name: 'galena 10 sachets',
    genericName: 'lactoferrin & iron & vitamin b 1 & vitamin b 6 & vitamin b 12',
    concentration: '10 sachets',
    price: 120,
    matchKeywords: ['galena', 'جالينا', 'lactoferrin', 'iron', 'b1', 'b6', 'b12', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'لاكتوفرّين مع حديد وفيتامينات ب لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 281
  {
    id: 'sky-omega-20-capsules-mvs5',
    name: 'sky omega 20 capsules',
    genericName: 'omega 3',
    concentration: '20 caps',
    price: 160,
    matchKeywords: ['sky omega', 'سكاى اوميجا', 'omega 3', 'fish oil', 'اوميجا ٣', '#multi_vitamins', '#omega3'],
    usage: 'أوميجا 3 لدعم القلب والمخ.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 282
  {
    id: 'memzy-30-hg-cap-mvs5',
    name: 'memzy 30 h.g cap',
    genericName: 'iron & vitamin c & cyanocobalamin',
    concentration: '30 caps',
    price: 126,
    matchKeywords: ['memzy', 'ميمزي', 'iron', 'vitamin c', 'cyanocobalamin', 'b12', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فيتامين C وB12 لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 283
  {
    id: 'iro-oley-plus-syrup-100ml-mvs5',
    name: 'iro-oley plus syrup 100 ml',
    genericName: 'iron',
    concentration: '100ml',
    price: 70,
    matchKeywords: ['iro-oley plus', 'ايرو اولي بلس', 'iron syrup', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب حديد لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 284
  {
    id: 'zelsano-120ml-syrup-mvs5',
    name: 'zelsano 120 ml syrup',
    genericName: 'ferrous bisglycinate & vitamin b6 & vitamin b12',
    concentration: '120ml',
    price: 75,
    matchKeywords: ['zelsano', 'زيلسانو', 'ferrous bisglycinate', 'b6', 'b12', 'iron syrup', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب حديد مع فيتامينات ب لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 285
  {
    id: 'prony-candy-30-pieces-mvs5',
    name: 'prony candy 30 pieces',
    genericName: 'lactoferrin & iron & vitamin b12 & folic acid & vitamin c',
    concentration: '30 pieces',
    price: 120,
    matchKeywords: ['prony candy', 'بروني كاندي', 'lactoferrin', 'iron', 'b12', 'folic', 'vitamin c', 'kids', 'اطفال', '#multi_vitamins', '#minerals'],
    usage: 'كاندي/مضغ لاكتوفرّين + حديد + فيتامينات لدعم الدم للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 286
  {
    id: 'vitaferrol-elixir-120ml-mvs5',
    name: 'vitaferrol elixir 120 ml',
    genericName: 'iron salts & thiamine hydrochloride (vit. b1) & ribofl',
    concentration: '120ml',
    price: 9,
    matchKeywords: ['vitaferrol', 'فيتافرول', 'elixir', 'iron', 'b1', 'riboflavin', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'إكسير حديد مع فيتامينات ب لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Solution',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 287
  {
    id: 'mextra-30-pieces-mvs5',
    name: 'mextra 30 pieces',
    genericName: 'iron & zinc & copper',
    concentration: '30 pieces',
    price: 90,
    matchKeywords: ['mextra', 'ميكسترا', 'iron', 'zinc', 'copper', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'مكمل حديد مع زنك ونحاس لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 288
  {
    id: 'skelvitrol-20-tabs-mvs5',
    name: 'skelvitrol 20 tabs',
    genericName: 'calcium & magnesium & vitamin d3 & zinc & copper &',
    concentration: '20 tabs',
    price: 100,
    matchKeywords: ['skelvitrol', 'سكلفيترول', 'calcium', 'magnesium', 'vitamin d3', 'zinc', 'copper', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'دعم العظام (كالسيوم + ماغنسيوم + D3 + زنك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 289 biotin 10000mcg 50 softgels (illegal import)
  
  // 290
  {
    id: 'blue-ox-20-tabs-mvs5',
    name: 'blue ox 20 tabs.',
    genericName: 'red ginseng & oat & wheat germ oil & l-arginine & zinc gl',
    concentration: '20 tabs',
    price: 105,
    matchKeywords: ['blue ox', 'بلو اوكس', 'ginseng', 'oat', 'wheat germ oil', 'arginine', 'zinc', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'مكمل نشاط وطاقة (جنسنج + أرجينين + زنك).',
    timing: 'مرة يومياً صباحاً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, ...ZINC_WARNINGS],
  },

  // 291
  {
    id: 'follidanza-30-film-coated-tabs-mvs5',
    name: 'follidanza 30 film coated tablets',
    genericName: 'd-chiro inositol & n-acetyl cystein & d - biotin & r-lipoic',
    concentration: '30 Film-coated Tablets',
    price: 395,
    matchKeywords: ['follidanza', 'فوليدانزا', 'd-chiro inositol', 'n-acetyl cysteine', 'biotin', 'lipoic', 'pcos', 'تكيس', '#multi_vitamins'],
    usage: 'دعم تكيس المبايض/التمثيل الغذائي (إينوزيتول + NAC + مضادات أكسدة).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 292
  {
    id: 'candy-vitamin-d3-30-pieces-mvs5',
    name: 'candy - vitmin d3 30 pieces',
    genericName: 'vitamin d3',
    concentration: '30 pieces',
    price: 59,
    matchKeywords: ['candy vitamin d3', 'vitamin d3 candy', 'فيتامين د كاندي', '#multi_vitamins', '#vitamin_d'],
    usage: 'كاندي/مضغ فيتامين D3 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: D3_GENERAL_DOSING_RULE,
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'لا تجمع مع فيتامين D آخر بجرعات عالية.'],
  },

  // 293
  {
    id: 'carogix-30-tabs-mvs5',
    name: 'carogix 30 tabs',
    genericName: 'selenium & zinc & biotin & folic acid & beta carotene & vitami',
    concentration: '30 tabs',
    price: 125,
    matchKeywords: ['carogix', 'كاروجيكس', 'selenium', 'zinc', 'biotin', 'folic', 'beta carotene', 'hair', 'شعر', '#multi_vitamins'],
    usage: 'مكمل للشعر والبشرة (سيلينيوم + زنك + بيوتين + فوليك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...ZINC_WARNINGS, ...GENERAL_SUPPLEMENT_WARNINGS],
  },

  // 294
  {
    id: 'dora-60-chew-pieces-mvs5',
    name: 'dora 60 chew. pieces',
    genericName: 'vitamin c & calcium & vitamin d3 & phosphorus',
    concentration: '60 pieces',
    price: 129,
    matchKeywords: ['dora 60', 'دورا', 'vitamin c', 'calcium', 'vitamin d3', 'phosphorus', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'كاندي/مضغ لدعم العظام (كالسيوم + D3 + C).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 295
  {
    id: 'librafer-liquid-120ml-syrup-mvs5',
    name: 'librafer liquid 120 ml syrup',
    genericName: 'iron & multivitamin',
    concentration: '120ml',
    price: 55,
    matchKeywords: ['librafer', 'ليبرافر', 'iron syrup', 'multivitamin', 'anemia', 'انيميا', '#iron', '#multi_vitamins'],
    usage: 'شراب حديد مع فيتامينات لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 296
  {
    id: 'osteozm-30-tabs-mvs5',
    name: 'osteozm 30 tabs',
    genericName: 'calcium carbonate & magneium hydroxide & vitami',
    concentration: '30 tabs',
    price: 160,
    matchKeywords: ['osteozm', 'اوستيوزم', 'calcium carbonate', 'magnesium hydroxide', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'دعم العظام (كالسيوم + ماغنسيوم + فيتامينات).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS],
  },

  // 297
  {
    id: 'elevit-pronatal-30-fc-tabs-mvs5',
    name: 'elevit pronatal 30 f.c. tabs.',
    genericName: 'multi vitamins',
    concentration: '30 F.C. tabs',
    price: 370,
    matchKeywords: ['elevit pronatal', 'elevit', 'ايلفيت', 'prenatal', 'pronatal', 'pregnancy', 'حمل', '#multi_vitamins'],
    usage: 'مولتي فيتامين للحمل.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'F.C. Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 600,
    minWeight: 40,
    maxWeight: 200,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 298
  {
    id: 'gram-bone-30-tab-mvs5',
    name: 'gram bone 30 tab',
    genericName: 'calcium & vitamin d3',
    concentration: '30 tabs',
    price: 99,
    matchKeywords: ['gram bone', 'جرام بون', 'calcium', 'vitamin d3', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'كالسيوم + فيتامين D3 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 299
  {
    id: 'halorange-syrup-60ml-mvs5',
    name: 'halorange syrup 60 ml',
    genericName: 'cod liver oil & ascorbic acid (vitamin c)',
    concentration: '60ml',
    price: 75,
    matchKeywords: ['halorange', 'هالورانج', 'cod liver oil', 'vitamin c', 'omega', 'اوميجا', '#multi_vitamins'],
    usage: 'زيت كبد الحوت مع فيتامين C لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 300
  {
    id: 'incan-c-30-capsules-mvs5',
    name: 'incan-c 30 capsules',
    genericName: 'vitamin c & zinc sulfate',
    concentration: '30 caps',
    price: 75,
    matchKeywords: ['incan-c', 'incan c', 'انكان سي', 'vitamin c', 'zinc sulfate', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'فيتامين C + زنك لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ٢–٤ أسابيع.'),
    warnings: ZINC_WARNINGS,
  },

  // 301
  {
    id: 'khamera-60-tabs-mvs5',
    name: 'khamera 60 tabs.',
    genericName: 'yeast',
    concentration: '60 tabs',
    price: 60,
    matchKeywords: ['khamera', 'خميرة', 'yeast', 'brewers yeast', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'خميرة (دعم التغذية والشهية في بعض الحالات).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص 1–2 يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 302
  {
    id: 'marnys-ginseng-1000mg-with-lecithin-30-caps-mvs5',
    name: 'marnys ginseng 1000 mg with lecithin 30 caps.',
    genericName: 'korean ginseng & soy lecithin',
    concentration: '30 caps',
    price: 700,
    matchKeywords: ['marnys ginseng 1000', 'marnys', 'ginseng', 'lecithin', 'soy', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'جنسنج كوري لدعم النشاط والطاقة.',
    timing: 'مرة يومياً صباحاً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'غير مناسب لحساسية الصويا (ليسيثين صويا).'],
  },

  // 303
  {
    id: 'marnys-pure-royal-jelly-10gm-mvs5',
    name: 'marnys pure royal jelly 10 gm',
    genericName: 'royal jelly',
    concentration: '10 gm',
    price: 100,
    matchKeywords: ['marnys pure royal jelly', 'marnys', 'royal jelly', 'رويال جيلي', '#multi_vitamins'],
    usage: 'رويال جيلي لدعم النشاط (منتجات نحل).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Solution',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('حسب إرشادات العبوة (عادةً مرة يومياً).'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية شديدة لمن لديهم حساسية من منتجات النحل.'],
  },

  // 304
  {
    id: 'mr-bear-plus-syrup-160ml-mvs5',
    name: 'mr. bear plus syrup 160 ml',
    genericName: 'vitamin a & vitamin d & vitamin e & vitamin c & vitamin b1 & v',
    concentration: '160ml',
    price: 145,
    matchKeywords: ['mr bear plus', 'مستر بير بلس', 'kids vitamins', 'vitamin a', 'vitamin d', 'vitamin e', 'vitamin c', '#multi_vitamins'],
    usage: 'شراب مولتي فيتامين للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 305
  {
    id: 'neurimax-6-im-amp-mvs5',
    name: 'neurimax 6 i.m. amp.',
    genericName: 'vitamin b1 & vitamin b2 & vitamin b6 & vitamin b12',
    concentration: 'IM ampoules',
    price: 60,
    matchKeywords: ['neurimax 6', 'neurimax', 'نيوريماكس', 'b1', 'b2', 'b6', 'b12', 'im amp', 'حقن', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'حقن فيتامينات ب المركبة لدعم التهاب/ألم الأعصاب (حسب التشخيص والحالة).',
    timing: 'حسب التشخيص والحالة.',
    category: Category.MULTI_VITAMINS,
    form: 'Ampoule (IV/IM)',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('أمبول بالعضل حسب البروتوكول (مثلاً يوم بعد يوم).'),
    warnings: ['يُستخدم في منشأة صحية.', 'قد يسبب ألم موضعي مكان الحقن.', 'راجع تداخلات المريض والحساسية.'],
  },

  // 306
  {
    id: 'ando-10gm-10-sachets-mvs5',
    name: 'ando 10 gm 10 sachets',
    genericName: 'lactoferrine & iron & zinc & folic acid & vitamin b1 & vita',
    concentration: '10 sachets',
    price: 120,
    matchKeywords: ['ando', 'اندو', 'lactoferrin', 'iron', 'zinc', 'folic', 'b1', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'لاكتوفرّين مع حديد وزنك وفوليك لدعم الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 307
  {
    id: 'optaderol-plus-30-cap-mvs5',
    name: 'optaderol plus 30 cap',
    genericName: 'vitamin d3 & vitamin k2',
    concentration: '30 caps',
    price: 180,
    matchKeywords: ['optaderol plus', 'اوبتاديرول بلس', 'vitamin d3', 'vitamin k2', 'bones', 'عظام', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 + K2 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين.'],
  },

  // 308
  {
    id: 'queen-2500-10-capsules-mvs5',
    name: 'queen 2500 - 10 capsules',
    genericName: 'royal jelly & ginseng & wheat germ oil',
    concentration: '10 caps',
    price: 59.25,
    matchKeywords: ['queen 2500', 'كوين ٢٥٠٠', 'royal jelly', 'ginseng', 'wheat germ oil', 'energy', 'طاقة', '#multi_vitamins'],
    usage: 'منتجات نحل + جنسنج لدعم النشاط.',
    timing: 'مرة يومياً صباحاً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية لمن لديهم حساسية من منتجات النحل.'],
  },

  // 309
  {
    id: 're-iro-30-tablets-mvs5',
    name: 're iro 30 tablets',
    genericName: 'ferrous fumarate & lactoferrin & vitamin c & folic acid & cuppe',
    concentration: '30 tabs',
    price: 130,
    matchKeywords: ['re iro', 're-iro', 'ري ايرو', 'ferrous fumarate', 'lactoferrin', 'vitamin c', 'folic', 'copper', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع لاكتوفرّين وفيتامينات لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 310
  {
    id: 'adultominita-30-tabs-mvs5',
    name: 'adultominita 30 tabs',
    genericName: 'multivitamins & minerals & antioxidants',
    concentration: '30 tabs',
    price: 140,
    matchKeywords: ['adultominita', 'ادلتومينيتا', 'multivitamins', 'minerals', 'antioxidants', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن ومضادات أكسدة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 311
  {
    id: 'rosha-30-chewable-tabs-mvs5',
    name: 'rosha 30 chewable tabs',
    genericName: 'vitamin d3 & calcium & magnesium',
    concentration: '30 chewable tabs',
    price: 70,
    matchKeywords: ['rosha', 'روشا', 'vitamin d3', 'calcium', 'magnesium', 'chewable', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'مضغ كالسيوم + ماغنسيوم + D3 لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرة يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 312
  {
    id: 'sanso-b-complex-20-caps-mvs5',
    name: 'sanso b complex 20 caps.',
    genericName: 'vitamin b12 & biotin & vitamins b1 & vitamins b2 & vitamin b6',
    concentration: '20 caps',
    price: 120,
    matchKeywords: ['sanso b complex', 'سانسو بي كومبلكس', 'b12', 'biotin', 'b1', 'b2', 'b6', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'فيتامينات ب مركبة لدعم الأعصاب والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 313
  {
    id: 'sansovit-with-iron-syrup-400gm-mvs5',
    name: 'sansovit with iron syrup 400gm',
    genericName: 'retinopalmitate & pyridoxine hydrochloride (vitamin b6) &',
    concentration: '400ml',
    price: 45.5,
    matchKeywords: ['sansovit with iron 400', 'sansovit iron 400', 'سانسوفيت حديد ٤٠٠', 'iron syrup', 'kids', 'اطفال', '#multi_vitamins', '#iron'],
    usage: 'شراب فيتامينات مع حديد للأطفال لدعم الدم والشهية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 314
  {
    id: 'super-yeast-30-tablets-mvs5',
    name: 'super yeast 30 tablets',
    genericName: "brewer's yeast",
    concentration: '30 tablets',
    price: 72,
    matchKeywords: ['super yeast', 'سوبر ييست', 'brewers yeast', 'yeast', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'خميرة بيرة لدعم التغذية والشهية.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص 1–2 يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 315
  {
    id: 'copad-4000-30-caps-mvs5',
    name: 'copad 4000 30 caps',
    genericName: 'vitamin d3 & vitamin k',
    concentration: '30 caps',
    price: 141,
    matchKeywords: ['copad 4000', 'كوباد ٤٠٠٠', 'vitamin d3', 'vitamin k', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 مع فيتامين K لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K قد يتداخل مع الوارفارين.'],
  },

  // 316
  {
    id: 'mb-steel-20-hard-gelatin-caps-mvs5',
    name: 'mb-steel 20 hard gelatin capsules',
    genericName: 'iron & vitamin c & vitamin b3 & vitamin b6 & vitamin b1 & vit',
    concentration: '20 caps',
    price: 120,
    matchKeywords: ['mb-steel', 'mb steel', 'ام بي ستيل', 'iron', 'vitamin c', 'b1', 'b3', 'b6', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فيتامينات لدعم علاج أنيميا نقص الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 317
  {
    id: 'decanerve-30-caps-mvs5',
    name: 'decanerve 30 caps.',
    genericName: 'vitamin b1 & vitamin b2 & vitamin b3 & vitamin b5 & vit',
    concentration: '30 caps',
    price: 210,
    matchKeywords: ['decanerve', 'ديكانيرف', 'b1', 'b2', 'b3', 'b5', 'neuropathy', 'تنميل', '#multi_vitamins'],
    usage: 'فيتامينات ب لدعم الأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 318
  {
    id: 'vitabella-fortified-liquid-chocolate-200gm-mvs5',
    name: 'vitabella fortified liquid chocolate 200 gm',
    genericName: 'minerals & vitamins',
    concentration: '200 gm',
    price: 95,
    matchKeywords: ['vitabella 200', 'vitabella chocolate', 'فيتابيلا شوكولاتة', 'minerals', 'vitamins', 'kids', 'اطفال', '#multi_vitamins'],
    usage: 'شوكولاتة مُدعّمة بالفيتامينات والمعادن لدعم التغذية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Solution',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: fixed('ملعقة كبيرة مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يحتوي سكريات.'],
  },

  // 319
  {
    id: 'vitabella-fortified-liquid-chocolate-350gm-mvs5',
    name: 'vitabella fortified liquid chocolate 350 gm',
    genericName: 'minerals & vitamins',
    concentration: '350 gm',
    price: 130,
    matchKeywords: ['vitabella 350', 'vitabella chocolate', 'فيتابيلا ٣٥٠', 'minerals', 'vitamins', '#multi_vitamins'],
    usage: 'شوكولاتة مُدعّمة بالفيتامينات والمعادن لدعم التغذية.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Solution',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: fixed('ملعقة كبيرة مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يحتوي سكريات.'],
  },

  // 320
  {
    id: 'vitorols-30-tablets-mvs5',
    name: 'vitorols 30 tablets',
    genericName: 'natural calcium & phosphorus & magnesium & zinc & boron & v',
    concentration: '30 tabs',
    price: 99,
    matchKeywords: ['vitorols', 'فيتورولز', 'calcium', 'phosphorus', 'magnesium', 'zinc', 'boron', 'bones', 'عظام', '#multi_vitamins'],
    usage: 'مكمل معادن لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...MAGNESIUM_WARNINGS, ...ZINC_WARNINGS],
  },

  // 321
  {
    id: 'talito-zinc-30-capsules-mvs5',
    name: 'talito zinc 30 capsules',
    genericName: 'lactoferrin & zinc amino acid & chelate iron iii glycinate & asc',
    concentration: '30 caps',
    price: 360,
    matchKeywords: ['talito zinc', 'تاليتو زنك', 'lactoferrin', 'zinc', 'iron glycinate', 'vitamin c', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'لاكتوفرّين مع زنك (وقد يحتوي حديد/فيتامين C) لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...ZINC_WARNINGS, ...IRON_SUPPLEMENT_WARNINGS],
  },

  // 322
  {
    id: 'phlegomez-120ml-syrup-mvs5',
    name: 'phlegomez 120 ml syrup',
    genericName: 'omega 3',
    concentration: '120ml',
    price: 85,
    matchKeywords: ['phlegomez', 'فليجوميز', 'omega 3 syrup', 'fish oil', '#multi_vitamins', '#omega3'],
    usage: 'شراب أوميجا 3 لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: OMEGA_WARNINGS,
  },

  // 323
  {
    id: 'axica-20-pills-mvs5',
    name: 'axica 20 pills',
    genericName: 'calcium & magnesium & lactoferrin & zinc & vitamin c &',
    concentration: '20 pills',
    price: 90,
    matchKeywords: ['axica', 'اكسـيكا', 'calcium', 'magnesium', 'lactoferrin', 'zinc', 'vitamin c', '#multi_vitamins'],
    usage: 'مكمل معادن/مناعة (كالسيوم + ماغنسيوم + لاكتوفرّين + زنك + C).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...ZINC_WARNINGS, ...MAGNESIUM_WARNINGS, ...BONE_SUPPORT_WARNINGS],
  },

  // 324
  {
    id: 'bloton-30-pieces-mvs5',
    name: 'bloton 30 pieces',
    genericName: 'iron & folic acid & vitamin c & zinc & copper',
    concentration: '30 pieces',
    price: 95,
    matchKeywords: ['bloton', 'بلوتون', 'iron', 'folic', 'vitamin c', 'zinc', 'copper', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'مكمل لدعم الدم (حديد + فوليك + C + زنك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 325
  {
    id: 'covi-100mg-14-sachets-mvs5',
    name: 'covi 100 mg 14 sachets',
    genericName: 'lactoferrin & vitamin b complex',
    concentration: '14 sachets',
    price: 125,
    matchKeywords: ['covi 100', 'covi', 'كوفي', 'lactoferrin', 'b complex', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'لاكتوفرّين مع فيتامينات ب لدعم المناعة والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },
];

