import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
  'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين A أو D بجرعات عالية.',
  'جرعات فيتامين A/D الزائدة قد تسبب أعراض تسمم (غثيان/صداع/إمساك/عطش شديد).',
];

const IRON_SUPPLEMENT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
  'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
  'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const OMEGA_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'يُستخدم بحذر مع أدوية السيولة أو اضطرابات النزف.',
  'قد يسبب تجشؤ بطعم السمك/اضطراب معدة؛ يؤخذ مع الطعام.',
];

const HERBAL_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'أوقف الاستخدام إذا ظهرت حساسية (طفح/حكة/تورم).',
];

export const VITAMINS_SUPPLEMENTS: Medication[] = [
  // ==========================================
  // multivitamins + supplements 1
  // ==========================================

  // 1
  {
    id: 'elbavit-syrup-60ml-mvs1',
    name: 'elbavit syrup 60 ml',
    genericName: 'vitamin a (retinol palmitate) & vitamin d3 (cholecalciferol) & vitamin e',
    concentration: '60ml',
    price: 39,
    matchKeywords: [
      'elbavit',
      'elbavit syrup',
      'البيفيت',
      'فيتامين اطفال',
      'vitamin a',
      'vitamin d3',
      'vitamin e',
      'مناعة',
      'نمو',
      'لين عظام',
      'rickets',
      'appetite',
      '#multi_vitamins',
    ],
    usage: 'مكمل فيتامينات (A + D3 + E) لدعم النمو والعظام والمناعة للأطفال.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 5,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 2
  {
    id: 'elbavit-with-iron-syrup-60ml-mvs1',
    name: 'elbavit with iron syrup 60 ml',
    genericName: 'calcium gluconate & calcium phospholactate & dexpanthenol',
    concentration: '60ml',
    price: 40,
    matchKeywords: [
      'elbavit with iron',
      'elbavit iron',
      'البيفيت حديد',
      'calcium',
      'dexpanthenol',
      'فاتح شهية',
      'weakness',
      'نقاهة',
      '#multi_vitamins',
      '#calcium',
    ],
    usage: 'مكمل لدعم الشهية والنمو (كالسيوم + ديكسبانثينول).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 5,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'افصل ساعتين عن مكملات الحديد أو الزنك لتحسين الامتصاص.'],
  },

  // 3
  {
    id: 'limitless-milga-max-30-tabs-mvs1',
    name: 'limitless milga max 30 tabs.',
    genericName: 'vitamin b6 & vitamin b12 & benfotiamine & magnesium & mecobalamin',
    concentration: '30 tabs',
    price: 248,
    matchKeywords: [
      'limitless milga max',
      'milga max',
      'ميلجا ماكس',
      'benfotiamine',
      'mecobalamin',
      'methylcobalamin',
      'vitamin b12',
      'neuropathy',
      'اعتلال اعصاب',
      'تنميل',
      'sciatica',
      '#multi_vitamins',
      '#vitamin_b',
    ],
    usage: 'دعم الأعصاب في حالات التنميل/اعتلال الأعصاب (مجموعة فيتامين ب + بنفوتيامين + ماغنسيوم).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الغداء لمدة ٤–٨ أسابيع.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يغيّر لون البول للأصفر الفاقع (طبيعي مع فيتامينات ب).'],
  },

  // 4
  {
    id: 'royal-jelly-600mg-12-caps-mvs1',
    name: 'royal jelly 600mg 12 cap',
    genericName: 'royal jelly',
    concentration: '600mg',
    price: 44,
    matchKeywords: ['royal jelly 600', 'royal jelly', 'رويال جيلي', 'غذاء ملكات', 'fatigue', 'ارهاق', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مكمل غذاء ملكات النحل لدعم الطاقة والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsule',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية شديدة لدى بعض الأشخاص (خصوصاً حساسية منتجات النحل/الربو).'],
  },

  // 5
  {
    id: 'vitamount-men-15-sg-caps-mvs1',
    name: 'vitamount for men 15 s.g. caps.',
    genericName: 'vitamin a (retinol palmitate) & ascorbic acid (vitamin c) & vitamin d3',
    concentration: '15 caps',
    price: 90,
    matchKeywords: ['vitamount men', 'vitamount for men', 'فيتاماونت رجال', 'vitamin c', 'vitamin d3', 'men multivitamin', 'طاقة', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مكمل متعدد للرجال لدعم المناعة والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 6
  {
    id: 'vitamount-women-15-sg-caps-mvs1',
    name: 'vitamount for women 15 s.g. caps',
    genericName: 'vitamin a (retinol palmitate) & ascorbic acid (vitamin c) & vitamin d3',
    concentration: '15 caps',
    price: 120,
    matchKeywords: ['vitamount women', 'vitamount for women', 'فيتاماونت سيدات', 'women multivitamin', 'immunity', 'مناعة', 'fatigue', 'ارهاق', '#multi_vitamins'],
    usage: 'مكمل متعدد للسيدات لدعم المناعة والحيوية.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 7
  {
    id: 'royal-jelly-1000mg-12-caps-mvs1',
    name: 'royal jelly 1000mg 12 caps',
    genericName: 'royal jelly',
    concentration: '1000mg',
    price: 88,
    matchKeywords: ['royal jelly 1000', 'royal jelly', 'غذاء ملكات', 'رويال جيلي ١٠٠٠', 'energy', 'طاقة', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'غذاء ملكات النحل بتركيز أعلى لدعم الطاقة والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية شديدة لدى بعض الأشخاص (خصوصاً حساسية منتجات النحل/الربو).'],
  },

  // 8
  {
    id: 'yeast-mepaco-60-tabs-mvs1',
    name: 'yeast mepaco 60 tabs',
    genericName: 'yeast',
    concentration: '60 tabs',
    price: 60,
    matchKeywords: ['yeast mepaco', 'mepaco yeast', 'خميرة', 'حب الشباب', 'acne', 'hair', 'سقوط الشعر', 'weight gain', 'زيادة الوزن', '#multi_vitamins'],
    usage: 'خميرة (مصدر لفيتامينات ب) لدعم البشرة والشعر وفتح الشهية.',
    timing: 'مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('٢ قرص بعد الأكل مرتين يومياً.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب غازات/انتفاخ في بداية الاستخدام.'],
  },

  // 9
  {
    id: 'mag-whites-30-tabs-mvs1',
    name: 'mag whites 30 tabs',
    genericName: 'magnesium glycinate',
    concentration: '30 tabs',
    price: 125,
    matchKeywords: ['mag whites', 'magnesium glycinate', 'ماغنسيوم', 'cramps', 'تقلصات', 'sleep', 'نوم', 'anxiety', 'قلق', '#multi_vitamins', '#magnesium'],
    usage: 'ماغنسيوم جلايسينات لتقلصات العضلات/الإجهاد وتحسين جودة النوم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مساءً بعد العشاء. عند التقلصات الشديدة: قرص صباحاً وقرص مساءً.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى (خطر تراكم الماغنسيوم).'],
  },

  // 10
  {
    id: 'growth-formula-wg-400g-powder-mvs1',
    name: 'growth formula wg 400 gram pd.',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & sodium',
    concentration: '400g',
    price: 245,
    matchKeywords: ['growth formula wg', 'weight gain', 'زيادة الوزن', 'thinness', 'نحافة', 'protein', 'بروتين', 'malnutrition', 'سوء تغذية', '#dietary_supplements'],
    usage: 'مكمل عالي السعرات لزيادة الوزن ودعم التغذية (بروتين + كربوهيدرات).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('٢ ملعقة كبيرة ممتلئة (≈ ٢٥ جم) تُذاب في ٢٠٠ مل لبن/ماء مرة يومياً. يمكن زيادتها إلى مرتين يومياً.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى السكري (يحتوي سكريات).', 'غير مناسب لمن لديهم حساسية بروتين اللبن/اللاكتوز.'],
  },

  // 11
  {
    id: 'antox-30-tabs-mvs1',
    name: 'antox 30 tabs',
    genericName: 'selenium & ascorbic acid (vitamin c) & vitamin a (retinol palmitate)',
    concentration: '30 tabs',
    price: 120,
    matchKeywords: ['antox', 'selenium', 'vitamin c', 'vitamin a', 'antioxidant', 'مضاد اكسدة', 'مناعة', 'immunity', '#multi_vitamins'],
    usage: 'مضاد أكسدة (سيلينيوم + فيتامين C + فيتامين A) لدعم المناعة وصحة الجلد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة شهر.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 12
  {
    id: 'aqua-b-30-tabs-mvs1',
    name: 'aqua b 30 tabs',
    genericName: 'methylecobalamine & vitamin b6 & methyle folate',
    concentration: '30 tabs',
    price: 105,
    matchKeywords: ['aqua b', 'methylcobalamin', 'mecobalamin', 'vitamin b6', 'methylfolate', 'folate', 'اعتلال اعصاب', 'تنميل', 'b12', '#multi_vitamins', '#vitamin_b'],
    usage: 'دعم الأعصاب وتكوين الدم (ميثيل كوبالامين + ب6 + ميثيل فولات).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 13
  {
    id: 'centrum-with-lutein-30-tabs-mvs1',
    name: 'centrum with lutein 30 tabs.',
    genericName: 'dibasic calcium phosphate & vitamin k1 & copper & iron & manganese',
    concentration: '30 tabs',
    price: 265,
    matchKeywords: ['centrum lutein', 'centrum with lutein', 'سنتروم', 'lutein', 'multivitamin', 'فيتامينات', 'minerals', 'معادن', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مولتي فيتامين + معادن لدعم الطاقة والمناعة مع لوتين لدعم العين.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً مع وجبة رئيسية.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يفصل ساعتين عن مكملات الحديد/الكالسيوم الإضافية لتجنب التداخل.'],
  },

  // 14
  {
    id: 'hi-potency-formula-30-tabs-mvs1',
    name: 'hi-potency formula 30 tabs.',
    genericName: 'biotin & vitamin b12, cyanocobalamin & pantothonic acid & choline bitartrate',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['hi potency formula', 'biotin', 'choline', 'pantothenic', 'hair', 'سقوط الشعر', 'nails', 'اظافر', 'skin', 'بشرة', '#multi_vitamins'],
    usage: 'دعم الشعر/الأظافر والطاقة (بيوتين + فيتامينات ب + كولين).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة ٢–٣ شهور.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 15
  {
    id: 'kerovit-15-sg-caps-mvs1',
    name: 'kerovit 15 soft gelatin caps.',
    genericName: 'vitamins',
    concentration: '15 caps',
    price: 150,
    matchKeywords: ['kerovit', 'كروفِت', 'hair', 'سقوط الشعر', 'nails', 'اظافر', 'skin', 'بشرة', 'multivitamin', '#multi_vitamins'],
    usage: 'مكمل لدعم الشعر والبشرة والأظافر.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 16
  {
    id: 'kidzona-omega-oral-drops-30ml-mvs1',
    name: 'kidzona omega oral drops 30 ml',
    genericName: 'fish oil & vitamin d3 & vitamin b complex',
    concentration: '30ml',
    price: 135,
    matchKeywords: ['kidzona omega', 'kidzona', 'كيدزونا', 'omega', 'fish oil', 'dha', 'epa', 'vitamin d3', 'مناعة', 'تركيز', 'memory', 'brain', '#multi_vitamins', '#omega3'],
    usage: 'أوميجا ٣ للأطفال مع فيتامين D3 ومجموعة فيتامين ب لدعم المخ والتركيز.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 6,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٠.٥ مل مرة يومياً';
      if (ageMonths < 72) return '١ مل مرة يومياً';
      return '٢ مل مرة يومياً';
    },
    warnings: OMEGA_WARNINGS,
  },

  // 17
  {
    id: 'perfectil-original-30-tabs-mvs1',
    name: 'perfectil original 30 tabs.',
    genericName: 'vitamin d3 & vitamin e & vitamin c & vitamin b1 & vitamin b2',
    concentration: '30 tabs',
    price: 300,
    matchKeywords: ['perfectil', 'perfectil original', 'برفكتيل', 'hair fall', 'تساقط الشعر', 'skin', 'بشرة', 'nails', 'اظافر', 'multivitamin', '#multi_vitamins', '#hair_fall'],
    usage: 'مولتي فيتامين مخصص لدعم الشعر والبشرة والأظافر.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً مع الوجبة الرئيسية.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 18
  {
    id: 'unovit-syrup-120ml-mvs1',
    name: 'unovit syrup 120 ml',
    genericName: 'royal jelly & honey',
    concentration: '120ml',
    price: 90,
    matchKeywords: ['unovit', 'unovit syrup', 'يونوفِت', 'honey', 'عسل', 'royal jelly', 'غذاء ملكات', 'appetite', 'فاتح شهية', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مقوٍ عام للأطفال (عسل + غذاء ملكات) لتحسين الشهية والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية لدى من لديهم حساسية منتجات النحل.'],
  },

  // 19
  {
    id: 'vitastress-20-fc-tabs-mvs1',
    name: 'vitastress 20 f.c. tabs.',
    genericName: 'zinc & pyridoxine & pantothonic acid & cupper & vitamin b12, cyanocobalamin',
    concentration: '20 tabs',
    price: 64,
    matchKeywords: ['vitastress', 'فيتاسترس', 'stress', 'توتر', 'fatigue', 'ارهاق', 'zinc', 'زنك', 'hair', 'سقوط الشعر', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'لدعم الطاقة وتقليل الإجهاد مع الزنك وفيتامينات ب.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الغداء لمدة ٤–٨ أسابيع.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 20
  {
    id: 'vitifect-syrup-120ml-mvs1',
    name: 'vitifect syrup 120 ml',
    genericName: 'dexapanthenol & calcium gluconate & calcium & vitamins',
    concentration: '120ml',
    price: 36,
    matchKeywords: ['vitifect', 'vitifect syrup', 'فيتيفكت', 'calcium', 'dexpanthenol', 'نمو', 'فاتح شهية', 'kids', 'اطفال', '#multi_vitamins', '#calcium'],
    usage: 'مكمل للأطفال (كالسيوم + فيتامينات) لدعم النمو والشهية.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 5,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 21
  {
    id: 'yeast-pex-60-tabs-mvs1',
    name: 'yeast pex 60 tabs.',
    genericName: 'yeast extract',
    concentration: '60 tabs',
    price: 40,
    matchKeywords: ['yeast pex', 'pex yeast', 'خميرة بيكس', 'yeast extract', 'فاتح شهية', 'weight gain', 'زيادة الوزن', 'hair', 'سقوط الشعر', '#multi_vitamins'],
    usage: 'خميرة/Yeast extract لدعم الشهية والطاقة وفيتامينات ب.',
    timing: 'مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص إلى ٢ قرص بعد الأكل مرتين يومياً.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب انتفاخ/غازات في بداية الاستخدام.'],
  },

  // 22
  {
    id: 'vitayami-30-fc-tabs-mvs1',
    name: 'vitayami 30 f.c. tabs',
    genericName: 'beta-carotene & vitamin a (retinol palmitate) & vitamin e & vitamin c',
    concentration: '30 tabs',
    price: 135,
    matchKeywords: ['vitayami', 'فيتايامي', 'beta carotene', 'vitamin a', 'vitamin c', 'vitamin e', 'antioxidant', 'مضاد اكسدة', 'skin', 'بشرة', '#multi_vitamins', '#vitamins', '#minerals'],
    usage: 'مضادات أكسدة لدعم المناعة وصحة الجلد (A + C + E + بيتا كاروتين).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة شهرين.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 23
  {
    id: 'limitless-conceive-q-30-chew-tabs-mvs1',
    name: 'limitless conceive q 30 chew. tabs.',
    genericName: 'myo-inositol & d-chiro-inositol & methyl folate & co q10 & alpha lactalbumin',
    concentration: '30 chew tabs',
    price: 395,
    matchKeywords: ['limitless conceive q', 'conceive q', 'كونسيف كيو', 'myo-inositol', 'd-chiro-inositol', 'pcos', 'تكيس المبايض', 'fertility', 'خصوبة', 'ovulation', 'تبويض', 'coq10', 'methylfolate', '#multi_vitamins'],
    usage: 'دعم الخصوبة وتنظيم الإباضة خاصةً مع تكيس المبايض (Inositol + Methylfolate + CoQ10).',
    timing: 'مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرتين يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب انتفاخ/اضطراب معدة بسيط في البداية.'],
  },

  // 24
  {
    id: 'whitnino-oral-drops-30ml-mvs1',
    name: 'whitnino 30 ml oral drops',
    genericName: 'ferrous bisglycinate & vitamin c & folic acid & vitamin b12',
    concentration: '30ml',
    price: 59,
    matchKeywords: ['whitnino', 'ويتنينو', 'iron drops', 'ferrous bisglycinate', 'anemia', 'انيميا', 'فقر دم', 'folic acid', 'b12', 'pallor', 'شحوب', '#multi_vitamins', '#iron'],
    usage: 'نقط حديد مع فوليك وب١٢ لدعم تكوين الدم وعلاج نقص الحديد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 6,
    maxAgeMonths: 1200,
    minWeight: 6,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٠.٥ مل مرة يومياً';
      if (ageMonths < 144) return '١ مل مرة يومياً';
      return '١ مل مرة يومياً (يمكن زيادتها إلى ٢ مل يومياً عند الاحتياج).';
    },
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 25
  {
    id: 'brestto-20-chew-tabs-mvs1',
    name: 'brestto 20 pieces chew. tabs.',
    genericName: 'fenugreek & fennel & dill & caraway & chamomile & anise & vitamins',
    concentration: '20 pieces',
    price: 160,
    matchKeywords: ['brestto', 'بريستو', 'lactation', 'إدرار اللبن', 'fenugreek', 'حلبة', 'fennel', 'شمر', 'anise', 'يانسون', 'gas', 'غازات', '#multi_vitamins'],
    usage: 'مكمل عشبي لدعم إدرار اللبن وتقليل المغص/الغازات.',
    timing: '٣ مرات يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('٢ قطعة قابلة للمضغ ٣ مرات يومياً بعد الأكل.'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية لدى من لديهم حساسية الحلبة/البقوليات.'],
  },

  // 26
  {
    id: 'zadoglobin-20-caps-mvs1',
    name: 'zadoglobin 20 caps',
    genericName: 'iron & folic acid & vitamin c & vitamin b6 & vitamin b12',
    concentration: '20 caps',
    price: 135,
    matchKeywords: ['zadoglobin', 'زادوجلوبين', 'iron', 'حديد', 'folic', 'فوليك', 'b12', 'anemia', 'انيميا', 'pregnancy anemia', 'فقر دم حمل', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد مع فوليك وفيتامينات لدعم تكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الغداء.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 27
  {
    id: 'jerry-vit-children-gummy-20-pcs-mvs1',
    name: 'jerry vit children gummy multivitamin 20 pieces',
    genericName: 'vitamin a & vitamin b & vitamin c & vitamin d & vitamin e',
    concentration: '20 gummies',
    price: 69,
    matchKeywords: ['jerry vit', 'جيري فيت', 'gummy vitamin', 'multivitamin kids', 'فيتامين اطفال', 'appetite', 'فاتح شهية', 'growth', 'نمو', '#multi_vitamins'],
    usage: 'فيتامينات للأطفال على هيئة gummies لدعم النمو والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 48) return 'قطعة واحدة يومياً';
      return 'قطعتان يومياً';
    },
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 28
  {
    id: 'sideral-folic-20-caps-mvs1',
    name: 'sideral folic 20 capsules',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12 & vitamin d3',
    concentration: '20 caps',
    price: 235,
    matchKeywords: ['sideral folic', 'سيدرال فوليك', 'iron', 'ferric', 'anemia', 'انيميا', 'pregnancy', 'حمل', 'folic', 'فوليك', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فوليك وفيتامينات لدعم تكوين الدم، مناسب لمن يعانون من تهيج المعدة مع الحديد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 29
  {
    id: 'sideral-active-15-orodispersible-sticks-mvs1',
    name: 'sideral active 15 orodispersible sticks',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12',
    concentration: '15 sticks',
    price: 150,
    matchKeywords: ['sideral active', 'سيدرال اكتيف', 'orodispersible sticks', 'iron sticks', 'anemia', 'انيميا', 'iron', 'حديد', '#multi_vitamins', '#iron'],
    usage: 'حديد على هيئة sticks سريعة الذوبان لدعم تكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('Stick واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 30
  {
    id: 'vinax-30-tabs-mvs1',
    name: 'vinax 30 tab',
    genericName: 'iron & zinc & vitamin c & vitamin b & liposomal iron with lactoferrin',
    concentration: '30 tabs',
    price: 150,
    matchKeywords: ['vinax', 'فينكس', 'liposomal iron', 'lactoferrin', 'iron', 'زنك', 'zinc', 'انيميا', 'anemia', 'fatigue', 'ارهاق', '#multi_vitamins', '#iron'],
    usage: 'حديد مع لاكتوفرّين وزنك لدعم المناعة ورفع مخزون الحديد.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 31
  {
    id: 'newtone-30-chew-tabs-mvs1',
    name: 'newtone 30 chew. tabs.',
    genericName: 'vitamin a & vitamin e & vitamin d & vitamin e & vitamin k & vitamin c',
    concentration: '30 chew tabs',
    price: 75,
    matchKeywords: ['newtone', 'نيوتون', 'chewable', 'multivitamin', 'فيتامينات', 'minerals', 'معادن', '#multi_vitamins', '#minerals'],
    usage: 'مولتي فيتامين قابل للمضغ لدعم المناعة والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 32
  {
    id: 'xerodox-30-sublingual-tabs-mvs1',
    name: 'xerodox 30 sublingual tabs.',
    genericName: 'vitamin b12 & vitamin b6 & folic acid',
    concentration: '30 tabs',
    price: 105,
    matchKeywords: ['xerodox', 'زيرودوكس', 'sublingual b12', 'b12', 'folic', 'تنميل', 'neuropathy', 'anemia', 'انيميا', '#multi_vitamins', '#vitamin_b'],
    usage: 'فيتامين ب12 + ب6 + فوليك لدعم الأعصاب وتكوين الدم (تحت اللسان).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 33
  {
    id: 'sansovit-plus-syrup-320ml-mvs1',
    name: 'sansovit plus syrup 320 ml',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vitamin b6',
    concentration: '320ml',
    price: 210,
    matchKeywords: ['sansovit plus', 'سانسوفيت', 'sansovit syrup', 'kids vitamin', 'فيتامين اطفال', 'appetite', 'فاتح شهية', 'growth', 'نمو', 'vitamin d3', '#multi_vitamins'],
    usage: 'فيتامينات للأطفال لدعم النمو والشهية (A + D3 + مجموعة ب).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 34
  {
    id: 'choletrix-d3-1000iu-oral-drops-30ml-mvs1',
    name: 'choletrix-d3 1000 iu oral drops 30ml',
    genericName: 'cholecalciferol',
    concentration: '1000 IU/ml',
    price: 87,
    matchKeywords: ['choletrix d3', 'choletrix', 'كوليتركس', 'vitamin d3', 'd3 drops', 'فيتامين د', 'bones', 'عظام', 'immunity', 'مناعة', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 نقط لدعم العظام والمناعة (جرعة يومية).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 2,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 12) return '٠.٤ مل يومياً (≈ ٤٠٠ وحدة)';
      if (ageMonths < 216) return '٠.٦ مل يومياً (≈ ٦٠٠ وحدة)';
      return '١ مل يومياً (١٠٠٠ وحدة)';
    },
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'لا تجمع مع مكملات D أخرى بجرعات عالية لتجنب ارتفاع الكالسيوم.'],
  },

  // 35
  {
    id: 'triocobavit-30-caps-mvs1',
    name: 'triocobavit 30 caps.',
    genericName: 'cyanocobolamin & pyridoxine & thiamine',
    concentration: '30 caps',
    price: 105,
    matchKeywords: ['triocobavit', 'تريوكوبافيت', 'b1', 'b6', 'b12', 'neuropathy', 'تنميل', 'اعصاب', '#multi_vitamins', '#vitamin_b'],
    usage: 'مجموعة فيتامين ب لدعم الأعصاب (B1 + B6 + B12).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 36
  {
    id: 'centrum-silver-with-lutein-30-tabs-mvs1',
    name: 'centrum silver with lutein 30 tabs.',
    genericName: 'multivitamins & minerals',
    concentration: '30 tabs',
    price: 290,
    matchKeywords: ['centrum silver', 'centrum silver lutein', 'سنتروم سيلفر', 'senior multivitamin', 'كبار السن', 'lutein', 'eye', 'عين', '#multi_vitamins'],
    usage: 'مولتي فيتامين ومعادن لكبار السن مع لوتين لدعم العين والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً مع وجبة رئيسية.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 37
  {
    id: 'ginso-plus-20-caps-mvs1',
    name: 'ginso plus 20 caps',
    genericName: 'ginkgo biloba & ginseng',
    concentration: '20 caps',
    price: 110,
    matchKeywords: ['ginso plus', 'جينسو بلس', 'ginkgo', 'ginseng', 'memory', 'ذاكرة', 'concentration', 'تركيز', 'circulation', 'دورة دموية', '#multi_vitamins'],
    usage: 'مكمل لدعم التركيز والدورة الدموية الطرفية (جينكو + جينسنغ).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة صباحاً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع أدوية السيولة/الأسبرين (قد يزيد النزف).', 'قد يسبب أرق/خفقان لدى بعض الأشخاص.'],
  },

  // 38
  {
    id: 'immuno-mash-kids-syrup-100ml-mvs1',
    name: 'immuno-mash kids syrup 100 ml',
    genericName: 'multivitamins',
    concentration: '100ml',
    price: 80,
    matchKeywords: ['immuno-mash', 'immunomash', 'ايمونو ماش', 'kids syrup', 'مناعة اطفال', 'vitamins', 'فيتامينات', 'appetite', 'فاتح شهية', '#multi_vitamins'],
    usage: 'فيتامينات للأطفال لدعم المناعة والنشاط.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 39
  {
    id: 'ronja-syrup-100ml-mvs1',
    name: 'ronja syrup 100 ml',
    genericName: 'iron & lysine & vitamin c & vitamin b complex & minerals',
    concentration: '100ml',
    price: 60,
    matchKeywords: ['ronja syrup', 'ronja', 'رونجا', 'iron syrup', 'حديد شراب', 'lysine', 'فاتح شهية', 'anemia', 'انيميا', 'weakness', 'خمول', '#multi_vitamins', '#iron'],
    usage: 'شراب حديد مع ليسين وفيتامينات لدعم الشهية وتكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 40
  {
    id: 'sansovit-plus-syrup-160ml-mvs1',
    name: 'sansovit plus syrup 160 ml',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vitamin b6',
    concentration: '160ml',
    price: 125,
    matchKeywords: ['sansovit plus 160', 'sansovit', 'سانسوفيت ١٦٠', 'kids vitamin', 'فيتامين اطفال', 'appetite', 'فاتح شهية', 'growth', 'نمو', '#multi_vitamins'],
    usage: 'فيتامينات للأطفال لدعم النمو والشهية (A + D3 + مجموعة ب).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 41
  {
    id: 'umega-kids-oral-drops-30ml-mvs1',
    name: 'umega kids drops 30 ml',
    genericName: 'omega-3 & vitamin d3 & vitamin e',
    concentration: '30ml',
    price: 95,
    matchKeywords: ['umega kids', 'umega drops', 'يو ميجا', 'omega 3', 'vitamin d3', 'vitamin e', 'memory', 'تركيز', 'مناعة', '#multi_vitamins', '#omega3'],
    usage: 'أوميجا ٣ للأطفال مع فيتامين D3 و E لدعم المخ والمناعة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 6,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٠.٥ مل مرة يومياً';
      if (ageMonths < 72) return '١ مل مرة يومياً';
      return '٢ مل مرة يومياً';
    },
    warnings: OMEGA_WARNINGS,
  },

  // 42
  {
    id: 'jenonal-compound-30-tab-mvs1',
    name: 'jenonal compound 30 tab',
    genericName: 'alpha-lipoic acid & vitamin b complex & vitamin c',
    concentration: '30 tabs',
    price: 112.5,
    matchKeywords: ['jenonal compound', 'jenonal', 'جينونال', 'alpha lipoic acid', 'ala', 'neuropathy', 'اعتلال اعصاب', 'diabetic neuropathy', 'التهاب اعصاب السكر', 'antioxidant', '#dietary_supplements'],
    usage: 'دعم الأعصاب كمضاد أكسدة (Alpha-lipoic acid) مع فيتامينات.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 43
  {
    id: 'growth-formula-pregnant-woman-10-sachet-choc-mvs1',
    name: 'growth formula pregnant woman 10 sachet - chocolate',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & sodium',
    concentration: '10 sachets',
    price: 179.5,
    matchKeywords: ['growth formula pregnant', 'pregnant woman', 'حامل', 'pregnancy nutrition', 'تغذية الحمل', 'protein', 'بروتين', '#dietary_supplements'],
    usage: 'مكمل تغذية للحمل لدعم السعرات والبروتين عند ضعف الشهية.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠ مل لبن/ماء بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع السكري (قد يحتوي سكريات).'],
  },

  // 44
  {
    id: 'topro-10-sachets-mvs1',
    name: 'topro 10 sachets',
    genericName: 'chicory inulin & lactobacillus & zinc',
    concentration: '10 sachets',
    price: 130,
    matchKeywords: ['topro', 'توبرو', 'inulin', 'lactobacillus', 'probiotic', 'بروبيوتك', 'colon', 'قولون', 'diarrhea', 'اسهال', '#dietary_supplements'],
    usage: 'بروبيوتك + إنولين لدعم الهضم والقولون مع الزنك.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ماء/عصير فاتر.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 45
  {
    id: 'anise-isis-12-sachets-mvs1',
    name: 'anise isis 12 sachets',
    genericName: 'anise',
    concentration: '12 sachets',
    price: 17.5,
    matchKeywords: ['anise isis', 'isis anise', 'يانسون', 'مغص', 'غازات', 'bloating', 'colic', '#herbal_supplements'],
    usage: 'يانسون للمغص والغازات.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يُنقع في ماء دافئ ويُشرب مرة إلى مرتين يومياً.'),
    warnings: HERBAL_WARNINGS,
  },

  // 46
  {
    id: 'growth-formula-kids-400g-powder-banana-mvs1',
    name: 'growth formula for kids 400 gm pd. - banana',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose & sodium',
    concentration: '400g',
    price: 249.5,
    matchKeywords: ['growth formula kids', 'growth formula banana', 'نحافة اطفال', 'underweight child', 'malnutrition', 'سوء تغذية', 'protein', 'بروتين', '#dietary_supplements'],
    usage: 'مكمل تغذية للأطفال لزيادة الوزن ودعم السعرات.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: fixed('٢ ملعقة كبيرة ممتلئة (≈ ٢٥ جم) تُذاب في ٢٠٠ مل لبن مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.', 'يُستخدم بحذر مع السكري (قد يحتوي سكريات).'],
  },

  // 47
  {
    id: 'hanzo-10-sachets-mvs1',
    name: 'hanzo 10 sachets',
    genericName: 'niacin & vitamin b6 & vitamin b12 & vitamin b2 & lycin & zinc & carnitin',
    concentration: '10 sachets',
    price: 170,
    matchKeywords: ['hanzo', 'هانزو', 'niacin', 'carnitine', 'zinc', 'energy', 'طاقة', 'fatigue', 'ارهاق', '#dietary_supplements'],
    usage: 'مكمل لدعم الطاقة والإجهاد مع فيتامينات ب وزنك وكارنيتين.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'النياسين قد يسبب احمرار/سخونة مؤقتة (flushing).'],
  },

  // 48
  {
    id: 'jenonal-compound-20-tab-mvs1',
    name: 'jenonal compound 20 tab',
    genericName: 'alpha-lipoic acid & vitamin b complex & vitamin c',
    concentration: '20 tabs',
    price: 106,
    matchKeywords: ['jenonal compound 20', 'jenonal', 'جينونال ٢٠', 'alpha lipoic acid', 'neuropathy', 'اعتلال اعصاب', '#dietary_supplements'],
    usage: 'دعم الأعصاب كمضاد أكسدة (Alpha-lipoic acid) مع فيتامينات.',
    timing: 'مرة واحدة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 49
  {
    id: 'manew-30-tabs-mvs1',
    name: 'manew 30 tabs',
    genericName: 'calcium & vitamin d & vitamin c & vitamin k',
    concentration: '30 tabs',
    price: 120,
    matchKeywords: ['manew', 'مانيو', 'calcium', 'vitamin d', 'vitamin k', 'bones', 'عظام', 'osteoporosis', 'هشاشة', '#multi_vitamins', '#calcium'],
    usage: 'دعم العظام (كالسيوم + فيتامين د + فيتامين ك).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.'],
  },

  // 50
  {
    id: 'kashkids-syrup-120ml-mvs1',
    name: 'kashkids 120 ml syrup',
    genericName: 'multivitamins',
    concentration: '120ml',
    price: 89,
    matchKeywords: ['kashkids', 'كاش كيدز', 'kids vitamins', 'فيتامين اطفال', 'appetite', 'فاتح شهية', 'growth', 'نمو', '#multi_vitamins'],
    usage: 'فيتامينات للأطفال لدعم النمو والنشاط.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٢.٥ مل مرة يومياً';
      if (ageMonths < 72) return '٥ مل مرة يومياً';
      return '١٠ مل مرة يومياً';
    },
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 51
  {
    id: 'carnivita-advance-men-30-sachets-mvs1',
    name: 'carnivita advance men 30 sachets',
    genericName: 'l-carnitine & vitamin c & vitamin b',
    concentration: '30 sachets',
    price: 395,
    matchKeywords: ['carnivita advance men', 'carnivita', 'كارنيفِتا', 'l-carnitine', 'fat burning', 'حرق الدهون', 'energy', 'طاقة', 'workout', 'تمارين', '#multi_vitamins'],
    usage: 'كارنيتين لدعم الطاقة والأداء مع فيتامينات.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً صباحاً أو قبل التمرين بساعة.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 52
  {
    id: 'centrum-with-lutein-100-tabs-mvs1',
    name: 'centrum with lutein 100 tabs.',
    genericName: 'dibasic calcium phosphate & vitamin k1 & copper & iron & manganese',
    concentration: '100 tabs',
    price: 710,
    matchKeywords: ['centrum lutein 100', 'centrum with lutein 100', 'سنتروم ١٠٠', 'multivitamin', 'minerals', 'lutein', '#multi_vitamins'],
    usage: 'مولتي فيتامين + معادن لدعم الطاقة والمناعة مع لوتين لدعم العين.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً مع وجبة رئيسية.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 53
  {
    id: 'healthy-bc-30-tab-mvs1',
    name: 'healthy bc 30 tab',
    genericName: 'vitamin b complex & folic acid',
    concentration: '30 tabs',
    price: 135,
    matchKeywords: ['healthy bc', 'healthy b complex', 'فيتامين ب مركب', 'b complex', 'folic acid', 'ارهاق', 'fatigue', 'neuropathy', 'اعصاب', '#multi_vitamins', '#vitamin_b'],
    usage: 'مجموعة فيتامين ب مع فوليك لدعم الأعصاب والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الإفطار.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 54
  {
    id: 'sideral-folic-20-orodispersible-sticks-mvs1',
    name: 'sideral folic 20 orodispersible sticks',
    genericName: 'iron & vitamin c & vitamin b6 & folic acid & vitamin b12 & vitamin d3',
    concentration: '20 sticks',
    price: 220,
    matchKeywords: ['sideral folic sticks', 'sideral folic 20 sticks', 'سيدرال فوليك ستيكس', 'iron sticks', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع فوليك وفيتامينات على هيئة sticks سريعة الذوبان.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('Stick واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 55
  {
    id: 'tristarshow-syrup-200ml-mvs1',
    name: 'tristarshow 200 ml syrup',
    genericName: 'dha & epa & omega3 & lipid soluble vitamin & a lipid soluble form of vitamin c',
    concentration: '200ml',
    price: 199,
    matchKeywords: ['tristarshow', 'تريستارشوو', 'omega3 syrup', 'dha', 'epa', 'omega', 'memory', 'تركيز', 'kids omega', '#omega3', '#multi_vitamins'],
    usage: 'شراب أوميجا ٣ (DHA/EPA) لدعم المخ والتركيز.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 144) return '٥ مل يومياً بعد الأكل';
      return '١٠ مل يومياً بعد الأكل';
    },
    warnings: OMEGA_WARNINGS,
  },

  // 56
  {
    id: 'limitless-osteodense-original-30-tabs-mvs1',
    name: 'limitless osteodense original 30 tabs',
    genericName: 'calcium & vitamin d3 & vitamin k2 & zinc & boron & copper & magnesium',
    concentration: '30 tabs',
    price: 145,
    matchKeywords: ['limitless osteodense', 'osteodense', 'اوستودينس', 'calcium', 'vitamin d3', 'k2', 'bones', 'عظام', 'osteoporosis', 'هشاشة', '#multi_vitamins'],
    usage: 'مكمل دعم العظام (كالسيوم + D3 + K2 + معادن).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.'],
  },

  // 57
  {
    id: 'zincomez-syrup-120ml-mvs1',
    name: 'zincomez 120 ml syrup',
    genericName: 'zinc sulphate',
    concentration: '120ml',
    price: 75,
    matchKeywords: ['zincomez', 'زينكوميز', 'zinc syrup', 'زنك شراب', 'immunity', 'مناعة', 'hair', 'سقوط الشعر', 'diarrhea', 'اسهال', '#multi_vitamins', '#zinc'],
    usage: 'شراب زنك لدعم المناعة وقد يفيد في حالات الإسهال/تساقط الشعر.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: fixed('٥ مل مرة يومياً بعد الأكل لمدة ٢–٤ أسابيع.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب غثيان إذا أُخذ على معدة فارغة.'],
  },

  // 58
  {
    id: 'khamera-marvel-30-tabs-mvs1',
    name: 'khamera 30 tabs. marvel',
    genericName: 'yeast',
    concentration: '30 tabs',
    price: 40,
    matchKeywords: ['khamera', 'خميرة', 'مارفيل خميرة', 'yeast', 'appetite', 'فاتح شهية', 'hair', 'سقوط الشعر', '#multi_vitamins'],
    usage: 'خميرة لدعم الشهية والبشرة والشعر.',
    timing: 'مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص إلى ٢ قرص بعد الأكل مرتين يومياً.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'قد يسبب انتفاخ/غازات في بداية الاستخدام.'],
  },

  // 59
  {
    id: 'kaveda-oral-drops-30ml-mvs1',
    name: 'kaveda oral drops 30ml',
    genericName: 'iron & vitamins',
    concentration: '30ml',
    price: 65,
    matchKeywords: ['kaveda', 'كافيدا', 'iron drops', 'حديد نقط', 'anemia', 'انيميا', 'ferritin', 'مخزون الحديد', '#multi_vitamins', '#iron'],
    usage: 'نقط حديد مع فيتامينات لدعم تكوين الدم للأطفال.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 6,
    maxWeight: 50,
    calculationRule: (_w, ageMonths) => {
      if (ageMonths < 24) return '٠.٥ مل مرة يومياً';
      if (ageMonths < 72) return '١ مل مرة يومياً';
      return '١.٥ مل مرة يومياً';
    },
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 60
  {
    id: 'totavit-20-tabs-mvs1',
    name: 'totavit 20 tabs.',
    genericName: 'multivitamins & iron & manganese & copper & chromium & iodine',
    concentration: '20 tabs',
    price: 87,
    matchKeywords: ['totavit', 'توتافيت', 'multivitamin iron', 'iron', 'anemia', 'انيميا', 'fatigue', 'ارهاق', '#multi_vitamins', '#iron'],
    usage: 'مولتي فيتامين ومعادن مع حديد لدعم الطاقة وتكوين الدم.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 61
  {
    id: 'umega-d-20-caps-mvs1',
    name: 'umega d 20 caps.',
    genericName: 'fish oil & vitamin d3',
    concentration: '20 caps',
    price: 155,
    matchKeywords: ['umega d', 'يو ميجا دي', 'fish oil', 'omega 3', 'vitamin d3', 'bone', 'عظام', 'immunity', 'مناعة', '#multi_vitamins', '#omega3'],
    usage: 'أوميجا ٣ مع فيتامين D3 لدعم القلب والمناعة والعظام.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً مع وجبة.'),
    warnings: OMEGA_WARNINGS,
  },

  // 62
  {
    id: 'vitatron-20-caps-mvs1',
    name: 'vitatron 20 caps',
    genericName: 'riboflavin (vitamin b2) & thiamine (vitamin b1) & vitamin a (retinol palmitate)',
    concentration: '20 caps',
    price: 130,
    matchKeywords: ['vitatron', 'فيتاترون', 'b1', 'b2', 'vitamin a', 'energy', 'طاقة', 'fatigue', 'ارهاق', '#multi_vitamins'],
    usage: 'فيتامينات لدعم الطاقة والشهية (B1 + B2 + A).',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 63
  {
    id: 'foji-30-tabs-mvs1',
    name: 'foji 30 tabs',
    genericName: 'folic acid & vitamin b12 & vitamin b6',
    concentration: '30 tabs',
    price: 105,
    matchKeywords: ['foji', 'فوجي', 'folic acid', 'فوليك', 'b12', 'b6', 'pregnancy', 'حمل', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'فوليك + ب12 + ب6 لدعم تكوين الدم والأعصاب.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 64
  {
    id: 'mixora-20-caps-mvs1',
    name: 'mixora 20 caps',
    genericName: 'vitamin b & vitamin c & vitamin d & vitamin e & vitamin k & zinc',
    concentration: '20 caps',
    price: 120,
    matchKeywords: ['mixora', 'ميكسورا', 'multivitamin', 'zinc', 'vitamin d', 'vitamin c', 'vitamin e', 'immunity', 'مناعة', 'fatigue', 'ارهاق', '#multi_vitamins'],
    usage: 'مولتي فيتامين مع زنك لدعم المناعة والطاقة.',
    timing: 'مرة واحدة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },
];

