import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_SUPPLEMENT_WARNINGS = [
  'لا تتجاوز الجرعة اليومية الموصى بها.',
  'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
  'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: اطلب استشارة طبية قبل الاستخدام.',
];

const FAT_SOLUBLE_VIT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'تجنب الجمع مع مكملات أخرى تحتوي على فيتامين A أو D أو E أو K بجرعات عالية.',
  'الجرعات الزائدة من فيتامينات A/D/E/K قد تسبب أعراض تسمم أو اضطرابات نزف.',
];

const IRON_SUPPLEMENT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إمساك/غثيان ويغير لون البراز للأسود (طبيعي).',
  'افصل عن الشاي/القهوة/الألبان ومضادات الحموضة ساعتين لتحسين الامتصاص.',
  'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const OMEGA_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'يُستخدم بحذر مع أدوية السيولة أو اضطرابات النزف.',
  'قد يسبب تجشؤ بطعم السمك/اضطراب معدة؛ يؤخذ مع الطعام.',
];

const ZINC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن المضادات الحيوية (تتراسيكلين/كينولون) لتجنب تقليل الامتصاص.',
];

const HERBAL_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'أوقف الاستخدام إذا ظهرت حساسية (طفح/حكة/تورم).',
];

const BONE_SUPPORT_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'افصل ساعتين عن مكملات الحديد لتحسين الامتصاص.',
  'يُستخدم بحذر مع حصوات الكلى أو ارتفاع الكالسيوم.',
];

const PROBIOTIC_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'إذا لديك نقص مناعة شديد أو تستخدم علاج كيماوي/كورتيزون عالي الجرعة: استخدم بحذر.',
];

const MAGNESIUM_WARNINGS = [
  ...GENERAL_SUPPLEMENT_WARNINGS,
  'قد يسبب إسهال/مغص خاصة مع الجرعات العالية.',
  'يُستخدم بحذر مع مرضى الكلى.',
];

const D3_GENERAL_DOSING_RULE = (_w: number, ageMonths: number) => {
  if (ageMonths < 12) return '٤٠٠ وحدة دولية يومياً';
  if (ageMonths < 216) return '٦٠٠ وحدة دولية يومياً';
  return '١٠٠٠ وحدة دولية يومياً';
};

export const MULTIVITAMINS_SUPPLEMENTS_4: Medication[] = [
  // ==========================================
  // multivitamins + supplements 4
  // Items: 195 → 259
  // ==========================================

  // 195
  {
    id: 'royal-provite-5000-20-oral-ampoules-mvs4',
    name: 'royal provite 5000 - 20 oral ampoules',
    genericName: 'royal jelly & bee pollen & bee propolis & vitamin e',
    concentration: '20 oral ampoules',
    price: 700,
    matchKeywords: ['royal provite', 'رويال بروفايت', 'royal jelly', 'bee pollen', 'propolis', 'vitamin e', 'energy', 'طاقة', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مكمل للطاقة ودعم المناعة (منتجات نحل + فيتامين E).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Ampoules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('أمبول فموي واحد يومياً بعد الإفطار.'),
    warnings: [...HERBAL_WARNINGS, 'قد يسبب حساسية شديدة لمن لديهم حساسية من منتجات النحل.'],
  },

  // 196
  {
    id: 'sanso-c-plus-14-tabs-mvs4',
    name: 'sanso c plus 14 tabs',
    genericName: 'zinc & vitamin c & vitamin d3 & vitamin e & vitamin a',
    concentration: '14 tabs',
    price: 95,
    matchKeywords: ['sanso c plus 14', 'sanso c plus', 'سانسو سي بلس', 'vitamin c', 'zinc', 'vitamin d3', 'vitamin e', 'vitamin a', 'immunity', 'مناعة', 'cold', 'برد', '#multi_vitamins'],
    usage: 'مكمل مناعي (C + زنك + A/D/E).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة ١٤ يوم.'),
    warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 197
  {
    id: 'sanso-c-plus-28-tabs-mvs4',
    name: 'sanso c plus 28 tabs',
    genericName: 'zinc & vitamin c & vitamin d3 & vitamin e & vitamin a',
    concentration: '28 tabs',
    price: 190,
    matchKeywords: ['sanso c plus 28', 'sanso c plus', 'سانسو سي بلس ٢٨', 'vitamin c', 'zinc', 'vitamin d3', 'vitamin e', 'vitamin a', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مكمل مناعي (C + زنك + A/D/E).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة ٢٨ يوم.'),
    warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 198
  {
    id: 'sansocal-d-30-chew-tabs-mvs4',
    name: 'sansocal-d 30 chew. tabs.',
    genericName: 'calcium & vitamin d3 & magnesium & zinc & copper',
    concentration: '30 chew tabs',
    price: 70,
    matchKeywords: ['sansocal-d', 'sansocal d', 'سانسوكال د', 'calcium', 'vitamin d3', 'magnesium', 'zinc', 'copper', 'bones', 'عظام', '#calcium', '#multi_vitamins'],
    usage: 'دعم العظام (كالسيوم + D3 + ماغنسيوم + زنك + نحاس).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص قابل للمضغ مرة يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 199
  {
    id: 'sansovit-with-iron-syrup-600gm-mvs4',
    name: 'sansovit with iron syrup 600gm',
    genericName: 'retinopalmitate & pyridoxine hydrochloride (vitamin b6)',
    concentration: '600ml',
    price: 55.5,
    matchKeywords: ['sansovit with iron 600', 'sansovit iron 600', 'سانسوفيت حديد ٦٠٠', 'iron syrup', 'appetite', 'فاتح شهية', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'شراب فيتامينات مع دعم للدم والشهية للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 200
  {
    id: 'selenium-ace-30-tabs-mvs4',
    name: 'selenium-ace 30 tabs',
    genericName: 'vitamin a (retinyl acetate) & vitamin e & ascorbic acid (vitamin c)',
    concentration: '30 tabs',
    price: 130,
    matchKeywords: ['selenium-ace', 'selenium ace', 'سيلينيوم ايه سي اي', 'vitamin a', 'vitamin c', 'vitamin e', 'antioxidant', 'مضاد اكسدة', '#multi_vitamins'],
    usage: 'مضادات أكسدة (A + C + E).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 201
  {
    id: 'bioworld-cal-syrup-120ml-mvs4',
    name: 'bioworld cal syrup 120 ml',
    genericName: 'calcium & magnesium & vitamin d3 & zinc',
    concentration: '120ml',
    price: 59,
    matchKeywords: ['bioworld cal', 'بيوورلد كال', 'calcium syrup', 'magnesium', 'vitamin d3', 'zinc', 'bones', 'عظام', 'growth', 'نمو', '#multi_vitamins', '#calcium'],
    usage: 'شراب معادن وفيتامين D3 للأطفال لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 202
  {
    id: 'luxoferol-20-soft-gelatin-cap-mvs4',
    name: 'luxoferol 20 soft gelatin cap',
    genericName: 'vitamin d3 & fish oil',
    concentration: '20 softgels',
    price: 165,
    matchKeywords: ['luxoferol', 'لوكسوفيرول', 'vitamin d3', 'fish oil', 'omega', 'اوميجا', 'bones', 'عظام', '#multi_vitamins', '#omega3', '#vitamin_d'],
    usage: 'فيتامين D3 مع زيت السمك لدعم العظام والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 203
  {
    id: 'santevita-120ml-syrup-mvs4',
    name: 'santevita 120 ml syrup',
    genericName: 'l-lysine & zinc & iron & iodine & vitamin b complex & vitamin a',
    concentration: '120ml',
    price: 90,
    matchKeywords: ['santevita', 'سانتيفيتا', 'lysine', 'iron', 'zinc', 'iodine', 'b complex', 'vitamin a', 'appetite', 'فاتح شهية', '#multi_vitamins', '#iron'],
    usage: 'شراب فاتح شهية مع دعم للدم والنمو (ليسين + حديد + زنك + يود + فيتامينات).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 204
  {
    id: 'triguard-30-capsules-mvs4',
    name: 'triguard 30 capsules',
    genericName: 'vitamin c & vitamin d & zinc',
    concentration: '30 caps',
    price: 60,
    matchKeywords: ['triguard', 'تريجارد', 'vitamin c', 'vitamin d', 'zinc', 'immunity', 'مناعة', '#multi_vitamins', '#immunity', '#zinc'],
    usage: 'دعم المناعة (C + D + زنك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 205
  {
    id: 'egycofer-10-sachet-mvs4',
    name: 'egycofer 10 sachet',
    genericName: 'lactoferrin & iron & vitamin c & vitamin b complex',
    concentration: '10 sachets',
    price: 130,
    matchKeywords: ['egycofer', 'ايجيكوفر', 'lactoferrin', 'iron', 'vitamin c', 'b complex', 'anemia', 'انيميا', 'immunity', 'مناعة', '#multi_vitamins', '#iron'],
    usage: 'لاكتوفرّين مع حديد وفيتامينات لدعم تكوين الدم والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 206
  {
    id: 'gelo-tron-30-chew-pieces-mvs4',
    name: 'gelo tron 30 chew. pieces',
    genericName: 'vitamin a & vitamin e & vitamin c & vitamin b12 & vitamin b5',
    concentration: '30 pieces',
    price: 69,
    matchKeywords: ['gelo tron', 'جيلو ترون', 'vitamin a', 'vitamin e', 'vitamin c', 'b12', 'b5', 'antioxidant', 'مضاد اكسدة', '#multi_vitamins'],
    usage: 'مكمل فيتامينات (A + C + E + فيتامينات ب).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 207
  {
    id: 'joy-iron-30-tables-mvs4',
    name: 'joy iron 30 tables',
    genericName: 'iron & zinc & vitamin c & vitamin b complex & folic acid',
    concentration: '30 tabs',
    price: 84,
    matchKeywords: ['joy iron', 'جوي ايرون', 'iron', 'zinc', 'vitamin c', 'b complex', 'folic', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل حديد مع زنك وفيتامينات لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 208
  {
    id: 'larocinia-10g-14-sachets-mvs4',
    name: 'larocinia 10 gram 14 sachets',
    genericName: 'lactoferrin & iron & folic acid & vitamin d & zinc & vitamin c',
    concentration: '14 sachets',
    price: 112,
    matchKeywords: ['larocinia', 'لاروسينيا', 'lactoferrin', 'iron', 'folic', 'vitamin d', 'zinc', 'vitamin c', '#multi_vitamins', '#iron'],
    usage: 'لاكتوفرّين مع حديد وفوليك وفيتامينات لدعم الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 209
  {
    id: 'lopro-iron-adult-14-sachets-mvs4',
    name: 'lopro iron adult 14 sachets',
    genericName: 'iron & lactoferrin & colostrum & vitamin b & vitamin c complex',
    concentration: '14 sachets',
    price: 175,
    matchKeywords: ['lopro iron adult', 'lopro iron', 'لو برو ايرون', 'iron', 'lactoferrin', 'colostrum', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد للبالغين مع لاكتوفرّين وكولوستروم لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن.'],
  },

  // 210
  {
    id: 'marligum-20-chewing-gummies-omega-3-mvs4',
    name: 'marligum 20 chewing gummies omega 3',
    genericName: 'omega 3 & vitamin d & vitamin c',
    concentration: '20 gummies',
    price: 50,
    matchKeywords: ['marligum 20', 'marligum', 'مارليجم', 'omega 3 gummies', 'vitamin d', 'vitamin c', 'kids', 'اطفال', '#multi_vitamins', '#omega_3'],
    usage: 'جُمّي أوميجا 3 مع فيتامينات لدعم المخ والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? 'قطعة واحدة يومياً بعد الأكل' : 'قطعتان يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 211
  {
    id: 'marligum-30-chewing-gummies-omega-3-mvs4',
    name: 'marligum 30 chewing gummies omega 3',
    genericName: 'omega 3 & vitamin d & vitamin c',
    concentration: '30 gummies',
    price: 98,
    matchKeywords: ['marligum 30', 'marligum', 'مارليجم ٣٠', 'omega 3 gummies', 'vitamin d', 'vitamin c', '#multi_vitamins', '#omega_3'],
    usage: 'جُمّي أوميجا 3 مع فيتامينات لدعم المخ والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? 'قطعة واحدة يومياً بعد الأكل' : 'قطعتان يومياً بعد الأكل'),
    warnings: [...OMEGA_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS],
  },

  // 212
  {
    id: 'omegaddox-liquid-200ml-mvs4',
    name: 'omegaddox liquid 200 ml',
    genericName: 'omega-3 fish oil & vitamin c & vitamin b1 & niacin & vitamins',
    concentration: '200ml',
    price: 290,
    matchKeywords: ['omegaddox', 'اوميجادوكس', 'omega 3 liquid', 'fish oil', 'vitamin c', 'b1', 'niacin', 'focus', 'تركيز', '#multi_vitamins', '#omega3'],
    usage: 'شراب أوميجا مع فيتامينات لدعم التركيز والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: OMEGA_WARNINGS,
  },

  // 213
  {
    id: 'oridal-oral-drops-mvs4',
    name: 'oridal oral drops',
    genericName: 'vitamin d3',
    concentration: 'Oral drops',
    price: 60,
    matchKeywords: ['oridal', 'اوريدال', 'vitamin d3 drops', 'نقط فيتامين د', 'infant', 'رضع', 'rickets', 'لين عظام', '#multi_vitamins', '#vitamin_d'],
    usage: 'فيتامين D3 نقط لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 2,
    maxWeight: 250,
    calculationRule: D3_GENERAL_DOSING_RULE,
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'لا تجمع مع فيتامين D آخر بجرعات عالية.'],
  },

  // 214
  {
    id: 'revota-20-pills-mvs4',
    name: 'revota 20 pills',
    genericName: 'iron & zinc & vitamin c & vitamin b12',
    concentration: '20 pills',
    price: 90,
    matchKeywords: ['revota', 'ريفوتا', 'iron', 'zinc', 'vitamin c', 'b12', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'حديد مع زنك وفيتامينات لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 215
  {
    id: 'rovime-10-sachet-mvs4',
    name: 'rovime 10 sachet',
    genericName: 'lactoferrin & colostrum & ferrous fumarate & vitamin c',
    concentration: '10 sachets',
    price: 160,
    matchKeywords: ['rovime', 'روفايم', 'lactoferrin', 'colostrum', 'ferrous fumarate', 'iron', 'vitamin c', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'لاكتوفرّين + كولوستروم + حديد لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن.'],
  },

  // 216
  {
    id: 'centravita-methylfolate-30-caps-mvs4',
    name: 'centravita methylfolate 30 caps',
    genericName: 'methylcobalamin & 1-5-methyltetrahydrofolate',
    concentration: '30 caps',
    price: 110,
    matchKeywords: ['centravita methylfolate', 'centravita', 'سنترفيتا', 'methylfolate', 'methylcobalamin', 'b12', 'neuropathy', 'تنميل', 'pregnancy', 'حمل', '#multi_vitamins'],
    usage: 'ميثيل فولات + ميثيل كوبالامين لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 217
  {
    id: 'sanso-zinc-50mg-30-caps-mvs4',
    name: 'sanso zinc 50 mg 30 caps.',
    genericName: 'zinc',
    concentration: '50mg',
    price: 110,
    matchKeywords: ['sanso zinc 50', 'sanso zinc', 'سانسو زنك', 'zinc 50mg', 'immunity', 'مناعة', 'acne', 'حب شباب', '#multi_vitamins', '#zinc'],
    usage: 'زنك لدعم المناعة والشعر/البشرة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ٤ أسابيع.'),
    warnings: [...ZINC_WARNINGS, 'الجرعات العالية لفترات طويلة قد تقلل النحاس وتسبب أعراض نقصه.'],
  },

  // 218
  {
    id: 'selenostar-30-tabs-mvs4',
    name: 'selenostar 30 tabs.',
    genericName: 'vitamin a & vitamin e & vitamin c & selenium',
    concentration: '30 tabs',
    price: 110,
    matchKeywords: ['selenostar', 'سيلينوستار', 'selenium', 'vitamin a', 'vitamin e', 'vitamin c', 'antioxidant', 'مضاد اكسدة', '#multi_vitamins'],
    usage: 'مضادات أكسدة مع سيلينيوم لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 219
  {
    id: 'stonium-b-complex-mvs4',
    name: 'stonium b complex',
    genericName: 'vitamin b complex & folic acid & vitamin b12 & biotin',
    concentration: 'B-complex',
    price: 92,
    matchKeywords: ['stonium', 'ستونيوم', 'b complex', 'folic', 'b12', 'biotin', 'hair', 'شعر', 'neuropathy', 'تنميل', '#multi_vitamins', '#vitamin_b'],
    usage: 'فيتامينات ب مع فوليك وب١٢ وبيوتين لدعم الأعصاب والشعر.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 220
  {
    id: 'b12-sano-pharma-1mg-30-tabs-mvs4',
    name: 'b12 sano pharma 1 mg 30 tabs',
    genericName: 'vitamin b12',
    concentration: '1mg',
    price: 99,
    matchKeywords: ['b12 sano pharma', 'sano pharma b12', 'b12 1mg', 'فيتامين ب١٢', 'neuropathy', 'تنميل', 'anemia', 'انيميا', '#multi_vitamins', '#vitamin_b12'],
    usage: 'فيتامين B12 لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل لمدة ٤–٨ أسابيع.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 221
  {
    id: 'trioglobinal-30-tabs-mvs4',
    name: 'trioglobinal 30 tabs.',
    genericName: 'liposomal iron & methylfolate & lactoferrin & vitamin c & vitamins',
    concentration: '30 tabs',
    price: 225,
    matchKeywords: ['trioglobinal', 'تريوجلوبينال', 'liposomal iron', 'methylfolate', 'lactoferrin', 'vitamin c', 'anemia', 'انيميا', '#multi_vitamins', '#liposomal_iron'],
    usage: 'حديد ليبوسومال مع لاكتوفرّين وميثيل فولات لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 222
  {
    id: 'colitra-plus-30-tab-mvs4',
    name: 'colitra plus 30 tab',
    genericName: 'glucosamine & collagen & chondroitin & vitamin d & vitamins',
    concentration: '30 tabs',
    price: 345,
    matchKeywords: ['colitra plus', 'كوليترا بلس', 'glucosamine', 'collagen', 'chondroitin', 'vitamin d', 'joints', 'مفاصل', '#multi_vitamins', '#joint_support'],
    usage: 'دعم المفاصل والغضاريف مع فيتامين D.',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 223
  {
    id: 'lacunited-30-capsules-mvs4',
    name: 'lacunited 30 capsules',
    genericName: 'lactoferrin & iron & folic acid',
    concentration: '30 caps',
    price: 135,
    matchKeywords: ['lacunited', 'لاكونايتد', 'lactoferrin', 'iron', 'folic', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'لاكتوفرّين مع حديد وفوليك لدعم مخزون الحديد.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: IRON_SUPPLEMENT_WARNINGS,
  },

  // 224
  {
    id: 'calfood-d3-film-coated-30-tabs-mvs4',
    name: 'calfood d3 film coated 30tabs',
    genericName: 'calcium & magnesium & zinc & vitamin d3',
    concentration: '30 tabs',
    price: 129,
    matchKeywords: ['calfood d3', 'كال فود د٣', 'calcium', 'magnesium', 'zinc', 'vitamin d3', 'bones', 'عظام', '#multi_vitamins', '#minerals'],
    usage: 'دعم العظام (كالسيوم + ماغنسيوم + زنك + D3).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 225
  {
    id: 'agnatix-syrup-60ml-mvs4',
    name: 'agnatix syrup 60 ml',
    genericName: 'zinc sulphate',
    concentration: '60ml',
    price: 59,
    matchKeywords: ['agnatix', 'اجناتكس', 'zinc sulphate syrup', 'zinc syrup', 'diarrhea', 'اسهال', 'immunity', 'مناعة', '#multi_vitamins', '#zinc'],
    usage: 'شراب زنك لدعم المناعة وتقليل مدة الإسهال عند الأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 6,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 60 ? '٥ مل يومياً بعد الأكل لمدة ١٠ أيام' : '١٠ مل يومياً بعد الأكل لمدة ١٠ أيام'),
    warnings: ZINC_WARNINGS,
  },

  // 226
  {
    id: 'dropegen-30ml-drops-mvs4',
    name: 'dropegen 30 ml drops',
    genericName: 'vitamin b12 & folic acid & biotin & vitamin b1 & vitamins',
    concentration: '30ml',
    price: 80,
    matchKeywords: ['dropegen', 'دروبيجن', 'drops', 'نقط', 'b12', 'folic', 'biotin', 'b1', 'kids', 'اطفال', '#multi_vitamins'],
    usage: 'نقط فيتامينات ب مع فوليك وبيوتين للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Oral Drops',
    minAgeMonths: 6,
    maxAgeMonths: 144,
    minWeight: 6,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٠.٥ مل يومياً بعد الأكل' : '١ مل يومياً بعد الأكل'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 227
  {
    id: 'formamy-30-c-tabs-mvs4',
    name: 'formamy 30 c. tabs.',
    genericName: 'vitamin a & vitamin c & vitamin d3 & vitamin e & vitamin b1',
    concentration: '30 tabs',
    price: 175,
    matchKeywords: ['formamy', 'فورامي', 'vitamin a', 'vitamin c', 'vitamin d3', 'vitamin e', 'b1', 'immunity', 'مناعة', '#multi_vitamins'],
    usage: 'مولتي فيتامين لدعم المناعة والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 228
  {
    id: 'liquid-chlorophyll-120ml-mvs4',
    name: 'liquid chlorophyll 120 ml',
    genericName: 'carbohydrates & chlorophyllin & sodium & copper',
    concentration: '120ml',
    price: 250,
    matchKeywords: ['liquid chlorophyll', 'chlorophyllin', 'كلوروفيل', 'detox', 'رائحة الفم', 'odor', '#multi_vitamins'],
    usage: 'مكمل كلوروفيل سائل لدعم رائحة الفم والانتعاش.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Solution',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('٥ مل يومياً تُخفف في كوب ماء بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 229
  {
    id: 'mica-30-tab-mvs4',
    name: 'mica 30 tab',
    genericName: 'calcium & vitamin d & magnesium & vitamin k2',
    concentration: '30 tabs',
    price: 100,
    matchKeywords: ['mica 30', 'mica', 'ميكا', 'calcium', 'vitamin d', 'magnesium', 'vitamin k2', 'bones', 'عظام', '#multi_vitamins', '#calcium'],
    usage: 'دعم العظام (كالسيوم + D + ماغنسيوم + K2).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...BONE_SUPPORT_WARNINGS, ...FAT_SOLUBLE_VIT_WARNINGS, 'فيتامين K2 قد يتداخل مع الوارفارين.'],
  },

  // 230
  {
    id: 'omegalox-liquid-200ml-mvs4',
    name: 'omegalox liquid 200 ml',
    genericName: 'omega-3 fish oil & vitamin c & vitamin b1 & niacin & vitamins',
    concentration: '200ml',
    price: 690,
    matchKeywords: ['omegalox', 'اوميجالوكس', 'omega 3 liquid', 'fish oil', 'vitamin c', 'b1', 'niacin', 'focus', 'تركيز', '#multi_vitamins', '#omega3'],
    usage: 'شراب أوميجا مع فيتامينات لدعم التركيز والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 144,
    minWeight: 10,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: OMEGA_WARNINGS,
  },

  // 231
  {
    id: 'primofol-30-tab-mvs4',
    name: 'primofol 30 tab',
    genericName: 'folic acid & vitamin b12',
    concentration: '30 tabs',
    price: 129,
    matchKeywords: ['primofol', 'بريموفول', 'folic acid', 'b12', 'pregnancy', 'حمل', 'anemia', 'انيميا', '#multi_vitamins'],
    usage: 'فوليك + B12 لدعم تكوين الدم وقبل/أثناء الحمل.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 232
  {
    id: 'sansovit-calcium-syrup-160ml-mvs4',
    name: 'sansovit calcium syrup 160 ml',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vitamins',
    concentration: '160ml',
    price: 48,
    matchKeywords: ['sansovit calcium 160', 'sansovit calcium', 'سانسوفيت كالسيوم ١٦٠', 'vitamin d3', 'growth', 'نمو', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال لدعم النمو والعظام.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 233
  {
    id: 'sansovit-calcium-syrup-160ml-chocolate-mvs4',
    name: 'sansovit calcium syrup 160 ml (chocolate)',
    genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vitamins',
    concentration: '160ml',
    price: 50,
    matchKeywords: ['sansovit calcium 160 chocolate', 'sansovit chocolate', 'سانسوفيت شوكولاتة', 'kids vitamins', 'فيتامين اطفال', '#multi_vitamins'],
    usage: 'شراب فيتامينات للأطفال (نكهة شوكولاتة) لدعم النمو.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: FAT_SOLUBLE_VIT_WARNINGS,
  },

  // 234
  {
    id: 'united-vit-30-fc-tabs-mvs4',
    name: 'united vit 30 f.c. tabs.',
    genericName: 'biotin & selenium & iron & copper & zinc & pantothenic acid',
    concentration: '30 tabs',
    price: 185,
    matchKeywords: ['united vit', 'يونايتد فيت', 'biotin', 'selenium', 'iron', 'zinc', 'copper', 'hair', 'شعر', 'anemia', 'انيميا', '#multi_vitamins', '#iron'],
    usage: 'مكمل للشعر والجلد مع دعم للدم (بيوتين/سيلينيوم/حديد/زنك).',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: [...IRON_SUPPLEMENT_WARNINGS, ...ZINC_WARNINGS],
  },

  // 235
  {
    id: 'vitalox-junior-liquid-200ml-mvs4',
    name: 'vitalox junior liquid 200 ml',
    genericName: 'multivitamins & minerals',
    concentration: '200ml',
    price: 490,
    matchKeywords: ['vitalox junior', 'vitalox kids', 'فيتالوكس جونيور', 'multivitamins', 'minerals', 'kids', 'اطفال', '#multi_vitamins'],
    usage: 'شراب مولتي فيتامين ومعادن للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.MULTI_VITAMINS,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 60,
    calculationRule: (_w, ageMonths) => (ageMonths < 72 ? '٥ مل يومياً بعد الأكل' : '١٠ مل يومياً بعد الأكل'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 236
  {
    id: 'innogen-cartigen-30-caps-mvs4',
    name: 'innogen cartigen 30 caps',
    genericName: 'glucosamine hydrochloride & hydrolyzed collagen',
    concentration: '30 caps',
    price: 240,
    matchKeywords: ['innogen cartigen', 'innogen', 'كارتجين', 'glucosamine hcl', 'collagen', 'joints', 'مفاصل', '#dietary_supplements', '#joint_support'],
    usage: 'مكمل لدعم الغضاريف والمفاصل (جلوكوزامين + كولاجين).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 237
  {
    id: 'ugalko-for-men-30-sachets-mvs4',
    name: 'ugalko for men 30 sachets',
    genericName: 'l-carnitine & acetyl l-carnitine & ascorbic acid & citric acid',
    concentration: '30 sachets',
    price: 500,
    matchKeywords: ['ugalko for men', 'ugalko men', 'يوجالكو رجال', 'l-carnitine', 'acetyl l-carnitine', 'vitamin c', 'fertility', 'خصوبة', '#dietary_supplements'],
    usage: 'مكمل لدعم خصوبة الرجال والطاقة (كارنيتين).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 238
  {
    id: 'ugalko-for-women-30-sachets-mvs4',
    name: 'ugalko for women 30 sachets',
    genericName: 'l-carnitine & l-arginine & acetyl-l-carnitine & ascorbic acid',
    concentration: '30 sachets',
    price: 400,
    matchKeywords: ['ugalko for women', 'ugalko women', 'يوجالكو سيدات', 'arginine', 'carnitine', 'vitamin c', 'energy', 'طاقة', '#dietary_supplements'],
    usage: 'مكمل لدعم الطاقة والدورة الدموية (أرجينين + كارنيتين).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 239
  {
    id: 'arthojo-30-tabs-mvs4',
    name: 'arthojo 30tabs',
    genericName: 'glucosamine sulphate & methyl sulfonyl methane & rose hips',
    concentration: '30 tabs',
    price: 210,
    matchKeywords: ['arthojo', 'ارثوجو', 'glucosamine sulphate', 'msm', 'rose hips', 'joints', 'مفاصل', '#dietary_supplements', '#joint_support'],
    usage: 'مكمل للمفاصل (جلوكوزامين + MSM + روزهيبس).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 240
  {
    id: 'folifo-30-tabs-mvs4',
    name: 'folifo 30 tabs',
    genericName: 'vitamin b12 & vitamin b6 & folic acid',
    concentration: '30 tabs',
    price: 120,
    matchKeywords: ['folifo', 'فوليفو', 'b12', 'b6', 'folic acid', 'neuropathy', 'تنميل', 'anemia', 'انيميا', '#dietary_supplements'],
    usage: 'فوليك + B12 + B6 لدعم الأعصاب وتكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 241
  {
    id: 'ladenes-30-ec-tabs-mvs4',
    name: 'ladenes 30 e.c. tabs',
    genericName: 'alpha amylase',
    concentration: '30 tabs',
    price: 90,
    matchKeywords: ['ladenes', 'لادينس', 'alpha amylase', 'anti-inflammatory', 'التهاب', 'swelling', 'تورم', '#dietary_supplements'],
    usage: 'مكمل إنزيمي للمساعدة في تقليل التورم/الالتهاب في بعض الحالات.',
    timing: 'مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Enteric Coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً قبل الأكل بساعة.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 242
  {
    id: 'darkovida-30-caps-mvs4',
    name: 'darkovida 30 caps',
    genericName: 'vitamin b6 & folic acid & biotin & pantothenic acid & zinc',
    concentration: '30 caps',
    price: 297,
    matchKeywords: ['darkovida', 'داركوفيدا', 'b6', 'folic acid', 'biotin', 'pantothenic', 'zinc', 'hair', 'شعر', '#dietary_supplements', '#zinc'],
    usage: 'مكمل للشعر والأظافر (بيوتين + زنك + فيتامينات).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: ZINC_WARNINGS,
  },

  // 243
  {
    id: 'extra-general-protein-15gm-10-sachets-mvs4',
    name: 'extra general protein 15 gm 10 sachets',
    genericName: 'whey protein & lactose & chocolate flavour',
    concentration: '10 sachets',
    price: 135,
    matchKeywords: ['extra general protein', 'protein sachets', 'whey protein', 'lactose', 'chocolate', 'muscle', 'عضلات', 'weight gain', 'زيادة وزن', '#dietary_supplements'],
    usage: 'مكمل بروتين لدعم التغذية وزيادة البروتين اليومي.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً يُذاب في ٢٠٠ مل ماء/لبن بعد الأكل أو بعد التمرين.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'يُستخدم بحذر مع مرضى الكلى.'],
  },

  // 244
  {
    id: 'avobeano-10-capsules-mvs4',
    name: 'avobeano 10 capsules',
    genericName: 'avocado & soybean',
    concentration: '10 caps',
    price: 75,
    matchKeywords: ['avobeano', 'افوبيانو', 'avocado', 'soybean', 'skin', 'بشرة', 'hair', 'شعر', '#dietary_supplements'],
    usage: 'زيوت نباتية لدعم البشرة والشعر.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة جيلاتينية واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 245
  {
    id: 'kids-formula-250g-powder-mvs4',
    name: 'kids formula 250 gram powder',
    genericName: 'skimmed milk & whey protein & maltodextrine & sucrose',
    concentration: '250g',
    price: 126,
    matchKeywords: ['kids formula 250', 'kids formula', 'نحافة اطفال', 'weight gain kids', 'milk', 'whey', 'maltodextrin', '#dietary_supplements'],
    usage: 'مكمل تغذية للأطفال لزيادة الوزن ودعم السعرات.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 12,
    maxAgeMonths: 144,
    minWeight: 8,
    maxWeight: 50,
    calculationRule: fixed('٢ ملعقة كبيرة تُذاب في ٢٠٠ مل لبن مرة يومياً بعد الأكل.'),
    warnings: [...GENERAL_SUPPLEMENT_WARNINGS, 'غير مناسب لحساسية بروتين اللبن/اللاكتوز.', 'يُستخدم بحذر مع السكري (قد يحتوي سكريات).'],
  },

  // 246
  {
    id: 'lentra-10-sachets-2gm-mvs4',
    name: 'lentra 10 sachets 2 gm',
    genericName: 'lactium',
    concentration: '10 sachets',
    price: 225,
    matchKeywords: ['lentra', 'لينترا', 'lactium', 'sleep', 'نوم', 'stress', 'توتر', '#dietary_supplements'],
    usage: 'لاكتيم للمساعدة على الاسترخاء وتحسين جودة النوم.',
    timing: 'قبل النوم.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد قبل النوم بـ ٣٠–٦٠ دقيقة.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 247
  {
    id: 'chancy-30-sublingual-tabs-mvs4',
    name: 'chancy 30 sublingual tabs.',
    genericName: 'folic acid & vitamin b12',
    concentration: '30 tabs',
    price: 90,
    matchKeywords: ['chancy', 'شانسي', 'sublingual', 'تحت اللسان', 'folic acid', 'b12', 'anemia', 'انيميا', '#dietary_supplements'],
    usage: 'فوليك + B12 تحت اللسان لدعم تكوين الدم.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 248
  {
    id: 'lentra-plus-10-caps-mvs4',
    name: 'lentra plus 10 caps',
    genericName: 'lactium',
    concentration: '10 caps',
    price: 180,
    matchKeywords: ['lentra plus', 'لينترا بلس', 'lactium', 'sleep', 'نوم', 'stress', 'توتر', '#dietary_supplements'],
    usage: 'لاكتيم للمساعدة على الاسترخاء وتحسين النوم.',
    timing: 'قبل النوم.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة قبل النوم بـ ٣٠–٦٠ دقيقة.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 249
  {
    id: 'kartajo-30-tablet-mvs4',
    name: 'kartajo 30 tablet',
    genericName: 'glucosamine sulphate & chondroitin sulphate & msm',
    concentration: '30 tabs',
    price: 240,
    matchKeywords: ['kartajo', 'كارتاجو', 'glucosamine sulphate', 'chondroitin', 'msm', 'joints', 'مفاصل', '#dietary_supplements', '#joint_support'],
    usage: 'مكمل للمفاصل (جلوكوزامين + كوندرويتين + MSM).',
    timing: 'مرة إلى مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مرتين يومياً بعد الأكل لمدة ٨–١٢ أسبوعاً.'),
    warnings: [...HERBAL_WARNINGS, 'يُستخدم بحذر مع حساسية القشريات/المأكولات البحرية (جلوكوزامين).'],
  },

  // 250
  {
    id: 'egunaz-d3-10ml-oral-drops-mvs4',
    name: 'egunaz d3 10ml oral drops',
    genericName: 'vitamin d3',
    concentration: '10ml',
    price: 38,
    matchKeywords: ['egunaz d3 drops', 'egunaz d3', 'ايجوناز د٣', 'vitamin d3 drops', 'نقط فيتامين د', '#dietary_supplements', '#vitamin_d'],
    usage: 'فيتامين D3 نقط لدعم العظام.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Oral Drops',
    minAgeMonths: 0,
    maxAgeMonths: 1200,
    minWeight: 2,
    maxWeight: 250,
    calculationRule: D3_GENERAL_DOSING_RULE,
    warnings: [...FAT_SOLUBLE_VIT_WARNINGS, 'لا تجمع مع فيتامين D آخر بجرعات عالية.'],
  },

  // 251
  {
    id: 'lentra-5-sachet-2gm-mvs4',
    name: 'lentra 5 sachet 2 gm',
    genericName: 'lactium',
    concentration: '5 sachets',
    price: 39,
    matchKeywords: ['lentra 5', 'لينترا ٥', 'lactium', 'sleep', 'نوم', 'stress', 'توتر', '#dietary_supplements'],
    usage: 'لاكتيم للمساعدة على الاسترخاء وتحسين النوم.',
    timing: 'قبل النوم.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد قبل النوم بـ ٣٠–٦٠ دقيقة.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 252
  {
    id: 'livia-10-sachets-mvs4',
    name: 'livia 10 sachets',
    genericName: 'prebiotic & probiotic & lactobacillus acidophilus',
    concentration: '10 sachets',
    price: 130,
    matchKeywords: ['livia', 'ليفيا', 'probiotic', 'prebiotic', 'lactobacillus', 'diarrhea', 'اسهال', 'ibs', 'قولون', '#probiotics', '#dietary_supplements'],
    usage: 'بروبيوتك مع بريبايوتك لدعم الجهاز الهضمي وتقليل الإسهال.',
    timing: 'مرة يومياً.',
    category: Category.PROBIOTICS,
    form: 'Sachets',
    minAgeMonths: 12,
    maxAgeMonths: 1200,
    minWeight: 8,
    maxWeight: 250,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل لمدة ١٠–١٤ يوم.'),
    warnings: PROBIOTIC_WARNINGS,
  },

  // 253
  {
    id: 's-p-natural-sweet-pot-2-wheat-germ-oil-mvs4',
    name: 's.p. natural sweet pot 2 wheat germ oil',
    genericName: 'natural sweet potato & wheat germ oil',
    concentration: 'Dietary supplement',
    price: 205,
    matchKeywords: ['sweet potato', 'بطاطا', 'wheat germ oil', 'زيت جنين القمح', 'appetite', 'فاتح شهية', '#dietary_supplements'],
    usage: 'مكمل غذائي للطاقة/السعرات ودعم الشهية.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Powder',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: fixed('ملعقة كبيرة مرة يومياً تُضاف على اللبن/الزبادي بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 254
  {
    id: 'ubm-immune-375mg-30-caps-mvs4',
    name: 'ubm immune 375mg 30 caps',
    genericName: 'beta glucan',
    concentration: '375mg',
    price: 350,
    matchKeywords: ['ubm immune', 'ubm', 'beta glucan', 'مناعة', 'immunity', '#dietary_supplements'],
    usage: 'بيتا جلوكان لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل لمدة ٤ أسابيع.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 255
  {
    id: 'melatowhite-5mg-tabs-mvs4',
    name: 'melatowhite 5 mg tabs',
    genericName: 'magnesium citrate & magnesium oxide',
    concentration: '5mg',
    price: 85,
    matchKeywords: ['melatowhite', 'ميلاتووايت', 'magnesium citrate', 'magnesium oxide', 'sleep', 'نوم', 'cramps', 'تقلصات', '#dietary_supplements'],
    usage: 'مغنيسيوم لدعم الاسترخاء وتقلصات العضلات وجودة النوم.',
    timing: 'قبل النوم.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد مساءً بعد العشاء أو قبل النوم.'),
    warnings: MAGNESIUM_WARNINGS,
  },

  // 256
  {
    id: 'blinga-d-20-capsules-mvs4',
    name: 'blinga-d 20 capsules',
    genericName: 'alpha lipoic acid & vitamin b12 & benfotiamine & vitamin b6',
    concentration: '20 caps',
    price: 155,
    matchKeywords: ['blinga-d', 'blinga d', 'بلينجا د', 'alpha lipoic acid', 'benfotiamine', 'b12', 'b6', 'neuropathy', 'اعصاب السكر', '#dietary_supplements', '#vitamin_b'],
    usage: 'دعم الأعصاب الطرفية (ALA + بنفوتيامين + فيتامينات ب).',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },

  // 257
  {
    id: 'helba-mix-600mg-20-tab-mvs4',
    name: 'helba mix 600 mg 20 tab',
    genericName: 'fenugreek & fennel & dill seed & caraway',
    concentration: '20 tabs',
    price: 70,
    matchKeywords: ['helba mix 600', 'helba mix', 'حلبة ميكس', 'fenugreek', 'fennel', 'dill', 'caraway', 'appetite', 'فاتح شهية', 'gas', 'غازات', '#dietary_supplements'],
    usage: 'مكمل عشبي لفتح الشهية وتقليل الغازات.',
    timing: 'مرتين يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد بعد الأكل مرتين يومياً.'),
    warnings: HERBAL_WARNINGS,
  },

  // 258
  {
    id: 'nebravent-syrup-mvs4',
    name: 'nebravent syrup',
    genericName: 'ivy leaf extract & licorice root extract & thyme leaf extract',
    concentration: 'Syrup',
    price: 35,
    matchKeywords: ['nebravent', 'نيبرافنت', 'ivy', 'licorice', 'thyme', 'cough', 'كحة', 'phlegm', 'بلغم', '#herbal_supplements', '#cough_syrup'],
    usage: 'شراب عشبي لدعم السعال وتهدئة الشعب.',
    timing: '٣ مرات يومياً.',
    category: Category.HERBAL_COUGH,
    form: 'Syrup',
    minAgeMonths: 24,
    maxAgeMonths: 1200,
    minWeight: 10,
    maxWeight: 250,
    calculationRule: (_w, ageMonths) => (ageMonths < 144 ? '٥ مل ٣ مرات يومياً' : '١٠ مل ٣ مرات يومياً'),
    warnings: [...HERBAL_WARNINGS, 'غير مناسب للأطفال أقل من سنتين.'],
  },

  // 259
  {
    id: 'nervivox-30-sublingual-tabs-mvs4',
    name: 'nervivox 30 sublingual tabs',
    genericName: 'folic acid & vitamin b6 & vitamin b12',
    concentration: '30 tabs',
    price: 90,
    matchKeywords: ['nervivox', 'نيرفيفوكس', 'sublingual', 'تحت اللسان', 'folic acid', 'b6', 'b12', 'neuropathy', 'تنميل', '#dietary_supplements'],
    usage: 'فوليك + B6 + B12 تحت اللسان لدعم الأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.DIETARY_SUPPLEMENTS,
    form: 'Orodispersible Tablet',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد يومياً يُترك ليذوب تحت اللسان.'),
    warnings: GENERAL_SUPPLEMENT_WARNINGS,
  },
];

