
import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const OMEGA_WARNINGS = [
  'يُفضّل تناوله بعد الأكل لتقليل الارتجاع/الطعم.',
  'حساسية السمك/المأكولات البحرية: تجنب الاستخدام.',
  'مع مميعات الدم أو اضطرابات النزف: انتبه لزيادة قابلية النزف.',
];

const SYRUP_AGE_RULE_2_5_OR_5_ML = (_w: number, ageMonths: number) => (ageMonths < 24 ? '٢.٥ مل مرة يومياً بعد الأكل' : '٥ مل مرة يومياً بعد الأكل');
const SYRUP_AGE_RULE_5_OR_10_ML = (_w: number, ageMonths: number) => (ageMonths < 48 ? '٥ مل مرة يومياً بعد الأكل' : '١٠ مل مرة يومياً بعد الأكل');
const JELLY_AGE_RULE_1_OR_2_PIECES = (_w: number, ageMonths: number) => (ageMonths < 48 ? 'قطعة واحدة يومياً بعد الأكل' : 'قطعتين يومياً بعد الأكل');

export const OMEGA_GROUP: Medication[] = [
  // 1
  {
    id: 'omega-3-plus-30-caps-omega',
    name: 'omega-3 plus 30 caps.',
    genericName: 'fish oil & wheat germ oil',
    concentration: '30 capsules',
    price: 135,
    matchKeywords: ['omega-3 plus', 'omega 3 plus', 'اوميجا ٣', 'fish oil', 'wheat germ oil', '#omega3'],
    usage: 'كبسولات أوميجا-٣ (زيت سمك) مع زيت جنين القمح لدعم القلب والمخ والدهون الثلاثية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 2
  {
    id: 'omega-rx-jelly-candy-60-pcs-omega',
    name: 'omega rx jelly candy 60 pcs.',
    genericName: 'omega-3 fish oil & vitamin c & vitamin d',
    concentration: '60 jelly pieces',
    price: 250,
    matchKeywords: ['omega rx', 'omega rx jelly', 'جيلي اوميجا', 'vitamin c', 'vitamin d', 'focus', 'speech delay', '#omega3'],
    usage: 'جيلي أوميجا-٣ مع فيتامين C وD لدعم التركيز والمناعة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: JELLY_AGE_RULE_1_OR_2_PIECES,
    warnings: OMEGA_WARNINGS,
  },

  // 3
  {
    id: 'omega-zad-syrup-100-ml-omega',
    name: 'omega zad syurp 100 ml',
    genericName: 'omega-3 fish oil & evening primrose oil & vitamin e',
    concentration: '100 ml syrup',
    price: 140,
    matchKeywords: ['omega zad', 'اوميجا زاد', 'evening primrose', 'vitamin e', 'omega syrup', '#omega3'],
    usage: 'شراب أوميجا-٣ مع زيت زهرة الربيع المسائية وفيتامين هـ لدعم المخ والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 216,
    minWeight: 6,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_2_5_OR_5_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 4
  {
    id: 'zandros-20-caps-omega',
    name: 'zandros 20 caps',
    genericName: 'fish oil, omega-3 fatty acids & vitamin e',
    concentration: '20 capsules',
    price: 120,
    matchKeywords: ['zandros', 'زاندروس', 'omega-3', 'vitamin e', '#omega3'],
    usage: 'كبسولات زيت سمك (أوميجا-٣) مع فيتامين هـ لدعم القلب والأعصاب.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 5
  {
    id: 'omega-rx-jelly-candy-30-pcs-omega',
    name: 'omega rx jelly candy 30 pcs.',
    genericName: 'omega-3 fish oil & vitamin c & vitamin d',
    concentration: '30 jelly pieces',
    price: 150,
    matchKeywords: ['omega rx', 'omega rx jelly', 'جيلي اوميجا', 'vitamin c', 'vitamin d', '#omega3'],
    usage: 'جيلي أوميجا-٣ مع فيتامين C وD لدعم التركيز والمناعة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Chewable Tablets',
    minAgeMonths: 24,
    maxAgeMonths: 216,
    minWeight: 10,
    maxWeight: 80,
    calculationRule: JELLY_AGE_RULE_1_OR_2_PIECES,
    warnings: OMEGA_WARNINGS,
  },

  // 6
  {
    id: 'omedrink-syrup-60-ml-omega',
    name: 'omedrink syrup 60 ml',
    genericName: 'fish oil & omega-3 fatty acids',
    concentration: '60 ml syrup',
    price: 140,
    matchKeywords: ['omedrink', 'اوميدرينك', 'omega syrup', 'fish oil', '#omega3'],
    usage: 'شراب أوميجا-٣ (زيت سمك) للأطفال لدعم المخ والنمو.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 216,
    minWeight: 6,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_2_5_OR_5_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 7
  {
    id: 'omegal-ultra-30-capsules-omega',
    name: 'omegal ultra 30 capsules',
    genericName: 'high purified omega 3 & coenzyme q10 & selenium & z...',
    concentration: '30 capsules',
    price: 240,
    matchKeywords: ['omegal ultra', 'اوميجال الترا', 'omega 3', 'coq10', 'selenium', '#omega3'],
    usage: 'أوميجا-٣ عالي النقاء مع CoQ10 وسيلينيوم لدعم القلب والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 9
  {
    id: 'omegal-juniors-60-capsules-omega',
    name: 'omegal juniors 60 capsules',
    genericName: 'high purified omega 3 & coenzyme q10 & selenium & z...',
    concentration: '60 capsules',
    price: 360,
    matchKeywords: ['omegal juniors', 'اوميجال جونيورز', 'omega 3', '#omega3'],
    usage: 'أوميجا-٣ عالي النقاء للأطفال/المراهقين لدعم التركيز والنمو.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 96,
    maxAgeMonths: 216,
    minWeight: 20,
    maxWeight: 80,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 10
  {
    id: 'ultranyl-20-capsules-omega',
    name: 'ultranyl 20 capsules',
    genericName: 'cod liver oil',
    concentration: '20 capsules',
    price: 130,
    matchKeywords: ['ultranyl', 'الترانيل', 'cod liver oil', 'زيت كبد الحوت', '#omega3'],
    usage: 'كبسولات زيت كبد الحوت لدعم المناعة وفيتامينات أ/د الطبيعية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, 'زيت كبد الحوت غني بفيتامين A: لا تجمعه مع مصادر عالية من فيتامين A.'],
  },

  // 11
  {
    id: 'omega-3-serio-30-caps-omega',
    name: 'omega 3 serio 30 caps',
    genericName: 'fish oil',
    concentration: '30 capsules',
    price: 255,
    matchKeywords: ['omega 3 serio', 'سيريو', 'fish oil', '#omega3'],
    usage: 'كبسولات زيت سمك (أوميجا-٣) لدعم القلب والذاكرة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 12
  {
    id: 'omega-a-i-t-30-caps-omega',
    name: 'omega a.i.t. 30 cap.s',
    genericName: 'omega oil & wheat germ oil',
    concentration: '30 capsules',
    price: 135,
    matchKeywords: ['omega a.i.t', 'omega ait', 'wheat germ oil', '#omega3'],
    usage: 'كبسولات أوميجا مع زيت جنين القمح لدعم القلب والجلد.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 13
  {
    id: 'degreasian-1g-28-sg-caps-omega',
    name: 'degreasian 1 gm 28 s.g. caps.',
    genericName: 'omega-3-acid ethyl esters',
    concentration: '1 g (28 soft gelatin capsules)',
    price: 384,
    matchKeywords: ['degreasian', 'ديجريزيان', 'ethyl esters', 'triglycerides', '#omega3'],
    usage: 'أوميجا-٣ (إيستر) لدعم خفض الدهون الثلاثية ودعم القلب.',
    timing: 'مرتين يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة مرتين يومياً مع الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 14
  {
    id: 'osease-syrup-120-ml-omega',
    name: 'osease syrup 120 ml',
    genericName: 'omega 3',
    concentration: '120 ml syrup',
    price: 70,
    matchKeywords: ['osease', 'اوسيز', 'omega syrup', '#omega3'],
    usage: 'شراب أوميجا-٣ لدعم المخ والمناعة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 216,
    minWeight: 6,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_2_5_OR_5_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 15
  {
    id: 'omega-saja-30-caps-omega',
    name: 'omega-saja 30 caps.',
    genericName: 'fish oil',
    concentration: '30 capsules',
    price: 250,
    matchKeywords: ['omega-saja', 'اوميجا ساجا', 'fish oil', '#omega3'],
    usage: 'كبسولات زيت سمك (أوميجا-٣) لدعم القلب والذاكرة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 16
  {
    id: 'efalex-syrup-120-ml-omega',
    name: 'efalex syrup 120 ml',
    genericName: 'fish oil & primerose oil & thyme & vitamin e',
    concentration: '120 ml syrup',
    price: 275,
    matchKeywords: ['efalex syrup', 'ايفاليكس', 'primrose', 'thyme', 'vitamin e', '#omega3'],
    usage: 'شراب أوميجا-٣ مع زيت زهرة الربيع والزعتر وفيتامين هـ لدعم التركيز والمناعة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 216,
    minWeight: 8,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 17
  {
    id: 'omegafit-1000mg-14-sachets-omega',
    name: 'omegafit 1000 mg 14 sachets',
    genericName: 'omega-3 fish oil',
    concentration: '1000 mg (14 sachets)',
    price: 165,
    matchKeywords: ['omegafit 1000', 'omegafit', 'اوميجافيت', 'sachets', '#omega3'],
    usage: 'أكياس أوميجا-٣ (١٠٠٠ مجم) لدعم القلب والدهون الثلاثية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Sachets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 18
  {
    id: 'shark-liver-oil-500mg-20-caps-omega',
    name: 'shark liver oil 500 mg 20 caps.',
    genericName: 'shark liver oil',
    concentration: '500 mg (20 capsules)',
    price: 123,
    matchKeywords: ['shark liver oil', 'زيت كبد القرش', 'omega', '#omega3'],
    usage: 'كبسولات زيت كبد القرش لدعم المناعة والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 19
  {
    id: 'jonorest-1250mg-20-capsules-omega',
    name: 'jonorest 1250 mg 20 capsules',
    genericName: 'omega 3',
    concentration: '1250 mg (20 capsules)',
    price: 148,
    matchKeywords: ['jonorest 1250', 'جونوريست', '1250 mg', '#omega3'],
    usage: 'كبسولات أوميجا-٣ بتركيز عالي لدعم القلب والدهون الثلاثية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 20
  {
    id: 'omega-300-20-capsules-omega',
    name: 'omega-300 - 20 capsules',
    genericName: 'omega-3 fish oil',
    concentration: '20 capsules',
    price: 180,
    matchKeywords: ['omega-300', 'اوميجا ٣٠٠', 'fish oil', '#omega3'],
    usage: 'كبسولات أوميجا-٣ لدعم القلب والمخ.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 21
  {
    id: 'omegafit-500mg-14-sachets-omega',
    name: 'omegafit 500 mg 14 sachets',
    genericName: 'omega-3 fish oil',
    concentration: '500 mg (14 sachets)',
    price: 115,
    matchKeywords: ['omegafit 500', 'omegafit', 'sachets', '#omega3'],
    usage: 'أكياس أوميجا-٣ (٥٠٠ مجم) لدعم المناعة والتركيز.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Sachets',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 22
  {
    id: 'sansocod-syrup-120-ml-omega',
    name: 'sansocod syrup 120 ml',
    genericName: 'cod liver oil',
    concentration: '120 ml syrup',
    price: 24,
    matchKeywords: ['sansocod 120', 'sansocod', 'سانسوكود', 'cod liver oil', '#omega3'],
    usage: 'شراب زيت كبد الحوت لدعم المناعة والنمو.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 216,
    minWeight: 8,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: [...OMEGA_WARNINGS, 'زيت كبد الحوت غني بفيتامين A: لا تجمعه مع مصادر عالية من فيتامين A.'],
  },

  // 23
  {
    id: 'sansocod-syrup-200-ml-omega',
    name: 'sansocod syrup 200 ml',
    genericName: 'cod liver oil',
    concentration: '200 ml syrup',
    price: 120,
    matchKeywords: ['sansocod 200', 'sansocod', 'cod liver oil', '#omega3'],
    usage: 'شراب زيت كبد الحوت (عبوة كبيرة) لدعم المناعة والنمو.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 216,
    minWeight: 8,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: [...OMEGA_WARNINGS, 'زيت كبد الحوت غني بفيتامين A: لا تجمعه مع مصادر عالية من فيتامين A.'],
  },

  // 24
  {
    id: 'silver-seas-20-caps-omega',
    name: 'silver seas 20 caps',
    genericName: 'cod liver oil',
    concentration: '20 capsules',
    price: 175,
    matchKeywords: ['silver seas', 'سيلفر سيز', 'cod liver oil', '#omega3'],
    usage: 'كبسولات زيت كبد الحوت لدعم المناعة وفيتامينات أ/د.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, 'زيت كبد الحوت غني بفيتامين A: لا تجمعه مع مصادر عالية من فيتامين A.'],
  },

  // 25
  {
    id: 'super-seas-30-capsules-omega',
    name: 'super seas 30 capsules',
    genericName: 'cod liver oil',
    concentration: '30 capsules',
    price: 120,
    matchKeywords: ['super seas', 'سوبر سيز', 'cod liver oil', '#omega3'],
    usage: 'كبسولات زيت كبد الحوت لدعم المناعة والنمو.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: [...OMEGA_WARNINGS, 'زيت كبد الحوت غني بفيتامين A: لا تجمعه مع مصادر عالية من فيتامين A.'],
  },

  // 26
  {
    id: 'lovaza-30-pieces-omega',
    name: 'lovaza 30 pieces',
    genericName: 'omega 3',
    concentration: '30 capsules',
    price: 135,
    matchKeywords: ['lovaza', 'لوفازا', 'omega 3', 'triglycerides', '#omega3'],
    usage: 'أوميجا-٣ لدعم خفض الدهون الثلاثية ودعم القلب.',
    timing: 'مرتين يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولتان مرتين يومياً مع الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 27
  {
    id: 'efalex-30-caps-omega',
    name: 'efalex 30 caps.',
    genericName: 'fish oil & thyme & primerose oil & tocopherol',
    concentration: '30 capsules',
    price: 200,
    matchKeywords: ['efalex caps', 'efalex', 'ايفاليكس', 'thyme', 'primrose', 'tocopherol', '#omega3'],
    usage: 'كبسولات أوميجا-٣ مع مكونات داعمة للتركيز مثل الزعتر وزيت زهرة الربيع.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 28
  {
    id: 'centravita-trio-omega-30-caps-omega',
    name: 'centravita trio omega 30 caps',
    genericName: 'omega 3',
    concentration: '30 capsules',
    price: 195,
    matchKeywords: ['centravita trio omega', 'سنترفيتا تريو', 'omega 3', '#omega3'],
    usage: 'كبسولات أوميجا-٣ لدعم القلب والتركيز.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 29
  {
    id: 'halorange-syrup-120-ml-omega',
    name: 'halorange syrup 120 ml',
    genericName: 'cod liver oil & ascorbic acid (vitamin c)',
    concentration: '120 ml syrup',
    price: 120,
    matchKeywords: ['halorange', 'هالورانج', 'cod liver oil', 'vitamin c', '#omega3'],
    usage: 'شراب زيت كبد الحوت مع فيتامين C لدعم المناعة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 216,
    minWeight: 8,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: [...OMEGA_WARNINGS, 'زيت كبد الحوت غني بفيتامين A: لا تجمعه مع مصادر عالية من فيتامين A.'],
  },

  // 30
  {
    id: 'omega-3-safe-1250mg-60-caps-omega',
    name: 'omega 3-safe 1250 mg 60 caps.',
    genericName: 'fish oil',
    concentration: '1250 mg (60 capsules)',
    price: 250,
    matchKeywords: ['omega 3-safe', 'omega safe', '1250 mg', 'fish oil', '#omega3'],
    usage: 'أوميجا-٣ بتركيز عالي لدعم القلب والدهون الثلاثية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 31
  {
    id: 'alzad-seas-syrup-120-ml-omega',
    name: 'alzad seas syrup 120 ml',
    genericName: 'dha & epa & omega 3',
    concentration: '120 ml syrup',
    price: 130,
    matchKeywords: ['alzad seas', 'الزاد سيز', 'dha', 'epa', 'omega syrup', '#omega3'],
    usage: 'شراب أوميجا-٣ (DHA/EPA) لدعم المخ والرؤية للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 216,
    minWeight: 6,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_2_5_OR_5_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 32
  {
    id: 'omega-3-1000mg-100-softgels-now-omega',
    name: 'omega-3 - 1000 mg 100 softgels (now)',
    genericName: 'ester-omega fish oil',
    concentration: '1000 mg (100 softgels)',
    price: 1100,
    matchKeywords: ['now omega-3', 'omega-3 1000', 'softgels', 'fish oil', '#omega3'],
    usage: 'أوميجا-٣ (١٠٠٠ مجم) لدعم القلب والدهون الثلاثية.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Soft Gelatin Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('سوفت جل واحدة يومياً بعد الأكل (يمكن سوفت جل مرتين يومياً عند الحاجة).'),
    warnings: OMEGA_WARNINGS,
  },

  // 33
  {
    id: 'abc-omega-3-6-9-syrup-60-ml-omega',
    name: 'abc omega 3-6-9 syrup 60 ml',
    genericName: 'wheat germ oil',
    concentration: '60 ml syrup',
    price: 88,
    matchKeywords: ['abc omega 3-6-9', 'abc omega', 'wheat germ oil', '#omega3'],
    usage: 'شراب أوميجا 3-6-9 (مصدر زيت جنين القمح) لدعم الجلد والطاقة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 12,
    maxAgeMonths: 216,
    minWeight: 8,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 34
  {
    id: 'd3lab-syrup-120-ml-omega',
    name: 'd3lab syrup 120 ml',
    genericName: 'omega 3',
    concentration: '120 ml syrup',
    price: 150,
    matchKeywords: ['d3lab', 'دي ثري لاب', 'omega syrup', '#omega3'],
    usage: 'شراب أوميجا-٣ لدعم المخ والمناعة للأطفال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Syrup',
    minAgeMonths: 6,
    maxAgeMonths: 216,
    minWeight: 6,
    maxWeight: 80,
    calculationRule: SYRUP_AGE_RULE_2_5_OR_5_ML,
    warnings: OMEGA_WARNINGS,
  },

  // 35
  {
    id: 'omega-trifecta-30-caps-omega',
    name: 'omega trifecta 30 caps',
    genericName: 'fish oil',
    concentration: '30 capsules',
    price: 150,
    matchKeywords: ['omega trifecta', 'ترايفكتا', 'fish oil', '#omega3', '#fish_oil'],
    usage: 'كبسولات زيت سمك (أوميجا-٣) لدعم القلب والذاكرة.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 144,
    maxAgeMonths: 1200,
    minWeight: 35,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },

  // 36
  {
    id: 'omegal-man-30-cap-omega',
    name: 'omegal man 30cap',
    genericName: 'high purified omega 3 & coenzyme q10 & selenium & z...',
    concentration: '30 capsules',
    price: 495,
    matchKeywords: ['omegal man', 'اوميجال مان', 'omega 3', 'coq10', 'selenium', '#omega3'],
    usage: 'أوميجا-٣ عالي النقاء مع CoQ10 وسيلينيوم لدعم القلب والطاقة للرجال.',
    timing: 'مرة يومياً.',
    category: Category.IMMUNITY_OMEGA,
    form: 'Capsules',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 200,
    calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
    warnings: OMEGA_WARNINGS,
  },
];

