import { Medication, Category } from '../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const GENERAL_VITAMIN_WARNINGS = [
	'لا تتجاوز الجرعة اليومية الموصى بها.',
	'يُفضّل تناوله بعد الأكل لتقليل اضطراب المعدة.',
	'إن وُجد مرض مزمن/حساسية شديدة أو أدوية ثابتة: راجع الجرعة والتداخلات قبل الاستخدام.',
];

const IRON_WARNINGS = [
	...GENERAL_VITAMIN_WARNINGS,
	'يُفضل على معدة فارغة (قبل الأكل بساعة) مع فيتامين C لتحسين الامتصاص؛ إن سبب اضطراب معدة يمكن تناوله بعد الأكل.',
	'قد يسبب غثيان/إمساك ويغير لون البراز للأسود (طبيعي).',
	'افصل ساعتين عن الشاي/القهوة/الألبان ومضادات الحموضة ومكملات الكالسيوم لتحسين الامتصاص.',
	'احفظه بعيداً عن متناول الأطفال (جرعة زائدة من الحديد خطيرة).',
];

const HAIR_WARNINGS = [
	...GENERAL_VITAMIN_WARNINGS,
	'نتائج الشعر عادة تظهر خلال ٦–٨ أسابيع من الاستخدام المنتظم.',
];

const SYRUP_AGE_RULE_5_OR_10_ML = (_w: number, ageMonths: number) => (ageMonths < 144 ? '٥ مل مرة يومياً بعد الأكل' : '١٠ مل مرة يومياً بعد الأكل');

export const VITAMIN_IRON_GROUP: Medication[] = [
	// 1
	{
		id: 'ronja-capsule-30-cap-vitiron',
		name: 'ronja capsule 30 cap.',
		genericName: 'iron & vitamin b6 & vitamin b12 & folic acid & copper & zinc',
		concentration: '30 capsules',
		price: 90,
		matchKeywords: ['ronja', 'رونجا', 'iron', 'b6', 'b12', 'folic', 'copper', 'zinc', 'anemia', 'انيميا', '#iron', '#vitamin', '#minerals'],
		usage: 'كبسولات حديد + فيتامينات ب + فوليك + عناصر لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 2
	{
		id: 'sansovit-plus-syrup-100ml-vitiron',
		name: 'sansovit plus syrup 100 ml',
		genericName: 'vitamin a & vitamin d3 & vitamin b1 & vitamin b2 & vitamin b6',
		concentration: '100 ml syrup',
		price: 95,
		matchKeywords: ['sansovit plus', 'sansovit', 'سانسوفيت', 'سانسوفيت بلس', 'multivitamin syrup', 'vitamin a', 'vitamin d3', 'b complex', '#vitamin'],
		usage: 'شراب فيتامينات لدعم الشهية والنمو وتعويض النقص عند الأطفال.',
		timing: 'مرة يومياً.',
		category: Category.MULTI_VITAMINS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: GENERAL_VITAMIN_WARNINGS,
	},

	// 3
	{
		id: 'menzoflic-fc-30-tabs-vitiron',
		name: 'menzoflic f. c 30 tabs',
		genericName: 'l-arginine & l-carnitine & magnesium & vitamin c & iron',
		concentration: '30 F.C. tabs',
		price: 275,
		matchKeywords: ['menzoflic', 'مينزوفليك', 'arginine', 'carnitine', 'magnesium', 'vitamin c', 'iron', 'fertility', 'infertility', '#iron', '#vitamin', '#minerals'],
		usage: 'مكمل لدعم الطاقة والخصوبة يحتوي على أرجنين/كارنيتين/ماغنسيوم/فيتامين C مع حديد.',
		timing: 'مرة يومياً.',
		category: Category.MULTI_VITAMINS,
		form: 'F.C. Tablets',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 4
	{
		id: 'ferrohealthy-120ml-syrup-vitiron',
		name: 'ferrohealthy 120ml syrup',
		genericName: 'iron & vitamin c & folic acid & vitamin b complex',
		concentration: '120 ml syrup',
		price: 85,
		matchKeywords: ['ferrohealthy', 'فيروهيلثي', 'iron syrup', 'vitamin c', 'folic', 'b complex', 'anemia', 'انيميا', '#iron'],
		usage: 'شراب حديد مع فيتامين C وفوليك وفيتامينات ب لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: IRON_WARNINGS,
	},

	// 5
	{
		id: 'heamsmart-120ml-syrup-vitiron',
		name: 'heamsmart 120 ml syrup',
		genericName: 'liposomal iron & vitamin c & folic acid & vitamin b',
		concentration: '120 ml syrup',
		price: 100,
		matchKeywords: ['heamsmart', 'هيم سمارت', 'liposomal iron', 'iron syrup', 'vitamin c', 'folic', 'b vitamins', '#iron', '#liposomal_iron'],
		usage: 'شراب حديد ليبوسومال مع فيتامين C وفوليك وفيتامينات ب لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: IRON_WARNINGS,
	},

	// 6
	{
		id: 'vita-hair-60-tab-vitiron',
		name: 'vita hair 60 tab',
		genericName: 'ascorbic acid (vitamin c) & l-lysine & vitamin b12, cyanocobalamin',
		concentration: '60 tablets',
		price: 98,
		matchKeywords: ['vita hair', 'فيتا هير', 'hair', 'lysine', 'vitamin c', 'b12', 'cyanocobalamin', '#hair', '#vitamin'],
		usage: 'مكمل للشعر يحتوي على فيتامين C + لايسين + فيتامين B12 لدعم نمو الشعر.',
		timing: 'مرة يومياً.',
		category: Category.MULTI_VITAMINS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: HAIR_WARNINGS,
	},

	// 7
	{
		id: 'logiglobin-30-capsules-vitiron',
		name: 'logiglobin 30 capsules',
		genericName: 'iron & vitamin b12 & vitamin c & copper & folate',
		concentration: '30 capsules',
		price: 89,
		matchKeywords: ['logiglobin', 'لوجيجلوبين', 'iron', 'b12', 'vitamin c', 'copper', 'folate', 'anemia', 'انيميا', '#iron'],
		usage: 'مكمل حديد مع B12 وC ونحاس وفولات لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 8
	{
		id: 'ferreserve-120ml-syrup-vitiron',
		name: 'ferreserve 120 ml syrup',
		genericName: 'ferrous fumarate & lysine & vitamin c & zinc & vitamin b1',
		concentration: '120 ml syrup',
		price: 60,
		matchKeywords: ['ferreserve', 'فيرسيرف', 'ferrous fumarate', 'lysine', 'vitamin c', 'zinc', 'b1', 'iron syrup', '#iron', '#zinc'],
		usage: 'شراب حديد (فومارات) مع لايسين وفيتامين C وزنك لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: IRON_WARNINGS,
	},

	// 9
	{
		id: 'irocept-syrup-120ml-vitiron',
		name: 'irocept syrup 120 ml',
		genericName: 'iron & lysine & vitamin c & vitamin b1 & vitamin b6 & vit...',
		concentration: '120 ml syrup',
		price: 65,
		matchKeywords: ['irocept', 'ايروسبت', 'iron syrup', 'lysine', 'vitamin c', 'b1', 'b6', 'انيميا', '#iron'],
		usage: 'شراب حديد مع لايسين وفيتامين C وفيتامينات ب لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: IRON_WARNINGS,
	},

	// 10
	{
		id: 'mounjelly-iron-vitamin-c-60-gummies-vitiron',
		name: 'mounjelly iron & vitamin c 60 gummies',
		genericName: 'iron & vitamin c',
		concentration: '60 gummies',
		price: 250,
		matchKeywords: ['mounjelly', 'مونجيلي', 'iron gummies', 'vitamin c gummies', 'gummies', 'انيميا', '#iron', '#vitamin'],
		usage: 'جُمّي حديد مع فيتامين C لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Chewable Tablets',
		minAgeMonths: 72,
		maxAgeMonths: 1200,
		minWeight: 18,
		maxWeight: 200,
		calculationRule: fixed('حبة واحدة يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 11
	{
		id: 'molena-iron-30-tabs-vitiron',
		name: 'molena iron 30 tabs',
		genericName: 'iron & folic acid & vitamin b12 & vitamin c',
		concentration: '30 tablets',
		price: 120,
		matchKeywords: ['molena iron', 'molena', 'مولينا', 'iron', 'folic', 'b12', 'vitamin c', 'anemia', '#iron'],
		usage: 'أقراص حديد مع فوليك وB12 وC لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 12
	{
		id: 'pirove-30-pieces-vitiron',
		name: 'pirove 30 pieces',
		genericName: 'iron & folic acid & vitamin c & vitamin b complex',
		concentration: '30 pieces',
		price: 90,
		matchKeywords: ['pirove', 'بيروف', 'iron', 'folic', 'vitamin c', 'b complex', 'anemia', '#iron'],
		usage: 'مكمل حديد مع فوليك وفيتامين C وB-complex لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Chewable Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قطعة واحدة يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 13
	{
		id: 'rozone-10-sachets-vitiron',
		name: 'rozone 10 sachets',
		genericName: 'lactoferrin & vitamin b complex & iron & vitamin c & folic acid ...',
		concentration: '10 sachets',
		price: 72,
		matchKeywords: ['rozone', 'روزون', 'lactoferrin', 'iron sachets', 'vitamin c', 'folic', 'b complex', '#iron'],
		usage: 'أكياس لاكتوفرين مع حديد وفيتامينات لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Sachets',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: fixed('كيس واحد يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 14
	{
		id: 'stravita-iron-120ml-syrup-vitiron',
		name: 'stravita iron 120 ml syrup',
		genericName: 'iron & zinc & copper & magnesiea & iodine & vitamin c',
		concentration: '120 ml syrup',
		price: 45,
		matchKeywords: ['stravita iron', 'stravita', 'سترافينا', 'iron syrup', 'zinc', 'copper', 'magnesium', 'iodine', 'vitamin c', '#iron', '#zinc'],
		usage: 'شراب حديد مع عناصر متعددة وفيتامين C لدعم علاج الأنيميا.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Syrup',
		minAgeMonths: 12,
		maxAgeMonths: 1200,
		minWeight: 8,
		maxWeight: 200,
		calculationRule: SYRUP_AGE_RULE_5_OR_10_ML,
		warnings: IRON_WARNINGS,
	},

	// 15
	{
		id: 'immunace-extra-protection-30-tabs-vitiron',
		name: 'immunace extra protection 30 tabs.',
		genericName: 'vitamin a & vitamin d3 & vitamin e & vitamin k & vitami...',
		concentration: '30 tablets',
		price: 220,
		matchKeywords: ['immunace extra protection', 'immunace', 'ايميونس', 'immunity', 'vitamin a', 'vitamin d3', 'vitamin e', 'vitamin k', 'minerals', '#immunity'],
		usage: 'مولتي فيتامين ومعادن لدعم المناعة.',
		timing: 'مرة يومياً.',
		category: Category.IMMUNITY_OMEGA,
		form: 'Tablets',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('قرص واحد يومياً بعد الأكل.'),
		warnings: GENERAL_VITAMIN_WARNINGS,
	},

	// 16
	{
		id: 'tonigate-omega-30-capsules-vitiron',
		name: "tonigate omega 30 capsules",
		genericName: "dha & iron & vitamin d3 & vitamins and minerals",
		concentration: '30 capsules',
		price: 210,
		matchKeywords: ['tonigate omega', 'tonigate', 'تونيجيت', 'omega', 'dha', 'iron', 'vitamin d3', 'women', "women's health", 'pregnancy', 'حامل', '#iron', '#omega3'],
		usage: 'أوميجا (DHA) مع حديد وفيتامينات ومعادن لدعم صحة المرأة.',
		timing: 'مرة يومياً.',
		category: Category.IMMUNITY_OMEGA,
		form: 'Capsules',
		minAgeMonths: 216,
		maxAgeMonths: 1200,
		minWeight: 45,
		maxWeight: 200,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},

	// 17
	{
		id: 'blofordex-30-capsules-vitiron',
		name: 'blofordex 30 capsules',
		genericName: 'ferrous fumarate & folic acid & zinc sulphate & copper sulphate',
		concentration: '30 capsules',
		price: 90,
		matchKeywords: ['blofordex', 'بلوفوردكس', 'ferrous fumarate', 'folic acid', 'zinc', 'copper', 'iron', 'anemia', 'انيميا', '#anti-anemic', '#iron'],
		usage: 'كبسولات حديد (فومارات) مع فوليك وزنك ونحاس لدعم علاج أنيميا نقص الحديد.',
		timing: 'مرة يومياً.',
		category: Category.VITAMINS_MINERALS,
		form: 'Capsules',
		minAgeMonths: 144,
		maxAgeMonths: 1200,
		minWeight: 35,
		maxWeight: 200,
		calculationRule: fixed('كبسولة واحدة يومياً بعد الأكل.'),
		warnings: IRON_WARNINGS,
	},
];

