
import { Medication, Category } from '../../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const BASE_SEDATIVE_WARNINGS = [
  'قد يسبب نعاس/دوخة؛ تجنب القيادة والآلات إذا حدث نعاس.',
  'تجنب الكحول ومهدئات أخرى.',
  'لا تُوقِف الدواء فجأة (خصوصاً المهدئات/البنزوديازيبين).',
];

const Z_DRUG_WARNINGS = [
  ...BASE_SEDATIVE_WARNINGS,
  'قد يسبب طعم معدني/مرارة بالفم (شائع مع إيزوبيكلون).',
  'قد يسبب سلوكيات أثناء النوم (نادر)؛ أوقفه واطلب تقييمًا عاجلاً إذا حدث.',
];

const BENZO_WARNINGS = [
  ...BASE_SEDATIVE_WARNINGS,
  'قد يسبب تعود/اعتماد عند الاستخدام الطويل؛ يُستخدم عادة لأقصر مدة ممكنة.',
  'قد يزيد النعاس لدى كبار السن ويزيد خطر السقوط.',
];

const BUSPIRONE_WARNINGS = [
  'ليس منوماً سريعاً؛ قد يحتاج ١–٢ أسبوع لظهور التحسن.',
  'قد يسبب دوخة/صداع أو غثيان في البداية.',
];

const TOFISOPAM_WARNINGS = [
  'قد يسبب دوخة/صداع أو اضطراب معدة.',
  'تجنب القيادة إذا حدث دوخة.',
];

export const HYPNOTICS_SEDATIVES_DRUGS: Medication[] = [
  // 1
  {
    id: 'sleepez-3mg-30-fc-tabs-hs',
    name: 'sleepez 3 mg 30 f.c.tabs.',
    genericName: 'eszopiclone',
    concentration: '3mg',
    price: 81,
    matchKeywords: ['sleepez 3', 'sleepez', 'eszopiclone 3', 'إيزوبيكلون', 'سليبيز', 'منوم', 'نوم', 'أرق', 'insomnia', 'sleep', 'z-drug', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق وصعوبة النوم (منوم من فئة Z-drugs).',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ٣ مجم على معدة فارغة قبل النوم مباشرة، وإذا حدث نعاس صباحي استخدم تركيز أقل (١–٢ مجم) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 2
  {
    id: 'night-calm-3mg-30-fc-tabs-hs',
    name: 'night calm 3mg 30 f.c. tabs.',
    genericName: 'eszopiclone',
    concentration: '3mg',
    price: 105,
    matchKeywords: ['night calm 3', 'night calm', 'eszopiclone 3', 'نايت كالم', 'أرق', 'insomnia', 'sleep aid', 'z drug', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق وصعوبة النوم.',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ٣ مجم على معدة فارغة قبل النوم مباشرة، وإذا حدث نعاس صباحي استخدم تركيز أقل (١–٢ مجم) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 3
  {
    id: 'night-calm-1mg-30-fc-tabs-hs',
    name: 'night calm 1mg 30 f.c. tabs.',
    genericName: 'eszopiclone',
    concentration: '1mg',
    price: 60,
    matchKeywords: ['night calm 1', 'eszopiclone 1', 'نايت كالم ١', 'جرعة صغيرة', 'elderly', 'أرق', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق بجرعة بداية صغيرة (مناسب كبداية أو لكبار السن).',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ١ مجم على معدة فارغة قبل النوم مباشرة، ويمكن رفع الجرعة إلى ٢–٣ مجم بتركيز مناسب إذا استمر الأرق – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 4
  {
    id: 'buspar-10mg-20-tabs-hs',
    name: 'buspar 10mg 20 tab.',
    genericName: 'buspirone hydrochloride',
    concentration: '10mg',
    price: 81,
    matchKeywords: ['buspar 10', 'buspirone 10', 'buspirone', 'بوسبار', 'بوسبيرون', 'قلق', 'gad', 'anxiety', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج القلق العام والتوتر (مضاد قلق غير بنزوديازيبين).',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – ٤–٨ أسابيع أو أطول',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٥ مجم ٢–٣ مرات يومياً بدون اعتبار للأكل كبداية، ثم تدرج إلى جرعة شائعة ١٥–٣٠ مجم/يوم مقسمة (حد أقصى ٦٠ مجم/يوم) – لمدة ٤–٨ أسابيع أو أطول حسب الاستجابة.'),
    warnings: BUSPIRONE_WARNINGS,
  },

  // 5
  {
    id: 'sleepez-2mg-20-fc-tabs-hs',
    name: 'sleepez 2mg 20 f.c. tabs.',
    genericName: 'eszopiclone',
    concentration: '2mg',
    price: 40,
    matchKeywords: ['sleepez 2', 'eszopiclone 2', 'سليبيز ٢', 'أرق', 'منوم', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق بجرعة متوسطة.',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ٢ مجم على معدة فارغة قبل النوم مباشرة، ويمكن رفع الجرعة إلى ٣ مجم بتركيز مناسب إذا استمر الأرق – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 6
  {
    id: 'sleepez-1mg-20-fc-tabs-hs',
    name: 'sleepez 1 mg 20 f.c.tabs.',
    genericName: 'eszopiclone',
    concentration: '1mg',
    price: 32,
    matchKeywords: ['sleepez 1', 'eszopiclone 1', 'سليبيز ١', 'أرق', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق بجرعة بداية صغيرة.',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ١ مجم على معدة فارغة قبل النوم مباشرة (جرعة بداية) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 7
  {
    id: 'westsleep-3mg-30-fc-tabs-hs',
    name: 'westsleep 3 mg 30 f.c.tabs.',
    genericName: 'eszopiclone',
    concentration: '3mg',
    price: 81,
    matchKeywords: ['westsleep 3', 'westsleep', 'eszopiclone 3', 'ويست سليب', 'أرق', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق وصعوبة النوم.',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ٣ مجم على معدة فارغة قبل النوم مباشرة، وإذا حدث نعاس صباحي استخدم تركيز أقل (١–٢ مجم) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 8
  {
    id: 'alprax-1mg-20-tabs-hs',
    name: 'alprax 1 mg 20 tabs',
    genericName: 'alprazolam',
    concentration: '1mg',
    price: 46,
    matchKeywords: ['alprax 1', 'alprazolam 1', 'alprazolam', 'alprax', 'البركس', 'البرازولام', 'قلق', 'panic', 'panic attack', 'anxiety', 'xanax', 'زاناكس', '#anxiolytics', '#hypnotics'],
    usage: 'مهدئ/مضاد قلق (بنزوديازيبين) للقلق الشديد/نوبات الهلع.',
    timing: 'كل ٨ ساعات بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٠٫٢٥–٠٫٥ مجم ٣ مرات يومياً بدون اعتبار للأكل بداية، يُزاد تدريجياً (حد أقصى معتاد ٤ مجم/يوم) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: BENZO_WARNINGS,
  },

  // 9
  {
    id: 'hypnor-7-5mg-10-tabs-hs',
    name: 'hypnor 7.5mg 10 tab.',
    genericName: 'zopiclone',
    concentration: '7.5mg',
    price: 9,
    matchKeywords: ['hypnor 7.5', 'zopiclone 7.5', 'zopiclone', 'زوبيكلون', 'هيبنور', 'منوم', 'أرق', 'insomnia', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق على المدى القصير.',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('نصف إلى قرص كامل (٣٫٧٥–٧٫٥ مجم) على معدة فارغة قبل النوم، وكبار السن يبدأون بنصف قرص – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 10
  {
    id: 'no-deprine-50mg-30-tabs-hs',
    name: 'no deprine 50mg 30 tab',
    genericName: 'tofisopam',
    concentration: '50mg',
    price: 99,
    matchKeywords: ['no deprine 50', 'tofisopam 50', 'tofisopam', 'توفيسوبام', 'نودبرين', 'قلق', 'anxiety', '#anxiolytics', '#hypnotics'],
    usage: 'مضاد قلق (غير بنزوديازيبين تقليدي) لعلاج القلق/التوتر.',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – ٤–٨ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٥٠ مجم ٢–٣ مرات يومياً بدون اعتبار للأكل (حد أقصى ٣٠٠ مجم/يوم) – لمدة ٤–٨ أسابيع حسب الاستجابة.'),
    warnings: TOFISOPAM_WARNINGS,
  },

  // 11
  {
    id: 'restolam-0-5mg-20-tabs-hs',
    name: 'restolam 0.5mg 20 tab.',
    genericName: 'alprazolam',
    concentration: '0.5mg',
    price: 24,
    matchKeywords: ['restolam 0.5', 'restolam', 'alprazolam 0.5', 'alprazolam', 'ريستولام', 'قلق', 'panic', 'panic attack', '#anxiolytics', '#hypnotics'],
    usage: 'مهدئ/مضاد قلق (بنزوديازيبين).',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٠٫٢٥–٠٫٥ مجم ٢–٣ مرات يومياً بدون اعتبار للأكل، ثم التدرج حسب الاستجابة – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: BENZO_WARNINGS,
  },

  // 12
  {
    id: 'restolam-1mg-20-tabs-hs',
    name: 'restolam 1 mg 20 tabs.',
    genericName: 'alprazolam',
    concentration: '1mg',
    price: 42,
    matchKeywords: ['restolam 1', 'alprazolam 1', 'alprazolam', 'ريستولام ١', 'قلق', 'panic', '#anxiolytics', '#hypnotics'],
    usage: 'مهدئ/مضاد قلق (بنزوديازيبين).',
    timing: 'كل ٨ ساعات بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٠٫٢٥–٠٫٥ مجم ٣ مرات يومياً بدون اعتبار للأكل، يُزاد تدريجياً (حد أقصى معتاد ٤ مجم/يوم) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: BENZO_WARNINGS,
  },

  // 13
  {
    id: 'xanax-0-5mg-100-tabs-hs',
    name: 'xanax 0.5 mg 100 tab.',
    genericName: 'alprazolam',
    concentration: '0.5mg',
    price: 160,
    matchKeywords: ['xanax 0.5 100', 'xanax', 'alprazolam 0.5', 'زاناكس', 'البرازولام', '#anxiolytics', '#hypnotics'],
    usage: 'مهدئ/مضاد قلق (بنزوديازيبين).',
    timing: 'كل ٨ ساعات بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٠٫٢٥–٠٫٥ مجم ٣ مرات يومياً بدون اعتبار للأكل، يُزاد تدريجياً (حد أقصى معتاد ٤ مجم/يوم) – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: BENZO_WARNINGS,
  },

  // 14
  {
    id: 'zolam-0-25mg-30-tabs-hs',
    name: 'zolam 0.25mg 30 tab.',
    genericName: 'alprazolam',
    concentration: '0.25mg',
    price: 30,
    matchKeywords: ['zolam 0.25', 'alprazolam 0.25', 'زولام ٠٫٢٥', '#anxiolytics', '#hypnotics'],
    usage: 'مضاد قلق (بنزوديازيبين) بجرعة صغيرة.',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٠٫٢٥ مجم ٢–٣ مرات يومياً بدون اعتبار للأكل حسب الاستجابة – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: BENZO_WARNINGS,
  },

  // 15
  {
    id: 'nestacoran-2mg-20-fc-tabs-hs',
    name: 'nestacoran 2mg 20 f.c. tabs.',
    genericName: 'eszopiclone',
    concentration: '2mg',
    price: 40,
    matchKeywords: ['nestacoran 2', 'eszopiclone 2', 'نيستاكران', 'أرق', '#anxiolytics', '#hypnotics'],
    usage: 'لعلاج الأرق بجرعة متوسطة.',
    timing: 'قرص قبل النوم مباشرة – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Film-coated Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 45,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ٢ مجم على معدة فارغة قبل النوم مباشرة، ويمكن رفع الجرعة إلى ٣ مجم بتركيز مناسب إذا استمر الأرق – لمدة قصيرة لا تتجاوز ٤ أسابيع.'),
    warnings: Z_DRUG_WARNINGS,
  },

  // 16
  {
    id: 'xanax-0-25mg-100-tabs-hs',
    name: 'xanax 0.25mg 100 tab.',
    genericName: 'alprazolam',
    concentration: '0.25mg',
    price: 110,
    matchKeywords: ['xanax 0.25 100', 'alprazolam 0.25', 'زاناكس ٠٫٢٥', '#anxiolytics', '#hypnotics'],
    usage: 'مضاد قلق (بنزوديازيبين) بجرعة صغيرة.',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('جرعات شائعة: ٠٫٢٥ مجم ٢–٣ مرات يومياً حسب الاستجابة.'),
    warnings: BENZO_WARNINGS,
  },

  // 17
  {
    id: 'zolam-0-5mg-10-tabs-hs',
    name: 'zolam 0.5mg 10 tab.',
    genericName: 'alprazolam',
    concentration: '0.5mg',
    price: 12,
    matchKeywords: ['zolam 0.5 10', 'alprazolam 0.5', 'زولام ٠٫٥ ١٠', '#anxiolytics', '#hypnotics'],
    usage: 'مضاد قلق (بنزوديازيبين).',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('جرعات شائعة: ٠٫٢٥–٠٫٥ مجم ٢–٣ مرات يومياً حسب الاستجابة.'),
    warnings: BENZO_WARNINGS,
  },

  // 18
  {
    id: 'zolam-0-5mg-30-tabs-hs',
    name: 'zolam 0.5mg 30 tab.',
    genericName: 'alprazolam',
    concentration: '0.5mg',
    price: 36,
    matchKeywords: ['zolam 0.5 30', 'alprazolam 0.5', 'زولام ٠٫٥ ٣٠', '#anxiolytics', '#hypnotics'],
    usage: 'مضاد قلق (بنزوديازيبين).',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – أقل من ٤ أسابيع',
    category: Category.HYPNOTICS_SEDATIVES,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('جرعات شائعة: ٠٫٢٥–٠٫٥ مجم ٢–٣ مرات يومياً حسب الاستجابة.'),
    warnings: BENZO_WARNINGS,
  },
];

