/**
 * الملف: constants.ts
 * الوصف: "مستودع القيم الافتراضية". 
 * يحتوي هذا الملف على كافة الثوابت التي يحتاجها النظام لإدارة الباقات: 
 * 1. DEFAULT_FORM: القيم الأولية للحدود والرسائل (تستخدم عند تهيئة لوحة التحكم). 
 * 2. مجموعات التحكم (GROUPS): تعريف هيكل الأقسام (مثل تحليل الحالة، الروشتات) وكيفية عرضها. 
 * 3. مفاتيح البيانات (Keys): مصفوفات لتسهيل عملية التكرار (Iteration) وحفظ البيانات في Firestore. 
 * 4. إعدادات الواتساب: الأرقام والروابط الافتراضية للتواصل.
 */

import type { LimitKey, MessageKey, WhatsappMessageKey } from './types';
import type { AccountTypeControls } from '../../../services/accountTypeControlsService';
import { GroupConfig } from '../../../types';

export const DEFAULT_FORM: AccountTypeControls = {
  freeDailyLimit: 2,
  premiumDailyLimit: 50,
  freeRecordDailyLimit: 3,
  premiumRecordDailyLimit: 50,
  freePublicBookingDailyLimit: 10,
  premiumPublicBookingDailyLimit: 200,
  freePublicFormBookingDailyLimit: 10,
  premiumPublicFormBookingDailyLimit: 200,
  freeSecretaryEntryRequestDailyLimit: 20,
  premiumSecretaryEntryRequestDailyLimit: 300,
  freeReadyPrescriptionDailyLimit: 3,
  premiumReadyPrescriptionDailyLimit: 50,
  freeMedicalReportDailyLimit: 3,
  premiumMedicalReportDailyLimit: 80,
  freeReadyPrescriptionsMaxCount: 5,
  premiumReadyPrescriptionsMaxCount: 100,
  freeMedicationCustomizationsMaxCount: 20,
  premiumMedicationCustomizationsMaxCount: 500,
  freeInteractionToolDailyLimit: 5000,
  premiumInteractionToolDailyLimit: 5000,
  freeRenalToolDailyLimit: 5000,
  premiumRenalToolDailyLimit: 5000,
  freePregnancyToolDailyLimit: 5000,
  premiumPregnancyToolDailyLimit: 5000,
  freeAnalysisLimitMessage: 'تم استهلاك الحد اليومي لتحليل الحالة (3 مرات) للحساب المجاني. للتواصل واتساب',
  premiumAnalysisLimitMessage: 'تم استهلاك الحد اليومي لتحليل الحالة (50 مرة) لحساب برو. للتواصل واتساب',
  freeRecordLimitMessage: 'تم استهلاك الحد اليومي لحفظ السجلات (3 مرات) للحساب المجاني. للتواصل واتساب',
  premiumRecordLimitMessage: 'تم استهلاك الحد اليومي لحفظ السجلات (50 مرة) لحساب برو. للتواصل واتساب',
  freePublicBookingLimitMessage: 'تم استهلاك الحد اليومي لإضافة موعد عند الطبيب ({limit}) للحساب المجاني. للتواصل واتساب',
  premiumPublicBookingLimitMessage: 'تم استهلاك الحد اليومي لإضافة موعد عند الطبيب ({limit}) لحساب برو. للتواصل واتساب',
  freePublicFormBookingLimitMessage: 'تم استهلاك الحد اليومي للحجز من فورم الجمهور ({limit}) للحساب المجاني. للتواصل واتساب',
  premiumPublicFormBookingLimitMessage: 'تم استهلاك الحد اليومي للحجز من فورم الجمهور ({limit}) لحساب برو. للتواصل واتساب',
  freeSecretaryEntryRequestLimitMessage: 'تم استهلاك الحد اليومي لارسال موعد للطبيب من خلال السكرتارية ({limit}) للحساب المجاني. للتواصل واتساب',
  premiumSecretaryEntryRequestLimitMessage: 'تم استهلاك الحد اليومي لارسال موعد للطبيب من خلال السكرتارية ({limit}) لحساب برو. للتواصل واتساب',
  freeReadyPrescriptionDailyLimitMessage: 'تم استهلاك الحد اليومي لحفظ الروشتات الجاهزة (3 مرات) للحساب المجاني. للتواصل واتساب',
  premiumReadyPrescriptionDailyLimitMessage: 'تم استهلاك الحد اليومي لحفظ الروشتات الجاهزة (50 مرة) لحساب برو. للتواصل واتساب',
  freeMedicalReportLimitMessage: 'تم استهلاك الحد اليومي لطباعة التقرير الطبي للحالة ({limit}) للحساب المجاني. للتواصل واتساب',
  premiumMedicalReportLimitMessage: 'تم استهلاك الحد اليومي لطباعة التقرير الطبي للحالة ({limit}) لحساب برو. للتواصل واتساب',
  freeReadyPrescriptionsCapacityMessage: 'وصلت للحد الأقصى للروشتات الجاهزة ({limit}) للحساب المجاني. احذف واحدة أولاً ثم أضف الجديدة.',
  premiumReadyPrescriptionsCapacityMessage: 'وصلت للحد الأقصى للروشتات الجاهزة ({limit}) لحساب برو. احذف واحدة أولاً ثم أضف الجديدة.',
  freeMedicationCustomizationsCapacityMessage: 'وصلت للحد الأقصى لتخزين الأدوية المعدلة ({limit}) للحساب المجاني.',
  premiumMedicationCustomizationsCapacityMessage: 'وصلت للحد الأقصى لتخزين الأدوية المعدلة ({limit}) لحساب برو.',
  whatsappNumber: '201092805293',
  freeAnalysisWhatsappMessage: 'السلام عليكم، تجاوزت حد تحليل الحالة وأرغب في الاشتراك.',
  premiumAnalysisWhatsappMessage: 'السلام عليكم، استهلكت حد تحليل الحالة وأرغب في ترقية الباقة.',
  freeRecordWhatsappMessage: 'السلام عليكم، تجاوزت حد حفظ السجلات وأرغب في الاشتراك.',
  premiumRecordWhatsappMessage: 'السلام عليكم، استهلكت حد حفظ السجلات وأرغب في ترقية الباقة.',
  freePublicBookingWhatsappMessage: 'السلام عليكم، تجاوزت حد إضافة المواعيد اليومية وأرغب في الاشتراك.',
  premiumPublicBookingWhatsappMessage: 'السلام عليكم، استهلكت حد إضافة المواعيد اليومية وأرغب في ترقية الباقة.',
  freePublicFormBookingWhatsappMessage: 'السلام عليكم، تجاوزت حد الحجز اليومي من فورم الجمهور وأرغب في الاشتراك.',
  premiumPublicFormBookingWhatsappMessage: 'السلام عليكم، استهلكت حد الحجز اليومي من فورم الجمهور وأرغب في ترقية الباقة.',
  freeSecretaryEntryRequestWhatsappMessage: 'السلام عليكم، تجاوزت حد ارسال الموعد للطبيب من خلال السكرتارية وأرغب في الاشتراك.',
  premiumSecretaryEntryRequestWhatsappMessage: 'السلام عليكم، استهلكت حد ارسال الموعد للطبيب من خلال السكرتارية وأرغب في ترقية الباقة.',
  freeReadyPrescriptionWhatsappMessage: 'السلام عليكم، تجاوزت حد حفظ الروشتات الجاهزة وأرغب في الاشتراك.',
  premiumReadyPrescriptionWhatsappMessage: 'السلام عليكم، استهلكت حد حفظ الروشتات الجاهزة وأرغب في ترقية الباقة.',
  freeMedicalReportWhatsappMessage: 'السلام عليكم، تجاوزت الحد اليومي لطباعة التقرير الطبي للحالة وأرغب في الاشتراك.',
  premiumMedicalReportWhatsappMessage: 'السلام عليكم، استهلكت الحد اليومي لطباعة التقرير الطبي للحالة وأرغب في ترقية الباقة.',
  freeReadyPrescriptionsCapacityWhatsappMessage: 'السلام عليكم، وصلت للحد الأقصى لعدد الروشتات الجاهزة وأرغب في الاشتراك.',
  premiumReadyPrescriptionsCapacityWhatsappMessage: 'السلام عليكم، وصلت للحد الأقصى لعدد الروشتات الجاهزة وأرغب في ترقية الباقة.',
  freeMedicationCustomizationsCapacityWhatsappMessage: 'السلام عليكم، وصلت للحد الأقصى لتخزين الأدوية المعدلة وأرغب في الاشتراك.',
  premiumMedicationCustomizationsCapacityWhatsappMessage: 'السلام عليكم، وصلت للحد الأقصى لتخزين الأدوية المعدلة وأرغب في ترقية الباقة.',
  interactionToolPremiumOnly: true,
  renalToolPremiumOnly: true,
  pregnancyToolPremiumOnly: true,
  interactionToolLockedMessage: 'هذه الأداة متاحة لحساب برو وبرو ماكس فقط.',
  renalToolLockedMessage: 'هذه الأداة متاحة لحساب برو وبرو ماكس فقط.',
  pregnancyToolLockedMessage: 'هذه الأداة متاحة لحساب برو وبرو ماكس فقط.',
  premiumTagLabel: 'Pro',
  // ─── قيم افتراضية مبدئية للفئة الجديدة "برو ماكس" (مطابقة لـ برو — الأدمن يعدّل لاحقاً) ───
  proMaxDailyLimit: 50,
  proMaxRecordDailyLimit: 50,
  proMaxPublicBookingDailyLimit: 200,
  proMaxPublicFormBookingDailyLimit: 200,
  proMaxSecretaryEntryRequestDailyLimit: 300,
  proMaxReadyPrescriptionDailyLimit: 50,
  proMaxMedicalReportDailyLimit: 80,
  proMaxReadyPrescriptionsMaxCount: 100,
  proMaxMedicationCustomizationsMaxCount: 500,
  proMaxInteractionToolDailyLimit: 5000,
  proMaxRenalToolDailyLimit: 5000,
  proMaxPregnancyToolDailyLimit: 5000,
  proMaxAnalysisLimitMessage: 'تم استهلاك الحد اليومي لتحليل الحالة (50 مرة) لحساب برو ماكس. للتواصل واتساب',
  proMaxRecordLimitMessage: 'تم استهلاك الحد اليومي لحفظ السجلات (50 مرة) لحساب برو ماكس. للتواصل واتساب',
  proMaxPublicBookingLimitMessage: 'تم استهلاك الحد اليومي لإضافة موعد عند الطبيب ({limit}) لحساب برو ماكس. للتواصل واتساب',
  proMaxPublicFormBookingLimitMessage: 'تم استهلاك الحد اليومي للحجز من فورم الجمهور ({limit}) لحساب برو ماكس. للتواصل واتساب',
  proMaxSecretaryEntryRequestLimitMessage: 'تم استهلاك الحد اليومي لارسال موعد للطبيب من خلال السكرتارية ({limit}) لحساب برو ماكس. للتواصل واتساب',
  proMaxReadyPrescriptionDailyLimitMessage: 'تم استهلاك الحد اليومي لحفظ الروشتات الجاهزة (50 مرة) لحساب برو ماكس. للتواصل واتساب',
  proMaxMedicalReportLimitMessage: 'تم استهلاك الحد اليومي لطباعة التقرير الطبي للحالة ({limit}) لحساب برو ماكس. للتواصل واتساب',
  proMaxReadyPrescriptionsCapacityMessage: 'وصلت للحد الأقصى للروشتات الجاهزة ({limit}) لحساب برو ماكس. احذف واحدة أولاً ثم أضف الجديدة.',
  proMaxMedicationCustomizationsCapacityMessage: 'وصلت للحد الأقصى لتخزين الأدوية المعدلة ({limit}) لحساب برو ماكس.',
  proMaxAnalysisWhatsappMessage: 'السلام عليكم، استهلكت حد تحليل الحالة في باقة برو ماكس وأرغب في التواصل.',
  proMaxRecordWhatsappMessage: 'السلام عليكم، استهلكت حد حفظ السجلات في باقة برو ماكس وأرغب في التواصل.',
  proMaxPublicBookingWhatsappMessage: 'السلام عليكم، استهلكت حد إضافة المواعيد اليومية في باقة برو ماكس وأرغب في التواصل.',
  proMaxPublicFormBookingWhatsappMessage: 'السلام عليكم، استهلكت حد الحجز اليومي من فورم الجمهور في باقة برو ماكس وأرغب في التواصل.',
  proMaxSecretaryEntryRequestWhatsappMessage: 'السلام عليكم، استهلكت حد ارسال الموعد للطبيب من خلال السكرتارية في باقة برو ماكس وأرغب في التواصل.',
  proMaxReadyPrescriptionWhatsappMessage: 'السلام عليكم، استهلكت حد حفظ الروشتات الجاهزة في باقة برو ماكس وأرغب في التواصل.',
  proMaxMedicalReportWhatsappMessage: 'السلام عليكم، استهلكت الحد اليومي لطباعة التقرير الطبي للحالة في باقة برو ماكس وأرغب في التواصل.',
  proMaxReadyPrescriptionsCapacityWhatsappMessage: 'السلام عليكم، وصلت للحد الأقصى لعدد الروشتات الجاهزة في باقة برو ماكس وأرغب في التواصل.',
  proMaxMedicationCustomizationsCapacityWhatsappMessage: 'السلام عليكم، وصلت للحد الأقصى لتخزين الأدوية المعدلة في باقة برو ماكس وأرغب في التواصل.',
  proMaxTagLabel: 'Pro Max',
  whatsappUrl: 'https://wa.me/201092805293',
};

export const LIMIT_KEYS: LimitKey[] = [
  'freeDailyLimit',
  'premiumDailyLimit',
  'freeRecordDailyLimit',
  'premiumRecordDailyLimit',
  'freePublicBookingDailyLimit',
  'premiumPublicBookingDailyLimit',
  'freePublicFormBookingDailyLimit',
  'premiumPublicFormBookingDailyLimit',
  'freeSecretaryEntryRequestDailyLimit',
  'premiumSecretaryEntryRequestDailyLimit',
  'freeReadyPrescriptionDailyLimit',
  'premiumReadyPrescriptionDailyLimit',
  'freeMedicalReportDailyLimit',
  'premiumMedicalReportDailyLimit',
  'freeReadyPrescriptionsMaxCount',
  'premiumReadyPrescriptionsMaxCount',
  'freeMedicationCustomizationsMaxCount',
  'premiumMedicationCustomizationsMaxCount',
  // ─── برو ماكس ───
  'proMaxDailyLimit',
  'proMaxRecordDailyLimit',
  'proMaxPublicBookingDailyLimit',
  'proMaxPublicFormBookingDailyLimit',
  'proMaxSecretaryEntryRequestDailyLimit',
  'proMaxReadyPrescriptionDailyLimit',
  'proMaxMedicalReportDailyLimit',
  'proMaxReadyPrescriptionsMaxCount',
  'proMaxMedicationCustomizationsMaxCount',
];

export const DRUG_TOOLS_LIMIT_KEYS: Array<
  | 'freeInteractionToolDailyLimit'
  | 'premiumInteractionToolDailyLimit'
  | 'proMaxInteractionToolDailyLimit'
  | 'freeRenalToolDailyLimit'
  | 'premiumRenalToolDailyLimit'
  | 'proMaxRenalToolDailyLimit'
  | 'freePregnancyToolDailyLimit'
  | 'premiumPregnancyToolDailyLimit'
  | 'proMaxPregnancyToolDailyLimit'
> = [
    'freeInteractionToolDailyLimit',
    'premiumInteractionToolDailyLimit',
    'proMaxInteractionToolDailyLimit',
    'freeRenalToolDailyLimit',
    'premiumRenalToolDailyLimit',
    'proMaxRenalToolDailyLimit',
    'freePregnancyToolDailyLimit',
    'premiumPregnancyToolDailyLimit',
    'proMaxPregnancyToolDailyLimit',
  ];

export const LIMIT_MESSAGE_KEYS: MessageKey[] = [
  'freeAnalysisLimitMessage',
  'premiumAnalysisLimitMessage',
  'freeRecordLimitMessage',
  'premiumRecordLimitMessage',
  'freePublicBookingLimitMessage',
  'premiumPublicBookingLimitMessage',
  'freePublicFormBookingLimitMessage',
  'premiumPublicFormBookingLimitMessage',
  'freeSecretaryEntryRequestLimitMessage',
  'premiumSecretaryEntryRequestLimitMessage',
  'freeReadyPrescriptionDailyLimitMessage',
  'premiumReadyPrescriptionDailyLimitMessage',
  'freeMedicalReportLimitMessage',
  'premiumMedicalReportLimitMessage',
  'freeReadyPrescriptionsCapacityMessage',
  'premiumReadyPrescriptionsCapacityMessage',
  'freeMedicationCustomizationsCapacityMessage',
  'premiumMedicationCustomizationsCapacityMessage',
  // ─── برو ماكس ───
  'proMaxAnalysisLimitMessage',
  'proMaxRecordLimitMessage',
  'proMaxPublicBookingLimitMessage',
  'proMaxPublicFormBookingLimitMessage',
  'proMaxSecretaryEntryRequestLimitMessage',
  'proMaxReadyPrescriptionDailyLimitMessage',
  'proMaxMedicalReportLimitMessage',
  'proMaxReadyPrescriptionsCapacityMessage',
  'proMaxMedicationCustomizationsCapacityMessage',
];

export const WHATSAPP_MESSAGE_KEYS: WhatsappMessageKey[] = [
  'freeAnalysisWhatsappMessage',
  'premiumAnalysisWhatsappMessage',
  'freeRecordWhatsappMessage',
  'premiumRecordWhatsappMessage',
  'freePublicBookingWhatsappMessage',
  'premiumPublicBookingWhatsappMessage',
  'freePublicFormBookingWhatsappMessage',
  'premiumPublicFormBookingWhatsappMessage',
  'freeSecretaryEntryRequestWhatsappMessage',
  'premiumSecretaryEntryRequestWhatsappMessage',
  'freeReadyPrescriptionWhatsappMessage',
  'premiumReadyPrescriptionWhatsappMessage',
  'freeMedicalReportWhatsappMessage',
  'premiumMedicalReportWhatsappMessage',
  'freeReadyPrescriptionsCapacityWhatsappMessage',
  'premiumReadyPrescriptionsCapacityWhatsappMessage',
  'freeMedicationCustomizationsCapacityWhatsappMessage',
  'premiumMedicationCustomizationsCapacityWhatsappMessage',
  // ─── برو ماكس ───
  'proMaxAnalysisWhatsappMessage',
  'proMaxRecordWhatsappMessage',
  'proMaxPublicBookingWhatsappMessage',
  'proMaxPublicFormBookingWhatsappMessage',
  'proMaxSecretaryEntryRequestWhatsappMessage',
  'proMaxReadyPrescriptionWhatsappMessage',
  'proMaxMedicalReportWhatsappMessage',
  'proMaxReadyPrescriptionsCapacityWhatsappMessage',
  'proMaxMedicationCustomizationsCapacityWhatsappMessage',
];

const GROUPS: GroupConfig[] = [
  {
    id: 'analysis',
    title: 'تحليل الحالة',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تحليل الحالة (مجاني)',
      whatsappPlaceholder: 'رسالة تحليل الحالة - مجاني',
      limitKey: 'freeDailyLimit',
      messageKey: 'freeAnalysisLimitMessage',
      whatsappMessageKey: 'freeAnalysisWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تحليل الحالة (برو)',
      whatsappPlaceholder: 'رسالة تحليل الحالة - برو',
      limitKey: 'premiumDailyLimit',
      messageKey: 'premiumAnalysisLimitMessage',
      whatsappMessageKey: 'premiumAnalysisWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تحليل الحالة (برو ماكس)',
      whatsappPlaceholder: 'رسالة تحليل الحالة - برو ماكس',
      limitKey: 'proMaxDailyLimit',
      messageKey: 'proMaxAnalysisLimitMessage',
      whatsappMessageKey: 'proMaxAnalysisWhatsappMessage',
    },
  },
  {
    id: 'records',
    title: 'حفظ السجلات',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حفظ السجلات (مجاني)',
      whatsappPlaceholder: 'رسالة حفظ السجلات - مجاني',
      limitKey: 'freeRecordDailyLimit',
      messageKey: 'freeRecordLimitMessage',
      whatsappMessageKey: 'freeRecordWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حفظ السجلات (برو)',
      whatsappPlaceholder: 'رسالة حفظ السجلات - برو',
      limitKey: 'premiumRecordDailyLimit',
      messageKey: 'premiumRecordLimitMessage',
      whatsappMessageKey: 'premiumRecordWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حفظ السجلات (برو ماكس)',
      whatsappPlaceholder: 'رسالة حفظ السجلات - برو ماكس',
      limitKey: 'proMaxRecordDailyLimit',
      messageKey: 'proMaxRecordLimitMessage',
      whatsappMessageKey: 'proMaxRecordWhatsappMessage',
    },
  },
  {
    id: 'medical_report_print',
    title: 'طباعة تقرير طبي للحالة',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة التقرير (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة التقرير - مجاني',
      limitKey: 'freeMedicalReportDailyLimit',
      messageKey: 'freeMedicalReportLimitMessage',
      whatsappMessageKey: 'freeMedicalReportWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة التقرير (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة التقرير - برو',
      limitKey: 'premiumMedicalReportDailyLimit',
      messageKey: 'premiumMedicalReportLimitMessage',
      whatsappMessageKey: 'premiumMedicalReportWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة التقرير (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة التقرير - برو ماكس',
      limitKey: 'proMaxMedicalReportDailyLimit',
      messageKey: 'proMaxMedicalReportLimitMessage',
      whatsappMessageKey: 'proMaxMedicalReportWhatsappMessage',
    },
  },
  {
    id: 'public_booking',
    title: 'إضافة موعد عند الطبيب (زر إضافة الموعد)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إضافة موعد (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لإضافة موعد - مجاني',
      limitKey: 'freePublicBookingDailyLimit',
      messageKey: 'freePublicBookingLimitMessage',
      whatsappMessageKey: 'freePublicBookingWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إضافة موعد (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لإضافة موعد - برو',
      limitKey: 'premiumPublicBookingDailyLimit',
      messageKey: 'premiumPublicBookingLimitMessage',
      whatsappMessageKey: 'premiumPublicBookingWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إضافة موعد (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لإضافة موعد - برو ماكس',
      limitKey: 'proMaxPublicBookingDailyLimit',
      messageKey: 'proMaxPublicBookingLimitMessage',
      whatsappMessageKey: 'proMaxPublicBookingWhatsappMessage',
    },
  },
  {
    id: 'secretary_request',
    title: 'ارسال موعد للطبيب من خلال السكرتارية (زر ارسال الى الطبيب)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب ارسال الموعد للطبيب (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لارسال الموعد للطبيب - مجاني',
      limitKey: 'freeSecretaryEntryRequestDailyLimit',
      messageKey: 'freeSecretaryEntryRequestLimitMessage',
      whatsappMessageKey: 'freeSecretaryEntryRequestWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب ارسال الموعد للطبيب (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لارسال الموعد للطبيب - برو',
      limitKey: 'premiumSecretaryEntryRequestDailyLimit',
      messageKey: 'premiumSecretaryEntryRequestLimitMessage',
      whatsappMessageKey: 'premiumSecretaryEntryRequestWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب ارسال الموعد للطبيب (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لارسال الموعد للطبيب - برو ماكس',
      limitKey: 'proMaxSecretaryEntryRequestDailyLimit',
      messageKey: 'proMaxSecretaryEntryRequestLimitMessage',
      whatsappMessageKey: 'proMaxSecretaryEntryRequestWhatsappMessage',
    },
  },
  {
    id: 'public_form_booking',
    title: 'حجز موعد من فورم الجمهور',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حجز فورم الجمهور (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لحجز فورم الجمهور - مجاني',
      limitKey: 'freePublicFormBookingDailyLimit',
      messageKey: 'freePublicFormBookingLimitMessage',
      whatsappMessageKey: 'freePublicFormBookingWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حجز فورم الجمهور (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لحجز فورم الجمهور - برو',
      limitKey: 'premiumPublicFormBookingDailyLimit',
      messageKey: 'premiumPublicFormBookingLimitMessage',
      whatsappMessageKey: 'premiumPublicFormBookingWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حجز فورم الجمهور (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لحجز فورم الجمهور - برو ماكس',
      limitKey: 'proMaxPublicFormBookingDailyLimit',
      messageKey: 'proMaxPublicFormBookingLimitMessage',
      whatsappMessageKey: 'proMaxPublicFormBookingWhatsappMessage',
    },
  },
  {
    id: 'ready_daily',
    title: 'حفظ الروشتات الجاهزة يوميا',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الروشتات الجاهزة (مجاني)',
      whatsappPlaceholder: 'رسالة الروشتات الجاهزة - مجاني',
      limitKey: 'freeReadyPrescriptionDailyLimit',
      messageKey: 'freeReadyPrescriptionDailyLimitMessage',
      whatsappMessageKey: 'freeReadyPrescriptionWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الروشتات الجاهزة (برو)',
      whatsappPlaceholder: 'رسالة الروشتات الجاهزة - برو',
      limitKey: 'premiumReadyPrescriptionDailyLimit',
      messageKey: 'premiumReadyPrescriptionDailyLimitMessage',
      whatsappMessageKey: 'premiumReadyPrescriptionWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الروشتات الجاهزة (برو ماكس)',
      whatsappPlaceholder: 'رسالة الروشتات الجاهزة - برو ماكس',
      limitKey: 'proMaxReadyPrescriptionDailyLimit',
      messageKey: 'proMaxReadyPrescriptionDailyLimitMessage',
      whatsappMessageKey: 'proMaxReadyPrescriptionWhatsappMessage',
    },
  },
  {
    id: 'ready_capacity',
    title: 'الحد الأقصى لعدد الروشتات الجاهزة',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الروشتات (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الروشتات الجاهزة - مجاني',
      limitKey: 'freeReadyPrescriptionsMaxCount',
      messageKey: 'freeReadyPrescriptionsCapacityMessage',
      whatsappMessageKey: 'freeReadyPrescriptionsCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الروشتات (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الروشتات الجاهزة - برو',
      limitKey: 'premiumReadyPrescriptionsMaxCount',
      messageKey: 'premiumReadyPrescriptionsCapacityMessage',
      whatsappMessageKey: 'premiumReadyPrescriptionsCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الروشتات (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الروشتات الجاهزة - برو ماكس',
      limitKey: 'proMaxReadyPrescriptionsMaxCount',
      messageKey: 'proMaxReadyPrescriptionsCapacityMessage',
      whatsappMessageKey: 'proMaxReadyPrescriptionsCapacityWhatsappMessage',
    },
  },
  {
    id: 'medication_customizations_capacity',
    title: 'تخزين الأدوية المعدلة',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الأدوية المعدلة (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الأدوية المعدلة - مجاني',
      limitKey: 'freeMedicationCustomizationsMaxCount',
      messageKey: 'freeMedicationCustomizationsCapacityMessage',
      whatsappMessageKey: 'freeMedicationCustomizationsCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الأدوية المعدلة (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الأدوية المعدلة - برو',
      limitKey: 'premiumMedicationCustomizationsMaxCount',
      messageKey: 'premiumMedicationCustomizationsCapacityMessage',
      whatsappMessageKey: 'premiumMedicationCustomizationsCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الأدوية المعدلة (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الأدوية المعدلة - برو ماكس',
      limitKey: 'proMaxMedicationCustomizationsMaxCount',
      messageKey: 'proMaxMedicationCustomizationsCapacityMessage',
      whatsappMessageKey: 'proMaxMedicationCustomizationsCapacityWhatsappMessage',
    },
  },
];

const END_GROUP_IDS = new Set(['public_booking', 'public_form_booking', 'secretary_request']);
export const ORDERED_GROUPS = [
  ...GROUPS.filter((group) => !END_GROUP_IDS.has(group.id)),
  ...GROUPS.filter((group) => END_GROUP_IDS.has(group.id)),
];

export const createOpenMap = (): Record<string, boolean> => {
  const map: Record<string, boolean> = {};
  GROUPS.forEach((group) => {
    map[group.id] = false;
  });
  return map;
};
