/**
 * الملف: constants.ts
 * الوصف: "مستودع المفاتيح والمجموعات للوحة التحكم".
 * يحتوي على:
 * 1. DEFAULT_FORM: القيم الأولية للحدود والرسائل — مُعاد تصديرها من DEFAULT_CONTROLS
 *    (المصدر الموحَّد) بدل التكرار، عشان لو الأدمن غيّر default في مكان، يتطبّق في الكل.
 * 2. مجموعات التحكم (GROUPS): تعريف هيكل الأقسام (تحليل الحالة، الترجمة، الروشتات...) وعرضها.
 * 3. مفاتيح البيانات (Keys): مصفوفات لتسهيل عملية التكرار وحفظ البيانات في Firestore.
 *
 * 🗑️ (2026-05) شيلنا جروب الترجمة — كانت بتقفل الزرّين، الترجمة دلوقتي جزء من الزر
 */

import type { LimitKey, MessageKey, WhatsappMessageKey } from './types';
import type { AccountTypeControls } from '../../../services/accountTypeControlsService';
import { DEFAULT_CONTROLS } from '../../../services/account-type-controls/defaults';
import { GroupConfig } from '../../../types';

// ─ DEFAULT_FORM = نفس DEFAULT_CONTROLS من services (المصدر الوحيد للحقيقة).
// ─ كان فيه تكرار قديم (~100 سطر) كان بيخلق bug: لو الأدمن غيّر رسالة في مكان،
//   مكنش بيتطبّق في المكان التاني. التوحيد ده يحل المشكلة دي نهائياً.
export const DEFAULT_FORM: AccountTypeControls = DEFAULT_CONTROLS;

export const LIMIT_KEYS: LimitKey[] = [
  'freeDailyLimit',
  'premiumDailyLimit',
  // 🆕 الزر السريع "إضافة بدون تحليل" (2026-05) — عداد منفصل عن التحليل العميق
  'freeQuickAddDailyLimit',
  'premiumQuickAddDailyLimit',
  'proMaxQuickAddDailyLimit',
  // ─ السجلات بقت سعة كلية مش يومية ─
  'freeRecordsMaxCount',
  'premiumRecordsMaxCount',
  'freePublicBookingDailyLimit',
  'premiumPublicBookingDailyLimit',
  'freePublicFormBookingDailyLimit',
  'premiumPublicFormBookingDailyLimit',
  'freeSecretaryEntryRequestDailyLimit',
  'premiumSecretaryEntryRequestDailyLimit',
  'freeReadyPrescriptionDailyLimit',
  'premiumReadyPrescriptionDailyLimit',
  'freeMedicalReportDailyLimit',
  'premiumMedicalReportDailyLimit',
  // ✂️ شيلنا حد الترجمة (2026-05) — الترجمة بقت جزء طبيعي من شغل الزرّين، مفيش حد منفصل
  // ─── الأزرار الذهبية + الكلى تحت "حدود الميزات" 🆕 ───
  'freeInteractionToolDailyLimit',
  'premiumInteractionToolDailyLimit',
  'freePregnancyToolDailyLimit',
  'premiumPregnancyToolDailyLimit',
  'freeRenalToolDailyLimit',
  'premiumRenalToolDailyLimit',
  // ─── 🆕 أزرار تصدير الروشتة ───
  'freePrescriptionPrintDailyLimit',
  'premiumPrescriptionPrintDailyLimit',
  'freePrescriptionDownloadDailyLimit',
  'premiumPrescriptionDownloadDailyLimit',
  'freePrescriptionWhatsappDailyLimit',
  'premiumPrescriptionWhatsappDailyLimit',
  'freeReadyPrescriptionsMaxCount',
  'premiumReadyPrescriptionsMaxCount',
  'freeMedicationCustomizationsMaxCount',
  'premiumMedicationCustomizationsMaxCount',
  // ─── سعة الفروع 🆕 ───
  'freeBranchesMaxCount',
  'premiumBranchesMaxCount',
  // ─── 🆕 سعة شركات التأمين ───
  'freeInsuranceCompaniesMaxCount',
  'premiumInsuranceCompaniesMaxCount',
  // ─── برو ماكس ───
  'proMaxDailyLimit',
  'proMaxRecordsMaxCount',
  'proMaxPublicBookingDailyLimit',
  'proMaxPublicFormBookingDailyLimit',
  'proMaxSecretaryEntryRequestDailyLimit',
  'proMaxReadyPrescriptionDailyLimit',
  'proMaxMedicalReportDailyLimit',
  'proMaxInteractionToolDailyLimit',
  'proMaxPregnancyToolDailyLimit',
  'proMaxRenalToolDailyLimit',
  'proMaxPrescriptionPrintDailyLimit',
  'proMaxPrescriptionDownloadDailyLimit',
  'proMaxPrescriptionWhatsappDailyLimit',
  'proMaxReadyPrescriptionsMaxCount',
  'proMaxMedicationCustomizationsMaxCount',
  'proMaxBranchesMaxCount',
  'proMaxInsuranceCompaniesMaxCount',
];

export const DRUG_TOOLS_LIMIT_KEYS: Array<
  | 'freeInteractionToolDailyLimit'
  | 'premiumInteractionToolDailyLimit'
  | 'proMaxInteractionToolDailyLimit'
  | 'freeRenalToolDailyLimit'
  | 'premiumRenalToolDailyLimit'
  | 'proMaxRenalToolDailyLimit'
  | 'freePregnancyToolDailyLimit'
  | 'premiumPregnancyToolDailyLimit'
  | 'proMaxPregnancyToolDailyLimit'
> = [
    'freeInteractionToolDailyLimit',
    'premiumInteractionToolDailyLimit',
    'proMaxInteractionToolDailyLimit',
    'freeRenalToolDailyLimit',
    'premiumRenalToolDailyLimit',
    'proMaxRenalToolDailyLimit',
    'freePregnancyToolDailyLimit',
    'premiumPregnancyToolDailyLimit',
    'proMaxPregnancyToolDailyLimit',
  ];

export const LIMIT_MESSAGE_KEYS: MessageKey[] = [
  'freeAnalysisLimitMessage',
  'premiumAnalysisLimitMessage',
  // 🆕 رسائل الزر السريع "إضافة بدون تحليل"
  'freeQuickAddLimitMessage',
  'premiumQuickAddLimitMessage',
  'proMaxQuickAddLimitMessage',
  'freeRecordsCapacityMessage',
  'premiumRecordsCapacityMessage',
  'freePublicBookingLimitMessage',
  'premiumPublicBookingLimitMessage',
  'freePublicFormBookingLimitMessage',
  'premiumPublicFormBookingLimitMessage',
  'freeSecretaryEntryRequestLimitMessage',
  'premiumSecretaryEntryRequestLimitMessage',
  'freeReadyPrescriptionDailyLimitMessage',
  'premiumReadyPrescriptionDailyLimitMessage',
  'freeMedicalReportLimitMessage',
  'premiumMedicalReportLimitMessage',
  // ✂️ شيلنا رسائل الترجمة (2026-05) — الترجمة بقت جزء من الزرّين
  // ─── 🆕 الأزرار الذهبية (التداخلات + الحمل/الرضاعة) + الكلى ───
  'freeInteractionToolLimitMessage',
  'premiumInteractionToolLimitMessage',
  'freePregnancyToolLimitMessage',
  'premiumPregnancyToolLimitMessage',
  'freeRenalToolLimitMessage',
  'premiumRenalToolLimitMessage',
  // ─── 🆕 أزرار تصدير الروشتة ───
  'freePrescriptionPrintLimitMessage',
  'premiumPrescriptionPrintLimitMessage',
  'freePrescriptionDownloadLimitMessage',
  'premiumPrescriptionDownloadLimitMessage',
  'freePrescriptionWhatsappLimitMessage',
  'premiumPrescriptionWhatsappLimitMessage',
  'freeReadyPrescriptionsCapacityMessage',
  'premiumReadyPrescriptionsCapacityMessage',
  'freeMedicationCustomizationsCapacityMessage',
  'premiumMedicationCustomizationsCapacityMessage',
  // ─── سعة الفروع 🆕 ───
  'freeBranchesCapacityMessage',
  'premiumBranchesCapacityMessage',
  // ─── 🆕 سعة شركات التأمين ───
  'freeInsuranceCompaniesCapacityMessage',
  'premiumInsuranceCompaniesCapacityMessage',
  // ─── برو ماكس ───
  'proMaxAnalysisLimitMessage',
  'proMaxRecordsCapacityMessage',
  'proMaxPublicBookingLimitMessage',
  'proMaxPublicFormBookingLimitMessage',
  'proMaxSecretaryEntryRequestLimitMessage',
  'proMaxReadyPrescriptionDailyLimitMessage',
  'proMaxMedicalReportLimitMessage',
  'proMaxInteractionToolLimitMessage',
  'proMaxPregnancyToolLimitMessage',
  'proMaxRenalToolLimitMessage',
  'proMaxPrescriptionPrintLimitMessage',
  'proMaxPrescriptionDownloadLimitMessage',
  'proMaxPrescriptionWhatsappLimitMessage',
  'proMaxReadyPrescriptionsCapacityMessage',
  'proMaxMedicationCustomizationsCapacityMessage',
  'proMaxBranchesCapacityMessage',
  'proMaxInsuranceCompaniesCapacityMessage',
];

export const WHATSAPP_MESSAGE_KEYS: WhatsappMessageKey[] = [
  'freeAnalysisWhatsappMessage',
  'premiumAnalysisWhatsappMessage',
  // 🆕 رسائل واتساب الزر السريع "إضافة بدون تحليل"
  'freeQuickAddWhatsappMessage',
  'premiumQuickAddWhatsappMessage',
  'proMaxQuickAddWhatsappMessage',
  'freeRecordsCapacityWhatsappMessage',
  'premiumRecordsCapacityWhatsappMessage',
  'freePublicBookingWhatsappMessage',
  'premiumPublicBookingWhatsappMessage',
  'freePublicFormBookingWhatsappMessage',
  'premiumPublicFormBookingWhatsappMessage',
  'freeSecretaryEntryRequestWhatsappMessage',
  'premiumSecretaryEntryRequestWhatsappMessage',
  'freeReadyPrescriptionWhatsappMessage',
  'premiumReadyPrescriptionWhatsappMessage',
  'freeMedicalReportWhatsappMessage',
  'premiumMedicalReportWhatsappMessage',
  // ✂️ شيلنا رسائل واتساب الترجمة (2026-05)
  // ─── 🆕 الأزرار الذهبية + الكلى ───
  'freeInteractionToolWhatsappMessage',
  'premiumInteractionToolWhatsappMessage',
  'freePregnancyToolWhatsappMessage',
  'premiumPregnancyToolWhatsappMessage',
  'freeRenalToolWhatsappMessage',
  'premiumRenalToolWhatsappMessage',
  // ─── 🆕 أزرار تصدير الروشتة ───
  'freePrescriptionPrintWhatsappMessage',
  'premiumPrescriptionPrintWhatsappMessage',
  'freePrescriptionDownloadWhatsappMessage',
  'premiumPrescriptionDownloadWhatsappMessage',
  'freePrescriptionWhatsappWhatsappMessage',
  'premiumPrescriptionWhatsappWhatsappMessage',
  'freeReadyPrescriptionsCapacityWhatsappMessage',
  'premiumReadyPrescriptionsCapacityWhatsappMessage',
  'freeMedicationCustomizationsCapacityWhatsappMessage',
  'premiumMedicationCustomizationsCapacityWhatsappMessage',
  // ─── سعة الفروع 🆕 ───
  'freeBranchesCapacityWhatsappMessage',
  'premiumBranchesCapacityWhatsappMessage',
  // ─── 🆕 سعة شركات التأمين ───
  'freeInsuranceCompaniesCapacityWhatsappMessage',
  'premiumInsuranceCompaniesCapacityWhatsappMessage',
  // ─── برو ماكس ───
  'proMaxAnalysisWhatsappMessage',
  'proMaxRecordsCapacityWhatsappMessage',
  'proMaxPublicBookingWhatsappMessage',
  'proMaxPublicFormBookingWhatsappMessage',
  'proMaxSecretaryEntryRequestWhatsappMessage',
  'proMaxReadyPrescriptionWhatsappMessage',
  'proMaxMedicalReportWhatsappMessage',
  'proMaxInteractionToolWhatsappMessage',
  'proMaxPregnancyToolWhatsappMessage',
  'proMaxRenalToolWhatsappMessage',
  'proMaxPrescriptionPrintWhatsappMessage',
  'proMaxPrescriptionDownloadWhatsappMessage',
  'proMaxPrescriptionWhatsappWhatsappMessage',
  'proMaxReadyPrescriptionsCapacityWhatsappMessage',
  'proMaxMedicationCustomizationsCapacityWhatsappMessage',
  'proMaxBranchesCapacityWhatsappMessage',
  'proMaxInsuranceCompaniesCapacityWhatsappMessage',
];

const GROUPS: GroupConfig[] = [
  {
    id: 'analysis',
    title: 'إضافة إلى الروشتة والسجلات مع تحليل الحالة (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تحليل الحالة (مجاني)',
      whatsappPlaceholder: 'رسالة تحليل الحالة - مجاني',
      limitKey: 'freeDailyLimit',
      messageKey: 'freeAnalysisLimitMessage',
      whatsappMessageKey: 'freeAnalysisWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تحليل الحالة (برو)',
      whatsappPlaceholder: 'رسالة تحليل الحالة - برو',
      limitKey: 'premiumDailyLimit',
      messageKey: 'premiumAnalysisLimitMessage',
      whatsappMessageKey: 'premiumAnalysisWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تحليل الحالة (برو ماكس)',
      whatsappPlaceholder: 'رسالة تحليل الحالة - برو ماكس',
      limitKey: 'proMaxDailyLimit',
      messageKey: 'proMaxAnalysisLimitMessage',
      whatsappMessageKey: 'proMaxAnalysisWhatsappMessage',
    },
  },
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 (2026-05) إضافة إلى الروشتة والسجلات بدون تحليل (الزر السريع)
  // ─ كان مشترك على نفس عداد التحليل العميق فاستهلاك زر بيقفل التاني.
  // ─ اتفصل لعداد منفصل: كل زر له حد يومي خاص + رسائل خاصة لكل باقة.
  // ─ الزر ده أرخص في AI (ترجمة فقط) فمنطقي حده أعلى من التحليل العميق.
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'quick_add',
    title: 'إضافة إلى الروشتة والسجلات بدون تحليل (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الزر السريع (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة الزر السريع - مجاني',
      limitKey: 'freeQuickAddDailyLimit',
      messageKey: 'freeQuickAddLimitMessage',
      whatsappMessageKey: 'freeQuickAddWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الزر السريع (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة الزر السريع - برو',
      limitKey: 'premiumQuickAddDailyLimit',
      messageKey: 'premiumQuickAddLimitMessage',
      whatsappMessageKey: 'premiumQuickAddWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الزر السريع (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة الزر السريع - برو ماكس',
      limitKey: 'proMaxQuickAddDailyLimit',
      messageKey: 'proMaxQuickAddLimitMessage',
      whatsappMessageKey: 'proMaxQuickAddWhatsappMessage',
    },
  },
  // ✂️ شيلنا جروب الترجمة (2026-05) — الترجمة بقت جزء طبيعي من الزرّين،
  //   حد كل زر هو اللي بيتحكم فيها. كانت بتقفل الزرّين الاتنين لما حدها يخلص.
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 الأزرار الذهبية تحت الروشتة — التداخلات الدوائية
  // ─ كانت في قسم "أدوات الأدوية" المنفصل، اتنقلت 2026-04 لقسم "حدود الميزات"
  //   كحد يومي كامل (مع رسالة + واتساب) عشان الأدمن يقدر يضبطها زي باقي الميزات.
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'interaction_tool',
    title: 'فحص التداخلات الدوائية (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب التداخلات (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة فحص التداخلات - مجاني',
      limitKey: 'freeInteractionToolDailyLimit',
      messageKey: 'freeInteractionToolLimitMessage',
      whatsappMessageKey: 'freeInteractionToolWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب التداخلات (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة فحص التداخلات - برو',
      limitKey: 'premiumInteractionToolDailyLimit',
      messageKey: 'premiumInteractionToolLimitMessage',
      whatsappMessageKey: 'premiumInteractionToolWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب التداخلات (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة فحص التداخلات - برو ماكس',
      limitKey: 'proMaxInteractionToolDailyLimit',
      messageKey: 'proMaxInteractionToolLimitMessage',
      whatsappMessageKey: 'proMaxInteractionToolWhatsappMessage',
    },
  },
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 الأزرار الذهبية تحت الروشتة — فحص الحمل والرضاعة
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'pregnancy_tool',
    title: 'فحص الدواء أثناء الحمل والرضاعة (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الحمل والرضاعة (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة فحص الحمل والرضاعة - مجاني',
      limitKey: 'freePregnancyToolDailyLimit',
      messageKey: 'freePregnancyToolLimitMessage',
      whatsappMessageKey: 'freePregnancyToolWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الحمل والرضاعة (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة فحص الحمل والرضاعة - برو',
      limitKey: 'premiumPregnancyToolDailyLimit',
      messageKey: 'premiumPregnancyToolLimitMessage',
      whatsappMessageKey: 'premiumPregnancyToolWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الحمل والرضاعة (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة فحص الحمل والرضاعة - برو ماكس',
      limitKey: 'proMaxPregnancyToolDailyLimit',
      messageKey: 'proMaxPregnancyToolLimitMessage',
      whatsappMessageKey: 'proMaxPregnancyToolWhatsappMessage',
    },
  },
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 حاسبة جرعات الكلى — اتنقلت 2026-04 من قسم "أدوات الأدوية" المنفصل
  // ─ بقت زي التداخلات والحمل: حد يومي + رسالة + واتساب لكل باقة
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'renal_tool',
    title: 'حاسبة جرعات الكلى (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب جرعات الكلى (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة جرعات الكلى - مجاني',
      limitKey: 'freeRenalToolDailyLimit',
      messageKey: 'freeRenalToolLimitMessage',
      whatsappMessageKey: 'freeRenalToolWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب جرعات الكلى (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة جرعات الكلى - برو',
      limitKey: 'premiumRenalToolDailyLimit',
      messageKey: 'premiumRenalToolLimitMessage',
      whatsappMessageKey: 'premiumRenalToolWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب جرعات الكلى (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة جرعات الكلى - برو ماكس',
      limitKey: 'proMaxRenalToolDailyLimit',
      messageKey: 'proMaxRenalToolLimitMessage',
      whatsappMessageKey: 'proMaxRenalToolWhatsappMessage',
    },
  },
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 أزرار تصدير الروشتة (طباعة + تنزيل + واتساب) — حدود يومية 2026-04
  // ─ مفيش تكلفة AI، الحدود لتمييز الباقات وتشجيع الترقية ـ
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'prescription_print',
    title: 'طباعة الروشتة (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة الروشتة (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة الروشتة - مجاني',
      limitKey: 'freePrescriptionPrintDailyLimit',
      messageKey: 'freePrescriptionPrintLimitMessage',
      whatsappMessageKey: 'freePrescriptionPrintWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة الروشتة (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة الروشتة - برو',
      limitKey: 'premiumPrescriptionPrintDailyLimit',
      messageKey: 'premiumPrescriptionPrintLimitMessage',
      whatsappMessageKey: 'premiumPrescriptionPrintWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة الروشتة (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة الروشتة - برو ماكس',
      limitKey: 'proMaxPrescriptionPrintDailyLimit',
      messageKey: 'proMaxPrescriptionPrintLimitMessage',
      whatsappMessageKey: 'proMaxPrescriptionPrintWhatsappMessage',
    },
  },
  {
    id: 'prescription_download',
    title: 'تنزيل الروشتة (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تنزيل الروشتة (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة تنزيل الروشتة - مجاني',
      limitKey: 'freePrescriptionDownloadDailyLimit',
      messageKey: 'freePrescriptionDownloadLimitMessage',
      whatsappMessageKey: 'freePrescriptionDownloadWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تنزيل الروشتة (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة تنزيل الروشتة - برو',
      limitKey: 'premiumPrescriptionDownloadDailyLimit',
      messageKey: 'premiumPrescriptionDownloadLimitMessage',
      whatsappMessageKey: 'premiumPrescriptionDownloadWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب تنزيل الروشتة (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة تنزيل الروشتة - برو ماكس',
      limitKey: 'proMaxPrescriptionDownloadDailyLimit',
      messageKey: 'proMaxPrescriptionDownloadLimitMessage',
      whatsappMessageKey: 'proMaxPrescriptionDownloadWhatsappMessage',
    },
  },
  {
    id: 'prescription_whatsapp',
    title: 'إرسال الروشتة عبر واتساب (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إرسال الروشتة (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة إرسال الروشتة - مجاني',
      limitKey: 'freePrescriptionWhatsappDailyLimit',
      messageKey: 'freePrescriptionWhatsappLimitMessage',
      whatsappMessageKey: 'freePrescriptionWhatsappWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إرسال الروشتة (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة إرسال الروشتة - برو',
      limitKey: 'premiumPrescriptionWhatsappDailyLimit',
      messageKey: 'premiumPrescriptionWhatsappLimitMessage',
      whatsappMessageKey: 'premiumPrescriptionWhatsappWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إرسال الروشتة (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة إرسال الروشتة - برو ماكس',
      limitKey: 'proMaxPrescriptionWhatsappDailyLimit',
      messageKey: 'proMaxPrescriptionWhatsappLimitMessage',
      whatsappMessageKey: 'proMaxPrescriptionWhatsappWhatsappMessage',
    },
  },
  // ─ السجلات الطبية بقت "حد كلي" (سعة) — كانت "حد يومي" قبل 2026-04 ─
  // ─ السلوك زي الروشتات الجاهزة: مجموع كلي مخزّن، لما يخلص لازم يحذف ─
  {
    id: 'records_capacity',
    title: 'حفظ السجلات (حد كلي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة السجلات (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة السجلات - مجاني',
      limitKey: 'freeRecordsMaxCount',
      messageKey: 'freeRecordsCapacityMessage',
      whatsappMessageKey: 'freeRecordsCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة السجلات (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة السجلات - برو',
      limitKey: 'premiumRecordsMaxCount',
      messageKey: 'premiumRecordsCapacityMessage',
      whatsappMessageKey: 'premiumRecordsCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة السجلات (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة السجلات - برو ماكس',
      limitKey: 'proMaxRecordsMaxCount',
      messageKey: 'proMaxRecordsCapacityMessage',
      whatsappMessageKey: 'proMaxRecordsCapacityWhatsappMessage',
    },
  },
  {
    id: 'medical_report_print',
    title: 'طباعة تقرير طبي للحالة (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة التقرير (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة التقرير - مجاني',
      limitKey: 'freeMedicalReportDailyLimit',
      messageKey: 'freeMedicalReportLimitMessage',
      whatsappMessageKey: 'freeMedicalReportWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة التقرير (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة التقرير - برو',
      limitKey: 'premiumMedicalReportDailyLimit',
      messageKey: 'premiumMedicalReportLimitMessage',
      whatsappMessageKey: 'premiumMedicalReportWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب طباعة التقرير (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة طباعة التقرير - برو ماكس',
      limitKey: 'proMaxMedicalReportDailyLimit',
      messageKey: 'proMaxMedicalReportLimitMessage',
      whatsappMessageKey: 'proMaxMedicalReportWhatsappMessage',
    },
  },
  {
    id: 'public_booking',
    title: 'إضافة الموعد — صفحة المواعيد (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إضافة موعد (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لإضافة موعد - مجاني',
      limitKey: 'freePublicBookingDailyLimit',
      messageKey: 'freePublicBookingLimitMessage',
      whatsappMessageKey: 'freePublicBookingWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إضافة موعد (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لإضافة موعد - برو',
      limitKey: 'premiumPublicBookingDailyLimit',
      messageKey: 'premiumPublicBookingLimitMessage',
      whatsappMessageKey: 'premiumPublicBookingWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب إضافة موعد (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لإضافة موعد - برو ماكس',
      limitKey: 'proMaxPublicBookingDailyLimit',
      messageKey: 'proMaxPublicBookingLimitMessage',
      whatsappMessageKey: 'proMaxPublicBookingWhatsappMessage',
    },
  },
  {
    id: 'secretary_request',
    title: 'إرسال إلى الطبيب من السكرتارية (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب ارسال الموعد للطبيب (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لارسال الموعد للطبيب - مجاني',
      limitKey: 'freeSecretaryEntryRequestDailyLimit',
      messageKey: 'freeSecretaryEntryRequestLimitMessage',
      whatsappMessageKey: 'freeSecretaryEntryRequestWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب ارسال الموعد للطبيب (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لارسال الموعد للطبيب - برو',
      limitKey: 'premiumSecretaryEntryRequestDailyLimit',
      messageKey: 'premiumSecretaryEntryRequestLimitMessage',
      whatsappMessageKey: 'premiumSecretaryEntryRequestWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب ارسال الموعد للطبيب (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لارسال الموعد للطبيب - برو ماكس',
      limitKey: 'proMaxSecretaryEntryRequestDailyLimit',
      messageKey: 'proMaxSecretaryEntryRequestLimitMessage',
      whatsappMessageKey: 'proMaxSecretaryEntryRequestWhatsappMessage',
    },
  },
  {
    id: 'public_form_booking',
    title: 'حجز موعد من فورم الجمهور (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حجز فورم الجمهور (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لحجز فورم الجمهور - مجاني',
      limitKey: 'freePublicFormBookingDailyLimit',
      messageKey: 'freePublicFormBookingLimitMessage',
      whatsappMessageKey: 'freePublicFormBookingWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حجز فورم الجمهور (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لحجز فورم الجمهور - برو',
      limitKey: 'premiumPublicFormBookingDailyLimit',
      messageKey: 'premiumPublicFormBookingLimitMessage',
      whatsappMessageKey: 'premiumPublicFormBookingWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب حجز فورم الجمهور (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة واتساب لحجز فورم الجمهور - برو ماكس',
      limitKey: 'proMaxPublicFormBookingDailyLimit',
      messageKey: 'proMaxPublicFormBookingLimitMessage',
      whatsappMessageKey: 'proMaxPublicFormBookingWhatsappMessage',
    },
  },
  {
    id: 'ready_daily',
    title: 'حفظ روشتة جاهزة (حد يومي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الروشتات الجاهزة (مجاني)',
      whatsappPlaceholder: 'رسالة الروشتات الجاهزة - مجاني',
      limitKey: 'freeReadyPrescriptionDailyLimit',
      messageKey: 'freeReadyPrescriptionDailyLimitMessage',
      whatsappMessageKey: 'freeReadyPrescriptionWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الروشتات الجاهزة (برو)',
      whatsappPlaceholder: 'رسالة الروشتات الجاهزة - برو',
      limitKey: 'premiumReadyPrescriptionDailyLimit',
      messageKey: 'premiumReadyPrescriptionDailyLimitMessage',
      whatsappMessageKey: 'premiumReadyPrescriptionWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد اليومي',
      messageLabel: 'رسالة تجاوز الحد',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الروشتات الجاهزة (برو ماكس)',
      whatsappPlaceholder: 'رسالة الروشتات الجاهزة - برو ماكس',
      limitKey: 'proMaxReadyPrescriptionDailyLimit',
      messageKey: 'proMaxReadyPrescriptionDailyLimitMessage',
      whatsappMessageKey: 'proMaxReadyPrescriptionWhatsappMessage',
    },
  },
  {
    id: 'ready_capacity',
    title: 'عدد الروشتات الجاهزة المخزّنة (حد كلي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الروشتات (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الروشتات الجاهزة - مجاني',
      limitKey: 'freeReadyPrescriptionsMaxCount',
      messageKey: 'freeReadyPrescriptionsCapacityMessage',
      whatsappMessageKey: 'freeReadyPrescriptionsCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الروشتات (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الروشتات الجاهزة - برو',
      limitKey: 'premiumReadyPrescriptionsMaxCount',
      messageKey: 'premiumReadyPrescriptionsCapacityMessage',
      whatsappMessageKey: 'premiumReadyPrescriptionsCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الروشتات (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الروشتات الجاهزة - برو ماكس',
      limitKey: 'proMaxReadyPrescriptionsMaxCount',
      messageKey: 'proMaxReadyPrescriptionsCapacityMessage',
      whatsappMessageKey: 'proMaxReadyPrescriptionsCapacityWhatsappMessage',
    },
  },
  {
    id: 'medication_customizations_capacity',
    title: 'تخزين الأدوية المعدّلة (حد كلي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الأدوية المعدلة (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الأدوية المعدلة - مجاني',
      limitKey: 'freeMedicationCustomizationsMaxCount',
      messageKey: 'freeMedicationCustomizationsCapacityMessage',
      whatsappMessageKey: 'freeMedicationCustomizationsCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الأدوية المعدلة (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الأدوية المعدلة - برو',
      limitKey: 'premiumMedicationCustomizationsMaxCount',
      messageKey: 'premiumMedicationCustomizationsCapacityMessage',
      whatsappMessageKey: 'premiumMedicationCustomizationsCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب الأدوية المعدلة (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الأدوية المعدلة - برو ماكس',
      limitKey: 'proMaxMedicationCustomizationsMaxCount',
      messageKey: 'proMaxMedicationCustomizationsCapacityMessage',
      whatsappMessageKey: 'proMaxMedicationCustomizationsCapacityWhatsappMessage',
    },
  },
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 سعة الفروع (إعلان الطبيب) — ميزة بتفرّق بين الباقات
  // ─ مجاني = فرع واحد · برو = 3 فروع · برو ماكس = 10 فروع (افتراضياً)
  // ─ كان MAX_BRANCHES_PER_DOCTOR=5 hardcoded — دلوقتي ينقرأ من إعدادات الأدمن.
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'branches_capacity',
    title: 'عدد الفروع — إعلان الطبيب (حد كلي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الفروع (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الفروع - مجاني',
      limitKey: 'freeBranchesMaxCount',
      messageKey: 'freeBranchesCapacityMessage',
      whatsappMessageKey: 'freeBranchesCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الفروع (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الفروع - برو',
      limitKey: 'premiumBranchesMaxCount',
      messageKey: 'premiumBranchesCapacityMessage',
      whatsappMessageKey: 'premiumBranchesCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب سعة الفروع (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة سعة الفروع - برو ماكس',
      limitKey: 'proMaxBranchesMaxCount',
      messageKey: 'proMaxBranchesCapacityMessage',
      whatsappMessageKey: 'proMaxBranchesCapacityWhatsappMessage',
    },
  },
  // ═══════════════════════════════════════════════════════════════════════
  // 🆕 شركات التأمين (سعة كلية) — تمييز بين الباقات 2026-04
  // ─ مجاني = 2 شركة · برو = 10 · برو ماكس = 50 (افتراضياً)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'insurance_companies_capacity',
    title: 'عدد شركات التأمين (حد كلي)',
    free: {
      name: 'مجاني',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب شركات التأمين (مجاني)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة شركات التأمين - مجاني',
      limitKey: 'freeInsuranceCompaniesMaxCount',
      messageKey: 'freeInsuranceCompaniesCapacityMessage',
      whatsappMessageKey: 'freeInsuranceCompaniesCapacityWhatsappMessage',
    },
    premium: {
      name: 'برو',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب شركات التأمين (برو)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة شركات التأمين - برو',
      limitKey: 'premiumInsuranceCompaniesMaxCount',
      messageKey: 'premiumInsuranceCompaniesCapacityMessage',
      whatsappMessageKey: 'premiumInsuranceCompaniesCapacityWhatsappMessage',
    },
    proMax: {
      name: 'برو ماكس',
      limitLabel: 'الحد الأقصى',
      messageLabel: 'رسالة السعة القصوى',
      whatsappLabel: 'رسالة واتساب',
      whatsappPreviewLabel: 'معاينة واتساب شركات التأمين (برو ماكس)',
      messagePlaceholder: 'استخدم {limit} لإظهار الرقم',
      whatsappPlaceholder: 'رسالة شركات التأمين - برو ماكس',
      limitKey: 'proMaxInsuranceCompaniesMaxCount',
      messageKey: 'proMaxInsuranceCompaniesCapacityMessage',
      whatsappMessageKey: 'proMaxInsuranceCompaniesCapacityWhatsappMessage',
    },
  },
];

const END_GROUP_IDS = new Set(['public_booking', 'public_form_booking', 'secretary_request']);
export const ORDERED_GROUPS = [
  ...GROUPS.filter((group) => !END_GROUP_IDS.has(group.id)),
  ...GROUPS.filter((group) => END_GROUP_IDS.has(group.id)),
];

