import { Medication, Category } from '../../../types';

const fixed = (text: string) => (_w: number, _a: number) => text;

const BETAHISTINE_WARNINGS = ['يُستخدم بحذر مع قرحة المعدة والربو. قد يسبب اضطراب معدة/صداع.'];
const SEDATING_WARNINGS = ['قد يسبب نعاس/دوخة؛ تجنب القيادة والآلات إذا حدث نعاس.', 'تجنب الكحول.'];

export const VERTIGO_DRUGS: Medication[] = [
  // 1
  {
    id: 'amocerebral-plus-20-40mg-30-tabs-vert',
    name: 'amocerebral plus 20/40 mg 30 tabs.',
    genericName: 'cinnarizine + dimenhydrinate',
    concentration: '20/40mg',
    price: 36,
    matchKeywords: [
      'amocerebral plus',
      'اموسيريبرال',
      'amocerebral',
      'cinnarizine',
      'dimenhydrinate',
      'دوار',
      'دوخة',
      'دوار الحركة',
      'motion sickness',
      'vertigo',
      'dizziness',
      'nausea',
      'غثيان',
      '#vertigo',
      '#motion_sickness',
    ],
    usage: 'لعلاج الدوخة/الدوار ودوار الحركة مع الغثيان (سيناريزين + ديمينهيدرينات).',
    timing: 'كل ٨ ساعات بعد الأكل – حتى ٤ أسابيع',
    category: Category.VERTIGO,
    form: 'Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص واحد ٣ مرات يومياً بعد الأكل (حد أقصى ٣ أقراص/يوم) – لمدة قصيرة حتى ٤ أسابيع.'),
    warnings: SEDATING_WARNINGS,
  },

  // 2
  {
    id: 'betaserc-16mg-60-tab-vert',
    name: 'betaserc 16mg 60 tab',
    genericName: 'betahistine dihydrochloride',
    concentration: '16mg',
    price: 219,
    matchKeywords: ['betaserc 16', 'betaserc', 'بيتاسيرك', 'betahistine 16', 'betahistine', 'meniere', 'ménière', 'tinnitus', 'طنين', 'دوار', 'dizziness', 'inner ear', '#vertigo'],
    usage: 'لتخفيف نوبات الدوار المرتبطة باضطرابات الأذن الداخلية (مثل منيير) وقد يفيد لطنين الأذن المصاحب.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٦ مجم ٣ مرات يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) أو ٢٤ مجم مرتين يومياً مع الطعام – لمدة ٢–٣ أشهر مع تقييم الاستجابة.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 3
  {
    id: 'dramenex-50mg-20-tabs-vert',
    name: 'dramenex 50mg 20 tabs.',
    genericName: 'dimenhydrinate',
    concentration: '50mg',
    price: 28,
    matchKeywords: ['dramenex 50', 'dramenex', 'درامينكس', 'dimenhydrinate 50', 'dimenhydrinate', 'motion sickness', 'دوار سفر', 'دوار الحركة', 'غثيان', 'قيء', 'nausea', 'vomiting', '#motion_sickness', '#vertigo'],
    usage: 'لعلاج دوار الحركة والغثيان/القيء المرتبط بالدوخة (ديمينهيدرينات).',
    timing: 'كل ٤–٦ ساعات عند الحاجة بدون اعتبار للأكل – ١–٢ يوم',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 72,
    maxAgeMonths: 1200,
    minWeight: 20,
    maxWeight: 250,
    calculationRule: fixed(
      'البالغون: قرص ٥٠ مجم كل ٤–٦ ساعات عند الحاجة بدون اعتبار للأكل (حد أقصى ٤٠٠ مجم/يوم). الأطفال ٦–١١ سنة: ٢٥–٥٠ مجم كل ٦–٨ ساعات (حد أقصى ١٥٠ مجم/يوم) – لمدة ١–٢ يوم.'
    ),
    warnings: SEDATING_WARNINGS,
  },

  // 4
  {
    id: 'sulpepta-25mg-30-tabs-vert',
    name: 'sulpepta 25 mg 30 tabs.',
    genericName: 'levosulpiride',
    concentration: '25mg',
    price: 54,
    matchKeywords: ['sulpepta 25', 'sulpepta', 'سولبيبتا', 'levosulpiride 25', 'levosulpiride', 'دوخة', 'دوخة نفسية', 'functional dizziness', 'dizziness anxiety', 'nausea', 'غثيان', '#antiemetic'],
    usage: 'قد يساعد في حالات الغثيان/الدوخة المرتبطة بعامل وظيفي/عسر هضم.',
    timing: 'كل ٨ ساعات قبل الأكل – ٢–٤ أسابيع',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٥ مجم ٣ مرات يومياً قبل الأكل. في الحالات الخفيفة: ٢٥ مجم مرتين يومياً قبل الأكل – لمدة ٢–٤ أسابيع.'),
    warnings: ['قد يسبب ارتفاع هرمون اللبن (hyperprolactinemia).', 'قد يسبب أعراضاً خارج هرمية نادرة.'],
  },

  // 5
  {
    id: 'verserc-24mg-30-tab-vert',
    name: 'verserc 24mg 30 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '24mg',
    price: 90,
    matchKeywords: ['verserc 24', 'verserc', 'فيرسيرك ٢٤', 'betahistine 24', 'betahistine', 'meniere', 'tinnitus', 'طنين', 'دوار', 'dizziness', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار المرتبط باضطرابات الأذن الداخلية وقد يفيد لطنين الأذن المصاحب.',
    timing: 'كل ١٢ ساعة مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٤ مجم مرتين يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر مع تقييم الاستجابة.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 6
  {
    id: 'betaserc-24mg-40-tabs-vert',
    name: 'betaserc 24mg 40 tabs',
    genericName: 'betahistine dihydrochloride',
    concentration: '24mg',
    price: 218,
    matchKeywords: ['betaserc 24', 'betaserc', 'بيتاسيرك ٢٤', 'betahistine 24', 'betahistine', 'meniere', 'tinnitus', 'طنين', 'دوار', 'dizziness', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار المرتبط باضطرابات الأذن الداخلية وقد يفيد لطنين الأذن المصاحب.',
    timing: 'كل ١٢ ساعة مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٤ مجم مرتين يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 7
  {
    id: 'steadyfutal-24mg-20-tabs-vert',
    name: 'steadyfutal 24 mg 20 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '24mg',
    price: 72,
    matchKeywords: ['steadyfutal 24 20', 'steadyfutal', 'ستيديفيوتال', 'betahistine 24', 'betahistine', 'دوار', 'عدم اتزان', 'imbalance', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار وعدم الاتزان المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ١٢ ساعة مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٤ مجم مرتين يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 8
  {
    id: 'microserc-24mg-20-tab-vert',
    name: 'microserc 24mg 20 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '24mg',
    price: 68,
    matchKeywords: ['microserc 24', 'microserc', 'ميكروسيرك', 'betahistine 24', 'betahistine', 'دوار', 'طنين', 'tinnitus', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار المرتبط باضطرابات الأذن الداخلية وقد يفيد لطنين الأذن المصاحب.',
    timing: 'كل ١٢ ساعة مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٤ مجم مرتين يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 9
  {
    id: 'verserc-16mg-30-tab-vert',
    name: 'verserc 16mg 30 tab',
    genericName: 'betahistine dihydrochloride',
    concentration: '16mg',
    price: 87,
    matchKeywords: ['verserc 16', 'verserc', 'فيرسيرك ١٦', 'betahistine 16', 'betahistine', 'دوار', 'طنين', 'tinnitus', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار المرتبط باضطرابات الأذن الداخلية وقد يفيد لطنين الأذن المصاحب.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٦ مجم ٣ مرات يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 10
  {
    id: 'steadyfutal-24mg-40-tabs-vert',
    name: 'steadyfutal 24 mg 40 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '24mg',
    price: 129,
    matchKeywords: ['steadyfutal 24 40', 'steadyfutal', 'ستيديفيوتال ٤٠', 'betahistine 24', 'betahistine', 'دوار', 'عدم اتزان', 'imbalance', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار وعدم الاتزان المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ١٢ ساعة مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٤ مجم مرتين يومياً مع الطعام – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 11
  {
    id: 'topmode-50mg-20-caps-vert',
    name: 'topmode 50mg 20 caps.',
    genericName: 'sulpiride',
    concentration: '50mg',
    price: 28.5,
    matchKeywords: ['topmode 50', 'topmode', 'توبمود', 'سولبيريد', 'sulpiride 50', 'sulpiride', 'دوخة', 'دوخة نفسية', 'functional dizziness', 'dizziness'],
    usage: 'قد يساعد في بعض حالات الدوخة/الغثيان المرتبطة بعامل وظيفي/نفسي.',
    timing: 'كل ٨–١٢ ساعة بدون اعتبار للأكل – ٢–٤ أسابيع',
    category: Category.VERTIGO,
    form: 'Capsule',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('كبسولة ٥٠ مجم مرتين يومياً بدون اعتبار للأكل، ويمكن زيادتها إلى ٥٠ مجم ٣ مرات يومياً (حد أقصى ١٥٠ مجم/يوم) – لمدة ٢–٤ أسابيع.'),
    warnings: ['قد يسبب ارتفاع هرمون اللبن.', 'قد يسبب نعاساً لدى بعض المرضى.'],
  },

  // 13
  {
    id: 'steadyfutal-16mg-60-tab-vert',
    name: 'steadyfutal 16mg 60 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '16mg',
    price: 120,
    matchKeywords: ['steadyfutal 16 60', 'steadyfutal', 'ستيديفيوتال ١٦ ٦٠', 'betahistine 16', 'betahistine', 'دوار', 'dizziness', 'طنين', 'tinnitus', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار المرتبط باضطرابات الأذن الداخلية وقد يفيد لطنين الأذن المصاحب.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٦ مجم ٣ مرات يومياً مع الطعام (إجمالي ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 14
  {
    id: 'betaserc-8mg-100-tab-vert',
    name: 'betaserc 8mg 100 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '8mg',
    price: 144,
    matchKeywords: ['betaserc 8', 'betaserc', 'بيتاسيرك ٨', 'betahistine 8', 'betahistine', 'دوار', 'dizziness', 'طنين', 'tinnitus', 'meniere', 'ménière', '#vertigo'],
    usage: 'بيتاهيستين بتركيز ٨ مجم لتخفيف الدوار/طنين الأذن المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٨ مجم ٣ مرات يومياً مع الطعام، ويمكن الزيادة إلى ١٦ مجم ٣ مرات يومياً (حد أقصى ٤٨ مجم/يوم) – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 15
  {
    id: 'histotec-24mg-20-fc-tabs-vert',
    name: 'histotec 24mg 20 f.c. tabs.',
    genericName: 'betahistine dihydrochloride',
    concentration: '24mg',
    price: 52,
    matchKeywords: ['histotec 24', 'histotec', 'هيستوتك', 'betahistine 24', 'betahistine', 'دوار', 'عدم اتزان', 'imbalance', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار وعدم الاتزان المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ١٢ ساعة مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Film-coated Tablets',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٢٤ مجم مرتين يومياً مع الطعام – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 16
  {
    id: 'microserc-16mg-20-tab-vert',
    name: 'microserc 16mg 20 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '16mg',
    price: 30,
    matchKeywords: ['microserc 16', 'microserc', 'ميكروسيرك ١٦', 'betahistine 16', 'betahistine', 'دوار', 'dizziness', 'طنين', 'tinnitus', '#vertigo'],
    usage: 'بيتاهيستين ١٦ مجم لتخفيف الدوار/طنين الأذن المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٦ مجم ٣ مرات يومياً مع الطعام – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 18
  {
    id: 'steadyfutal-16mg-20-tab-vert',
    name: 'steadyfutal 16mg 20 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '16mg',
    price: 40,
    matchKeywords: ['steadyfutal 16 20', 'steadyfutal', 'ستيديفيوتال ١٦ ٢٠', 'betahistine 16', 'betahistine', 'دوار', 'عدم اتزان', 'imbalance', '#vertigo'],
    usage: 'بيتاهيستين لتخفيف الدوار وعدم الاتزان المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ١٦ مجم ٣ مرات يومياً مع الطعام – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },

  // 19
  {
    id: 'steadyfutal-8mg-30-tab-vert',
    name: 'steadyfutal 8mg 30 tab.',
    genericName: 'betahistine dihydrochloride',
    concentration: '8mg',
    price: 36,
    matchKeywords: ['steadyfutal 8 30', 'steadyfutal', 'ستيديفيوتال ٨ ٣٠', 'betahistine 8', 'betahistine', 'دوار', 'dizziness', 'طنين', 'tinnitus', '#vertigo'],
    usage: 'بيتاهيستين ٨ مجم لتخفيف الدوار/طنين الأذن المرتبط باضطرابات الأذن الداخلية.',
    timing: 'كل ٨ ساعات مع الأكل – ٢–٣ أشهر',
    category: Category.VERTIGO,
    form: 'Tablet',
    minAgeMonths: 216,
    maxAgeMonths: 1200,
    minWeight: 40,
    maxWeight: 250,
    calculationRule: fixed('قرص ٨ مجم ٣ مرات يومياً مع الطعام – لمدة ٢–٣ أشهر.'),
    warnings: BETAHISTINE_WARNINGS,
  },
];
